### ISSUE TITLE
Enable HTTPS quit with error

### ISSUE THREAD

**Issue by BodoWitcha** [nextcloud/nextcloud-snap#100]
As reported by several members and suggested  to report this issue here by [oparoz](https://help.nextcloud.com/users/oparoz)  in the [forum] (https://help.nextcloud.com/t/enable-https-quit-with-error/4114) when using Letsincrypt as described in Nextcloud Wiki [Enabling HTTPS (SSLS, TLS)] (https://github.com/nextcloud/nextcloud-snap/wiki/Enabling-HTTPS-(SSLS,-TLS)) fails with

`ls: cannot access '/var/snap/nextcloud/48/certs/certbot/config/live': No such file or directory`

or

 `ls: cannot access '/var/snap/nextcloud/99/certs/certbot/config/live': No such file or directory`

**Comment by solick** [comment]
Same problem here

**Comment by kyrofa** [comment]
Thanks for the bug report! Which version of the snap are you using (the version shown in `snap list`)? Please also provide the command run as well as the complete command output (please mask sensitive values).

**Comment by BodoWitcha** [comment]
solick2u reported in the forum:

> There has been an update for the snap today can you check if your snap has been updated?

I used the `sudo snap refresh` command, which resulted in the refresh with a 135 MB file.

Then I read  kyrofa request of the snap version, which it is updated of the above refresh command.
The result now is:
```
ubuntu@ubuntu-standard:~$ snap list
Name         Version      Rev  Developer  Notes
nextcloud    10.0.1snap1  128  nextcloud  -
ubuntu-core  16.04.1      424  canonical  -

```

After a reboot I re-entered the `sudo nextcloud.enable-https -d` command resulting in:

```
ubuntu@ubuntu-standard:~$ sudo nextcloud.enable-https -d
[sudo] password for ubuntu:
In order for Let's Encrypt to verify that you actually own the domain for
which you're requesting a certificate, there are a number of requirements
of which you need to be aware:

1. In order to register with the Let's Encrypt ACME server, you must agree
   to the currently-in-effect Subscriber Agreement located here:

       https://letsencrypt.org/repository/

   By continuing to use this tool you agree to these terms. Please cancel
   now if otherwise.

2. You must have the domain name(s) for which you want certificates
   pointing at the external IP address of this machine.

3. Both ports 80 and 443 on the external IP address of this machine must
   point to this machine (e.g. port forwarding might need to be setup on
   your router).

Have you met these requirements? (y/n) y
Please enter an email address (for urgent notices or key recovery): xxx@xxxxxxx.xxx
Please enter your domain name(s) (space-separated): xxxxxxxx.yyyyyy.com
Attempting to obtain certificates... done
Looks like you're ready for HTTPS!
```
Looks ok, but after the command to enable HTTPS I got:

```
ubuntu@ubuntu-standard:~$ sudo nextcloud.enable-https
In order for Let's Encrypt to verify that you actually own the domain for
which you're requesting a certificate, there are a number of requirements
of which you need to be aware:

1. In order to register with the Let's Encrypt ACME server, you must agree
   to the currently-in-effect Subscriber Agreement located here:

       https://letsencrypt.org/repository/

   By continuing to use this tool you agree to these terms. Please cancel
   now if otherwise.

2. You must have the domain name(s) for which you want certificates
   pointing at the external IP address of this machine.

3. Both ports 80 and 443 on the external IP address of this machine must
   point to this machine (e.g. port forwarding might need to be setup on
   your router).

Have you met these requirements? (y/n) y
Please enter an email address (for urgent notices or key recovery): xxx@xxxxxxx.xxx
Please enter your domain name(s) (space-separated):  xxxxxxxx.yyyyyy.com
Attempting to obtain certificates... error running certbot:

Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for benwniewold.dlinkddns.com
Using the webroot path /var/snap/nextcloud/current/certs/certbot for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Generating key (4096 bits): /var/snap/nextcloud/current/certs/certbot/config/keys/0007_key-certbot.pem
Creating CSR: /var/snap/nextcloud/current/certs/certbot/config/csr/0007_csr-certbot.pem
An unexpected error occurred:
There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for: dlinkddns.com
Please see the logfiles in /var/snap/nextcloud/current/certs/certbot/logs for more details.
```

But this is different issue. I have to wait another week before I can retry this domain.

**Comment by kyrofa** [comment]
Try `$ sudo nextcloud.enable-https -t` to obtain a cert from Let's Encrypt's staging server (whose limit is much much higher). It won't be signed by a third-party recognized by your browser, but it'll be coming from Let's Encrypt so you can test out the flow.

Note that this bug sounds like #74, which was fixed in the v10.0.1snap1, so hopefully you won't be seeing this again now that you've updated.

**Comment by BodoWitcha** [comment]
To avoid any issues caused by my inexperience with linux I have restarted the installation from the original SD image. After the installation and all updates && upgrades (including snap) the status is:
```
ubuntu@ubuntu-standard:~$ snap list
Name         Version      Rev  Developer  Notes
nextcloud    10.0.1snap1  128  nextcloud  -
ubuntu-core  16.04.1      424  canonical  -
```
The Enable HTTPS performed with the command :
`sudo nextcloud.enable-https -d`
succes.

The test command:
`sudo nextcloud.enable-https -t`
ended with:
`2016-10-16 09:22:31,578:DEBUG:certbot.reporter:Reporting to user: Congratulations! Your certificate and chain have been saved at /var/snap/nextcloud/current/certs/certbot/config/live/bniewold.dlinkddns.com/fullchain.pem. Your cert will expire on 2017-01-14. To obtain a new or tweaked version of this certificate in the future, simply run certbot again. To non-interactively renew *all* of your certificates, run "certbot renew"`

From my point of view this issue can be closed.
Now wait for another week to enable LetsEncrypt signed certificate.

**Comment by kyrofa** [comment]
Thanks @BodoWitcha. I'm going to go ahead and close this, then. Please feel free to re-open if there's still an issue.

**Comment by lindhe** [comment]
I'm currently at 11.0.0snap3 and am experiencing this issue. Any ideas?
