### ISSUE TITLE
Add MOSH (mobile shell) as a part of the default package/snap

### ISSUE THREAD

**Issue by joltdude** [nextcloud/nextcloud-snap#101]
I'd like to see MOSH added as part of the default snap, esp as apt-get is eventually going to go away...
https://mosh.org/

**Comment by kyrofa** [comment]
This isn't something that belongs in the Nextcloud snap-- it would be snapped on its own.

**Comment by joltdude** [comment]
Requiring additional snaps for base features.. Brilliant. Remember apt get will no longer work eventually.. Not sure why I'm even bothering suggesting anything

**Comment by kyrofa** [comment]
I'm not sure what you think this project is. It's not the "nextcloud box" project. It's the Nextcloud snap, which has thousands of users, some of which are using the Nextcloud box, and some of which will use Ubuntu Core once it's complete. Not all of those users will want MOSH bundled in. If you think MOSH would be useful on the Nextcloud Box (which will eventually be using Ubuntu Core), then it should be its own snap, and installed on the box alongside Nextcloud.
