### ISSUE TITLE
Error:There are no commands defined in the "config:system" namespace

### ISSUE THREAD

**Issue by yoooloo16** [nextcloud/nextcloud-snap#1015]
Nextcloud's automatic hostname detection fail when behind a proxy，I am notice it redirecting incorrectly.I do “sudo nextcloud.occ config:system:set overwritehost --value="example.com:81"”，but Error:There are no commands defined in the "config:system" namespace,why Error?

**Comment by kyrofa** [comment]
Have you created an admin account, etc? Can I see the output of the following three commands, please?

1. `snap list nextcloud`
2. `sudo nextcloud.occ status`
3. `sudo nextcloud.occ list`

**Comment by yoooloo16** [comment]
jiashan@jiashan:~$ snap list nextcloud
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  15.0.8snap2  13453  stable    nextcloud✓  -
jiashan@jiashan:~$ sudo nextcloud.occ status
[sudo] password for jiashan: 
Nextcloud is not installed - only a limited number of commands are available
  - installed: false
  - version: 15.0.8.1
  - versionstring: 15.0.8
  - edition: 
jiashan@jiashan:~$ sudo nextcloud.occ list
Nextcloud is not installed - only a limited number of commands are available
Nextcloud 15.0.8

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-warnings     Skip global warnings, show command output only
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  check                 check dependencies of the server environment
  help                  Displays help for a command
  list                  Lists commands
  status                show some status information
 app
  app:check-code        check code to be compliant
 integrity
  integrity:check-app   Check integrity of an app using a signature.
  integrity:check-core  Check integrity of core code using a signature.
  integrity:sign-app    Signs an app using a private key.
  integrity:sign-core   Sign core using a private key.
 l10n
  l10n:createjs         Create javascript translation files for a given app
 maintenance
  maintenance:install   install Nextcloud
jiashan@jiashan:~$

**Comment by yoooloo16** [comment]
I want to install https, I want to "nextcloud. enable - HTTPS lets - encrypt", but no, my 80 port is occupied, I set up 81 port.

**Comment by kyrofa** [comment]
Ah, looks like you haven't created an admin account etc. for Nextcloud yet. You can do either do it by visiting it in your browser, or straight from the terminal with `sudo nextcloud.manual-install <username> <password>`.

**Comment by yoooloo16** [comment]
it is ervery good，but  error:https.I set up 81 port,way error


jiashan@jiashan:~$ sudo nextcloud.enable-https lets-encrypt
In order for Let's Encrypt to verify that you actually own the
domain(s) for which you're requesting a certificate, there are a
number of requirements of which you need to be aware:

1. In order to register with the Let's Encrypt ACME server, you must
   agree to the currently-in-effect Subscriber Agreement located
   here:

       https://letsencrypt.org/repository/

   By continuing to use this tool you agree to these terms. Please
   cancel now if otherwise.

2. You must have the domain name(s) for which you want certificates
   pointing at the external IP address of this machine.

3. Both ports 80 and 443 on the external IP address of this machine
   must point to this machine (e.g. port forwarding might need to be
   setup on your router).

Have you met these requirements? (y/n) y
Please enter an email address (for urgent notices or key recovery): 55041050@qq.com
Please enter your domain name(s) (space-separated): yun.jscig.com:81
Attempting to obtain certificates... error running certbot:

Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for yun.jscig.com
Using the webroot path /var/snap/nextcloud/current/certs/certbot for all unmatched domains.
Waiting for verification...
Challenge failed for domain yun.jscig.com
http-01 challenge for yun.jscig.com
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: yun.jscig.com
   Type:   connection
   Detail: Fetching
   http://yun.jscig.com/.well-known/acme-challenge/GZHo9t2QtEcbL6TlJwh1QgsB3P1xR_AMDaHLR7LwOEg:
   Timeout during connect (likely firewall problem)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

**Comment by yoooloo16** [comment]
To fix these errors, please make sure that your domain name was
entered correctly and the DNS A/AAAA record(s) for that domain
contain(s) the right IP address.  why??  
http://yun.jscig.com:81/    
it is ok.

**Comment by yoooloo16** [comment]
i do "sudo nextcloud.occ config:system:set overwritehost --value="example.com:81""

**Comment by kyrofa** [comment]
Please read [this section of the README](https://github.com/nextcloud/nextcloud-snap#httphttps-port-configuration). To quote:

> **Note:** Let's Encrypt will expect that Nextcloud is exposed on ports 80 and 443. If you change ports and don't put Nextcloud behind a proxy such that ports 80 and 443 are sent to Nextcloud for that domain name, Let's Encrypt will be unable to verify ownership of your domain and will not grant certificates.

**Comment by tromlet** [comment]
> Ah, looks like you haven't created an admin account etc. for Nextcloud yet. You can do either do it by visiting it in your browser, or straight from the terminal with `sudo nextcloud.manual-install <username> <password>`. Once you do that, more commands (including the ability to set system config) will become available.

might be helpful for this to be documented in the install section or the readme, just sayin'...

**Comment by kyrofa** [comment]
Hey, I didn't invent that bonkers behavior, that's native Nextcloud :) . You can always refer to its documentation.
