### ISSUE TITLE
Fonts incorrect

### ISSUE THREAD

**Issue by tristone13th** [nextcloud/nextcloud-snap#1016]
After I installed snap version of nextcloud and launched this software, I got this:

![Screenshot from 2019-05-21 19-27-52](https://user-images.githubusercontent.com/17382962/58092415-98fae580-7bfe-11e9-8987-feb494f25712.png)

Although it will not affect the functions, but I'm a little OCD, so how could I fix it?

**Comment by kyrofa** [comment]
Is this the nextcloud client? This repo is for the server, I have no idea what's happening there.
