### ISSUE TITLE
ETA for stable version 16

### ISSUE THREAD

**Issue by TarSzator** [nextcloud/nextcloud-snap#1020]
Is there an estimated time of arrival for Version 16 of Nextcloud in the stable channel?

**Comment by pachulo** [comment]
Guess it will be when 16.0.2 is released, if they honor their ETA for E2E encryption app:
https://github.com/nextcloud/nextcloud-snap/pull/1002

**Comment by kyrofa** [comment]
Yeah they released v16 before core apps supported it. We don't want to push that out to everyone only to have their apps disabled! We're waiting for the apps to catch up.

**Comment by kyrofa** [comment]
Oh, I neglected to mention: you can always update before we push it to everyone by using the `16/candidate` channel:

    $ sudo snap refresh nextcloud --channel=16/candidate

As long as you know that there are reasons we don't consider it ready for the masses :) .

**Comment by kyrofa** [comment]
Since I believe this question has been answered, I'm going to close this issue in favor of #972.

**Comment by TarSzator** [comment]
Thanks a lot for all the good answers, that helped much
