### ISSUE TITLE
TLS 1.3 not supported

### ISSUE THREAD

**Issue by Guillaume99** [nextcloud/nextcloud-snap#1021]
TLS 1.3 is enabled since Apache 2.4.36 (https://github.com/apache/httpd/blob/2.4.36/CHANGES), so it should be available on this snap ...

version : Version : 15.0.8.1

**Comment by pachulo** [comment]
Well, it's not Apache HTTP only that has to support it. Guess we would be able to think about this when the snap is updated to core18 base: https://github.com/nextcloud/nextcloud-snap/issues/755
