### ISSUE TITLE
Moving data directory,Internal Server Error and apparmor profiles

### ISSUE THREAD

**Issue by palaroda** [nextcloud/nextcloud-snap#1024]
I have external storage mounted to /media/nextcloud. By default apparmor denies access to this folder and i get Internal Server Error similar to #741 issue.
Logs looks like this:

May 23 11:06:58 cloud kernel: [255431.083533] audit: type=1400 audit(1558598818.295:5976): apparmor=“DENIED” operation=“open” profile=“snap.nextcloud.php-fpm” name="/media/nextcloud/data/nextcloud.log" pid=26872 comm=“php-fpm” requested_mask=“ac” denied_mask=“ac” fsuid=0 ouid=0

I can change profile /var/lib/snapd/apparmor/profiles/snap.nextcloud.php-fpm 
addind something like:  

/media/nextcloud rw,
/media/nextcloud/** rw,

and nextcloud works fine.
But after each snap update apparmor replaces this profile and my changes are lost.
How to save my fixes in apparmor profiles and prevent them from changes on update?

**Comment by kyrofa** [comment]
Did you connect the `removable-media` plug?

**Comment by palaroda** [comment]
thanks. my mistake, i forgot this plug

**Comment by kyrofa** [comment]
Excellent, I'll go ahead and close this, then.

**Comment by huaKing** [comment]
root@yunxuan:/home/yunxuan# cat /snap/nextcloud/current/meta/snap.yaml
name: nextcloud
version: 19.0.3snap2
summary: Nextcloud Server - A safe home for all your data
description: |
  Access, share and protect your files, calendars, contacts, communication and
  more at home and in your enterprise.
apps:
  apache:
    command: bin/run-httpd -k start -DFOREGROUND
    stop-command: bin/httpd-wrapper -k stop
    daemon: simple
    restart-condition: always
    plugs:
    - network
    - network-bind
    - removable-media
    command-chain:
    - snap/command-chain/snapcraft-runner
  disable-https:
    command: bin/disable-https
    plugs:
    - network
    - network-bind
    command-chain:
    - snap/command-chain/snapcraft-runner
  enable-https:
    command: bin/enable-https
    plugs:
    - network
    - network-bind
    command-chain:
    - snap/command-chain/snapcraft-runner
  export:
    command: bin/export-data
    plugs:
    - network
    - network-bind
    - removable-media
    command-chain:
    - snap/command-chain/snapcraft-runner
  import:
    command: bin/import-data
    plugs:
    - network
    - network-bind
    - removable-media
    command-chain:
    - snap/command-chain/snapcraft-runner
  manual-install:
    command: bin/manual-install
    plugs:
    - network
    - network-bind
    - removable-media
    command-chain:
    - snap/command-chain/snapcraft-runner
  mdns-publisher:
    command: bin/delay-on-failure mdns-publisher nextcloud
    daemon: simple
    restart-condition: always
    plugs:
    - network
    - network-bind
    command-chain:
    - snap/command-chain/snapcraft-runner
  mysql:
    command: bin/start_mysql
    stop-command: support-files/mysql.server stop
    daemon: simple
    restart-condition: always
    plugs:
    - network
    - network-bind
    command-chain:
    - snap/command-chain/snapcraft-runner
  mysql-client:
    command: bin/run-mysql
    plugs:
    - network
    - network-bind
    command-chain:
    - snap/command-chain/snapcraft-runner
  mysqldump:
    command: bin/run-mysqldump
    plugs:
    - network
    - network-bind
    command-chain:
    - snap/command-chain/snapcraft-runner
  nextcloud-cron:
    command: bin/nextcloud-cron
    daemon: simple
    restart-condition: on-failure
    plugs:
    - network
    - network-bind
    - removable-media
    command-chain:
    - snap/command-chain/snapcraft-runner
  nextcloud-fixer:
    command: bin/nextcloud-fixer
    daemon: simple
    restart-condition: on-failure
    plugs:
    - network
    - network-bind
    - removable-media
    command-chain:
    - snap/command-chain/snapcraft-runner
  occ:
    command: bin/occ
    plugs:
    - network
    - network-bind
    - removable-media
    command-chain:
    - snap/command-chain/snapcraft-runner
  php-fpm:
    command: bin/start-php-fpm
    daemon: simple
    restart-condition: always
    plugs:
    - network
    - network-bind
    - network-observe
    - removable-media
    command-chain:
    - snap/command-chain/snapcraft-runner
  redis-server:
    command: bin/start-redis-server
    daemon: simple
    restart-condition: always
    plugs:
    - network
    - network-bind
    command-chain:
    - snap/command-chain/snapcraft-runner
  renew-certs:
    command: bin/renew-certs
    daemon: simple
    restart-condition: always
    plugs:
    - network
    - network-bind
    command-chain:
    - snap/command-chain/snapcraft-runner
architectures:
- amd64
assumes:
- command-chain
base: core18
confinement: strict
grade: stable
hooks:
  configure:
    plugs:
    - network
    - network-bind
    - removable-media
  pre-refresh:
    plugs:
    - network
    - network-bind
    - removable-media

**Comment by huaKing** [comment]
I use own data path: /mnt/md1/data . 
How to config?

**Comment by huaKing** [comment]
sudo snap connect nextcloud:removable-media ?

**Comment by kyrofa** [comment]
@huaKing this section in the [README](https://github.com/nextcloud/nextcloud-snap#removable-media) should explain it.
