### ISSUE TITLE
Nextcloud ignores Forwarded-For header

### ISSUE THREAD

**Issue by Bleuzen** [nextcloud/nextcloud-snap#1027]
Hi, I set up this nextcloud snap behind a nginx reverse proxy as described here:
https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy

My nginx configuration:
```
server {
        server_name <domain name>;

        location / {
                proxy_pass_header   Server;
                proxy_set_header    Host $host;
                proxy_set_header    X-Real-IP $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto $scheme;
                proxy_pass          http://127.0.0.1:81;
        }
}
```

The site works, nextcloud comes up at the address where I want it.

The ip gets forwarded as it should. I checkd this by temporarily replacing the line from
`proxy_pass          http://127.0.0.1:81;`
to
`proxy_pass          https://myip.is/;`
It shows my real ip (not the one of my proxy / 127.0.0.1), so everything should be fine, ip got forwarded corrrectly.

But Nextcloud seems to ignore this.
If someone tries to login multiple times and failed, it counts as brutforce attempt. Ok, but the problem is, that after someone did this, all users get the anti brutforce slowdown.

In my database:

`SELECT * FROM oc_bruteforce_attempts;`
```
+----+--------+------------+-----------+--------------+-----------------+
| id | action | occurred   | ip        | subnet       | metadata        |
+----+--------+------------+-----------+--------------+-----------------+
|  1 | login  | 1558725301 | 127.0.0.1 | 127.0.0.1/32 | {"user":"-"} |
|  2 | login  | 1558725303 | 127.0.0.1 | 127.0.0.1/32 | {"user":"-"} |
|  3 | login  | 1558725305 | 127.0.0.1 | 127.0.0.1/32 | {"user":"-"} |
|  4 | login  | 1558725307 | 127.0.0.1 | 127.0.0.1/32 | {"user":"-"} |
|  5 | login  | 1558725312 | 127.0.0.1 | 127.0.0.1/32 | {"user":"-"} |
|  6 | login  | 1558725319 | 127.0.0.1 | 127.0.0.1/32 | {"user":"-"} |
+----+--------+------------+-----------+--------------+-----------------+

```
you see that nextcloud put in 127.0.0.1 instead of the real attackers ip address. So this slows down all logins.

So Nextcloud always thinks it gets called from 127.0.0.1. How can I change this, I want it to get the users real ip.

**Comment by Bleuzen** [comment]
Ok I found the solution myself:
I had to add
```
  'trusted_proxies' => 
  array (
    0 => '127.0.0.1',
  ),
```
to my
`/var/snap/nextcloud/current/nextcloud/config/config.php`.

A note about this required config changed should make it into the wiki page.

**Comment by fireembler** [comment]
Hello, i'm having the same problem on the recent Nextcloud Snap behind an NGINX Reverse Proxy. forwarded_for headers are set, I tried several NGINX configurations as well as different Nextcloud settings including trusted_proxies, trusted_domains, overwriteprotocol, host, webroot. 

Any tips or help is welcome!
