### ISSUE TITLE
nextcloud.enable-https hangs on restarting the Apache web-server step.

### ISSUE THREAD

**Issue by bonsje** [nextcloud/nextcloud-snap#103]
Hi there, 

It seems that nextcloud.enable-https hangs on restarting the Apache web-server step. 

**My Environment**

Ubuntu Server 16.04.1 amd64 KVM VPS. 
1x dedicated ipv4 adres, not using firewall restrictions during install. 

Snapd version: 

```
snap    2.15.2ubuntu1
snapd   2.15.2ubuntu1
series  16
ubuntu  16.04

```

Installed snaps: 

```
Name         Version      Rev  Developer  Notes
nextcloud    10.0.1snap1  126  nextcloud  -
ubuntu-core  16.04.1      423  canonical  -
```

**nextcloud.enable-https step:**

When i try a dry run:

Everything seems ok, and there are no errors: 
```
root@vmi87797:~# nextcloud.enable-https -d
In order for Let's Encrypt to verify that you actually own the domain for
which you're requesting a certificate, there are a number of requirements
of which you need to be aware:

1. In order to register with the Let's Encrypt ACME server, you must agree
   to the currently-in-effect Subscriber Agreement located here:

       https://letsencrypt.org/repository/

   By continuing to use this tool you agree to these terms. Please cancel
   now if otherwise.

2. You must have the domain name(s) for which you want certificates
   pointing at the external IP address of this machine.

3. Both ports 80 and 443 on the external IP address of this machine must
   point to this machine (e.g. port forwarding might need to be setup on
   your router).

Have you met these requirements? (y/n) y
Please enter an email address (for urgent notices or key recovery): <my@email.com>
Please enter your domain name(s) (space-separated): <my domain>
Attempting to obtain certificates... done
Looks like you're ready for HTTPS!
```

But without the -d flag, it seems to be hanging on the Restarting apache... fase, 

```
root@vmi87797:~# nextcloud.enable-https   
In order for Let's Encrypt to verify that you actually own the domain for
which you're requesting a certificate, there are a number of requirements
of which you need to be aware:

1. In order to register with the Let's Encrypt ACME server, you must agree
   to the currently-in-effect Subscriber Agreement located here:

       https://letsencrypt.org/repository/

   By continuing to use this tool you agree to these terms. Please cancel
   now if otherwise.

2. You must have the domain name(s) for which you want certificates
   pointing at the external IP address of this machine.

3. Both ports 80 and 443 on the external IP address of this machine must
   point to this machine (e.g. port forwarding might need to be setup on
   your router).

Have you met these requirements? (y/n) y
Please enter an email address (for urgent notices or key recovery): <my@email.com>
Please enter your domain name(s) (space-separated): <my domain>
Attempting to obtain certificates... done
Restarting apache...
```

I waited for about 15 minutes and it was still stuck on that fase,
I rebooted my server, and it seems that the Certificate install was a success, everything worked as it should.  

I did not encounter this behavior on snap 9.0.54snap3 (last time i did a clean install via snap). 
I reinstalled the whole VPS with Ubuntu 16.04.1 server, to make sure it was not a weird kind of server issue on my side. 

For my atm not a big deal, it seems to work fine after a server reboot (and kill the script), but for new users this can be frustrating.  

If you need any information, please ask.  

I encountered this issue on 2 servers, with the same ubuntu version on amd64 but with different ipv4 address and domains.

**Comment by oparoz** [comment]
This could be a race condition. Did you try to generate the cert immediately after having installed the snap? It takes a while for Nextcloud to be ready the first time it's installed.

**Comment by thercast** [comment]
I encountered the same issue as well.  I waited to generate the cert until at least one hour after installing the snap on my digital ocean VPS running ubuntu 16.04.1.  I also did the dry run first and had no issues from that run.  Also happy to provide more info if that helps.

Installed snaps:

```
Name         Version      Rev  Developer  Notes
nextcloud    10.0.1snap1  126  nextcloud  -
ubuntu-core  16.04.1      423  canonical  -
```
snap version info:
```
snap    2.15.2ubuntu1
snapd   2.15.2ubuntu1
series  16
ubuntu  16.04
```

**Comment by bonsje** [comment]
> This could be a race condition. Did you try to generate the cert immediately after having installed the snap? It takes a while for Nextcloud to be ready the first time it's installed.

I waited more than 10 minutes when i generate the cert, i first checked if the nextcloud was running, i even created the administrator account first, to make sure everything went well. 

If you need any more info please ask.

**Comment by kyrofa** [comment]
Well that's annoying, sorry folks! I just revamped how this was done in 10.0.1snap1 as I noticed a hang as well. Not sure what's happening now. The time it happened to me Apache actually rebooted but the way the snap was waiting for it to come back was faulty, so a simple ctrl+c to get out of the wait loop was enough to get up and running (i.e. no reboot necessary). Can anyone verify that is still the case?

**Comment by bonsje** [comment]
In my case when i did a ctrl+c, and visited the nexcloud instance it was still running with a nonSSL config. 
Did a server reboot and the SSL config was loaded and worked perfectly. so my apache2 seems not being reloaded in my case. 

with the `sudo service snap.nextcloud.apache restart` command it should also worked instead of a reboot.

**Comment by kyrofa** [comment]
@bonsje good information, thank you. So Apache isn't actually dying, eh? Alright, I'll dig into this. And yes, simply restarting the Apache service is all that's needed at that point.

**Comment by kyrofa** [comment]
Ah, this is an issue with the migration for certificates made in previous versions of the snap. Apache is actually get restarted in a loop. I'll release a fix shortly.

**Comment by kyrofa** [comment]
Keep an eye out for v10.0.1snap2, things should start working again. Thanks for the bug!
