### ISSUE TITLE
"smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login"

### ISSUE THREAD

**Issue by EnricoSx** [nextcloud/nextcloud-snap#1032]
Thanks for your hard works :)
i try on ubuntu server 19.04 (Hyper-V)
`sudo snap install nextcloud --channel=16/candidate`
`sudo snap connect nextcloud:removable-media`
but i receive

> "smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login"

i install **smbclient** and **php-smbclient** then **reboot**, but nothing.
There is a way to fix it ? _Thanks_

**Comment by EnricoSx** [comment]
now i try mount with fstab, from ssh my user "enrico" access correctly, but not nextcloud

**Comment by pachulo** [comment]
That is expected: native support for SMB seems to be a little bit tricky and we still did not find time to make it work it for all the archs supported by the snap. More info here: https://github.com/nextcloud/nextcloud-snap/pull/585

The current workaround is what you already did, mount the share somewhere below /media and use it as a “normal” folder.
