### ISSUE TITLE
 I want to know where Apache 2.4 config is located?

### ISSUE THREAD

**Issue by yoooloo16** [nextcloud/nextcloud-snap#1033]
I want to know where Apache 2.4 config is located?

**Comment by yoooloo16** [comment]
Nextcloud, my internal network and 80 ports can connect to Nextcloud, the Internet can not connect to Nextcloud, I query 80 ports on Ubuntu 18.04, no listening, I want to know where Apache 2.4 config is located? How to modify it?

**Comment by kyrofa** [comment]
The fact that the snap uses Apache is an implementation detail; the config is not user-modifiable. If your internal network can connect to Nextcloud but the internet cannot, that's an issue in your routing setup, not the snap.
