### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by curiousclinician** [nextcloud/nextcloud-snap#1035]
Deploying this exactly as it is written does not work at all,  and very likely never did.

This is yet another developer who is so far into their work that they can't imagine that this is a new language for most of us... and they don't seem to have maintained this or responded to issues in some time.  So... I guess they're a  shitty developer who doesn't take down repos they don't maintain?

I've got better things to do.

CorbettMD out.

**Comment by kyrofa** [comment]
Uh. Okay.
