### ISSUE TITLE
Problem with Cronjob

### ISSUE THREAD

**Issue by Hofer-Julian** [nextcloud/nextcloud-snap#1039]
I set up a fresh nextcloud snap install with Ubuntu 18.04.2 LTS (GNU/Linux 4.14.120-160 armv7l) on Odroid HC2.

I noticed that nextcloud warned me that it there wasn't a cronjob running for over 3h so I executed `sudo snap set nextcloud nextcloud.cron-interval=40m` in the hope that this would change something. As far as I can see it executed two or three times and then stopped as well. I played this game three times until I decided to ask for help.

Output of `snap info core`:
```
name:      core
summary:   snapd runtime environment
publisher: Canonical✓
contact:   snaps@canonical.com
license:   unset
description: |
  The core runtime environment for snapd
type:         core
snap-id:      99T7MUlRhtI3U0QFgl5mXXESAiSwt776
tracking:     stable
refresh-date: 6 days ago, at 17:50 UTC
channels:
  stable:    16-2.39                   2019-05-22 (6961) 79MB -
  candidate: 16-2.39.1                 2019-06-04 (7124) 79MB -
  beta:      16-2.39.2                 2019-06-05 (7173) 79MB -
  edge:      16-2.39.2+git1333.c984d91 2019-06-07 (7183) 79MB -
installed:   16-2.39                              (6961) 79MB core
```
Output of `snap version`
```
snap    2.39
snapd   2.39
series  16
ubuntu  18.04
kernel  4.14.120-160
```

**Comment by kyrofa** [comment]
Can you please paste the output of [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)?

**Comment by Hofer-Julian** [comment]
I currently switched back to nextcloudpi because of this.

But I when I install the snap the next time, I will make sure to execute your script

**Comment by kyrofa** [comment]
Alright I'll go ahead and close this, then. Feel free to reopen in the future if necessary.
