### ISSUE TITLE
How External Storage Supports User Isolation？

### ISSUE THREAD

**Issue by chenzhikang** [nextcloud/nextcloud-snap#1043]
i installed nextcloud-snap of version 15.0.8.1; 
but my installed disk(sda2) capacity is not enough,so I extended another disk of sdb1 as the extend storage data directory;
when i configed of app"External storage support"，there is a serious problem that every one could see the same files of sdb1,so how to config of user isolation of files?

**Comment by peckeltw** [comment]
Same here, but with S3 configured as external storage. @chenzhikang you can limit access to the external storage by user or group, see [documentation](https://docs.nextcloud.com/server/15/admin_manual/configuration_files/external_storage/amazons3.html), but I agree this is not ultimately a good solution.
