### ISSUE TITLE
How to install ffmpeg?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-snap#1046]
I want to use the nextcloud video converter from the app store: https://apps.nextcloud.com/apps/video_converter
But it needs ffmpeg and is not installed in the snap. 
How can I do that?

**Comment by kyrofa** [comment]
I'm afraid this isn't really possible as far as I can tell. I expect the snap itself would need to bundle ffmpeg, which isn't something we can do. If you can tell the app where to look for ffmpeg, perhaps you can build ffmpeg and install it into `/var/snap/nextcloud/current/` or some other place the snap can read (since it can't access the ffmpeg installed on your host due to confinement).

**Comment by szaimen** [comment]
Because I do not know, if there is an option to configure the path where the app looks for ffmpeg, I created a new issue: https://github.com/PaulLereverend/NextcloudVideo_Converter/issues/18
When there was an option to configure the path, would a symbolic link to the normal installation path enough to get it working?

**Comment by kyrofa** [comment]
I'm afraid not-- confinement follows symlinks, as it were. If the snap doesn't have access to the linked file, the symlink won't be useful either. It doesn't sound like there's a good solution here, I'm sorry.

**Comment by kyrofa** [comment]
I'm going to go ahead and close this, but feel free to continue discussion here.

**Comment by dmfgaming** [comment]
I have ffmpeg installed in snap, but yet it says its not installed. You can install ffmpeg in snap by sudo snap install ffmpeg

but The converter is still giving me, need to install ffmpeg, so how do I fix this?

**Comment by kyrofa** [comment]
> sudo snap install ffmpeg

That just installs another snap containing ffmpeg; Nextcloud doesn't have access to it. My [comment above](https://github.com/nextcloud/nextcloud-snap/issues/1046#issuecomment-509676968) remains my only suggestion, I'm afraid.

**Comment by Jachhj-sc** [comment]
> I'm afraid this isn't really possible as far as I can tell. I expect the snap itself would need to bundle ffmpeg, which isn't something we can do. If you can tell the app where to look for ffmpeg, perhaps you can build ffmpeg and install it into `/var/snap/nextcloud/current/` or some other place the snap can read (since it can't access the ffmpeg installed on your host due to confinement).

Thanks installing it in the current folder and updating source code for the app to take my path instead of asking the system where it is, worked.

**Comment by shaman79** [comment]
Hello, can you be more specific on the instructions? I am trying to enable video support for Memories. Nextcloud was installed through snap. 
I would like to know where exactly you placed the ffmpeg binary and how did you changed the sources. Thank you.

**Comment by shaman79** [comment]
@kyrofa Can you be more specific on why you cannot bundle ffmpeg (and other common dependencies) in snaps? I find snap extremely limiting the NC capabilities, so there should be some good solution to this - maybe there could be some extra packages with the common dependencies or something like that.

**Comment by laurens94** [comment]
@shaman79 There's an open Pull Request awaiting approval: https://github.com/nextcloud-snap/nextcloud-snap/pull/2013
So it seems there might finally be a proper solution coming soon 🤞  In the comments you can find some more information regarding this issue.

**Comment by shaman79** [comment]
Cool. In the meantime this is how I solved it:
- Create `/var/snap/nextcloud/bin/` directory
- Google for ffmpeg static build (has included static libraries). I used https://johnvansickle.com/ffmpeg/
- Unpack ffmpeg and ffprobe into `/var/snap/nextcloud/bin/` 
- add/change following lines in `/var/snap/nextcloud/current/nextcloud/config/config.php` 
  'memories.ffmpeg_path' => '/var/snap/nextcloud/bin/ffmpeg',
  'memories.ffprobe_path' => '/var/snap/nextcloud/bin/ffprobe',
- run `nextcloud.occ memories:video-setup`

**Comment by szaimen** [comment]
I suppose this should be documented somewhere @kyrofa @pachulo ?

**Comment by mosin** [comment]
> Cool. In the meantime this is how I solved it:
> 
>     * Create `/var/snap/nextcloud/bin/` directory
> 
>     * Google for ffmpeg static build (has included static libraries). I used https://johnvansickle.com/ffmpeg/
> 
>     * Unpack ffmpeg and ffprobe into `/var/snap/nextcloud/bin/`
> 
>     * add/change following lines in `/var/snap/nextcloud/current/nextcloud/config/config.php`
>       'memories.ffmpeg_path' => '/var/snap/nextcloud/bin/ffmpeg',
>       'memories.ffprobe_path' => '/var/snap/nextcloud/bin/ffprobe',
> 
>     * run `nextcloud.occ memories:video-setup`

I get an error that 'There are no commands defined in the "memories" namespace.' when trying that. Did I put the memories lines in the wrong place?

**Comment by shaman79** [comment]
My instructions are specific for the Memories app. For general ffmpeg support in Nextcloud you migh need to add `'ffmpeg' => '/var/snap/nextcloud/bin/ffmpeg',` to your config, but I am not sure if and in which apps it works.

**Comment by kyrofa** [comment]
> Cool. In the meantime this is how I solved it:

Great solution! I wish that would work across the board, but @pachulo discovered that other apps require ffmpeg to be in the PATH.

**Comment by kyrofa** [comment]
Okay it might actually work across the board. Can someone try @shaman79's approach for the movies app, updating your config to [point it to the right place](https://github.com/nextcloud/server/blob/stable25/lib/private/Preview/Movie.php#L68)?

**Comment by laurens94** [comment]
> run `nextcloud.occ memories:video-setup`

@shaman79 May I ask what you chose when the setup asked the questions below:

> Do you want to enable transcoding and HLS? [Y/n]
> QSV is available. Do you want to enable it? [Y/n]

For me videos still don't have thumbnails and can't even play from the Memories app. Do you also need to change anything in the config regarding `enabledPreviewProviders`?

**Comment by shaman79** [comment]
I said yes to transcoding, I have no QSV available. Videos play nicely. No previews but I did not had preview generation enabled for movies. Will try later.

**Comment by shaman79** [comment]
@kyrofa Setting `movieBinary` did not enabled previews for Memories. For the record, I did enabled preview generation for Movies in config `enablePreviewProviders`.

**Comment by Jachhj-sc** [comment]
ok, so i got as far as *@shaman79*  so i can run videos with memories but i have no preview.
However I found that in "https://github.com/nextcloud/server/blob/master/lib/private/PreviewManager.php"
the following code is responsible for getting the binary path.
```
		// Video requires avconv or ffmpeg
		if (in_array(Preview\Movie::class, $this->getEnabledDefaultProvider())) {
			$movieBinary = $this->binaryFinder->findBinaryPath('avconv');
			if (!is_string($movieBinary)) {
				$movieBinary = $this->binaryFinder->findBinaryPath('ffmpeg');
			}

			if (is_string($movieBinary)) {
				$this->registerCoreProvider(Preview\Movie::class, '/video\/.*/', ["movieBinary" => $movieBinary]);
			}
		}
	}
```
And specifically 
`$movieBinary = $this->binaryFinder->findBinaryPath('ffmpeg');`
This uses the findbinarypath method to find the binary of ffmpeg in what i assume /bin etc.
So setting any config.php values wont have any effects on the preview provider because it doesn't even look in config.php for the ffmpeg path.

If i look a little up 
`$officeBinary = $this->config->getSystemValue('preview_libreoffice_path', null);`
this line shows that the office binary path does get checked if it exist in config.php
with the get system value.
so idealy this needs to be done for ffmpeg too, so we can add the path in config.php

however I think it is impossible to edit the source code of the snap package, otherwise its an easy fix.
so if someone knows how to effectively update the snap package with the previewManager.php updated. then i think the previewgeneration for videos should work

**Comment by szaimen** [comment]
> If i look a little up
> `$officeBinary = $this->config->getSystemValue('preview_libreoffice_path', null);`
> this line shows that the office binary path does get checked if it exist in config.php
> with the get system value.
> so idealy this needs to be done for ffmpeg too, so we can add the path in config.php

Yes indeed. Can you create a PR in server?

**Comment by szaimen** [comment]
> i think this pr needs to be added in https://github.com/nextcloud/server right?

Correct

**Comment by kyrofa** [comment]
Yeah we don't patch Nextcloud here. Any changes need to be done in upstream Nextcloud itself, as @szaimen said.

**Comment by FedeBx** [comment]
https://github.com/nextcloud-snap/nextcloud-snap/issues/1046#issuecomment-1387233399

Dear, thank you for your help and valuable time. I have identified the error mentioned in this thread (  @Jachhj-sc @szaimen  ), how should I go about fixing it? 

I have the latest version of nexcloud SNAP installed ( _nextcloud 25.0.3snap3 33730 latest/stable_) with PreviewGenerator installed from the Nexcloud backend and the file "PreviewManager.php" is with out the improvement suggested:

Is there a temporary way to tell the nexcloud SNAP where the ffmpeg is?

The above is the same as this case, the error was identified but in my SNAP it continues wrong
https://github.com/nextcloud/server/issues/32837

excuse my query. I am a OLD programmer trying to come back, learning from his valuable contribution.
Tks!

**Comment by szaimen** [comment]
You need to wait for Nc26

**Comment by ShapeShifter499** [comment]
>     * Unpack ffmpeg and ffprobe into `/var/snap/nextcloud/bin/`

@shaman79 I wonder if one could symlink the system installed ffmpeg?  Or will it end up using the snap core system for libraries?

**Comment by ShapeShifter499** [comment]
I have resorted to placing the latest static build of ffmpeg into `/var/snap/nextcloud/bin` for now and it works fine. Thank you.

**Comment by skisky89** [comment]
```
Command "memories:video-setup" is not defined. 
Did you mean one of these?
      memories:index
      memories:migrate-google-takeout
      memories:places-setup 
```
Has anyone seen this error ?? I've installed/setup memories and added the ffmpeg location to config.php

**Comment by ShadabFaiz** [comment]
> ```
> Command "memories:video-setup" is not defined. 
> Did you mean one of these?
>       memories:index
>       memories:migrate-google-takeout
>       memories:places-setup 
> ```
> 
> Has anyone seen this error ?? I've installed/setup memories and added the ffmpeg location to config.php

same issue... @skisky89 did you find any solution to this ?

**Comment by FedeBx** [comment]
> > ```
> > Command "memories:video-setup" is not defined. 
> > Did you mean one of these?
> >       memories:index
> >       memories:migrate-google-takeout
> >       memories:places-setup 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Has anyone seen this error ?? I've installed/setup memories and added the ffmpeg location to config.php
> 
> same issue... @skisky89 did you find any solution to this ?

@skisky89 @ShadabFaiz 

Before I configured it from the terminal, I estimate that since version 5 it changed and I configure it from the administrator user's UI

Starting with v5.0.0, you can fully configure memories using the admin panel. With an admin account in Nextcloud, go to Settings -> Memories. Using the admin interface for configuration is strongly recommended in most cases.

[(https://memories.gallery/config/)]

I hope it helps, don't go deeper into analyzing if the command was replaced/turned off or there is an error

**Comment by SayantanRC** [comment]
Parameters for memories have changed.
```
'memories.vod.disable' => false,
'memories.vod.ffmpeg' => '/var/snap/nextcloud/bin/ffmpeg',
'memories.vod.ffprobe' => '/var/snap/nextcloud/bin/ffprobe',
```

**Comment by YamiYukiSenpai** [comment]
I'm curious to know, is it still impossible to use the snap/deb version of ffmpeg?

**Comment by YamiYukiSenpai** [comment]
> Cool. In the meantime this is how I solved it:
> 
>     * Create `/var/snap/nextcloud/bin/` directory
> 
>     * Google for ffmpeg static build (has included static libraries). I used https://johnvansickle.com/ffmpeg/
> 
>     * Unpack ffmpeg and ffprobe into `/var/snap/nextcloud/bin/`
> 
>     * add/change following lines in `/var/snap/nextcloud/current/nextcloud/config/config.php`
>       'memories.ffmpeg_path' => '/var/snap/nextcloud/bin/ffmpeg',
>       'memories.ffprobe_path' => '/var/snap/nextcloud/bin/ffprobe',
> 
>     * run `nextcloud.occ memories:video-setup`

I followed the steps here, and I still have the message " ffmpeg preview binary not found. Thumbnail generation may not work for videos. " in Memories.

```
  'ffmpeg' => '/var/snap/nextcloud/current/bin/ffmpeg',
  'memories.ffmpeg_path' => '/var/snap/nextcloud/current/bin/ffmpeg',
  'memories.ffprobe_path' => '/var/snap/nextcloud/current/bin/ffprobe',
```

**Comment by FrRene06** [comment]
Hello,

I have entered the following path for ffmpeg :
/var/snap/nextcloud/40887/nextcloud/extra-apps/recognize/node_modules/ffmpeg-static/ffmpeg

and the executable is recognized. I get the following message:
The ffmpeg binary exists and is usable (4.4.1-static).

But for ffprobe, with the same path, I get the following error:
The ffprobe binary was not found.

Nothing is simple with a snap version of Netcloud...

Translated with DeepL.com (free version)

**Comment by leadweedy** [comment]
> 
> I followed the steps here, and I still have the message " ffmpeg preview binary not found. Thumbnail generation may not work for videos. " in Memories.
> 
> ```
>   'ffmpeg' => '/var/snap/nextcloud/current/bin/ffmpeg',
>   'memories.vod.ffmpeg' => '/var/snap/nextcloud/current/bin/ffmpeg',
>   'memories.vod.ffprobe' => '/var/snap/nextcloud/current/bin/ffprobe',
> ```

there's an additional parameter to specify the ffmpeg path specifically for generating previews.
```
'preview_ffmpeg_path' => '/var/snap/nextcloud/current/bin/ffmpeg',
```
ref https://memories.gallery/system-config/

**Comment by YamiYukiSenpai** [comment]
Should this issue be re-opened?

I think the Nextcloud Snap can use ffmpeg snap for all ffmpeg needs?

https://forum.snapcraft.io/t/call-for-testing-ffmpeg-sdk-for-core24/41167/3
