### ISSUE TITLE
Renew doesn't work and installs "second certificate" (not replacing the former)

### ISSUE THREAD

**Issue by erwinmoojen** [nextcloud/nextcloud-snap#1047]
Hi,
I already solved the issue, but thought it should be known that the renew function doesn't work properly with a "regular install".

Using nextcloud.enable-https lets-encrypt I didn't get any error. As it seems, the new certificates were installed in a folder with the name domain.com-001, while the old folder with the old certificates remained in the folder domain.com (within the folder /var/snap/nextcloud/13968/certs/certbot/config/live).

Renaming the folder did the trick, but it also took me a couple of hours to find it out and I'm pretty sure other people are running into this issue as well. Is there a way in which I can prevent this from happening in 3 months time? 

Thanks for your thoughts! Best, Erwin

**Comment by kyrofa** [comment]
Thanks for the report, @erwinmoojen. This doesn't describe the behavior I see-- any chance you ran `enable-https` multiple times?

**Comment by erwinmoojen** [comment]
I might indeed have done this, but I have so for other domains and there it hasn't yet shown this new, additional .conf file.

**Comment by erwinmoojen** [comment]
Well, that might have been the case indeed. But I have done so for other domains, but don't see the same issue there.
