### ISSUE TITLE
Is the export command is compatible when encryption is activated?

### ISSUE THREAD

**Issue by sonic1200** [nextcloud/nextcloud-snap#1069]
Hi,

I need to migrate my current snap instance to a new server and I've just read this article : https://github.com/nextcloud/nextcloud-snap/wiki/How-to-backup-your-instance

It seems very usefull for my usage but I'm wondering if this feature is compatible if I have activated the server side encryption in my current instance? (I have planned to keep this encryption on my new instance)

Is there other known limitations than the one written in the current wiki?

Thank you.

**Comment by kyrofa** [comment]
Honestly, I don't know. I'm not sure how the encryption works, exactly. Can you test it out and let us know?

What I CAN tell you is that, if the files are encrypted in the data directory (which I assume they are with the encryption app), they will also be encrypted in the backup. What I DON'T know is if backing up the database etc. will also back up the encryption key, thus making any restored backup capable of decrypting the data.

**Comment by sonic1200** [comment]
Hi,

Thanks for your answer.
I have planned to test the export this week-end, so I will let you know what will be the results of my tests.

Thank you.

**Comment by sonic1200** [comment]
Hi,

@kyrofa I've just tested the import and export command between my 2 servers and I confirm that the encrypted data is still usable after the import on my new machine. The encryption keys seems to be correctly imported!
I think you can update the page with this indication for other people who will ask the question.

Last small glitch that I had with this migration is with the trusted domain security issues that are copied from my old server to the new one. When I tried to connect on the new server, I couldn't because the trusted domain wasn't the same. I've finally managed to solved this issue by using this solution : https://help.nextcloud.com/t/trusted-domain-in-snap-install-of-next-cloud/8414/4
I think it could be also a good addon to put in the documentation for the export/import snap to help other people when migrating to a new server with those scripts.

I don't know if the import script could avoid the import of the trusted domain when importing on another server in the future?

Thank you.

**Comment by the-sane** [comment]
I support making a note of the potential trusted domain issue in the documentation, but it makes sense to me to continue backing up and restoring this data.  I'd imagine the most common scenario for migrating the nextcloud instance to a new server is a total hardware upgrade/replacement where the domain would remain the same?

**Comment by kyrofa** [comment]
> I'd imagine the most common scenario for migrating the nextcloud instance to a new server is a total hardware upgrade/replacement where the domain would remain the same?

That's exactly the use-case I was envisioning, yeah. I agree, the way it's working now is probably the way we want it to work, but it's probably worth a wiki page providing a tutorial and some caveats.

**Comment by kyrofa** [comment]
Alright, done: https://github.com/nextcloud/nextcloud-snap/wiki/How-to-backup-your-instance#caveats . Look okay?

**Comment by the-sane** [comment]
Looks good to me.

Anyone specifically interested in whether or not their encryption keys will be backed up/restored can hopefully find this issue and see the conversation here.  Personally, I would be hesitant to include mention of that on the official wiki.  I've been reading up on Nextcloud's server-side encryption recently with an eye to deploy it on my instance, but my impression has been it is still quite buggy.  It seems like it was designed with a very specific use-case in mind and, under any other use-case, data loss may be possible.  So, while it worked for Sonic this time, my feeling is it might not work in all situations in its current state.

That said, I wonder if an rsync style backup would be more or less effective at this kind of thing, potentially pulling more data over for some of the edge-cases where a restore with encryption might otherwise fail?  I don't grok enough about snaps yet to know if it would freak out when rysncing the data from one disk over to a new disk.

**Comment by the-sane** [comment]
In trying to answer my own question about rsync, I've been reading through some of the threads from when the export feature was added to the snap.  I'm getting the impression that the mysql database may not love rsync and should be backed up using its own database tools instead (via the export command).  Aside from that, rsyncing the entire nextcloud folder should work fine?

So for someone who wants to be doubly sure that everything is backed up and restored properly, I'm thinking rsync everything over, then dump and restore the database separately for good measure.  Does this sound right to you, @kyrofa?

**Comment by sonic1200** [comment]
Hi,

Indeed it works perfectly for me this time. I guess that the rsync VS specific database extract tools compatibility is probably due to the database format. I guess that if you use Rsync you must have the same exact version of nextcloud on the backuped instance and the restored one. 
Thank for the update for the documentation. People can still refer to this thread for more info.
My use case is exactly the one described by the-sane : transfert my data from one hardware to another one with keeping the same domain. (Hardware migration)

Thanks
