### ISSUE TITLE
Updating an app doesn't really "update it"

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/nextcloud-snap#1076]
#### Describe the bug
I had a weird experience today with one of NC apps called "GpxPod". While troubleshooting for an issue, it appeared that although I had already updated to the newest version, the code was still working as if it's the older version. From dev:
"When I roll back to commit 706caae7 I get your results, which means the code running on your side is actually not v4.0.4. What happens to you is extremely strange. Either your machine is possessed or you did something wrong or Snap NC install is doing unexpected extreme caching... "

The only thing I did was to update the app via app center but somehow, it still acted as it was old (despite the app reporting newest version installed). I tried re-enabling NC snap & rebooting the server & removing browser cache but the only thing that fixed it was me having to disable and enable the app via the app center.

#### To Reproduce
Unknown - It seems that user must have an older version of an app (for me it was GpxPod) and update it through app center. 

#### Expected behavior
The app and its code should be obviously updated to the newest version

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud - nextcloud  15.0.10snap2  14827  stable    nextcloud✓  -

and:

    $ snap version - 
```
snap    2.39.3
snapd   2.39.3
series  16
ubuntu  19.04
kernel  5.0.0-20-generic
```

**Comment by kyrofa** [comment]
Yes, the snap does use caching, but nothing that would survive a reboot like that. If what finally made things work was disabling and re-enabling the app, that sounds like something outside the snap.

**Comment by kyrofa** [comment]
16.0.5snap2 removed some opcache weirdness in the snap as well. I think between that and the fact that anything should be cleared by a reboot, this issue can be closed. If you run into it again, please let us know.
