### ISSUE TITLE
After install, can't find files

### ISSUE THREAD

**Issue by rafny** [nextcloud/nextcloud-snap#1077]
After a new fresh install, I can't seem to find any files for Nextcloud. The main directory is empty. Also, when I used the occ:debug config setting, snap refreshed and the website was down for a few seconds, so at least I know I'm connected to the right install. 

```
$ snap/nextcloud$ tree
.
├── 14827
├── common
└── current -> 14827

3 directories, 0 files
```
```
$ /var/lib/snapd/snaps$ tree
.
├── amazon-ssm-agent_1455.snap
├── core_7270.snap
├── nextcloud_14827.snap
└── partial

1 directory, 3 files
```
```
$ snap list nextcloud
Name       Version       Rev    Tracking  Publisher   Notes
nextcloud  15.0.10snap2  14827  stable    nextcloud✓  -
```
```
$ /var/lib/snapd/snaps$ snap version
snap    2.39.3
snapd   2.39.3
series  16
ubuntu  18.04
kernel  4.15.0-1044-aws
```

**Comment by bhasan** [comment]
I'm pretty sure you have to log in first. First log in will initialize the user including creating paths and data.

**Comment by rafny** [comment]
Do you mean login into the server or nextcloud? I'm already logged into the AWS EC3 via ssh (also confirmed the lack of files via SFTP), but is there a separate snap/nextdoor login?

**Comment by bhasan** [comment]
Log into Nextcloud for the first time. So if you installed Nextcloud as user "Admin", log into Nextcloud with user "Admin". After the first login, Nextcloud will set up that account.

**Comment by rafny** [comment]
I already went through the admin set-up and have everything up and running.

**Comment by bhasan** [comment]
Ah, I mistook you saying "after a fresh install" as you have not logged into your account on Nextcloud. My mistake.

**Comment by rafny** [comment]
Its ok. This is my third snap install of nextcloud, and the first time I see this issue.
