### ISSUE TITLE
Question:  Why does modifying an app's .js file not take effect on the main Nextcloud page?

### ISSUE THREAD

**Issue by the-sane** [nextcloud/nextcloud-snap#1103]
I could use some help understanding a bit of curious behavior that I think is due to the snap vs a traditional install.  I've loaded Nextcloud in incognito to make sure it isn't a local caching issue, and disabled AppArmor to rule that out.  Please help :)

I'm working on fixing a minor bug with grid view for photo folders in the files app.  I have edited the files app's `filelist.js` to apply a fix.  To do this, I followed [these instructions](https://askubuntu.com/a/1036611) to create a bind-mount of the `htdocs/apps/files/js` directory to a copy that I could edit.  I then applied my fix to `filelist.js`.  (The fix is described here: https://github.com/nextcloud/server/issues/16510#issuecomment-522362033)

My fix works great for the other user on a traditional install.  For me, the fix works only if I view that photo folder via a share link.  When I start at my Nextcoud home screen (ie, clicking the files app icon), then navigate to the same folder, the fix doesn't seem to get loaded.  If I inspect the page source, I see a line `defer src="/apps/files/js/filelist.js ...` for the first scenario but not the latter.  The user on a traditional install confirmed the fix works for him in both scenarios.

I can't find anywhere else in the code that I would need to make these changes, and I can't imagine that Nextcloud is loading different code in those two scenarios.  It has to be a snap thing, right?

I just want to make sure before I go submitting a pull request with my fix.  I'm still learning snap stuff so I appreciate any insight!

**Comment by kyrofa** [comment]
I'd be very surprised if bind-mounting like that worked consistently given the intricacies of how snapd sets up a snap with a series of bind mounts anyway. The snap isn't the best thing to use for daily development like that-- it's hard to get your modifications in there, and then even when you do the changes you made aren't under version control or anything, so you have to remember what you did when you modify whatever branch you're working on. If you're really working on a bugfix, I'll tell you what I do: I have a LXD container setup with php, apache, sqlite, and the Nextcloud repo checked out in /var/www/nextcloud (the typical setup). Develop from there.

That said, if you really want to hack on the snap, just extract it.

Step 1: download the snap

    $ snap download nextcloud

Step 2: Extract the snap

    $ unsquashfs *.snap  # this will by default extract into a directory named squashfs-root

Step 3: Use `snap try` to mount a r/w directory as a snap

    $ sudo snap try squashfs-root/

Now you have a readable/writable Nextcloud snap installed. Any modification you made in squashfs-root/ will be reflected in the snap (although you may need to restart various snap services to pick up changes, of course).

**Comment by the-sane** [comment]
I see, thank you so much!  I appreciate the info.
