### ISSUE TITLE
php-imagick missing

### ISSUE THREAD

**Issue by uselpa** [nextcloud/nextcloud-snap#1111]
#### Describe the bug
Admin overview says:
```
There are some warnings regarding your setup.
This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.
- imagick
```

#### To Reproduce
1. Log in as an administrator
2. Click on Administration Overview
3. See error

#### Expected behavior
Previous snap did not show any warning or error.

#### OS/snapd/snap version
```
root@deb10a:~# uname -a
Linux deb10a 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux
root@deb10a:~# snap version
snap    2.40
snapd   2.40
series  16
debian  10
kernel  4.19.0-5-amd64
root@deb10a:~# snap list nextcloud
Name       Version       Rev    Tracking  Publisher   Notes
nextcloud  15.0.11snap1  15565  15        nextcloud✓  -
```

**Comment by kyrofa** [comment]
I suspect you previously didn't enable the theming app, which uses imagick to generate the favicon. We don't include imagick in the snap due to security concerns.

**Comment by uselpa** [comment]
Spot on. Thank you.

**Comment by KaiBuskirk** [comment]
hello... love snap....
as a designer i work in svg for 30 years... whats the security issue...
id like the error to go away.... and choose imagick through a seperate snap...
any thoughts.. thanks, kai
