### ISSUE TITLE
Instructions for backing up SD Card on Linux

### ISSUE THREAD

**Issue by egoebelbecker** [nextcloud/nextcloud-snap#112]
I cloned the wiki over here:

https://github.com/egoebelbecker/nextcloud-snap-wiki

And added instructions for backing up the SD Card on Linux:

https://github.com/egoebelbecker/nextcloud-snap-wiki/blob/master/How-to-backup-your-SD-card.md

Not sure how else to get the changes over to you.

**Comment by oparoz** [comment]
Awesome @egoebelbecker !
I've updated our wiki.

For future reference, the wiki is just a git repo, but there are no mechanisms to submit PRs, so what you did works fine.
