### ISSUE TITLE
Data directory configuration documentation should be updated

### ISSUE THREAD

**Issue by peterwvj** [nextcloud/nextcloud-snap#1121]
The following page says as follows "access to /mnt requires snapd version 2.36+", see https://snapcraft.io/docs/removable-media-interface 

I can confirm that this works. I keep my Nextcloud data in `/mnt`.

The following page, which claims that "the partition you want to use must be mounted somewhere in /media/" should probably be updated accordingly:

https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition

We may also want to update

https://github.com/nextcloud/nextcloud-snap/blob/master/README.md#removable-media

**Comment by kyrofa** [comment]
> The following page, which claims that "the partition you want to use must be mounted somewhere in /media/" should probably be updated accordingly:

Done, thank you!

**Comment by kyrofa** [comment]
The README update will make it to master in the next release.

**Comment by peterwvj** [comment]
Thanks, @kyrofa!
