### ISSUE TITLE
files:scan fails on snap installation

### ISSUE THREAD

**Issue by joedborg** [nextcloud/nextcloud-snap#1124]
### Steps to reproduce
1. `snap install nextcloud`
2. Add files manually
3. `sudo -u www-data nextcloud.occ files:scan --all`

### Expected behaviour
Manually files should be scanned in.

### Actual behaviour
```
2019/09/23 16:13:16.498305 cmd_run.go:884: WARNING: cannot create user data directory: cannot create "/var/www/snap/nextcloud/15910": mkdir /var/www: permission denied
Sorry, home directories outside of /home are not currently supported. 
See https://forum.snapcraft.io/t/11209 for details.`
```

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:**: Snap

**Database:**: Snap

**PHP version:**: Snap

**Nextcloud version:** 15.0.11snap2

**Updated from an older Nextcloud/ownCloud or fresh install:** Snap

**Where did you install Nextcloud from:** Snap

**Comment by kesselb** [comment]
@nextcloud/snap I think this belongs here. Feel free to move it back if its related to nextcloud itself.

**Comment by kyrofa** [comment]
You're right @kesselb, thank you. @joedborg, just run `sudo nextcloud.occ files:scan --all`.

**Comment by joedborg** [comment]
Hi @kyrofa, I tried that first, sadly it doesn't work either:

```
root@atlas:/media/usb/Nextcloud/joe/files# mkdir Foo
root@atlas:/media/usb/Nextcloud/joe/files# chown www-data:www-data Foo/
root@atlas:/media/usb/Nextcloud/joe/files# touch Foo/Bar
root@atlas:/media/usb/Nextcloud/joe/files# chown www-data:www-data Foo/Bar
root@atlas:/media/usb/Nextcloud/joe/files# nextcloud.occ files:scan --all
Starting scan for user 1 out of 2 (joe)
Home storage for user joe not writable
Make sure you're running the scan command only as the user the web server runs as
Starting scan for user 2 out of 2 (sa)
Home storage for user sa not writable
Make sure you're running the scan command only as the user the web server runs as
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 0       | 0     | 00:00:00     |
+---------+-------+--------------+
```

./Foo/Bar doesn't show up on the UI either.

**Comment by kyrofa** [comment]
@joedborg sounds like you have storage set up in a place that isn't accessible from within confinement.

**Comment by joedborg** [comment]
@kyrofa Yes, I followed https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition 

I believe this is working as, when I add files and folders via the UI, they appear on the disk.

**Comment by kyrofa** [comment]
@joedborg are those directories/files owned by root?

**Comment by joedborg** [comment]
@kyrofa the root data directory is, everything inside is owned by `www-data`.  I did try chowning the root data dir to `www-data`, but everything breaks if I do that.

**Comment by kyrofa** [comment]
Try going the other way-- make everything there owned by root (the snap doesn't use www-data, but a confined root instead).

**Comment by joedborg** [comment]
Thanks @kyrofa, that's worked.  Maybe due to sticky permissions, it was adding files belonging to that user so I assumed it was correct.
