### ISSUE TITLE
Deleting a shared folder

### ISSUE THREAD

**Issue by jerome1233** [nextcloud/nextcloud-snap#1137]
#### Describe the bug
Hello,

I have a problem with deleting a shared folder.
A friend shared one folder with me, now he stopped the sharing. But the folder stays in my WebUi. I cannot delete them.

>     [webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: at <>
> 
>         /snap/nextcloud/16232/htdocs/3rdparty/sabre/dav/lib/DAV/Tree.php line 76
>         OCA\DAV\Connector\Sabre\Directory->getChild(“CFL”)
>         /snap/nextcloud/16232/htdocs/3rdparty/sabre/dav/lib/DAV/Tree.php line 178
>         Sabre\DAV\Tree->getNodeForPath(“files/jerome/CFL”)
>         /snap/nextcloud/16232/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 287
>         Sabre\DAV\Tree->delete(“files/jerome/CFL”)
>         <>
>         Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\Reque … "}, Sabre\HTTP\Response {})
>         /snap/nextcloud/16232/htdocs/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
>         undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},“httpDelete”], [Sabre\HTTP\Requ … }])
>         /snap/nextcloud/16232/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 479
>         Sabre\Event\EventEmitter->emit(“method:DELETE”, [Sabre\HTTP\Requ … }])
>         /snap/nextcloud/16232/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 254
>         Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque … "}, Sabre\HTTP\Response {})
>         /snap/nextcloud/16232/htdocs/apps/dav/lib/Server.php line 316
>         Sabre\DAV\Server->exec()
>         /snap/nextcloud/16232/htdocs/apps/dav/appinfo/v2/remote.php line 35
>         OCA\DAV\Server->exec()
>         /snap/nextcloud/16232/htdocs/remote.php line 163
>         undefinedundefinedrequire_once("/snap/nextcloud … p")
> 
>     DELETE /remote.php/dav/files/jerome/CFL
>     from******** by jerome at 2019-10-03T12:02:16+00:00

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

and:

    $ snap version

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by kyrofa** [comment]
This issue does not seem specific to the snap, please log it [upstream](https://github.com/nextcloud/server).
