### ISSUE TITLE
My VPN subdomain name is pointing to my Nextcloud portal

### ISSUE THREAD

**Issue by aaleeexx** [nextcloud/nextcloud-snap#1139]
Background:

I have a tower server at home that I use as a mediaserver.
I use ESXi 6.5 to run 2 virtual machines over ubuntu 16.4, one for VPN service and a software used to update my dynamic DNS entries, the other one is for Nextcloud.

Question:

I have 2 subdomains, the first one is for my VPN service and it's `vpn.mydomain.com` or **A**, to make it easier, the second one is for Nextcloud and it's `nextcloud.mydomain.com` or **B**, to make it easier also. When I type **B** on the URL bar and I hit enter it works, it redirect me to Nextcloud login portal which is correct, but, when I type **A**, it does the same thing. I don't want **A** to reach Nextcloud portal.

**Comment by kyrofa** [comment]
Happy to help! I have a similar setup myself. There's a miss of information missing about yours, though. I assume you have a single IP address, correct? Which means **A** and **B** actually resolve to the same IP? However, there are three machines at play here: the ESXi server, and each VM. What is the networking setup you're using? _Something_ needs to play the role of dispatcher-- if the domain names resolve to the same IP address, there needs to be something listening on that IP address that can forward traffic to the right place depending on the domain name being used. That shouldn't be the snap, it's not made to do that. I personally use haproxy for this.

**Comment by aaleeexx** [comment]
Hi! I'm glad I found someone with my same issue. 
So yes, I have a single IP address, the one that the ISP is giving to me.
Yes, **A** and **B** resolve the same IP. 
The server is connected to a 5-ports switch and this to a powerline, which is connected finally to my modem/router. Port forwarding on my router is for my VPN service and for Nextcloud of course.  
I'm really going crazy, how did you set up the proxy to resolve this?

**Comment by kyrofa** [comment]
I use essentially [this setup](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy) for haproxy. Create a new VM for it, forward ports 80 and 443 to it, and have it take care of forwarding on to both the VPN and the snap based on the domain name being used.

**Comment by aaleeexx** [comment]
Awesome, I’ll update you tomorrow.
Thanks by the way!

**Comment by aaleeexx** [comment]
@kyrofa May I see your haproxy.cfg file? I want to make sure what I did is right.

**Comment by kyrofa** [comment]
@aaleeexx the [haproxy configuration on the wiki](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy) is the minimum required if you want to enable HTTPS via Let's Encrypt (it requires both ports 80 and 443 to be sent to the snap). I'm afraid my personal haproxy configuration is far more complex and wouldn't be helpful to you.

**Comment by aaleeexx** [comment]
Alright, thank you though 👍

**Comment by kyrofa** [comment]
I believe this question has been answered, so I'm going to close. Please feel free to continue discussion here.
