### ISSUE TITLE
Colloabora snap?

### ISSUE THREAD

**Issue by enoch85** [nextcloud/nextcloud-snap#114]
Hey snap-professionals! 

What do you think, would it be possible to create a Collabora snap? 

Requested it here: https://github.com/nextcloud/nextcloud-snap/issues/104

**Comment by MariusBluem** [comment]
👍

**Comment by enoch85** [comment]
@oparoz 


Forget about that idea.
It's forgotten, wasn't thinking about that it actually was a rPi2.

just pulls binaries iirc.
I don't know how Collabora is built but @ezraholm50 talked about that it was buggy (the docker image) and I'd rather use something that is made by Nextclouders

Also, snap is built into Ubuntu, docker is not.

**Comment by kyrofa** [comment]
Probably, but it's difficult to know without trying! Give it a shot :smile: .

**Comment by kyrofa** [comment]
Closing this as it's unrelated to this snap.
