### ISSUE TITLE
Waiting for updated server part of snap

### ISSUE THREAD

**Issue by ducemollari** [nextcloud/nextcloud-snap#1140]
Hello.

After updating of my snap install I got some errors:
Got "This directory is unavailable, please check the logs or contact the administrator" after logon. (placed issue here: https://github.com/nextcloud/server/issues/17331).

Fix for it was merged: https://github.com/nextcloud/server/pull/17359 But in my snap I have old version. How I can update file for testing?

**Comment by kyrofa** [comment]
Which snap channel are you tracking, `stable`? (`snap info nextcloud` will tell you). Those fixes aren't contained in a release yet, but if you're using v16 the daily build might have it: `sudo snap refresh nextcloud --channel=16/edge`. I don't condone that, we don't test it regularly, but if you need the fix it should be there.

**Comment by ducemollari** [comment]
Sure, I'm on stable. Will try 16/edge.

**Comment by ducemollari** [comment]
It works, I have no more errors in logs. I even turned back on files_accesscontrol app and still no errors with groupfolders in my Files.
Will check on other users of this installation and then refresh other installations.

**Comment by kyrofa** [comment]
Excellent, thanks for letting us know! Keep an eye on releases here, though-- I recommend refreshing back to `stable` as soon as it contained the fix you need. I'm going to go ahead and close this as I think the question was answered, but please feel free to continue discussion here.
