### ISSUE TITLE
TypeError: Return value and other error -  nextcloud  16.0.5snap2

### ISSUE THREAD

**Issue by rosenrot** [nextcloud/nextcloud-snap#1145]
[nextcloud.log](https://github.com/nextcloud/nextcloud-snap/files/3745505/nextcloud.log)
In the nextcloud logs, I see such an errors and it repeats:

Error | PHP | TypeError:  Return value of OC\AppFramework\Http\Request::getServerHost() must be  of the type string, null returned at  /snap/nextcloud/16408/htdocs/lib/private/AppFramework/Http/Request.php#903

Error | PHP | Undefined offset: 0 at /snap/nextcloud/16408/htdocs/lib/private/AppFramework/Http/Request.php#903

Error | index | TypeError: Return value of OC\AppFramework\Http\Request::getServerHost() must be of the type string, null returned

#### OS/snapd/snap version
Ubuntu Mate for Rpi 3b+

$ snap list nextcloud
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  16.0.5snap2  16408  stable    nextcloud✓  -

and:

$ snap version
snap    2.42
snapd   2.42
series  16
ubuntu  18.04
kernel  4.15.0-1048-raspi2

**Comment by kyrofa** [comment]
That sounds like an upstream Nextcloud bug. Can you try `16/edge` to see if it was perhaps related to https://github.com/nextcloud/server/pull/17359 ? If not, you'll need to log this upstream, it doesn't appear specific to the snap.
