### ISSUE TITLE
PHP: update to 7.3

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#1149]
PHP v7.2 will reach the [end of active support](https://www.php.net/supported-versions.php) soon. While it will continue receiving security updates, we should start the move to v7.3.

**Comment by stondino00** [comment]
PHP 7.3.13 Security Update

https://www.php.net/ChangeLog-7.php#7.3.13

**Comment by kyrofa** [comment]
On it, thank you.
