### ISSUE TITLE
Log Script includes ObjectStore Credentials

### ISSUE THREAD

**Issue by daniel7558** [nextcloud/nextcloud-snap#1150]
#### Describe the bug
The recommended script to get all logfiles for a bugreport includes the access key and secret for Object Storage when nextcloud is configured to use object storage as the primary storage.
[Issue Debugging Scripts](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)

#### To Reproduce
1. Configure the nextcloud installation to use AWS S3 (for example)
2. Run the script

#### Expected behavior
Credentials get removed/replaced with `***REMOVED SENSITIVE VALUE***` as it is done for the `passwordsalt` and `secret` field. 

At least  there should be a *clear warning* that the output might include credentials and that it has to be reviewed manually.

#### OS/snapd/snap version
not applicable 

#### Logs
Excerpt from log output:

```
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "mydata.nextcloud.myDomain.tld",
                "region": "eu-central-1",
                "autocreate": true,
                "key": "<Key was included in plaintext>",
                "secret": "<Secret was included in plaintext>",
                "use_ssl": true
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
```

**Comment by kyrofa** [comment]
I agree completely. We're just using Nextcloud's tool (`occ`) for doing this, I'm not sure how they decide what values are sensitive but it's obviously imperfect. Can you log this upstream?

**Comment by daniel7558** [comment]
> I agree completely. We're just using Nextcloud's tool (`occ`) for doing this, I'm not sure how they decide what values are sensitive but it's obviously imperfect. Can you log this upstream?

Sure, I've posted it here: [https://github.com/nextcloud/server/issues/17659](https://github.com/nextcloud/server/issues/17659)
