### ISSUE TITLE
PHP 7.2.24 Update

### ISSUE THREAD

**Issue by stondino00** [nextcloud/nextcloud-snap#1152]
PHP 7.2.24 has been released and fixes a security vulnerability.

https://www.php.net/ChangeLog-7.php#7.2.24

**Comment by kapsiR** [comment]
[Urgent security issue in NGINX/php-fpm](https://nextcloud.com/blog/urgent-security-issue-in-nginx-php-fpm/):
Is there any manual step necessary, when using nextcloud-snap on Ubuntu Core?

**Comment by kyrofa** [comment]
Nope, don't worry. The snap doesn't use nginx, either.
