### ISSUE TITLE
Is it not possible to write a data directory outside of the snap?

### ISSUE THREAD

**Issue by HittingSmoke** [nextcloud/nextcloud-snap#116]
Forgive me if this isn't appropriate for an issue report. I'm new to snaps and I'm not sure if I'm encountering bugs, limitations, or configuration problems.

My setup is NextCloud running in a 16.04 VM with my NAS on bare metal, accessible via NFS shares. I'm trying to get my data directory on my NAS share. I realized that /mnt/nas would not work from NextCloud running inside a snap because of container security. Then when checking issue reports here I saw that /media is accessible so I mounted the NFS share at /media/nas (bad practice I know, but I need to get this working somehow).

After moving the NFS share mount point to /media and changing the data dir path in /snap/nextcloud/current/nextcloud/config/config.php I can get the NextCloud interface to load and can read the default files but I can not write. It just says "Failed to create...". PHP error log reports permission denied errors.

The NFS share is owned by root with 770. It is also writable by my user and www-data via ACL. I've tested creating files with all of these users from the NextCloud VM, but it appears httpd from the container is running as root so it should not be an issue.

Should what I'm doing be possible? The NFS share is writable by everyone I grant permissions to. It's setup and mounted correctly. It's just that NextCloud is not being allowed to write to it. I don't know if this is a limitation of snaps, a bug, or something I've overlooked.

**Comment by kyrofa** [comment]
The Nextcloud snap gained this ability in #110, but it's not yet been released to stable. If you want this ability, try out the beta:

    $ sudo snap install --beta nextcloud

**Comment by HittingSmoke** [comment]
I'm not seeing any difference in behavior on the beta. Here's what I did to test.

NFS share is mounted at /media/nas. config.php is pointing to /media/nas/nextcloud for the data directory.

I rsync'd all of the files from the default data directory to /media/nas/nextcloud.

Tried to create a file. Says "Failed to create file..."

Checked permissions on files and folders. root owns them with write access. Can write to NFS share via the command line fine.

I tried deleting the default Nextcloud.mp4 through the web UI. It says "Error deleting..." PHP reports the same "Permission denied" error. Just for experimentation I tried setting Nextcloud.mp4 to 777 permissions. The web UI still will not delete it. Same "Permission denied" error in PHP.

**Comment by kyrofa** [comment]
Ah, I forgot to mention that the interface that grants access to removable media is not automatically connected, so you'll need to grant the snap permission before this will work. You can see this if you run `snap interfaces`, where the Nextcloud snap has the removable-media interface that isn't connected to anything. To connect it, run the following command:

    $ sudo snap connect nextcloud:removable-media ubuntu-core:removable-media

**Comment by HittingSmoke** [comment]
That sorted it! Thank you.

**Comment by peterwvj** [comment]
Access to /mnt is now supported but requires snapd version 2.36+

**Comment by cldtech** [comment]
I need external storage that is neither /media nor /mnt. In fact why can't we choose any folder? Or at least follow symlinks?

**Comment by kyrofa** [comment]
@cldtech because that would require that the snap has permission to write wherever it wants. That is not the case in a confined world.

**Comment by cldtech** [comment]
Then why can it be for /mnt and /media?

**Comment by kyrofa** [comment]
Because that's the [only relevant confinement interface](https://snapcraft.io/docs/removable-media-interface) we could have used. If you think there should be more, it's a discussion to raise with the snap devs, not here. When it exists, we can use it if it seems a good fit.
