### ISSUE TITLE
Upgrade NextCloud to 16.0.7

### ISSUE THREAD

**Issue by stondino00** [nextcloud/nextcloud-snap#1164]
https://github.com/nextcloud/server/releases/tag/v16.0.6

**Comment by stondino00** [comment]
Anybody know what's up with nextcloud's release schedule?  They've built 16.0.6 but it appears they have delayed the official release as their blog, change-log and download section still lists the previous builds.  Seems like they have too many major versions at the same time to keep up with.

**Comment by kyrofa** [comment]
Yeah that's not uncommon for them. I can't speak to their process, but I know they've tagged releases that they've never publicized because they found critical bugs in them, which is why we in the snap don't upgrade until it's front and center on their website.

**Comment by stondino00** [comment]
Ok looks like they finally posted on the website.

https://nextcloud.com/blog/nextcloud-17-0-1-is-here-updates-to-15-and-16-also-out/

**Comment by kyrofa** [comment]
Some issues are happening on the upgrade to 16.0.6: https://github.com/nextcloud/nextcloud-snap/pull/1166#issuecomment-555611896

**Comment by stondino00** [comment]
I've been trying to track the v17 and v16.0.7 discussions.  Are we able to get this built with the new php?

https://github.com/nextcloud/server/releases/tag/v16.0.7

https://nextcloud.com/blog/nextcloud-17-0-2-16-0-7-and-15-0-14-available-for-update-plus-beta-3-of-18-for-testing/

**Comment by kyrofa** [comment]
Resolved by #1198.
