### ISSUE TITLE
Cannot build by snapcraft v3.8

### ISSUE THREAD

**Issue by yuntan** [nextcloud/nextcloud-snap#1165]
#### Describe the bug
`snapcraft` command crashes while building snap.

#### To Reproduce
1. edit `snap/snapcraft.yaml` and add `base: core`.
2. run `snapcraft`.
3. `snapcraft` crashes.

#### OS/snapd/snap version
snapcraft v3.8

#### Logs
```
$ snapcraft
Launching a VM.
Loaded local plugin for php
Loaded local plugin for redis
Loaded local plugin for apache
'required'
We would appreciate it if you anonymously reported this issue.
No other data than the traceback and the version of snapcraft in use will be sent.
Would you like to send this error data? (Yes/No/Always/View) [no]:
```

**Comment by kyrofa** [comment]
> edit snap/snapcraft.yaml and add base: core.

This is your problem. Such a thing is not supported today.
