### ISSUE TITLE
Upload does not finish & Delete throws error

### ISSUE THREAD

**Issue by Fuzzzzy** [nextcloud/nextcloud-snap#1168]
1. In a shared by link folder, if the user uploads files, they are getting uploaded but the upload gets stuck in the finishing phase: 
http://prntscr.com/pyo0nr

If I hit refresh after this, the file is there. 

2. Then if I try to delete those files, it gets deleted but the client gets "Error deleting file"
http://prntscr.com/pyo1hl

I'm using the latest stable version of nextcloud 16.0.6 on a local single server setup with redis.
I flushed the redis cache but the issue is still there. 

The error 524 in the console is coming from cloudflare not getting a response from the server under 100s.

The error was also there before I've updated nextcloud to the latest version.

Please advise.
Thanks!
I.

**Comment by kyrofa** [comment]
> nextcloud 16.0.6 on a local single server setup with redis.
> [...] before I've updated nextcloud to the latest version.

This sounds like you're _not_ using the snap. Sounds like you should log an issue against [upstream Nextcloud instead](https://github.com/nextcloud/server).
