### ISSUE TITLE
Let's Encrypt SHA-2 Signing CA?

### ISSUE THREAD

**Issue by stondino00** [nextcloud/nextcloud-snap#1171]
I've had this snap for almost a year with using the let's encrypt ssl certificate and everything works fine.

My nessus scans this week have come back not liking the Let's Encrypt certificate that's used to sign.  Need's to be a SHA-2 root.

I'm showing DST Root CA X3
PKCS #1 SHA-1 With RSA Encryption

I just tried running the let's encrypt commands again to generate a new cert but I still have this SHA-1 root.  How do I get a SHA-2 root from Let's encrypt to sign my certificate?

**Comment by kyrofa** [comment]
My nessus is making the same complaint. I'm not sure off the bat, but definitely something to deal with.

**Comment by pachulo** [comment]
I would say that this is a false positive from Nessus: https://community.letsencrypt.org/t/pci-compliance-sha1-root/55097

**Comment by stondino00** [comment]
That's what I initially thought too.  SSLLabs is showing me this.  It's that third certificate that has a SHA-1 Nessus is complaining about.


![image](https://user-images.githubusercontent.com/54154986/69338050-f280b300-0c27-11ea-9c16-02f76dc238f5.png)

**Comment by stondino00** [comment]
I had this show up on other Internet facing services I run and had to reissue the certificates with a full SHA-256 CA and it's fixed my other servers in nessus except this one.  Those were purchased certs however and easy to fix.

**Comment by stondino00** [comment]
I'm not seeing where they offer a SHA-256 to replace this certificate.  I guess I'll reach out to nessus on this plugin about how it's a weaker signature but it shouldn't matter being a root CA. Or we'll have to just purchase a rapid ssl cert or something that I know I can get a SHA-256 root for.
