### ISSUE TITLE
nextcloud occ 

### ISSUE THREAD

**Issue by Alex-Domo** [nextcloud/nextcloud-snap#1173]
Who can tell you how nextcloud occ commands work in the snap nextcloud package

https://docs.nextcloud.com/server/16/admin_manual/configuration_files/encryption_configuration.html#disabling-encryption

**Comment by dasaweb** [comment]
You can use the occ commands by using `sudo nextcloud.occ ...`. Please check `sudo nextcloud.occ -h` for help.

See also here: https://github.com/nextcloud/nextcloud-snap#included-cli-utilities

**Comment by Alex-Domo** [comment]
ответ:  sudo nextcloud.occ -h
command not found

**Comment by kyrofa** [comment]
Not sure what OS you're using, but it sounds like `/snap/bin/` is not on your `$PATH`.

**Comment by kyrofa** [comment]
I think this question is answered, so I'll close, but feel free to continue discussion here.

**Comment by seatrout** [comment]
I also have this problem on a Raspberry pi 4 running Debian Buster. /snap/bin/ is in my path, but is is still not recognised. Only by typing the full path -- 

> sudo /snap/bin/nextcloud.occ

Do I get the result I want. 

>
