### ISSUE TITLE
Nextcloud snap with nginx already installed

### ISSUE THREAD

**Issue by anishmittal2020** [nextcloud/nextcloud-snap#1179]
I use Ubuntu 18.04.3 and I already have nginx installed. I installed nextcloud as follows: 

```bash
$ lsb_release -a
Description:    Ubuntu 18.04.3 LTS

$ nginx -v
nginx version: nginx/1.14.0 (Ubuntu)

$ sudo snap install nextcloud

$ sudo snap start nextcloud
Started.
```

- In the `Readme.md` it is mentioned that:

> If your hostname is localhost or localhost.localdomain, like on an Ubuntu Core device, nextcloud.local will be used instead.

But when I type `localhost.nextcloud.local` in the address bar of my browser, I end up here:

![image](https://user-images.githubusercontent.com/42092626/69809780-b67ebc80-11ea-11ea-8670-6460c14b84ef.png)

![image](https://user-images.githubusercontent.com/42092626/69809796-c0a0bb00-11ea-11ea-912e-3c29d366ba63.png)

![image](https://user-images.githubusercontent.com/42092626/69810371-0611b800-11ec-11ea-934b-b6969d74a4d5.png)

# I am unable  to get to the login page. What should I do?

**Comment by kyrofa** [comment]
The snap by default listens on port 80, which is currently used by nginx. You need to change either nginx or the snap to listen on another port (directions for the snap are in the readme).
