### ISSUE TITLE
noob question about Nextcloud 17

### ISSUE THREAD

**Issue by Chippel** [nextcloud/nextcloud-snap#1182]
Hello all. Sorry if I ask such a question but I didn't find anything about it. When does the Snap install the new Nextcloud 17 update? I have the Snap "sudo snap install nextcloud" installed and I'm wondering when an update will be made or if I have to do it myself.

**Comment by kyrofa** [comment]
Please see #1129 for details regarding the v17 upgrade. Long story short, v17 has some issues and isn't ready yet. But if you run `snap install nextcloud` you'll automatically update once it's ready.

**Comment by Chippel** [comment]
Oh, thanks for the fast answer :-) do you mind if I ask another question or do I have to open a new thread for it?

**Comment by kyrofa** [comment]
Consider a reader beyond the two of us: would it be beneficial to them if your next question was a standalone thing, or does it build on your initial question enough it can just go right here? Consider also that the initial query is considered closed: if your next question ends up being an issue that needs to be tracked you'll _need_ to create a new one.
