### ISSUE TITLE
Nextcloud snap, haproxy, docker and iptables - witch rules?

### ISSUE THREAD

**Issue by skollrc** [nextcloud/nextcloud-snap#1187]
#### Describe the bug
Hi,

I have nextcloud snap and collabora in a docker container behind an HA Proxy. I recently add an iptables firewall and I can't use collabora since. (fail to load collabora, please try later). I also disable ipv6 as I normaly didn't use it.

#### To Reproduce
1 https://github.com/nextcloud/nextcloud-snap/wiki/Nextcloud-and-Collabora-behind-HAProxy
2 add iptable rules

#### Expected behavior
Everythings works fine before this
I put ipv6 back and disable iptables and everethings reworks again

#### OS/snapd/snap version
OS: up to date Ubuntu 18.05
Snap Nextcloud 16.05#!/bin/bash

##### My iptables script:

iptables -t filter -F
iptables -t filter -X

iptables -t filter -P INPUT DROP
iptables -t filter -P FORWARD DROP
iptables -t filter -P OUTPUT DROP

iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

iptables -t filter -A INPUT -i lo -j ACCEPT
iptables -t filter -A OUTPUT -o lo -j ACCEPT

iptables -A OUTPUT -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --sport 80 -m state --state ESTABLISHED -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 81 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 81 -j ACCEPT

iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 444 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 444 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 22 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 25 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 25 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 9980 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 9980 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 9443 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 9443 -j ACCEPT
iptables -t filter -A FORWARD -i docker0 -o enp3s0 -j ACCEPT
iptables -t filter -A FORWARD -i enp3s0 -o docker0 -j ACCEPT
iptables -t filter -A INPUT -i docker0 -j ACCEPT
iptables -t filter -A FORWARD -j DOCKER-ISOLATION
iptables -t filter -A FORWARD -o docker0 -j DOCKER
iptables -t filter -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
iptables -t filter -A FORWARD -i docker0 -o docker0 -j ACCEPT
iptables -t filter -A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9980 -j ACCEPT

iptables -t filter -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 53 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 68 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 68 -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A OUTPUT -p icmp -j ACCEPT

iptables -A FORWARD -p tcp --syn -m limit --limit 1/second -j ACCEPT
iptables -A FORWARD -p udp -m limit --limit 1/second -j ACCEPT
iptables -A FORWARD -p icmp --icmp-type echo-request -m limit --limit 1/second -j ACCEPT

iptables -A FORWARD -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s -j ACCEPT

##### My haproxy config
global
    

    tune.ssl.default-dh-param 2048
    
frontend http-in

    bind *:80
    mode http

    acl host_nextcloud hdr(host) -i my.domain
    acl path_letsencrypt path_beg /.well-known/acme-challenge/
    
    use_backend letsencrypt if !host_nextcloud path_letsencrypt
    use_backend nextcloud-http if host_nextcloud

frontend https-in
    bind *:443 

    

    mode tcp

    tcp-request inspect-delay 5s
    tcp-request content accept if { req.ssl_hello_type 1 }

    acl host_nextcloud req.ssl_sni -i my.domain

    use_backend nextcloud-https if host_nextcloud
    default_backend https-term

frontend https-term
    bind *:9443 ssl crt /etc/haproxy/certs

    mode http

    acl path_letsencrypt path_beg /.well-known/acme-challenge/

    use_backend letsencrypt if path_letsencrypt
    default_backend collabora

backend https-term
    mode tcp
    server terminator 127.0.0.1:9443

backend letsencrypt
    mode http
    server letsencrypt 127.0.0.1:10500

backend nextcloud-http
    mode http
    option httpchk HEAD / HTTP/1.1\r\nHost:localhost

    server nextcloud 127.0.0.1:81 check

backend nextcloud-https
    mode tcp
    option ssl-hello-chk

    server nextcloud 127.0.0.1:444 check

backend collabora
    mode http
    option httpchk HEAD / HTTP/1.1\r\nHost:localhost
    server collabora 127.0.0.1:9980 check ssl verify none

**Comment by kyrofa** [comment]
I'm afraid firewalls aren't really our area of expertise; this doesn't really involve the snap at all other than the fact that the firewall you implemented seemingly blocks communication between it at collabora. I'm happy to try and help, but you've got to give me something to go on, here: what exactly are you looking to accomplish with the firewall?

**Comment by skollrc** [comment]
I would like to secure my server. before using collabora, I just used snap with approxymatly the same firewall script (I changed some port  here but nothing related to docker).

**Comment by skollrc** [comment]
Problem solved:
add DOCKER_OPTS="**--iptables=false**" in /etc/init.d/docker

**Comment by kyrofa** [comment]
Interesting, thanks for the update!
