### ISSUE TITLE
A few questions about security and maintaining

### ISSUE THREAD

**Issue by Chippel** [nextcloud/nextcloud-snap#1188]
So I'm currently thinking about switching completely over to a VPS with the Nextcloud Snap install. I wonder how secure it is and how much "admin" I have to be in order to secure my installation. I'm used to creating users and setting up fail2ban + SSH keys for login. Is it secure enough to just update the packages in the future or do I have to know anything else in order of security, performance and reliability? I'm still afraid of switching but maybe you guys can help me.

**Comment by jassonmc** [comment]
I actually share similar interest in the security aspect of the nextcloud snap, as it seems dificult to get hold of some security related hard facts about snap in general

**Comment by kyrofa** [comment]
The Nextcloud snap is _not_ a VM. It's just an application. You'll need to take care of the instance on which you have it installed just like any other instance-- fail2ban, sshguard, SSH keys, etc. What you gain by using the Nextcloud snap is that it will take care of itself as far as maintenance of its components are concerned. It bundles all its dependencies, which means it will update its own dependencies as it sees fit (if there's a new PHP release that fixes some security issues, for example, it'll update it automatically). It will also update Nextcloud itself automatically.

> [...] it seems dificult to get hold of some security related hard facts about snap in general

What exactly are you looking to learn? Have you seen the [whitepaper](https://assets.ubuntu.com/v1/66fcd858-ubuntu-core-security-whitepaper.pdf) about security in snaps and on Ubuntu Core?

**Comment by jassonmc** [comment]
@kyrofa 
Thanks for the valuable link to that whitepaper, which definitely cleared up many questions I had.
Coming from CentOS myself, I didn't understand, that Ubuntu core is the fundamental building block :)

**Comment by kyrofa** [comment]
I think this question has been answered, so I'm going to close it. Please feel free to continue discussion here.
