### ISSUE TITLE
How to use third-party tools to connect Mysql, the database of nextcloud-snap 

### ISSUE THREAD

**Issue by stevenshi0755** [nextcloud/nextcloud-snap#1194]
Hello guys,

I have 2 problems:
1)How to use third-party tools to connect Mysql , the database of nextcloud-snap?
2)How to develop or customize the next cloud based on snap？

Thanks!

**Comment by kyrofa** [comment]
1. mysql uses a unix socket in `/var/snap/nextcloud/current/mysql`, but we don't offer any guarantees that the socket will never move. Use at your own risk.
2. Clone it, change it, build it, and install it!
