### ISSUE TITLE
Advice about using the snap on a ZFS filesystem

### ISSUE THREAD

**Issue by thomascobb** [nextcloud/nextcloud-snap#1199]
I am about to setup a nextcloud server after the last one corrupted its database during a power failure. I have backups, but would like to try and make the recovery procedure easier. I noticed that Ubuntu 19.10 has ZFS as an install option for the root filesystem, which should let me do snapshots, check data integrity and roll back easily, so I thought I might try that.

I have a 1TB Intel 660p NVMe for the root filesystem, and a 2TB 2.5" HDD for the data. I guess I could setup two single disc ZFS pools, then do a nightly snapshot of both with nextcloud in maintenance mode.

Feel free to close this as off topic, but I was interested to see if anyone had any experience running the snap on top of ZFS, and if it was recommended.

**Comment by kyrofa** [comment]
You're ALWAYS welcome to ask questions here, and in the [snapcraft forum](https://forum.snapcraft.io/). I'm afraid I for one have no sage advice either way regarding ZFS, but I'll leave this open in case anyone else does.

**Comment by auberginepop** [comment]
Nextcloud has a maintenance mode which pauses activity and should mean the database will be in a consistent state when the ZFS snapshot happens.

**Comment by UnePierre** [comment]
I have my data in a zraid with regular snapshots (more frequently than daily, but with pruning). I'm planning on an additional offline / off-site backup though.
My plan is to use the MySQL-dump facility into the same zraid. If this needs maintenance mode, so be it.
When that is up and running, and tested, I'll sleep very well.

**Comment by thomascobb** [comment]
I ended up running the root filesystem and the snap on the NVMe on an EXT4 partition. The HDD is using BTRFS and exposed to the snap to write its data on. A nightly cron job puts nextcloud into maintenance mode, does a BTRFS snapshot, and runs the export script for everything apart from data. It also prunes old snapshots to make sure I have a few old snapshots rather than 100s of them (which has caused BTRFS in the past). An offsite backup copies these snapshots over periodically. Maybe I'll look at ZFS in the future for both the root filesystem and data when Ubuntu LTS supports it.
