### ISSUE TITLE
nextcloud.occ files:scan --all does not find manually added folders (S3 external storage)

### ISSUE THREAD

**Issue by ohlr** [nextcloud/nextcloud-snap#1202]
I have sub folders in my external storage (S3) which I added through the S3 cli.
`nextcloud.occ files:scan --all` does not find the folders.
I have to create the folders manually (in the gui) such that the data inside becomes visible.

**Comment by kyrofa** [comment]
Please log this issue against upstream Nextcloud (or the external storage app). It doesn't seem snap specific.
