### ISSUE TITLE
Sabre\DAV\Exception\BadRequest: expected filesize X got Y error

### ISSUE THREAD

**Issue by isaacgerg** [nextcloud/nextcloud-snap#1203]
I get this error despite using the snap command to make my upload filesize 16GB which I verified through the nextcloud interface. I suspect this could be an apache issue but I have no way to change the config since snap makes it read-only.

My install is on AWS using https://medium.com/@n.moretto/nextcloud-on-aws-ad244739c586

Running 16.0.5

**Comment by isaacgerg** [comment]
Any ideas on what i can look into to fix this?

**Comment by kyrofa** [comment]
> I get this error despite using the snap command to make my upload filesize 16GB which I verified through the nextcloud interface

Eh? How did you do that?

**Comment by kyrofa** [comment]
Also, any chance you're using a proxy of some kind?

**Comment by isaacgerg** [comment]
No.  I am running on an AWS instance.

**Comment by isaacgerg** [comment]
> How did you do that?

Ahh!  I am in error.  I did not do that.

**Comment by txtd** [comment]
I am seeing the exact errors in my log file.

My nextcloud is not behind a proxy and I am running on Azure.

What else would I need to provide in order to help debug this issue?

**Comment by kyrofa** [comment]
@txtd are you also using S3?

**Comment by txtd** [comment]
Nope. I am running nextcloud in a VM hosted on Azure with just one SSD attached to it.

**Comment by jame-mni** [comment]
I am getting this error as well, on any files larger then 100mb.  I'm running on local hardware.

I believe it may be related to mod reqtimeout or http2 from these threads, but since we can't edit the files in the SNAP partition, the issue remains.
https://github.com/nextcloud/server/issues/15095
https://github.com/nextcloud/server/issues/16138

Had issues both on 16.x and 17

PHP

Nextcloud version: 17.0.3 Build:2020-02-04T23:21:45+00:00 79617a2b23cd50c74ea62d9ba9be9fedac42ea87 - 17.0.3.1

Version: 7.3.13

Memory Limit: -1 B

Max Execution Time: 3600

Upload max size: 16 GB

**Comment by isaacgerg** [comment]
@txtd  I have no idea what Gnome Tasks is.  I dont use any kind of UI, just command line to setup.

**Comment by ddesmond** [comment]
have the same errors using wasabi as external storage.
any hints why would that be like so?

**Comment by jame-mni** [comment]
> have the same errors using wasabi as external storage.
> any hints why would that be like so?
> edit: from logging:
> Error: Cannot modify header information - headers already sent by (output started at /snap/nextcloud/26119/htdocs/3rdparty/sabre/http/lib/Sapi.php:132) at /snap/nextcloud/26119/htdocs/apps/dav/lib/Connector/Sabre/File.php#691
> 
> and
> 
> Sabre\DAV\Exception\BadRequest: Expected filesize of 10000000 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 5439488 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.

Are you by chance using Cloudflare or another reverse Proxy?  I was able to resolve this error by disabling those.

**Comment by ddesmond** [comment]
> Are you by chance using Cloudflare or another reverse Proxy? I was able to resolve this error by disabling those.
we do not use any proxy/reverse  or Cloudflare.
How should i read this error? we sometimes do upload big files, sometimes in GBs size. Is this a critical bug?
i can see the files on other machine where loading of those files takes place, and didint notice any errors in files per se (corruptions or such - knock on wood, thanks god)

**Comment by matthewlswanson** [comment]
I am getting this on both a local manual install and using the nextcloudvm script. So it is not related to snap but is an issue with the nextcloud server in general.

**Comment by kyrofa** [comment]
> it is not related to snap but is an issue with the nextcloud server in general.

Indeed, please log this upstream if you're effected by it, there's nothing we can do here.

**Comment by ShapeShifter499** [comment]
@kyrofa I saw that the nextcloud vm project enabled this. https://github.com/nextcloud/vm/commit/50d499b343e495a65c0ab929f40445bf0352fbc4


Does adding these settings help at all?  I'm currently facing this same issue but I haven't made any changes yet.

**Comment by ShapeShifter499** [comment]
Update, so in my case I have haproxy in front of my nextcloud-snap setup.

Adding a larger timeout to haproxy defaults helped. These seem fine for me.
```
timeout connect 30s
timeout client  2h
timeout server  2h
```

I also had to get rid of anything like 'option http-server-close' for the nextcloud part of my haproxy which makes sense.
