### ISSUE TITLE
Change snapcraft snap name to "Nextcloud Server" instead of "Nextcloud" and leave description of usage or link to this repo

### ISSUE THREAD

**Issue by coughingmouse** [nextcloud/nextcloud-snap#1206]
I was trying to leave a comment on Ubuntu Software but I forgot to sign in so I couldn't. Now have I realized...

#### Describe the bug
Users on Snapcraft, Ubuntu Software, and Gnome Software download this snap, thinking this is the client. It's very hard for the end-user to realize that this is the server, especially on other platforms like Ubuntu Software.

#### To Reproduce
i. On the web
1. Go to //snapcraft.io/nextcloud
2. See that the server snap can be mistaken for the client

ii. On Ubuntu (recommended, because here it really doesn't look like the server)
1. Open up 'Ubuntu Software'
2. Type "Nextcloud"
3. Scroll down and find the Nextcloud app named "Nextcloud"
4. See that it doesn't look like a server with your own eyes 👀

#### Expected behavior
A server should not be mistaken for a client.

#### OS/snapd/snap version
On Ubuntu 19.10, checked the regular snap on 2019-01-08 (UTC+9).

snap    2.42.5
snapd   2.42.5
series  16
ubuntu  19.10
kernel  5.3.0-26-generic

**Comment by kyrofa** [comment]
Looks like the server to me:

![Screenshot from 2020-01-08 08-09-27](https://user-images.githubusercontent.com/946674/71994874-608c3400-31ee-11ea-847f-cdb68a4b7d14.png)

Besides, we can't change the name of a snap without asking everyone who already has it installed to reinstall it, which is of course unreasonable.

**Comment by coughingmouse** [comment]
Please reconsider this.

How is anyone supposed to assume that you guys were "actually" snapping the server if it's a snap, which is usually used for clients?

Cloud service users don't read descriptions as carefully as you developers. Users trying to install "Nextcloud" on their PC probably didn't read the image you posted, because that image comes after this which made them firmly confident that it the client they were looking for:
![image](https://user-images.githubusercontent.com/15174845/71995858-94af3580-327e-11ea-8889-07737e3f918c.png)
which is the part read by users trying to install a Nextcloud client on Ubuntu Software. Not everyone reads every description and understands them. (Or think of it this way: how would you name the client? "Nextcloud Client"? Users don't know what a client---or a server---is, and they don't need to.)

I get that renaming is not possible at status quo. What a dumb name, to begin with, knowing you can't simply change the snap name. 

You can still modify the first part of the description before "Where are your photos and documents?" to notify the users that it's a server and that there is instruction somewhere (here in Github or wherever else). I believe the naming accounts significantly to the snap getting 49 1-star reviews out of 79 ratings in total, and couldn't just watch your review getting a 1-star rating for this simple ignorance.
