### ISSUE TITLE
Nextcloud installation broken after last refresh

### ISSUE THREAD

**Issue by ersv** [nextcloud/nextcloud-snap#1214]
Please, how do I debug the following problem? I am running a fairly important/big Nextcloud instance and googling turns up nothing:

I am on a ubuntu 18-04 server and this morning the Nextcloud installation on this server broke after an automatic refresh. 

When I go to the webpage of the installation I only get:

"Downgrading is not supported and is likely to cause unpredictable issues (from 16.0.7.1 to 16.0.5.1) "

I am using the stable version:

$ snap list nextcloud
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  16.0.5snap4  18019  stable    nextcloud✓  -

Any help very much appreciated.

**Comment by cyberkeiler** [comment]
I just got into the same problem:

Was on beta channel by mistake, but there were issues with the nextcloud-fixer constantly switching restarting and blocking the instance switching in maintenance mode and back every few seconds.

If somewone can help downgrading to stable branch I would be thankfull as well ;)

**Comment by kyrofa** [comment]
Sorry guys, I tested that nextcloud-fixer thing but when it was actually released it didn't work properly so I had to pull it out. It was only out for 30 seconds or so so you guys had unlucky timing, I'm sorry! Try `sudo snap revert nextcloud` to get on the rev before, and I'm working on a fix ASAP.

**Comment by cyberkeiler** [comment]
No problem @kyrofa - thanks anyway for your continously work.

Just to clarify: 
The way to go is switching back to beta and than revert? 
Or revert in the stable snap?

**Comment by kyrofa** [comment]
@cyberkeiler I need to see the output of `snap list nextcloud --all` in order to give you a definite answer.

**Comment by cyberkeiler** [comment]
Sure, here you go. I'm back on beta due to the downgrading issue. And this is the output of the snap list:

> Name       Version                   Rev    Tracking  Publisher   Notes
> nextcloud  16.0.5snap4               18019  beta      nextcloud✓  disabled
> nextcloud  16.0.5snap4+git6.275ff41  18172  beta      nextcloud✓  -


Thanks!

**Comment by ersv** [comment]
Thank you for your efforts with this project. 

I ran `sudo snap revert nextcloud` and now I only get "server in maintenance mode", perhaps I shouldn't have run the revert thing?
My output from snap list is:

$ snap list nextcloud --all
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  16.0.7snap1  18184  stable    nextcloud✓  -
nextcloud  16.0.5snap4  18019  stable    nextcloud✓  disabled


What should I do to get back on track?

**Comment by kyrofa** [comment]
This will get you back on track:

    $ sudo snap refresh nextcloud --channel=beta/pr-1215

I can't quite explain why that ran differently in production than on my dev machine, but I developed and tested that ^ specifically against my production instance and can confirm that it works.

**Comment by kyrofa** [comment]
As soon as I get that in a stable release (a few hours) I'll let you know here and you can safely refresh back to stable.

**Comment by kyrofa** [comment]
> server in maintenance mode

That's probably leftovers from the back update, you should be able to safely disable maintenance mode:

    $ sudo nextcloud.occ maintenance:mode --off

**Comment by kyrofa** [comment]
I'll land that feature as soon as one or both of you can confirm that it works for you as well.

**Comment by cyberkeiler** [comment]
Yes, it is working again! Thanks a lot @kyrofa

**Comment by kyrofa** [comment]
Alright 16.0.7snap2 is in the stable channel and ready for you to switch:

    $ sudo snap refresh --stable nextcloud

If you're already on the stable channel, you can just run `sudo snap refresh` or do nothing at all.

**Comment by ersv** [comment]
It's working nicely again, thank you kyrofa!
