### ISSUE TITLE
Idea for the future: notify admins

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-snap#1220]
As I stated in https://github.com/nextcloud/nextcloud-snap/issues/1129

>There is a working script that informs all admin users in the Nextcloud VM now. Maybe it could also get used here?

> The current version was merged [here](https://github.com/nextcloud/vm/pull/1030/files) but we are currently reworking the function to make it more efficient [here](https://github.com/nextcloud/vm/pull/1034/files).

**Comment by the-sane** [comment]
I like the idea.  Here's my thoughts on the script from a previous comment:

> At its core, it's just looping through all users and grepping for that admin tag, then using the existing occ notification:generate feature to create a web notification for each of those found users. It could take a while on large instances, so I see it being used as a last resort only if we know an update will break something but there's nothing we can do about it and the update has to be pushed out anyway.

**Comment by kyrofa** [comment]
I like it. Check out #1221.
