### ISSUE TITLE
18/Stretch: Only Office's Community Document Server cannot be installed due to Client.php

### ISSUE THREAD

**Issue by yoasty** [nextcloud/nextcloud-snap#1228]
#### Describe the bug
A clear and concise description of the bug.
The "TIMEOUT" setting in Client.php is set to 30 but the size of the file is too big to make 30 seconds realistic/attainable for a download. 
#### To Reproduce
Go to apps and search for the Community Document Server (typing "community" should bring it up). Click to install it. The install will fail after about 30 seconds with about a third of the download done.
cURL error 28 
#### Expected behavior
Since the Community Document Server is part of the simple Onlyoffice installation shown in the videos etc. it should be able to simply install it with the standard defaults. Changing the settings to a much higher value should solve the problem.
#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

and:

    $ snap version

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by scubamuc** [comment]
Nextcloud-snap current stable version is **Nextcloud 16.07**.

OnlyOffice community document server is available from Nextcloud **18** (Nextcloud hub).

**Comment by alexpattyn** [comment]
Same issue on channel=18/edge. https://help.nextcloud.com/t/downloading-certain-apps-not-working/62603/11 has a work around. But I have yet to apply it to my own instance (have to find were Client.php is).

**Comment by kyrofa** [comment]
You won't be able to edit Client.php in the snap, but as soon as a fix
lands on stable18 you'll get it automatically.

**Comment by alexpattyn** [comment]
@kyrofa Thanks saved me from searching ha. I'll look to rebase to stable 18 when it comes out then.

**Comment by derhagen** [comment]
The timeout was disabled for CLI app installs, so `nextcloud.occ app:install documentserver_community` should work

**Comment by kyrofa** [comment]
Given that this has a workaround (and we can't do anything more about this in the snap) I'm going to go ahead and close this. Feel free to continue discussion here.
