### ISSUE TITLE
Cannot get nextcloud listening on ipv4

### ISSUE THREAD

**Issue by fralbo** [nextcloud/nextcloud-snap#1231]
I've installed nextcloud (18.0.0) with snap and configured it to listen to port 82 with `sudo snap set nextcloud ports.http=82`, firewall is opened on that port as well but it doesn't respond.

I tried to find info on web including nextcloud community without success. it's strangely like if I was the only one to experiment this issue.

Investigating, it seems that it's listening to port 82 but on ipv6 only (pid 5231):

	ubuntuadmin@ubuntu-1804-srv:~$ sudo netstat -tulpn
	[sudo] password for ubuntuadmin:
	Active Internet connections (only servers)
	Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
	tcp        0      0 127.0.0.1:9236          0.0.0.0:*               LISTEN      2476/gitaly
	tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      844/systemd-resolve
	tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1275/sshd
	tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      2464/grafana-server
	tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1711/master
	tcp        0      0 0.0.0.0:5050            0.0.0.0:*               LISTEN      2351/nginx: master
	tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      2351/nginx: master
	tcp        0      0 0.0.0.0:8060            0.0.0.0:*               LISTEN      2351/nginx: master
	tcp        0      0 127.0.0.1:9121          0.0.0.0:*               LISTEN      2400/redis_exporter
	tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN      2412/prometheus
	tcp        0      0 127.0.0.1:9187          0.0.0.0:*               LISTEN      2438/postgres_expor
	tcp        0      0 127.0.0.1:9093          0.0.0.0:*               LISTEN      2420/alertmanager
	tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      2488/registry
	tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1512/mysqld
	tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      2419/node_exporter
	tcp        0      0 127.0.0.1:9229          0.0.0.0:*               LISTEN      2239/gitlab-workhor
	tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      3156/unicorn master
	tcp        0      0 127.0.0.1:9168          0.0.0.0:*               LISTEN      2418/puma 4.3.1.git
	tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2351/nginx: master
	tcp        0      0 127.0.0.1:8082          0.0.0.0:*               LISTEN      2368/sidekiq 5.2.7
	tcp6       0      0 :::22                   :::*                    LISTEN      1275/sshd
	tcp6       0      0 :::25                   :::*                    LISTEN      1711/master
	tcp6       0      0 :::9094                 :::*                    LISTEN      2420/alertmanager
	tcp6       0      0 ::1:9168                :::*                    LISTEN      2418/puma 4.3.1.git
	tcp6       0      0 :::82                   :::*                    LISTEN      5231/httpd
	udp        0      0 127.0.0.53:53           0.0.0.0:*                           844/systemd-resolve
	udp        0      0 0.0.0.0:5353            0.0.0.0:*                           4558/mdns-publisher
	udp6       0      0 :::9094                 :::*                                2420/alertmanager
	udp6       0      0 :::5353                 :::*                                4558/mdns-publisher

(nginx is for Gitlab)

Why ??
What do I have to change or add to tell him to listen on `tcp:`?

Regards,

**Comment by fralbo** [comment]
I works now, I don't why....
Sorry.

**Comment by Padrio** [comment]
> I works now, I don't why....
> Sorry.

What did you do to accomplish this? I've got the same issue...

**Comment by feivur** [comment]
facing this issue too
