### ISSUE TITLE
Email links are Network IP

### ISSUE THREAD

**Issue by yourimuldernl** [nextcloud/nextcloud-snap#1232]
when i get a email from my server and open a link in the mail it opens in my brouwser as iternal IP

**Comment by kyrofa** [comment]
Take a look at the link itself in the email instead of opening it in your browser. Is it also an internal IP?

**Comment by yourimuldernl** [comment]
the url in the mail is also internal IP

**Comment by yourimuldernl** [comment]
i just found my problem the config.php was miss configured 
overwrite.cli.url was set to the internal IP (I feel supid Now)
