### ISSUE TITLE
ResourceLocator can not find a web root creat file

### ISSUE THREAD

**Issue by leeivan** [nextcloud/nextcloud-snap#1235]
# Steps to reproduce
1. update to Nextcloud 16 and 17
2.create files, such as text document, mind map 
### Actual behaviour
do not create, but folder, word, ppt, and so on.
### Server configuration
ubuntu 18.04 snap
#### logs

Error | lib | ResourceLocator can not find a web root (root: /var/snap/nextcloud/18576/nextcloud/extra-apps/richdocuments, file: index.php/css/richdocuments/8931-79af-viewer.css?v=d41d8cd98f00b204e9800998ecf8427e, webRoot: , throw: true)
-- | -- | --

**Comment by kyrofa** [comment]
This is a known issue that needs to be fixed upstream (and progress is being made on that front, I think).
