### ISSUE TITLE
No result from sudo nextcloud.occ

### ISSUE THREAD

**Issue by pc-robelbois** [nextcloud/nextcloud-snap#1238]
#### Describe the bug
Fresh ubuntu install, snap install nextcloud, run sudo nextcloud.occ.

#### Expected behavior
Any kind of output from nextcloud.occ cmd.

#### Screenshots
![image](https://user-images.githubusercontent.com/50719398/73786125-f6d55a80-4798-11ea-9c60-dd7dbf45d52f.png)

#### OS/snapd/snap version
snap list nextcloud
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  16.0.7snap2  18204  stable    nextcloud*  -

snap version
snap    2.42.5
snapd   2.42.5
series  16
ubuntu  19.10
kernel  5.0.21-4-pve

#### Logs
[debug.log](https://github.com/nextcloud/nextcloud-snap/files/4156003/debug.log)

**Comment by kyrofa** [comment]
Something is very broken on your machine:
```
error: cannot communicate with server: Post http://localhost/v2/snapctl: write unix @->/run/snapd-snap.socket: write: broken pipe
```
Snapd isn't running properly.
