### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by chomudda** [nextcloud/nextcloud-snap#1239]
#### Describe the bug
After following [this](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition) guide to change the data directory,  NextCloud stops working, internal server error message appears. Does not matter if you have just installed NextCloud or if you have already added an admin user, results are the same.

#### To Reproduce
1. sudo snap install nextcloud
2. Follow [this](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition#if-you-just-installed-the-snap-and-havent-created-an-admin-user-yet) guide to change the data directory location.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
    nextcloud  16.0.7snap2  18204  stable    nextcloud✓

and:

    $ snap version

snap    2.42.1+18.04
snapd   2.42.1+18.04
series  16
ubuntu  18.04
kernel  5.3.0-28-generic

#### Logs
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

**Comment by torbjornmelle** [comment]
Did you find a solution? I've experienced the same problem following the same guide (and almost every guide online). I'm almost givin up Nextcloud and external storage.

$ snap list nextcloud
nextcloud  17.0.3snap1  19299  stable    nextcloud✓

$ snap version
snap    2.43.3
snapd   2.43.3
series  16
ubuntu  19.10
kernel  5.3.0-7629-generic

**Comment by chomudda** [comment]
Yes, I managed to get it working without SSL which is not ideal. Honestly, don't bother with it. Transfer speeds were terrible. Seafile has a much better user experience. Setup is very smooth. Transfer speeds are so much better.

**Comment by maximilianovermeyer** [comment]
For anyone stumbling across this: the following command allows the nextcloud snap to access the external path.
`sudo snap connect nextcloud:removable-media`
