### ISSUE TITLE
Upgade to Nextcloud 18

### ISSUE THREAD

**Issue by ahlooii** [nextcloud/nextcloud-snap#1247]
Dear all, if i want to update the app to 18.0 Nextcloud Hub, i use sudo snap nextcloud refresh (at host machine of course), it return with the result of nothing to update. I been told it was because the latest snap stable is stucked at 16.0.8. So if i want to change to 18 (edge) version, can i do the following?

Current Ver. of NC: 16.0.8
Ubuntu Server w. LXDE skin.
Nextcloud install with Snap.

I would backup my data directory and just uninstall my current nextcloud and reinstall with Vers. 18 Nextcloud Hub Snap and replace the new data directory with my old data directory.

Will that worked?

**Comment by Flaburgan** [comment]
Hi @ahlooii and thank you for your interest about nextcloud packaged as snap. The snap is currently in the process of being updated to the v17. I don't think any work to update to v18 as started yet, but this should start soon after the upgrade to v17 is done. If you want to help, v17 to be released, please follow the instruction there: https://github.com/nextcloud/nextcloud-snap/pull/1224#issuecomment-583948410

Have a nice day.

**Comment by Mercurial** [comment]
I was also wondering how to update to the latest version, I hope 18 will be available soon!

**Comment by kyrofa** [comment]
Don't worry, if you're tracking the `stable` channel (which you are by default) you'll automatically update as we judge it stable enough!

**Comment by Mercurial** [comment]
thanks for your hardwork @kyrofa

**Comment by szaimen** [comment]
Are you sure that you want to get automatically upgraded to Nextcloud 18 as long as this issue isn't resolved? https://github.com/nextcloud/photos/issues/128

**Comment by szaimen** [comment]
I don't know if that is possible with the snap but would that work (if the feature will not be ready until Nextcloud 18's security support is dropped)
https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/20

**Comment by inhedgerow** [comment]
I just came here to ask, what happens now with this?  a fresh snap install, I went to apps, and the right click app showed a box saying 'update to 0.17.0', I assumed this was the right click app, and when selected I was shown a screen saying app update in progress.  My admin overview now shows Version
Nextcloud 17.0.3
!!!wtf is this going to break?

**Comment by inhedgerow** [comment]
persists through reboot too. damn.

**Comment by kyrofa** [comment]
@inhedgerow I'm confused. It's not clear what you're doing or what exactly broke. Are you experimenting with v18?

**Comment by inhedgerow** [comment]
I am obviously just dumb. just looked at the main page.  apologies, last install of the stable branch was still 16 and my initial install just before posting was still 16.... read before posting idiot.

**Comment by kyrofa** [comment]
Looks like you already have @inhedgerow, no problem :) .

**Comment by jospoortvliet** [comment]
FYI - wrt the issue with Photos and lack of slideshow on public links - this is WIP and hopefully addressed in 18.0.2. See https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/32 for more.

**Comment by derhagen** [comment]
18.0.2 is out: https://github.com/nextcloud/server/releases/tag/v18.0.2

**Comment by szaimen** [comment]
Viewer for public links will come with 18.0.3

**Comment by derhagen** [comment]
18.0.3 is out: https://nextcloud.com/blog/update-18-0-3-and-17-0-5-out-update-soon/

**Comment by szaimen** [comment]
18.0.3 is an unplanned security update. The feature will unfortunately come with 18.0.4.

**Comment by kyrofa** [comment]
@szaimen thank you for keeping us in the loop. I've updated #1271, but we'll hold off and upgrading folks until this is fixed.

**Comment by kyrofa** [comment]
FYI, sounds like all the bugfixes have landed, we're just waiting for 18.0.4 to be cut. Has anyone taken the `18/edge` channel for a spin, lately? That should have the fixes.

**Comment by derhagen** [comment]
> FYI, sounds like all the bugfixes have landed, we're just waiting for 18.0.4 to be cut. Has anyone taken the `18/edge` channel for a spin, lately? That should have the fixes.

The slideshow is working on 18/edge, but since nextcloud/photos#236 is still open, you get the usual file view when you open a public link to an album. The recipient can change this to grid view, which comes pretty close to the photo view from before. See https://nc.derhagen.eu/index.php/s/BsWAPfof7rrjPno for reference.

This breaks the 'send a nice photo gallery link to your grandparents' use case for now, but I don't think this should be a showstopper for 18.

**Comment by kyrofa** [comment]
Agreed, I think https://github.com/nextcloud/photos/issues/236 should be non-blocking, let's roll with the fixes in 18.0.4. Keep in mind you can switch channels to `17/stable` if you want to stay there!
