### ISSUE TITLE
How to fix PHP module imagick isn't installed

### ISSUE THREAD

**Issue by Flaburgan** [nextcloud/nextcloud-snap#1249]
The automatic check says my installation is missing the imagick php module. How can I correct that? I'm running 16.0.8 but it's like this for more than a year, probably since the installation.

**Comment by kyrofa** [comment]
Indeed, the snap doesn't bundle imagick (on purpose). This warning is only shown when the theming app is enabled, where it's used to generate a favicon. In the snap, you simply get no favicon generated.

**Comment by Flaburgan** [comment]
I was asking that because the picture app is quite slow to open a picture in full screen so I was wondering if it could be linked.
