### ISSUE TITLE
I changed a circle CI setting

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-snap#1252]
@kyrofa @pachulo 

I changed a setting on circle CI, because it was leaking our github auth token to external contributors and we received a security report about it.
I didn't see the variable being used, so I'm not sure it is a problem.
But in fact you should all be in the nextcloud organisation here on github, so you should be able to send your branches to our repository and then create the PRs from there.

cheers Joas - Nextcloud Security

**Comment by kyrofa** [comment]
Thanks for the heads up, @nickvergessen!

> it was leaking our github auth token to external contributors

Yikes.

> I didn't see the variable being used, so I'm not sure it is a problem.
> But in fact you should all be in the nextcloud organisation here on github, so you should be able to send your branches to our repository and then create the PRs from there.

I'm not entirely clear on what has changed. Are you saying CircleCI will no longer be able to run on PRs from forks (i.e. our community contributors)?

**Comment by nickvergessen** [comment]
> Are you saying CircleCI will no longer be able to run on PRs from forks (i.e. our community contributors)?

Running CI is one setting, exposing custom enviroment keys is the one I disabled.

I'm not sure what the key is used for. But in case a forked PR fails you now know why :sunglasses:

**Comment by kyrofa** [comment]
Ah, now I understand! Yeah we don't that, should be no problem at all. Thanks again for the heads up :smiley: .
