### ISSUE TITLE
Admin notification doesn't support spaces in username

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-snap#1260]
Today there was a bug report in the Nextcloud VM repository where the notify admin function didn't work. 
This was caused by spaces in the userid:
https://github.com/nextcloud/server/issues/18868

To fix that we are currently updating the function:
https://github.com/nextcloud/vm/pull/1105

Maybe you should think about improving the function as well?

**Comment by kyrofa** [comment]
Thanks for the heads up my friend, we will investigate.
