### ISSUE TITLE
Backup database error

### ISSUE THREAD

**Issue by guoguoguilai** [nextcloud/nextcloud-snap#1263]
I am trying to backup nextcloud database. 
When using **sudo nextcloud.mysqldump > abc.sql**, an error occured
`
mysqldump: [Warning] World-writable config file '/var/snap/nextcloud/18885/mysql/root.ini' is ignored.
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) when trying to connect
`
When using ** sudo nextcloud.export -b abc.sql**, another error occured
`WARNING: This functionality is still experimental and under
development, use at your own risk. Note that the CLI interface is
unstable, so beware if using from within scripts.
Enabling maintenance mode... done
Exporting database...
mysqldump: [Warning] World-writable config file '/var/snap/nextcloud/18885/mysql/root.ini' is ignored.
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) when trying to connect
Unable to export database
Disabling maintenance mode... done
`

I thought it was my local mysql's fault, so I run 
`sudo service mysqld stop
sudo snap restart nextcloud`
But still the same error. How can I solve this?

**Comment by kyrofa** [comment]
Looks like you (or some other piece of software) changed that file to be world-readable. That's a security problem, so the mysql client refuses to use it. You should change it back to how the snap made it, which is 600:

    $ sudo chmod 600 /var/snap/nextcloud/current/mysql/root.ini

Things should start working again. Depending on what kind of host you're on, you might want to consider changing mysql's passwords, but I'll leave that up to you.

**Comment by guoguoguilai** [comment]
> Looks like you (or some other piece of software) changed that file to be world-readable. That's a security problem, so the mysql client refuses to use it. You should change it back to how the snap made it, which is 600:
> 
> ```
> $ sudo chmod 600 /var/snap/nextcloud/current/mysql/root.ini
> ```
> 
> Things should start working again. Depending on what kind of host you're on, you might want to consider changing mysql's passwords, but I'll leave that up to you.

It works! Thank you so much!
