### ISSUE TITLE
Nextcloud snap 17.0.3 missing php imagick extension

### ISSUE THREAD

**Issue by weierophinney** [nextcloud/nextcloud-snap#1269]
#### What dependency/component is out of date?

- Nextcloud snap 17.03 is missing the PHP imagick extension.

My snap instance was recently updated to 17.0.3 from 16.0.5.

When I go to the admin overview, I get a warning indicating that the imagick extension for PHP is not installed. My understanding is that this is necessary for theming (likely for resizing uploaded images).

**Comment by kyrofa** [comment]
The snap doesn't ship imagick for security reasons. You only see this warning if you have theming enabled, and the only feature you miss is favicon generation. I know it's annoying to see a warning, I'm sorry about that, but imagick is not something we're willing to enable.

**Comment by johanmorenolds** [comment]
Great reply, thanks, i have been trying to solve the "issue" for a long time
