### ISSUE TITLE
Apparmor config needs additional directory specified

### ISSUE THREAD

**Issue by maltesedonkey** [nextcloud/nextcloud-snap#1270]
syslog reports repeated (every few seconds) lines of the form

Feb 25 15:56:50 XXX kernel: [593997.294585] audit: type=1400 audit(1582646210.324:1902): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=11327 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Addition of the following line to snap.nextcloud.php-fpm in /var/lib/snapd/apparmor/profiles followed by a apparmor reload (service apparmor reload on Ubuntu) cures it.

  /etc/systemd/timesyncd.conf     r,

Using:installed:      17.0.3snap1

**Comment by maltesedonkey** [comment]
But change is lost on snap update or Nextcloud restart (don't know how to make change permanent)

**Comment by kyrofa** [comment]
Yeah I'm afraid snapd generates the appamor stuff on the fly and will overwrite any chances you make when it feels like it. Nice for testing, but not for actually persisting changes. The fix, however, is not to open up confinement further, but to somehow convince PHP not to reach for that file. Any chance you can help me investigate that?

**Comment by maltesedonkey** [comment]
Yep.  What can I do to help?  I don't know much about how Nextcloud works internally but am pretty OK on all things Linux.  Is it PHP that is looking to access timesyncd.conf or Nextcloud?  Even with apparmor banning it, Nextcloud worked fine across my platforms in terms of file sync.

**Comment by kyrofa** [comment]
Yeah it's PHP. Check the profile name, `snap.nextcloud.php-fpm`. That means it corresponding to [this app](https://github.com/nextcloud/nextcloud-snap/blob/master/snap/snapcraft.yaml#L29), which is as the name suggests, PHP. What's unclear is if this is hard-coded behavior in PHP, or perhaps controlled via its config.

**Comment by kyrofa** [comment]
Orrr, it's the app being RUN by PHP. [Here's the culprit](https://github.com/nextcloud/serverinfo/blob/master/lib/OperatingSystems/DefaultOs.php#L96).

**Comment by kyrofa** [comment]
This is what that file looks like on Ubuntu, which is a big fat nothing:

```bash
$ cat /etc/systemd/timesyncd.conf 
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See timesyncd.conf(5) for details.

[Time]
#NTP=
#FallbackNTP=ntp.ubuntu.com
#RootDistanceMaxSec=5
#PollIntervalMinSec=32
#PollIntervalMaxSec=2048
```

We can ship that in the snap as well to mask this denial, it will just get no NTP servers from it.

**Comment by kyrofa** [comment]
Note that I only see this denial when visiting the "System" menu in the settings (and then indeed it's about once a second). I also see several other denials:

```
Feb 25 12:40:06 protege kernel: [929524.214652] audit: type=1400 audit(1582663206.947:57564): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/df" pid=26620 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 25 12:40:06 protege kernel: [929524.217856] audit: type=1400 audit(1582663206.951:57565): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=26628 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 25 12:40:06 protege kernel: [929524.217917] audit: type=1400 audit(1582663206.951:57566): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=26628 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 25 12:40:06 protege kernel: [929524.221130] audit: type=1400 audit(1582663206.951:57567): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=26631 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 25 12:40:06 protege kernel: [929524.221315] audit: type=1400 audit(1582663206.955:57568): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=26631 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 25 12:40:06 protege kernel: [929524.222713] audit: type=1400 audit(1582663206.955:57569): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=26636 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 25 12:40:06 protege kernel: [929524.222714] audit: type=1400 audit(1582663206.955:57570): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=26636 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 25 12:40:06 protege kernel: [929524.224756] audit: type=1400 audit(1582663206.955:57571): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=26642 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 25 12:40:06 protege kernel: [929524.224758] audit: type=1400 audit(1582663206.955:57572): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=26642 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 25 12:40:06 protege kernel: [929524.226766] audit: type=1400 audit(1582663206.959:57573): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/sys/devices/virtual/net/docker0/operstate" pid=26645 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb 25 12:40:12 protege kernel: [929529.371435] kauditd_printk_skb: 208 callbacks suppressed
Feb 25 12:40:12 protege kernel: [929529.371436] audit: type=1400 audit(1582663212.103:57782): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=27235 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb 25 12:40:13 protege kernel: [929530.460926] audit: type=1400 audit(1582663213.191:57783): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=27322 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb 25 12:40:14 protege kernel: [929531.516028] audit: type=1400 audit(1582663214.247:57784): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=27335 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb 25 12:40:15 protege kernel: [929532.598625] audit: type=1400 audit(1582663215.331:57785): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=27348 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb 25 12:40:16 protege kernel: [929533.629837] audit: type=1400 audit(1582663216.363:57786): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=27361 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb 25 12:40:17 protege kernel: [929534.723200] audit: type=1400 audit(1582663217.455:57787): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=27452 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by maltesedonkey** [comment]
Yes - only when accessing the System menu.  Yesterday I must have had a tab open on that page as it was happening all the time.

Upon login I see one instance of

Feb 26 08:42:31 kernel: [654334.483116] audit: type=1400 audit(1582706551.905:2063): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/root/.rnd" pid=1146 comm="php-fpm" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

When in the System sub menu I see lines such as 

Feb 26 08:52:17 kernel: [654920.121341] audit: type=1400 audit(1582707137.545:2064): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/df" pid=1932 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 26 08:52:17 kernel: [654920.144163] audit: type=1400 audit(1582707137.569:2065): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=1939 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Feb 26 08:52:17 kernel: [654920.265287] audit: type=1400 audit(1582707137.685:2073): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/sys/devices/pci0000:00/0000:00:03.0/virtio0/net/ens3/operstate" pid=1956 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb 26 08:52:22 kernel: [654925.329995] audit: type=1400 audit(1582707142.753:2085): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=2019 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

There are also some script errors

Feb 26 08:52:17 Nextcloud: {"reqId":"N43tQoeq2OYwWdkzNEv4","level":3,"time":"2020-02-26T08:52:17+00:00","remoteAddr":"192.168.1.1","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/serverinfo","message":"Undefined variable: result at \/snap\/nextcloud\/19299\/htdocs\/apps\/serverinfo\/lib\/OperatingSystems\/DefaultOs.php#173","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36 OPR\/66.0.3515.103","version":"17.0.3.1"}
Feb 26 08:52:18 Nextcloud: {"reqId":"N43tQoeq2OYwWdkzNEv4","level":3,"time":"2020-02-26T08:52:18+00:00","remoteAddr":"192.168.1.1","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/serverinfo","message":"Invalid argument supplied for foreach() at \/snap\/nextcloud\/19299\/htdocs\/apps\/serverinfo\/templates\/settings-admin.php#101","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36 OPR\/66.0.3515.103","version":"17.0.3.1"}
Feb 26 08:52:19 Nextcloud: {"reqId":"zM2EQimL8R8tuVLiN4gr","level":3,"time":"2020-02-26T08:52:19+00:00","remoteAddr":"192.168.1.1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/serverinfo\/api\/v1\/\/diskdata?format=json","message":"Undefined variable: result at \/snap\/nextcloud\/19299\/htdocs\/apps\/serverinfo\/lib\/OperatingSystems\/DefaultOs.php#173","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36 OPR\/66.0.3515.103","version":"17.0.3.1"}
Feb 26 08:52:19 Nextcloud: {"reqId":"zM2EQimL8R8tuVLiN4gr","level":3,"time":"2020-02-26T08:52:19+00:00","remoteAddr":"192.168.1.1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/serverinfo\/api\/v1\/\/diskdata?format=json","message":"Invalid argument supplied for foreach() at \/snap\/nextcloud\/19299\/htdocs\/apps\/serverinfo\/lib\/Os.php#155","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36 OPR\/66.0.3515.103","version":"17.0.3.1"}

**Comment by kyrofa** [comment]
Alright, while annoying, I think we can safely ignore this. I'm going to go ahead and close, but feel free to continue discussion here. There's not a lot we can do other than working on the upstream app to make sure it only does things that are possible when under confinement.

**Comment by insaner** [comment]
In my case it's these messages every few seconds: 

> 2025-03-30T00:06:30.317249-04:00 minidell kernel: audit: type=1400 audit(1234567.315:1234567): apparmor="DENIED" operation="open" class="file" profile="snap.nextcloud.php-fpm" name="/proc/1234/comm" pid=12345 comm="admin" requested_mask="r" denied_mask="r" fsuid=0 ouid=120

operation="open"
 class="file"
 profile="snap.nextcloud.php-fpm"
 name="/proc/1234/comm"
 comm="admin"
 requested_mask="r"
 denied_mask="r"
 fsuid=0
 ouid=100


> 2025-03-30T00:06:36.336278-04:00` MY_HOST_HERE kernel: audit: type=1400 audit(1234567.334:1234568): apparmor="DENIED" operation="open" class="file" profile="snap.nextcloud.php-fpm" name="/proc/12345/smaps_rollup" pid=12345 comm="admin" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

 operation="open"
 class="file"
 profile="snap.nextcloud.php-fpm"
 name="/proc/12345/smaps_rollup"
 pid=12345
 comm="admin"
 requested_mask="r"
 denied_mask="r"
 fsuid=0
 ouid=0

**Comment by insaner** [comment]
In my case it's these messages every few seconds: 

> 2025-03-30T00:06:30.317249-04:00 MY_HOST_HERE kernel: audit: type=1400 audit(1234567.315:1234567): apparmor="DENIED" operation="open" class="file" profile="snap.nextcloud.php-fpm" name="/proc/1234/comm" pid=12345 comm="admin" requested_mask="r" denied_mask="r" fsuid=0 ouid=120

operation="open"
 class="file"
 profile="snap.nextcloud.php-fpm"
 name="/proc/1234/comm"
 comm="admin"
 requested_mask="r"
 denied_mask="r"
 fsuid=0
 ouid=100


> 2025-03-30T00:06:36.336278-04:00` MY_HOST_HERE kernel: audit: type=1400 audit(1234567.334:1234568): apparmor="DENIED" operation="open" class="file" profile="snap.nextcloud.php-fpm" name="/proc/12345/smaps_rollup" pid=12345 comm="admin" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

 operation="open"
 class="file"
 profile="snap.nextcloud.php-fpm"
 name="/proc/12345/smaps_rollup"
 pid=12345
 comm="admin"
 requested_mask="r"
 denied_mask="r"
 fsuid=0
 ouid=0
