### ISSUE TITLE
Shares Widget (of System Monitoring) is not scaled properly

### ISSUE THREAD

**Issue by cmasterdelphi** [nextcloud/nextcloud-snap#1274]
#### Describe the bug
The Monitoring Widget of Shares (Settings > Administration/System) does not scale properly
![image](https://user-images.githubusercontent.com/56067322/75763836-2f873600-5d3d-11ea-982c-1f3774466fe1.png)

#### To Reproduce
1. Login as Admin
2. Click on Profile Icon and Settings
3. Scroll down to Section Administration and Select "System" (should be last item)
4. Scroll down to Widget "Shares" and see the wrong scaled diagram

#### Expected behavior
Widget of Shares is scaled properly to fill out the widget so you can really see, how much space is used for what.

#### OS/snapd/snap version
Client OS: Windows 10x64 Build 1909 with Firefox x64 v73.0.1
Nextcloud: Nextcloud 17.0.3 (17.0.3snap1)

**Comment by szaimen** [comment]
This is an upstream bug...

**Comment by kyrofa** [comment]
Yeah please log this [upstream](https://github.com/nextcloud/server).
