### ISSUE TITLE
Let’s Encrypt CAA Rechecking Bug

### ISSUE THREAD

**Issue by samtygier** [nextcloud/nextcloud-snap#1275]
Let’s Encrypt have announced a bug in their certificate issuing.

https://community.letsencrypt.org/t/2020-02-29-caa-rechecking-bug/114591

And that to resolve it existing certificates will be revoked, and must be force renewed by March 4.

https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864

Will it be possible for the snap do perform this automatically?

**Comment by kyrofa** [comment]
Oh that's awful. Thank you for the heads up, we'll look into it.

**Comment by kyrofa** [comment]
This only effects 2.6% of **all valid Let's Encrypt certs**. My Nextcloud snap instance is not effected. Are you sure yours is?

**Comment by samtygier** [comment]
According to https://checkhost.unboundtest.com/ I am not effected. You might be right about the emergency update risk.

For someone who is effected, what would be the manual process force renew.

**Comment by lindhe** [comment]
I'm effected, and will need to renew. I had expected there to be a `nextcloud.renew-certs` command but there isn't. Is there a way of triggering a renewal manually, or do I have to delete the old certs and start over?

**Comment by kyrofa** [comment]
For anyone effected, here's what you do:

### Step 1: Force-renew your cert

Run this command. It should work regardless of your architecture, although I've only tested it on amd64:

    $ sudo snap run --shell nextcloud.occ -c 'export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"; . "$SNAP/utilities/https-utilities"; run_certbot renew --force-renewal'

It may look a little suspicious at the end, saying something similar to:

    Running post-hook command: restart-apache
    Output from post-hook command restart-apache:
    Restarting apache... error
    Certificates have been activated: using HTTPS only
    Certificates look to be in order: enabling HSTS
    httpd: error while loading shared libraries: libaprutil-1.so.0: cannot open shared object file: No such file or directory

Don't worry about that, it's because I gave you architecture-agnostic directions. We've now updated your cert, we just need to take care of...

### 2. Restart apache

    $ sudo snap restart nextcloud.apache

Now you should be up and running with a new cert, one that isn't effected by this bug.

**Comment by JokerGermany** [comment]
@kyrofa 
Thanks, but didn't work for me
Ubuntu Server 18.04
`sudo snap run --shell nextcloud.occ -c 'export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"; . "$SNAP/utilities/https-utilities"; run_certbot renew --force-renewal'
Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing
/var/snap/nextcloud/current/certs/certbot/config/renewal/nas.XXX.myfritz.net.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Plugins selected: Authenticator webroot, Installer None
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for cloud.XXX
http-01 challenge for cloud.XXX
http-01 challenge for cloud.XXX
http-01 challenge for nas.XXX
http-01 challenge for nas.XXX
http-01 challenge for nas.XXX
http-01 challenge for nas.XXX.myfritz.net
Cleaning up challenges
Attempting to renew cert (nas.XXX.myfritz.net) from /var/snap/nextcloud/current/certs/certbot/config/renewal/nas.XXX.myfritz.net.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Select the webroot for cloud.XXX:
Choices: ['Enter a new webroot', '/var/snap/nextcloud/current/certs/certbot']

(You can set this with the --webroot-path flag). Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /var/snap/nextcloud/current/certs/certbot/config/live/nas.XXX.myfritz.net/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

All renewal attempts failed. The following certs could not be renewed:
  /var/snap/nextcloud/current/certs/certbot/config/live/nas.XXX.myfritz.net/fullchain.pem (failure)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)`

**Comment by kyrofa** [comment]
> I needed to add the webroot-path

Huh, that shouldn't have been required. Obtaining the cert initially uses that so it should have been in the config. Any chance you've been editing the config manually? Regardless, I'm glad you got it working, thank you for sharing!

**Comment by lindhe** [comment]
The instructions worked for me. Did not need `--webroot-path`. Thanks!

**Comment by kyrofa** [comment]
We're about a month past that deadline and I haven't heard any more complaints, so I'm going to go ahead and close this. Obviously feel free to continue any discussion here.
