### ISSUE TITLE
Need a way to edit lib/private/Installer.php to fix timeout bug for downloading larger apps.

### ISSUE THREAD

**Issue by merrpink** [nextcloud/nextcloud-snap#1276]
#### Describe the bug
The timeout for app downloads is set to 120. This is not enough time for many, especially for large apps like community document server. The fix for this bug now (on regular installs) is to edit lib/private/Installer.php line 274 and insert a timeout number that will work for you. However, in the snap, this file is read only and I have not found a snap command to edit this line directly. 

#### To Reproduce
1. Open Nextcloud and try to download and install community doc server. 

#### Expected behavior
Throws a timeout error

#### OS/snapd/snap version
OS: Ubuntu server 18.04
snap: 2.43.3

    $ snap list nextcloud
Nextcloud 18-2020-03-03 (community doc server not available on lower versions).

and:

    $ snap version
2.43.3
#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by szaimen** [comment]
This will be fixed with 18.0.2

**Comment by merrpink** [comment]
> This will be fixed with 18.0.2
> At least when installing over occ

You are probably referring to the Nextcloud release. Do you know when snap will integrate this?

**Comment by kyrofa** [comment]
I'm afraid there is no manual fix, the snap's files are read-only. We're waiting for a few fixes in 18.0.2 before really testing it in earnest. Hopefully not long after that.

**Comment by merrpink** [comment]
> I'm afraid there is no manual fix, the snap's files are read-only. We're waiting for a few fixes in 18.0.2 before really testing it in earnest. Hopefully not long after that.

Ok thanks. I was hoping for some esoteric nextcloud.occ command that might be able edit that line....

**Comment by kyrofa** [comment]
Note that 18.0.2 didn't have the fixes we needed. We're still waiting...
