### ISSUE TITLE
Every time when iam trying to Logout, it takes a very long time

### ISSUE THREAD

**Issue by LinuxTux23** [nextcloud/nextcloud-snap#1282]
#### Describe the bug
Hi there, every time when i want to logout from the nextcloud web interface, it takes nearly forever to bring me to the login page.
Can u help to to clear this problem, and make my cloud faster ?

PS: I have installed it on a Raspberry Pi 4b with 4 GB of RAM, so i think the System has eneugh power to hande netxcloud.

Yours sincirly,

LinuxTux23

#### OS/snapd/snap version

nextcloud  17.0.3snap1  19303  stable    nextcloud✓  -

snap      2.43.3
snapd     2.43.3
series    16
raspbian  10
kernel    4.19.97-v7l+

**Comment by kyrofa** [comment]
There are a few factors here. Your CPU and your RAM are certainly among them, but drive access is another. You might need an SD card upgrade to get one with faster access, for example. Beyond that, there's not a lot we can do. The rpi is not tremendously fast, and the tech stack for Nextcloud is a lot. You can't expect performance to be comparable to a traditional server.
