### ISSUE TITLE
Slow internet and Fetcher.php

### ISSUE THREAD

**Issue by jlb181** [nextcloud/nextcloud-snap#1283]
I live out in the country and am only able to get a pretty slow DSL service.  The instance of nextcloud is for family use at home but unless I can change the line

$options = [
			'timeout' => 10,

in Fetcher.php I am unable to view or download apps.  I was running this on my RPI 4+ but the SD card failed so I am setting up on this machine.  My setting on the Pi was 'timeout' => 3600,

I am very new to snap and could use a little guidance on writing to a read only file system if possible.
I read the HACKING section of the readme but I'm afraid it's not clear to me.

**Comment by jlb181** [comment]
I was able to work around this by downloading the app tar.gz and, as root, extract them into .../extra-apps.  Then refresh the disabled apps page and enable the newly added app.   I still cannot use the app store via nextcloud.

**Comment by kyrofa** [comment]
I'm afraid that, unless upstream Nextcloud exposes this setting as something that is actually configurable (i.e. via `config.php`), you won't be able to configure it in the snap. Those core .php files are all read-only. The only way to change them is to build and maintain your own snap, or install Nextcloud via another method.
