### ISSUE TITLE
Fresh snap install is sending notification emails from a third-party provider.

### ISSUE THREAD

**Issue by theoden8** [nextcloud/nextcloud-snap#1284]
---

removed. turns out it was internal administration issue.

---

**Comment by kyrofa** [comment]
I'm afraid I can't explain this. The snap isn't special. In fact, while it's technically possible for a non-snap install to be able to send email out of the box (using sendmail), the snap can't even do that. As a result, if you indeed haven't set up any email, I have no idea how this is possible. Can you share the email headers?

**Comment by theoden8** [comment]
I believe that could be possible, if you [follow this link](https://snip.dssr.ch/?66a25d084a3af954#2yAWbZqzy963Px8RnZ2K4L79pSFaP65xjUV5Fin32aUZ). As a precaution I set expiration date for 1 month, which shouldn't cause any unnecessary rush.

**Comment by theoden8** [comment]
@kyrofa turns out this was due to another administrator's effort of setting up a postfix server.
