### ISSUE TITLE
nextcloud.enable-https usability issues

### ISSUE THREAD

**Issue by pavelschon** [nextcloud/nextcloud-snap#1291]
Command _nextcloud.enable-https_ has usability issues, but please consider this as a newbie feedback, not necessarily a bug.

Signature to install custom SSL certificate is:
```
nextcloud.enable-https custom [-h -s] <cert> <key> <chain>
```

I have two files generated by certbot, containing wildcard certificate:
```
example.com.fullchain.pem
example.com.privkey.pem
```

It's not clear how to pass those two files to the command which expects three files.
I suggest to provide more verbose help to the command.

**Comment by kyrofa** [comment]
If you're using certbot, why not just use `nextcloud.enable-https lets-encrypt`?

**Comment by pavelschon** [comment]
The reason was I have wildcard certificate, generated on other machine, used by more services, not only nextcloud. For that reason I cannot use builtin lets-encrypt command.

Since I have a https reverse proxy, I decided to stick with http on lan.
