### ISSUE TITLE
Cannot remove contact-list from Nextcloud-Snap

### ISSUE THREAD

**Issue by DJ-3ncoder** [nextcloud/nextcloud-snap#1294]
I read a lot about the contact menu in Nextcloud (server, not snap) and that users wish to remove it but it is not possible still now in snap. The issues got closed but nobody paid attention.

I am using: 17.0.5snap1

To me it is a security issue when every user could see all other users!

Please add in some setting to deactivate this on users but not on the admin-account!

**Comment by kyrofa** [comment]
> it is not possible still now in snap

I'm not clear on the issue, but the snap isn't doing anything special here. It sounds like whatever your issue is got fixed in upstream Nextcloud, is that right? Is it contained in a release, yet?

**Comment by DJ-3ncoder** [comment]
I do not know if it really got fixed but the issues got closed so I thought it got fixed.

The problem is, some of my users told me, that he could see all the other users and their full names and this is a big security issue because it is "standard" (default) configuration

**Comment by kyrofa** [comment]
Can you please refer me to the issue that got closed? I can tell you if it was fixed or not.

**Comment by DJ-3ncoder** [comment]
This is one example where somebody said, that users can see all other users on the installation:
https://github.com/nextcloud/server/issues/4656

**Comment by kyrofa** [comment]
It sounds like it was fixed ages ago. If you're still having issues with it please open [another issue upstream](https://github.com/nextcloud/server/issues/new/choose). Once it's fixed there it will be fixed in the snap as well.
