### ISSUE TITLE
Does nextcloud-snap support high availability?

### ISSUE THREAD

**Issue by R8s6** [nextcloud/nextcloud-snap#1300]
Can this snap be highly available, or with at least 1 duplicate that is always in-sync?  

Reason asking is because a machine will eventually fail, it would be awesome if the snap can be set up to be highly available. Yes, backup will be run as frequently as possible as well.

Thank you!

**Comment by kyrofa** [comment]
I'm afraid not, no. This is a standard LAMP snap, created to make things as simple as possible. Making it HA would significantly increase complexity, which defeats that primary purpose. If you want an HA Nextcloud, I'm afraid you'll need to do it on your own. I suggest kubernetes, perhaps https://microk8s.io/ .
