### ISSUE TITLE
Best way to keep Nexcloud from running before user mounts encrypted partition?

### ISSUE THREAD

**Issue by jpapadakis** [nextcloud/nextcloud-snap#1304]
I've been running with nexcloud-snap successfully for a while now with my data on an external drive. I'd like to now LUKS encrypt this external drive, which would require me to manually mount it before nextcloud-snap can use. Is there a clean way to ensure the nextcloud snap does not start at boot, expecting this drive to be mounted?

**Comment by kyrofa** [comment]
That's a good question, I'm not sure. I suggest starting a new thread on forum.snapcraft.io/ asking how one would go about doing this for a given snap that uses the `removable-media` interface. Feel free to tag me over there (same nick) and I can help ping the right folks.

**Comment by jpapadakis** [comment]
Okay, I'll see about making a post there. So far, I'm thinking systemctl disable for the nextcloud snap could be an option, as I understand this will stop it from starting on boot. Then I could manually start after mounting. I'll also give this a try.

**Comment by jpapadakis** [comment]
I've made a post on the snapcraft forum [here](https://forum.snapcraft.io/t/getting-snap-to-wait-on-boot-for-user-to-mount-encrypted-drive/16764). It looks like I can indeed use `systemctl` to disable (not start at boot) via `systemctl disable snap.nextcloud.*` some of the nextcloud snap's services, however, I don't know which one(s) would be best to disable, or if this would cause any problems. 

Options:

```
snap.nextcloud.apache.service 
snap.nextcloud.nextcloud-fixer.service
snap.nextcloud.mdns-publisher.service   
snap.nextcloud.php-fpm.service
snap.nextcloud.mysql.service            
snap.nextcloud.redis-server.service
snap.nextcloud.nextcloud-cron.service   
snap.nextcloud.renew-certs.service
```

**Comment by kyrofa** [comment]
I'm not sure how well disabling snap services will persist after a refresh, but it's worth a try. Note, however, that I can't promise these service names will never change, so keep an eye on your logs.

Off the top of my head, the following services will need your external media mounted:

- snap.nextcloud.php-fpm.service
- snap.nextcloud.nextcloud-cron.service

**Comment by jpapadakis** [comment]
Okay did a bit more digging. It looks like snapd offers some [control](https://snapcraft.io/docs/service-management) in this area. 

Running a `snap stop --disable nextcloud` and rebooting showed:
```
$ sudo snap services
Service                    Startup   Current   Notes
nextcloud.apache           disabled  inactive  -
nextcloud.mdns-publisher   disabled  inactive  -
nextcloud.mysql            disabled  inactive  -
nextcloud.nextcloud-cron   disabled  inactive  -
nextcloud.nextcloud-fixer  disabled  inactive  -
nextcloud.php-fpm          disabled  inactive  -
nextcloud.redis-server     disabled  inactive  -
nextcloud.renew-certs      disabled  inactive  -
```
Then after a `snap start nextcloud`:
```
$ sudo snap services
Service                    Startup   Current  Notes
nextcloud.apache           disabled  active   -
nextcloud.mdns-publisher   disabled  active   -
nextcloud.mysql            disabled  active   -
nextcloud.nextcloud-cron   disabled  active   -
nextcloud.nextcloud-fixer  disabled  active   -
nextcloud.php-fpm          disabled  active   -
nextcloud.redis-server     disabled  active   -
nextcloud.renew-certs      disabled  active   -
```
This seems to persist between reboots as well.

**Comment by kyrofa** [comment]
Ah ha! THAT is probably the way to go.

**Comment by jpapadakis** [comment]
Yeah this has worked out great. So after a one time `snap stop --disable nextcloud`. I then do the following after a reboot to decrypt and mount my LUKS encrypted drive and start Nextcloud:

```
cryptsetup open /dev/disk/by-uuid/<uuid-of-my-disk> <volume-mapper-name>
mount /dev/mapper/<volume-mapper-name> <mount-point>
snap start nextcloud
```

This has been running successfully after a few days and a couple of reboots. Thanks Kyle!

**Comment by pachulo** [comment]
Thanks a lot for the info @jpapadakis , this should be written in the Wiki!
