### ISSUE TITLE
Nextcloud Talk asking for A TURN server

### ISSUE THREAD

**Issue by mau2806** [nextcloud/nextcloud-snap#1315]
#### Describe the bug
nextcloud Talk plugin works but only in local network. If external user is connecting to nextcloud talk over port forwarded connection (firewall) error message:
Could not establish a connection with at least one participant. A TURN server might be needed for your scenario.
snap image with nextcloud 17.06 didn't show this error message. 
Has the TURN Server been part of 17.06?
Is the TURN Server part of 18.04?

#### To Reproduce
1. Create nextcloud Talk Session in Intranet
2. Connect to this Talk Session as participant connect to this Session from Internet.  Nextcloud is visible in Internet via port forwarding (http -> lets encrypt, https -> nextcloud)
3. Error message: Could not establish a connection with at least one participant. A TURN server might be needed for your scenario.

#### Expected behavior
On version 17.05 (snap package) participiants can share calls without creating a TURN server outside the SNAP package

#### Screenshots
N.A.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

and:

    $ snap version

/var/snap/nextcloud# uname -a
Linux raspberryaul 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
root@raspberryaul:/var/snap/nextcloud# snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  18.0.4snap1  20500  latest/stable  nextcloud✓  -
root@raspberryaul:/var/snap/nextcloud# snap version
snap      2.44.3
snapd     2.44.3
series    16
raspbian  10
kernel    4.19.97-v7l+

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by derhagen** [comment]
The need for a TURN server in a WebRTC video chat arises, when a direct connection between participants is not possible. Often, the reason for this is a NAT in between them, which explains why everything works fine in your local network. You could try installing a TURN server (e.g. coturn), which is not part of a Nextcloud and configuring it for nextcloud talk or adjust your NAT setting. This is most likely not an issue with nextcloud itself.

**Comment by mau2806** [comment]
I am using the nextcloud snap image and it ran until yesterday with video calls via "talk" behind a firewall (fritz!box). After snap packages updated to 18.04 calls with external partners throw the message "Could not establish a connection with at least one participant. A TURN server might be needed for your scenario". Because the snap package contained all things needed for "talk" app I wondered if the updated snap package changed behaviour.
https://nextcloud-talk.readthedocs.io/en/latest/TURN/
Chapter "Background" describes that there is a STUN Server provided by nextcloud Coporation which is used by default. I suspect that this STUN Server enabled my calls by "Talk" up to now as stated in the documentation:
"Nextcloud Talk will try direct P2P in the first place, use STUN if needed and TURN as last resort fallback. Thus to be most flexible and guarantee functionality of your Nextcloud Talk instance in all possible connection cases, you would want to setup a TURN server."

Is there any change in the snap package (update 17.06 -> 18.04) which can cause the need of the TURN Server ?

**Comment by kyrofa** [comment]
The snap has changed nothing here other than including Nextcloud 18 instead of 17. With no more information I'd agree with @derhagen that this was a networking issue, not a Nextcloud issue, but the fact that this worked fine in v17 is interesting, thus it _could_ be a bug in Nextcloud 18.

> Is there any change in the snap package (update 17.06 -> 18.04) which can cause the need of the TURN Server ?

No, the snap shouldn't be getting in your way, here.

**Comment by mau2806** [comment]
It seems that nextcloud 18 with my infrastructure in place needs a TURN server. I installed one behind my firewall  and the TALK server is running again. The default STUN Server provied by nextcloud is now replaced too (by the TURN server) in the configuration.
No changes in the nextcloud-snap package are necessary for that.
Thanks!
