### ISSUE TITLE
php-soap missing - can't install nextcloud OpenOTP two factor authentication app

### ISSUE THREAD

**Issue by dfs90** [nextcloud/nextcloud-snap#1317]
#### Describe the bug
The OpenOTP two factor authentication app cannot be installed as php-soap is missing.

#### To Reproduce
1. Open your nextcloud and log in
2. Go to 'Apps'
3. Try to install "OpenOTP"
4. Installation will fail as "soap" is missing

#### OS/snapd/snap version
latest version of Ubuntu Server, snapd and nextcloud snap

Could you please add the php-soap dependency in order to make the OpenOTP app work?
Thank you! :-)

**Comment by kyrofa** [comment]
Sorry, we have a standing policy of not packing dependencies in to enable apps other than the core (bundled) apps, otherwise the snap would grow to infinite size.
