### ISSUE TITLE
18.0.4snap1 documentserver_community install timeout

### ISSUE THREAD

**Issue by rebootit** [nextcloud/nextcloud-snap#1319]
####18.0.4snap1 documentserver_community install timeout for slow connexion
I cannot install the documentserver_community app on slow connexion server due to timeout of 300 sec. On regular install you can change the setting by increasing this timeout in lib/private/Installer.php but on the snap this Installer.php il not writtable.

#### To Reproduce
1. Go to app store
2. Click on download and activate
3. With slow connexion it result in: cURL error 28: Operation timed out after 119998 milliseconds with 238593596 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by kyrofa** [comment]
Indeed, that file is not writable in the snap. This needs a proper fix upstream. Until then, though, note that the CLI has no timeout, so you can run `sudo nextcloud.occ app:install documentserver_community`.
