### ISSUE TITLE
Nextcloud asset cache doesn't play nice with snap's revert capability

### ISSUE THREAD

**Issue by allanp5979** [nextcloud/nextcloud-snap#1323]
Hi,

I had a problem with my IMAP mailboxes just sitting 'Loading' but never loading in the last few days. After updating the ubuntu machine the problem was still there so I thought I would just try reverting to the previous snap installation. I issued the 'sudo snap revert nextcloud'  and it performed everything correctly. I rebooted the server but now when any user logs in via web browser the main page loads but none of the files. The IMAP still has the same problem so I am going backwards. Right now I would like to just get the files back! 

Notes
- If you use a nextcloud app such as that from an android phone then all files are there so there is nothing wrong with the files it is something to do with the browser access.

- Also it has an error regarding the cronjob not being run for the last 4 days! - this was not the case before the revert it was happy with the cronjobs.

Any suggestions to get me back to where we can see files via browser again?

**Comment by pachulo** [comment]
This is likely because of this: https://github.com/nextcloud/nextcloud-snap/issues/753#issuecomment-431996652

And if you have you data on an external directory, you would need something like what I did here: https://github.com/nextcloud/nextcloud-snap/issues/753#issuecomment-576916512

**Comment by allanp5979** [comment]
I have removed the cache and rebuilt as per #753 and that seems to have overcome the problem of the files not displaying on the web browsers. Thanks pachulo. I will now see if I can try and diagnose further the original problem of the IMAP contents not loading.

Thanks again.

**Comment by kyrofa** [comment]
Thank you for logging this issue @allanp5979, and @pachulo for the quick response. I'm re-opening for two reasons:

1. The ability to revert the snap is one of our main selling points-- it should work, darnit
2. Maybe this is something we can fix

There are two ways we can fix this, as far as I can tell: automatically blow away the cache and rebuild it whenever e.g. Apache fires up, or add a feature upstream to save this cache somewhere OTHER than the data dir.

The first option (blow it away at startup) sounds easy, but only for the default case. We'll need to support someone moving the datadir as well, which means we'll need to figure out where it is before we blow it away.

I actually quite like the second option. This cache is version specific. When you upgrade, it gets regenerated. When you rollback, you should be using the one that was used by the previous version. If we can define where that should be via an environment variable (much like the feature we added to have the config file located via an environment variable) we can put this cache in `$SNAP_DATA`, which is versioned.

**Comment by kesselb** [comment]
The caching logic for SCSS, JavaScript and Icons is quite complex. I'm not sure if you are able to place those assets somewhere else easily or at all.

Routine to clean and regenerate the assets is part of `occ maintenance:repair`. If you run that after downgrade the assets should be all right.

**Comment by kyrofa** [comment]
Ah! A third option, love it. Thanks @kesselb, that seems the obvious path.
