### ISSUE TITLE
Disable Updater

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud-snap#133]
Updater is not used in Nextcloud snap ... and it is not possible to use it or to change the channel 😁 
We should disable it, because it irritates users about the updating process of their Nextcloud 😉 

@kyrofa @oparoz

**Comment by kyrofa** [comment]
Dupe of #32. Yeah, definitely annoying, but needs some experimentation regarding how to best do it. Can I just not include that app? Will the integrity check fail? Do I have to just "disable" it somehow via `occ`?
