### ISSUE TITLE
button problem in spreed - snap related ?

### ISSUE THREAD

**Issue by Refhi** [nextcloud/nextcloud-snap#1334]
I've posted a (now closed) issue about an icon problem in spreed which might be related to snap install as it seems to happen on snap install but not docker install (same spreed & nextcloud version, clean install tested). Unfortunately I couldn't test it on other kinds of installation.

_Originally posted by @Refhi in https://github.com/nextcloud/spreed/issues/3404#issuecomment-626146685_

**Comment by kyrofa** [comment]
I can duplicate. Sounds like an issue with the app making some improper assumptions about where its assets are (e.g. assuming they're going to be in the nextcloud root when in fact they aren't in the snap). Not something we can fix from here, I'm afraid, you'll need to keep pushing on that issue.
