### ISSUE TITLE
sharing community documentserver from snap

### ISSUE THREAD

**Issue by scubamuc** [nextcloud/nextcloud-snap#1335]
Unable to share community documentserver from nextcloud-snap

Nextcloud-snap stable release incl. community documentserver app running on Server with ample resssources. Both servers encrypted with Letsencrypt.

Connect ONLYOFFICE App on hosted cloud instance to nextcloud-snap instance running community documentserver. 

It should be possible to connect a hosted cloud instance ONLYOFFICE App to a Nextcloud-snap instance running community-document server.

Any ideas?

**Comment by szaimen** [comment]
> It should be possible to connect a hosted cloud instance ONLYOFFICE App to a Nextcloud-snap instance running community-document server.

This is technically not possible.

Why not install the community-documentserver on the hosted cloud instance?

**Comment by scubamuc** [comment]
> Why not install the community-documentserver on the hosted cloud instance?

this was my first plan. Since the hosted cloud instance has limited PHP-Memory (128MB) it is not possible to install community-documentserver on hosted instance.

Thanks for the Info.
