### ISSUE TITLE
Fix to reverse proxy wiki page

### ISSUE THREAD

**Issue by samtygier** [nextcloud/nextcloud-snap#1338]
https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy has instructions for setting up a reverse proxy with HAProxy.

In the second code listing, under the `backend nextcloud-https` section the line `option forwardfor` should be removed as this only valid for http mode and generates a warning.

**Comment by kyrofa** [comment]
Fixed, thank you!
