### ISSUE TITLE
Cannot display the users autocomplete list on "Comments" when put @

### ISSUE THREAD

**Issue by sgdox** [nextcloud/nextcloud-snap#1339]
#### Describe the bug
I upgraded from Nextcloud 17.0.5 to 18.0.4, and now:

When a user select a file previusly shared, then he go to "Comments" an then try to mention to another user using @ there is not user to select, and cannot make a mention.
Whe we try to mention to the admin account there is possible, but only manually: @admin.  
There is not possible to mention to a user that have a space in her name like:@name last name
There is not possible to get users list whit autocomplete when we put @, before we did the upgrade (nextcloud 17.0.5) we could do that.

It is important to say that I am using LDAP user and group backend and and and before upgrading to version 18.0.4 the mentions in the files worked fine

#### To Reproduce
Into a file options in nextcloud, try to make a mention to a user that previusly shared a file. There is not option to mention it. Before 18.0.4 upgrade the users use the @ to find others users.

Screenshots
![image](https://user-images.githubusercontent.com/27734020/82254713-f9f3f100-9918-11ea-9957-37db54c489e4.png)
![image](https://user-images.githubusercontent.com/27734020/82258873-3c6cfc00-9920-11ea-9ae9-2858dfaf0072.png)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  18.0.4snap1  20498  latest/stable  nextcloud✓  -

and:

root@nextcloud:~# snap version
snap    2.44.3
snapd   2.44.3
series  16
ubuntu  18.04
kernel  4.15.0-99-generic

**Comment by szaimen** [comment]
This is probably an upstream issue with userids with spaces in it.
https://github.com/nextcloud/documentation/issues/1774

**Comment by sgdox** [comment]
> This is probably an upstream issue with userids with spaces in it.
> [nextcloud/documentation#1774](https://github.com/nextcloud/documentation/issues/1774)

No, because we are using LDAP user and group backend, and before upgrading nextcloud to 18.0.4 we could do that. Tenemos Nextcloud aproximadamente 1 año en modo de producción

**Comment by sgdox** [comment]
THIS IS A BUG IN 18.0.4 Version:
In a new instance of Nextcloud snap 18.0.4, same problem happens, user autocomplete "@" cannot be accessed in comments. This instance does not have additional modules installed.

![image](https://user-images.githubusercontent.com/27734020/82274671-5cafb180-9946-11ea-83ea-497c3c90eb6c.png)

**Comment by kyrofa** [comment]
I can confirm that this is an issue. However, this works fine on the sharing tab, so I agree that this sounds like upstream Nextcloud breakage.

**Comment by sgdox** [comment]
There is any solution for this issue??

**Comment by kyrofa** [comment]
Please log this issue [upstream](https://github.com/nextcloud/server) to get more traction. There's nothing we can really do here.

**Comment by sgdox** [comment]
But resolve this issue is very important to the correct function of nextcloud snap 18.0.4, please can you move it to the parent Nextcloud issue repo?

**Comment by kyrofa** [comment]
> But resolve this issue is very important to the correct function of nextcloud snap 18.0.4

Oh agreed, and I'd say it's important to the correct function of nextcloud in _general_. But the fact remains that we can't make changes to Nextcloud shipped in the snap, those changes have to come from upstream.

> please can you move it to the parent Nextcloud issue repo?

I can't actually-- I don't have permission to do so.

**Comment by kyrofa** [comment]
I'm going to go ahead and close the tracking of the issue here. As mentioned, it should be logged upstream. There's nothing we can do here.
