### ISSUE TITLE
Nextcloud: update to v19

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#1342]
Nextcloud 19 isn't released yet, but it's time to start testing its RCs at least.

**Comment by kyrofa** [comment]
I've got 19.0.0RC2 out in the `19/candidate/rc2` channel. This is **not** ready for production use, but I'd love some help testing this to see if we need to log any bugs before it comes out. I'd very much like to upgrade to v19 when it's released (ish) instead of waiting several point releases (cc @pachulo).

**Comment by kyrofa** [comment]
Testing fresh install first.

- A quick glance at the overview page in the settings leads me to believe we'll need to build in the `bcmath` PHP module, which seems fine.
- When I tried to install the calendar app I got "Exception: could not download app calendar" which worried me. But then I was able to install the contacts app no problem. Then I tried installing the calendar app again and it worked. That error was also accompanied by a warning "Could not connect to appstore: cURL error 35: Unknown SSL protocol error in connection to apps.nextcloud.com:443 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)". Sounds like a temporary network issue, but I'll poke at it again and make sure.
- Calendar app appears to work well
- Contacts app won't let me create a new contact. Turns out I need to go to settings and create a new address book before I can do that. Sounds like a fairly typical hooks problem (the calendar app has this every other release or so, too). Logged as https://github.com/nextcloud/contacts/issues/1635 . Probably not blocking for us though.

**Comment by kyrofa** [comment]
When I tried a fresh install with recommended apps, I ended up not having onlyoffice. I hopped into the apps settings and I see that the document server isn't marked as being compatible with v19, so that probably isn't surprising. @kesselb can you confirm?

**Comment by kyrofa** [comment]
Upgrade from stable (18.0.4) seems to be fine as well without the recommended apps. With them and you end up with onlyoffice getting disabled because it's not compatible, which again is not a surprise.

**Comment by kesselb** [comment]
> Will the "recommended apps" support v19 before release?

I think so.

**Comment by pachulo** [comment]
Let's see if I cant test this this week, I'm quite busy right now...

**Comment by kyrofa** [comment]
@szaimen do you know of any v19 blockers?

**Comment by szaimen** [comment]
> @szaimen do you know of any v19 blockers?

@kyrofa no, none that I am aware of.
We should nonetheless wait for the release and see if some new major bugs get reported.
Also some apps haven't got updated yet for NC19 (e.g. the onlyoffice app) and I would wait probably until 19.0.1 is out.

BTW: for the new passwordless login is a new PHP module required:
https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html
it is called `bcmath`

**Comment by kyrofa** [comment]
Alright, RC3 is out in the `19/candidate/rc3` channel:

    $ sudo snap install nextcloud --channel=19/candidate/rc3

Or if you already have it installed (not recommended for production installs):

    $ sudo snap refresh nextcloud --channel=19/candidate/rc3

**Comment by kyrofa** [comment]
Also, thanks for that @szaimen :) .

**Comment by szaimen** [comment]
BTW: is the old `ResourceLocator can not find a web root` error finally resolved on NC19?

**Comment by Surenthiran** [comment]
v19 is released in production when we can expect it in snap.

**Comment by kyrofa** [comment]
Please see #1353 for current status. You're welcome to help test it as well.
