### ISSUE TITLE
Cannot install Community Document Server.

### ISSUE THREAD

**Issue by merrpink** [nextcloud/nextcloud-snap#1350]
`cURL error 28: Operation timed out after 119947 milliseconds with 259864932 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Filed a bug report a while ago and was told it would be fixed in 18.02. Now we are many versions later than that as I am running Edge. Stable is at 18.04. However, I am still getting the same error and cannot download Community Doc Server. Do I have to do something manually?

OS is Ubuntu 18.04

**Comment by szaimen** [comment]
Yes, run 
`nextcloud.occ app:install documentserver_community` or using the occ web app `occ app:install documentserver_community` should do the trick

**Comment by merrpink** [comment]
@aszaimen Thank you, that did the trick. Unfortunate that users cannot just click and download the normal way...

**Comment by szaimen** [comment]
@merrpink That is an Nextcloud Server Upstream issue and cannot get fixed by the snap, AFAIK.

**Comment by kyrofa** [comment]
We agree this this is an unfortunate issue, but indeed, there's nothing the snap can do about this. Please [log a bug upstream](https://github.com/nextcloud/server).

**Comment by pachulo** [comment]
This should work better when we get the 18.0.5 (or 19.0.0) update:

- https://github.com/nextcloud/server/pull/21053
- https://github.com/nextcloud/server/pull/21050
