### ISSUE TITLE
HTTPS still redirects even after turning it off

### ISSUE THREAD

**Issue by Dunked0n** [nextcloud/nextcloud-snap#1351]
I tried to enable https but now I changed my mind and so I tried to disable it but now it keeps redirecting to https, giving an error, and i cant make it stop, where can I find the config file?

**Comment by kyrofa** [comment]
Did you use Let's Encrypt? If so you're probably being bitten by HSTS. You need to tell your browser to forget your URL.

**Comment by kyrofa** [comment]
I believe this question has been answered, so I'll close, but feel free to continue discussion here and we can re-open as necessary.
