### ISSUE TITLE
No files listed in public shared folders & browser asks for authentication

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/nextcloud-snap#1354]
I refer to some other issues that describe exactly the same problem I have.
There I also found a solution to enable the AllowOverwrite property but the apache config and .htaccess file are read-only.

https://github.com/nextcloud/server/issues/6885
https://github.com/nextcloud/server/issues/6600
https://github.com/nextcloud/server/issues/8448

I really don't know how to solve the problem myself ...

And this is the solution I found but can't apply because read-only apache and .htaccess configs:
https://github.com/nextcloud/server/issues/6885#issuecomment-342764047

OS: Ubuntu Server 18.04
Snap-Channel: 18/stable
Nextcloud-Version: 18.0.4snap2

**Comment by Pilzinsel64** [comment]
I found out, that happen only behind the Proxy in my company, not on the mobile phone. Could be because the proxy? Because also in the this [comment](https://github.com/nextcloud/server/issues/6885#issuecomment-342764047) described how to add trusted proxies.

**Comment by kyrofa** [comment]
I can't duplicate, this sounds like a proxy issue indeed.

**Comment by Pilzinsel64** [comment]
Yes, adding it to the trusting proxy was the result for the empty file list. However, I missed it somehow. Thanks you very much!
