### ISSUE TITLE
How can I stop the nextcloud?

### ISSUE THREAD

**Issue by 160610101** [nextcloud/nextcloud-snap#1357]
How can I stop the nextcloud that I've already deployed with snap? 
It can't seem to stop like a docker container,like:
`docker stop #id`
Do I have to delete this app? like:
`sudo snap remove nextcloud`

**Comment by jotoho** [comment]
You can do `sudo snap stop nextcloud` to stop Nextcloud and `sudo snap start nextcloud` to start it back up.

**Comment by 160610101** [comment]
> You can do sudo snap stop nextcloud to stop Nextcloud and sudo snap start nextcloud to start it back up.

It works.
Thank you so much!

**Comment by kyrofa** [comment]
Thanks @jotoho! Note that you can stop/start individual services in the snap as well with the same command. I believe this question has been answered, so I'll close it, but feel free to continue discussion here.
