### ISSUE TITLE
Cannot update to 10.0.2

### ISSUE THREAD

**Issue by canoxnet** [nextcloud/nextcloud-snap#136]
My nextcloud box today offered me the update to version 10.0.2, but I can not update to this version.

I have no write permission in the /snap/nextcloud folder

Does anyone have a solution

**Comment by kyrofa** [comment]
The snap will update to 10.0.2 on its own. The updater app needs to be removed (#32), we just haven't gotten there yet.

**Comment by kyrofa** [comment]
Keep an eye on #135 and you'll know when to expect an update.
