### ISSUE TITLE
Nextcloud: update to 18.0.6

### ISSUE THREAD

**Issue by pachulo** [nextcloud/nextcloud-snap#1374]
Here we go: https://github.com/nextcloud/server/releases/tag/v18.0.6

**Comment by stondino00** [comment]
Looks like this has made the change-log page now and includes that fix.

https://nextcloud.com/changelog/#latest18

**Comment by username72764274** [comment]
There is an issue with that release: https://github.com/nextcloud/server/issues/21348

**Comment by stondino00** [comment]
I had no issues or errors upgrading to the 18.0.6 PR.
