### ISSUE TITLE
switch from 18/edge to latest/stable

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/nextcloud-snap#1375]
#### Describe the bug
a way to switch from edge to stable

#### To Reproduce
1. snap refresh nextcloud --channel=latest/stable
2. nextcloud complains about downgrading being unsupported

**Comment by kyrofa** [comment]
Upstream nextcloud doesn't support downgrading like that. Snaps can help you a little by giving you the ability to revert after you accidentally did that refresh (`sudo snap revert nextcloud`), but then you lose any changes you made while on `18/edge`. If that's okay with you, then I suggest a revert. If not, you might be a little stuck until 18.0.6 is shipped (which will be soon).

**Comment by Fuseteam** [comment]
@kyrofa so 18.0.6 will be a stable release? when will that release? that way i can at least pause updates untill after 18.0.6, as to prevent edge passing the stable version

**Comment by Fuseteam** [comment]
cool thanks and yes considering i am already on edge it _should_ be fine

**Comment by kyrofa** [comment]
Haha, thanks! 18.0.6 has now been released to stable, so you should try getting back on that.

**Comment by Fuseteam** [comment]
wow that was quick thanks :smile: switching now
