### ISSUE TITLE
Grid view in a shared photo folder consumes a lot of CPU and memory

### ISSUE THREAD

**Issue by derhagen** [nextcloud/nextcloud-snap#1383]
#### Describe the bug
I uploaded a folder of 150 photos, each 3-6MB. I shared the folder with a public link. Opening the link and viewing single photos works fine, but switching to grid view consumes a lot of CPU and memory. In this case, it uses all of my 2GB of memory. Might this have something to do with the missing imagick package? 

#### OS/snapd/snap version
```
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  18.0.6snap1  21521  latest/stable  nextcloud✓  -
```
```
$ snap version
snap    2.45
snapd   2.45
series  16
ubuntu  18.04
kernel  4.15.0-106-generic
```

**Comment by kyrofa** [comment]
> Might this have something to do with the missing imagick package?

No, that's only used for theming. What is your PHP memory limit set to?

**Comment by derhagen** [comment]
> No, that's only used for theming. What is your PHP memory limit set to?

512MB

**Comment by kyrofa** [comment]
That seems sensible. I'd say this is just a good-old poorly-behaving application. I suggest reporting the issue upstream and see if they can do things more efficiently.
