### ISSUE TITLE
After upgrade to 20.04/21521 mysql daemon doesn't start

### ISSUE THREAD

**Issue by kscherer** [nextcloud/nextcloud-snap#1384]
After a recent upgrade the nextcloud snap does not start because mysql does not start. This prevents the php services from starting. There aren't many clues, there are only a few apparmor and seccomp denies in the logs:

    Jun 22 13:31:52 strad nextcloud.mysql[41976]: 2020-06-22T17:31:52.700522Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
    Jun 22 13:31:52 strad nextcloud.mysql[41976]: 2020-06-22T17:31:52.701720Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
    Jun 22 13:31:52 strad nextcloud.mysql[41976]: 2020-06-22T17:31:52.701760Z 0 [ERROR] Aborting
    Jun 22 13:31:52 strad audit[41995]: AVC apparmor="DENIED" operation="exec" profile="snap.nextcloud.mysql" name="/bin/systemctl" pid=41995 comm="mysql.server" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
    Jun 22 13:31:52 strad kernel: audit: type=1400 audit(1592847112.732:216): apparmor="DENIED" operation="exec" profile="snap.nextcloud.mysql" name="/bin/systemctl" pid=41995 comm="mysql.server" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
    Jun 22 13:31:52 strad nextcloud.mysql[41981]: Starting MySQL
    Jun 22 13:31:53 strad audit[42191]: SECCOMP auid=4294967295 uid=0 gid=0 ses=4294967295 pid=42191 comm="mysqld" exe="/snap/nextcloud/21521/bin/mysqld" sig=0 arch=c000003e syscall=49 compat=0 ip=0x7f4f459ed877 code=0x50000
    Jun 22 13:31:53 strad kernel: audit: type=1326 audit(1592847113.368:217): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=42191 comm="mysqld" exe="/snap/nextcloud/21521/bin/mysqld" sig=0 arch=c000003e syscall=49 compat=0 ip=0x7f4f459ed877 code=0x50000
    Jun 22 13:31:55 strad nextcloud.mysql[41981]: ... * The server quit without updating PID file (/tmp/pids/mysql.pid).
    Jun 22 13:31:55 strad nextcloud.mysql[41921]: Waiting for MySQL...

    > snap list nextcloud
    Name       Version      Rev    Tracking       Publisher   Notes
    nextcloud  18.0.6snap1  21521  latest/stable  nextcloud✓  -
    > snap version
    snap    2.45
    snapd   2.45
    series  16
    ubuntu  20.04
    kernel  5.4.0-37-generic

Looking at the mysql/error.log shows a problem with creating the socket:

    2020-06-23T00:53:42.590496Z 0 [ERROR] Can't start server : Bind on unix socket: Operation not permitted
    2020-06-23T00:53:42.590531Z 0 [ERROR] Do you already have another mysqld server running on socket: /tmp/sockets/mysql.sock ?
    2020-06-23T00:53:42.590554Z 0 [ERROR] Aborting

This snap has been running without problems on this machine for over a year. /var/snap is on a bind mount to a larger disk and this has worked well. Enabling debug mode doesn't give any more information. What can I do to debug this?

**Comment by kyrofa** [comment]
If you do a `sudo snap restart nextcloud.mysql`, do you see anything telling in the syslog? Any sort of denial, perhaps?

**Comment by kyrofa** [comment]
And you're not using parallel snap installs or anything funky like that?

**Comment by kyrofa** [comment]
Sorry, typing as I'm thinking: can I please see the output of `snap interfaces`?

**Comment by kscherer** [comment]
Thank you Kyle for taking the time to help me.

The syslog snippet has all the entries related to mysql.

The only "funky" thing I am doing is the bind mount of the /var/snap dir but that worked well for long time

    > snap interfaces nextcloud
    Slot  Plug
    -     nextcloud:network
    -     nextcloud:network-bind
    -     nextcloud:removable-media

Turns out this error goes away and the nextcloud install is working after reverting to 21413 so that should help narrow it down.

**Comment by kyrofa** [comment]
> working after reverting to 21413

Dang you shattered my theory. But this is still interesting, none of your interfaces are connected. Can I please see the output of:

- `snap list`, and
- `dpkg -l | grep snapd`

**Comment by kscherer** [comment]
> snap list
    Name       Version      Rev    Tracking       Publisher   Notes
    core       16-2.45      9289   latest/stable  canonical✓  core
    core18     20200427     1754   latest/stable  canonical✓  base
    nextcloud  18.0.4snap4  21413  latest/stable  nextcloud✓  -
    > dpkg -l | grep snapd
    ii  snapd                                  2.44.3+20.04                      amd64        Daemon and tooling that enable snap packages

**Comment by kyrofa** [comment]
Well this is officially super weird. My theory it wrong, it just looks like all the Nextcloud snap's interfaces got disconnected for some unknown reason. Try getting it up to date again and manually connect them. Does it work?

    $ sudo snap connect nextcloud:network
    $ sudo snap connect nextcloud:network-bind
    $ sudo snap connect nextcloud:removable-media   # Only if you did this in the past, this does not happen by default

**Comment by kscherer** [comment]
Okay after connecting the network and running `snap refresh nextcloud` it is working with the latest 21521. The only thing I can think of was that I was trying to prevent nextcloud from automatically starting because there is a race condition between zfs mount and the bind mount of /var/snap that breaks many things. It looks like I will have to manually `snap disable nextcloud` before the next restart and then enable it after the mounts are in place manually.

Thanks!!
