### ISSUE TITLE
mixed content error

### ISSUE THREAD

**Issue by Surenthiran** [nextcloud/nextcloud-snap#1388]
Mixed Content: The page at 'https://cloud.futurisk.in/index.php/apps/files/?dir=/&fileid=6' was loaded over HTTPS, but requested an insecure form action 'http://cloud.futurisk.in/extra-apps/richdocumentscode/proxy.php?req=/loleaflet/d125c71/loleaflet.html?WOPISrc=https%3A%2F%2Fcloud.futurisk.in%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F180617_ocpwfc5jg7bd&title=test%201%20.docx&lang=en&closebutton=1&revisionhistory=1'. This request has been blocked; the content must be served over HTTPS.

server updated to version 19 tried to use edit document am getting this error. please let me know what other details you need address this issue. 

server is running in ubuntu 20 in virual box under windows server 2012

**Comment by kyrofa** [comment]
Please log an issue against https://github.com/CollaboraOnline/richdocumentscode/ , I don't believe this has anything to do with the snap specifically, just how collabora works with HTTPS.
