### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by EberhardHuebner** [nextcloud/nextcloud-snap#1389]
#### Describe the bug
the php-modul in snap 19.0.0 reports still security error
with the imagicks i know the using is not recommende but nessesary for me
our clients students do not believe the real security report scan only this message is important
![nextcloud snap 19 0 0](https://user-images.githubusercontent.com/67425294/85733997-f49a7b00-b6fc-11ea-88cd-34c80a1b7453.jpg)

#### To Reproduce
1. Go to 'spersonal tap
2. Click on '.overview'

. See error

#### Expected behavior
no security warning for the theme using
#### Screenshots
screenshots 

#### OS/snapd/snap version 19.0.0
What OS and ubuntu server 20.04.1

**Comment by kyrofa** [comment]
I'm afraid I don't speak German, but I believe the only warning you're seeing there is that you're using theming and imagick isn't installed, right? Is there anything else there? If not, that's not security-related at all. In fact, it would be a security issue to HAVE imagick, which is why the snap doesn't. Or are you asking something else?

**Comment by scubamuc** [comment]
es gab in der Vergangenheit hier bereits einige Diskussionen bzgl. der "Sicherheitswarnung". Diese "Sicherheitswarnung" ist meiner Meinung nach eher eine Optimierungsmeldung. 

Die Meldung schlägt vor: 
Eine Optimierung kann dadurch erreicht werden wenn das Paket imagick installiert wird!

Die Anwendung erwartet, dass "imagick" im Snap enthalten ist. Aus Sicherheitsgründen haben sich die Entwickler um Nextcloud-Snap dagegen entschieden das Paket im Snap mitzuliefern. 

Durch das fehlende Paket ist lediglich die "Favicon" Umwandlung und Bereitstellung im Nextcloud-Snap eingeschränkt.

**Comment by enoch85** [comment]
Please read this: https://github.com/nextcloud/server/issues/13099

It's actually better without it.

**Comment by kyrofa** [comment]
Thank you both! I'll go ahead and close this.

**Comment by EberhardHuebner** [comment]
Thanks for your help, understand now the reason.Maybe solved the message in the next NC version.

**Comment by Fuseteam** [comment]
> Please read this: [nextcloud/server#13099](https://github.com/nextcloud/server/issues/13099)
> 
> It's actually better without it.

i noticed its still giving that warning on nextcloud 20 fwiw

**Comment by enoch85** [comment]
@Fuseteam 

> Please read this: nextcloud/server#13099

It's actually better without it.

**Comment by Fuseteam** [comment]
> @Fuseteam
> 
> > Please read this: [nextcloud/server#13099](https://github.com/nextcloud/server/issues/13099)
> 
> > It's actually better without it.

i mean I get that I'm just saying its still telling new users the opposite ano 2021

**Comment by kyrofa** [comment]
@Fuseteam you're preaching to the choir, @enoch85 and I have both tried to get upstream Nextcloud to change this. Neither of us have the power to make it happen. We'd love to see that warning disappear, and even better, for Nextcloud to stop relying on imagick altogether.

**Comment by Fuseteam** [comment]
ah i see, so i guess upstream doesn't want to change it

**Comment by tbjers** [comment]
It's now May 2022 and I just got an imagick warning. I am a necromancer, bringing dead threads back to life!

**Comment by kyrofa** [comment]
Please read the thread you're trying to bring back to life-- none of us have the ability to change it. Looks like things might change for Nextcloud 24, though.

**Comment by tbjers** [comment]
> Please read the thread you're trying to bring back to life

Oh, I read the thread, and basically every other thread--directly or otherwise--linked to this issue. And, I did bring it back to life to marvel at how it's been 3 years. But, I digress. I am preaching to the choir.
