### ISSUE TITLE
Snap shouldn't allow skipping major versions

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#1393]
Upstream Nextcloud doesn't support skipping major versions. The snap makes it a bit too easy to do that. We should check versions in the post-refresh hook and fail the refresh if a major version is being skipped.

**Comment by Sergeeeek** [comment]
I think it just happened to me. As far as I remember I had version 17 last time I checked, now server is stuck in maintenance mode. nextcloud.occ tells me
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
```
But it refuses all connections and running nextcloud.occ upgrade gives me:
```
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
```

nextcloud.occ also reports the current version as **19.0**

How can I get it back up?

**Comment by kyrofa** [comment]
Sorry for the delay @Sergeeeek! I'm glad to see you got the fix, but more generically, in case other folks stumble over this, there's a [wiki page with guidance for all sorts of similar situations](https://github.com/nextcloud/nextcloud-snap/wiki/What-do-I-do-if-an-update-breaks-Nextcloud%3F)

**Comment by Sergeeeek** [comment]
No problem, I found the solution in 15 mins, don't expect you to answer that quickly 😄 

As for the wiki page, for some reason when I googled "nextcloud snap" + this error: 
``` 
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
```
Or this error: 
``` 
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
```
I couldn't find that wiki page, only some old forum posts about Nextcloud 12.

I think it would be great if those errors were put into the wiki page so that it comes up close to top results in Google.

**Comment by kyrofa** [comment]
Ah excellent idea-- done!
