### ISSUE TITLE
DAVx5 not working with a self-signed certificate

### ISSUE THREAD

**Issue by ghost** [nextcloud/nextcloud-snap#1394]
#### Describe the bug
A clear and concise description of the bug.
The DAVx5 app doesn't work when using HTTPS and a self-signed ceriticate; it says "Connection security problem (error code 3)

#### To Reproduce
1. Install the Nextcloud Android app and DAVx5 (From F-Droid)
2. Open the Nextcloud app and go to settings, click on "Sync calendar & contacts"
3. DAVx5 will open, showing the error.

#### Expected behavior
DAVx5 letting me log in to my NC account to sync my calendar and contacts.

#### Screenshots
GitHub won't let me send the screenshot so I uploaded it here: https://upload.disroot.org/r/yx41wYsu#3ZNe58YxlJT7yQYmHl4f1unyyZkUc2Fcc+1ig8siguI=

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
```
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  19.0.0snap1  21796  -         nextcloud✓  -
```

and:

    $ snap version

```
snap    2.45.1
snapd   2.45.1
series  16
ubuntu  20.04
kernel  5.4.0-39-generic
```

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

Not really needed, plus the output is too big for my terminal.

**Comment by kyrofa** [comment]
> when using HTTPS and a self-signed ceriticate; it says "Connection security problem (error code 3)

This is a problem with your use of self-signed certs. If the Android app doesn't allow for trusting a given cert, there's nothing we can really do to help you on the snap side. Is there a reason you can't use Let's Encrypt and get a properly trusted cert?

**Comment by kyrofa** [comment]
Closing both due to inactivity and due to the fact that I don't believe there's anything we can do on the snap side to improve this situation.
