### ISSUE TITLE
Nextcloud 19 does not update file modified time for non-administrative user

### ISSUE THREAD

**Issue by ratheesb** [nextcloud/nextcloud-snap#1395]
Nextcloud (19) Web interface doesn’t update last modified time for edited files specially for Onlyoffice files (it updates sometime after 10-30 minutes). But files are updated after few seconds when I download and check it manually. And this problem does not persist when nextcloud logged in as administrator. This is for only non-administrative user and only in Nextcloud snap 19 on ubuntu server 20.

**Comment by kyrofa** [comment]
This doesn't sound like it's specific to the snap. Mind [logging against upstream nextcloud](https://github.com/nextcloud/server/issues/new/choose)?
