### ISSUE TITLE
Command 'nextcloud.occ' not found...

### ISSUE THREAD

**Issue by Rajicn** [nextcloud/nextcloud-snap#1400]
Ubuntu server 20.04 (clean installation)
used snap install nextcloud
got nextcloud 19.0.0snap1
 Installation was fine,no errors, everything is great but i want to redirect all traffic to use https and check and setup trusted domains so i found https://github.com/nextcloud/nextcloud-snap#configuration and tried with command:
`sudo nextcloud.occ config:system:get trusted_domains`
and got error:
```
Command 'nextcloud.occ' not found, but can be installed with:

snap install nextcloud
```
Soon I figured that i disabled nextcloud and after eneblig it i got message 
`root@home:/snap/bin# nextcloud.occ config:system:get trusted_domains
Command 'nextcloud.occ' is available in '/snap/bin/nextcloud.occ'
The command could not be located because '/snap/bin' is not included in the PATH environment variable.
nextcloud.occ: command not found
`

finally i added ./ in fron of command (file name) and it worked.
`root@home:/snap/bin# ./nextcloud.occ config:system:get trusted_domains
192.168.10.10
sub.tld.com
`
I havent managed to find solution for this anywhere on the net, so I think it would be nice to be added somewhere in manuals...

**Comment by kyrofa** [comment]
You need to make sure `/snap/bin` is on your $PATH.
