### ISSUE TITLE
cURL error 28: Operation timed out after 120000 milliseconds

### ISSUE THREAD

**Issue by Achim222** [nextcloud/nextcloud-snap#1401]
Hi
i have a problem install Apps, Notes etc.,

cURL error 28: Operation timed out after 120000 milliseconds with 295506 out of 611041 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

I Just edit: Installer.php, line 274. Change 120 to 300. where can I find the file ?

thanks

 snap    2.45.1+20.04
snapd   2.45.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-40-generic

nextcloud  19.0.0snap1  21796  latest/stable  nextcloud✓  -

**Comment by kyrofa** [comment]
I'm afraid the snap doesn't support patching the PHP files. This needs to be fixed upstream. As a workaround, you can install with `nextcloud.occ` which doesn't have a timeout.

**Comment by Achim222** [comment]
thanks,
i am newbie for snap and nextcloud.occ
how should I do that ?

thamks

**Comment by kyrofa** [comment]
Like this:

    $ sudo nextcloud.occ app:install <app name>

**Comment by kyrofa** [comment]
I'm going to go ahead and close this because I think the question is answered, but feel free to continue discussion here.

**Comment by Achim222** [comment]
okay, thanks!
but nothing happens
![Bildschirmfoto zu 2020-07-14 08-29-55](https://user-images.githubusercontent.com/38311579/87392328-9b5f9200-c5ac-11ea-9420-acd5a3af44f6.png)
 ! the Cursor blinks

**Comment by LyimeS** [comment]
> Like this:
> 
> ```
> $ sudo nextcloud.occ app:install <app name>
> ```

thank you, sir :)

**Comment by Fuseteam** [comment]
> I'm afraid the snap doesn't support patching the PHP files. This needs to be fixed upstream. As a workaround, you can install with `nextcloud.occ` which doesn't have a timeout.

as of right now the maximum upload size can be set with `snap set nextcloud php.upload-max-filesize` couldn't we have something similar for the curl timeout?

**Comment by Fuseteam** [comment]
> > as of right now the maximum upload size can be set with `snap set nextcloud php.upload-max-filesize`
> 
> That's not actually true.

eh? I'm positive I managed to do that just this weekend 

> > couldn't we have something similar for the curl timeout?
> 
> No, that particular timeout is hard-coded in Nextcloud. Not even the snap itself can patch those files-- they're contained in a squashfs image that is by definition read-only.

oh bummer

**Comment by Fuseteam** [comment]
oh

> > > as of right now the maximum upload size can be set with `snap set nextcloud php.upload-max-filesize`
> > 
> > 
> > That's not actually true.
> 
> eh? I'm positive I managed to do that just this weekend
oh I stand corrected :thinking:
