### ISSUE TITLE
Rainloop not working with nextcloud 19.0.0snap1

### ISSUE THREAD

**Issue by henry-sa** [nextcloud/nextcloud-snap#1405]
After upgrading Nextcloud snap 18 to 19.0.0snap1 Rainloop is not working anymore - it's not loading. Also the admin page is not accessible anymore. I gues its may some issue with rights. Reinstall and install does not help

**Comment by scubamuc** [comment]
Hi henry-sa, this is a known issue... see here [https://github.com/pierre-alain-b/rainloop-nextcloud/issues/201] . I have the same problem and have decided to revert to the previous version until pierre has come up with a patch.

By the way, there is a workaround for Nextcloud-Snap: 
[https://github.com/pierre-alain-b/rainloop-nextcloud/issues/201#issuecomment-648938762]

**Comment by henry-sa** [comment]
Hello,
thank you - I did not find the other issue yet. Thank you - I'lll try. At the moment I also use snap18 instead of 19.

**Comment by kyrofa** [comment]
Indeed, this does not appear to be an issue with the snap. For anyone who got bit by this and needs to revert and stay on v18 until it's fixed, see the [What do I do if an update breaks Nextcloud](https://github.com/nextcloud/nextcloud-snap/wiki/What-do-I-do-if-an-update-breaks-Nextcloud%3F) article.
