### ISSUE TITLE
ONLYOFFICE integration problems

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/nextcloud-snap#1413]
#### Describe the bug
I have had problems with ONLYOFFICE since it came out within NC Hub. The problems are described [in this issue](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/312)
Quote:

> When then editing the new document with the web based document editor, the editing works fine and all changes are stored in the file. However, the last modified date of the file is not changed in nextcloud. The sync client will not pick up any changes and the local file on the clients will remain the empty.

Supposedly, author of that issue claims "_on another nextcloud instance that uses a regular file system backend instead of block storage, but is otherwise configured identically, this problem does not exist._" His issue exists on block storage and he was able to fix it by adding `allow_local_remote_servers' => true,` to the config.php. This however, doesn't affect my issue in any way and according to what the author said, it should be working fine for me considering I dont use block storage on my installation. Might it be this is snap-related?

#### To Reproduce
1 Create new world document using MS World/Libre office and sync it to NC
2 open said document using onlyoffice and perform edits (append something to the bottom etc)
3 Notice that:

- "Modified" data hasn't changed
- If you try to download that edited file it will not download with the changes you made using onlyoffice
- If you're syncing this file with your PC locally, it won't sync with the edited data

Note: The changes you made via onlyoffice will be visible only if you use onlyoffice to open that document.

#### Expected behavior
Modified date should change, NC should pick up the changes made by onlyoffice in web. 

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  19.0.1snap1  22327  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.45.2
snapd   2.45.2
series  16
ubuntu  20.04
kernel  5.4.0-42-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by joserick** [comment]
Hi!,

Yesterday a client gave me this problem and I managed to solve it realizing that the "CRON" had not been executed in 3 months, for which I proceeded to execute it manually (`php -f cron.php`), and after a minute and half, the date of the previously modified document It was updated, to which I considered that the Onlyoffice somehow storage the task of updating dates in this process of "CRON" and not in "AJAX"

To which based on the documentation of Nextcloud -> "[Background jobs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron)" I was able to make the CRON run once every minute.

And magically the dates of the files began to be updated between 1 and 2 minutes of waiting
