### ISSUE TITLE
Find old installation data after uninstalling snap

### ISSUE THREAD

**Issue by andiskufi** [nextcloud/nextcloud-snap#1417]
Hi,
I uninstalled my snap Nextcloud version on my Raspberry Pi but I forgot to back up my data folder.
When the snap was uninstalling it was showing that it was copying my data but it didn’t say where the data was copied. Does anyone know where I can find my files?
Thanks,
Andi

**Comment by kyrofa** [comment]
You're right, snapd, the daemon running your snap, takes [automatic snapshots](https://snapcraft.io/docs/snapshots) periodically, including when the snap is removed. For example, I just installed the snap, created an admin user, and uploaded some stuff. Then I uninstalled the snap. Now I can run `snap saved` to take a look at my snapshots. Look near the bottom:

```
$ snap saved
Set  Snap                  Age    Version                   Rev    Size    Notes
<snip>
343  nextcloud             23.8h  19.0.1snap1+git1.f4c9f02  22369   686MB  auto
344  nextcloud             11.6h  19.0.1snap1+git1.4671dc6  22379  20.6MB  auto
345  nextcloud             43.6s  19.0.1snap2               22400  21.4MB  auto
```

See that last one is a little over 40 seconds old? I can restore that snapshot like so:

```
$ sudo snap restore 345
Restored snapshot #345.
```

That gives me my data back:

```
$ ls /var/snap/nextcloud/
22400/  common/
```

But it doesn't re-install the snap. Let's do that real quick:

```
$ sudo snap install nextcloud
nextcloud 19.0.1snap2 from Nextcloud✓ installed
```

And voila, we're back up and running where we were before.

**Comment by andiskufi** [comment]
Then I think that I lost my data as after uninstalling I installed a new snap version and if I do the command I get only the new version

`pi@andipi:~ $ snap saved`
`Set  Snap          Age        Version        Rev       Size       Notes`
`1    nextcloud  20d7h  19.0.0snap1  21798  4.54GB  auto`

Am I correct or there is still hope?

**Comment by kyrofa** [comment]
Ah, your backup is from 19.0.0snap1? No this is super hacky, but uninstall the snap again and try this (**only if you're on amd64**, tell me if you're not):

1. Restore your backup (you may have already done this): `sudo snap restore 1`. At this point, all of your data is in `/var/snap/nextcloud/common` if you're just looking to move it somewhere else. You might want to grab a backup of that directory now, just in case.
2. Copy the old revision's data to the new revision's data directory: `sudo cp -a /var/snap/nextcloud/21798 /var/snap/nextcloud/22400`
3. Install Nextcloud: `sudo snap install nextcloud`

See if that works.

**Comment by andiskufi** [comment]
No. The data I want to recover is from version 15 something dev channel. Because I wanted to have the latest version I uninstalled it without backing up my data. When it was uninstalling it was showing that it was copying my data somewhere. After it finished I installed the 19.0.0 version and my data was not there. Sorry if I confused you but before trying anything it's best I believe you have the whole picture

**Comment by kyrofa** [comment]
Huh, yeah given that you only have one snapshot I'm not sure where that might be. However, your backup is over 4GB, so something is definitely in there! What is it?

**Comment by andiskufi** [comment]
They are the new data I inserted after the installation. Mostly whatever I had on the old one just missing some stuff I had forgotten to back up. Anyway if it's not something easy don't stress yourself to much. Thank you very much for trying to help. I really appreciate it :)

**Comment by kyrofa** [comment]
Of course, I'm sorry I couldn't help more :( .
