### ISSUE TITLE
wont finish installing. Permission Denied

### ISSUE THREAD

**Issue by torqx** [nextcloud/nextcloud-snap#1419]
**does not finish installing on MX-Linux 18.  (although is shows "sparky 5:12")**
$ snap version
snap    2.42.1
snapd   2.42.1
series  16
sparky  5.12
kernel  4.15.0-1-amd64
**NextCloud installation fails with the following message:**
error: cannot perform the following tasks:
- Run configure hook of "nextcloud" snap if present (run hook "configure": cannot create temporary directory for the root file system: Permission denied)

**Comment by kyrofa** [comment]
> MX-Linux 18

I... have no idea what this is. But given that this works on so many other Linux distributions, I suspect that your snapd is either out of date or there is some other snapd-related issue.

**Comment by kyrofa** [comment]
I'm going to close this for now given that this sounds like an internal snapd bug. I suggest logging an issue [against snapd](https://bugs.launchpad.net/snapd).
