### ISSUE TITLE
Theming app disabled after reboot with unmounted disk

### ISSUE THREAD

**Issue by code-by-gijs** [nextcloud/nextcloud-snap#1420]
#### Theming app disabled after reboot with unmounted disk
I have an encrypted disk that I mount manually. So when I reboot my ubuntu, by default, the data directory is not yet mounted. After mounting the disk nextcloud works fine. The only thing is that the theming app is disabled. When I manually enable the theming app, all the theme settings I did previously are up and running.

#### To Reproduce
1. Disable auto-mount of an external disk
2. Reboot your system
3. Manually mount your disk
4. Browse to your nextcloud instance
5. You see that the theming app is disabled.

#### Expected behavior
It's expected that the theming app will be enabled after the reboot.

#### OS/snapd/snap version
nextcloud: 19.0.1snap2
snap: 2.45.2
os: Ubuntu 20.04 on raspberry pi 4 8gb

#### Logs
No errors are shown in the logs.

**Comment by kyrofa** [comment]
The snap isn't doing anything special here. Just to be clear, is this disk mounted in `/media` somewhere so Nextcloud starts up without a data directory? Or are you using this disk for all of `/var` for example?

**Comment by code-by-gijs** [comment]
It’s mounted in `/mnt`. The mount works fine. Only thing is that after mounting, the theming app is disabled.

**Comment by kyrofa** [comment]
Yeah I'm not concerned about the mount itself, just curious what it's being used for. Can I see the output of the [issue debugging script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts), please?

**Comment by code-by-gijs** [comment]
I can see with the debug script it's running a fixer script after reboot:
```-- Reboot --
Jul 28 06:56:36 cloud systemd[1]: Started Service for snap application nextcloud.nextcloud-fixer.
Jul 28 06:56:39 cloud nextcloud.nextcloud-fixer[1420]: Waiting for Apache...
Jul 28 06:56:55 cloud nextcloud.nextcloud-fixer[1420]: done
Jul 28 06:56:57 cloud nextcloud.nextcloud-fixer[1420]: Waiting for Nextcloud to be installed...
Jul 28 06:57:45 cloud nextcloud.nextcloud-fixer[1420]: done
Jul 28 06:57:45 cloud nextcloud.nextcloud-fixer[3739]: run-parts: executing /snap/nextcloud/22408/fixes/fresh-install/1_disable-theming.sh
Jul 28 06:57:45 cloud nextcloud.nextcloud-fixer[3740]: Disabling theming by default...
Jul 28 06:57:46 cloud nextcloud.nextcloud-fixer[3740]: done
Jul 28 06:57:46 cloud nextcloud.nextcloud-fixer[3739]: run-parts: executing /snap/nextcloud/22408/fixes/fresh-install/2_add-missing-indices.sh
Jul 28 06:57:47 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the share table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the filecache table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the twofactor_providers table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the login_flow_v2 table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the whats_new table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the cards table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the cards_properties table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the calendarobjects_props table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the schedulingobjects table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Check indices of the oc_properties table.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3857]: Done.
Jul 28 06:57:48 cloud nextcloud.nextcloud-fixer[3739]: run-parts: executing /snap/nextcloud/22408/fixes/fresh-install/3_add-missing-columns.sh
Jul 28 06:57:49 cloud nextcloud.nextcloud-fixer[3919]: Check columns of the comments table.
Jul 28 06:57:49 cloud nextcloud.nextcloud-fixer[3919]: Done.
Jul 28 06:57:49 cloud nextcloud.nextcloud-fixer[3739]: run-parts: executing /snap/nextcloud/22408/fixes/fresh-install/4_convert-filecache-bigint.sh
Jul 28 06:57:51 cloud nextcloud.nextcloud-fixer[3980]: All tables already up to date!
Jul 28 06:57:51 cloud nextcloud.nextcloud-fixer[3739]: run-parts: executing /snap/nextcloud/22408/fixes/fresh-install/99_record_snap_version.sh
Jul 28 06:57:51 cloud systemd[1]: snap.nextcloud.nextcloud-fixer.service: Succeeded.

**Comment by code-by-gijs** [comment]
Great! I've now created an .ocdata file in my unmounted folder. Now, everthing works fine after mounting! Would it not be better if nextcloud would check the config file for the installed status?

**Comment by kyrofa** [comment]
> Would it not be better if nextcloud would check the config file for the installed status?

The problem is that the config file is PHP. We leave parsing PHP to Nextcloud, and we parse the json output of `occ` instead. It seems it's checking more than just that file.
