### ISSUE TITLE
Broken symlinks cause "nextcloud.occ files:scan" to malfunction, and oc_filecache corruption

### ISSUE THREAD

**Issue by Pajkastare** [nextcloud/nextcloud-snap#1425]
#### Describe the bug
If a broken symlink (a symlink that leads to an invalid/nonexistent location) is placed in the files directory under a user, and "nextcloud.occ files:scan [username | --all] -v" is executed, invalid entries such as "/username/files////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////Readme.md" are listed. And added to the oc_filecache table, as the "path". There seems to be one additional entry one "/" longer until the [currently] 4000 bytes limit to the "path" field in the database is reached, after which error messages will be displayed stating that the path is too long.

This will cause the oc_filecache files to get very large. I observed oc_filecache file sizes of > 900 MB, for about 5000 files, which is not reasonable in any way.

#### To Reproduce
Before reproducing:
1. "cd /var/snap/nextcloud/current/mysql"
2. "ls -al nextcloud/oc_filecache*"
3. Note the filesizes

1. Go to the directory that is the root of the Nextcloud files area, the one defined by "datadirectory" in /var/snap/nextcloud/current/nextcloud/config/config.php
2. "cd username/files"
3. "ln -s /invalid/directory/that/does/not/exist"
4. "nextcloud.occ files:scan username -v"
5. Watch the invalid paths scroll by (or omit the "-v" to speed this process up a bit)
6. "cd /var/snap/nextcloud/current/mysql"
7. "ls -al nextcloud/oc_filecache*"
8. Observe the larger filesizes compared to before before

#### Expected behavior
The "nextcloud.occ files:scan [username | --all] -v" should ignore broken/invalid symlinks, and not create invalid paths in the database.
Also, an automatic and periodic database optimization step to reduce filesizes would be nice, but not really relevant for this bug report.

#### Screenshots
The explanation should be enough.

#### OS/snapd/snap version
What OS and version are you running? 
Raspberry Pi 4 (4 GB RAM), Ubuntu 20.04 64-bit, snap version of Nextcloud (but I would guess that this problem is present in the non-snap version as well, but I have not tested that myself) as installed the standard snap way. No local compile of anything nextcloud-related. Ubuntu is kept up-to-date.

Additional info that I don't think is relevant to this bug report, but it doesn't hurt to define it:
- I have configured "removable media", and overlay-mounted an ZFS filesystem (ZFS as provided by apt under Ubuntu 20.04, which is version 0.8.3) under /mnt. But Nextcloud itself is installed on the ext4 SD card the Raspberry Pi is booting from. (I don't use ZFS on root.)

    $ snap list nextcloud
```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  19.0.1snap2  22408  latest/stable  nextcloud✓  -
```
    $ snap version
```
snap    2.45.2
snapd   2.45.2
series  16
ubuntu  20.04
kernel  5.4.0-1015-raspi

```
    $ uname -a
`Linux ubuntu 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
`

#### Logs
Don't have them, I fixed the problem and moved on... And then thought that I should create a bug report.

#### A workaround for other persons who might get this problem:
0. Backup everything
1. Remove all invalid symlinks under the Nextcloud data directory
2. snap start nextcloud
3. cd /var/snap/nextcloud/current/mysql
4. nextcloud.mysql-client nextcloud
5. show table status like "oc_filecache";
6. SELECT * FROM oc_filecache WHERE path LIKE '%//%'; # Sanity-check that this catches invalid entries
6. DELETE FROM oc_filecache WHERE path LIKE '%//%';
7. OPTIMIZE TABLE oc_filecache;
8. Ctrl-D (to exit mysql-client)
9. snap stop nextcloud; snap start nextcloud; sleep 5; nextcloud.mysql-client nextcloud # This might be unnecessary
10. SELECT * FROM oc_filecache WHERE path LIKE '%//%'; # Should be an empty set
11. show table status like "oc_filecache"; # Should only contain valid stuff
12. Ctrl-D (to exit mysql-client)
13. nextcloud.occ files:scan --all -v
14. Done.

**Comment by Pajkastare** [comment]
Clarification: The snap installed MySQL. (As evident from the executable filename, but since some do run Nextcloud with other SQL backends it might as well be stated here.)

I also noted that I got an additional, but relatively small, reduction in oc_filecache* sizes if I execeuted "ALTER TABLE oc_filecache FORCE;" prior to the OPTIMIZE step, but I don't know enough SQL to explain why.

**Comment by kyrofa** [comment]
Both nextcloud and `occ` are vanilla, there's nothing we can do about this here. Would you mind logging this issue against [upstream Nextcloud](https://github.com/nextcloud/server), please?
