### ISSUE TITLE
Default share permissions does not have an effect

### ISSUE THREAD

**Issue by g4ndy** [nextcloud/nextcloud-snap#1427]
#### Describe the bug
Default share permissions does not have an effect - started with 19.01snap2

#### To Reproduce
1. Go to settings - sharing - Default share permissions
2. Uncheck checkboxes for default share permissions
3. Share folder with an user and default share permissions will not be taken into account (user will be set with all share permissions enabled - undesirable and potentially dangerous behvior)

#### Expected behavior
Default share permissions should be taken into account when sharing with an user.

#### OS/snapd/snap version
Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-42-generic x86_64)

$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  19.0.1snap2  22400  latest/stable  nextcloud✓  -

and:

    $ snap version
snap    2.45.2
snapd   2.45.2
series  16
ubuntu  20.04
kernel  5.4.0-42-generic

**Comment by kyrofa** [comment]
This sounds like an upstream Nextcloud bug, please [log it there](https://github.com/nextcloud/server).
