### ISSUE TITLE
How to change data directory on external drive when changing server

### ISSUE THREAD

**Issue by BuckarooToo** [nextcloud/nextcloud-snap#1446]
I am using a Raspberry Pi 4 and Ubuntu. I have previously set up Nextcloud, and have my data on an external drive. Now, I am booting the Raspberry Pi 4 from a new microSD card, and reinstalled Ubuntu and Nextcloud. My data is still on the external drive. After enabling removable media, and changing the path of the data directory, I still do not see my files in Nextcloud. I suspect this is because the database has not been updated to reflect the files in the data folder on the external drive. Is that correct, and is there a way to force the database to update, or do I have to manual move the files again?

**Comment by kyrofa** [comment]
Try `sudo nextcloud.occ files:scan --all` and see if that resolves things for you.

**Comment by BuckarooToo** [comment]
Yes, that did it! I might suggest adding that to the Wiki section for external storage. Thanks!

**Comment by kyrofa** [comment]
Ah excellent, thanks for reporting back. I'll go ahead and close this then, but feel free to continue discussion here.
