### ISSUE TITLE
Problem opening tif file

### ISSUE THREAD

**Issue by ioneng** [nextcloud/nextcloud-snap#1449]
I'm having trouble opening any tif or tiff file. I have enabled tiff preview in config.php, ran files:scan on the tiff file folder and preview generator did generate previews for every tif file in @_thumb folder. Howeven when I click on a tif file in files or photos. A blank preview screen shows up: 
![image](https://user-images.githubusercontent.com/9411407/92555124-4ee1bb80-f2aa-11ea-84c5-e59283bfd3d2.png)

I'm starting to think that this might be a snap problem as tiff support was not built-in? Please help.

**Comment by ioneng** [comment]
I just found out that camera raw preview app was trying to open the preview but failed. After I disabled camera raw preview app, I can no longer go into the preview screen. It only allows me to download tif file now. The file downloaded ok, I can open it in windows photo app to see it. So it means ‘OC\Preview\TIFF’  is not working. Can someone try to open a tif file on their setup and see whether it's just my problem or tif is not supported on snap installation.

**Comment by kyrofa** [comment]
I can confirm this doesn't appear to be working, I get prompted to download them as well. Sadly, it seems to be failing completely silently, so it's impossible to know why. There's nothing we can do about it here, consider logging this upstream.

**Comment by szaimen** [comment]
The camera raw preview app depends on imagick to open TIFF files successfully, afaik.

**Comment by ioneng** [comment]
I end up just installing nextcloud manually. Snap is much easier to set up but if you want the full experience, it's just not good enough yet.

**Comment by kyrofa** [comment]
> it's just not good enough yet.

Heh, I'm afraid that if you need imagick it'll never be good enough :wink: .
