### ISSUE TITLE
Disable output buffering

### ISSUE THREAD

**Issue by TeHashX** [nextcloud/nextcloud-snap#1450]
It's possible to disable?
<img width="693" alt="ob" src="https://user-images.githubusercontent.com/1405188/92724509-65077e80-f373-11ea-9fd8-49e84240bd83.png">

**Comment by kyrofa** [comment]
Yeah totally, thanks for the heads up, we'll look into it. Your version is obviously beyond v19, what channel are you on?

**Comment by TeHashX** [comment]
Latest/edge

**Comment by takanotume24** [comment]
I'm getting the same error.
The channel is latest/edge.
```
Nextcloud 20.0.0 RC1 Build:2020-09-17T23:34:15+00:00 45cf49bbca1563b69ea7b73ea3497c91651cc313
```
