### ISSUE TITLE
Network Monitoring (Settings > System) does not show correct information

### ISSUE THREAD

**Issue by cmasterdelphi** [nextcloud/nextcloud-snap#1451]
#### Describe the bug
The Network Monitoring Tool (which can be found under Settings > System) does not show the correct information of the IP and speed

#### To Reproduce
1. Login as Admin
2. Go to Settings > System and scroll to Network (see screenshot)
3. See wrong Information

#### Expected behavior
See correct information about Network (IP, Speed, etc)

#### Screenshots
Screenshot of Netcloud
![grafik](https://user-images.githubusercontent.com/56067322/92740001-b0bf2580-f37d-11ea-9902-a1b04b49ca42.png)

Screenshot of my NIC
![grafik](https://user-images.githubusercontent.com/56067322/92741265-b5d0a480-f37e-11ea-90be-7dabb13c46d1.png)

#### OS/snapd/snap version
OS: Ubuntu 18.04
Snap: 19.0.2

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by kyrofa** [comment]
Can you check your syslog while visiting that page? You might see a bunch of denials, can you share them? I suspect we'll need to add another network-related interface to access that information under confinement.

**Comment by cmasterdelphi** [comment]
Sure, I checked the syslog while visiting the page, but there is not really anything in there.
I'll attach the syslog as well as the script (which I didnt run before)

[syslog.txt](https://github.com/nextcloud/nextcloud-snap/files/5207564/syslog.txt)

[debugscript.log](https://github.com/nextcloud/nextcloud-snap/files/5207561/debugscript.log)
)

**Comment by kyrofa** [comment]
> Sep 11 07:23:52 bg11 kernel: [3004003.802522] audit: type=1400 audit(1599809032.971:1805): apparmor="DENIED" operation="exec" profile="snap.nextcloud.php-fpm" name="/bin/ip" pid=24737 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0

Yep, that's exactly what I needed. Give #1455 a shot, let me know if it fixes things.
