### ISSUE TITLE
Nextcloud offline while service is running

### ISSUE THREAD

**Issue by SnorrenEnzo** [nextcloud/nextcloud-snap#1457]
My Nextcloud Snap installation (19.0.2snap1) suddenly decided to go offline. I can't remember if anything happened around that time that might have triggered it. Restarting the machine (Ubuntu 20.04) did not fix it, neither did `snap disable nextcloud`, `snap enable nextcloud`. The output of the debug script from the [wiki](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts) is shown below:

[2020-09-18_nextcloud_debug.txt](https://github.com/nextcloud/nextcloud-snap/files/5246077/2020-09-18_nextcloud_debug.txt)

There is some issue with Apache, but running `systemctl status snap.nextcloud.apache` indicates that it is active and running. Same for MySQL. 
`snap refresh` results in a timeout when it tries to refresh Apache. Making a snapshot, as indicated [here](https://github.com/nextcloud/nextcloud-snap/issues/1174) results in the process freezing, possibly due to the rather large (~180 GB) amount of data stored on Nextcloud. I guess that making a snapshot also saves all the files stored on Nextcloud. I could not find a way to confirm or disable this.

I have been looking all over the place the past week to try to find a solution, but have not found anything yet. Anyone got some hints or suggestions?

EDIT:
`snap logs nextcloud` output:

[2020-09-18_nextcloud.log](https://github.com/nextcloud/nextcloud-snap/files/5246159/2020-09-18_nextcloud.log)

**Comment by kyrofa** [comment]
I think this is key:

> sep 18 16:22:44 morsweg-server nextcloud.apache[152204]: (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
> sep 18 16:22:44 morsweg-server nextcloud.apache[152204]: (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80

Something else is stealing the ports the snap needs. Fix that and I bet it'll start working again.

**Comment by SnorrenEnzo** [comment]
Turns out that while trying to install Bookstack and subsequently removing it, an Apache installation remained active on my system. Removing it did the job. Thank you!

**Comment by kyrofa** [comment]
Ah excellent, thank you for letting us know!
