### ISSUE TITLE
PHP is not compiled with Argon2 support

### ISSUE THREAD

**Issue by bensuffolk** [nextcloud/nextcloud-snap#1459]
#### Describe the bug
I would like to migrate my existing nextcloud server to this snap, however all my user passwords on  he existing server are encrypted with argon2, and as this snap does not include that existing users passwords will not work, and need resetting.

#### Expected behavior
argon2 encrypted passwords to work

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-47-generic x86_64)

    $ snap list nextcloud

nextcloud  19.0.3snap1  23171  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.46.1
snapd   2.46.1
series  16
ubuntu  20.04
kernel  5.4.0-47-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by kyrofa** [comment]
How do you tell Nextcloud to use argon2?

**Comment by bensuffolk** [comment]
It automatically uses it if it’s compiled in to php.

**Comment by kyrofa** [comment]
Huh, how did I not know this? :thinking: 

I'll get a PR up, we can give it a test.

**Comment by kyrofa** [comment]
@bensuffolk can you try testing out #1461? Instructions are over there.
