### ISSUE TITLE
Cron Job interval 5 or 15 minutes?

### ISSUE THREAD

**Issue by Lejo1** [nextcloud/nextcloud-snap#1462]
#### Describe the bug

The default cron job interval of this snap is 5 minutes but the web settings tells you that you should execute cron.php every 5 min.
So I changed the interval to 5 min. manually.

On the other hand I also found [this](https://github.com/nextcloud/nextcloud-snap/issues/350#issuecomment-331029942) comment telling me that the interval should be 15 minutes.

So what is right?

I just think we should have the right interval set by default.

**Comment by kyrofa** [comment]
You're right, it should be five minutes. That comment as well as the recommendation to run every 15 minutes is out of date. The snap will use [5 minutes by default](https://github.com/nextcloud/nextcloud-snap/blob/master/src/nextcloud/utilities/nextcloud-utilities#L8), on new installs, however, the _previous_ default was 15 minutes. As a result, snaps that were installed when the default was 15 minutes stay at 15 minutes unless they opt to choose something else, as you did.
