### ISSUE TITLE
i cant edit the my.cnf of mysql

### ISSUE THREAD

**Issue by AldousS22** [nextcloud/nextcloud-snap#1463]
#### Describe the bug
today i uploaded a nextcloudclient.ext (104mb) but it failded
<br>
vim the my.cnf i saw the maxpackage is 100mb<br>
my.cnf is the config of mysql ; but the root of it is 644 i cant change it with chmod;
<br>

i tried to remount the disk  but the disk cant remount <br>
the dev/loop0  created by  snap<br>

#### Screenshots
![image](https://user-images.githubusercontent.com/43975826/94361233-6c55b880-00e5-11eb-9570-fa3321751060.png)
<br>
![image](https://user-images.githubusercontent.com/43975826/94360781-9f4a7d00-00e2-11eb-8cbc-76773a299e1a.png)
<br>
![image](https://user-images.githubusercontent.com/43975826/94360805-bbe6b500-00e2-11eb-86b4-7c8d383d2e01.png)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ nextcloud  19.0.3snap1  23171  latest/stable  nextcloud✓  -

and:

    $ snap    2.45.3.1-1.el8
snapd   2.45.3.1-1.el8
series  16
centos  8
kernel  4.18.0-193.el8.x86_64

**Comment by AldousS22** [comment]
![image](https://user-images.githubusercontent.com/43975826/94361337-0ddd0a00-00e6-11eb-91fe-6222878714ee.png)

**Comment by AldousS22** [comment]
vim /var/lib/snapd/snap/nextcloud/23171/my.cnf

**Comment by AldousS22** [comment]
as a cloud i think the max_allowed packet = 4096mb better

**Comment by kyrofa** [comment]
> today i uploaded a nextcloudclient.ext (104mb) but it failded

Files are not stored as blobs in MySQL. That packet size shouldn't effect supported file size, those are controlled via PHP settings, and I've successfully tested uploading multiple GB files. What gives you the impression that the MySQL packet size is the issue, here?

**Comment by AldousS22** [comment]
Thanks i did it sucessfully after edit the php setting. 
I've thought of it i reinstall the server pc casuse  someting, but after installed i forgeted edit php .
Thanks.
