### ISSUE TITLE
AppArmor blocking access to timesyncd?

### ISSUE THREAD

**Issue by JMoVS** [nextcloud/nextcloud-snap#1464]
#### Describe the bug
My log is getting spammed with access denied to timesyncd like this:

```
Sep 27 20:13:47 $host kernel: audit: type=1400 audit(1601230427.919:3940): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=3165156 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 27 20:13:50 &host audit[3165193]: AVC apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/etc/systemd/timesyncd.conf" pid=3165193 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

`nextcloud  19.0.3snap1  23171  latest/stable  nextcloud✓  -`

and:

```
snap    2.46.1
snapd   2.46.1
series  16
ubuntu  20.04
kernel  5.4.0-47-generic
```
#### Logs

If those detailed logs are needed, I can supply them

**Comment by kyrofa** [comment]
You shouldn't be getting spammed continuously, right? You should only see this when visiting a page in Nextcloud that tries to show you the configured NTP servers. To the length of my knowledge, there is no interface that provides read-only access to this information under confinement (e.g. there's `timeserver-control`, but we don't need write access).

**Comment by JMoVS** [comment]
@kyrofa I'm not sure. Maybe this is the firewall blocking external IPs trying to access that? I don't know. I just discovered it in the logs but have no baseline to compare it to.I was trying to pin down a problem (that I still haven't found) where the readme.md feature would start creating 2 readme.md files, one UPPERCASE and one CamelCase, and then syncing to clients would stop working. Maybe that's because the data resides on ZFS or case-sensitiveness or whatever - but I saw a suggestion that these sync problem might have to do with timestamps so that's why I started looking in the logs.

I now disabled the readme.md feature (the one where you can show headers for folders etc) as after extensive research, I hadn't found a solution or even someone having the really same problem it seems.

**Comment by kyrofa** [comment]
Yeah the only place this is used is the `serverinfo` app where it tries to determine NTP servers. This is definitely non-fatal. It has nothing to do with the firewall, it's just apparmor not allowing that app to reach outside of confinement. 

> I was trying to pin down a problem (that I still haven't found) where the readme.md feature would start creating 2 readme.md files, one UPPERCASE and one CamelCase, and then syncing to clients would stop working. Maybe that's because the data resides on ZFS or case-sensitiveness or whatever - but I saw a suggestion that these sync problem might have to do with timestamps so that's why I started looking in the logs.

This problem is unrelated. It comes from [this line](https://github.com/nextcloud/serverinfo/blob/master/lib/OperatingSystems/DefaultOs.php#L134) in the app is all, it won't effect timestamps. Your instincts about case-sensitivity sound more likely.
