### ISSUE TITLE
Doctrine\DBAL\DBALException: Failed to connect to the database

### ISSUE THREAD

**Issue by DJ-3ncoder** [nextcloud/nextcloud-snap#1466]
I am getting this error below:

[cron] Error: Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory at <<closure>>

 0. /snap/nextcloud/23171/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 889
    OC\DB\Connection->connect()
 1. /snap/nextcloud/23171/htdocs/lib/private/DB/Connection.php line 194
    Doctrine\DBAL\Connection->executeQuery("SELECT * FROM `oc_appconfig`", [], [], null)
 2. /snap/nextcloud/23171/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 200
    OC\DB\Connection->executeQuery("SELECT * FROM `oc_appconfig`", [], [])
 3. /snap/nextcloud/23171/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php line 216
    Doctrine\DBAL\Query\QueryBuilder->execute()
 4. /snap/nextcloud/23171/htdocs/lib/private/AppConfig.php line 331
    OC\DB\QueryBuilder\QueryBuilder->execute()
 5. /snap/nextcloud/23171/htdocs/lib/private/AppConfig.php line 109
    OC\AppConfig->loadConfigValues()
 6. /snap/nextcloud/23171/htdocs/lib/private/AppConfig.php line 287
    OC\AppConfig->getApps()
 7. /snap/nextcloud/23171/htdocs/lib/private/legacy/OC_App.php line 883
    OC\AppConfig->getValues(false, "installed_version")
 8. /snap/nextcloud/23171/htdocs/lib/private/Server.php line 665
    OC_App::getAppVersions()
 9. /snap/nextcloud/23171/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OC\Server->OC\{closure}("*** sensitive parameters replaced ***")
10. /snap/nextcloud/23171/htdocs/lib/private/ServerContainer.php line 124
    Pimple\Container->offsetGet("OC\\Memcache\\Factory")
11. /snap/nextcloud/23171/htdocs/lib/private/Server.php line 1704
    OC\ServerContainer->query("OC\\Memcache\\Factory")
12. /snap/nextcloud/23171/htdocs/lib/private/Server.php line 856
    OC\Server->getMemCacheFactory()
13. /snap/nextcloud/23171/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OC\Server->OC\{closure}("*** sensitive parameters replaced ***")
14. /snap/nextcloud/23171/htdocs/lib/private/ServerContainer.php line 124
    Pimple\Container->offsetGet("OC\\App\\AppManager")
15. /snap/nextcloud/23171/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php line 163
    OC\ServerContainer->query("OC\\App\\AppManager")
16. /snap/nextcloud/23171/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php line 114
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
17. /snap/nextcloud/23171/htdocs/lib/private/ServerContainer.php line 124
    Pimple\Container->offsetGet("OCP\\App\\IAppManager")
18. /snap/nextcloud/23171/htdocs/lib/private/Server.php line 1894
    OC\ServerContainer->query("OCP\\App\\IAppManager")
19. /snap/nextcloud/23171/htdocs/lib/private/legacy/OC_App.php line 347
    OC\Server->getAppManager()
20. /snap/nextcloud/23171/htdocs/lib/private/legacy/OC_App.php line 114
    OC_App::getEnabledApps()
21. /snap/nextcloud/23171/htdocs/lib/base.php line 648
    OC_App::loadApps(["session"])
22. /snap/nextcloud/23171/htdocs/lib/base.php line 1095
    OC::init()
23. /snap/nextcloud/23171/htdocs/cron.php line 42
    require_once("/snap/nextcloud ... p")

at 2020-09-28T19:42:22+00:00

I found a very similar issue but I cannot do the steps that they were doing because I am using the snap version of Nextcloud.
That's why I cannot change some "start after that and that" or "start before that and that" settings.
My snap is updating on its own and the first time I got that error was on 16.09.2020

How to reproduce this error: do a reboot of the server

Due to the fact, that it occurs since 16.09. maybe it has something to do with a version of the snap that was released back then.

**Comment by DJ-3ncoder** [comment]
I am very sorry, I forgot to mention my system info:
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-118-generic x86_64)

services:
  nextcloud.apache:          simple, enabled, active
  nextcloud.mdns-publisher:  simple, enabled, active
  nextcloud.mysql:           simple, enabled, active
  nextcloud.nextcloud-cron:  simple, enabled, active
  nextcloud.nextcloud-fixer: simple, enabled, inactive
  nextcloud.php-fpm:         simple, enabled, active
  nextcloud.redis-server:    simple, enabled, active
  nextcloud.renew-certs:     simple, enabled, active
snap-id:      njObIbGQEaVx1H4nyWxchk1i8opy4h54
tracking:     latest/stable
refresh-date: 15 days ago, at 19:19 UTC
channels:
  latest/stable:    19.0.3snap1               2020-09-14 (23171) 270MB -
  latest/candidate: 19.0.3snap1               2020-09-14 (23171) 270MB -
  latest/beta:      19.0.3snap1+git2.c7ba709  2020-09-27 (23395) 270MB -
  latest/edge:      master-2020-09-29         2020-09-29 (23420) 291MB -
  19/stable:        19.0.3snap1               2020-09-14 (23171) 270MB -
  19/candidate:     ↑
  19/beta:          ↑
  19/edge:          19-2020-09-29             2020-09-29 (23416) 270MB -
  18/stable:        18.0.6snap1               2020-06-11 (21521) 265MB -
  18/candidate:     ↑
  18/beta:          18.0.6snap1+git2.a633b2e  2020-06-25 (21847) 265MB -
  18/edge:          18-2020-09-29             2020-09-29 (23419) 267MB -
  17/stable:        17.0.6snap1               2020-05-03 (20616) 229MB -
  17/candidate:     ↑
  17/beta:          17.0.6snap1+git10.8f765f8 2020-06-09 (21474) 249MB -
  17/edge:          17-2020-07-10             2020-07-10 (22146) 251MB -
  16/stable:        16.0.11snap1              2020-06-08 (21459) 225MB -
  16/candidate:     ↑
  16/beta:          ↑
  16/edge:          ↑
  

I think it is because of the update on 14th Sept and on 16th Sept there was my first reboot since newest version.

**Comment by aracno** [comment]
Hi,
i ve got exactly the same problem but i also noticed that activity mail notifications is not working anymore.
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-118-generic x86_64)
:)

**Comment by kyrofa** [comment]
Really hard to debug issues like this without the [logs](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts) requested in the issue template, mind pasting those in here?

**Comment by DJ-3ncoder** [comment]
Yeah, I will try to generate these logs for you with the link where your "logs" is linked to

**Comment by kyrofa** [comment]
I haven't seen the logs, but you might consider trying the snap outlined in #1481. Curious to see if that solves your problem.

**Comment by DJ-3ncoder** [comment]
The output is so huge, I cannot copy it from the terminal :O
Where does it save them?

**Comment by kyrofa** [comment]
Don't worry about the logs at the moment, try refreshing from the stable channel:

    $ sudo snap refresh --stable nextcloud

That contains what I believe to be a fix for this. Can you confirm it works?

**Comment by allanp5979** [comment]
HI,

I believe I have a similar issue:


An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'localhost' (using password: YES) in /snap/nextcloud/23743/htdocs/lib/private/DB/Connection.php:67
Stack trace:
#0 /snap/nextcloud/23743/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(889): OC\DB\Connection->connect()
#1 /snap/nextcloud/23743/htdocs/lib/private/DB/Connection.php(194): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)
#2 /snap/nextcloud/23743/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(200): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array)
#3 /snap/nextcloud/23743/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php(216): Doctrine\DBAL\Query\QueryBuilder->execute()
#4 /snap/nextcloud/23743/htdocs/lib/private/AppConfig.php(331): OC\DB\QueryBuilder\QueryBuilder->execute()
#5 /snap/nextcloud/23743/htdocs/lib/private/AppConfig.php(109): OC\AppConfig->loadConfigValues()
#6 /snap/nextcloud/23743/htdocs/lib/private/AppConfig.php(287): OC\AppConfig->getApps()
#7 /snap/nextcloud/23743/htdocs/lib/private/legacy/OC_App.php(883): OC\AppConfig->getValues(false, 'installed_versi...')
#8 /snap/nextcloud/23743/htdocs/lib/private/Server.php(665): OC_App::getAppVersions()
#9 /snap/nextcloud/23743/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#10 /snap/nextcloud/23743/htdocs/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OC\\Memcache\\Fac...')
#11 /snap/nextcloud/23743/htdocs/lib/private/Server.php(1704): OC\ServerContainer->query('OC\\Memcache\\Fac...')
#12 /snap/nextcloud/23743/htdocs/lib/private/Server.php(856): OC\Server->getMemCacheFactory()
#13 /snap/nextcloud/23743/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#14 /snap/nextcloud/23743/htdocs/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#15 /snap/nextcloud/23743/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OC\\App\\AppManag...')
#16 /snap/nextcloud/23743/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#17 /snap/nextcloud/23743/htdocs/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OCP\\App\\IAppMan...')
#18 /snap/nextcloud/23743/htdocs/lib/private/Server.php(1894): OC\ServerContainer->query('OCP\\App\\IAppMan...')
#19 /snap/nextcloud/23743/htdocs/lib/private/legacy/OC_App.php(347): OC\Server->getAppManager()
#20 /snap/nextcloud/23743/htdocs/lib/private/legacy/OC_App.php(114): OC_App::getEnabledApps()
#21 /snap/nextcloud/23743/htdocs/lib/base.php(648): OC_App::loadApps(Array)
#22 /snap/nextcloud/23743/htdocs/lib/base.php(1094): OC::init()
#23 /snap/nextcloud/23743/htdocs/console.php(49): require_once('/snap/nextcloud...')
#24 /snap/nextcloud/23743/htdocs/occ(11): require_once('/snap/nextcloud...')

Is there a particular log file you would like?

Thanks

Peter

**Comment by kyrofa** [comment]
@allanp5979 that sounds like #1503 (you've commented there as well, so I assume you know that). I believe this particular issue has been resolved, so I'm going to go ahead and close this.

**Comment by labor4** [comment]
Hi
A note. Mine is in a chrooted directory on a Plesk instance.
I fixed it by changing in config.php:
`  
'dbhost' => 'localhost',
`
to
`  
'dbhost' => '127.0.0.1',
`

It seems somehow my socket was broken.
