### ISSUE TITLE
Update Nextcloud to v20

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#1474]
v20.0.0 was just released. We'll wait until at least the point release to upgrade everyone, but time to start the process.

**Comment by JMoVS** [comment]
the snap experience has been 1A for me so far - really nice - thanks for your efforts!

**Comment by AbyssMoon** [comment]
I'm amazed, snap has been working for me for about 2 years, I don't do anything, the version is always up-to-date, everything is fine
Thanks for your work!

**Comment by dasaweb** [comment]
Maybe a bit off topic, but a comment to the topic of using snap in general:

Everything worked fine for me up to version 19... Then this bug (https://github.com/nextcloud/server/issues/5031#issuecomment-686524908) appeared and I had to disable most of my synchronizations. This means that the key feature of the Nextcloud is no longer working for me. There is a small fix for this problem (see https://github.com/nextcloud/server/pull/23257/files), which I could easily apply to a normal Nextcloud installation. But I can't do that in the snap installation. So for the first time I regret having gone the way of snap :-/ Or is there a way to implement such a code modification in your own snap installation?

**Comment by kyrofa** [comment]
Off topic indeed, but I'm happy to respond. Before I continue though, I want to point out that we here only package the snap. We try to fix blocking bugs in Nextcloud when we find them, but what you're receiving in the snap is vanilla Nextcloud. If Nextcloud has a bug, so will the snap, and the only clean way to fix that is to fix it in Nextcloud, which will cause it to be fixed in the snap.

> [...] which I could easily apply to a normal Nextcloud installation. But I can't do that in the snap installation. So for the first time I regret having gone the way of snap :-/ Or is there a way to implement such a code modification in your own snap installation?

Technically you can if you're willing to build your own snap, but you'll get integrity check errors. I don't recommend this route. We don't apply custom patches to Nextcloud here, either. You should be pinging folks on that upstream PR, try to get it landed ASAP.

**Comment by dasaweb** [comment]
> Off topic indeed, but I'm happy to respond. Before I continue though, I want to point out that we here only package the snap. We try to fix blocking bugs in Nextcloud when we find them, but what you're receiving in the snap is vanilla Nextcloud. If Nextcloud has a bug, so will the snap, and the only clean way to fix that is to fix it in Nextcloud, which will cause it to be fixed in the snap.

Thanks anyway for your answer! That's what I thought, and I think that's good and right.
 
> > [...] which I could easily apply to a normal Nextcloud installation. But I can't do that in the snap installation. So for the first time I regret having gone the way of snap :-/ Or is there a way to implement such a code modification in your own snap installation?
> 
> Technically you can if you're willing to build your own snap, but you'll get integrity check errors. I don't recommend this route. We don't apply custom patches to Nextcloud here, either. You should be pinging folks on that upstream PR, try to get it landed ASAP.

I was afraid that this would not be possible so easily. Then I will continue to try to get the fix into a final version of Nextcloud as soon as possible. I always find it difficult to get other people to do something if you can't contribute anything yourself... But I will try to force that with a lot of kindness ;-)

**Comment by kyrofa** [comment]
>  I always find it difficult to get other people to do something if you can't contribute anything yourself... But I will try to force that with a lot of kindness ;-)

You and me both! I think that's the best approach, though :) .
