### ISSUE TITLE
Using nextcloud.occ to scan for file changes not working

### ISSUE THREAD

**Issue by petwri** [nextcloud/nextcloud-snap#149]
I just removed my standard nextcloud instance to replace it with nextcloud snap, and pretty much everything worked like charm. But there is one issue I am still dealing with, which is the manual scanning for file changes. On a standard nextcloud, using occ like `sudo -u www-data php occ files:scan --all` should do a rescan of all file changes (includes external storage) an pick up local changes.

Running the same thing with `sudo nextcloud.occ files:scan --all` gives me a permission error for the external storage locations, although their permissions are set to 777 and `nextcloud.occ` is run as root. Any ideas what I am doing wrong?

**Comment by kyrofa** [comment]
So to make sure I understand: you're using the external storage app, which means you must have connected the `removable-media` plug, right? The files in external storage show up just fine in Nextcloud, but when you try to scan for new files, you get a permission error.

If you can confirm the setup I'll give this a try and see if I can duplicate.

**Comment by petwri** [comment]
Duh, forgot the connection of the `removable-media` interface. Sry, my bad, issue resolved. Thanks!

**Comment by petwri** [comment]
Ok, after working for a few hours, I now again got issues with this scanning. Running `sudo nextcloud.occ files:scan --all` complains about the home storage of users not being writable, even though occ is ran as root. When then again trying to connect the `removable media` interface, I get the following error:

`error: cannot perform the following tasks:
- Connect nextcloud:removable-media to ubuntu-core:removable-media (snap "nextcloud" has no plug named "removable-media")
`

Ideas?

**Comment by kyrofa** [comment]
Huh... so you connected the interface and it worked for a while, but now it's saying that plug doesn't exist? Mind pasting in the output of `snap interfaces` for me?

**Comment by petwri** [comment]
There you go: seems to be there

`Slot                     Plug
:bluetooth-control       -
:browser-support         -
:camera                  -
:cups-control            -
:dcdbas-control          -
:docker-support          -
:firewall-control        -
:fuse-support            -
:gsettings               -
:hardware-observe        -
:home                    -
:kernel-module-control   -
:libvirt                 -
:locale-control          -
:log-observe             -
:lxd-support             -
:modem-manager           -
:mount-observe           -
:network                 -
:network-bind            -
:network-control         -
:network-manager         -
:network-observe         -
:network-setup-observe   -
:opengl                  -
:optical-drive           -
:ppp                     -
:process-control         -
:pulseaudio              -
:removable-media         -
:screen-inhibit-control  -
:shutdown                -
:snapd-control           -
:system-observe          -
:system-trace            -
:time-control            -
:timeserver-control      -
:timezone-control        -
:tpm                     -
:unity7                  -
:upower-observe          -
:x11                     -
`

**Comment by petwri** [comment]
@kyrofa Any other input on this issue? removable-media plug seems to be present.

**Comment by kyrofa** [comment]
That output looks very problematic. Can you also paste the output of `snap list` as well as `snap version`, please? Also remember that single backticks are for _inline_ code. You need to use triple backticks to get line breaks.

**Comment by petwri** [comment]
`snap list` gives

```
Name         Version      Rev  Developer  Notes
nextcloud    10.0.2snap1  383  nextcloud  -
ubuntu-core  16.04.1      423  canonical  -
```

`
snap version gives me
`
```
snap    2.17.1ubuntu1
snapd   2.17.1ubuntu1
series  16
ubuntu  16.04
```

**Comment by kyrofa** [comment]
Note that the output of `snap interfaces` is problematic as nothing is in the "Plugs" column-- that's where Nextcloud should show up. Try installing another snap: `sudo snap install snappy-debug`. Then please show me the output of `snap interfaces` again.

**Comment by petwri** [comment]
Ok, for some odd reasons `snap interfaces` now shows a line with

```:removable-media         nextcloud
```

But scanning still doesn't work

```
user2@hostname:~$ sudo /snap/bin/nextcloud.occ files:scan --all
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php

Scanning files for 2 users
Starting scan for user 1 out of 2 (user1)
Starting scan for user 2 out of 2 (user2)
Home storage for user user2 not writable
Make sure you're running the scan command only as the user the web server runs as

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 260     | 10841 | 00:00:04     |
+---------+-------+--------------+
```

**Comment by kyrofa** [comment]
Huh... I honestly have no idea what's going on here. Try disabling/re-enabling the snap and see if that helps things at all:

```
$ sudo disable nextcloud
$ sudo enable nextcloud
```

**Comment by kyrofa** [comment]
I'd also be interested in any errors in your syslog when you run `occ files:scan`.

**Comment by petwri** [comment]
Disabling and re-enabling nextcloud didn't change a thing, nothing in the syslog.

**Comment by kyrofa** [comment]
Are you having problems within Nextcloud itself using the removable media? Or just when scanning?

**Comment by petwri** [comment]
I can access the files on nextcloud through my browser just fine, it's just that very often that file changes don't get picked up by nextcloud, that's why I wanted to do the scan periodically.

**Comment by kyrofa** [comment]
Okay, so I don't think the problem is with the `removable-media` interface. I just tested this specific scenario and it works fine here, too (including the scan). I'm curious: from the scan, it appears you have two users. However, only one user is actually causing an error. Assuming you followed #150 to use the removable media, both users should be in `/media`. What does the ownership of those directories look like? Run `sudo ls -l /media/my/data/dir/`. Everything in there should be owned by root.

**Comment by petwri** [comment]
Yes, I did move my data directory to `/media/.cloud`

```
root@hostname:/media# ls -l /media/.cloud/
total 92
drwxr-xr-x 2 root root  4096 Dec 20 13:24 files_external
-rwxrwx--- 1 root root     0 Dec 20 13:12 index.html
drwxr-xr-x 6 root root  4096 Dec 20 17:21 user1
-rw-r----- 1 root root 72730 Dec 28 21:58 nextcloud.log
drwxr-xr-x 4 root root  4096 Dec 27 16:08 user2
```

As you see, owned by root. The problem is with the external storage, which has different ownership and permissions (obviously not root), because it is used, edited and maintained by a different user (in this case `main`).

```
root@hostname:/media# ls -l /media/Storage/
total 48
drwxrwxrwx 6 main main  4096 Nov  5 11:59 Documents
drwxrwxrwx 8 main main 45056 Dec 12 18:57 Photos
```

But it's permissions are 777, so why shouldn't root, running the nextcloud instance, be able to access the directories?

**Comment by kyrofa** [comment]
Yeah fair enough-- it should be succeeding as long as it has read permissions (I just tested). Can you paste the result of increasing the verbosity, please? `sudo nextcloud.occ files:scan --all -vvv`

**Comment by petwri** [comment]
Exactly the same result. Lists the files scanned for the first user, when
trying to scan files for user2, it gives the error. Btw, user2 only uses
external storage.

**Comment by kyrofa** [comment]
> Exactly the same result. Lists the files scanned for the first user, when trying to scan files for user2, it gives the error.

To clarify, it doesn't show a single file scanned for user2?

> Btw, user2 only uses external storage.

What does that mean, exactly? Is the external storage limited in availability to user2? Does user2 have any files other than those in external storage?

Note that I'm unable to get the error you're getting without actually removing write permissions from `/media/.cloud/user2`. Everything works if external storage is owned by someone else or write permissions are otherwise withheld from it, so I don't think this is due to external storage.

**Comment by petwri** [comment]
Yes, exactly. user2 only has files in /media/Storage, and not a single file
in there shows up during verbose scanning.

**Comment by petwri** [comment]
Got it!

I just created a folder containing one single file on the top level nextcloud data directory of user2 through the nextcloud browser interface and voila, everything works. Even after deleting this directory again, scanning runs as expected. So now, everything is back to the way it used to be, but scanning works now.
Seems as if something in `/media/.cloud/user2` was missing or had corrupted permissions and creating a file fixed that. Thanks for the support.

Issue solved!

**Comment by kyrofa** [comment]
Ah ha! Thanks for poking at it some more-- that sounds like a bug in Nextcloud's scanner. It'd be worth reporting if you have time.
