### ISSUE TITLE
Web update loop for 19.0.4snap1

### ISSUE THREAD

**Issue by d00vy** [nextcloud/nextcloud-snap#1504]
#### Describe the bug
Visiting my Nextcloud URL and attempting to log in presents a page stating that "Nextcloud will be updated to version 19.0.4" with a button to "Start Update"
Click the button, update seems to work and exits with "update successful" but loops back to the initial page to begin the update. Several attempts produce the same results. I reverted to 19.0.3 (```snap revert nextcloud```) and everything functions normally. Updated the snap again (```snap refresh nextcloud```) to 19.0.4 and presented with the same issue as before.

#### To Reproduce
1. ```snap refresh nextcloud```
2. Presented with web update page
3. Click on "Start Update"
4. Loop back to web update page

#### Expected behavior
Snaps have normally updated on their own without issue in the past. ```snap refresh``` has typically taken care of everything I need. This is the first time I've encountered a web updater, and it doesn't work.

#### Screenshots
![update1](https://user-images.githubusercontent.com/47931208/96020841-42ee9980-0e14-11eb-8164-188c4777cbe2.JPG)

#### OS/snapd/snap version
What OS and version are you running? 
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  19.0.4snap1  23743  latest/stable  nextcloud✓ 

$ snap version
snap    2.47
snapd   2.47
series  16
ubuntu  20.04
kernel  5.4.65-1-pve
```

#### Logs
[script-log.txt](https://github.com/nextcloud/nextcloud-snap/files/5379823/script-log.txt)
[updater-log.txt](https://github.com/nextcloud/nextcloud-snap/files/5379827/updater-log.txt)

**Comment by kyrofa** [comment]
Can I see the output of this command, please?

    $ sudo nextcloud.occ user:list --output=json

**Comment by kyrofa** [comment]
Huh, everything looks like that upgrade completed, I really see no errors that explain what's happening. What happens if you just run `sudo nextcloud.occ upgrade` on your own? It still says it succeeded but it actually doesn't?

**Comment by d00vy** [comment]
>
> 
> Huh, everything looks like that upgrade completed, I really see no errors that explain what's happening. What happens if you just run `sudo nextcloud.occ upgrade` on your own? It still says it succeeded but it actually doesn't?

Yes, the upgrade appears to succeed but there's no change. Here is the output of `sudo nextcloud.occ upgrade`: 
[occ-upgrade-log.txt](https://github.com/nextcloud/nextcloud-snap/files/5386201/occ-upgrade-log.txt)

> 
> 
> Can I see the output of this command, please?
```
$ sudo nextcloud.occ user:list --output=json
{"doovy":"Casey","jillyanne":"Jillian"}
```

**Comment by kyrofa** [comment]
Huh, I've never seen behavior like this before. Please try running the upgrading manually again, then let's see the output of the following command:

    $ sudo cat /var/snap/nextcloud/current/logs/nextcloud.log

**Comment by kyrofa** [comment]
Also, can I see the output of this, please? This could contain some sensitive info, so feel free to mask as necessary, I'm asking due to a nextcloud-fixer error there (which I don't think is related to this loop, but is still problematic):

```
$ sudo snap run --shell nextcloud.occ <<"EOF"
occ user:list --output=json | jq -r 'keys[]' | while read -r user; do
    echo "Dealing with '$user' now..."
    occ user:info --output=json "$user"
done
EOF
```

**Comment by d00vy** [comment]
Unfortunately I'm running into issues using that command. Seems the ```jq -r 'keys[]'``` command returns a ```parse error: Invalid numeric literal at line 1, column 10``` that I can't figure out.

I think this is the info you're looking for anyway. I only have 2 users enabled, "doovy" being the admin account.
The output of ```occ user:info doovy``` returns:
```
$ occ user:info doovy
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
  - user_id: doovy
  - display_name: Casey
  - email: <removed>
  - cloud_id: doovy@192.168.11.102
  - enabled: true
  - groups:
    - admin
  - quota: none
  - last_seen: 2020-10-14T03:57:01+00:00
  - user_directory: /mnt/storage/doovy
  - backend: Database
```

and in JSON format:
```
$ occ user:info doovy --output=json
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{"user_id":"doovy","display_name":"Casey","email":"<removed>","cloud_id":"doovy@192.168.11.102","enabled":true,"groups":["admin"],"quota":"none","last_seen":"2020-10-14T03:57:01+00:00","user_directory":"\/mnt\/storage\/doovy","backend":"Database"}
```

I've been reverting to 19.0.3snap2 until I can figure out how to complete this update. I believe you can see this in ```nextcloud.log``` when I attempt to ```snap refresh``` to upgrade and run the commands you're providing, and then reverting back.

I'm not sure if it's of any value but just to clarify: I'm running this snap in an LXC container via Proxmox and I'm only using the ```root``` user. I'm using CaddyV2 as my reverse proxy, which has been working fine after making some changes to my ```config.php```. I've attempted the updates both through my public URL/Caddy and the local IP with no change. Is is possible that there is something going on with the communication between the Nextcloud snap and Caddy that is causing problems?

Also in case it's relevant: you may notice I'm using external storage located at ```/mnt/storage/<user>``` which is also where my ```nextcloud.log``` file is located.
[nextcloud.log.txt](https://github.com/nextcloud/nextcloud-snap/files/5411166/nextcloud.log.txt)

Thanks for your help!

**Comment by kyrofa** [comment]
> parse error: Invalid numeric literal at line 1, column 10

Yeah that's the issue I was trying to narrow down, but I think you got me there by showing me that this is actually https://github.com/nextcloud/server/issues/23596 . I don't know if working around that will fix your problem (I suspect not), but we can try.

**Comment by kyrofa** [comment]
@d00vy 20.0.1 was just released to stable with this fix, any chance that changed anything?

**Comment by d00vy** [comment]
No change; same behavior as before with both web and command line upgrades.

nextcloud.log has several "no app in context" errors:
```{"reqId":"B0JpHzFEgdxpWSyPKlty","level":1,"time":"2020-10-27T17:46:44+00:00","remoteAddr":"192.168.11.101","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=pbjZMvfxrHDr4HrbWtxnRncZhmXHmqB%2BQ389Lm5LBpw%3D%3A69SSdseTh0WfmhO%2FII8fDUV%2F9SD%2F39FLFSV5Tzg7N7c%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}```

And seems to be missing a "js/config.js":
```

Thanks for following up.

**Comment by kyrofa** [comment]
Dang, I'm really stumped by this behavior. It might be time to open a thread on help.nextcloud.com to help debug this, I don't really know where to look at this point.

**Comment by d00vy** [comment]
I started over with a fresh server and 20.0.1snap1 installed fine. Won't be able to troubleshoot this issue any further
