### ISSUE TITLE
Collabora Online - Built-in CODE Server: Could not establish connection to the Collabora Online server.

### ISSUE THREAD

**Issue by ewan86** [nextcloud/nextcloud-snap#1507]
I am unable to use the built in code server to open documents in nextcloud using collabora online

#### To Reproduce
1.install Collabora Online - Built-in CODE Server app and enable
2. install Collabora online app
3. try to open office document - failed to load collabora online please try again later
4. Go to code server settings - says server is enabled
5. Click settings link, get 404 error
5. Go to Collabora online settings, says Could not establish connection to the Collabora Online server.

#### Expected behavior
Documents to open in libreoffice online within nextcloud and for the settings for libreoffice online to say connected. And settings link to open

#### Screenshots
![image](https://user-images.githubusercontent.com/13614310/96316229-6c6f1700-1006-11eb-8056-ce5448c6cf20.png)
![image](https://user-images.githubusercontent.com/13614310/96316754-91638a00-1006-11eb-9b27-e24c9924e3f7.png)

#### OS/snapd/snap version
ubuntu 18.04

   Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  19.0.4snap1  23743  latest/stable  nextcloud✓  -

   snap version
snap    2.47
snapd   2.47
series  16
ubuntu  18.04
kernel  4.15.0-121-generic

**Comment by kyrofa** [comment]
I've tested this in the past successfully, and nothing has changed in the snap. You might consider logging a bug against CODE, see if they can help debug what's happening.

**Comment by kyrofa** [comment]
This is an issue with collabora, please log over there. I'll close this here.
