### ISSUE TITLE
/var/snap/nextcloud/current/mysql/mysql.sock exists after reboot

### ISSUE THREAD

**Issue by dshcherb** [nextcloud/nextcloud-snap#151]
I was having some trouble in recovering nextcloud after a softlockup on a node. The nextcloud snap was running in a VM at the time of the hardware node hang and the hard reboot that followed.

So I got this in the journal, which is kind of confusing as there are multiple errors (`--initialize` seems ok as it is in the `start_mysql` wrapper):
```
дек 19 20:06:17 myvmhostname systemd[1]: Started Service for snap application nextcloud.mysql.
дек 19 20:06:17 myvmhostname snap[3892]: 2016-12-19T17:06:17.270288Z 0 [Warning] Changed limits: max_open_files: 1024 (requested 5000)
дек 19 20:06:17 myvmhostname snap[3892]: 2016-12-19T17:06:17.270329Z 0 [Warning] Changed limits: table_open_cache: 431 (requested 2000)
дек 19 20:06:17 myvmhostname snap[3892]: 2016-12-19T17:06:17.270426Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
дек 19 20:06:17 myvmhostname snap[3892]: 2016-12-19T17:06:17.271004Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
дек 19 20:06:17 myvmhostname snap[3892]: 2016-12-19T17:06:17.271389Z 0 [ERROR] Aborting
дек 19 20:06:17 myvmhostname snap[3892]: Starting MySQL
дек 19 20:06:17 myvmhostname snap[3892]: .
дек 19 20:06:17 myvmhostname snap[3892]: Waiting for server...
дек 19 20:06:17 myvmhostname snap[3892]: Checking/upgrading mysql tables if necessary...
дек 19 20:06:17 myvmhostname snap[3892]: mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/snap/nextcloud/current/mysql/mysql.sock' (111) while connecting to the MySQL server
дек 19 20:06:17 myvmhostname snap[3892]: Upgrade process encountered error and will not continue.
дек 19 20:06:17 myvmhostname snap[3913]: MySQL server process #3827 is not running! ... failed!
```
The same output remained after doing `systemctl restart snap.nextcloud.mysql.service`.

I poked around this and found that a unix socket that mysqld listens on was present even though the instance was not.

```
stat /var/snap/nextcloud/current/mysql/mysql.sock
  File: '/var/snap/nextcloud/current/mysql/mysql.sock'
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: fc00h/64512d	Inode: 98043970    Links: 1
Access: (0777/srwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-12-20 21:09:25.921717143 +0300
Modify: 2016-12-20 21:09:18.505794944 +0300
Change: 2016-12-20 21:09:18.505794944 +0300
 Birth: -
```

I then did

```rm /var/snap/nextcloud/current/mysql/mysql.sock```

And the unit started just fine:

```
systemctl status snap.nextcloud.mysql.service
● snap.nextcloud.mysql.service - Service for snap application nextcloud.mysql
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.mysql.service; enabled; vendor preset: enabled)
   Active: active (running) since Вт 2016-12-20 21:23:51 MSK; 55s ago
  Process: 3629 ExecStop=/usr/bin/snap run --command=stop nextcloud.mysql (code=exited, status=0/SUCCESS)
 Main PID: 4114 (start_mysql)
   CGroup: /system.slice/snap.nextcloud.mysql.service
           ├─4114 /bin/sh /snap/nextcloud/383/bin/start_mysql
           ├─4129 /bin/sh /snap/nextcloud/383/bin/mysqld_safe --datadir=/var/snap/nextcloud/383/mysql --pid-file=/var/snap/nextcloud/383/mysql/myvmhostname.pid --lc-messages-dir=/snap/next
           ├─4300 /snap/nextcloud/383/bin/mysqld --basedir=/snap/nextcloud/383 --datadir=/var/snap/nextcloud/383/mysql --plugin-dir=/snap/nextcloud/383/lib/plugin --lc-messages-dir=/snap/n
           └─4392 sleep 1

дек 20 21:23:51 myvmhostname snap[4114]: 2016-12-20T18:23:51.245513Z 0 [Warning] Changed limits: table_open_cache: 431 (requested 2000)
дек 20 21:23:51 myvmhostname snap[4114]: 2016-12-20T18:23:51.245611Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server op
дек 20 21:23:51 myvmhostname snap[4114]: 2016-12-20T18:23:51.246204Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
дек 20 21:23:51 myvmhostname snap[4114]: 2016-12-20T18:23:51.246707Z 0 [ERROR] Aborting
дек 20 21:23:51 myvmhostname snap[4114]: Starting MySQL
дек 20 21:23:51 myvmhostname snap[4114]: .
дек 20 21:23:51 myvmhostname snap[4114]: Waiting for server...
дек 20 21:23:52 myvmhostname snap[4114]: Checking/upgrading mysql tables if necessary...
дек 20 21:23:52 myvmhostname snap[4114]: Checking if update is needed.
дек 20 21:23:52 myvmhostname snap[4114]: This installation of MySQL is already upgraded to 5.7.11, use --force if you still need to run mysql_upgrade
```

Now the mysql instance is listening on the socket as it should:
```
ss -ax | grep -i mysql
u_str  LISTEN     0      80     /var/snap/nextcloud/383/mysql/mysql.sock 33295                 * 0
```

From what I can see after a little grepping is that the socket location is configured in root.ini. 

```
# grep -RiP 'mysql.*?sock' /var/snap/nextcloud/current
...
/var/snap/nextcloud/current/nextcloud/config/config.php:  'dbhost' => 'localhost:/var/snap/nextcloud/current/mysql/mysql.sock',
...
/var/snap/nextcloud/current/mysql/root.ini:socket=/var/snap/nextcloud/current/mysql/mysql.sock
```

https://github.com/nextcloud/nextcloud-snap/blob/f1ad91131b142704c7e16b038cdf58ba08e33004/src/mysql/start_mysql#L6

My impression is that the socket files should be located on **tmpfs** to not be persistent across reboots - so some alternative to storing at ```/var/run/mysqld/mysqld.sock``` like in a standalone installation should be made.

NOTE: on Ubuntu /var/run is a symlink to /run which is where a tmpfs is mounted.
readlink /var/run ; grep "`readlink /var/run`\s" /proc/mounts
/run
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=332592k,nr_inodes=415737,mode=755 0 0

The default standalone mysql configuration files have this:
/etc/mysql/mysql.conf.d/mysqld.cnf:socket		= /var/run/mysqld/mysqld.sock
/etc/mysql/debian.cnf:socket   = /var/run/mysqld/mysqld.sock

Therefore, storing socket files on a tmpfs is a proper way to handle these files.

I am going to think about how to fit tmpfs mounting into the current snap structure but any suggestions are welcome.

**Comment by kyrofa** [comment]
Good catch @dshcherb! This probably applies to the PID file, as well.

Note that it doesn't need to strictly be tmpfs, but simply somewhere that is wiped on each boot. Typically I'd recommend simply using `/tmp`, but snaps introduce a challenge there in that each app gets its own private `/tmp` (e.g. PHP-FPM's `/tmp` won't contain mysql's socket). I'm not sure there's a volatile location that will be stable across apps, but we'll figure something out!

**Comment by dshcherb** [comment]
```ls -al /proc/`pgrep -f 'mysqld\s'`/ns | grep mnt
lrwxrwxrwx 1 root root 0 дек 20 22:29 mnt -> mnt:[4026532191]
```
```
ps -ef | grep -i httpd 
root      1230     1  0 21:06 ?        00:00:00 /bin/sh /snap/nextcloud/383/bin/run-httpd -k start -DFOREGROUND
root      1654  1230  0 21:06 ?        00:00:00 /bin/sh /snap/nextcloud/383/bin/httpd-wrapper -k start -DFOREGROUND
root      1657  1654  0 21:06 ?        00:00:00 httpd -d /snap/nextcloud/383 -DEnableHTTPS -DEnableHSTS -k start -DFOREGROUND
root      1658  1657  0 21:06 ?        00:00:01 httpd -d /snap/nextcloud/383 -DEnableHTTPS -DEnableHSTS -k start -DFOREGROUND
root      1659  1657  0 21:06 ?        00:00:01 httpd -d /snap/nextcloud/383 -DEnableHTTPS -DEnableHSTS -k start -DFOREGROUND
root      1660  1657  0 21:06 ?        00:00:01 httpd -d /snap/nextcloud/383 -DEnableHTTPS -DEnableHSTS -k start -DFOREGROUND
root      1813  1657  0 21:06 ?        00:00:01 httpd -d /snap/nextcloud/383 -DEnableHTTPS -DEnableHSTS -k start -DFOREGROUND

ls -al /proc/1657/ns/ | grep -i mnt
lrwxrwxrwx 1 root root 0 дек 20 22:32 mnt -> mnt:[4026532191]
```
Both are in the same mount namespace.
```
ps -ef | grep -i php-fpm
root      1222     1  0 21:06 ?        00:00:00 /bin/sh /snap/nextcloud/383/bin/start-php-fpm
root      1399  1222  0 21:06 ?        00:00:00 php-fpm: master process (/snap/nextcloud/383/config/php/php-fpm.conf)
root      1408     1  0 21:06 ?        00:00:00 php-fpm: master process (/etc/php/7.0/fpm/php-fpm.conf)
www-data  1410  1408  0 21:06 ?        00:00:00 php-fpm: pool www
www-data  1411  1408  0 21:06 ?        00:00:00 php-fpm: pool www
root     10264  1399  9 22:32 ?        00:00:00 php-fpm: pool www

ls -al /proc/1399/ns/ | grep -i mnt
lrwxrwxrwx 1 root root 0 дек 20 22:33 mnt -> mnt:[4026532191]
```

1408 is in a different mnt namespace - no idea why yet:

```ls -al /proc/1408/ns/ | grep -i mnt
lrwxrwxrwx 1 root root 0 дек 20 22:33 mnt -> mnt:[4026531840]
```
Even though it is a different mount namespace **MS_SLAVE** propagation could help in case we want to go the tmpfs way. But this requires us to mount tmpfs somewhere at the beginning of the bootstrapping process and later umouting it. Plus doing anything on this tmpfs should be prohibited as this is a potential MemAvailable leaker.

Just something to consider.

**Comment by kyrofa** [comment]
The app-unique /tmp was changed in snap-confine v1.0.43, which means we can finally fix this issue.

**Comment by dshcherb** [comment]
@kyrofa 

Great to hear that - I need the same funtionality for the libvirt snap https://github.com/openstack-snaps/snap-libvirt

**Comment by kyrofa** [comment]
If you have a few minutes to go over #217 I would really appreciate it. Not required though, I'll merge it in the next day or two.

**Comment by dshcherb** [comment]
@kyrofa 

It is quite late in my time zone so I just glanced over the changes and it looks fine - basically, every pidfile and unix socket will live under /tmp which an app-unique tmpfs.

Could you point me to a snap-confine (or snapd now as it has been merged) commit for /tmp changes? I'm going to do the same for my snap.

**Comment by kyrofa** [comment]
A glance is all I wanted, thanks!

I actually have no idea where that commit is, I was told by jdstrand about the change.

**Comment by dshcherb** [comment]
@kyrofa 

I am just going to leave this here for the reference.
https://github.com/snapcore/snapd/commit/ecf6bfd6e5f7d67131a9baeda0443f377b3dfdd7 - seems like an original commit.

The current setup:
https://github.com/snapcore/snapd/blob/master/cmd/snap-confine/snap-confine.apparmor.in#L175
    # set up snap-specific private /tmp dir
    capability chown,
    /tmp/ w,
    /tmp/snap.*/ w,
    /tmp/snap.*/tmp/ w,
    mount options=(rw private) ->  /tmp/,
    mount options=(rw bind) /tmp/snap.*/tmp/ -> /tmp/,

**Comment by kyrofa** [comment]
That commit is old, it seems to be the one setting up app-specific /tmps, causing this issue in the first place. Look at the C code there.

Note that no mounting is being done here, so you won't find tmpfs-specific text. It's tmpfs as a virtue of being contained within the host /tmp.

**Comment by kyrofa** [comment]
Note that the fix for this issue is now in the candidate channel. If anyone wants to test it, run `sudo snap install --candidate nextcloud`.
