### ISSUE TITLE
Internal Server Error after Login

### ISSUE THREAD

**Issue by dash199t** [nextcloud/nextcloud-snap#1515]
Hi,
my nextcloud was working great since many months and updates and there were no problems.
But after the 14.10.2020 I can still login, but I can't see my data, because I get an internal server error and I shall lookup the server logs.
I did this, but didn't find any problematic parts, just my smartphone trying to access the cloud, with obviously didn't work. Also all services are active and don't show any errors, but there are no apache and no redis logs, at least not in the specified folders in the wiki. Also the email notifications still work fine and I can get an email when I login through a new IP,etc.
I am using this version:
nextcloud  19.0.4snap1  23743  latest/stable  nextcloud✓  -

I hope I can get any help from the community, because I have no more clue with my limited abilities.

**Comment by kyrofa** [comment]
Hey there, don't worry, we'll get you back up and running. First of all, the logs moved in this release and I only now updating the [log gathering script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts), mind trying that again?

**Comment by dash199t** [comment]
Hi, thanks a lot for making me hope. Through your script I saw that apache hasn't had permission to access the data directory. I dont know why it changed, because I didnt do it, but now it works!
Thanks a lot for helping me out!

As a solution:
I changed the permissions on `/var/snap/nextcloud/common/` with `$ sudo chown -R root:root /var/snap/nextcloud/common/` and now it works!

**Comment by kyrofa** [comment]
Ah ha! I don't know why that would have changed either-- do you know who owned it suddenly? I agree with your fix. I'll go ahead and close this for now, but feel free to continue discussion here.
