### ISSUE TITLE
After auto-upgrade to 20.0.1 app is not accessible and all occ commands fail

### ISSUE THREAD

**Issue by lawzava** [nextcloud/nextcloud-snap#1532]
#### Describe the bug

App just throws the "Internal Server Error" screen.

`/var/snap/nextcloud/current/logs` have no errors.

Logs, same for any other occ command:
```
$ sudo nextcloud.occ app:list
An unhandled exception has been thrown:
Exception: Authenticated ciphertext could not be decoded. in /snap/nextcloud/24051/htdocs/lib/private/Security/Crypto.php:122
Stack trace:
#0 /snap/nextcloud/24051/htdocs/lib/private/Encryption/Keys/Storage.php(285): OC\Security\Crypto->decrypt('-----BEGIN PUBL...')
#1 /snap/nextcloud/24051/htdocs/lib/private/Encryption/Keys/Storage.php(230): OC\Encryption\Keys\Storage->getKey('/files_encrypti...')
#2 /snap/nextcloud/24051/htdocs/lib/private/Encryption/Keys/Storage.php(122): OC\Encryption\Keys\Storage->getKeyWithUid('/files_encrypti...', NULL)
#3 /snap/nextcloud/24051/htdocs/apps/encryption/lib/KeyManager.php(615): OC\Encryption\Keys\Storage->getSystemUserKey('pubShare_cbb5ad...', 'OC_DEFAULT_MODU...')
#4 /snap/nextcloud/24051/htdocs/apps/encryption/lib/KeyManager.php(171): OCA\Encryption\KeyManager->getPublicShareKey()
#5 /snap/nextcloud/24051/htdocs/apps/encryption/lib/Users/Setup.php(87): OCA\Encryption\KeyManager->validateShareKey()
#6 /snap/nextcloud/24051/htdocs/apps/encryption/lib/AppInfo/Application.php(73): OCA\Encryption\Users\Setup->setupSystem()
#7 /snap/nextcloud/24051/htdocs/apps/encryption/appinfo/app.php(37): OCA\Encryption\AppInfo\Application->setUp()
#8 /snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php(289): require_once('/snap/nextcloud...')
#9 /snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php(171): OC_App::requireAppFile(Object(OCA\Encryption\AppInfo\Application))
#10 /snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php(131): OC_App::loadApp('encryption')
#11 /snap/nextcloud/24051/htdocs/lib/private/Console/Application.php(127): OC_App::loadApps()
#12 /snap/nextcloud/24051/htdocs/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /snap/nextcloud/24051/htdocs/occ(11): require_once('/snap/nextcloud...')
#14 {main}

Next OC\ServerNotAvailableException: Could not decrypt key in /snap/nextcloud/24051/htdocs/lib/private/Encryption/Keys/Storage.php:287
Stack trace:
#0 /snap/nextcloud/24051/htdocs/lib/private/Encryption/Keys/Storage.php(230): OC\Encryption\Keys\Storage->getKey('/files_encrypti...')
#1 /snap/nextcloud/24051/htdocs/lib/private/Encryption/Keys/Storage.php(122): OC\Encryption\Keys\Storage->getKeyWithUid('/files_encrypti...', NULL)
#2 /snap/nextcloud/24051/htdocs/apps/encryption/lib/KeyManager.php(615): OC\Encryption\Keys\Storage->getSystemUserKey('pubShare_cbb5ad...', 'OC_DEFAULT_MODU...')
#3 /snap/nextcloud/24051/htdocs/apps/encryption/lib/KeyManager.php(171): OCA\Encryption\KeyManager->getPublicShareKey()
#4 /snap/nextcloud/24051/htdocs/apps/encryption/lib/Users/Setup.php(87): OCA\Encryption\KeyManager->validateShareKey()
#5 /snap/nextcloud/24051/htdocs/apps/encryption/lib/AppInfo/Application.php(73): OCA\Encryption\Users\Setup->setupSystem()
#6 /snap/nextcloud/24051/htdocs/apps/encryption/appinfo/app.php(37): OCA\Encryption\AppInfo\Application->setUp()
#7 /snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php(289): require_once('/snap/nextcloud...')
#8 /snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php(171): OC_App::requireAppFile(Object(OCA\Encryption\AppInfo\Application))
#9 /snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php(131): OC_App::loadApp('encryption')
#10 /snap/nextcloud/24051/htdocs/lib/private/Console/Application.php(127): OC_App::loadApps()
#11 /snap/nextcloud/24051/htdocs/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /snap/nextcloud/24051/htdocs/occ(11): require_once('/snap/nextcloud...')
#13 {main}%                                                                                                 
```

#### To Reproduce
1. Update to 20.0.1
2. Navigate to your app

#### Expected behavior
Should have accessed app without any issue

#### Screenshots
https://i.imgur.com/j998Rcr.png

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

```
➜  ~ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.1snap1  24051  latest/stable  nextcloud✓  -
```

and:

    $ snap version

```
➜  ~ snap version
snap    2.47.1+20.04
snapd   2.47.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-1029-aws
```

Additional notes:
Server-side encryption is enabled.

**Comment by TommoCrabb** [comment]
I'm having exactly the same problem. The only difference is that I'm running Ubuntu 18.04. It's still the snap version of Nextcloud though.

**Comment by kyrofa** [comment]
> I'm having exactly the same problem.

Also with server-side encryption?

**Comment by TommoCrabb** [comment]
Full story:

Originally, I did NOT have server-side encryption enabled. After the last update, I started getting a persistent error message in the web interface that said something about "Invalid private key for encryption app". I Googled around and found a help thread that suggested that I could fix the problem by enabling encryption

`nextcloud.occ encryption:enable`

Needless to say, this did not fix the problem. Now all I get when I go to the web interface is a page that says "Internal Server Error", and when I type any nextcloud.occ command into the terminal, I get the same error message that Iawzava posted above.

I don't know if this is salvageable or not, but I hope there's at least some way to fish my data out and import it into a fresh installation.

**Comment by danielfm** [comment]
I had to revert to the previous snap version with the `sudo snap revert nextcloud` command, and everything is working again, but I'm not sure whether I should change something in my configuration before migrating to the latest version.

**Comment by TommoCrabb** [comment]
Cheers @danielfm, reverting the snap package did indeed work. I just have no idea where to go from here.

**Comment by danielfm** [comment]
Me too.

I tried deleting and reuploading all my data from Nextcloud, just to make sure no files were encrypted with some old key, as I once enabled the encryption but I disabled it after being put off by the performance penalty I observed.

Anyway, I re-uploaded all my files, tried to upgrade the snap again, but the message appeared again:

> Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files.

Will rollback again and wait for a proper solution.

**Comment by danielfm** [comment]
Another thing I tried after upgrading was to create a brand new user, to see if this message appeared for this user as well, and it did, so I'm not sure what the problem might be.

**Comment by kyrofa** [comment]
I'm afraid I don't actually know anything about the encryption app (I don't use it). You might consider logging a bug against it, see if the devs have a way to troubleshoot what went wrong with the upgrade. Feel free to ping me on it, I'm happy to help translate debugging instructions into snap instructions.

**Comment by danielfm** [comment]
@kyrofa Since I don't need the encryption app as well, I upgraded the snap to the latest version and disabled the app. The message is not appearing anymore, and everything seems to be working so far. Thanks.

**Comment by kyrofa** [comment]
Okay this definitely seems like an issue in the encryption app, then. I'll go ahead and close this, I don't think there's anything we can fix from here.
