### ISSUE TITLE
large stream of log messages from snap.nextcloud.php-fpm

### ISSUE THREAD

**Issue by akumria** [nextcloud/nextcloud-snap#1533]
Apparmor is denying snap.nextcloud.php-fpm access to /etc/ntp.conf; since this is being requested so often it results in a large stream of messages being to the logfiles.

#### To Reproduce
Install nextcloud

#### Expected behavior
I would expect no stream of log messages from apparmor; either snap.nextcloud.php-fpm is fixed to not need access to this file (it is unclear why it would need access), or it is granted read-only access to the file.

#### OS/snapd/snap version
```
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.1snap1  24051  latest/stable  nextcloud✓  -
```

```
$ snap version
snap    2.47.1+20.04
snapd   2.47.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-52-generic
```

**Comment by kyrofa** [comment]
PHP on its own doesn't do this, but anything that Nextcloud or its apps do happens via PHP. I suspect you have an app that's doing this.

**Comment by akumria** [comment]
This is with *zero* installed apps; simply the default nextcloud snap (and deliberately not enabling anything).

**Comment by kyrofa** [comment]
This is coming from the [serverinfo](https://github.com/nextcloud/serverinfo/blob/dcdafc143ec96792154c24fae61816cbd1f51949/lib/OperatingSystems/DefaultOs.php#L133) app. As a result, you should only see if when visiting that app (I don't see it constantly, for example). Note that the timeserver feature was [removed in a recent commit](https://github.com/nextcloud/serverinfo/commit/7b499276fd61dc23751b180cab459f0f32f7ae9d) as well, so I suspect the next release will stop this.

I'm going to go ahead and close this, there's nothing we can do about it and it has already been fixed upstream.

**Comment by lindhe** [comment]
FYI: For me the serverinfo app was called something else, maybe Analytics or whatnot.
