### ISSUE TITLE
Lost nextcloud database(mysql)

### ISSUE THREAD

**Issue by linspinho** [nextcloud/nextcloud-snap#1537]
HELP! I have a problem all  command line deployed give me an output like that;

[root@nextcloud /]# nextcloud.occ status
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'localhost' (using password: YES) in /snap/nextcloud/23743/htdocs/lib/private/DB/Connection.php:67
Stack trace:
#0 /snap/nextcloud/23743/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(889): OC\DB\Connection->connect()
#1 /snap/nextcloud/23743/htdocs/lib/private/DB/Connection.php(194): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)
#2 /snap/nextcloud/23743/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(200): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array)
#3 /snap/nextcloud/23743/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php(216): Doctrine\DBAL\Query\QueryBuilder->execute()
#4 /snap/nextcloud/23743/htdocs/lib/private/AppConfig.php(331): OC\DB\QueryBuilder\QueryBuilder->execute()
#5 /snap/nextcloud/23743/htdocs/lib/private/AppConfig.php(109): OC\AppConfig->loadConfigValues()
#6 /snap/nextcloud/23743/htdocs/lib/private/AppConfig.php(287): OC\AppConfig->getApps()
#7 /snap/nextcloud/23743/htdocs/lib/private/legacy/OC_App.php(883): OC\AppConfig->getValues(false, 'installed_versi...')
#8 /snap/nextcloud/23743/htdocs/lib/private/Server.php(665): OC_App::getAppVersions()
#9 /snap/nextcloud/23743/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#10 /snap/nextcloud/23743/htdocs/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OC\\Memcache\\Fac...')
#11 /snap/nextcloud/23743/htdocs/lib/private/Server.php(1704): OC\ServerContainer->query('OC\\Memcache\\Fac...')
#12 /snap/nextcloud/23743/htdocs/lib/private/Server.php(856): OC\Server->getMemCacheFactory()
#13 /snap/nextcloud/23743/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#14 /snap/nextcloud/23743/htdocs/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#15 /snap/nextcloud/23743/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OC\\App\\AppManag...')
#16 /snap/nextcloud/23743/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#17 /snap/nextcloud/23743/htdocs/lib/private/ServerContainer.php(124): Pimple\Container->offsetGet('OCP\\App\\IAppMan...')
#18 /snap/nextcloud/23743/htdocs/lib/private/Server.php(1894): OC\ServerContainer->query('OCP\\App\\IAppMan...')
#19 /snap/nextcloud/23743/htdocs/lib/private/legacy/OC_App.php(347): OC\Server->getAppManager()
#20 /snap/nextcloud/23743/htdocs/lib/private/legacy/OC_App.php(114): OC_App::getEnabledApps()
#21 /snap/nextcloud/23743/htdocs/lib/base.php(648): OC_App::loadApps(Array)
#22 /snap/nextcloud/23743/htdocs/lib/base.php(1094): OC::init()
#23 /snap/nextcloud/23743/htdocs/console.php(49): require_once('/snap/nextcloud...')
#24 /snap/nextcloud/23743/htdocs/occ(11): require_once('/snap/nextcloud...')
#25 {main}
 
 Is there a way to revert this to normal?

**Comment by kyrofa** [comment]
Did the snap only recently update? This sounds like #1503 if so.

**Comment by linspinho** [comment]
Friend its probably the same problem,  This is a very serious problem, I  have lost a lot of information, I've seen a to big mysql.log file, more than 3 millions lines( 1+ minute to load) and in this file several crash mention but from months ago.

I am using Nextcloud on an Virtual Machine - CentOS 7 

I had to revert VM from snapshot.
I'll try to run the VM with the problematic nextcloud.

Thanks for you time.

**Comment by kyrofa** [comment]
If it's the same probem, then #1503 has a solution near the bottom that you're willing to try. I'm not convinced it's the same problem without those logs though. The script to which I linked above won't attempt to load the entire file, just the post recent lines.

**Comment by linspinho** [comment]
@kyrofa I am going to try to explain. forgive my bad english. I have this CentOS 7 VM running Snap Nextcloud in out-29-2020 I was ready to make a backup with nextcloud.export, when I ran the command  the output was similar to the one I put above, so I tried login on nextcloud webpage and this gave a error.  After some searches on web I look back and saw a snapshot from 0ut-19  so a ran this i another xen server hopping that VM brought me nextcloud back, to my surprise was'nt working to then I ran the snap revert nextcloud, I got nextcloud back, everything seems working good, but when I am trying to export it give me database error again. to answer your questions:
 
About the update: yes, but I think i want up to version 20.
the backup I dont know I know the reverted one is V19.
About the tests:

[root@nextcloud ~]# ls -lh /var/snap/nextcloud/23496/mysql/
total 371M
-rw-r-----. 1 root root   56 Feb 28  2020 auto.cnf
-rw-------. 1 root root 1.7K Feb 28  2020 ca-key.pem
-rw-r--r--. 1 root root 1.1K Feb 28  2020 ca.pem
-rw-r--r--. 1 root root 1.1K Feb 28  2020 client-cert.pem
-rw-------. 1 root root 1.7K Feb 28  2020 client-key.pem
-rw-r-----. 1 root root 187M Nov  6 14:50 error.log
-rw-r-----. 1 root root 4.4K Oct 14 16:28 ib_buffer_pool
-rw-r-----. 1 root root  76M Nov  9 12:52 ibdata1
-rw-r-----. 1 root root  48M Nov  9 12:52 ib_logfile0
-rw-r-----. 1 root root  48M Nov  9 12:52 ib_logfile1
-rw-r-----. 1 root root  12M Nov  9 12:51 ibtmp1
drwxr-x---. 2 root root 4.0K Jul 30 08:24 mysql
-rw-r--r--. 1 root root    6 Jul 30 08:24 mysql_upgrade_info
drwxr-x---. 2 root root 8.0K Sep  2 08:59 nextcloud
-rw-------. 1 root root   65 Feb 28  2020 nextcloud_password
drwxr-x---. 2 root root 8.0K Jul 30 08:24 performance_schema
-rw-------. 1 root root 1.7K Feb 28  2020 private_key.pem
-rw-r--r--. 1 root root  452 Feb 28  2020 public_key.pem
-rw-------. 1 root root    0 Nov  6 14:50 root.ini
-rw-r--r--. 1 root root 1.1K Feb 28  2020 server-cert.pem
-rw-------. 1 root root 1.7K Feb 28  2020 server-key.pem
drwxr-x---. 2 root root 8.0K Feb 28  2020 sys



[root@nextcloud ~]# ls -lh /var/snap/nextcloud/23743/mysql/

total 109M
-rw-r-----. 1 root root   56 Oct 14 16:28 auto.cnf
-rw-------. 1 root root 1.7K Oct 14 16:28 ca-key.pem
-rw-r--r--. 1 root root 1.1K Oct 14 16:28 ca.pem
-rw-r--r--. 1 root root 1.1K Oct 14 16:28 client-cert.pem
-rw-------. 1 root root 1.7K Oct 14 16:28 client-key.pem
-rw-r-----. 1 root root  324 Nov  6 14:50 ib_buffer_pool
-rw-r-----. 1 root root  12M Nov  6 14:50 ibdata1
-rw-r-----. 1 root root  48M Nov  6 14:50 ib_logfile0
-rw-r-----. 1 root root  48M Oct 14 16:28 ib_logfile1
drwxr-x---. 2 root root 4.0K Oct 14 16:28 mysql
-rw-r--r--. 1 root root    6 Oct 14 16:28 mysql_upgrade_info
drwxr-x---. 2 root root   20 Oct 14 16:28 nextcloud
-rw-------. 1 root root   65 Oct 14 16:28 nextcloud_password
drwxr-x---. 2 root root 8.0K Oct 14 16:28 performance_schema
-rw-------. 1 root root 1.7K Oct 14 16:28 private_key.pem
-rw-r--r--. 1 root root  452 Oct 14 16:28 public_key.pem
-rw-------. 1 root root  124 Nov  4 16:28 root.ini
-rw-r--r--. 1 root root 1.1K Oct 14 16:28 server-cert.pem
-rw-------. 1 root root 1.7K Oct 14 16:28 server-key.pem
drwxr-x---. 2 root root 8.0K Oct 14 16:28 sys


[root@nextcloud ~]# snap version
snap    2.42.2-1.el7
snapd   2.42.2-1.el7
series  16
centos  7
kernel  3.10.0-1062.12.1.el7.x86_64

[root@nextcloud ~]# snap list nextcloud
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  19.0.3snap2  23496  stable    nextcloud*  -


[root@nextcloud ~]# cat /var/snap/nextcloud/23496/mysql/root.ini | sed s"/\(^password=\).*$/\1<masked>/"
"NO OUTPUT"

[root@nextcloud ~]# cat /var/snap/nextcloud/23496/mysql/root.ini | sed s"/\(^password=\).*$/\1<masked>/"
[client]
socket=/tmp/sockets/mysql.sock
user=root
password=<masked>

[root@nextcloud ~]#journalctl --no-pager -n100 -u "snap.nextcloud.mysql.service"
-- Logs begin at Wed 2020-11-04 16:28:05 -03, end at Mon 2020-11-09 13:44:25 -03. --
Nov 04 16:28:23 nextcloud.labld systemd[1]: Started Service for snap application nextcloud.mysql.
Nov 04 16:28:30 nextcloud.labld nextcloud.mysql[1115]: Starting MySQL
Nov 04 16:28:35 nextcloud.labld nextcloud.mysql[1115]: ..... *
Nov 04 16:28:35 nextcloud.labld nextcloud.mysql[1115]: Checking/upgrading mysql tables if necessary...
Nov 04 16:28:35 nextcloud.labld nextcloud.mysql[1115]: Checking if update is needed.
Nov 04 16:28:35 nextcloud.labld nextcloud.mysql[1115]: This installation of MySQL is already upgraded to 5.7.31, use --force if you still need to run mysql_upgrade
Nov 06 14:50:02 nextcloud.labld systemd[1]: Stopping Service for snap application nextcloud.mysql...
Nov 06 14:50:02 nextcloud.labld nextcloud.mysql[64596]: Shutting down MySQL
Nov 06 14:50:04 nextcloud.labld nextcloud.mysql[64596]: .. *
Nov 06 14:50:05 nextcloud.labld systemd[1]: Stopped Service for snap application nextcloud.mysql.
Nov 06 14:50:09 nextcloud.labld systemd[1]: Started Service for snap application nextcloud.mysql.
Nov 06 14:50:15 nextcloud.labld nextcloud.mysql[64822]: 2020-11-06T17:50:15.083955Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
Nov 06 14:50:15 nextcloud.labld nextcloud.mysql[64822]: 2020-11-06T17:50:15.097808Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
Nov 06 14:50:15 nextcloud.labld nextcloud.mysql[64822]: 2020-11-06T17:50:15.097922Z 0 [ERROR] Aborting
Nov 06 14:50:15 nextcloud.labld nextcloud.mysql[64822]: Starting MySQL
Nov 06 14:50:18 nextcloud.labld nextcloud.mysql[64822]: ... *
Nov 06 14:50:18 nextcloud.labld nextcloud.mysql[64822]: Checking/upgrading mysql tables if necessary...
Nov 06 14:50:18 nextcloud.labld nextcloud.mysql[64822]: mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) while connecting to the MySQL server
Nov 06 14:50:18 nextcloud.labld nextcloud.mysql[64822]: Upgrade process encountered error and will not continue.


[root@nextcloud ~]# nextcloud.export
Enabling maintenance mode...
done
Exporting apps...

         30.40K   0%    0.00kB/s    0:00:00  
         30.40K   0%    0.00kB/s    0:00:00 (xfr#1, ir-chk=1189/1203)
         30.40K   0%    0.00kB/s    0:00:00 (xfr#1, ir-chk=1180/1203)
         64.92K   0%   32.92MB/s    0:00:00 (xfr#2, ir-chk=1188/1203)
         67.60K   0%   35.48MB/s    0:00:00 (xfr#3, ir-chk=1179/1203)
         70.91K   0%   38.63MB/s    0:00:00 (xfr#4, ir-chk=1178/1203)
        101.31K   0%   67.62MB/s    0:00:00 (xfr#5, ir-chk=1177/1203)
        135.83K   0%   33.51MB/s    0:00:00 (xfr#6, ir-chk=1176/1203)
        138.51K   0%   34.37MB/s    0:00:00 (xfr#7, ir-chk=1168/1203)
        141.81K   0%   35.42MB/s    0:00:00 (xfr#8, ir-chk=1167/1203)
        148.03K   0%   28.05MB/s    0:00:00 (xfr#9, ir-chk=1166/1203)
        150.17K   0%   28.56MB/s    0:00:00 (xfr#10, ir-chk=1165/1203)
        162.11K   0%   31.40MB/s    0:00:00 (xfr#11, ir-chk=1164/1203)
        163.14K   0%   31.65MB/s    0:00:00 (xfr#12, ir-chk=1163/1203)
        164.91K   0%   32.07MB/s    0:00:00 (xfr#13, ir-chk=1162/1203)
        169.96K   0%   33.27MB/s    0:00:00 (xfr#14, ir-chk=1161/1203)
        170.87K   0%   33.49MB/s    0:00:00 (xfr#15, ir-chk=1160/1203)
        172.76K   0%   27.15MB/s    0:00:00 (xfr#16, ir-chk=1159/1203)
        173.94K   0%   27.38MB/s    0:00:00 (xfr#17, ir-chk=1158/1203)
        174.77K   0%   27.54MB/s    0:00:00 (xfr#18, ir-chk=1157/1203)
        176.79K   0%   27.92MB/s    0:00:00 (xfr#19, ir-chk=1156/1203)
        182.94K   0%   29.10MB/s    0:00:00 (xfr#20, ir-chk=1155/1203)
        184.58K   0%   29.41MB/s    0:00:00 (xfr#21, ir-chk=1154/1203)
        185.93K   0%   29.66MB/s    0:00:00 (xfr#22, ir-chk=1153/1203)
        186.21K   0%   29.72MB/s    0:00:00 (xfr#23, ir-chk=1152/1203)
        187.03K   0%   29.87MB/s    0:00:00 (xfr#24, ir-chk=1151/1203)
        187.43K   0%   29.95MB/s    0:00:00 (xfr#25, ir-chk=1150/1203)
        188.54K   0%   25.13MB/s    0:00:00 (xfr#26, ir-chk=1149/1203)
        188.78K   0%   25.17MB/s    0:00:00 (xfr#27, ir-chk=1148/1203)
        189.20K   0%   25.24MB/s    0:00:00 (xfr#28, ir-chk=1147/1203)
        190.71K   0%   25.48MB/s    0:00:00 (xfr#29, ir-chk=1146/1203)
        194.20K   0%   26.04MB/s    0:00:00 (xfr#30, ir-chk=1145/1203)
        195.34K   0%   26.22MB/s    0:00:00 (xfr#31, ir-chk=1144/1203)
        199.63K   0%   26.90MB/s    0:00:00 (xfr#32, ir-chk=1143/1203)
        200.39K   0%   27.02MB/s    0:00:00 (xfr#33, ir-chk=1142/1203)
        201.52K   0%   27.20MB/s    0:00:00 (xfr#34, ir-chk=1141/1203)
        202.09K   0%   27.29MB/s    0:00:00 (xfr#35, ir-chk=1140/1203)
        202.23K   0%   27.31MB/s    0:00:00 (xfr#36, ir-chk=1139/1203)
        202.43K   0%   23.44MB/s    0:00:00 (xfr#37, ir-chk=1138/1203)
        202.58K   0%   23.46MB/s    0:00:00 (xfr#38, ir-chk=1137/1203)
        203.46K   0%   23.58MB/s    0:00:00 (xfr#39, ir-chk=1136/1203)
        203.95K   0%   23.64MB/s    0:00:00 (xfr#40, ir-chk=1135/1203)
        204.41K   0%   23.71MB/s    0:00:00 (xfr#41, ir-chk=1134/1203)
        204.67K   0%   23.74MB/s    0:00:00 (xfr#42, ir-chk=1133/1203)
        205.05K   0%   23.79MB/s    0:00:00 (xfr#43, ir-chk=1132/1203)
        205.19K   0%   23.81MB/s    0:00:00 (xfr#44, ir-chk=1131/1203)
        206.71K   0%   24.02MB/s    0:00:00 (xfr#45, ir-chk=1130/1203)
        206.94K   0%   24.05MB/s    0:00:00 (xfr#46, ir-chk=1129/1203)
        207.10K   0%   21.06MB/s    0:00:00 (xfr#47, ir-chk=1128/1203)
        207.25K   0%   21.08MB/s    0:00:00 (xfr#48, ir-chk=1127/1203)
        207.66K   0%   21.13MB/s    0:00:00 (xfr#49, ir-chk=1126/1203)
        299.38K   0%   19.73MB/s    0:00:00 (xfr#50, ir-chk=1124/1203)
        309.44K   0%   10.24MB/s    0:00:00 (xfr#51, ir-chk=1123/1203)
        331.07K   0%   11.03MB/s    0:00:00 (xfr#52, ir-chk=1122/1203)
        362.21K   1%   11.72MB/s    0:00:00 (xfr#53, ir-chk=1121/1203)
        382.42K   1%   11.99MB/s    0:00:00 (xfr#54, ir-chk=1120/1203)
        406.77K   1%   12.38MB/s    0:00:00 (xfr#55, ir-chk=1119/1203)
        431.29K   1%   12.33MB/s    0:00:00 (xfr#56, ir-chk=1118/1203)
        438.90K   1%   12.57MB/s    0:00:00 (xfr#57, ir-chk=1117/1203)
        457.43K   1%   13.14MB/s    0:00:00 (xfr#58, ir-chk=1116/1203)
        468.53K   1%   13.48MB/s    0:00:00 (xfr#59, ir-chk=1115/1203)
        489.86K   1%   13.69MB/s    0:00:00 (xfr#60, ir-chk=1114/1203)
        496.27K   1%   13.88MB/s    0:00:00 (xfr#61, ir-chk=1113/1203)
        569.93K   1%   14.29MB/s    0:00:00 (xfr#62, ir-chk=1112/1203)
        615.60K   1%   14.31MB/s    0:00:00 (xfr#63, ir-chk=1111/1203)
        650.65K   1%   15.17MB/s    0:00:00 (xfr#64, ir-chk=1110/1203)
        673.32K   2%   15.33MB/s    0:00:00 (xfr#65, ir-chk=1109/1203)
        684.35K   2%   14.85MB/s    0:00:00 (xfr#66, ir-chk=1108/1203)
        712.13K   2%   15.48MB/s    0:00:00 (xfr#67, ir-chk=1107/1203)
        723.22K   2%   15.73MB/s    0:00:00 (xfr#68, ir-chk=1106/1203)
        743.88K   2%   15.46MB/s    0:00:00 (xfr#69, ir-chk=1105/1203)
        789.08K   2%   16.44MB/s    0:00:00 (xfr#70, ir-chk=1104/1203)
        813.18K   2%   16.59MB/s    0:00:00 (xfr#71, ir-chk=1103/1203)
        852.50K   2%   16.33MB/s    0:00:00 (xfr#72, ir-chk=1102/1203)
        861.64K   2%   16.52MB/s    0:00:00 (xfr#73, ir-chk=1101/1203)
        890.87K   2%   17.10MB/s    0:00:00 (xfr#74, ir-chk=1100/1203)
        929.43K   2%   16.81MB/s    0:00:00 (xfr#75, ir-chk=1099/1203)
        943.59K   2%   16.75MB/s    0:00:00 (xfr#76, ir-chk=1098/1203)
          1.02M   3%   17.89MB/s    0:00:00 (xfr#77, ir-chk=1097/1203)
          1.04M   3%   17.83MB/s    0:00:00 (xfr#78, ir-chk=1096/1203)
          1.06M   3%   17.79MB/s    0:00:00 (xfr#79, ir-chk=1095/1203)
          1.09M   3%   18.04MB/s    0:00:00 (xfr#80, ir-chk=1094/1203)
          1.12M   3%   18.25MB/s    0:00:00 (xfr#81, ir-chk=1093/1203)
          1.13M   3%   18.04MB/s    0:00:00 (xfr#82, ir-chk=1092/1203)
          1.14M   3%   18.25MB/s    0:00:00 (xfr#83, ir-chk=1091/1203)
          1.16M   3%   18.64MB/s    0:00:00 (xfr#84, ir-chk=1090/1203)
          1.17M   3%   18.80MB/s    0:00:00 (xfr#85, ir-chk=1089/1203)
          1.19M   3%   19.13MB/s    0:00:00 (xfr#86, ir-chk=1088/1203)
          1.23M   3%   18.70MB/s    0:00:00 (xfr#87, ir-chk=1087/1203)
          1.25M   3%   18.72MB/s    0:00:00 (xfr#88, ir-chk=1086/1203)
          1.26M   3%   18.34MB/s    0:00:00 (xfr#89, ir-chk=1085/1203)
          1.31M   3%   19.04MB/s    0:00:00 (xfr#90, ir-chk=1084/1203)
          1.32M   3%   18.66MB/s    0:00:00 (xfr#91, ir-chk=1083/1203)
          1.35M   4%   19.02MB/s    0:00:00 (xfr#92, ir-chk=1082/1203)
          1.39M   4%   19.06MB/s    0:00:00 (xfr#93, ir-chk=1081/1203)
          1.40M   4%   19.27MB/s    0:00:00 (xfr#94, ir-chk=1080/1203)
          1.41M   4%   19.08MB/s    0:00:00 (xfr#95, ir-chk=1079/1203)
          1.43M   4%   19.40MB/s    0:00:00 (xfr#96, ir-chk=1078/1203)
          1.44M   4%   19.51MB/s    0:00:00 (xfr#97, ir-chk=1077/1203)
          1.49M   4%   19.32MB/s    0:00:00 (xfr#98, ir-chk=1076/1203)
          1.50M   4%   19.13MB/s    0:00:00 (xfr#99, ir-chk=1075/1203)
          1.52M   4%   19.46MB/s    0:00:00 (xfr#100, ir-chk=1074/1203)
          1.56M   4%   19.47MB/s    0:00:00 (xfr#101, ir-chk=1073/1203)
          1.60M   4%   19.91MB/s    0:00:00 (xfr#102, ir-chk=1072/1203)
          1.61M   4%   20.06MB/s    0:00:00 (xfr#103, ir-chk=1071/1203)
          1.62M   4%   20.19MB/s    0:00:00 (xfr#104, ir-chk=1070/1203)
          1.63M   4%   20.02MB/s    0:00:00 (xfr#105, ir-chk=1069/1203)
          1.63M   4%   19.58MB/s    0:00:00 (xfr#106, ir-chk=1068/1203)
          1.66M   4%   19.66MB/s    0:00:00 (xfr#107, ir-chk=1067/1203)
          1.69M   5%   19.99MB/s    0:00:00 (xfr#108, ir-chk=1066/1203)
          1.70M   5%   19.64MB/s    0:00:00 (xfr#109, ir-chk=1065/1203)
          1.72M   5%   19.86MB/s    0:00:00 (xfr#110, ir-chk=1064/1203)
          1.73M   5%   19.73MB/s    0:00:00 (xfr#111, ir-chk=1063/1203)
          1.74M   5%   19.87MB/s    0:00:00 (xfr#112, ir-chk=1062/1203)
          1.75M   5%   19.56MB/s    0:00:00 (xfr#113, ir-chk=1061/1203)
          5.22M  15%   31.91MB/s    0:00:00 (xfr#114, ir-chk=1060/1203)
          5.24M  15%   31.67MB/s    0:00:00 (xfr#115, ir-chk=1059/1203)
         14.83M  44%   40.32MB/s    0:00:00 (xfr#116, ir-chk=1058/1203)
         14.83M  32%   39.75MB/s    0:00:00 (xfr#117, ir-chk=1558/1705)
         14.83M  32%   39.75MB/s    0:00:00 (xfr#118, ir-chk=1557/1705)
         14.83M  32%   39.64MB/s    0:00:00 (xfr#119, ir-chk=1556/1705)
         14.83M  32%   39.65MB/s    0:00:00 (xfr#120, ir-chk=1555/1705)
        ....
        156.31M 100%   47.86MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.86MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.86MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.86MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.86MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.86MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.86MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.86MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.85MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.85MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
        156.31M 100%   47.85MB/s    0:00:03 (xfr#4030, to-chk=0/4482)
Exporting database...
Unable to export database
Disabling maintenance mode...
done

Is There a way to bring the 24051 revision back?

**Comment by kyrofa** [comment]
Okay yeah, looks like #1503. Assuming you have reverted and are currently running find on 19.0.3, run the script [outlined here](https://github.com/nextcloud/nextcloud-snap/issues/1503#issuecomment-712388758). ONLY the script, though-- don't run `snap remove` on anything. Once you've run that script and confirm that 19.0.3 is still working properly, come back here and give me the output of `snap list nextcloud --all`.

**Comment by linspinho** [comment]
Hello kyrofa, I've run that script but it gave me some error:

`/bin/bash: line 1: /snap/nextcloud/23496/utilities/mysql-utilities
: No such file or directory
/bin/bash: line 2: $'\r': command not found
error: error running snapctl: unknown service: "nextcloud.mysql\r"
/bin/bash: line 4: $'\r': command not found
/bin/bash: line 6: $'\r': command not found
Generating root mysql password... 
done

/bin/bash: line 11: $'\r': command not found
/bin/bash: line 41: warning: here-document at line 13 delimited by end-of-file (wanted `EOF')
/bin/bash: line 13: mysql_pid: command not found
`
Obs: If I enable network snap update and every thing got bad again! Even so I am able to revert.

**Comment by kyrofa** [comment]
Huh, are you doing that through Windows or cygwin or something?

**Comment by linspinho** [comment]
As I said before, I am using Centos 7 virtual machine installed on xcp-ng(xenserver) virtual console.

**Comment by kyrofa** [comment]
I'm afraid I'm not terribly familiar with either, but you should not be seeing:

>  /bin/bash: line 2: $'\r': command not found

See [this](https://askubuntu.com/questions/966488/how-do-i-fix-r-command-not-found-errors-running-bash-scripts-in-wsl).

**Comment by linspinho** [comment]
ok kyrofa thanks for the last tip.

the `snap list nextcloud --all` output:
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  19.0.3snap2  23496  stable    nextcloud*  -
nextcloud  19.0.4snap1  23743  stable    nextcloud*  disabled

It seems working well.

did not perform others commands!

**Comment by kyrofa** [comment]
Okay so you're back up and running? Excellent. You're currently using revision 23496, and everything looks good? Okay, toast revision 23743:

    $ sudo snap remove nextcloud --revision=23743

Then run `sudo snap refresh nextcloud` and you should update to v20.

**Comment by linspinho** [comment]
Ok kyrofa, done! Thank you!

The change to recover some lost data it is possible as I have the VM snapshot?

**Comment by kyrofa** [comment]
This issue occurred immediately when updating to 19.0.4snap1, so if you reverted back to where you were before (19.0.3snap2), are you sure you actually lost data?

If so, two things:

1. Your files should be fine, this was a database-only issue
2. You can certainly import some or all of an old database dump if you wish, you have the `nextcloud.mysql-client` command if you need it.

**Comment by kyrofa** [comment]
Now that you're back up and running, I'll go ahead and close this, but I'm happy to continue discussion here.
