### ISSUE TITLE
Update PHP to 7.1

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#154]

**Comment by kyrofa** [comment]
Reverted in #156 as PHP 7.1 apparently doesn't build on arm64. Will revisit updating on next PHP release.

**Comment by pachulo** [comment]
I think that this should work now that we finally upgraded to 12.x!
Once 11.0.6 is the default 11 installation it should also work as per https://github.com/nextcloud/server/issues/6991

**Comment by kyrofa** [comment]
Sweeet, finally. Thanks @pachulo!

**Comment by kyrofa** [comment]
After a false start (more issues with 7.1.12) it appears that 7.1.13 works!
