### ISSUE TITLE
imagick is missing php-module

### ISSUE THREAD

**Issue by pheiduck** [nextcloud/nextcloud-snap#1540]
#### Describe the bug
imagick is missing

#### To Reproduce
1. Go to settings -> overview
2. see missing php-module

#### Expected behavior
Green checkmark System running fine. 

#### Screenshots
![grafik](https://user-images.githubusercontent.com/47042125/98851992-4e56d400-2457-11eb-8e84-4b8e4148cfb8.png)

#### OS/snapd/snap version
Arch Linux Kernel 5.9.6

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.1snap1  24051  latest/stable  nextcloud✓  -
and:

    $ snap version
snap    2.47.1-2
snapd   2.47.1-2
series  16
arch    -
kernel  5.9.6-arch1-1

**Comment by kyrofa** [comment]
I'm afraid imagick is a security concern, and as such isn't enabled on purpose. You see this warning if you enable the theming app, because the theming app uses it to generate favicons. As a result, that particular feature isn't possible while using the snap.
