### ISSUE TITLE
Can't get to first install page of snap nextcloud on Raspberry Pi 4

### ISSUE THREAD

**Issue by pauldev-here** [nextcloud/nextcloud-snap#1541]
No matter what I do, I can't get to the configuration page of my nextcloud installation.

sudo snap install nextcloud
sudo snap start nextcloud

Then I tried typing in my ip address, ipaddress/nextcloud, ipaddress.local, localhost on the server, localhost.local nothing works it either says site can't be reached due to server address not being able to be found or the host refused to connect.

I ran a script for logs that I found somewhere that I can't find now, and this error keeps repeating under the PHP section:

ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

**Comment by kyrofa** [comment]
You might just need a wait a little bit for it to initialize.

> ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

This is a non-fatal error, and has nothing to do with the snap. Your OS is configured to try to inject that library (although it looks like an environment variable wasn't substituted, which is another problem with your OS), and that doesn't work in snaps. There's nothing we can do here to fix that error, you need to stop trying to preload it for the snap.

**Comment by pauldev-here** [comment]
> I fixed my issue by doing this:
> `sudo snap install core`

_Originally posted by @pluisenbol in https://github.com/nextcloud/nextcloud-snap/issues/501#issuecomment-719936188_

 ^^
This was the solution
