### ISSUE TITLE
Subdomains not working

### ISSUE THREAD

**Issue by dlgeraghty** [nextcloud/nextcloud-snap#1542]
####I cant get this snap working when trying to run nextcloud in a subdomain, e.g nextcloud.domain.com

####  What did I modify
previous to this: add entry in the dns table...
1. /var/snap/nextcloud/current/nextcloud/config/config.php :
 ```
'overwrite.cli.url' => 'https://nextcloud.domain.com',
```
````
'overwrite.host' => 'https://nextcloud.domain.com',
````
2. I executed snap restart nextcloud
3. No error was reported
4. But when accessing the domain, nothing appears :( 
5. I did NOT modify any apache config file (nor in the snap neither in my system), maybe this is needed? if so, what file? the structure is not clear...

#### Expected behavior
The nextcloud instance should load in nextcloud.domain.com

#### OS/snapd/snap version
ubuntu 20.04
following commands:

    $ snap list nextcloud
```
nextcloud  20.0.1snap1  24051  latest/stable  nextcloud*  -
```
and:

    $ snap version
```
snap    2.47.1+20.04
snapd   2.47.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-53-generic
```

#### Logs
i attach it as a file, as it is too big for copying
[nextcloud.log](https://github.com/nextcloud/nextcloud-snap/files/5540484/nextcloud.log)

**Comment by kyrofa** [comment]
> But when accessing the domain, nothing appears :(

No error, nothing? What do you actually see? Note that I run the snap using a subdomain-- there's nothing special about a subdomain versus anything else.

**Comment by dlgeraghty** [comment]
Really, that's weird, could yo please explain to me what are the necessary changes to configure it on a subdomain? 
I suppose that you would need to modify the overwrite.cli.url field with the one you intend to use, is it not like that? 
If there are any other modifications that need to be done in order to get that working, I would appreciate the help, as I cant find it anywhere else.
Though I found a post from you in the "tell me how the snap nextcloud is going for you" in the nextcloud forum, I believe, in which you say this snap is only meant to be run standalone, is that the case now or is that post just old??

Anyway, is there some way in which I can actually see what the apache config that this is generating looks like? I feel like I could debug from there, but if there is some other way please let me now.

**Comment by dlgeraghty** [comment]
Okay, I have been doing a little research these past days and have found a workaround this issue:

Just configuring a reverse proxy on the host OS will work, for instance, with caddy what I would do is to configure the snap to run on some port like 8080, as an example, and then in the Caddyfile (keep in mind that this is Caddy v2 notation)

```
nextcloud.domain.com{
    reverse_proxy localhost:8080    
}
```

this way, the snap would be running on 8080, but it could be reachable from the subdomain through the proxy, just what I needed and doesnt require a huge amount of effort!

I am going to run this snap again as it offers me better performance than a "normal" installation of nextcloud, great job!
