### ISSUE TITLE
Snap performance in comparison to other kinds of installation

### ISSUE THREAD

**Issue by joaohenrifranco** [nextcloud/nextcloud-snap#1543]
I have been using Nextcloud for a few months now (snap version) but after reading about some performance costs that could be associated with using snap versions of some apps (like VLC), I was wondering if the same happens with Nextcloud.

Am I losing some performance by using this method instead of the traditional, docker, or VM installation? 

I tried to find answers on the issues, wiki (and everywhere else on the internet) but couldn't. I'm sorry if it has already been discussed, references are welcome.

**Comment by kyrofa** [comment]
I'm not sure anyone has actually stress tested and compared options like that (I haven't). It probably also depends on your hardware. Data would certainly be welcome! That said, if you're truly looking to eke out the most performance possible, the snap probably isn't for you-- it's just not as tunable as other options (on purpose). If you're looking for something you don't have to maintain and will keep you automatically up-to-date and secure, that's the market cornered by the snap.

**Comment by kyrofa** [comment]
I'm going to go ahead and close this since it's so open-ended and we haven't gotten more responses, but feel free to continue discussion here.
