### ISSUE TITLE
[Feature] include turn server

### ISSUE THREAD

**Issue by mokkin** [nextcloud/nextcloud-snap#1545]
For the talk app a turn server is recommended to discover clients behind NATs.
Please try to include https://github.com/coturn/coturn for example.

**Comment by kyrofa** [comment]
Does this need to be in the snap? Or can it simply be installed on the same server? Seems like it would be better suited to just being a standalone snap, for example.

**Comment by mokkin** [comment]
It was just my idea to provide an all in one snap.

**Comment by kyrofa** [comment]
Thank you for the suggestion! However, I'm afraid this doesn't fit in the roadmap of the snap.
