### ISSUE TITLE
Change order of commands in Wiki

### ISSUE THREAD

**Issue by lindhe** [nextcloud/nextcloud-snap#1549]
I have no idea how to edit the Wiki, so I'm putting it as an issue until I figure it out. Sorry for cluttering.

**Please do not change this without checking with the original author!** Perhaps there's a subtle technical reason for why it is this way.

In [the instructions for moving the data directory](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition#if-you-have-already-created-an-admin-user), the user is encouraged to edit the `config.php` file while the snap is still running. This sits ill with me for a number of reasons, but mainly because (1) changing `datadirectory` before migrating the files on disk could result in new files being overwritten and (2) changing such a central part of the configuration mid-operation sounds dangerous (I'm imagining a risk for inconsistent internal states between processes or whatnot).

Is there a reason for doing it in this order? Otherwise, I would feel _way_ more comfortable having it in the following order:

1. Stop the snap from running
1. Decide where you want the new data to live
1. Update the Nextcloud config to use the new data directory
1. Move (or copy) the current data directory to the new place
1. Re-enable the snap

**Comment by kyrofa** [comment]
You are absolutely right, there's a race condition here. These instructions predate the time when the `snap` command gained the ability to control the status of services, and the only way to make sure everything in the snap was stopped was to disable it. However, disabling the snap also removed the `current` symlink in `/var/snap/nextcloud/` and similar data spaces, which made the instructions all but impossible to write (and execute) given that they would need to contain revision numbers.

Thankfully, these days we can just run `snap stop` to stop the services without needing to disable the whole snap, so I quickly tweaked the directions on that page. Thank you for logging the issue!
