### ISSUE TITLE
Nextcloud 20.0.2 auto updater finished updating and now the website won't connect to clients

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#1565]
#### Describe the bug
Nextcloud 20.0.2 auto updater finished updating and now the website won't connect to remote clients

Following the return from maintenance mode via a auto-update, nextcloud now refuses to connect, error 522 connection timed out to any remote clients.
Previously the system and server was error free, following the update, I now have multiple SQL errors as follows

There are some warnings regarding your setup.
The database is missing some primary keys. Due to the fact that adding primary keys on big tables could take some time they were not added automatically. By running "occ db:add-missing-primary-keys" those missing primary keys could be added manually while the instance keeps running.
Missing primary key on table "oc_federated_reshares".
Missing primary key on table "oc_systemtag_object_mapping".
Missing primary key on table "oc_comments_read_markers".
Missing primary key on table "oc_collres_resources".
Missing primary key on table "oc_collres_accesscache".
Missing primary key on table "oc_filecache_extended".

How do I exactly fix this foobar from a auto-update which apparently hammered my nextcloud?
What is the primary key that is being asked or telling me is missing?

I'm able to connect as administrator locally and review the system as I normally used to be able to do, however any remote attempts to the https://website.me throws up a error 522 connection timed out.

**Comment by ASmith-** [comment]
Solved, On the server I ran 
$ sudo nextcloud.occ db:add-missing-primary-keys

The missing table keys were added back correctly (semi-automatically) in seconds.
The Nextcloud server was still kicking up the 522 connection error. Looking over further help suggestions on this specific Https error, I went to my Cloudflare dashboard and pulled up my DNS information and compared it to my connections on the server.

The Ipv4 had also changed apparently at or around the time the auto-updater finished up, moments after I updated the IPv4 address in the DNS Type A entrys for the domain and WWW, My Nextcloud server was back online. I use Cloudflare for its forwarding proxy and custom caching and recently its DNSSEC encryption. A lot of bang for a free account these days.

**Comment by kyrofa** [comment]
I'm re-opening this, the snap should definitely be adding those keys, I just completely missed that it was required. It never showed up on any of my tests, but I do see it on my production instance, so it must be related to instances that have been running for a long time.
