### ISSUE TITLE
20.0.2 missing primary keys

### ISSUE THREAD

**Issue by uselpa** [nextcloud/nextcloud-snap#1568]
#### Describe the bug
Output from Administration/Overview in the web interface:
```
There are some warnings regarding your setup.
The database is missing some primary keys. Due to the fact that adding primary keys on big tables could take some time they were not added automatically. By running "occ db:add-missing-primary-keys" those missing primary keys could be added manually while the instance keeps running.
Missing primary key on table "oc_federated_reshares".
Missing primary key on table "oc_systemtag_object_mapping".
Missing primary key on table "oc_comments_read_markers".
Missing primary key on table "oc_collres_resources".
Missing primary key on table "oc_collres_accesscache".
Missing primary key on table "oc_filecache_extended".
```

#### OS/snapd/snap version
```
root@deb10a:~# snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.2snap1  24782  latest/stable  nextcloud✓  -
root@deb10a:~# snap version
snap    2.48
snapd   2.48
series  16
debian  10
kernel  4.19.0-12-amd64
```

**Comment by stondino00** [comment]
They never officially released 20.0.2.  I think they have 20.0.3 being released by next Thursday that fixes tons of open bugs after 20.0.2 was built.

https://github.com/nextcloud/server/milestone/138?closed=1

Roughly 46 bugs closed just since 20.0.2 was released.

**Comment by kyrofa** [comment]
@stondino00 not true, check the download page on nextcloud.com and https://nextcloud.com/changelog/#latest20, they both show 20.0.2.

That said, this is a duplicate of #1565, which was fixed in 20.0.2snap2, released yesterday. Try refreshing again:

    $ sudo snap refresh nextcloud

Can you confirm that issue disappears?

**Comment by stondino00** [comment]
Well not officially announced on their blog is what I mean.  Anyway, 20.0.3 will be released next week for what that's worth.

![image](https://user-images.githubusercontent.com/54154986/101265714-313bbb00-370e-11eb-8b43-d391ec9ce9de.png)

**Comment by uselpa** [comment]
@kyrofa The indexes have been created, all is back to normal, thanks. Would like to add that I did not experience any functional problem, as opposed to #1565, I only saw the messages during my weekly manual check.
