### ISSUE TITLE
Use Nextcloud's recommended MySQL configuration

### ISSUE THREAD

**Issue by andybalaam** [nextcloud/nextcloud-snap#1571]
This snap has been a fantastic way for me to use Nextcloud, thank you!

The MySQL config of the current stable snap is:

```bash
$ cat /snap/nextcloud/current/my.cnf 
[mysqld]
user=root
max_allowed_packet=100M
secure-file-priv=NULL
skip-networking
log_error=../logs/mysql_errors.log
```

But I notice that the Nextcloud admin manual [Database configuration](https://docs.nextcloud.com/server/20/admin_manual/configuration_database/linux_database_configuration.html) page recommends these settings:

```
[mysqld]
transaction_isolation = READ-COMMITTED
binlog_format = ROW
```

Checking at runtime, I can see that binlog_format defaults to `ROW` but the transaction isolation is set to `REPEATABLE-READ`:

```
$ sudo nextcloud.mysql-client 
...snip...
mysql> SHOW VARIABLES LIKE 'transaction_isolation';
+-----------------------+-----------------+
| Variable_name         | Value           |
+-----------------------+-----------------+
| transaction_isolation | REPEATABLE-READ |
+-----------------------+-----------------+
1 row in set (0.07 sec)
```

I know there are other issues such as #49 which might be tricky to implement, and I have read elsewhere ([Nextcloud Help: High MySQL CUP Usage](https://help.nextcloud.com/t/high-mysql-cpu-usage/91084) ) that `query_cache_type = ON` might help, but I would suggest that it might be a relatively simple decision to provide the config recommended in the Nextcloud manual.

Since `READ-COMMITTED` locks fewer rows, I would hope that this might improve performance a little.

(I am using version 20.0.2snap2.)

```bash
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.2snap2  24828  latest/stable  nextcloud✓  -
```

**Comment by kyrofa** [comment]
Thanks for the pointer @andybalaam, I agree. Let me built a snap that works like that and you can take it for a spin, tell me what you think.

**Comment by kyrofa** [comment]
Alright @andybalaam, I've proposed #1583. Snaps are built and ready for you to test them if you're up for it (details over there).
