### ISSUE TITLE
nextcloud: update to 20.0.3

### ISSUE THREAD

**Issue by stondino00** [nextcloud/nextcloud-snap#1575]
https://github.com/nextcloud/server/releases/tag/v20.0.3

Not on changelog or blog yet but been built in github.

**Comment by kyrofa** [comment]
Thanks for the heads up. Given that we don't pull the tag directly, we'll wait for it to be on changelog.

**Comment by stondino00** [comment]
Sounds good.  Appears to be in the changelog now.

https://nextcloud.com/changelog/#latest20

Thanks
