### ISSUE TITLE
adapt file upload limit to the system

### ISSUE THREAD

**Issue by Guillaume99** [nextcloud/nextcloud-snap#158]
according to this post : 
https://help.nextcloud.com/t/nextcloud-box-file-size-limit/7088/2?u=guillaume

the upload limit may be different, on 32 and 64 bits system. It would be great to have a default value compliant with this maximum ...

**Comment by kyrofa** [comment]
Note that you can actually upload files greater than 2GB on the pi, so I'm not sure the post to which you linked is accurate.
