### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by nunomgsantos80** [nextcloud/nextcloud-snap#1590]
I get this error message when I login:

Too many requests

There were too many requests from your network. Retry later or contact your administrator if this is an error. 

Any ideas to resolve this?

**Comment by kyrofa** [comment]
This doesn't have anything to do with the snap, I'm afraid. I suggest [reading this forum post](https://help.nextcloud.com/t/cannot-login-too-many-requests/100905), consider posting your own, or logging an issue against upstream Nextcloud.

**Comment by nunomgsantos80** [comment]
Thks @kyrofa
