### ISSUE TITLE
Wiki update nextcloud change data directory

### ISSUE THREAD

**Issue by weiwang11** [nextcloud/nextcloud-snap#1592]
https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition states to directly change the `/var/snap/nextcloud/current/nextcloud/config/autoconfig.php` file if you want to change the data directory. 

Isn't it better to change `/var/snap/nextcloud/current/nextcloud/config/config.php` as mentioned in the github `README.md` file while nextcloud is running and then run `sudo snap restart nextcloud.php-fpm` to refresh nextcloud? What's the difference between modifying `autoconfig.php` and `config.php` when there's no admin account created?

**Comment by kyrofa** [comment]
Pay careful attention to the headers. Where `autoconfig.php` is recommended is under the "If you just installed the snap, and haven't created an admin user yet" section. In that case, the `config.php` doesn't contain a data directory at all. If you have created an admin user, then you need to follow the next section, which does indeed discuss editing the `config.php`.

**Comment by weiwang11** [comment]
Ah that makes sense. I did read the header but I was just wondering why we're using `autoconfig.php` instead of `config.php`. I didn't know `config.php` is only created after the admin user does. Is it possible to update it to include this information as the `README.md` only states to uses `config.php`.
