### ISSUE TITLE
The app called "Extract" can't connect to p7zip or unrar

### ISSUE THREAD

**Issue by JiahuiZhuo** [nextcloud/nextcloud-snap#1598]
#### Describe the bug
Seems like being a snap app need always interfaces to connect extern package like p7zip.
The app called "Extract" needs "p7zip" and "unrar" as dependencies, but the packages installed in the system can't be used by nextcloud-snap.
May I install package inside to the snap image? or create some interface in snap to connect this packages?

#### To Reproduce
1. Install "Extract" in APPS
2. Install p7zip and unrar in system
3. Don't work

#### OS/snapd/snap version

```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.4snap1  25276  latest/stable  nextcloud✓  -
```

```
snap    2.48.1
snapd   2.48.1
series  16
ubuntu  20.04
kernel  5.4.0-58-generic
```

**Comment by kyrofa** [comment]
>  May I install package inside to the snap image? or create some interface in snap to connect this packages?

You can place these tools in a place the snap can reach in confinement (e.g. `/var/snap/nextcloud/current`), but that's assuming the Extract app supports looking elsewhere for them, which would surprise me. This isn't something we have a good system to support, I'm afraid.
