### ISSUE TITLE
Auto update notifications do not expand when clicked

### ISSUE THREAD

**Issue by JMoVS** [nextcloud/nextcloud-snap#1599]
#### Describe the bug
Hi, in nextcloud 18 or 19, clicking on the notification allowed one to view the whole "we autoupdated" note. Now clicking on it doesn't work and ironically when I "x" them away, they quickly flash the whole notification:

<img width="375" alt="grafik" src="https://user-images.githubusercontent.com/7354506/103135008-7459d000-46b5-11eb-80ea-d3e91cc8e05a.png">

#### To Reproduce
1. Get the snap auto-updated
2. Click on on the bell icon to see what's "new" in your admin account
3. Click on the notification

#### Expected behavior
Clicking on it should result in the whole text being shown

#### Screenshots
see above

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    nextcloud  20.0.4snap1  25276  latest/stable  nextcloud✓  -

and:

   snap    2.48.1
snapd   2.48.1
series  16
ubuntu  20.04
kernel  5.4.0-47-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by kyrofa** [comment]
The snap uses existing Nextcloud functionality to display those. All the display features are native Nextcloud, so if there appears to be a bug there, I suggest logging an issue against [Nextcloud itself](https://github.com/nextcloud/server).
