### ISSUE TITLE
20.0.5 Has Hit the Changelog Site

### ISSUE THREAD

**Issue by stondino00** [nextcloud/nextcloud-snap#1607]
https://nextcloud.com/changelog/#latest20

**Comment by stondino00** [comment]
They may be releasing a 20.0.6 rather soon based on what I see in milestones.

**Comment by kyrofa** [comment]
Hmm, maybe 20.0.5 should be avoided then?

**Comment by stondino00** [comment]
I guess they have posted 20.0.5 in the blog so should be good to build this. I spoke too soon apparently. Thanks

**Comment by szaimen** [comment]
This might be of interest for you:
https://help.nextcloud.com/t/nc-20-0-5-2-floods-logging/104859

**Comment by kyrofa** [comment]
Indeed it is, thank you @szaimen. We'll skip 20.0.5.
