### ISSUE TITLE
How to add another  domain name in one  certificate ?

### ISSUE THREAD

**Issue by CookedMeat2** [nextcloud/nextcloud-snap#1608]
I have added a certificate for lets encrypt. I want to add another domain name. How to apply for a certificate for another domain name? Please tell me the simple steps to make two or three domain names share one certificate. Thank you

**Comment by kyrofa** [comment]
It's a little harder than it needs to be, but still not too bad. First of all, disable encryption:

    $ sudo nextcloud.disable-https

Then toast all the Let's Encrypt certs (this is what I need to make cleaner):

    $ sudo rm -rf /var/snap/nextcloud/current/certs/

Then simply go through the same process you did before, but add all your domains when it prompts you:

    $ sudo nextcloud.enable-https lets-encrypt

**Comment by CookedMeat2** [comment]
> $ sudo rm -rf /var/snap/nextcloud/current/certs

thanks fo your help, I add another  another domain names successfully
but i delete this folder:
`$ sudo rm -rf /var/snap/nextcloud/25647/certs/certbot/config

is it ok?

**Comment by kyrofa** [comment]
Hmm, you mean you didn't blow away the entire certs directory, just the config directory, and then you were able to get a new cert? In that case you probably have multiple certs available, and the snap code isn't really written to handle that in a proper way. Make sure you go through that directory and remove any certs/keys that don't relate to your current setup. You should only have one of each.

**Comment by kyrofa** [comment]
It sounds like you're up and running, so I'll go ahead and close this, but feel free to continue this discussion here.
