### ISSUE TITLE
apparmor="DENIED" messages

### ISSUE THREAD

**Issue by montvid** [nextcloud/nextcloud-snap#1612]
#### Describe the bug
Will these messages cause problems? Should i fix this somehow?
```
[   18.949662] audit: type=1400 audit(1611064871.016:51): apparmor="DENIED" operation="exec" profile="snap.nextcloud.mysql" name="/bin/systemctl" pid=1310 comm="mysql.server" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
[   19.135818] audit: type=1400 audit(1611064871.204:52): apparmor="DENIED" operation="open" profile="snap.nextcloud.renew-certs" name="/proc/1042/mounts" pid=1042 comm="python2" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[   22.963472] audit: type=1400 audit(1611064875.028:53): apparmor="DENIED" operation="file_mmap" profile="snap.nextcloud.php-fpm" name="/" pid=1647 comm="php-fpm" requested_mask="w" denied_mask="w" fsuid=0 ouid=0

```

#### To Reproduce
Reboot the pc and in dmesg you see these errors.

#### Expected behavior
No apparmor="DENIED" messages

#### OS/snapd/snap version
Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-62-generic x86_64)
    $ snap list nextcloud
nextcloud  19.0.6snap1  25104  19/stable  nextcloud✓  -
    $ snap version
snap    2.48.2
snapd   2.48.2
series  16
ubuntu  20.04
kernel  5.4.0-62-generic

**Comment by kyrofa** [comment]
> Will these messages cause problems? Should i fix this somehow?

No, these are expected under confinement, don't worry.
