### ISSUE TITLE
no HEIC image format support?

### ISSUE THREAD

**Issue by montvid** [nextcloud/nextcloud-snap#1613]
#### Describe the bug
HEIC image format support (used by iphone photos) was added in nextcloud 20, backported to 19, 18 as noted here but nextcloud-snap does not have HEIC support in nextcloud 19 snap I am using: 
https://github.com/nextcloud/viewer/pull/577
https://github.com/nextcloud/photos/issues/498
https://github.com/nextcloud/photos/pull/509
The solution might be to upgrade/compile imagemagick with heic support.
#### To Reproduce
Nextcloud does not generate a thumbnail nor shows the image - one can only download the image file.
#### Expected behavior
Generate a thumbnail and show a heic image in nextcloud.

#### OS/snapd/snap version

Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-62-generic x86_64)
$ snap list nextcloud
nextcloud 19.0.6snap1 25104 19/stable nextcloud✓ -
$ snap version
snap 2.48.2
snapd 2.48.2
series 16
ubuntu 20.04
kernel 5.4.0-62-generic

**Comment by kyrofa** [comment]
>  The solution might be to upgrade/compile imagemagick with heic support.

I'm afraid if this feature requires imagick we're out of luck. Imagick is a security concern, and thus isn't something we ship in the snap.

**Comment by montvid** [comment]
How do you generate thumbnails and images in nextcloud without imagemagick? I thought it is included in the snap.

**Comment by kyrofa** [comment]
I believe it's just PHP, but I'll admit that's not my area of expertise. It's definitely not in the snap, though.

**Comment by kyrofa** [comment]
I'm going to go ahead and close as I believe this question is answered, but feel free to continue discussion here.

**Comment by montvid** [comment]
Well you did not answer my question. Can you add heic support?

**Comment by kyrofa** [comment]
I'm sorry, I thought I did. I'm afraid adding imagick to the snap is not in our plans.

**Comment by montvid** [comment]
So do you know if heic requires imagick?

**Comment by kyrofa** [comment]
Based on [this comment](https://github.com/nextcloud/photos/issues/498#issuecomment-712023681) I believe so, yes.

**Comment by montvid** [comment]
Thanks, for your time. it seems upstream can't solve this imagick problem for like 2 years now. https://github.com/nextcloud/server/issues/13099

**Comment by kyrofa** [comment]
Of course. I'm sorry we can't enable this for you, we're just trying to look out for the folks who don't realize it's a security concern.

**Comment by ccellist** [comment]
I know this is an old issue, and I understand the need to not include any insecure packages into the snap.... but this is quite a blocker for me and many others I'm sure. What is the underlying security concern here, and is it still present (checks calendar) over 2 years later?

**Comment by szaimen** [comment]
Therr is now imaginary which can run as a sidecar for thr snap and enables previews for almost all image files: https://docs.nextcloud.com/server/25/admin_manual/installation/server_tuning.html?highlight=imaginary#previews

**Comment by PIX3LFLUX** [comment]
I followed this instruction to get HEIC images to work: [(https://decatec.de/home-server/anzeige-von-bildern-in-der-nextcloud-beschleunigen-preview-generator-und-imaginary/)]
