### ISSUE TITLE
Unable to upload files bigger than 2M

### ISSUE THREAD

**Issue by Ephtolens** [nextcloud/nextcloud-snap#1614]
To be clear and concise, i just want to upload, as the title says, bigger file than 2M. I already tried to rewrite the php.ini file but it's in write-only mode. There is no way to modify that. I also search over the issues but nothing seems to have changed.

I also tried  this :

 `sudo snap set  nextcloud php.upload-max-filesize=20G`

It doesn't work either..., it doesn't return any error but it doesn't change anything (even after a restart of my nextcloud instance)

I'm running out of idea...

The last one I had was to fork the git and modify the php.ini file directly but i don't know how to properly make the switch between the two version of nextcloud without loosing my data already synchronized on my server.

Hope anyone can help me on this !

Thank you

**Comment by kyrofa** [comment]
I have no troubles uploading massive files using the snap. No changes should be necessary. Any chance you've got something else between you and the snap, like a proxy? Often those can have ramifications on such things.

**Comment by Ephtolens** [comment]
Yes I'm using Nginx, thanks for raising that option, i'll look into this !

**Comment by kyrofa** [comment]
Yeah I'm not an nginx pro, but try `client_max_body_size`.

**Comment by Ephtolens** [comment]
yes i just set up this variable in my nginx config and it work ! Thanks a lot ! 
'client_max_body_size 512M;'
