### ISSUE TITLE
Unable to backup mysql DB through cron job

### ISSUE THREAD

**Issue by rogieroudshoorn** [nextcloud/nextcloud-snap#1617]
#### Describe the bug
I'd like to make a periodical backup of the mysql DB inside the nextcloud snap for backup purposes.

#### To Reproduce
I've created (well, found online and modified) a shell script to run a backup against the snap. However, when my root cron job tries to run nextcloud.mysqldump, it fails with the log statement:
`nextcloud.mysqldump: not found`

Script source:

```
#!/bin/sh

#----------------------------------------------------
# a simple mysql database backup script.
# version 2, updated March 26, 2011.
# copyright 2011 alvin alexander, http://devdaily.com
#----------------------------------------------------
# This work is licensed under a Creative Commons 
# Attribution-ShareAlike 3.0 Unported License;
# see http://creativecommons.org/licenses/by-sa/3.0/ 
# for more information.
#----------------------------------------------------

# (1) set up all the mysqldump variables
FILE=nextcloud.sql.`date +"%Y%m%d"`

# (2) in case you run this more than once a day, remove the previous version of the file
unalias rm     2> /dev/null
rm ${FILE}     2> /dev/null
rm ${FILE}.gz  2> /dev/null

# (3) do the mysql database backup (dump)
command nextcloud.mysqldump > ${FILE}

# (4) gzip the mysql database dump file
gzip $FILE

# (5) push the file to nas
smbclient -U '' //MYNAS/MYLOC/ ''<< EOC

cd MYDIR
put $FILE.gz
EOC

# (5) show the user the result
ls -l
```

If i execute the script manually (with sudo), it'll work as intended.

#### Expected behavior
I'd like the cron job to be able to execute nextcloud.mysqldump.

#### OS/snapd/snap version
Ubuntu 20.04 Server

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.4snap2  25647  latest/stable  nextcloud*  -

snap    2.48.2
snapd   2.48.2
series  16
ubuntu  20.04
kernel  5.4.0-64-generic

#### Logs
nothing in nextcloud logs

**Comment by scubamuc** [comment]
you can backup nextcloud-snap DB with `nextcloud.export -b` see `nextcloud.export -h` for more info

**Comment by rogieroudshoorn** [comment]
> howzit bru, you can backup nextcloud-snap DB with `nextcloud.export -b` see `nextcloud.export -h` for more info

Hi, thank you for the thought! However, it suffers from the same issue:
`/bin/sh: 1: nextcloud.export: not found`

**Comment by kyrofa** [comment]
Try adding `/snap/bin/` to your `$PATH`.

**Comment by rogieroudshoorn** [comment]
> Try adding `/snap/bin/` to your `$PATH`.

Good idea! However, It's already in /etc/environment

**Comment by kyrofa** [comment]
Are there any `nextcloud.*` commands in there? If not, something is very broken.

**Comment by rogieroudshoorn** [comment]
> Are there any `nextcloud.*` commands in there? If not, something is very broken.

Yeah, they are all there (the things also work when i run it manually). I did however, based on your question, log the PATH that the cron job uses and it's just /usr/bin and bin. So i guess the problem is possibly with my local cron setup.

**Comment by kyrofa** [comment]
Easy solution is to just modify your script to use absolute paths to the commands you care about.

**Comment by rogieroudshoorn** [comment]
For the next person, the solution is found here : https://stackoverflow.com/questions/10129381/crontab-path-and-user

crontabs run with only /bin:/usr/bin, and you have to declare your PATH in the crontab file itself.
