### ISSUE TITLE
20.0.6 Has Hit the Changelog

### ISSUE THREAD

**Issue by stondino00** [nextcloud/nextcloud-snap#1619]
https://nextcloud.com/changelog/

**Comment by stondino00** [comment]
How long does it take again to see beta changes on that snap channel?  Seems like it used to be rather instantly but I'm currently on the beta channel and still don't see the updates pushed yesterday to that branch.

Thanks

**Comment by kyrofa** [comment]
@stondino00 you're right, Travis is failing me. I keep forgetting I need to get off of there. I just manually kicked things over, you should get it in the next few hours.

**Comment by pachulo** [comment]
I don't want to spoil the party, but there seems to be another version just to be released:
https://github.com/nextcloud/server/pull/25368

Fixing another nasty bug: https://github.com/nextcloud/server/pull/25335

Nextcloud really needs a better test-suite...

**Comment by kyrofa** [comment]
Thanks for the heads up @pachulo. Yeah, I've been saying that for years!
