### ISSUE TITLE
High CPU Load - Mysqld

### ISSUE THREAD

**Issue by Dlitosh** [nextcloud/nextcloud-snap#1629]
Hello,

I have the following issue with my nextcloud snap installation:
![image](https://user-images.githubusercontent.com/5259888/106659903-a1947a80-659f-11eb-9e9d-001ad2dad0a6.png)
It continuously runs with over 70% load on CPU when running mysqld process. Sometimes for more than 24hrs.

I see several posts on this here and on general nextcloud forum. The solution usually involves adjusting mysql .cnf file, however I can't do it with a snap installation.

Can someone tell me if there is a way to prevent mysqld process from running that load on the CPU while using the snap version of nextcloud?

Thank you

**Comment by kyrofa** [comment]
Not directly, no. However, this is something I've been unable to duplicate. If you're up for experimenting, I suggest [installing the snap to be writable](https://github.com/nextcloud/nextcloud-snap/wiki/Installing-the-snap-in-writable-mode), and poking at the `my.cnf` file in the root of it (don't do this on a production install, though). If you manage to get it behaving better, share what you did with us and we can try to solve it for everyone.

**Comment by Dlitosh** [comment]
> Not directly, no. However, this is something I've been unable to duplicate. If you're up for experimenting, I suggest [installing the snap to be writable](https://github.com/nextcloud/nextcloud-snap/wiki/Installing-the-snap-in-writable-mode), and poking at the `my.cnf` file in the root of it (don't do this on a production install, though). If you manage to get it behaving better, share what you did with us and we can try to solve it for everyone.

Thank you, I'll try to do that. 
Is it a good idea to backup the data (and configuration files) and then install writable-snap on top of my current installation (so that i can try to reproduce it my data as is?)
And if anything I can later install the normal snap?

**Comment by Dlitosh** [comment]
Come to think of it, i can just backup my snap

**Comment by kyrofa** [comment]
Yeah you can do that. Once you're done experimenting, yes, just install the snap like normal again.

**Comment by mr-bryn** [comment]
I had a similar issue installing the latest NextCloud snap on a fresh debian 10 install. Mysqld process was using lots of CPU and NextCloud via my web browser wasn't accessible.

I found the snap setup was missing the 'core' package - it only had core18.

I removed NextCloud snap, then did `sudo snap install core `and reinstalled NextCloud.
Now mysql is behaving and NextCloud is accessible.
