### ISSUE TITLE
Odd App Store Behavior

### ISSUE THREAD

**Issue by GaryParr** [nextcloud/nextcloud-snap#1640]
Hi,

I installed 20.0.6snap1 on ubuntu 20.04 yesterday and everything seemed fine. Working through some setup today and noticed that Two-Factor TOTP is missing from the app store. Two-Factor UTF is there though.  I'm also seeing apps that should be compatible with Nextcloud (such as Music) showing as untested.

CURL on https://apps.nextcloud.com returns a 200 OK so it doesn't appear to be a network issue on my end and I can't find anything apparent in the logs.

Any suggestions on where to look for root cause or how to "refresh" the app store? 

Thanks,
Gary

**Comment by kyrofa** [comment]
Yeah hold up, that was a [huge bug in 20.0.6](https://github.com/nextcloud/server/pull/25335), 20.0.7 is being tested now.

**Comment by GaryParr** [comment]
Ah, got it. Thanks!

**Comment by kyrofa** [comment]
Alright it's released now, refresh and see if you can get your apps back.
