### ISSUE TITLE
Fix imagick

### ISSUE THREAD

**Issue by tawissus** [nextcloud/nextcloud-snap#1641]
Hello, how to fix/remove imagick error?
Settings - administration Overview

Nextcloud Snap 20.0.7snap1

![Screenshot_20210205-210941](https://user-images.githubusercontent.com/1453423/107083888-9b4c0b80-67f6-11eb-90a5-0ccd978e7a64.png)

**Comment by kyrofa** [comment]
imagick is a security concern, we don't ship it in the snap, I'm sorry.
