### ISSUE TITLE
Some LDAP users not shown in user list, but they exist and can login etc.

### ISSUE THREAD

**Issue by lug-gh** [nextcloud/nextcloud-snap#1643]
#### Describe the bug
Yesterday I was contacted by a colleague that a shared file cannot be opened. I know this error from the past, usually resharing helped. So I searched which user this file belongs to, I remember when opening a shared link, in the top bar it said who it's shared by, but not this time. I don't know if that has anything to do with the problem or if it's just an UI change.
So I searched for the file in the filesystem itself, and found the users LDAP (whatever-)ID, it looks like this: 6F52C7F2-A4CA-4B19-................... (I cannot find that attribute in the attribute editor in our Active Directory)

So I opened up the user list in nextcloud, and noticed there are much less users than there should be, like 20 maybe.
I went to the LDAP connector settings, started the test count and it said there should be 84 users.

My personal user is also missing in the user list, but I still can login, so I guess it's some display error.
Unfortunately I cannot tell how long this issue persists, auto update did a great job the last months or even years.

#### OS/snapd/snap version
Ubuntu 16.04

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.7snap1  26119  latest/stable  nextcloud✓  -

    $ snap version
snap    2.48.2.1
snapd   2.48.2.1
series  16
ubuntu  16.04
kernel  4.4.0-190-generic

#### Logs
Strange: /var/snap/nextcloud/current/logs/nextcloud.log does not exist, but there are many other log files.

![image](https://user-images.githubusercontent.com/24546639/107510491-4ddbef80-6ba4-11eb-9165-3701b978a5db.png)

**Comment by kyrofa** [comment]
I'm afraid my ldap knowledge is effectively zero, I don't even know where to recommend you start looking :cry: . This doesn't sound snap-specific though, you might try logging an issue against [upstream nextcloud](https://github.com/nextcloud/server) and see if they have some insights.

**Comment by lug-gh** [comment]
Okay, but I think thats not gonna help me, as my last bugreport from july 2019 doesn't even have a single reply

then I hope it's gonna self heal with future updates 😁

**Comment by kyrofa** [comment]
You might also try a post at https://help.nextcloud.com/ . I'm sorry I'm useless, here.
