### ISSUE TITLE
How can i add my own custom header and footer?

### ISSUE THREAD

**Issue by JonCSgr** [nextcloud/nextcloud-snap#1648]
Sorry for asking such a silly question but i am not that familiar with snaps . So in a normal installation i would just go over /var/www/ and edit the html file to add my own custom header+ footer.

On snaps where do i need to go and is this even possible ?

**Comment by kyrofa** [comment]
> So in a normal installation i would just go over /var/www/ and edit the html file to add my own custom header+ footer.

First place I'd look for that type of thing is the theming app. If you actually are hoping to modify the PHP, you're out of luck:1

1. You'll get checksum errors from nextcloud itself
2. The snap is read-only, so you can't modify the PHP code anyway

**Comment by JonCSgr** [comment]
Oh i see . Do you have any app in mind that can do the job?
This is the end result i am looking for all the pages of nc. 
![image](https://user-images.githubusercontent.com/61245954/107824378-0e6ef800-6d8a-11eb-8380-1facd7529760.png)

**Comment by kyrofa** [comment]
The [theming app](https://apps.nextcloud.com/apps/theming) is the app I know that does that kind of thing, but there may be others I don't know about. Heck, you could probably make one that'll do that if you had to.
