### ISSUE TITLE
can not run php cli - unable to execute cronjob

### ISSUE THREAD

**Issue by g4ndy** [nextcloud/nextcloud-snap#1650]
#### Describe the bug
If I try to execute /snap/nextcloud/current/bin/php (as a root user - same as snap) I get error:
/snap/nextcloud/current/bin/php: error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory

I need to be able to execute php cli since without it my cron won't execute nextcloud's cron.php
*/5 * * * * /snap/nextcloud/current/bin/php -f /snap/nextcloud/current/htdocs/cron.php

#### Expected behavior
php cli is functional

#### OS/snapd/snap version

nextcloud  20.0.7snap1  26119  latest/stable  nextcloud✓
snap    2.48.3+20.04
snapd   2.48.3+20.04
series  16
ubuntu  20.04
kernel  5.4.0-65-generic

**Comment by kyrofa** [comment]
The snap executes Nextcloud'c cron.php on its own, you don't need a job doing this at all. The interval is [configurable](https://github.com/nextcloud/nextcloud-snap#cronjob-interval-configuration) if you wish.
