### ISSUE TITLE
NextCloud 20.0.8 On Changelog Page

### ISSUE THREAD

**Issue by stondino00** [nextcloud/nextcloud-snap#1656]
https://nextcloud.com/changelog/#latest20

**Comment by Fuseteam** [comment]
sooooo what is the issue?

**Comment by stondino00** [comment]
No issue.  20.0.8 is being released today based on milestones schedule page.

https://github.com/nextcloud/server/milestones

**Comment by Fuseteam** [comment]
> No issue. 20.0.8 is being released today based on milestones schedule page.
> 
> https://github.com/nextcloud/server/milestones

uh I'm sure the team is aware of that :eyes:

**Comment by stondino00** [comment]
Thanks for your unhelpful comments.

**Comment by kyrofa** [comment]
@Fuseteam, thank you for trying to triage the issue. Note that we aren't Nextcloud employees here, just community members. @stondino00 is a longstanding member of our community and is incredibly helpful on keeping tabs on when our dependencies change, from mysql, to php, and yes, Nextcloud itself. No one else notifies us of things like that, we learn about new Nextcloud releases the same way everyone else does. Well, that's not true-- I learn of them from @stondino00, but you get my point :) .

**Comment by Fuseteam** [comment]
> @Fuseteam, thank you for trying to triage the issue, but let's please try to keep the sarcasm to a minimum. Note that we aren't Nextcloud employees here, just community members. @stondino00 is a longstanding member of our community and is incredibly helpful on keeping tabs on when our dependencies change, from mysql, to php, and yes, Nextcloud itself. No one else notifies us of things like that, we learn about new Nextcloud releases the same way everyone else does. Well, that's not true-- I learn of them from @stondino00, but you get my point :) .

uh that wasn't intended as sarcasm my bad

**Comment by stondino00** [comment]
Thanks for the kind words kyrofa.  I'm just trying to do my part and help out.  Sorry for my reply @Fuseteam.

**Comment by Fuseteam** [comment]
no worries @stondino00, i should be one apologizing if I came across as rude or sarcastic

**Comment by stondino00** [comment]
Announced on the blog yesterday.

https://nextcloud.com/blog/nextcloud-20-0-8-and-19-0-9-are-out-update/

**Comment by stondino00** [comment]
Just a reminder @kyrofa
