### ISSUE TITLE
INFO: After "Collabora Online - Built-in CODE Server, Update 6.4.606", extremely slow

### ISSUE THREAD

**Issue by scubamuc** [nextcloud/nextcloud-snap#1661]
**nextcloud  20.0.7snap1  26119  latest/stable  nextcloud**

**app-update**:  Collabora Online - Built-in CODE Server, Update to 6.4.606

**INFO**: app-update causes nextcloud-snap to become extremely slow. 

**Workaround**: deactivate the richdocuments app : `sudo snap run nextcloud.occ app:disable richdocuments`

**Comment by szaimen** [comment]
https://github.com/nextcloud/richdocuments/issues/1282#issuecomment-756816460
