### ISSUE TITLE
HEIC previews

### ISSUE THREAD

**Issue by Dlitosh** [nextcloud/nextcloud-snap#1667]
Would it be possible to include the ported Imagick library (with HEIC support) into the next snap?

https://www.truenas.com/community/threads/nextcloud-20-help-with-heic-support-via-imagick7.89156/

**Comment by ph00lt0** [comment]
Imagick is a security concern, it won't be added.
This is a duplicate issue. Please look into other issues first. https://github.com/nextcloud/nextcloud-snap/issues/1540
