### ISSUE TITLE
I switched my domain & renewed ssl-certificate -> nextcloud still offers the old cert.

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/nextcloud-snap#1671]
I only have one domain and I replaced it like this:
```
sudo snap run nextcloud.occ config:system:set trusted_domains 1 --value=mynewdomain.tld
sudo snap run nextcloud.enable-https lets-encrypt
```
the second command told me that the certificate was generated successfully.

-> I can access the site using the new domain-name but the cert is the old one (also the old date).
I tried with different browsers (cleared cache) & openssl-client.

**Comment by ph00lt0** [comment]
Duplicate issue. 

Temporary solution:
https://github.com/nextcloud/nextcloud-snap/issues/406#issuecomment-354486968
