### ISSUE TITLE
Update not working after migrating snap to manual installation

### ISSUE THREAD

**Issue by UAnton** [nextcloud/nextcloud-snap#1672]
#### Describe the bug
After migrating from snap to manual - no update options.

#### To Reproduce
Migrate snap to manual installation

#### Expected behavior
 NC20 with a possible update to NC21

#### Screenshots
[Scrrenshot](https://paste.pics/BU1W9)

#### OS/snapd/snap version
`Ubuntu `18.04``

`nextcloud  20.0.7snap1  26119  latest/stable  nextcloud✓  -`

snap    2.49
snapd   2.49
series  16
ubuntu  18.04
kernel  4.15.0-136-generic

**Comment by kyrofa** [comment]
Wait, I'm confused, you're logging this against the snap, but you're not using it? Can you clarify your situation for me, please? You may have intended to log this against [Nextcloud itself](https://github.com/nextcloud/server), if you're not using the snap.

**Comment by UAnton** [comment]
> Wait, I'm confused, you're logging this against the snap, but you're not using it? Can you clarify your situation for me, please? You may have intended to log this against [Nextcloud itself](https://github.com/nextcloud/server), if you're not using the snap.

Oh... sorry! My mistake. Wrong section. Sorry!
