### ISSUE TITLE
Session Time

### ISSUE THREAD

**Issue by TidalWave123** [nextcloud/nextcloud-snap#1675]
Hey Guys, 

I'm just curious how do I change the browser session length. I want all of my next cloud users to auto log out after six hours, for security, and have them re-authenticate.

**Comment by kyrofa** [comment]
This doesn't relate specifically to the snap, but check out the various [configuration parameters](https://docs.nextcloud.com/server/20/admin_manual/configuration_server/config_sample_php_parameters.html) available in Nextcloud itself, including things like `session_lifetime` and `auto_logout`. If you need something beyond that, please consider logging an issue against [upstream Nextcloud](https://github.com/nextcloud/server) where folks will know more.
