### ISSUE TITLE
httpd.conf is placed in /snap/ instead of /var/snap/

### ISSUE THREAD

**Issue by brenzi** [nextcloud/nextcloud-snap#1677]
In order to edit the httpd.conf because of #1610 I'd expect the httpd.conf file to be located below `/var/snap...` but instead I found it below `/snap` where it is write-protected

#### OS/snapd/snap version
Ubuntu 20.04 server

nextcloud  20.0.7snap1  26119  latest/stable  nextcloud✓  -
snap    2.49
snapd   2.49
series  16
ubuntu  20.04
kernel  5.4.0-66-generic

**Comment by kyrofa** [comment]
This is working as designed. If we made the apache config writable it's an opportunity for us to break our users in a number of ways.

**Comment by brenzi** [comment]
Well, then how would I fix #1610?

In your snap you assume the apache in your snap will be the only one running on the system. But I'm running apache as a reverse proxy to your snap apache because I have wordpress sites besides nextcloud on the same server.

Now nextcloud thinks all requests come from 127.0.0.1 which always triggers the bruteforce logic for all incoming IP's
I could fix this by accessing the apache config

**Comment by kyrofa** [comment]
> I could fix this by accessing the apache config

How would you go about fixing this if you could?

**Comment by brenzi** [comment]
using 
https://httpd.apache.org/docs/current/mod/mod_remoteip.html

adding this in the snap apache config:
```
RemoteIPHeader X-Forwarded-For
```

**Comment by kyrofa** [comment]
Then your config would immediately break, because [that module isn't built in the snap](https://github.com/nextcloud/nextcloud-snap/blob/master/snap/snapcraft.yaml#L149). You see my point, hopefully.

I'll need to do some investigation and see if that setting would be inappropriate if the snap isn't behind a proxy, and if so this will need to be behind a configuration parameter in the snap. You're welcome to help on that front, if you like.

**Comment by brenzi** [comment]
I agree that the snap should actually accommodate my use case in the first place preferrably ;-)
Can't help, need to focus on other stuff, unfortunately

**Comment by kyrofa** [comment]
Okay, I'll get to it when I have some time, then.

**Comment by brenzi** [comment]
@kyrofa checking back if there is a solution to our problem by now. I still get bruteforce warning and 30s timeout because all attempts count on localhost behind a reverse proxy
