### ISSUE TITLE
Looks like wiki article about moving data directory to other disk is incomplete

### ISSUE THREAD

**Issue by TomBuyvoets** [nextcloud/nextcloud-snap#1694]
It looks like [this](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partitionl) wiki article is incomplete. The issue is, a snap has no access other than its own folder [link](https://help.nextcloud.com/t/changing-data-directory-location-with-snap-installation-procedures/23841).

What happing is. You get an error stating: `Invalid data directory .ocdata is missing` after changing the data directory. 

The fix for me was mounting the disk to `/media` instead of `/data`. And running `snap connect nextcloud:removable-media`.

Are there more people having this issue?

Is there a way to still mount the data disk to `/data` and give snap access to another disk?

**Comment by kyrofa** [comment]
That the [wiki article](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition) explicitly states:

> The partition you want to use must be mounted _somewhere_ in `/media/` or `/mnt/`

It then uses `/media` everywhere. You're not really following it, so I'm not sure I agree with your assertion that it's incomplete :smiley: .

**Comment by TomBuyvoets** [comment]
I totally missed the prerequisites section. Sorry about that. You are right.
