### ISSUE TITLE
Use system CA certificates & /etc/ldap/ldap.conf

### ISSUE THREAD

**Issue by marioqxx** [nextcloud/nextcloud-snap#1697]
#### Describe the bug
Nextcloud snap does not use system CA certificates, but comes with its own.
This might impact security, e.g. compromised CA's.

#### To Reproduce
Is inherently build into the snap. No workaround possible with e.g.:
https://forum.snapcraft.io/t/custom-ssl-certs-for-snapd-to-the-snap-store-communication/17446/2

#### Expected behavior
Snap to use the CA certificates from host /etc/ssl/certs and /etc/ldap/ldap.conf

#### OS/snapd/snap version
Ubuntu Server 20.04.2, Nextcloud 20.0.8snap1

Further references:
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1826362?comments=all

**Comment by kyrofa** [comment]
I'm afraid this is related to snapd itself, not this particular snap. There's nothing we can do about the snap confinement model here.

**Comment by pachulo** [comment]
I don't know if this will be part of the solution, but it seems to me like step on this direction, at least for "classic" systems based on Debian/Ubuntu: https://github.com/snapcore/snapd/pull/9819

**Comment by marioqxx** [comment]
@kyrofa, @pachulo, you are right. I just updated to snap 2.50, which now can see system Ca certfifcates in the nextcloud-shell. 

There is though the remaining issue that custom CA certificates are located in /usr/local/share/ca-certificates/, which is blocked by Apparmor.

This is related to: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1901586

I haven't yet found the correct profile to make the proper additions, but this is hopefully not a so long journey.

Thanks to both of you, I start to understand this now much better!

**Comment by theoneandonly-vector** [comment]
anyone has an update on this?

**Comment by anonymouse64** [comment]
Note that the support added to snapd only allows reading from /etc/ssl from the host, not from /usr/local/share/ca-certificates, so you should put your custom system certificates inside /etc/ssl instead to get the nextcloud snap to see these.
