### ISSUE TITLE
Flow: snap doesn't have permission to access external utilities

### ISSUE THREAD

**Issue by someone755** [nextcloud/nextcloud-snap#1699]
#### Describe the bug
When setting up a flow script, snap apparently cannot run binaries outside of the snap. For example, create a simple shell script and call a binary that is available system-wide, but is not part of the snap (e.g. imagemagick's `convert`), and set up a flow for this script to run. The script's error log will return `convert: not found`

#### To Reproduce
1. Create shell script calling e.g. `convert`
2. Set up Nextcloud Flow to use above script
3. See that `convert` is never run, because it isn't visible to the snap

#### Expected behavior
I'm not sure if this is expected or not (given that each snap is its own container), but it would be very nice if this behavior was documented somewhere, if nothing else for those of us new to nextcloud/snap/linux. (I for one would never have started using nextcloud-snap had I known of this limitation.)

No relevant logs/screenshots to add.

**Comment by kyrofa** [comment]
> I'm not sure if this is expected or not

Yeah, I'm afraid so. The snap can't reach out of its confinement.

> it would be very nice if this behavior was documented somewhere

I'm sorry, but we don't have enough maintainers to go through every possible Nextcloud app and test it with the snap, much less document any idiosyncrasies. You might consider asking individual apps to do this.
