### ISSUE TITLE
feature request: bring in news-updater

### ISSUE THREAD

**Issue by burdickjp** [nextcloud/nextcloud-snap#17]
would it be possible to integrate the news updater?
https://github.com/nextcloud/news-updater

**Comment by kyrofa** [comment]
I'd rather not have a daemon running that people may not use (the news app, while cool, is not preinstalled in Nextcloud). I've not run the news app, though-- a quick read-through of the README with commands like `nextcloud-news-updater https://domain.com/path/to/nextcloud --user admin_user --password admin_password` leads me to believe it's not actually dependent upon Nextcloud (doesn't need access to its config, database, etc.). Is that true? If so, it would be super easy to package in another snap that the user can install if they also install the news app. What do you think?

**Comment by burdickjp** [comment]
I haven't previously used the news updater. I'm just getting my nextcloud instance going and saw that this could be an option. If you feel another snap would be worthwhile then I say it's better than not having it at all. Unless there's a way to have the daemon installed without necessarily having it enabled within a snap. I'm really still trying to get my head wrapped around snaps.

**Comment by kyrofa** [comment]
The thing about snaps is that they bundle all their dependencies. Bundling everything required for every Nextcloud app won't scale, so at least right now I'm focusing on making sure the out-of-the-box experience is a good one and making sure all includes apps are working well. If another snap works for the news updater then I think that's a more scalable approach.

**Comment by burdickjp** [comment]
I think https should be the higher priority, then.

**Comment by kyrofa** [comment]
I'm going to go ahead and close this as I believe the solution is not part of this snap.
