### ISSUE TITLE
occ wrapper not working anymore...

### ISSUE THREAD

**Issue by Guillaume99** [nextcloud/nextcloud-snap#170]
when trying to run the occ command on NC11, I had the following :

root@localhost:/snap/nextcloud/current# ./command-occ.wrapper 
./command-occ.wrapper: 9: exec: occ: not found

**Comment by kyrofa** [comment]
Yeah, don't run it that way, run it as documented in the [README](https://github.com/nextcloud/nextcloud-snap): `sudo nextcloud.occ`

**Comment by Guillaume99** [comment]
I was already root ...

**Comment by Guillaume99** [comment]
oups ...

thx !
