### ISSUE TITLE
Provisioning API application

### ISSUE THREAD

**Issue by chrinats** [nextcloud/nextcloud-snap#1705]
Greetings,

I would like to make requests to my Nextcloud instance using the API. Found the manual below:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_provisioning_api.html

It asks for  **OCS-APIRequest** header to be set to true and **Content-Type: application/x-www-form-urlencoded** .

Is that possible when using the snap installation? I can't even configure/alter the apache conf file. 

Any suggestions on that?

Best regards.

**Comment by kyrofa** [comment]
I don't believe this requires any Apache modifications. Rather, it's referring to what is required in the API _requests_.

**Comment by kyrofa** [comment]
This is what I see in my own production instance (using the snap):

```
$ curl https://my.cloud.com/ocs/v1.php/cloud/users
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Current user is not logged in</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

I believe this works fine, so I'll close. Feel free to reopen if you discover issues.
