### ISSUE TITLE
Background jobs no longer running

### ISSUE THREAD

**Issue by onlinemumie** [nextcloud/nextcloud-snap#1706]
#### Background jobs no longer running

I've been running Nextcloud snap on my Ubuntu server for almost a year now and it has worked well, but a couple of days ago, the feeds on the News app stopped updating. When I logged in as admin on the hub to check what was going on, it turned out that backround jobs have stopped running.

#### Expected behavior

I guess background jobs should be running every 5 minutes, as it says in the setting for Cron.

#### OS/snapd/snap version

nextcloud  20.0.8snap1  27089  latest/stable

snap    2.49.2
snapd   2.49.2
series  16
ubuntu  20.04
kernel  5.4.0-72-generic

#### Logs

Output from script is too long to be a comment - see attached file.
[Logs.txt](https://github.com/nextcloud/nextcloud-snap/files/6361537/Logs.txt)

**Comment by kyrofa** [comment]
What do you get if you run this command manually?

```
$ sudo snap run --shell nextcloud.nextcloud-cron <<'EOF'
. "$SNAP/utilities/nextcloud-utilities"
run-php "$SNAP/htdocs/cron.php"
EOF
```

**Comment by onlinemumie** [comment]
Actually, I get no output when I run the code manually.
When I log in to Nextcloud hub as admin and check settings, background jobs have restarted, but stops again after 5 minutes.

**Comment by onlinemumie** [comment]
I tried this again today and got no response at all in terminal (just a blank line). When I log into the hub as admin, I can see the following error message in the log:

Error PHP Allowed memory size of 536870912 bytes exhausted (tried to allocate 96992160 bytes) at /snap/nextcloud/27089/htdocs/lib/private/AppFramework/Middleware/CompressionMiddleware.php#90

**Comment by kyrofa** [comment]
You can try [increasing the PHP memory limit](https://github.com/nextcloud/nextcloud-snap#php-memory-limit-configuration), but I'm afraid you're exceeding my expertise. Without it printing what its problem is, I'm not sure how to debug why it's not doing anything. This might be a question for upstream Nextcloud. @kesselb might have an idea.

**Comment by onlinemumie** [comment]
Thank you for the link. I have increased the memory limit to 512M now. Perhaps it will do the trick.

**Comment by onlinemumie** [comment]
Update: Increasing PHP memory limit didn't do the trick. Background jobs still run to a halt, but it takes longer now - usually between 6 and 12 hours.

**Comment by onlinemumie** [comment]
[SOLVED] Problem seems to have solved itself after a long period of daily reboots. Background jobs started working again with kernel update 5.4.0-73.
