### ISSUE TITLE
how to edit the layout files in the root directory

### ISSUE THREAD

**Issue by MadMacMig** [nextcloud/nextcloud-snap#1707]
I can't seem to edit the layout.public.php files in the root filesystem. I would like to change loads of things within Nextcloud but I need access to that file. One of these uses are changing the create your free account now button on the footer of a public Nextcloud page and much more.

**Comment by szaimen** [comment]
> One of these uses are changing the create your free account now button on the footer of a public Nextcloud page

You can do this with: 
`nextcloud.occ config:system:set simpleSignUpLink.shown --type=bool --value=false`

**Comment by kyrofa** [comment]
I believe this question has been answered, so I'm going to close. Feel free to continue discussion here.
