### ISSUE TITLE
How to delete all Nextcloud branding and more

### ISSUE THREAD

**Issue by MadMacMig** [nextcloud/nextcloud-snap#1709]
I have been wondering and trying to figure out how to remove all Nextcloud branding and also how to change the look of the whole web interface to my own. One of the big things that I'd like to take out is the Reasons to use Nextcloud footer in settings and more.

Because Nextcloud is truly open source, ii'd like to try and make a fully custom version based on Nextcloud but with a complete different look, and not only use Nextcloud for storage, but also find a way to make it into an OS so that I can also integrate VMs into user's account.

You might wonder why I would like to do this, and the reason is that I am looking to try and start up a cloud company like Dropbox and AWS but all in one. And I thought, because Nextcloud is already very advanced, I thought it would be a great place to start.

**Comment by kyrofa** [comment]
This repo is for the snap, I suggest asking this [upstream](github.com/nextcloud/server).
