### ISSUE TITLE
OCR Integration (dependencies outside Snap container?)

### ISSUE THREAD

**Issue by adamlove86** [nextcloud/nextcloud-snap#172]
Hi there,

Got Nextant working well, and recently upgraded to Nextcloud Snap 11. I've also installed OCR version 2, however dependencies required for OCR are:
- OCRmyPDF
- tesseract-ocr

See (https://github.com/janis91/ocr)

Whilst I've installed these dependencies, they won't connect to the nextcloud snap, or I'm not sure how to make them talk to each other (or how to install them inside the snap container).

Any assistance would be appreciated!

**Comment by kyrofa** [comment]
Yeah, those things should probably be contained within their own snap. Unfortunately, snapd provides no way to get the app contained within said new snap to get into nextcloud. The problem is difficult to solve in a secure manner without that, and it's a known issue, so let's wait for a fix.

**Comment by kyrofa** [comment]
Tracking upstream bug: LP: [#1655125](https://bugs.launchpad.net/snappy/+bug/1655125)

**Comment by adamlove86** [comment]
Came across these snaps the other day - you may already be across it though as he also works at Canonical

https://uappexplorer.com/app/nextcloud-nextant.rmescandon

https://uappexplorer.com/app/solr.rmescandon

**Comment by kyrofa** [comment]
Yep, he ran into the same issue.

**Comment by adamlove86** [comment]
Thanks for your help with this. 
I've moved on from the Snap to the full Nextcloud and all seems to be okay. Feel free to close if you wish as it's no longer an issue for me and there hasn't been any feedback from anyone else regarding this issue.
