### ISSUE TITLE
sudo snap refresh nextcloud NOT found 20.0.9snap2

### ISSUE THREAD

**Issue by King-GO** [nextcloud/nextcloud-snap#1724]
sudo snap refresh nextcloud --stable
sudo snap refresh nextcloud --channel=20/stable
snap refresh nextcloud --channel=stable

CANNOT FIND 20.0.9snap2 

System want to upgrade from 20.0.9snap1 to 20.0.9snap2

**Comment by Domiking001** [comment]
As far as i know, it's not in the stable channel for now, you would need to switch into the candidate channel.

source: https://snapcraft.io/nextcloud

**Comment by kyrofa** [comment]
@Domiking001 is spot on, I haven't released it to stable, yet. I always test it on my own production stack before I push it to everyone, and I wasn't completely happy with it. I'm digging into an issue I found.
