### ISSUE TITLE
MySQL version “5.7.34” is used. Nextcloud 21 will no longer support this version and requires MySQL 8 or higher

### ISSUE THREAD

**Issue by CarlosRuiz-globalqss** [nextcloud/nextcloud-snap#1726]
In a fresh server installed with snap the Overview is showing this message:

MySQL version “5.7.34” is used. Nextcloud 21 will no longer support this version and requires MySQL 8 or higher

Is that something to concern about?

I see the snap installed version is 20.0.9 while the site shows "Latest stable version: 21.0.1"

Will the snap refresh mysql when the version 21 is released?  Otherwise I think is better at this moment to install with another method.

Regards,

Carlos Ruiz

**Comment by kyrofa** [comment]
Can I see the output of `snap list nextcloud --all`, please?

**Comment by CarlosRuiz-globalqss** [comment]
Furthermore, the README.md says:
"
Nextcloud server packaged as a snap. It consists of:
...
    PHP 7.3
    MySQL 8
...
"

which is inaccurate.

**Comment by CarlosRuiz-globalqss** [comment]
> Can I see the output of `snap list nextcloud --all`, please?

sure

```
# snap list nextcloud --all
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.9snap1  27434  latest/stable  nextcloud✓  -

```

**Comment by kyrofa** [comment]
You're out of date. Try `sudo snap refresh nextcloud`. MySQL v8 is contained within 20.0.9snap2.
