### ISSUE TITLE
Webdav timeouts after updating to Snap 20.0.9snap2

### ISSUE THREAD

**Issue by rlKoekie** [nextcloud/nextcloud-snap#1728]
#### Describe the bug
After changing to 20.0.9snap2 (from 20.0.9snap1), connecting to the webdav fails or is very slow. I've searched the logs for errors, but none are thrown. The only suspicious thing I came across was a lot of these warnings in dmesg:
` type=1400 audit(1621067221.119:882): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.nextcloud-cron" pid=23764 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"`

I've reverted back to 20.0.9snap1 and my webdav started working fine again:
`snap revert nextcloud`
followed by `nextcloud.occ files:scan --all` to force an update of the file cache.

#### To Reproduce
`mkdir /tmp/emptydir`
`sudo /bin/mount https://mynextcloud.address/remote.php/dav/files/myUserName/ /tmp/emptydir -t davfs -o user,uid=linuxusername,gid=linuxusername,dir_mode=750`
This takes a very long time or hangs, issuing an "ls" on /tmp/emptydir then also hangs

#### Expected behavior
With 20.0.9snap1 the previous command instantly mounts, and giving an "ls" on the /tmp/emptydir folder returns contents quickly

#### OS/snapd/snap version
snap    2.50
snapd   2.50
series  16
ubuntu  18.04
kernel  5.4.0-74-generic

broken with: nextcloud  20.0.9snap2  27697  latest/stable  nextcloud✓ -
works with: nextcloud  20.0.9snap1  27434  latest/stable  nextcloud✓  -

#### Logs
Sorry, don't have those as I already reverted back and prefer not to break my nextcloud setup again. I can try to reproduce on a different machine if needed

**Comment by Fuseteam** [comment]
this is likely related to the mysql upgrade as noted here, it may take a while on a large database: https://github.com/nextcloud/nextcloud-snap/issues/1626#issuecomment-841251479

**Comment by rlKoekie** [comment]
I reverted back after 12-18 hours. All the other nextcloud functions (web view, desktop/Android client, passwords, etc) did work on the new snap. The only issue for me was slow webdav.
Is the database upgrade something that runs in the background after upgrading the snap? I did not see any significant cpu activity with slow webdav on the new snap.

**Comment by kyrofa** [comment]
Good thought @Fuseteam, but no @rlKoekie-- if you were able to access the web app then the upgrade completed successfully. My wife uses webdav as well and I'm all upgraded, so let me check with her and see if she's been having troubles.

**Comment by rlKoekie** [comment]
I've updated to snap 21.0.1snap1, and the webdav problem did not come back. All is well here, so I'm closing this issue. Thanks to everybody who looked into it!
