### ISSUE TITLE
[SECURITY] Upgrade PHP to 7.0.14

### ISSUE THREAD

**Issue by pachulo** [nextcloud/nextcloud-snap#173]
I haven't seen any issue regarding this (althought the PHP update is from a month ago):
> The PHP development team announces the immediate availability of PHP 7.0.14. This is a security release. Several security bugs were fixed in this release. All PHP 7.0 users are encouraged to upgrade to this version.

- http://www.php.net/ChangeLog-7.php#7.0.14

So I'm opening it just in case.

**Comment by kyrofa** [comment]
Thanks for logging the issue @pachulo. I actually tried upgrading to 7.1 last release. Unfortunately, it seems neither 7.0.14 or 7.1 build on arm64. I'm still investigating.

**Comment by oparoz** [comment]
Shouldn't arm64 be considered a "nice to have" at this stage, like i386? Meaning that it shouldn't block a security feature from making it in?

**Comment by kyrofa** [comment]
We've supported arm64 since the beginning, and I know people who are using it.

**Comment by kyrofa** [comment]
We'll follow PHP bug [#73898](https://bugs.php.net/bug.php?id=73898) and see where it leads.

**Comment by kyrofa** [comment]
Note that the bug has been fixed. The next release will work.

**Comment by pachulo** [comment]
I think that the time has come:
* http://www.php.net/ChangeLog-7.php#7.0.15
* http://www.php.net/ChangeLog-7.php#7.1.1

**Comment by kyrofa** [comment]
@pachulo thanks for the poke. I've verified that 7.1.1 a) works, and b) builds on all supported architectures. This is now available in candidate and targeted at the next release.
