### ISSUE TITLE
The automated update to 21.0.1-snap1 broke 2FA

### ISSUE THREAD

**Issue by darrenmhill** [nextcloud/nextcloud-snap#1738]
#### Describe the bug
Logging in as admin (with 2FA enforced), I got the error saying TFA is not configured and I was only allowed to cancel login or supply a backup code.

#### To Reproduce
1. Login with a 2FA enforced account following upgrade (from V20).

##### I was able to fix using:

sudo -u www-data php occ app:update --all
sudo -u www-data php occ app:enable twofactor_totp

#### Expected behavior
Allows 2FA entry.

**Comment by kyrofa** [comment]
My production instance is configured this way, and I always upgrade it before rolling it out to everyone else. I had no issues with 2fa, and still don't. Given that you were able to fix it with an app update, I suspect the app update that is supposed to happen during upgrade didn't succeed. Can you share your logs?

**Comment by darrenmhill** [comment]
Happy to. Can you please guide me to the right log file/location and I'll attempt to post?

**Comment by darrenmhill** [comment]
I ran the script and there wasn't any obvious error messaging around the time of the update.

**Comment by kyrofa** [comment]
> I was able to fix using:
> 
> sudo -u www-data php occ app:update --all
> sudo -u www-data php occ app:enable twofactor_totp

Ah, just realized you're not actually using the snap. This repo is for the Nextcloud snap. If you would like to log an issue against Nextcloud itself, do that [here](https://github.com/nextcloud/server).
