### ISSUE TITLE
Collabora built in code server error on fresh install

### ISSUE THREAD

**Issue by vincemd22** [nextcloud/nextcloud-snap#1739]
#### Describe the bug
Collabora built in code server error on fresh install

#### To Reproduce
1. install snap 21.0.1snap1 on new VPS

2. add
sudo snap connect nextcloud:removable-media
sudo nextcloud.enable-https lets-encrypt

3. on open Office doc : Failed to load Collabora Online - please try again later

4. in Setting / Collabora Online / Collabora built in code server 
Could not establish connection to the Collabora Online server.

#### Expected behavior

test on Ubuntu 20.04 and Ubuntu 18.04

#### Screenshots
![Screenshot from 2021-05-22 04-57-30](https://user-images.githubusercontent.com/28971404/119212795-00ccbb00-babb-11eb-8319-b940735c90a2.png)

#### OS/snapd/snap version
Ubuntu 20.04.2 LTS
snap 21.0.1snap1

    $ snap list nextcloud

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  21.0.1snap1  27920  latest/stable  nextcloud✓  -

    $ snap version
snap    2.50
snapd   2.50
series  16
ubuntu  20.04
kernel  5.4.0-73-generic

#### Logs

[richdocuments] Error: Exception: Could not find urlsrc in WOPI at <<closure>>

0. /var/snap/nextcloud/27920/nextcloud/extra-apps/richdocuments/lib/TokenManager.php line 208
   OCA\Richdocuments\WOPI\Parser->getUrlSrc("application/vnd.ms-excel")
1. /var/snap/nextcloud/27920/nextcloud/extra-apps/richdocuments/lib/Controller/DocumentController.php line 226
   OCA\Richdocuments\TokenManager->getToken("*** sensitive parameters replaced ***")
2. /snap/nextcloud/27920/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 218
   OCA\Richdocuments\Controller\DocumentController->index("*** sensitive parameter replaced ***", null)
3. /snap/nextcloud/27920/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 127
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocument ... {}, "index")
4. /snap/nextcloud/27920/htdocs/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocument ... {}, "index")
5. /snap/nextcloud/27920/htdocs/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Richdocume ... r", "index", OC\AppFramework\ ... {}, {_route: "richdocuments.document.index"})
6. /snap/nextcloud/27920/htdocs/lib/base.php line 993
   OC\Route\Router->match("/apps/richdocuments/index")
7. /snap/nextcloud/27920/htdocs/index.php line 37
   OC::handleRequest()

GET /index.php/apps/richdocuments/index?fileId=992&requesttoken=kPcRVQnlS3TdVE9SxPmKhFiblI5r0ToixaLdCR386Os%3D%3A1pAhBDqLPC3vMzgWgZfEsSrXwqUsugMU99ioc27J0bI%3D
from 109.10.227.228 by guybrush at 2021-05-22T02:49:28+00:00

**Comment by kyrofa** [comment]
Please log this against collabora.

**Comment by fpennica** [comment]
If someone is interested, this could be a problem with the system fontconfig installation.

I was having the same error in nextcloud logs: `[richdocuments] Error: Exception: Could not find urlsrc in WOPI`, as also reported here: https://github.com/CollaboraOnline/richdocumentscode/issues/119

But checking the richdocuments proxy status: `https://<my.domain.address>/extra-apps/richdocumentscode/proxy.php?status`, it returned a `no_fontconfig` error.

It seems Ubuntu Server doesn't have the required fontconfig libraries installed by default. Installing them the proxy status returns `{"status":"OK"}` and the integrated CODE server works as expected.

It would have been useful if the logs reported the actual proxy error and not the misleading `Could not find urlsrc in WOPI` message.

**Comment by g-work** [comment]
Does somebody know how to solve this error on a Synology Diskstation? Is it possible to get the needed libraries on it?
