### ISSUE TITLE
error update to 21.0.1

### ISSUE THREAD

**Issue by BRBRRIB** [nextcloud/nextcloud-snap#1741]
Hello 

When a try to acess the nextcloud i got a message that a need to update the nextcloud version but when a click in update i got a message error 

Exception: App "Collabora Online - Built-in CODE Server" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: x86_64

I had the snap version on ubuntu Ubuntu 20.04.2 LTS on raspery with arm64.

i try update using snap refresh but the not works.

![Captura de tela de 2021-05-23 16-31-17](https://user-images.githubusercontent.com/54336188/119274052-61a3e280-bbe4-11eb-9b90-7bda82bc9b40.png)

**Comment by kyrofa** [comment]
I suggest deactivating that app, then, or reverting. Sounds like they don't support arm64 on v21, yet.

**Comment by BRBRRIB** [comment]
> I suggest deactivating that app, then, or reverting. Sounds like they don't support arm64 on v21, yet.

How can i do this ? in fact i dont need that app.

**Comment by scubamuc** [comment]
Remove Collabora-Online and CODE-Server:
`sudo snap run nextcloud.occ app:disable richdocuments && sudo snap run nextcloud.occ app:disable richdocumentscore`

**Comment by BRBRRIB** [comment]
> Remove Collabora-Online and CODE-Server:
> `sudo snap run nextcloud.occ app:disable richdocuments && sudo snap run nextcloud.occ app:disable richdocumentscore`

Thanks works.

In my case I disable richdocumentscode, I do not find the richdocumentscore.

Thanks again

**Comment by kyrofa** [comment]
> In my case I disable richdocumentscode, I do not find the richdocumentscore.

You did the right thing, that was just a typo,
