### ISSUE TITLE
MySQL DB Taking up a lot of space - how can I connect to it to see details and clear it out?

### ISSUE THREAD

**Issue by Jsalas424** [nextcloud/nextcloud-snap#1742]
#### Describe the bug
The Nextcloud MySQL files are taking up >30GB for ~90GB worth of data. I can't figure out how to connect to it to actually see which tables are taking up room and potentially clear them out. 

I noticed that my filesystem was nearing max, so I added 15GB but another MySQL file was made within a couple of hours and took it all up instantly. You can see the drop in storage usage in this graph and then the sharp/sudden rise. 

<img width="680" alt="image" src="https://user-images.githubusercontent.com/51519895/119346676-88a3f800-bc68-11eb-8297-76a70e179045.png">

#### To Reproduce

Uncertain. My usage just started climbing rapidly in the past couple of weeks:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/51519895/119346850-ba1cc380-bc68-11eb-991d-af892be7e058.png">

#### Expected behavior
I don't expect MySQL to be taking up so much room for such a small amount of data.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
```
jon@nextcloud:~$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  21.0.1snap1  27920  latest/stable  nextcloud✓  -

```

and:

    $ snap version
```
jon@nextcloud:~$ snap version
snap    2.50
snapd   2.50
series  16
ubuntu  20.04
kernel  5.4.0-73-generic
```

#### Logs
```
jon@nextcloud:~$ sudo du -h --max-depth=1 /var/snap/nextcloud
18G	/var/snap/nextcloud/27920
17G	/var/snap/nextcloud/27697
90G	/var/snap/nextcloud/common
123G	/var/snap/nextcloud
jon@nextcloud:~$ sudo du -h --max-depth=1 /var/snap/nextcloud/27920
8.0K	/var/snap/nextcloud/27920/logrotate
1.2G	/var/snap/nextcloud/27920/nextcloud
3.4M	/var/snap/nextcloud/27920/certs
17G	/var/snap/nextcloud/27920/mysql
36M	/var/snap/nextcloud/27920/logs
19M	/var/snap/nextcloud/27920/redis
18G	/var/snap/nextcloud/27920
```

**Comment by ClaasTeichmann** [comment]
I have the same problem and the / partition was filled completely, leading to an unusable installation of nextcloud-snap.

I think that the cause is an increase in logfile size since the update to nextcloud-snap 21.
Here, you find a discussion about the same problem (with a temporary workaround):
https://help.nextcloud.com/t/nextcloud-snap-21-0-1-with-1gb-mysql-binlog-files-generated-every-1h/116932
He suggests to delete some of the log-files, e.g.,:

    sudo snap stop nextcloud
    sudo rm /var/snap/nextcloud/current/mysql/binlog.000040

Then remove the file `binlog.000040` from the index-file and restart the nextcloud:

    sudo vim /var/snap/nextcloud/current/mysql/binlog.index
    sudo snap start nextcloud

This is of course not practical, as you have to do this manually every other day (depending on the speed of the writing of the logfiles). Also the disk (in my case it is even an SD-card) might get used too much and break soon.

I hope that this problem can be fixed, as I assume that soon many installations will be unusable. If you need further information from my installation, please let me know.

Finally, I think the nextcloud-snap is a great idea as it simplifies many administrative tasks!

**Comment by kyrofa** [comment]
Hang tight folks, I'm on it.

**Comment by mwoelfer-tuwien** [comment]
Correct me if i'm wrong, but I think the underlying issue might be the onlyoffice document server app. Since deactivating it, my log-file size has been stable, might be another unrelated issue though.

**Comment by kyrofa** [comment]
It's possible-- my file sizes are perfectly reasonable, and I don't use onlyoffice or collabora-- but I'm hoping I can figure out a way to rotate them out at least. Right now I'm not even sure why they're enabled, honestly-- the docs lead me to believe they shouldn't be.

**Comment by ClaasTeichmann** [comment]
Hmm, I deactivated:

 * Collabora Online    4.1.1
 * Collabora Online - Built-in CODE Server (ARM64)   6.4.806

but the log-files are still growing, so the problem seems to persist. :-/
@mwoelfer-tuwien or did you deactivate something else?

**Comment by Jsalas424** [comment]
In the meantime, what is the correct way to downgrade my snap to the previous version? I know it's something along the linee of `snap revert ...`

**Comment by kyrofa** [comment]
`sudo snap revert nextcloud` will do it. It won't try to upgrade again until I release an update.

**Comment by kyrofa** [comment]
I've proposed #1747 which lowers the expiration to 7 days (from the default of 30), but that's only going to help those people where 7 days of logs is acceptable. I've seen at least one screenshot where there are several 1GB logfiles from _the same day_ which indicates something (I suspect a Nextcloud app) very badly misbehaving and thrashing the database. @Jsalas424 can you confirm this PR is going to help you, or is something thrashing your DB?

**Comment by kyrofa** [comment]
You know what, nevermind. I'm going with #1748 and disabling the binary logging entirely.

**Comment by kyrofa** [comment]
Keep an eye on [these builds](https://launchpad.net/~nextcloud-snap-dev/+snap/nextcloud-beta). Once they're done, run `sudo snap refresh nextcloud --channel=latest/beta` and see if the binlogs stop growing.

**Comment by kyrofa** [comment]
All builds are done now, FYI. The snap revision is `21.0.1snap1+git2.15a9d78`.

**Comment by Jsalas424** [comment]
> All builds are done now, FYI. The snap revision is `21.0.1snap1+git2.15a9d78`. If you want to hold out for the 21.0.1snap2 release I'll try to ship it tonight.

Awesome, so now I should run `sudo snap refresh nextcloud --channel=latest/beta` correct?

**Comment by Jsalas424** [comment]
Also will this erase the crazy large DB entries already in there or what is the correct procedure now to clean that up?

**Comment by ClaasTeichmann** [comment]
@kyrofa It looks like the snap revision `21.0.1snap1+git2.15a9d78` fixes the problem, as no more binlog.0000.. files are written out. :+1: 
@Jsalas424 Old binlog.0000... files are not deleted. I stopped nextcloud and deleted the old ones except for one (just in case) and also edited `binlog.index` accordingly.
The binlog files are here, e.g.: `/var/snap/nextcloud/current/mysql/binlog.000043`
(it would be good to delete the files before upgrading, otherwise they are copied to the new revision of nextcloud-snap)

**Comment by KennyRal** [comment]
I had the same issue.
I've stopped mysql and nextcloud.snap.mysql.service deleted the logbin.0000XX files and deleted their filename from the logbin.index file, restarted mysql and nextcloud.snap.mysql.service
Installed the snap revision is 21.0.1snap1+git2.15a9d78
I've also rebooted the unit.
The hourly generation of the 1GB binlog.000XX files stopped. GOOD thank you!
But now I'm still stuck with the very high CPU usage coming from "php-fpm: pool www".
From within NextCloud I've already disabled Collabora Online and Collabora Online - Built-in CODE Server

Any idea on that?

**Comment by KennyRal** [comment]
Relate to my previous comment: Is this memory usage normal?
![Screenshot from 2021-05-30 07-40-18](https://user-images.githubusercontent.com/85049374/120093419-6a337600-c11a-11eb-961a-a09602e9fdca.png)

**Comment by ClaasTeichmann** [comment]
@KennyRal in my case there is no high CPU usage.

**Comment by nalberto** [comment]
If anyone need a temp solution to clear disk space do the following

check binlog file size first

```
cd /var/snap/nextcloud/current/mysql
ls -la
```
make note of the latest binlog file. Something like binlog.0000014
connect to mysql using nextclound mysql client and remove old logs

`sudo nextcloud.mysql-client -S /tmp/sockets/mysql.sock -u root`
no password needed for command above

`PURGE BINARY LOGS TO 'binlog.0000XX';`

where XX is the latest two digits of the latest binlog file

This made it for me.

**Comment by kyrofa** [comment]
> `PURGE BINARY LOGS [...]`

Yeah I think that's probably the best way to do this.

**Comment by pachulo** [comment]
@kyrofa should we backport this to stable/20?

**Comment by kyrofa** [comment]
@pachulo yes, please.

**Comment by pachulo** [comment]
> @pachulo yes, please.

@kyrofa would you mind creating a `20` branch that starts before the switch to nextcloud 21? Thanks!

**Comment by kyrofa** [comment]
Done!
