### ISSUE TITLE
How to add values to "my.cnf" that survive an automatic update of nextcloud-snap?

### ISSUE THREAD

**Issue by UweKeim** [nextcloud/nextcloud-snap#1744]
Since recently my disk runs full because of the [Binary Log of MySQL](https://dev.mysql.com/doc/refman/8.0/en/binary-log.html) takes up too much space.

(My content files are located in AWS S3 buckets, so my primary hard disk is intentionally rather small)

I found out that I can configure to have fewer binary logs by configuring the [`binlog_expire_logs_seconds`](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_expire_logs_seconds) variable inside "my.cnf".

Since every Snap version of Nextcloud brings its own "my.cnf", there is no way I see to make such an addition to "my.cnf" without being forced to do this every time Nextcloud is updated via Snap.

E.g.:

```
/snap/nextcloud/27920/my.cnf
/snap/nextcloud/27697/my.cnf
```

Using the `nextcloud.mysql-client` I also found no way to specify such a setting for "my.cnf".

### My question

Is there a known way to tell nextcloud-snap some configuration values for MySQL that are automatically propagated to a newly, automatically installed nextcloud-snap?

**Comment by kyrofa** [comment]
> Is there a known way to tell nextcloud-snap some configuration values for MySQL that are automatically propagated to a newly, automatically installed nextcloud-snap?

I'm afraid not. But you're not the only one who's had exactly this problem since the update to mysql v8, which apparently has a bug that enables the binary logs when we didn't expect it. Please see #1742.
