### ISSUE TITLE
Mysql Binlogs 1.2gb full my harddrive on ubuntu server

### ISSUE THREAD

**Issue by igherardia** [nextcloud/nextcloud-snap#1745]
This is the mysql log or backup that generates 1gb files and fills the hard disk.
NEXTCLOUD did not send an email warning about a disk almost full

![error nextcloud](https://user-images.githubusercontent.com/51250424/119991799-38969f80-bfa0-11eb-829d-75e1cdca75ff.png)

**Comment by kyrofa** [comment]
Note that while we're fixing this, it indicates that your mysql is being absolutely thrashed by something. This is not normal. Check your apps and logs.
