### ISSUE TITLE
Error "Could not rename part file to final file" on file upload to shared subfolder inside a group folder

### ISSUE THREAD

**Issue by jassonmc** [nextcloud/nextcloud-snap#1746]
#### Describe the bug
Since automatic Upgrade from 20.0.9snap1 to 21.0.1snap1, upload of files into a shared subfolder (shared with a named user) of a group folder does no longer work with error message "Could not rename part file to final file".

Interestingly, the issue seems to ONLY occur in combination as described above.
It does not occur when the very same subfolder inside that group folder is shared with an external link, nor does it happen when a folder inside a normal folder is shared with a user or an external link.

It might be related to this, but since the snap is immutable, I can't test the proposed fix there:
https://github.com/nextcloud/server/issues/8942

#### To Reproduce
Steps to reproduce the behaviour:
1. Create a group called "INTERNAL" and add the standard NC admin to that group
2. Install App "Group folders"
3. Create a group folder "GROUP-Files" and assign to group "INTERNAL"
4. As NC admin, create inside that Folder "GROUP-Files" a subfolder called "HR-Docs"
5. Share that subfolder "HR-Docs" now with an existing user and allow to upload files
6. Login as the user and try to upload a file into that shared folder "HR-Docs"
7. Uploading starts and aborts with error "Could not rename part file to final file"

#### Expected behavior
The upload should go through.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  21.0.1snap1  27920  latest/stable  nextcloud✓  -

and:

    $ snap version
snap    2.50-1.el8
snapd   2.50-1.el8
series  16
centos  8
kernel  4.18.0-240.22.1.el8_3.x86_64

#### Logs
Following is logged in protocol area in nextcloud admin gui when I try to upload a file:
Error: Cannot modify header information - headers already sent by (output started at /snap/nextcloud/27920/htdocs/3rdparty/sabre/http/lib/Sapi.php:132) at /snap/nextcloud/27920/htdocs/apps/dav/lib/Connector/Sabre/File.php#691	
2021-05-28T16:59:03+0200
Error	PHP	Error: Cannot modify header information - headers already sent by (output started at /snap/nextcloud/27920/htdocs/3rdparty/sabre/http/lib/Sapi.php:132) at /snap/nextcloud/27920/htdocs/apps/dav/lib/Connector/Sabre/File.php#691	
2021-05-28T16:59:03+0200
Error	PHP	Error: Cannot modify header information - headers already sent by (output started at /snap/nextcloud/27920/htdocs/3rdparty/sabre/http/lib/Sapi.php:132) at /snap/nextcloud/27920/htdocs/apps/dav/lib/Connector/Sabre/File.php#691	
2021-05-28T16:59:03+0200
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	
2021-05-28T16:59:03+0200
Error	webdav	renaming part file to final file failed $renameOkay: false, $fileExists: false)	
2021-05-28T16:59:03+0200
Error	core	unable to rename, file does not exists : /var/snap/nextcloud/common/nextcloud/data/ESP/Educa Rahmenvertrag Microsoft - 17.05.21.pdf.ocTransferId2007953689.part	
2021-05-28T16:59:03+0200

**Comment by kyrofa** [comment]
It does indeed sound like nextcloud/server#8942. There's nothing we can do about it here, as soon as it's fixed upstream and contained in a release, it'll be fixed here. Hang tight. Remember you can revert back to v20 as well, assuming you still have a v20 revision around.
