### ISSUE TITLE
Search function is now just searching but nothing is coming up

### ISSUE THREAD

**Issue by Keaters2913** [nextcloud/nextcloud-snap#1750]
#### Describe the bug
When you click on the magnify glass icon to do a index search of something, it will not yield any results.  It just spins with empty greyed out icons but nothing will appear.

#### To Reproduce
1) Go to Files
2) Click on the Magnify Glass icon and type in the name of a file to find it including the file extension in the search as well
3) All I get is a spinning icon if it is searching for the file, but nothing will come up after 10 minutes

#### Expected behavior
The file and other similar named files should come up in the search field when searching in Files section.

#### Screenshots

![image](https://user-images.githubusercontent.com/77809014/120216757-6deff700-c205-11eb-97a8-95300ad288da.png)

#### OS/snapd/snap version
What OS and version are you running? (Ubuntu 20.0.4) Please also include the output of the
following commands:

    $ snap list nextcloud

NextCloud 21.0.1snap2 Rev 28088 Latest/StableSna

and:

    $ snap version

snap 2.50
snapd 2.50
series 16

#### Logs
Error | core | Doctrine\DBAL\Query\QueryException:&nbsp;More than 1000 expressions in a list are not allowed on Oracle. | &nbsp; | 2021-05-31T11:29:40-0400
-- | -- | -- | -- | --
Error | core | Doctrine\DBAL\Query\QueryException:&nbsp;More than 1000 expressions in a list are not allowed on Oracle. | &nbsp; | 2021-05-31T11:29:39-0400
Error | core | Doctrine\DBAL\Query\QueryException:&nbsp;More than 1000 expressions in a list are not allowed on Oracle. | &nbsp; | 2021-05-31T11:28:22-0400
Error | core | Doctrine\DBAL\Query\QueryException:&nbsp;More than 1000 expressions in a list are not allowed on Oracle. | &nbsp; | 2021-05-31T11:28:21-0400

**Comment by Keaters2913** [comment]
Please Note, The file in the screenshot I am searching for is in the folder I have open in that screenshot

**Comment by kyrofa** [comment]
This sounds like an upstream bug, I suggest logging it [there](https://github.com/nextcloud/server).

**Comment by Keaters2913** [comment]
I just opened a case with the link you provided and they said since it is a snap repository edition, that I have to post in here

**Comment by ph00lt0** [comment]
@Keaters2913 likely related to https://github.com/nextcloud/server/issues/26493

**Comment by ph00lt0** [comment]
Seems there is quite a lot going here see also: https://github.com/nextcloud/server/pull/25036
