### ISSUE TITLE
Bug with Searching with NextCloud 20.0.1Snap2

### ISSUE THREAD

**Issue by Keaters2913** [nextcloud/nextcloud-snap#1752]
#### Describe the bug
When you click on the magnify glass icon to do a index search of something, it will not yield any results. It just spins with empty greyed out icons but nothing will appear.  I have opened a ticket with the NextCloud Server Github page, but they said since it is a Snap repository edition, I am supposed to log the ticket in here.

#### To Reproduce
1. Go to Files
2. Click on the Magnify Glass icon and type in the name of a file to find it including the file extension in the search as well
3. All I get is a spinning icon if it is searching for the file, but nothing will come up after 10 minutes

#### Expected behavior
The file and other similar named files should come up in the search field when searching in Files section.

#### Screenshots
https://user-images.githubusercontent.com/77809014/120216757-6deff700-c205-11eb-97a8-95300ad288da.png

Please note, in this image, the file I am searching is in the IT Projects folder.

#### OS/snapd/snap version
What OS and version are you running? (Ubuntu 20.0.4) Please also include the output of the
following commands:

    $ snap list nextcloud

NextCloud 21.0.1snap2 Rev 28088 Latest/Stable Snap

and:

    $ snap version

snap 2.50
snapd 2.50
series 16

#### Logs

Error | core | Doctrine\DBAL\Query\QueryException:&nbsp;More than 1000 expressions in a list are not allowed on Oracle. | &nbsp; | 2021-06-01T09:29:40-0400
-- | -- | -- | -- | --
Error | core | Doctrine\DBAL\Query\QueryException:&nbsp;More than 1000 expressions in a list are not allowed on Oracle. | &nbsp; | 2021-06-01T09:29:39-0400
Error | core | Doctrine\DBAL\Query\QueryException:&nbsp;More than 1000 expressions in a list are not allowed on Oracle. | &nbsp; | 2021-06-01T09:28:11-0400
Error | core | Doctrine\DBAL\Query\QueryException:&nbsp;More than 1000 expressions in a list are not allowed on Oracle. | &nbsp; | 2021-06-01T09:28:10-0400

**Comment by Keaters2913** [comment]
Here are some additional logs showing a newer error when doing a search:

Error | PHP | Error:&nbsp;Trying to access array offset on value of type bool at /snap/nextcloud/27920/htdocs/apps/files_external/lib/Lib/Storage/SFTP.php#335 | &nbsp; | 2021-06-01T10:06:50-0400
-- | -- | -- | -- | --
Error | PHP | Error:&nbsp;Trying to access array offset on value of type bool at /snap/nextcloud/27920/htdocs/apps/files_external/lib/Lib/Storage/SFTP.php#331 | &nbsp; | 2021-06-01T10:06:50-0400
Error | PHP | Error:&nbsp;Trying to access array offset on value of type bool at /snap/nextcloud/27920/htdocs/apps/files_external/lib/Lib/Storage/SFTP.php#335 | &nbsp; | 2021-06-01T10:06:50-0400
Error | PHP | Error:&nbsp;Trying to access array offset on value of type bool at /snap/nextcloud/27920/htdocs/apps/files_external/lib/Lib/Storage/SFTP.php#331 | &nbsp; | 2021-06-01T10:06:50-0400

**Comment by kyrofa** [comment]
> I have opened a ticket with the NextCloud Server Github page, but they said since it is a Snap repository edition, I am supposed to log the ticket in here.

That's unfortunate, looking at the errors, it appears that this issue has nothing to do with the snap. If they're not willing to help you, there's nothing I can do. We ship vanilla Nextcloud, it's not like we maintain a fork.
