### ISSUE TITLE
Why remove something that’s not broken? Self signed ssl

### ISSUE THREAD

**Issue by t3dium** [nextcloud/nextcloud-snap#1771]
**2nd EDIT: the issue isn’t with nextcloud, I just needed to reboot after installing snapd for the first time, everything works fine now.**

**EDIT: it appears that no occ commands work when using nextcloud’s snap, this wasn’t an issue in order versions**

> sudo nextcloud.enable-https self-signed

The command is gone in newer versions of nextcloud

_Meaning that in order to use https you’ll either need to get a public domain, and use letsencrypt. Or to selfhost within LAN, install nginx proxy manager, learn how to actually use it, generate an OpenSSL certificate/key and manually repeat this every 365 days as the certificate will expire (due to ios restrictions)_

Please bring back the command, don’t remove something that’s not broken as previously there was an option for self-signed and letsencrypt. If anything, you’re making it much less accessible for beginners

Does anyone know where the ssl path is, so that I could potentially import my own ssl key/cert?

**Comment by kyrofa** [comment]
> don’t remove something that’s not broken as previously there was an option for self-signed and letsencrypt

Don't worry, I agree completely :) . It sounds like the OS you're using doesn't have `/snap/bin` in the PATH, so rebooting it sources the changes installing snapd made to your environment. I'm afraid we have no control over how that aspect works, but rest assured that we're not planning on breaking anything.
