### ISSUE TITLE
Remove link “Get your own free account” in sharing Tab

### ISSUE THREAD

**Issue by Domiking001** [nextcloud/nextcloud-snap#1775]
#### Describe the bug
When sharing a folder and going into that link, Nextcloud "promotes" signing up on its own website www.nextcloud.com, which isn't even possible, and i think it would be better to exclude that as a standard, as it's pretty simple.
See [https://help.nextcloud.com/t/remove-link-get-your-own-free-account/41131/2] (Nexctloud Forum Issue with solution)

#### To Reproduce
1. Go to a folder in your Nextloud (Webinterface)
2. Click on the sharing button
3. "Share link"
4. Paste that link into a new tab
5. Look at the bottom for the promoting line

#### Expected behavior
I think the link is useless and should be disabled by default, it has no advantage. Without that link the sharing screen looks more clean.

#### Proposed solution
I tested the solution myself on my own instance (NC 21), and it's pretty easy, it only requires a new line in the standard config file under 
`/var/snap/nextcloud/current/nextcloud/config/config.php`
which just includes
`'simpleSignUpLink.shown' => false,`

(I'm new to github so i don't really know how i could change the config with an own branch myself, neither do i know how such desicions are evuluated if it should be made or not, so i just opened it as an issue)

**Comment by kyrofa** [comment]
I suggest logging this issue against [upstream nextcloud](https://github.com/nextcloud/server), this definitely isn't a decision we made.
