### ISSUE TITLE
Integrate fixes from upstream

### ISSUE THREAD

**Issue by JMoVS** [nextcloud/nextcloud-snap#1776]
#### Describe the bug
I am facing the bug https://github.com/nextcloud/groupfolders/issues/1445 that is fixed by https://github.com/nextcloud/server/pull/27015 - is this already integrated in the latest snap version? (sry I don't know an IRC or email to ask this directly)

**Comment by kyrofa** [comment]
Looks like it's in v21.0.3 which is currently building and will be released to stable shortly. You can test out the beta channel to confirm though:

    $ sudo snap install nextcloud --beta

**Comment by kyrofa** [comment]
Also: this is a perfectly find place to ask questions! I much prefer this than having people email me :) .

**Comment by JMoVS** [comment]
> Looks like it's in v21.0.3 which is currently building and will be released to stable shortly. You can test out the beta channel to confirm though:
> 
> ```
> $ sudo snap install nextcloud --beta
> ```

is there an easy way to migrate from beta to release again?

**Comment by kyrofa** [comment]
Yeah 21.0.3snap1 is in stable now, so just switch back:

    $ sudo snap refresh nextcloud --stable

**Comment by kyrofa** [comment]
I'm going to go ahead and close this since I believe this is fixed.
