### ISSUE TITLE
Cron didn't run for 13 days

### ISSUE THREAD

**Issue by JMoVS** [nextcloud/nextcloud-snap#1788]
#### Describe the bug
My Nextcloud today showed me that it didn't run crown for 13 days

#### To Reproduce
unclear

#### Expected behavior
Cron should run

#### Screenshots
![grafik](https://user-images.githubusercontent.com/7354506/125031211-984a9500-e08c-11eb-9c33-ff1056a3a741.png)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  21.0.1snap2  28088  latest/stable  nextcloud✓  -

and:

    $ snap version
snap    2.51.1
snapd   2.51.1
series  16
ubuntu  20.04
kernel  5.4.0-70-generic

#### Logs
Sadly were too long:

[log.log](https://github.com/nextcloud/nextcloud-snap/files/6789183/log.log)

**Comment by kyrofa** [comment]
> Apr 12 11:01:12 vmd57702.contaboserver.net systemd[12331]: snap.nextcloud.nextcloud-cron.service: Changing to the requested working directory failed: No such file or directory
Apr 12 11:01:12 vmd57702.contaboserver.net systemd[12331]: snap.nextcloud.nextcloud-cron.service: Failed at step CHDIR spawning /usr/bin/snap: No such file or directory
Apr 12 11:01:12 vmd57702.contaboserver.net systemd[1]: snap.nextcloud.nextcloud-cron.service: Main process exited, code=exited, status=200/CHDIR

I'm afraid I have no idea what's happening here, this looks systemd or snapd related. The cron job doesn't change directory at all, and `/usr/bin/snap` should definitely exist. I suggest logging this against upstream snapd and see what they have to say.

**Comment by JMoVS** [comment]
those are from April...

But it apparently solved itself after 21.0.3 ;-)
