### ISSUE TITLE
news app requires 64bit php

### ISSUE THREAD

**Issue by mau2806** [nextcloud/nextcloud-snap#1790]
#### Describe the bug
App "news" (V16) requires OS 64 bit (https://apps.nextcloud.com/apps/news/releases?platform=20#20)
So I moved my raspberry pi 4 to 64bit.

#### To Reproduce
Installing news app will not work any longer using Version 16 or higher
because php Version needs to be a 64bit Version

#### Expected behavior
Support of 64bit arm packages to meet php package requirements?

#### Error message
App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.

#### OS/snapd/snap version
snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  21.0.3snap1  28399  latest/stable  nextcloud✓  -

and:

snap version
snap      2.51.1
snapd     2.51.1
series    16
raspbian  10
kernel    5.10.46-v8+

#### Logs
n.a.

**Comment by kyrofa** [comment]
Here is my map for the latest release:

```
Track    Arch     Channel    Version            Revision
latest   amd64    stable     21.0.3snap1        28403
                  candidate  ↑                  ↑
                  beta       ↑                  ↑
                  edge       master-2021-06-15  28354
         arm64    stable     21.0.3snap1        28404
                  candidate  ↑                  ↑
                  beta       ↑                  ↑
                  edge       master-2021-06-15  28366
         armhf    stable     21.0.3snap1        28399
                  candidate  ↑                  ↑
                  beta       ↑                  ↑
                  edge       master-2021-06-15  28365
         i386     stable     21.0.3snap1        28402
                  candidate  ↑                  ↑
                  beta       ↑                  ↑
                  edge       master-2021-06-15  28363
         ppc64el  stable     21.0.3snap1        28398
                  candidate  ↑                  ↑
                  beta       ↑                  ↑
                  edge       master-2021-06-15  28356
```

As you can see, I have both armhf and arm64 releases, but you're installing the armhf one. I can't speak to how snapd determines the snap arch to grab, but are you certain you're running an arm64 OS? Can I see the output of `uname -a`, please?

**Comment by mau2806** [comment]
I am running a 64 bit kernel, but I changed to it from a 32 bit installation. So all seems correct from the nextcloud-snap. I'll test a new installation with the arm64 install image to move to your arm64 branch.
Thanks!
