### ISSUE TITLE
RaspiPi homeserver suddenly died

### ISSUE THREAD

**Issue by btcviking** [nextcloud/nextcloud-snap#1793]
Hello,

Today my homeserver died in a really mysterious way. I restarted it after doing some usual maintenance and setting a new hostname via 'sudo raspi-config', but it never booted up again. Totally unresponsive via ssh and no way for me to get in. 

Unfortunately I have no way now to use nextcloud.export which would have been the probably best way to migrate into a new installation. I want to continue using nextcloud snap and I also have all the data of the former nextcloud that was installed on the now dead homeserver. So, the files should be fine and I actually have some backup of the hard drive as I had set it up in a raid. 

What would be the best way to set up a new installation for me? Is it possible to somehow set up a new pi 4 and install a fresh nextcloud snap into the old data with the same users? I have done some research and it seems there are ways to migrate mass data (rsync) but most solutions involve the old instance to work. I only have the hard drive(s).

Your help would be much appreciated. 

P.s: This would be helpful to know in general. What to do when the homeserver suddenly dies but you have all the data? 

Thank you. Would be glad and sponsor a coffee/beer via the lightning network!

**Comment by kyrofa** [comment]
Absolutely! I need to finish making the kids lunch and I need to sit down and type this out, but I wanted to respond real quick to ease your fears.

**Comment by kyrofa** [comment]
On your old hard drive, I need to see the output of this command:

    $ ls -ld /path/to/mount/var/snap/nextcloud/current

**Comment by kyrofa** [comment]
I also need to see the contents of `/var/snap/nextcloud/current/nextcloud/config/config.php`. Please mask out sensitive values, like the database password etc.

**Comment by btcviking** [comment]
Hey, 
thank you for the quick response. So I guess I will need to use the hard drive on another Linux instance I need to setup to run these commands on it?! 
I will do that right this morning and get back to you! Thank you again for the quick response!

**Comment by btcviking** [comment]
Hey, I seem to face an issue here. The ssd is not being shown when plugged in to my newly setup ubuntu. When I try to mount it, it simply says 'unknown file system type 'linux_raid_member'.

Any ideas? I have tried to find a way to mount it and it seems complicated, but if you agree I would proceed with the process described here: https://serverfault.com/questions/383362/mount-unknown-filesystem-type-linux-raid-member

If you have a better idea please let me know. Thank you!

**Comment by btcviking** [comment]
Just as a comment: I do have both drives belonging to the raid, none of them failed or anything. So if there is a way to mount it without stoping the RAID, that would even be better.

**Comment by ph00lt0** [comment]
@btcviking I think you shouldn't mount it directly if you have configured it as raid, you need to assemble the RAID first. Might be wise to add --readonly also so that you do not change the contents of the drive.

Did you do something like this?
https://unix.stackexchange.com/questions/300122/mount-a-single-hard-disk-that-was-part-of-raid-1

**Comment by btcviking** [comment]
@ph00lt0 thank you for your answer. I haven't done this yet as I rather wanted to check if there is a better option. I do have both hard drives, they are running on a hub and I can plug them both in so I do not "have to" degrade the array per se. 

It is a good idea to work with mdadm --readonly however I wasn't so sure about the process. So what I think or get from your message is that I have to assemble the raid first to access the files? In this case I would connect them to my Ubuntu laptop (which I use only temporarily to access the drive before putting it back together with a fresh nextcloud install) and have to 

`mdadm --assemble --scan --verbose --readonly`

I hope this would give me an option to then mount it so I can proceed with 
`ls -ld /path/to/mount/var/snap/nextcloud/current` 
..and the config.php?!

**Comment by btcviking** [comment]
..or should I to make it easier for me just already set up a fresh Debian Pi4 which I am going to use as the new home server and toss the "temporary laptop with Ubuntu" in the first place? 
I probably can save some work doing it straight via the Pi intended for the fresh nextcloud installation anyway, correct?

Sorry for the confusion.

**Comment by ph00lt0** [comment]
@btcviking afaik assembling is the only option you have but I am not an expert with this. Maybe others have a better option.

In order to get you back up I would definitely make a fresh install and use nextcloud.import. Maybe you could start the drive directly in the new rpi, but only do this if you have a backup of your data.

**Comment by kyrofa** [comment]
> So I guess I will need to use the hard drive on another Linux instance I need to setup to run these commands on it?!

Yes, and you'll need to use it on another machine to pull the data off of it as well, but you won't need to use it long-term unless you want to. However, I hesitate on giving advice regarding how to do that; I'm not an mdadm pro and really don't want to mess up your data-- take your time and do your research, and once you're able to give me the info I need, we can continue this process.

**Comment by btcviking** [comment]
@kyrofa I have a third hard drive as a clone to be extra secure. I think I should use that then to try around before trying to assemble the raid? I was just thinking I have to use the raid to give the right result of
`las -ld /path/to/mount/var/snap/nextcloud/current`

It might even be easier to accomplish as it is not a 'part' of the raid. I understand the hesitance to tell me what to do, but I will take this as learning experience. If the data gets lost I still do have most of the data somewhere else as I was in the process of moving that data, but kept most important files on the laptops and phones. Thank you everyone for your advice: @kyrofa @ph00lt0 

@ph00lt0 after some more reading I think you are totally right. I did manage to make a fresh install of Debian on another raspi pi that I intend to use as my next homeserver. It already shows more info when trying `sudo fdisk -l` it shows both hard drives and another instance of /dev/md127 which should be the super block of the raid it seems. I wasn't able to mount it but it is promising that I could assemble it now without changing or losing data.

**Comment by kyrofa** [comment]
@btcviking that may not be entirely true. The reason I wanted you to run that command was so that we knew for certain which revision of the snap owned the data you wanted to import. If you're going to import from another backup hard drive, then we no longer care about which revision you were running in production-- what revision owned the data you want to import from the backup? We determine that by the `current` symlink in that directory, which you will also probably have on the backup HD (although it kind of depends on what kind of backup that is-- full clone?

**Comment by ph00lt0** [comment]
@btcviking I agree with @kyrofa that it would be good to find the cause to prevent it from happening another time. But glad it worked out.

**Comment by btcviking** [comment]
@kyrofa Yes, it is a full clone. It's a function of the hub I am using "offline clone". 

I understand now what you were trying to understand. However, I wanted to give a little update on the situation. I was able to revive the pi that initially seemed dead. I attached my TV to it and a super old keyboard then it showed me that it launched the emergency shell with the error "Cannot open access to console. The root account is locked see sulogin(8) man page for more details". 

The last thing before the pi didn't boot normally again was I'm changed the host name and locale settings with:
`sudo raspi-config`
Did I do sth I shouldn't be doing once the system is up and running?

I think it would be best if I get this to boot again and then do a nextcloud.export...well, depending on whats "easier" to do. I have read so far that I may have an issue in the /boot/cmdline.txt file which I could open and fix from another instance (Ubuntu laptop). I just wanted to check in with you to hear what you think. I also will attach pictures of what it is showing me. It is in some kinda loop, at least the emergency shell doesn't let me do anything. If I get this out of the way I could do everything else via ssh again. 

This was helpful in understand a little: https://www.raspberrypi.org/forums/viewtopic.php?p=1268468

As well as :
http://www.htgsd.com/information-technology/fix-rpi-with-cannot-open-access-to-console-the-root-account-is-locked/

![image](https://user-images.githubusercontent.com/69312355/126066264-fe2588f0-3395-421c-9ffe-b174efb19bc7.jpeg)

![image](https://user-images.githubusercontent.com/69312355/126066268-795e4678-33eb-4fc1-b004-607e83a066c6.jpeg)

**Comment by kyrofa** [comment]
> I think it would be best if I get this to boot again and then do a nextcloud.export

Oh absolutely, if you can get the thing running a lot more options open up.

**Comment by btcviking** [comment]
@kyrofa did you ever face this issue or have an idea what I could do? Just don't want to destroy this chance by foolishly editing the cmdline.txt 

I know your time is precious. So if not it's fine but if you ever experienced this I'd appreciate a link or your input :)

**Comment by btcviking** [comment]
@kyrofa UPDATE: I am now able to communicate with the pi via cli but not ssh or anything. I do not know the state of my 'fstab' file from before but it seems fine to me (attached is a picture).

![image](https://user-images.githubusercontent.com/69312355/126157049-cf468f83-230f-4a11-8184-1e90ff3caa60.jpeg)

My cmdline.txt looks like this:
`console=serial0,115200 console=tty1 root=PARTUUID=6c586e13-02 roots type=ext4 elevator=deadline rack.repair=yes rootwait` + `init=/bin/sh` which made me able to type in the shell. 

Also I had to 
`mount -o remount,rw/` otherwise I could only read not write. 

Please help? thank you!

**Comment by btcviking** [comment]
Here btw is the output of the two initial commands you wanted me to check up on @kyrofa also in pictures unfortunately :P 

![image](https://user-images.githubusercontent.com/69312355/126164614-87cd249a-486d-4c06-ac58-258ce7805280.jpeg)

And
![image](https://user-images.githubusercontent.com/69312355/126164641-9c0331fc-e35e-4c94-92d0-e97f5fe26843.jpeg)

**Comment by btcviking** [comment]
Seems like I have a degraded array for some reason. Anyone know how to investigate what's wrong there? I would just know `cat /proc/mdstat`for now.

Would be really strange that it stops working from one to the other second. I tried to # out my current settings in fstab and was able to boot the pi normally again. Then I replace 'dev/md0p1' with its uuid that I got from blkid but that only resulted in the same and the pi isn't booting anymore, basically like before. Now I'll #-out again and will have to investigate more. Any help is appreciated.

**Comment by btcviking** [comment]
So now via ssh. 
My hard drives are alright. This is the info I am getting:
![image](https://user-images.githubusercontent.com/69312355/126190503-95f26294-2646-4810-8d5a-987bf6969fd2.jpeg)

It seems like somehow it is not mounted, but I am just not sure what this is
![image](https://user-images.githubusercontent.com/69312355/126190576-ade0081e-ac47-4edc-b331-94c1ad3f4e12.jpeg)

Here is the info directly by mdadm:
![image](https://user-images.githubusercontent.com/69312355/126190629-28e6575a-61b6-4350-9906-0036ec67e395.jpeg)


Should I just remount? I never unmounted it though ...

**Comment by btcviking** [comment]
Thanks @everyone who was helping. I got it back working. For some reason the raspi pi didn't boot up anymore since the ssd/raid couldn't be mounted during boot up. 

I had to manually take out the sad card and put it in another linux instance where I then edited the cmdline.txt adding `init=/bin/sh` to the end but in the same line. This link was helpful: http://www.htgsd.com/information-technology/fix-rpi-with-cannot-open-access-to-console-the-root-account-is-locked/

Putting the sd card back into the pi with attached keyboard and display I was able to use the shell and type or make changes again after using this command `mount -o remount, rw / ` be careful there needs to be a space after the comma. 

The I just went to the fstab and commented everything out that I added once (Raid). Put the sd card back into the linux instance and reverted any change I made to cmdline.txt (you can also use vim without putting the card back into the linux instance). 

Now it booted again without problems. I used the command `mountpoint /path/to/raid` to check if the drive is mounted as I was also able to see the raid was "auto-readonly" with `cat /proc/mdstat/`. I had to simply remount the drive to my nextcloud path and all worked again. Additionally I used cronjob to make sure it mounts the drive at boot just in case it happens again. `sudo crontab -e` and then add: `@reboot sleep 5; sudo mount /dev/md0 /media/raid`
