### ISSUE TITLE
Working Caddy v2 reverse proxy settings?

### ISSUE THREAD

**Issue by btcviking** [nextcloud/nextcloud-snap#1798]
Hello, I have been playing around with caddy v2 as a reverse proxy. To me it is a pretty good deal with automatic ssl certificates and the software itself being written in golang which offers good speed and reliability. 

I know a lot of people love NGinx or HAProxy for different reasons, but I wanted to look and use caddy for once it is setup it is actually working good for plenty services I use it for. 

However, I seem to not be able at all to get it work with nextcloud snap! It all seems so simple but for some reasons it will not click for me. Because I have been getting very good support opening an issue here I wanted to see if someone actually got it to work and if we can make that an addition/pull request for the nextcloud wiki section with reverse proxies?! 

I have so far installed caddy vs via apt package manager and it is no problem to get it to work after of course telling nextcloud snap to not use ports 80 and 443. 
But I have never managed to reach nextcloud snap through caddy and it's caddyfile so far! Any help or experience is appreciated. Thank you

**Comment by kyrofa** [comment]
I'm afraid I have no experience with caddy, but would be happy to get it into the wiki if someone has done it.

**Comment by btcviking** [comment]
I was hoping just any user of the nextcloud snap might have been going this route and able to help with it as I wasn't able to get it to work. There is always someone better out there :)

**Comment by uPvtkBlpiucvDUf** [comment]
I'm using this with the nexcloud snap

```
https://example.com {
    reverse_proxy localhost:8080
    header / Strict-Transport-Security max-age=31536000;
}
```

**Comment by btcviking** [comment]
And you have no further issues with for example using mobile apps? Seem like the very basic config most things would be using with Caddy but for some reason this doesn't work for me. I will look at it again today!

**Comment by btcviking** [comment]
> I'm using this with the nexcloud snap
> 
> 
> 
> ```
> 
> https://example.com {
> 
>     reverse_proxy localhost:8080
> 
>     header / Strict-Transport-Security max-age=31536000;
> 
> }
> 
> ```

This actually works flawless. For some reason I believe `encode gzip` amongst other things were necessary but that broke everything for me. Thank you for the input, I am now running multiple services on the pi behind caddy as reverse proxy. Such an easy setup.
