### ISSUE TITLE
Snap 11.0.1 files antivirus not running

### ISSUE THREAD

**Issue by horstvogel** [nextcloud/nextcloud-snap#191]
Hello,
it is possible to run snap an the files_antivirus App?
clamav-daemon is installed and running. 

Here the error Ubuntu 16.04 Server
![2017-01-22 09_26_04-administrator - nextcloud - internet explorer](https://cloud.githubusercontent.com/assets/25108737/22184829/2f42a16c-e0da-11e6-8be5-dec996579320.png)

thanks Horst

**Comment by kyrofa** [comment]
@horstvogel I'm afraid not (at least not right now)-- the snap doesn't have permission to access `/var/run/clamav`. The only way this would work is if clamav's socket was in a writable area for the snap (e.g. `/var/snap/nextcloud/current/`). Please see #172 for how we plan on better solving this issue.

**Comment by horstvogel** [comment]
Ok, thanks.
