### ISSUE TITLE
Allow option to connect to spreed.me snap

### ISSUE THREAD

**Issue by mcphail** [nextcloud/nextcloud-snap#192]
I don't think the current apache config is set up to connect to the spreed snap. Just now, the only way I can see to do this is to hand-roll a nextcloud snap with the modules and config enabled.

I don't think this should be enabled by default, but there should be a way to enable it. I don't think there is a way for users to configure snap options at present.

My knowledge of apache configs is sparse, but I think the `<If ...>` directive can be used to query the presence of a file. I propose we add a stanza which queries the presence of a file under the `$SNAP_COMMON` tree and enables the appropriate modules/config. The user could `touch` that file to enable (or, ideally, run a wrapper script to add/remove that file and restart apache).

Thoughts? I'm happy to hack together a patch.

**Comment by mcphail** [comment]
It looks as if `<If ...>` isn't suitable for this, as only a subset of directives can be included in these stanzas. c23f5f06bfa4 might be a better way, using `<IfDefine ...>` blocks and adding the file check to the wrapper script.

**Comment by oparoz** [comment]
Integration with the spreed-snap has been denied as it's dead code until someone installs the snap:
https://github.com/nextcloud/nextcloud-snap/pull/72

One option is to create a fork which includes integration, but that would need to be kept in sync. Bear in mind though that Spreed technology is being integrated directly inside Nextcloud.

**Comment by oparoz** [comment]
Re-opening since the idea is to use a text file to trigger the code, so less of a risk. Would be a first step while we wait for hooks.

**Comment by mcphail** [comment]
I think this can be closed, as it looks as if there is now a sensible mechanism to configure snaps.
