### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by jlicher** [nextcloud/nextcloud-snap#193]
Since the upgrade to 11.0.1 some official Apps like "Two Factor TOTP Provider" don't work anymore. They come with the message `App "Two Factor TOTP Provider" cannot be installed because the following dependencies are not fulfilled: PHP with a version lower than 7.0 is required.` According to the developer, this problem was fixed in December, So why is it broken in the snap?

**Comment by kyrofa** [comment]
v11.0.1snap1 uses PHP v7.1. Are you saying two factor auth should work with PHP v7.1? The app isn't touched in the snap, it's whatever is contained in the Nextcloud release tarball.

**Comment by jlicher** [comment]
Two factor should work with php 7.1. But the upgrade deactivates the App and i get the message above when I try to activate ist. I got a solution by my own: I have to unistall the app and install it again. Now i works, But where does this problem come from? There seems to be a working version in the apsstore, but there is no message or possibility to update the app.

**Comment by kyrofa** [comment]
Note that we can easily roll back to PHP v7.0.X, but according to the error message, that shouldn't have worked either!

**Comment by kyrofa** [comment]
Huh... no clue about that. Sounds like something internal to the app.

**Comment by jlicher** [comment]
ok, i will try to open a discussion at the "Two Factor TOTP Provider" section.

**Comment by kyrofa** [comment]
Alright I'll leave this open for now, would appreciate any updates you have!

**Comment by oparoz** [comment]
Just a heads up. Nextcloud is not yet a 100% compatible with PHP 7.1. There are fixed coming in the next release.

**Comment by kyrofa** [comment]
@oparoz would you recommend we use 7.0.15, then?

**Comment by oparoz** [comment]
Yes. Mostly because the majority of app devs have probably not tested their apps on 7.1, so there may be more surprises.

**Comment by kyrofa** [comment]
@oparoz fair enough, thank you.

**Comment by kyrofa** [comment]
Note that the latest release is using PHP v7.0.15. I'm going to go ahead and close this.
