### ISSUE TITLE
No option to choose data location

### ISSUE THREAD

**Issue by adamlove86** [nextcloud/nextcloud-snap#200]
Hi there, have done a fresh install and it appears there's no option to choose the data directory. Drive is mounted via /media and have connected to snap via sudo snap connect nextcloud:removable-media core:removable-media

Running fresh install 16.04 with latest version of snap nextcloud. Thanks for your help :)

![screen shot 2017-01-27 at 13 38 43](https://cloud.githubusercontent.com/assets/20361489/22358770/f4b6b46a-e495-11e6-84cc-d39fca7ddc0f.png)

**Comment by kyrofa** [comment]
It's not shown when creating an account because the snap has a default place to put the data. Please see #150 for how to use an alternate location.
