### ISSUE TITLE
Programmatic install with `maintenance:install` fails

### ISSUE THREAD

**Issue by jamescooke** [nextcloud/nextcloud-snap#208]
My goal is to install Nextcloud on an Ubuntu instance inside CircleCI to run integration testing against - this snap seems the easiest route to achieving that, so thanks for everyone's effort on the package. I'm using the latest 'ubuntu/xenial64' Vagrant box and running `sudo snap install nextcloud`.

When the provisioning script runs:

```sh
sudo nextcloud.occ maintenance:install --admin-user=admin --admin-pass=admin
```

... the following error is received:

```
Can't create or write into the data directory /snap/nextcloud/862/htdocs/data
```

This looks like the install is attempting to write directly to the snap in `/snap/nextcloud` which is a read-only filesystem (please excuse me if this is wrong, I'm pretty new to snaps). Instead I guess that it should be writing to `/var/snap/nextcloud/` instead - is that right? Is there a work-around for this at the moment or have I done something completely wrong?

Debugging:

```sh
$ sudo nextcloud.occ status
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Nextcloud is not installed - only a limited number of commands are available
  - installed: false
  - version: 11.0.1.2
  - versionstring: 11.0.1
  - edition: 
```

**Comment by kyrofa** [comment]
@jamescooke how quickly after installing the snap do you run `maintenance:install`? It takes a second to generate a mysql database and point things at /var/snap/nextcloud.

**Comment by jamescooke** [comment]
Hi @kyrofa - thanks for the quick reply. Originally, this ran immediately. I've adjusted the provisioning script to stop after `sudo snap install nextcloud`, left it for a few minutes and tried again with the same result.

I've opened a port to the test VM and can see that the "Create an admin account" page is available. Even though this page is available, the `maintenance:install` command still fails.

If I then go back to the web and provide admin credentials then everything comes alive as expected.

**Comment by kyrofa** [comment]
@jamescooke interesting. I'll admit I've not used `occ maintenance:install`, any chance it ignores autoconfig.php?

**Comment by jamescooke** [comment]
@kyrofa I'm sorry - my experience with this command is very limited. All I can say is that it has worked fine in the past with Owncloud. If it's any help, this is the previous provisioning script that worked for Owncloud's latest release on `download.owncloud.org` apt repository:

```sh
apt-get install -y owncloud
sudo -u www-data php /var/www/owncloud/occ maintenance:install --admin-user=admin --admin-pass=admin
apache2ctl restart
```

There was no waiting required after doing the `apt-get install` before running the install, but I did need to add a `curl --retry 5` pointed at one of the OCS endpoints to ensure that testing did not start until the server was up.

If you can propose a test that I can run to see if `occ maintenance:install` is ignoring `autoconfig.php` I will happily run it and post the result here.

**Comment by kyrofa** [comment]
I'm looking at the code for it now (`core/Command/Maintenance/Install.php`), and yeah, judging from the options it supports it doesn't use autoconfig.php. That's too bad, that's how the snap pre-seeds the database info and data directory.

In your example, where you install the owncloud deb, how is the database created and auth information handed to the owncloud config?

**Comment by kyrofa** [comment]
(worst case, we can ship our own cli installer command that wraps `occ maintenance:install` with the correct values).

**Comment by jamescooke** [comment]
I was just looking at `Install.php` too and spotted the `data-dir` option, but hacking it does not appear to work:

```sh
$ sudo nextcloud.occ maintenance:install --admin-user=admin --admin-pass=admin --data-dir=/var/snap/nextcloud/common/nextcloud/data
...
Nextcloud is not installed - only a limited number of commands are available
Bad system call
```

Is `/var/snap/nextcloud/common/nextcloud/data` a reasonable guess for `--data-dir`?

It did complete some work, but did not finish, just showed `Bad system call`. The `data` directory previously did not exist so it has created these files, plus I think that `cron` ran and created the rest:

```sh
$ sudo ls /var/snap/nextcloud/common/nextcloud/data -lrt
total 4
-rw-r--r-- 1 root root   0 Feb 15 17:44 owncloud.db-journal
-rw-r--r-- 1 root root   0 Feb 15 17:46 index.html
-rw-r--r-- 1 root root   0 Feb 15 17:46 owncloud.db
-rw-r----- 1 root root 191 Feb 15 17:46 nextcloud.log
$ sudo cat /var/snap/nextcloud/common/nextcloud/data/nextcloud.log
{"reqId":"qpKecDhwuObf2bTiMJGP","remoteAddr":"","app":"cron","message":"Not installed","level":4,"time":"2017-02-15T17:46:57+00:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}
```

In the Owncloud example, there was no further configuration to create the database or pass auth information - I guess that was all provided by `dpgk` when installing the package.

**Comment by kyrofa** [comment]
Yeah you'll still be missing the database info as well. Let me investigate this a little (although it'll probably be tomorrow).

**Comment by kyrofa** [comment]
I'm still very curious how the following is possible:

```
apt-get install -y owncloud
sudo -u www-data php /var/www/owncloud/occ maintenance:install --admin-user=admin --admin-pass=admin
apache2ctl restart
```

The reason I'm confused is that it seems `occ maintenance:install` _requires_ the database information to be passed via CLI. The fact that you don't need to means there must be someway to pre-seed this, but I don't know how.

**Comment by kyrofa** [comment]
Ah ha, I lied! If you don't pass database info, it uses sqlite instead.

**Comment by kyrofa** [comment]
@jamescooke I think the only way to do this is to create a new app in the snap called, say, `nextcloud.manual-install` that accepts a username and password. My question for you is: is that preferable to your current `curl` method?

**Comment by jamescooke** [comment]
@kyrofa Following up on your comments and questions:

Your quoted install command is flaky :disappointed: ... If I run `snap install` and `maintenance:install` back to back, then it does not work for me on a vanilla 16.04 Ubuntu instance, this is what happens:

```sh
$ sudo snap install nextcloud
nextcloud 11.0.1snap3 from 'nextcloud' installed
$ sudo nextcloud.occ maintenance:install --admin-user=admin --admin-pass=admin --data-dir=/var/snap/nextcloud/common/nextcloud/data
Cannot write into "config" directory!
This can usually be fixed by giving the webserver write access to the config directory
```

However, as you mentioned before a waiting time is required for this command to work, so that seems like a solution for me at this stage. :+1: 

IMO all command options are preferable to pointing `curl` at the configuration page - they are much easier to wire into deployment systems like Ansible and easier to debug when things go wrong.

Thanks for your help on this.

**Comment by kyrofa** [comment]
> IMO all command options are preferable to pointing curl at the configuration page - they are much easier to wire into deployment systems like Ansible and easier to debug when things go wrong.

+1 to that. I'll get this in the next release. And I'll make it blocking-- if the server isn't fired up yet, it'll say so and wait.

**Comment by jamescooke** [comment]
If this could be automatically blocking that would be a great feature - I'm currently prefixing my calls to your suggested `sudo nextcloud.occ maintenance:install` with a `curl` check that the port is open.

**Comment by kyrofa** [comment]
Sure thing. I'll have a candidate release out soon if you don't mind testing it for your use-case.

**Comment by jamescooke** [comment]
Happy to :+1:

**Comment by kyrofa** [comment]
Alright, does [this script](https://github.com/nextcloud/nextcloud-snap/pull/218/files#diff-215d406751a1d590f5611fa9c23a3619) seem to do what you want?

**Comment by kyrofa** [comment]
I've gone ahead and merged it so that you can test it. You can do that with `sudo snap install --candidate nextcloud`.

**Comment by jamescooke** [comment]
Thanks @kyrofa - hopefully will be able to test tomorrow and confirm working.

**Comment by kyrofa** [comment]
Thanks @jamescooke. Let me know and I'll cut the release.

**Comment by jamescooke** [comment]
Thanks @kyrofa - that works well! :+1:

**Comment by kyrofa** [comment]
Thanks for testing, @jamescooke! I'll get started on the release.
