### ISSUE TITLE
Unable to mount the snap

### ISSUE THREAD

**Issue by tfgordon** [nextcloud/nextcloud-snap#212]
I am trying to install NextCloud on a hosted virtual machine running Ubuntu 16.04.2 LTS, but am getting a mounting error:

$ sudo snap install nextcloud
error: cannot perform the following tasks:
- Mount snap "core" (1337) ([start snap-core-1337.mount] failed with exit status 1: Job for snap-core-1337.mount failed. See "systemctl status snap-core-1337.mount" and "journalctl -xe" for details.
)

$ sudo systemctl status snap-core-1337.mount
snap-core-1337.mount - Mount unit for core
   Loaded: loaded (/etc/systemd/system/snap-core-1337.mount; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mi 2017-03-01 12:02:57 CET; 1min 0s ago
    Where: /snap/core/1337
     What: /var/lib/snapd/snaps/core_1337.snap
  Process: 32662 ExecMount=/bin/mount /var/lib/snapd/snaps/core_1337.snap /snap/core/1337 -t squashfs (code=exited, status=32)

Any idea what the cause of the problem could be?

**Comment by kyrofa** [comment]
What does "a hosted virtual machine" mean? Hosted where? Are you sure this is real Ubuntu, kernel and everything?

**Comment by tfgordon** [comment]
The file /var/log/syslog file doesn't provide any further informtion about the failure, other than "unknown error":

Mar  5 15:40:08 h2667230 /usr/lib/snapd/snapd[1892]: taskrunner.go:353: DEBUG: Running task 203 on Do: Mount snap "core" (1337)
Mar  5 15:40:09 h2667230 mount[5137]: mount: /snap/core/1337: mount failed: Unknown error -1
Mar  5 15:40:09 h2667230 /usr/lib/snapd/snapd[1892]: task.go:303: DEBUG: 2017-03-05T15:40:09+01:00 ERROR [start snap-core-1337.mount] failed with exit status 1: Job for snap-core-1337.mount failed. See "systemctl status snap-core-1337.mount" and "journalctl -xe" for details.

The hosted server claims to be running Ubuntu 16.04.2 LTS:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

The kernel version is given as:

$ uname -a
Linux h2667230.stratoserver.net 4.4.0-042stab120.16 #1 SMP Tue Dec 13 20:58:28 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

Does "stratoserver" here suggest the kernal has been modified?   (I will ask the ISP, strato.de, and let you know if I am able to find out.)

**Comment by tfgordon** [comment]
The ISP sent me an email telling me that snaps can be installed, but may not modify the Linux kernel. However, not only can I not install the Nextcloud snap, not even the demo hello-world snap can be installed.  I get the same mounting error.  So this does not seem to be a problem specific to the Nextcloud snap.  I will contact the ISP again and ask for further help and get back to you.

**Comment by kyrofa** [comment]
> The ISP sent me an email telling me that snaps can be installed, but may not modify the Linux kernel. 

That's not quite what I meant-- I'm suggesting that the kernel they're using is not an official Ubuntu kernel: specifically, I'm suggesting that it doesn't include support for squashfs. To prove this, try the following:

```
$ sudo apt install squashfs-tools
$ cd /tmp
$ mkdir foo
$ mkdir baz
$ touch foo/bar
$ mksquashfs foo foo.squash
$ sudo mount foo.squash baz
$ ls baz/
```

Do you get any errors there?

**Comment by tfgordon** [comment]
Yes, I understand that you want to know whether the kernel has been modified.  I have asked my ISP again.   I tried your test to see if squashfs is supported.  Everything worked except mounting:

$ sudo mount foo.squash baz
mount: baz: mount failed: Unknown error -1

I will also report this to the ISP.

**Comment by kyrofa** [comment]
Well at least you don't get "unknown filesystem type" or similar errors. So perhaps squashfs support is built in. But yeah, something else is missing there-- you need to be able to mount in order to install snaps.

**Comment by tfgordon** [comment]
I just spoke with the technical support at the ISP, strato.de, and was told that if something doesn't work as expected then this is due to a limitation of Virtuozzo, the virtualization software they use.  I had previously been told that snaps were supported, so in my view these two pieces of advice are inconsistent. It was recommended that I upgrade to a dedicated server.  But I decided instead to cancel my contract, within the 30 day grace period, to give me time to consider alternatives.

**Comment by kyrofa** [comment]
>  But I decided instead to cancel my contract, within the 30 day grace period, to give me time to consider alternatives.

Good call, and good investigation! I'm going to go ahead and close this, then.

**Comment by mayeaux** [comment]
@kyrofa I get a `mount: unknown filesystem type 'squashfs'` error, with OVH, am I screwed or what?

**Comment by kyrofa** [comment]
Yes, OVH does by default use a non-standard kernel. However, I've read a few articles that suggest it's possible to install the standard kernel on there. I suggest reaching out to OVH support to help.

**Comment by mayeaux** [comment]
Thanks, I've reached out to them so I'll bring that up when they get back. I'm not a Linux wizard, why won't squashfs work on non-standard kernels? Thanks again

**Comment by mayeaux** [comment]
Yeah, there's nothing mentioned in their advertising whatsoever that it's a nonstandard kernel and that that may have implications for trying to run basic software, unfortunately I've got quite a bit of infra set up on their systems already but we'll see what happens when I chat with their support, I definitely agree it should be mentioned clearly in their advertising (or at least while provisioning the OS)

**Comment by XCage15** [comment]
I own some ovh svr.
here is the some snip of the kernel config.

`# CONFIG_HUGETLB_PAGE is not set
CONFIG_CONFIGFS_FS=m
CONFIG_MISC_FILESYSTEMS=y
# CONFIG_ORANGEFS_FS is not set
# CONFIG_ADFS_FS is not set
# CONFIG_AFFS_FS is not set
# CONFIG_ECRYPT_FS is not set
# CONFIG_HFS_FS is not set
# CONFIG_HFSPLUS_FS is not set
# CONFIG_BEFS_FS is not set
# CONFIG_BFS_FS is not set
# CONFIG_EFS_FS is not set
# CONFIG_JFFS2_FS is not set
# CONFIG_LOGFS is not set
# CONFIG_CRAMFS is not set
# CONFIG_SQUASHFS is not set
# CONFIG_VXFS_FS is not set
# CONFIG_MINIX_FS is not set
# CONFIG_OMFS_FS is not set
# CONFIG_HPFS_FS is not set
# CONFIG_QNX4FS_FS is not set
# CONFIG_QNX6FS_FS is not set
# CONFIG_ROMFS_FS is not set
# CONFIG_PSTORE is not set
# CONFIG_SYSV_FS is not set
# CONFIG_UFS_FS is not set
CONFIG_NETWORK_FILESYSTEMS=y
CONFIG_NFS_FS=y
CONFIG_NFS_V2=y
CONFIG_NFS_V3=y
CONFIG_NFS_V3_ACL=y
CONFIG_NFS_V4=y
CONFIG_NFS_SWAP=y
CONFIG_NFS_V4_1=y
# CONFIG_NFS_V4_2 is not set
CONFIG_PNFS_FILE_LAYOUT=y
CONFIG_PNFS_BLOCK=m
CONFIG_PNFS_FLEXFILE_LAYOUT=m
CONFIG_NFS_V4_1_IMPLEMENTATION_ID_DOMAIN="kernel.org"
CONFIG_NFS_V4_1_MIGRATION=y
CONFIG_ROOT_NFS=y
# CONFIG_NFS_USE_LEGACY_DNS is not set
CONFIG_NFS_USE_KERNEL_DNS=y
CONFIG_NFSD=y
CONFIG_NFSD_V2_ACL=y
CONFIG_NFSD_V3=y
CONFIG_NFSD_V3_ACL=y
CONFIG_NFSD_V4=y
CONFIG_NFSD_PNFS=y
CONFIG_NFSD_BLOCKLAYOUT=y
CONFIG_NFSD_SCSILAYOUT=y
CONFIG_NFSD_FLEXFILELAYOUT=y`

**Comment by XCage15** [comment]
I found someway to make squash kernel module.

```
# uname -r
4.9.124-armada375
```
and I download the kernel source code from kernel.org
```
# aria2c 'https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.124.tar.xz'
[#397423 88MiB/89MiB(99%) CN:1 DL:6.7MiB]
12/28 18:44:42 [NOTICE] Download complete: /root/linux-4.9.124.tar.xz

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
397423|OK  |   6.7MiB/s|/root/linux-4.9.124.tar.xz

Status Legend:
(OK):download completed.
```
although the source code location may change.

extract the source code archive and go to the extracted folder.
```
root@host# make oldconfig
scripts/kconfig/conf  --oldconfig Kconfig
#
# using defaults found in /boot/config-4.9.124-armada375
#
#
# configuration written to .config
#
```
and install the `libncurses5-dev` in ubuntu to config by ncurses ui.

and 
```
# make menuconfig
```
and go to `File Systems`, and `Miscellaneous filesystems` and  mark `<M>` on `SquashFS 4.0 - Squashed file system support` and Save and exit.

after that, make the squashfs kernel module by 
```
# make M=fs/squashfs
```
The output should be as followed.
```

  WARNING: Symbol version dump ./Module.symvers
           is missing; modules will have no dependencies and modversions.

  LD      fs/squashfs/built-in.o
  CC [M]  fs/squashfs/block.o
  CC [M]  fs/squashfs/dir.o
  CC [M]  fs/squashfs/cache.o
  CC [M]  fs/squashfs/export.o
  CC [M]  fs/squashfs/file.o
  CC [M]  fs/squashfs/fragment.o
  CC [M]  fs/squashfs/id.o
  CC [M]  fs/squashfs/inode.o
  CC [M]  fs/squashfs/namei.o
  CC [M]  fs/squashfs/super.o
  CC [M]  fs/squashfs/symlink.o
  CC [M]  fs/squashfs/decompressor.o
  CC [M]  fs/squashfs/file_cache.o
  CC [M]  fs/squashfs/decompressor_single.o
  CC [M]  fs/squashfs/xattr.o
  CC [M]  fs/squashfs/xattr_id.o
  CC [M]  fs/squashfs/lz4_wrapper.o
  CC [M]  fs/squashfs/lzo_wrapper.o
  CC [M]  fs/squashfs/xz_wrapper.o
  CC [M]  fs/squashfs/zlib_wrapper.o
  LD [M]  fs/squashfs/squashfs.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      fs/squashfs/squashfs.mod.o
  LD [M]  fs/squashfs/squashfs.ko
#
```
And type `  insmod fs/squashfs/squashfs.ko ` to insert the module.
verify by `lsmod`
```
# lsmod
Module                  Size  Used by
squashfs               27261  0
```
