### ISSUE TITLE
integration with Collabora Office Online

### ISSUE THREAD

**Issue by rmescandon** [nextcloud/nextcloud-snap#216]
It is needed to share documents folder in order to Collabora Office Online snap [1] integrate with Nextcloud. This way any doc can be rendered by Office Online. Currently that Office Online snap is in process to be handed over to upstream guys. 

[1] https://github.com/rmescandon/loolwsd-snap

**Comment by kyrofa** [comment]
The directory in which the snap stores Nextcloud's data is configurable by the user. Have you considered what happens if the user changes that location?

**Comment by rmescandon** [comment]
Obviously right now wont't work if the path changes. 
How about having a soft link to the docs folder instead. I wonder if setting that link when snap becomes enabled could be enough. It should be also written in nextcloud config file section where the path is set, a  comment explaining that changing that path needs snap to be disabled/enabled to expose data properly to other snaps.

**Comment by oparoz** [comment]
I'd recommend you take another path for this.
1. Connect the interface giving you access to /media
1. Mount a documents folder in /media
1. Point CODE to that folder

**Comment by kyrofa** [comment]
I tend to agree with @oparoz here. AppArmor normalizes file paths, so symlinks won't help us here.

**Comment by rmescandon** [comment]
So, correct me if I'm wrong. You mean:
- plug interface "removable_media" to some nextcloud daemon (apache one?)
- bind mount "$SNAP_COMMON/nextcloud/data/admin/files" in /media/<user>/<whatever>
- plug interface "removable_media" to CODE daemon
- point CODE to /media/<user>/<whatever>
is that right?

**Comment by corwin78** [comment]
Hello guys, any tips how to integrate Collabora with snapped NextCloud? Is Collabora installation via Docker, how is recommended in many guides, good way for this case? Thx.

**Comment by kyrofa** [comment]
@corwin78 I'm afraid I know next to nothing about Collabora. But if all it needs is access to the Nextcloud documents, you can probably mount them into the docker container. Is that all it needs?

**Comment by corwin78** [comment]
@kyrofa Main issue is, that I don't know how to interconnect Apache from Snap with system Apache, to allow access to Collabora office on the same IP like NextCloud, but via different URL.

**Comment by skollrc** [comment]
Hi everyone,I would like to know how to integrate collabora online in a snap or if it already exist? (not another snap like this project but an all in one snap )

**Comment by Pardaigle** [comment]
Same problem as @corwin78 , I can't figure out how configure Apache to let Collabora work witn Nextcloud.

**Comment by digulla** [comment]
The problem with CODE and Nextcloud SNAP is that both need port 80 in the same computer.

The fix would be to integrate the necessary ProxyPass and ProxyReverse options mentioned at https://nextcloud.com/collaboraonline/ to  `/snap/nextcloud/current/conf/httpd.conf` and/or `/snap/nextcloud/current/conf/ssl.conf` (when HTTPS is enabled).

I tried to edit those files but they are on a read only filesystem. How can I edit this file and restart the apache running inside the snap?

**Comment by skollrc** [comment]
+1 any news? I realy want to have lool working in my nextcloud snap but can't do it yet. Is there any project to have a snap with nextcloud ans lool in the same Snap ?

**Comment by Urs-O** [comment]
Are there any News in thus Problem? I think i ran into the same issue...

**Comment by kyrofa** [comment]
This should be resolved by the fact that collabora (and onlyoffice) are both now integrated into Nextcloud itself as apps. Both of them work in the snap, in my experience.
