### ISSUE TITLE
Documentation request: cloudflare tunnel

### ISSUE THREAD

**Issue by ph00lt0** [nextcloud/nextcloud-snap#2187]
I am trying to put nextcloud-snap behind a cloudflare tunnel much like:
https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#cloudflare-argo-tunnel

I am however getting stuck with what settings I exactly need to get this to run. 
It seems I would need to disable https and use overwrite host, however the exact settings aren't really clear to me and I am struggling to find the right configuration. Should you have any suggestions I would very much appreciate this.

**Comment by kyrofa** [comment]
Those docs are docker-specific. Sounds like that container does something special to validate domains. The snap doesn't do anything special, so I would first try completely ignoring the `SKIP_DOMAIN_VALIDATION=true`. It's entirely possible something in the Nextcloud codebase needs to be disabled, but that would require a deeper dive into that container.

**Comment by kyrofa** [comment]
You may need to delve into that container then and see what it does if that variable is set to true.

**Comment by kyrofa** [comment]
Ah, excellent, thanks for the update.
