### ISSUE TITLE
Enabling HTTPS (SSL, TLS) Documentation outdated

### ISSUE THREAD

**Issue by shadowempire123** [nextcloud/nextcloud-snap#222]
nextcloud box 11.0.1 (stable)
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-1017-raspi2 armv7l)
raspi firmware: rpi-4.9.y

The command `sudo nextcloud.enable-https -d` as shown here:
https://github.com/nextcloud/nextcloud-snap/wiki/Enabling-HTTPS-(SSL,-TLS)
https://github.com/nextcloud/nextcloud-snap/wiki/Connecting-the-Nextcloud-Box-to-the-Internet
is not working anymore.

see also here:
https://help.nextcloud.com/t/error-enabling-ssl-nextcloud-box/9491

**Comment by oparoz** [comment]
Fixed. Thanks for noticing.
