### ISSUE TITLE
Upgrade from 11.0.1snap3 -> 11.0.2snap1: mysql client no longer working

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#228]
On v11.0.1snap3:

```
$ sudo nextcloud.mysql-client 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.11 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

After the upgrade to v11.0.2snap1:

```
$ sudo nextcloud.mysql-client 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/snap/nextcloud/current/mysql/mysql.sock' (2)
```

**Comment by kyrofa** [comment]
This is because the upgrade didn't change the socket location in `/var/snap/nextcloud/current/mysql/root.ini` to `/tmp/sockets/mysql.sock`.

**Comment by ernesst** [comment]
Thanks for the help,
Does the folder /tmp/sockets should be created automatically ?

**Comment by kyrofa** [comment]
The snap will create it, the .ini just needs the path to it.

**Comment by kyrofa** [comment]
If you're nervous making this change and are willing to wait, the snap will automatically update and fix this for you.

**Comment by ernesst** [comment]
No i'm not, just after the ini correction and restarting the nextcloud snap i couldn't find it in /tmp/sockets/
I found it in : /tmp/snap.0_snap.nextcloud.mysql_KE76hL/tmp/sockets/
Does the  /tmp/snap.0_snap.nextcloud.mysql_KE76hL/ folder created randomly ? I'm currently monitoring the mysql server with nagios, which requires a fixe location for the .socks

**Comment by kyrofa** [comment]
Ah, you may run into issues there. The /tmp within the snap is a private one created by snap-confine, which means it'll be a random subdirectory of the host's /tmp, as you see there.

**Comment by ernesst** [comment]
Ok thanks for the info, i'll temporary stop the monitoring and think to a solution.
