### ISSUE TITLE
Documentation missing for "Preview Generator" on nextcloud box wiki

### ISSUE THREAD

**Issue by shadowempire123** [nextcloud/nextcloud-snap#232]
hi,
as automated/improved thumbnail generation is an important topic, I would recommend a detailed howto set it up for a nextcloud box.
it looks like it is not really clear how to configure it...
see here:
https://help.nextcloud.com/t/clarity-on-the-crontab-settings-for-the-preview-generator-app/6144/2
https://help.nextcloud.com/t/no-picture-previews-in-nextcloud-11-0-1/8528/3
https://help.nextcloud.com/t/error-while-generating-thumbnails-with-previewgenerator/8295

maybe it is possible to integrate it as a default feature in a future nextcloud box build, without the need of manually editing the crontab.

I am getting this error (Preview Generater was installed via the GUI):
```
root@nextcloud:/snap/nextcloud/current/bin# /snap/nextcloud/1190/bin/occ preview:pre-generate
/snap/nextcloud/1190/bin/occ: 3: .: Can't open /utilities/mysql-utilities
```

mysql-utilities on the nextcloud box is located here:
/snap/nextcloud/1190/utilities/mysql-utilities

**Comment by kyrofa** [comment]
Yikes, not a lot we can do with hard-coded paths, there. Also, is there a way for apps to tie into Nextcloud's broader `cron.php`? Adding new commands to be periodically run within the snap depending on the app installed isn't going to scale very well.

**Comment by oparoz** [comment]
Works fine here:

```
$ sudo nextcloud.occ preview:generate-all
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Scanning folder /admin/files
Scanning folder /admin/files/Documents
Scanning folder /admin/files/Media
```

**Comment by kyrofa** [comment]
Thanks @oparoz. @shadowempire123 looking closer at your error, it seems you're running a binary straight out of the snap, which means you don't get the environment setup the right way. You need to run `nextcloud.occ` as @oparoz did.

**Comment by shadowempire123** [comment]
@kyrofa: indeed this is working. still I get a lot of these error messages.

a short description how to "crontab" it would be nice to have.

**Comment by kyrofa** [comment]
That's not something that can be done from the snap itself. If you actually have cron available you can just add `nextcloud.occ preview:generate-all` to root's crontab.

I'm going to go ahead and close this here, but feel free to follow-up.

**Comment by shadowempire123** [comment]
thx for your feedback.
I still think a short howto should be added for not so advanced user to the nextcloud box wiki.

(- how to modify the crontab)
- how it should look like (screenshot)
- description of scheduling impact
- troubleshooting
