### ISSUE TITLE
Dear github. We know you can host images, why not in the wiki?

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud-snap#235]
so let's put them here in the comments ;-)

**Comment by NinaNC** [comment]
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image2](https://cloud.githubusercontent.com/assets/26001373/24001704/26c6b72c-0a5f-11e7-81d2-a11d5fdf236c.jpg)
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image3](https://cloud.githubusercontent.com/assets/26001373/24001706/26fee7e6-0a5f-11e7-91fa-0002aff896c4.jpg)
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image4](https://cloud.githubusercontent.com/assets/26001373/24001708/2702f836-0a5f-11e7-87d2-fe24f0d90f29.jpg)
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image5](https://cloud.githubusercontent.com/assets/26001373/24001705/26fd1bd2-0a5f-11e7-9149-880de3fbf191.jpg)
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image6](https://cloud.githubusercontent.com/assets/26001373/24001709/2726ac5e-0a5f-11e7-8750-bc6447ca4956.jpg)
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image7](https://cloud.githubusercontent.com/assets/26001373/24001707/26ff9236-0a5f-11e7-8e48-3be264ebc1c7.jpg)

**Comment by NinaNC** [comment]
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image8](https://cloud.githubusercontent.com/assets/26001373/24003555/153f0630-0a64-11e7-879f-5f0d99ba0097.jpg)
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image9](https://cloud.githubusercontent.com/assets/26001373/24003556/15644198-0a64-11e7-9fb7-1779a4c92d59.jpg)
![Uploading ReleaseNotes-UbuntuCore16forNextCloud-MfgImage_page10_image10.jpg…]()
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image11](https://cloud.githubusercontent.com/assets/26001373/24003557/15a7e150-0a64-11e7-8702-2636d06928b5.jpg)

**Comment by NinaNC** [comment]
![releasenotes-ubuntucore16fornextcloud-mfgimage_page10_image10](https://cloud.githubusercontent.com/assets/26001373/24003775/aeac1e48-0a64-11e7-999e-9543c32e7f1d.jpg)

**Comment by NinaNC** [comment]
![coresystem1](https://cloud.githubusercontent.com/assets/26001373/24396308/066b2b46-13a3-11e7-9985-940c7a64af5d.png)
![coresystem2](https://cloud.githubusercontent.com/assets/26001373/24396310/066da128-13a3-11e7-803c-8091207c4458.png)
![coresystem3](https://cloud.githubusercontent.com/assets/26001373/24396311/066e206c-13a3-11e7-85b3-2a562161cfcf.png)
![coresystem4](https://cloud.githubusercontent.com/assets/26001373/24396312/066ec800-13a3-11e7-8a73-57ec4cec3c1d.png)
![coresystem5](https://cloud.githubusercontent.com/assets/26001373/24396307/066ab418-13a3-11e7-80b7-fceb8a42fe6d.png)
![coresystem6](https://cloud.githubusercontent.com/assets/26001373/24396309/066b33f2-13a3-11e7-90d7-1710c4a752be.png)
