### ISSUE TITLE
Uploading files larger than 20 GB fails

### ISSUE THREAD

**Issue by yuriystepanenko** [nextcloud/nextcloud-snap#2411]
when I upload files to the cloud up to 20GB in size, I can also successfully download them to any of my devices through the site or through the windows client.
when I upload files larger than 20GB to the cloud, when I try to download to any computer, I get a file about a byte in size. BUT if you go through the site and see the properties of the file - then select the version - the arrow for downloading the first version - voila, the file download is normal.
All these download errors occur randomly, I can delete it and download it again and everything will be fine.

**Comment by scubamuc** [comment]
I believe this is not a Nextcloud-snap issue.

Maybe you can add input here: https://help.nextcloud.com/t/uploading-files-larger-than-20-gb-fails/161445

**Comment by yuriystepanenko** [comment]
> I believe this is not a Nextcloud-snap issue.
> 
> Maybe you can add input here: https://help.nextcloud.com/t/uploading-files-larger-than-20-gb-fails/161445

it's my ticket too

**Comment by scubamuc** [comment]
> BUT if you go through the site and see the properties of the file - then select the version - the arrow for downloading the first version - voila, the file download is normal.

can you screenshot this?

**Comment by yuriystepanenko** [comment]
> > BUT if you go through the site and see the properties of the file - then select the version - the arrow for downloading the first version - voila, the file download is normal.
> 
> can you screenshot this?

![image](https://user-images.githubusercontent.com/83817590/236480229-d3418dd1-d5cf-452c-a511-e7e2ca709f4e.png)

**Comment by scubamuc** [comment]
please show your logs, see [logging an issue](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts)

**Comment by yuriystepanenko** [comment]
> please show your logs, see [logging an issue](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts)




> > BUT if you go through the site and see the properties of the file - then select the version - the arrow for downloading the first version - voila, the file download is normal.
> 
> can you screenshot this?

https://i.ibb.co/vhNfWnS/nextcloud.jpg

**Comment by yuriystepanenko** [comment]
> please show your logs, see [logging an issue](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts)

[log.zip](https://github.com/nextcloud-snap/nextcloud-snap/files/11407210/log.zip)

**Comment by scubamuc** [comment]
see [logging an issue](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts)

**Comment by scubamuc** [comment]
@yuriystepanenko , if you can't copy and paste the log as a comment, save it as a txt file and attach here...

**Comment by yuriystepanenko** [comment]
#large

> @yuriystepanenko, если у вас не получается скопировать и вставить лог как комментарий, сохраните его как txt файл и прикрепите сюда...
I can do it)
[log.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/11407418/log.txt)

**Comment by scubamuc** [comment]
great thanks
I'm not seeing anything obvious here... there is a recurring exception:

![grafik](https://user-images.githubusercontent.com/54933878/236503476-b23bdf30-f981-464b-9e8b-187238234f9a.png)

but I'm guessing that this is not the root cause of your issue.

can you check these settings in `/var/snap/nextcloud/current/nextcloud/config/config.php`

# Nextcloud.snap -- set upload filesize #

```
php.upload-max-filesize
php.post-max-size
php.max-input-time
php.max-execution-time
```

**Comment by kyrofa** [comment]
This is almost certainly an upstream nextcloud bug. I can't imagine what the snap could do that would break one download button but not the other.

**Comment by yuriystepanenko** [comment]
> @kyrofaСпасибо что подметил это
> 
> @yuriystepanenkoпожалуйста, проигнорируйте этот пост, так как это кажется моим первым предложением, это **не** проблема **Nextcloud-snap** .
> 
> > Это почти наверняка ошибка исходного уровня nextcloud. Я не могу себе представить, что может сделать оснастка, которая сломает одну кнопку загрузки, но не другую.
> 
> попробуйте снова зарегистрировать проблему в восходящем направлении.

Thank you very much for your help, I will wait for your information

**Comment by scubamuc** [comment]
so I've tested this:
1. create file 25GB `fallocate -l 25G File.25GB`
2. upload file to Nextcloud-snap
    ![grafik](https://user-images.githubusercontent.com/54933878/236788760-87ea3ca5-745a-40b7-bf44-88283baf2348.png)
3. download file from Nextcloud-snap
4. compare files in file manager
    ![grafik](https://user-images.githubusercontent.com/54933878/236791743-f5e74987-ff42-4e57-b341-277767c071c0.png)

thus up and download files larger that 20GB is possible and works just fine

> This is almost certainly an upstream nextcloud bug. I can't imagine what the snap could do that would break one download button but not the other.   

possibly a restriction by service-provider

**Comment by yuriystepanenko** [comment]
I can upload 10 files of 40 GB each and 2-3 pieces are not downloaded (I can only download through the version).
I will delete these files and upload again and both upload buttons work correctly.
It all happens randomly.

**Comment by yuriystepanenko** [comment]
> so I've tested this:
> 
> 1. create file 25GB `fallocate -l 25G File.25GB`
> 2. upload file to Nextcloud-snap
>    ![grafik](https://user-images.githubusercontent.com/54933878/236788760-87ea3ca5-745a-40b7-bf44-88283baf2348.png)
> 3. download file from Nextcloud-snap
> 4. compare files in file manager
>    ![grafik](https://user-images.githubusercontent.com/54933878/236791743-f5e74987-ff42-4e57-b341-277767c071c0.png)
> 
> thus up and download files larger that 20GB is possible and works just fine
> 
> > This is almost certainly an upstream nextcloud bug. I can't imagine what the snap could do that would break one download button but not the other.
> 
> possibly a restriction by service-provider

I can upload 10 files of 40 GB each and 2-3 pieces are not downloaded (I can only download through the version).
I will delete these files and upload again and both upload buttons work correctly.
It all happens randomly.

**Comment by yuriystepanenko** [comment]
> what type of file is this? are these Database-files?

5 different types of files - databases, archives, videos...
I'm looking for a solution on the internet and I find a lot of threads about the same zero files error, and nowhere is there a solution in the direction of snap.
All solutions that helped to solve the problem were under the usual installation of the nextcloud package

**Comment by scubamuc** [comment]
there will be no difference between "ususal" installation and Nextcloud-snap. your issue presumably has nothing to do with Nextcloud. I'm going out on a limb here, but are you using browser-client on linux or M$? if on M$ see if there's a antivirus or malware-blocker doing something to the files in between up- and download.

**Comment by yuriystepanenko** [comment]
> there will be no difference between "ususal" installation and Nextcloud-snap. your issue presumably has nothing to do with Nextcloud. I'm going out on a limb here, but are you using browser-client on linux or M$? if on M$ see if there's a antivirus or malware-blocker doing something to the files in between up- and download.

file uploads are done through the browser or through the client.
for the test i asked the fools to log in from their computers and download the file - about 100 people tried to download the file and all got the same error.. file size 0
I also asked to disable anti-virus applications and that didn't help.
This morning my friend uploaded a 41GB file and now the file is not downloading, but as soon as I go to the file properties, then go to the version and click download from here and everything is downloaded ..
To be honest, I’m already hysterical)) I still can’t understand how this happens ..

**Comment by yuriystepanenko** [comment]
I just realized that there are problems only with those files that have versions. files that do not have versions and have no problems ...

**Comment by yuriystepanenko** [comment]
Yes, this was due to the versioning of some files. I just disabled the app and it worked. thanks for the help
