### ISSUE TITLE
Question in regards to snap autoupdate

### ISSUE THREAD

**Issue by SkyWheel** [nextcloud/nextcloud-snap#254]
Hi everybody!
Each Nextcloud version upgrade (not Nextcloud snap upgrade) I receive the same issue: 2FA app [Two Factor Totp](https://github.com/nextcloud/twofactor_totp) has been disabled. Have to re-enable it manually. I reckon this is a security weakness. At the same time the issue has nothing common with Nextcloud-snap.
Here is my question: I would like to control snap upgrade process. Would be enough just to execute next command:
`sudo systemctl disable snapd.refresh.service`
Are there any other ways to disable Nextcloud-snap autoupdate, as I beleive the above found is not the best one.
Thank you!

**Comment by kyrofa** [comment]
> Have to re-enable it manually.

This is a general problem with Nextcloud that is [apparently being resolved in v12](https://twitter.com/Nextclouders/status/857140541343051777).

> I would like to control snap upgrade process.

This is a more general snap question that would perhaps be better suited to the [snapcraft forums](https://forum.snapcraft.io/).

**Comment by SkyWheel** [comment]
@kyrofa , thanks for the links! I'm really excited to learn that v12 will fix the issue.
And via the forums already found some interesting stuff.

**Comment by kyrofa** [comment]
No problem, yeah there's some handy info there.

> I'm really excited to learn that v12 will fix the issue.

Heh, me too-- that's my main issue with it, nowadays.
