### ISSUE TITLE
Documentation: Include kyrofa posts about creating this snap in the Wiki

### ISSUE THREAD

**Issue by pachulo** [nextcloud/nextcloud-snap#257]
I think that some of the posts in the [kyrofa blog](https://kyrofa.com) should be referenced in the wiki, for example in the [Developer-FAQ](/nextcloud/nextcloud-snap/wiki/Developer-FAQ). At least these:
* https://kyrofa.com/posts/building-your-snap-on-device-there-s-a-better-way
* https://kyrofa.com/posts/snapping-nextcloud-the-web-server
* https://kyrofa.com/posts/snapping-nextcloud-mysql
* https://kyrofa.com/posts/snapping-nextcloud-the-memcache
* https://kyrofa.com/posts/snapping-nextcloud-nextcloud-itself
* https://kyrofa.com/posts/ubuntu-core-on-virtualbox

**Comment by kyrofa** [comment]
Thanks @pachulo, I'm glad you found them useful! Haha, I didn't realize we had a Developer FAQ. @oparoz do you think some of these would be helpful, there?

**Comment by oparoz** [comment]
Yes, I think it would be good to either link to them or extract and maintain their content. Up to you.

**Comment by kyrofa** [comment]
I added a FAQ entry for using the snap builders... but I'm not sure the others fit there. @pachulo what questions do any of those other links answer?

**Comment by pachulo** [comment]
These come to my mind:
- **Q: Why are you compiling a custom repository of mysql-server?**
- A: https://kyrofa.com/posts/snapping-nextcloud-mysql
- **Q: Why don't you use the distro packages for MySQL/PHP/Apache?**
- A: https://kyrofa.com/posts/snapping-nextcloud-mysql & https://kyrofa.com/posts/snapping-nextcloud-php-7 & https://kyrofa.com/posts/snapping-nextcloud-the-web-server
- **Q: How can I test Ubuntu Core the easy way?**
- A: https://kyrofa.com/posts/ubuntu-core-on-virtualbox

Maybe the last one doesn't suit here..

**Comment by kyrofa** [comment]
Ah, yeah I'll buy those. Though I agree, that last one doesn't really have anything to do with the snap.

**Comment by kyrofa** [comment]
Thanks @pachulo! Done.
