### ISSUE TITLE
Errors compiling the (slightly modified) snap with launchpad

### ISSUE THREAD

**Issue by pachulo** [nextcloud/nextcloud-snap#260]
When trying to do something about this issue https://github.com/nextcloud/nextcloud-snap/issues/60, [I tried the easy approach](https://github.com/pachulo/nextcloud-snap/commit/c530d7636e02e2b240f0dd9cb517ce86523b8f3a) to see which rocks I find on the road, but when trying to compile it with my rbpi3 I hit the out of RAM problem that @kyrofa commented here:
- https://kyrofa.com/posts/snapping-nextcloud-mysql

And then I found this other @kyrofa post:
- https://kyrofa.com/posts/building-your-snap-on-device-there-s-a-better-way

So I decided to try this new method; created this project:
- https://launchpad.net/nextcloud-snap-pachulo

And tried to build snaps for armhf from it, but I'm only getting errors:

- https://code.launchpad.net/~pachulo/+snap/nextcloud-snap-pachulo/+build/36333/+files/buildlog_snap_ubuntu_xenial_armhf_nextcloud-snap-pachulo_BUILDING.txt.gz
- https://code.launchpad.net/~pachulo/+snap/nextcloud-snap-pachulo/+build/36418/+files/buildlog_snap_ubuntu_xenial_armhf_nextcloud-snap-pachulo_BUILDING.txt.gz
- https://code.launchpad.net/~pachulo/+snap/nextcloud-snap-pachulo/+build/36340/+files/buildlog_snap_ubuntu_xenial_armhf_nextcloud-snap-pachulo_BUILDING.txt.gz
- https://code.launchpad.net/~pachulo/+snap/nextcloud-snap-pachulo/+build/36333/+files/buildlog_snap_ubuntu_xenial_armhf_nextcloud-snap-pachulo_BUILDING.txt.gz

So my guess is that I'm doing something wrong, but I don't know what it is.

**Comment by kyrofa** [comment]
It seems you have added `smbclient` and `php-smbclient` to the list of `stage-packages` for the `php` part. I've not looked myself, but it seems that one or both of those packages depends upon python2, so that gets pulled in as a stage-package as well. Which then conflicts with the certbot stuff which also requires python2. 

It's odd that those files have different contents, though. I suggest trying to build locally (on a faster amd64 machine) so you can see what the differences are. Once you get it working on amd64, THEN you can hand it over to the LP builders to build for all architectures.

**Comment by pachulo** [comment]
After doing what you said, I found out that the differences between the files is this one for all of them:

```
ubuntu@nextcloud-snap-compile:~/snaps/nextcloud-snap$ diff ./parts/certbot-nextcloud-plugin/install/usr/lib/python2.7/UserString.py ./parts/php/install/usr/lib/python2.7/UserString.py
1c1
< #!/usr/bin/env python2.7
---
> #! /usr/bin/python2.7
ubuntu@nextcloud-snap-compile:~/snaps/nextcloud-snap$ diff ./parts/certbot-nextcloud-plugin/install/usr/lib/python2.7/smtplib.py ./parts/php/install/usr/lib/python2.7/smtplib.py
1c1
< #!/usr/bin/env python2.7
---
> #! /usr/bin/python2.7
ubuntu@nextcloud-snap-compile:~/snaps/nextcloud-snap$ diff ./parts/certbot-nextcloud-plugin/install/usr/lib/python2.7/tabnanny.py ./parts/php/install/usr/lib/python2.7/tabnanny.py
1c1
< #!/usr/bin/env python2.7
---
> #! /usr/bin/python2.7
```
Do you have any idea why the files are different?

**Comment by pachulo** [comment]
By the way, this is what I tried now with the snapcraft.yml https://github.com/pachulo/nextcloud-snap/commit/13cd1c5d7302fd12d50d4082739714bba3f529d2

**Comment by pachulo** [comment]
OK, I think that is related to this code in the snapcraft python plugin:
- https://github.com/snapcore/snapcraft/blob/master/snapcraft/plugins/python.py#L351

Could it be?

**Comment by pachulo** [comment]
Created a PR: https://github.com/nextcloud/nextcloud-snap/pull/263
