### ISSUE TITLE
exiftool version does not match: expected 12.70 but found 12.60

### ISSUE THREAD

**Issue by alesrosina** [nextcloud/nextcloud-snap#2620]
#### Describe the bug
When using applications that uses `exiftool` (eg. Memories) since Friday I'm getting an error:

```
exiftool version does not match: expected 12.70 but found 12.60
``` 

#### To Reproduce
n/a

#### Expected behavior
Snap should include latest version of exiftool.

#### Screenshots
n/a

#### OS/snapd/snap version

```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.3snap1  38464  latest/stable  nextcloud✓  -
```
Snap version:
```
snap    2.60.4
snapd   2.60.4
series  16
debian  11
kernel  6.1.21-v8+

```

#### Logs
```
exiftool version does not match: expected 12.70 but found 12.60
``` 

If I understood correctly, this lib is bundled with snap, right?

**Comment by alesrosina** [comment]
Ah, ok I've figure it out.

Problem being with Memories config - there is a hardcoded path for exiftools included in memories. Since app was installed with one version from snap, and upgraded in newer version, path was still pointing to old snap version.

```php
  'memories.exiftool' => '/var/snap/nextcloud/38464/nextcloud/extra-apps/memories/bin-ext/exiftool-aarch64-glibc',
  'memories.vod.path' => '/var/snap/nextcloud/38464/nextcloud/extra-apps/memories/bin-ext/go-vod-aarch64',
```

Simple path change from explicit snap version to `current` did the trick:

```php
  'memories.exiftool' => '/var/snap/nextcloud/current/nextcloud/extra-apps/memories/bin-ext/exiftool-aarch64-glibc',
  'memories.vod.path' => '/var/snap/nextcloud/current/nextcloud/extra-apps/memories/bin-ext/go-vod-aarch64',
```


Leaving this here, if somebody else got stuck with this.

**Comment by scubamuc** [comment]
@pachulo does the snap include `exiftool` ?
