### ISSUE TITLE
Nextcloud Box users - connect to internet

### ISSUE THREAD

**Issue by gbz101** [nextcloud/nextcloud-snap#264]
https://github.com/nextcloud/nextcloud-snap/wiki/Connecting-the-Nextcloud-Box-to-the-Internet
includes the text:

"3. Add your external domain to Nextcloud

List the domains you're currently using

# sudo nextcloud.occ config:system:get trusted_domains

Create a new entry

# sudo nextcloud.occ config:system:set trusted_domains 2 --value=your.domain"

I'm using Nextcloud 11.0.3 (stable) and (at least) the first sudo nextcloud.occ command did not work. I assumed that the second sudo nextcloud.occ command would similarly not work.

I ended up hunting around forums to help me find the file I needed to edit to add to the trusted domains.

I found it at /var/snap/nextcloud/current/nextcloud/config/config.php.

This forum post helped me: https://help.nextcloud.com/t/after-installation-how-to-connect/4375/5.

Is the above text re sudo nextcloud.occ ... inapplicable to Nextcloud 11.0.3 (stable)?

**Comment by kyrofa** [comment]
No, I just did this myself and it worked fine. What errors did you receive?

**Comment by gbz101** [comment]
Thanks for looking at this. Sorry, it turns out that I was inattentive and this issue can be closed.

I've revisited this and the command for getting trusted domains does work after all (on my Nextcloud Box (11.0.3 (stable)). The desired info was provided right at the end of the output. 

I was distracted by a long sequence of error messages. The first was: "ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored." and there was more than a screenful of similar messages. However, I should have paid attention to what was output right at the end.

**Comment by kyrofa** [comment]
Yeah there's something a little odd with how the Box's were setup out of the... well... box that causes those warnings. They're non-fatal, but super annoying. The solution given to me by Canonical was to upgrade to the Ubuntu Core-based image.
