### ISSUE TITLE
Upgrade Redis to 3.2.8

### ISSUE THREAD

**Issue by pachulo** [nextcloud/nextcloud-snap#267]
Because of this:
* https://raw.githubusercontent.com/antirez/redis/3.2/00-RELEASENOTES
* https://www.reddit.com/r/redis/comments/5r8wxn/redis_327_is_out_important_security_fixes_inside/

**Comment by kyrofa** [comment]
Thanks for being on top of that :smiley: . Mind taking a look at #268?
