### ISSUE TITLE
Version in config.php is not updated

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#27]
I've just checked the config.phph file of the latest edge release and it's at 9.0.50.0. It should be at 9.0.53.0 so something seems wrong.

**Comment by kyrofa** [comment]
Run `sudo /snap/bin/nextcloud.occ upgrade`. Does it say it's all up-to-date?

**Comment by oparoz** [comment]
Just tried with the beta (24), same problem.

Running the occ command tells me that I already have the latest version

**Comment by oparoz** [comment]
Just checked the files and this is really 9.0.50, so it contains lots of vulnerabilities :S

**Comment by oparoz** [comment]
Found the problem in https://github.com/nextcloud/nextcloud-snap/pull/23 :)

**Comment by kyrofa** [comment]
> Just checked the files and this is really 9.0.50, so it contains lots of vulnerabilities :S

Ah, that was a problem on beta only (good catch). The released version is still 9.0.53.

**Comment by oparoz** [comment]
Yep, I compiled the release and saw nothing wrong, so thought there might be a caching problem, but decided to check the version in your PR to be sure :)
