### ISSUE TITLE
RedisException when upgrading Nextcloud Box to 11.0.3snap2

### ISSUE THREAD

**Issue by kruegerb** [nextcloud/nextcloud-snap#278]
I just received my Nextcloud Box today and the setup went smoothly. Everything worked out of the box on the 10.0.1 version. I then decided I wanted to upgrade to the latest snap before I do anything else. I followed the instructions for restarting from scratch here:

[How to restart from scratch](https://github.com/nextcloud/nextcloud-snap/wiki/How-to-restart-from-scratch)

After allowing 8-10 minutes for the box to configure itself, I performed the following actions:

From terminal:
1. `ssh ubuntu@nextcloud.local`
1. `sudo snap refresh nextcloud`

After snap refresh finished, In browser:
1. Loaded up nextcloud.local 
1. Entered an admin username and password and clicked the "Finish Setup" button

After the loading animation spun on the page for about 60 seconds, I received an HTTP 500 Error and the address bar contained the path `nextcloud.local/index.php/apps/files/`. Looking at the logs, I see the following in `apache/logs/php_errors.log`:

```
==> apache/logs/php_errors.log <==
[18-May-2017 04:20:34 UTC] PHP Fatal error:  Uncaught RedisException: Redis server went away in /snap/nextcloud/1333/htdocs/lib/private/Memcache/Redis.php:52
Stack trace:
#0 /snap/nextcloud/1333/htdocs/lib/private/Memcache/Redis.php(52): Redis->get('392c69e5b26389b...')
#1 /snap/nextcloud/1333/htdocs/lib/autoloader.php(153): OC\Memcache\Redis->get('OC_User')
#2 [internal function]: OC\Autoloader->load('OC_User')
#3 /snap/nextcloud/1333/htdocs/lib/private/Log/File.php(100): spl_autoload_call('OC_User')
#4 [internal function]: OC\Log\File::write('PHP', 'RedisException:...', 3)
#5 /snap/nextcloud/1333/htdocs/lib/private/Log.php(301): call_user_func(Array, 'PHP', 'RedisException:...', 3)
#6 /snap/nextcloud/1333/htdocs/lib/private/Log.php(159): OC\Log->log(3, 'RedisException:...', Array)
#7 /snap/nextcloud/1333/htdocs/lib/private/Log/ErrorHandler.php(81): OC\Log->critical('RedisException:...', Array)
#8 [internal function]: OC\Log\ErrorHandler::onException(Object(RedisException))
#9 {main}
  thrown in /snap/nextcloud/1333/htdocs/lib/private/Memcache/Redis.php on line 52
```
Why would I be getting this RedisException right out of the gate on 11.0.3snap2 when the 10.0.1 version didn't have any issues at all?

**Comment by kyrofa** [comment]
Hmm, this is actually a larger issue: nextcloud doesn't support updating in one jump like you essentially did, they require you to go through each release. It would probably be easiest to just remove the super old snap you have and just install the new one, since it sounds like it's a brand new box. Thoughts?
