### ISSUE TITLE
Download Progress not being shown while downloading a File

### ISSUE THREAD

**Issue by ghost** [nextcloud/nextcloud-snap#2796]
It's not a bug, it's just me asking for help.
I use the Edge browser
The way I want it to be.Displays the final file size and estimated download time.

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/112467275/599b97cb-4833-4193-bf36-2415156439d7)

What it looks like in reality.

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/112467275/74a51f99-e75c-4e04-9084-6117e4cac1aa)

Maybe I should go to the community and ask questions. Forgive me, I love this place more than anyone else.

**Comment by scubamuc** [comment]
@Benjamin-Watson0 
> Maybe I should go to the community and ask questions. Forgive me, I love this place more than anyone else.

its great to have you here, feel right at home 👋

I see the same as you do, whether its Chrome, Edge or Firefox. I tested different filetypes too:
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/26b55e1b-0543-46d4-8b08-5960c51f0d73)
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/7f4107b2-2af6-43c0-8981-b9222841d65f)
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/f738db90-7d2f-4aeb-b340-2d316c433398)

like you've already said, its unsure if this is a Nextcloud thing or a browser thing... definitely not a snap thing 👀
