### ISSUE TITLE
Mounted disks cannot be accessed in external storage

### ISSUE THREAD

**Issue by ghost** [nextcloud/nextcloud-snap#2797]
#### Describe the bug
I mount the disk in `/mnt/newdisk `and it can be accessed in my personal files, but when I click on the external storage, it shows that there is an error in the configuration.
I've connected the removable-media.And this folder is owned by the root user.
#### To Reproduce
1. Go to 'file'
2. Click on 'external storage'
3. 2. Click on 'Connected folders'
External mounting error
×
There is an error with this external storage. Do you want to check the configuration of this mount point in the settings page?
#### Expected behavior
I have access to it
#### Screenshots
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/112467275/f4bf5678-cd95-4f25-bc71-746c004dce7d)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
nextcloud  29.0.2snap1  42890  latest/stable  nextcloud
and:

    $ snap version
snap version
snap    2.63
snapd   2.63
series  16
ubuntu  22.04
kernel  5.15.0-112-generic
#### Screen recording file
https://1drv.ms/v/s!AjUhMEyrls9_gbkJif7-PRZvvAD7pg?e=nKTNeW

**Comment by scubamuc** [comment]
@Benjamin-Watson0 welcome back,

[Removable media](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-Nextcloud-snap#removable-media) must be mounted to either /media or /mnt as root with root permissions **and connected to Snap**! see https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-what-permissions-should-external-media-have

**Comment by scubamuc** [comment]
@Benjamin-Watson0 are you asking support for OS or Nextcloud snap?

**Comment by scubamuc** [comment]
@Benjamin-Watson0 did you connect removable media?
```
sudo snap connect nextcloud:removable-media
```

**Comment by scubamuc** [comment]
select local:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/c3cf4e1d-3e4b-41cb-8db9-164c0b620cde)

**Comment by scubamuc** [comment]
you're green:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/74ed9386-626f-437e-9f19-350cf70c5892)

I don't speak or read Chinese yet 😉 will need courses 👌🤿 ... counting on you.

sorry, but if you've done all the necessary steps suggested in the wiki, then you'll have to do some research.

**Comment by scubamuc** [comment]
@Benjamin-Watson0 

>echo "UUID=e943fbb7-020a-4c64-a48a-2597eb2496df /vdb1 ext4 defaults 0 0" >> /etc/fstab

double check this... you've mounted to `/vdb` instead of `/sdb`

**Comment by scubamuc** [comment]
@Benjamin-Watson0,
I'm having a "deja vu" can you change language to English and post that error message... see also your logfiles for "warning: **core** ACL **external_files**" .
if you're getting that message, remove `fulltextsearch` app as "fulltextsearch" cannot access `external_files` which is an upstream issue.

**Comment by scubamuc** [comment]
@Benjamin-Watson0 
wow, that looks a lot like an upstream language issue to me 👀 

you could try and see in changing the new user's language to Chinese, from English, to see whether that issue can be confirmed. then you'd know that its a language issue that upstream should take a look at.

if changing the language confirms the issue please close this and take the time to create an issue upstream with the Nextcloud external_files team. that would be greatly appreciated.

**Comment by scubamuc** [comment]
@kyrofa can't find the forest for all the trees. can you assist please?

**Comment by scubamuc** [comment]
okay, so its just the "super" admin user who's getting the error message?

**Comment by scubamuc** [comment]
@Benjamin-Watson0, 

sorry mate... I have no Idea what's happening there.

I've requested assistance from devs. Lets wait and see if someone has an idea?

**Comment by kyrofa** [comment]
> I can access the mounted folder in all files or personal files, but when I click on the mounted folder in external storage, it will give an error.

Hmm, this sounds like it's working when accessing it a certain way, and not working when accessing it other ways? If you can access it sometimes, I don't think confinement is your problem, and it doesn't sound like a permissions issue either. Is there anything interesting in your Nextcloud log?

**Comment by scubamuc** [comment]
@Benjamin-Watson0 well done! "seek an ye shall find" 🤿👌:
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/a4c60aec-b1c1-4ca4-a96b-1d5eab4608e6)

>I recently tweaked the php settings and I remember that S3 seemed to work fine before.

so we can agree, this is not a snap issue? please close here if you are d'accord.
