### ISSUE TITLE
OpenWeatherMap API Key Not Saved

### ISSUE THREAD

**Issue by sempervictus** [nextcloud/nextcloud-snap#285]
In the administrative settings menu, below SMTP configuration, is an API key field for OpenWeatherMap. This form either doesn't properly submit, or the backend does not commit, but keys arent saved whatever the cause, resulting in errors raised in the user-facing app.

Error log entry:
```
Undefined index: openweathermap_api_key at /var/snap/nextcloud/1446/nextcloud/extra-apps/weather/templates/admin.php#6
```

**Comment by kyrofa** [comment]
@sempervictus this sounds more like a weather-app-related issue, not snap-related. Does it work in nextcloud when it's not packaged as a snap?

**Comment by javierurien** [comment]
Same here, but different path (appears not to be snap)
`Undefined index: openweathermap_api_key at /var/lib/apps/nextcloud/apps/weather/templates/admin.php#6`

**Comment by kyrofa** [comment]
Alright, please do report this upstream, then. I'll close this here.
