### ISSUE TITLE
Menu bar Icons/text are all blacked out? Wrong theme color

### ISSUE THREAD

**Issue by BugsWorld** [nextcloud/nextcloud-snap#2978]
For some reason my nextcloud started looking different where the menubar icons are all black as well as the text which is impossible to read. And the Blue theme is not correct either, its a different blue for some reason. 

<img width="1923" alt="Screenshot 2024-11-24 at 2 40 59 PM" src="https://github.com/user-attachments/assets/bd6f2d78-e5d4-44d5-a2e3-20efb24689d4">

**Comment by scubamuc** [comment]
@BugsWorld thanks for your request

please see [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help), especially when you create an [issue](https://github.com/nextcloud-snap/nextcloud-snap/issues) complete the bug report (the more information the better). this is certainly not a snap issue

consider posting your issue [upstream](https://help.nextcloud.com/)

double check your "Appearance settings", check the background colour in your Theming settings... etc.

![grafik](https://github.com/user-attachments/assets/bf3f337b-3705-406f-b2ff-42605d8245e5)
