### ISSUE TITLE
"Strict-Transport-Security" HTTP header is not configured to at least "15552000" seconds

### ISSUE THREAD

**Issue by philFernandez** [nextcloud/nextcloud-snap#299]
I've installed and setup nextcloud snap on a raspberry pi 3 on Ubuntu Core 16. The setup went smooth, and everything is up and running w/o issue for the most part. The only issue I am having is that on the admin page in the nextcloud web ui I am getting a warning about the Strict-Transport-Security HTTP header not being configured to at least 15552000 seconds. 

This is my first experience with Ubuntu Core so I'm not really familiar with how the file systems work. I've located the ssl.conf in directory /snap/nextcloud/current/conf. This seems to be the conf file where I would want to adjust the setting that nextcloud is complaining about but this part of the file system is read only. I'm not able to adjust conf settings even as root. 

How can I adjust the setting that nextcloud is complaining about, and make the warning on my admin page go away? Any help is greatly appreciated.

**Comment by kyrofa** [comment]
What command did you use to enable HTTPS? Are you using Let's Encrypt certificates, self-signed certificates, or certificates from another CA?

**Comment by philFernandez** [comment]
I used the command "sudo nextcloud.enable-https self-signed" I am using the self signed certificate that was generated via this command.

**Comment by kyrofa** [comment]
Yeah HSTS and self-signed certs don't mix: https://lists.owasp.org/pipermail/security101/2013-February/000123.html . The snap doesn't enable HSTS if you elect to use self-signed certificates. If you need HSTS, then you should use certificates that trace back to a trusted CA (e.g. Let's Encrypt).

**Comment by philFernandez** [comment]
Okay, thank you for the info. I am using nextcloud for personal use. Do you think I'd be okay from a security stand point to ignore the HSTS warning and use as is?

**Comment by philFernandez** [comment]
I have it setup in such a way that I can access the pi nextcloud instance from the web over port 443, which I have forwarded to the pi via my home router.

**Comment by kyrofa** [comment]
Yes, it's still encrypted, just keep its limitations in mind:

- Visits to HTTP (even though HTTP redirects to HTTPS) can be hijacked
- Since the cert doesn't trace back to a trusted root it will always warn. If you accept permanently, make sure it's the legitimate one, and treat the warning showing up again as an issue (although note that the cert expires after 90 days, so you'll eventually get the warning again and need to re-accept it).

**Comment by philFernandez** [comment]
Thank you for your help

**Comment by kyrofa** [comment]
Of course, any time :smiley: .

**Comment by Fuseteam** [comment]
ah cool, so its due to using a self-signed certificate. on a related note is there an official way to tell the browser to trust the certificate?

**Comment by kyrofa** [comment]
> official way to tell the browser to trust the certificate?

Yes, but every browser is different, so I can't really provide generic instructions.

**Comment by Fuseteam** [comment]
> > official way to tell the browser to trust the certificate?
> 
> Yes, but every browser is different, so I can't really provide generic instructions.

is there at least a way to get ahold of the CA file? I'm using firefox for the most part
