### ISSUE TITLE
[Security vulnerability] User enumeration

### ISSUE THREAD

**Issue by SkyWheel** [nextcloud/nextcloud-snap#300]
Hi ALL,
First I was going to report this bug privately, but then I've figured out [this link](https://packetstormsecurity.com/files/140493/Nextcloud-Owncloud-User-Enumeration.htmll) with the same vulnerability.
My friend performed testing my Nextcloud installation with [Burp Suite](https://portswigger.net/) and discovered some issues. He scanned login web page with big dictionary of usernames and enumerated usernames from my Nextcloud server.
If a username is non-existent, then response looks like below:
![bs_user_enum_1](https://user-images.githubusercontent.com/10903432/26912265-9c50d5ac-4c56-11e7-83f6-8cd200ad9586.png)
But if a user exists in the server then response looks like below:
![bs_user_enum_2](https://user-images.githubusercontent.com/10903432/26912283-b3af02e6-4c56-11e7-8533-a140fe362384.png)
You can check the issue without Burp Suite in next way.
If you try to login with non-existent user "test" and then click button "Wrong password. Reset it?", you will see:
![image](https://user-images.githubusercontent.com/10903432/26912347-073829b0-4c57-11e7-8818-21c1e0f166c9.png)
Then if you try to login with existing user and click button "Wrong password. Reset it?", you will see:
![image](https://user-images.githubusercontent.com/10903432/26912406-6e8d924e-4c57-11e7-9e9c-58a44bbe3c45.png)

I reckon it is issue of Nextcloud itself not just Nextcloud-snap, but not sure should I create just a bug-report here, or for Nextcloud server itself and link them, or just there. Please advise.

**Comment by kyrofa** [comment]
Good catch! You're right though, this isn't snap specific. Please report against [Nextcloud Server](https://github.com/nextcloud/server).

**Comment by SkyWheel** [comment]
@kyrofa 
I've created bug-report on Hackerone platform. Hopefully they will fix it soon...

**Comment by SkyWheel** [comment]
Well, they don't consider user enumeration as a security risk. Their statement is [here](https://nextcloud.com/security/threat-model/). Though I'm not agree with them, but can't do anything...
@kyrofa , could you please advise if fail2ban works with Nextcloud-snap (separately) or it is required to be included in the snap?
Thank you.

**Comment by kyrofa** [comment]
Yes, fail2ban should work fine (on classic Ubuntu anyway, Ubuntu Core may be different), although the logs are in the snap's writable location instead of default places (i.e. /var/snap/nextcloud/...). I'm not sure how verbose the apache log needs to be in order for it to work though. Please do test it, and if we need to enable some logging to make it work, I think that's just fine.
