### ISSUE TITLE
PHP 7.0.20 available

### ISSUE THREAD

**Issue by pachulo** [nextcloud/nextcloud-snap#303]
http://www.php.net/ChangeLog-7.php#7.0.20

I opened PR https://github.com/nextcloud/nextcloud-snap/pull/302 to update it.

**Comment by kyrofa** [comment]
Once the builds finish the fix for this issue will be contained in the beta branch:

    sudo snap install --beta nextcloud

Or, if you already have it installed:

    sudo snap refresh --beta nextcloud

**Comment by kyrofa** [comment]
This has now been upgraded to a security issue thanks to Nessus.
