### ISSUE TITLE
On demand thumbnail/preview generation crashes Nextcloud Box

### ISSUE THREAD

**Issue by ps-nl** [nextcloud/nextcloud-snap#304]
With reference to: https://help.nextcloud.com/t/uploading-viewing-photos-crashes-nextcloud-box/13977/3 

In the standard configuration on a RPI-3, the Nextcloud box is brought to its knees by on-demand thumbnail/preview genaration. The impact could be lessened by the preview generator app, but this is not part of the standard installation. 

Would it be possible to configure the snap so as to include the preview generator app and a corresponding cronjob by default when installed on a Nextcloud Box. Given the aim of that project / appliance, manual install and setup of a cronjob is probably beyond the scope of the average user.

**Comment by pachulo** [comment]
I think that this is a know problem:

- https://github.com/nextcloud/gallery/issues/14
- https://github.com/nextcloud/gallery/issues/195

And yes, integrating the [previewgenerator application](https://apps.nextcloud.com/apps/previewgenerator) could be a solution ([at least in NC 12](https://github.com/nextcloud/gallery/issues/14#issuecomment-299128198)) but that should be tested.
Do you think that you could create a PR?

**Comment by ps-nl** [comment]
@pachulo I should have probably disclosed that I am the average user referred to. I have not yet managed to get the preview generator into a cronjob. So unfortunately, I don't think a PR from my side will move this forward.

**Comment by kyrofa** [comment]
Our goal in the snap is to provide a standard Nextcloud experience, using recommended settings as much as possible. These are shortcomings in a standard Nextcloud app, and should be fixed there, not worked around here.

**Comment by ps-nl** [comment]
Kyle I understand that philosophy. It is a bit of an issue though that Nextcloud is now selling a hardware solution (the Box) with software that is configured in such a way that the product does not offer that “standard Nextcloud experience”.

**Comment by nero120** [comment]
Completely agree with @ps-nl . I also bought a NextCloud box with RPI-3 recently and not only do I have to wait far too long to see image previews, it usually crashes and brings down the whole site if I navigate to a folder with many photos (I store my photo collection in NextCloud).

As a user I see this as a showstopping issue and it's frankly incredibly disappointing that such a visible part of the product is both broken and badly lacking when it is actually working.

The rest of the product is great and I would be very happy were it not for this issue, but if I'm honest it's making me think twice about using it... pity.

**Comment by ps-nl** [comment]
FYI, I have migrated to NextCloudPi a couple of months ago, which is running without any issue. I have given up on the official snap being configured in a way that works for the Box.

**Comment by nero120** [comment]
Thanks for the heads-up, I didn't know about that! Have you got preview generation running with it as well?

**Comment by ps-nl** [comment]
Yes, and it is reasonably fast as well.

**Comment by nero120** [comment]
Ok thanks @ps-nl, I'll give it a try.

**Comment by kyrofa** [comment]
> It is a bit of an issue though that Nextcloud is now selling a hardware solution (the Box) with software that is configured in such a way that the product does not offer that “standard Nextcloud experience”.

Except it does. And the standard Nextcloud experience sucks in this regard, I agree. You're asking us to provide a NON-standard experience, when I'm saying Nextcloud should just be fixed.

You seem to be under the mistaken impression that we're in charge of the Box here, and I'm afraid we're not. We simply can't hack around every Nextcloud limitation to make it work better on your device. Please log bugs against the gallery.

**Comment by nero120** [comment]
Point taken @kyrofa, fair enough.

**Comment by andthenirealized** [comment]
Just an observation that could be of interest to others.

Running the preview php-script would crash Nextcloud web access on my rpi 3B+. SSH access still active, though. Temporary fix was to locate the php-process and kill it. Not fun.
However, after updating the firmware (sudo rpi-update), the problem has disappeared.

Please be cautious, if you choose to update the firmware. DO NOT interrupt the update process. It could brick your Pi.
