### ISSUE TITLE
Nextcloud fails to sync, load folders and data

### ISSUE THREAD

**Issue by wabuMike** [nextcloud/nextcloud-snap#305]
Nextcloud sometimes fails to load data or sync in the clients.
I'm using a Raspberry Pi 3.
`dmesg` is full of lines like this `[55381.412583] audit: type=1400 audit(1497526231.650:6960): apparmor="DENIED" operation="exec" profile="snap.nextcloud.mysql" name="/usr/bin/nohup" pid=24529 comm="mysqld_safe" requested_mask="x" denied_mask="x" fsuid=0 ouid=0` and `[55350.071177] audit: type=1400 audit(1497526200.310:6954): apparmor="DENIED" operation="exec" profile="snap.nextcloud.mysql" name="/bin/systemctl" pid=24187 comm="mysql.server" requested_mask="x" denied_mask="x" fsuid=0 ouid=0`
The nextcloud.log is full of lines like
    {"reqId":"EDNe2c4jzvYI+IzioLP3","remoteAddr":"<XXX>","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\Exception\\\\DriverException: An exception occurred while executing 'SELECT `id`, `numeric_id`, `available`, `last_checked` FROM `oc_storages` WHERE `id` IN (?)' with params [\\\"local::\\\\\\\/var\\\\\\\/snap\\\\\\\/nextcloud\\\\\\\/common\\\\\\\/nextcloud\\\\\\\/data\\\\\\\/Michl\\\\\\\/\\\"]:\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/snap\\\/nextcloud\\\/1542\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(201): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/snap\\\/nextcloud\\\/1542\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(150): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/snap\\\/nextcloud\\\/1542\\\/htdocs\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/snap\\\/nextcloud\\\/1542\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#5 \\\/snap\\\/nextcloud\\\/1542\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/snap\\\/nextcloud\\\/1542\\\/htdocs\\\/apps\\\/dav\\\/lib\\\/Server.php(231): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/snap\\\/nextcloud\\\/1542\\\/htdocs\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#8 \\\/snap\\\/nextcloud\\\/1542\\\/htdocs\\\/remote.php(165): require_once('\\\/snap\\\/nextcloud...')\\n#9 {main}\",\"File\":\"\\\/snap\\\/nextcloud\\\/1542\\\/htdocs\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":162,\"User\":\"Michl\"}","level":4,"time":"2017-06-15T10:46:04+00:00","method":"PROPFIND","url":"\/remote.php\/dav\/files\/<XXX>","user":"Michl","version":"11.0.3.2"}

**Comment by wabuMike** [comment]
This might be the same issue as  #259 . Can't confirm this, because I can't find the mysql logs.

**Comment by wabuMike** [comment]
It looks like a reboot solved this issue. No more AppArmor messages in kernel log. 
You may close this issue.

**Comment by kyrofa** [comment]
Note that the MySQL logs are located in `/var/snap/nextcloud/current/mysql/`. I'll go ahead and close this as suggested, but feel free to re-open if necessary.
