### ISSUE TITLE
Lost SSH Key 

### ISSUE THREAD

**Issue by anagno** [nextcloud/nextcloud-snap#310]
Hello everyone,

When I bought my nextcloud box I followed the procedure described in the wiki (https://github.com/nextcloud/nextcloud-snap/wiki/How-to-connect-to-the-Nextcloud-Box-with-SSH#out-of-box-experience-oobe) and I created an account using the SSO account of Ubuntu to set up the box. 
Unfortunately, after a format in my personal I lost my private key for that account and now I am not able to connect.  So my question is: is there a solution to produce new keys, or do I have to reinstall the box?

Kind regards,

anagno

**Comment by kyrofa** [comment]
Don't reinstall! Worst-case, you can remove the SD card and change the key yourself. However, before resorting to that, would you mind asking that question in the [Snapcraft forum](https://forum.snapcraft.io/)?

**Comment by anagno** [comment]
https://forum.snapcraft.io/t/can-ssh-keys-be-regenerated/1116

Thanks for the info. I did not know that there was a specific forum.

**Comment by anagno** [comment]
In the end I figure it out. Just as you suggested I changed the key by removing the **hard drive**. The key is located under writable/user-data/<user mail>/.ssh/authorized_keys. I swap my old public key with a new one and I was able to log in.

I would suggest to include this information also in the wiki, because probably I am not the only person that "misplaced" his keys. 

Kind regards,

anagno
