### ISSUE TITLE
Update Apache to 2.4.26

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#311]
2.4.25 has multiple security vulnerabilities.

**Comment by oparoz** [comment]
Just a heads up, the fcgi proxy is broken in this release. The apache config needs an extra switch.

**Comment by kyrofa** [comment]
Thanks for the heads up!

**Comment by kyrofa** [comment]
@oparoz I don't see any issues. Mind taking a quick look at #312? It seems to work for me.

**Comment by oparoz** [comment]
I think it's too risky not to include the fix for
https://bz.apache.org/bugzilla/show_bug.cgi?id=61202

**Comment by kyrofa** [comment]
To be clear, are you recommending that we use `ProxyFCGIBackendType GENERIC` for the proxy?

**Comment by oparoz** [comment]
Yes, there is a sample config at the bottom of the ticket. It restores the old behaviour.
