### ISSUE TITLE
Downloading uploaded by sharing files is not working 

### ISSUE THREAD

**Issue by SkyWheel** [nextcloud/nextcloud-snap#322]
Hi guys!
Figured out very annoying issue.
I shared a folder via a link with a password. Another person has uploaded a file.
When I'm trying to download the shared file via ticking it with mouse and clicking "Download" button on the top right corner then everything is OK:
![working](https://user-images.githubusercontent.com/10903432/28354338-e3044c24-6ca2-11e7-8d9d-ecb47ed93fd6.png)
But if I'm trying to download via file's properties:
![not_working](https://user-images.githubusercontent.com/10903432/28354381-063f0d1e-6ca3-11e7-8fe3-252672e74311.png)
Then I receive File not found page:
![file-not-found](https://user-images.githubusercontent.com/10903432/28354405-1d735aee-6ca3-11e7-84a3-e0b0328b4299.png)
If the same file I'm uploading via different Nextcloud account then everything is OK.
The issue has been figured out in all major browsers (Explorer, Edge, Chrome, Firefox).

**Comment by kyrofa** [comment]
That sounds like an [upstream Nextcloud](https://github.com/nextcloud/server) bug. Do you mind reporting there?

**Comment by SkyWheel** [comment]
@kyrofa , Hi Kyle.
Just caught next error.
I've uploaded test file via shared link.
When I'm trying to access it via my account receiving error below:
![uploaded_file_error](https://user-images.githubusercontent.com/10903432/28403886-2735603c-6d6a-11e7-98a8-76bb6b3b4289.png)
At the same time in admin logs I can see next error message
`

Fatal | webdav | OC\HintException: Bad Signature/snap/nextcloud/1982/htdocs/apps/encryption/lib/Crypto/Crypt.php - line 464:   OCA\Encryption\Crypto\Crypt->checkSignature('kJ/PHXlLHUIAZvo...',  '})\x849`(o\xE4mnf&\x80\xA0\xF9...', '13c80465b2b5eec...')/snap/nextcloud/1982/htdocs/apps/encryption/lib/Crypto/Encryption.php - line 372:    OCA\Encryption\Crypto\Crypt->symmetricDecryptFileContent('kJ/PHXlLHUIAZvo...',  '})\x849`(o\xE4mnf&\x80\xA0\xF9...', 'AES-256-CTR', 0, 0)/snap/nextcloud/1982/htdocs/lib/private/Files/Stream/Encryption.php - line 460:  OCA\Encryption\Crypto\Encryption->decrypt('kJ/PHXlLHUIAZvo...', 0)/snap/nextcloud/1982/htdocs/lib/private/Files/Stream/Encryption.php - line 291:  OC\Files\Stream\Encryption->readCache()[internal function] OC\Files\Stream\Encryption->stream_read(8192)/snap/nextcloud/1982/htdocs/3rdparty/icewind/streams/src/Wrapper.php - line 83:  fread(Resource id #522, 8192)/snap/nextcloud/1982/htdocs/3rdparty/icewind/streams/src/CallbackWrapper.php - line 91:  Icewind\Streams\Wrapper->stream_read(8192)[internal function] Icewind\Streams\CallbackWrapper->stream_read(8192)/snap/nextcloud/1982/htdocs/3rdparty/sabre/http/lib/Sapi.php - line 78:  stream_copy_to_stream(Resource id #526, Resource id #536, '3407284')/snap/nextcloud/1982/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 498:  Sabre\HTTP\Sapi  sendResponse(Object(Sabre\HTTP\Response))/snap/nextcloud/1982/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/snap/nextcloud/1982/htdocs/apps/dav/appinfo/v1/webdav.php - line 60:  Sabre\DAV\Server->exec()/snap/nextcloud/1982/htdocs/remote.php - line 165:  require_once('/snap/nextcloud...'){main} | 2017-07-20T16:32:55+1000
-- | -- | -- | --


`
I'm going to create bug report for upstream Nextcloud, but I concern could it be issue with Nextcloud-snap?

**Comment by SkyWheel** [comment]
OK, figured similar [upstream Nextcloud issue](https://github.com/nextcloud/server/issues/4604)
Looking forward to upgrade my Nextcloud-snap to 12 or at least 11.0.4, because I use uploading via shared folders heavily, and entire Nextcloud server is 90% useless without this feature.

**Comment by kyrofa** [comment]
Yeah you and me both, but v12 doesn't support the snap, we're crossing our fingers for a v12.0.1.

**Comment by kyrofa** [comment]
On another issue you mention that this used to work. When? The last several updates from the snap have been security updates, it's been using Nextcloud 11.0.3 for a while.

**Comment by SkyWheel** [comment]
@kyrofa,  my bad. The issue was already there, but I have discovered it too late...
