### ISSUE TITLE
Disabling automated Nextcloud-snap refresh

### ISSUE THREAD

**Issue by SkyWheel** [nextcloud/nextcloud-snap#327]
Hi guys,
I came to a point when I need to disable automatic snap refresh. I would like to perform all snap updates manually by "sudo snap refresh".
I've tried to find some solution online, but none of solutions work for me.
Do you guys have any workaround for that?
Thank you.

**Comment by kyrofa** [comment]
I'm afraid not. Snaps are designed to automatically update. You can set those updates to occur at a predetermined date and time, but you cannot disable them completely. I'm afraid this is out of our control. More details in [this forum post](https://forum.snapcraft.io/t/disabling-automatic-refresh-for-snap-from-store/707).

**Comment by SkyWheel** [comment]
@kyrofa , Thanks Kyle, but as far as I understood this option gives me just update window at least once a day. So, I cannot set up a particular date.
Correct me please if I am wrong.

**Comment by SkyWheel** [comment]
Unfortunately that means snapd is not production-ready...

**Comment by kyrofa** [comment]
I think in the current release you're right, but if you read that thread you'll see the month thing is at least planned if not already in master.

What makes snapd not production ready? That they have strong feelings about automatic updates?

**Comment by SkyWheel** [comment]
Looking forward to receive this feature from them.
Production-ready means at least full control on update.
For example, I faced the situation, when a small Nextcloud bug appeared as pretty serious for me. 90% functionality of my Nextcloud installation has been affected. If I only could test new version before upgrade...
Now I'm using 12/Edge channel only because of this small bug.
Obviously, there are other options of Nextcloud installations, but I love Nextcloud-snap so much...

**Comment by kyrofa** [comment]
The snap has been on 11.0.3 for ages now, what issue are you referring to?

**Comment by SkyWheel** [comment]
This [one](https://github.com/nextcloud/nextcloud-snap/issues/322)
