### ISSUE TITLE
http://localhost shows an apache webpage

### ISSUE THREAD

**Issue by tenleftfingers** [nextcloud/nextcloud-snap#328]
I've installed the nextcloud snap, but 127.0.0.1/localhost show the default apache page. Apache was installed previously (via .deb).

What is the mechanism that dictates which installed server gets 'representation' by 127.0.0.1/localhost and how come nextcloud snap isn't represented by it?

**Comment by pachulo** [comment]
Well, if the Apache httpd was running before the snap was installed is normal that you see the default apache page. When the snap starts and tries to bind to port 80 it will get an error, as the httpd daemon already "took" it.

I think that the "mechanism" is "the first one that takes it".

**Comment by kyrofa** [comment]
Indeed, the snap currently requires port 80. It's completely first-come, first-served.
