### ISSUE TITLE
Nextcloud Snap + Rocket.Chat Snap

### ISSUE THREAD

**Issue by AlexanderPlaza** [nextcloud/nextcloud-snap#333]
Hello!

Currently I am running the latest version of Nextcloud Snap and the latest Rocket.Chat Snap on the same box. Both are working but only Nextcloud is working with LetsEncrypt because it is set for port 80/443. 

I know Rocket.Chat Snap uses Caddy as a proxy. However I am not sure what the Nextcloud snap uses as a proxy. As I am currently using the dynamic DNS client noip.com I was wondering if the following is possible.

To have port 80/443 open to be used by Lets Encrypt by both snaps -> have it forwarded to the appropriate internal ports and base that on the Dynamic DNS address?

Example:
Nextcloud -> nextcloud.ddns.net -> Internal Port 3909
Rocket.Chat -> rocketchat.ddns.net -> Internal Port 3000

I understand this is possible if I was to just build it all manually but I am quite excited to be using the Snap technology. Even a small push in the right direction/project would be appreciated. Once I have a working configuration I would like to contribute to your Wiki (and rocket.chat's Wiki) so others can follow.

Warm regards,

Alexander

**Comment by kyrofa** [comment]
The snap uses Apache to proxy to php fpm. We ran into issues trying to make the port configurable, but perhaps it's time to try again. Until then, what I do personally is run the nextcloud snap in a lxd container. All my web apps run in a container. This isolates them from each other. Then my front-facing container runs haproxy and proxies traffic according to domain name.

**Comment by AlexanderPlaza** [comment]
What sort of previous issues were you running into? I think it would be excellent if we were able to configure ports. 

Is there any documentation on running the snap in a LXD container or how to migrate a current configuration to LXD containers?

**Comment by pachulo** [comment]
@AlexanderPlaza the problems are described here: https://github.com/nextcloud/nextcloud-snap/issues/134#issuecomment-301612433

**Comment by extraymond** [comment]
It would be nice to have rocketchat, wekan or other webservice alongside nextcloud.
If port 80 and 443 can be configurable, we can just use caddy to obtain the certificate automatically.

**Comment by SkyWheel** [comment]
@kyrofa , could you please share installation/configuration options for the snap in lxd.
And what are the advantages  to use snap-in-lxd against nextcloud-docker?

**Comment by kyrofa** [comment]
Regarding advantages against nextcloud-docker, note that I've not actually used it. I doubt it automatically updates, though. It claims its targeting microservices.

Anyway, installing the snap in lxd is pretty easy assuming you have lxd installed:

1. Create a new container: `lxc launch ubuntu:xenial nextcloud`
2. Log into the container: `lxc exec nextcloud bash`
3. Make sure it's all up-to-date, and install `squashfuse`: `apt update && apt upgrade -y && apt install squashfuse`
4. Install Nextcloud: `snap install nextcloud`

That's it.

**Comment by kyrofa** [comment]
See #349 for port configuration support.

**Comment by kyrofa** [comment]
You should now be able to change the ports used by Nextcloud. See the [README for more details](https://github.com/nextcloud/nextcloud-snap/blob/master/README.md#httphttps-port-configuration). I believe that solves this issue, but please shout if not.
