### ISSUE TITLE
Downgrading is not supported

### ISSUE THREAD

**Issue by SkyWheel** [nextcloud/nextcloud-snap#343]
I was using channel 12/edge for several weeks. Decided to downgrade to the stable channel. But it was unsuccessful:
![downgrade_is_not_supported](https://user-images.githubusercontent.com/10903432/29704304-95c169c4-89bc-11e7-9e53-f458c17d4e37.png)

Oops...

So, what are the ways to return back to the stable channel?

**Comment by kyrofa** [comment]
Unfortunately this is just how Nextcloud works. Your only option is to wait until v12 is actually released.
