### ISSUE TITLE
how to change domain name without breaking everything

### ISSUE THREAD

**Issue by xavierle** [nextcloud/nextcloud-snap#346]
actually i have 3 trusted domains configure

domain1.com
domain2.com
domain3.com

all domains are accepted but everything is redirected to domain1.com

i have to do somehting else with domain1
how can i configure the snap to make domain2.com as the main domain
without breaking everything

i feel stupid using snaps ...

this is quite different than using a standard server

**Comment by kyrofa** [comment]
Nothing in Apache is doing that redirect, and I don't think Nextcloud does either. Are all your domain names pointing to the exact same IP, or are the others e.g. URL records pointing to domain1.com?

**Comment by kyrofa** [comment]
I'll go ahead and close this. Let me know if you're still having problems.
