### ISSUE TITLE
Let's encrypt challange fails with timeout error

### ISSUE THREAD

**Issue by ti-guru** [nextcloud/nextcloud-snap#348]
Hey,

I gave this snap a go as I was attracted by nextcloud-snap's relative ease of installation compared to going with the full [full stack installation](https://www.c-rieger.de/nextcloud-installation-guide/). This is a repost of a thread at [help.nextcloud.com](https://help.nextcloud.com/t/nextcloud-snap-fails-lets-encrypt-challenge-with-timeout-error/20674) as there currently are no replies there:

I’ve got a raspberry pi 3 on my local LAN with a static ip address. The router has port 80 and 443 forwarded to the pi. I’ve flashed the SD card with the latest Ubuntu core image and installed the Nextcloud snap like [this](https://pastebin.com/Mn7wRiW9). After the installation I added my own domain as a trusted domain. No other customizations done. I've followed the steps in the [wiki](https://github.com/nextcloud/nextcloud-snap/wiki/Connecting-the-Nextcloud-Box-to-the-Internet) meticulously.

I’m trying to obtain a SSL certificate from let’s encrypt with the standard commands like [this](https://pastebin.com/GSJvEi8q), but the process keeps failing every time with a timeout error.

I’m using Dynu as DNS server. My domain is setup with just the ipv4 A record and I’ve disabled the ipv6 AAAA record as my ISP doesn’t support ipv6 (yet). A DNS propagation search shows that other DNS servers have the correct ip address. I can reach the nextcloud installation through port 80 if I type in my domain address in the browser (e.g. on a phone using cellular data), and use port 443 if I use the `sudo nextcloud.enable-https self-signed` command. The logs show that certbot is using the correct ip address to connect. [This](https://pastebin.com/jXaVRUGq) is the log output from certbot after a failed attempt.

Not sure if I've overlooked some configuration details or if it's a bug. Any ideas on where to from here?

**Comment by kyrofa** [comment]
This is an excellent bug report, thank you for the thorough explanation and logs. However, I don't see anything wrong here other than the obvious: Let's Encrypt simply cannot reach the files on your server. I'd be happy to help you troubleshoot, but in order to do that I need your real data: domain name, expected IP address, etc. If you're not comfortable sharing that information here (probably good instincts), would you mind emailing them to me? My contact information is on my profile.

**Comment by kyrofa** [comment]
Thanks for sending me the details, @ti-guru.

The domain name does indeed resolve to the IP address you've provided, however, I can't seem to get any traffic through. No pings, no scans, no Firefox on port 80, nothing. The same thing happens to me that seems to happen to Let's Encrypt. If you didn't already tell me that you could use this domain to visit Nextcloud I would suspect that your router didn't have port forwarding enabled. Is there any chance you're using geoblocking? If we fix things such that I can get through, I suspect Let's Encrypt will begin working as well.

**Comment by ti-guru** [comment]
Thanks for your feedback @kyrofa! This turned out to be an incorrectly configured port forward on my router. No nextcloud-snap bug.

**Comment by kyrofa** [comment]
Ah ha! Excellent, thank you for getting back to me :) .
