### ISSUE TITLE
Enhance customization CHRON.PHP allowing spinning down hard drives

### ISSUE THREAD

**Issue by vedovatti** [nextcloud/nextcloud-snap#350]
The current Cron-job configuration is set by default 15 min. to reschedule a job. This keeps constantly spinning the hard drives in idle as well.
This cause unnecessary spinning of hard drives in the Nextcloud Box, which wastes energy and reduce time life of hard disks.
Would be great to have the possibility to customize the Cron-job configuration to set different time intervals. Additionally, could be great to have to stablish different in a different time range. E.g. Schedule corn-job 10 min interval from 08:00 - 18:00, and 2 hours interval from 18:00 - 08:00.
Any other suggestion to solve this issue would be great. Thanks.

**Comment by kyrofa** [comment]
15 minutes is the interval recommended in the Nextcloud manual. Running it less often would have bad side-effects: event notifications would be late, garbage collection wouldn't happen regularly, etc. If there's nothing for it to do, then it shouldn't do anything. What makes you say that this wastes energy and shortens disk lifespan?

**Comment by devz3r0** [comment]
@kyrofa I have the same device and issue, what the TC meant is, that the hard disk is not shutting down, because the 15 min cronjob is preventing that, because it is loading stuff from the disk during the time, even if its only the script itself which may do nothing.

In my case I use it only as replication device for my primary nextcloud instance, so a ajax-refresh which is created only on access is sufficient, and the room won't always have the sound of the spinning disk.

**Comment by vedovatti** [comment]
The real issue is the hard disks keep spinning from my Nextcloud Box. According to the official documentation it suppose to put to sleep after no use from some minutes. During the last 2 months I tested the Box and I realized it never stops spinning the disks. The hard disk sound and heats. I am the only user, so there almost not activity, and I expected to stop spinning the disk . But it never stops.
After some investigation, as @devz3r0 mentioned, it seems to be caused by the cron job executing every 15 min it keeps the disk spinning. 
So I understand the Cron job is necessary but is the is a way to prevent keeping the hard disks spinning in idle, that would a good solution.

**Comment by kyrofa** [comment]
Okay, what is the preferred solution, here? An option to disable the cron job and simply use ajax?

**Comment by devz3r0** [comment]
either that, or let the user set the time by himself. The thing what baffles me is that, its so locked down, that no one can change it by them self. Isn't that the opposite of an open system?

**Comment by kyrofa** [comment]
@devz3r0 the snap isn't meant to necessarily be open, it's meant to work work out of the box. Ubuntu Core has no concept of cron jobs; this was the best we could come up with that worked out of the box.

Now that we have configuration working, we can support disabling that job, or changing its frequency. It should be a pretty quick fix, so I've nominated it for Hacktoberfest.
