### ISSUE TITLE
Removing trusted domain and lets encrypt certificate

### ISSUE THREAD

**Issue by Seferi** [nextcloud/nextcloud-snap#352]
Hi,

I changed my dns provider and need to remove the old https certificate from lets encrypt and the domain from the trusted domain. I have been searching around in nextcloud forum and here but couldn't find much related to the problem. I appreciate if you could help. Thanks in advance.

**Comment by kyrofa** [comment]
You can see the list of trusted domains with:

    $ sudo nextcloud.occ config:system:get trusted_domains
    foo.com
    bar.com

To remove one, use the index in that list. For example, to remove `bar.com` from above:

    $ sudo nextcloud.occ config:system:delete trusted_domains 2

You can disable HTTPS using:

    $ sudo nextcloud.disable-https

And then try getting certs for your new domain just as you did before. If you run into issues with that, blow away the old certbot data at `/var/snap/nextcloud/current/certs/certbot` and try again.

**Comment by Seferi** [comment]
Thanks for the quick response mate. I have done everything you said except the certbot thing but when i go to the website over https or try to login with nextcloud android app, i get The url does not match the hostname in the certificate.. Disabling https doesn't remove the certificates.. How can i remove the certificates?

**Comment by kyrofa** [comment]
Disable HTTPS should stop using the certs, even though they're still on disk. Although since it used HSTS you have a bit of an issue since your browser is caching the fact that it's HSTS. Try visiting it in Firefox's private mode.

If you must remove the certs, yeah, blow away `/var/snap/nextcloud/current/certs/certbot`.

**Comment by Seferi** [comment]
Removing the certbot solved it mate. Thanks alot. By the way i have been getting these errors with every command many times: 
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

Is it normal?

**Comment by kyrofa** [comment]
You must be using the Box. Judging from the bug reports I've seen, yeah, it's normal. I'm not sure what the deal is with that image (I was not involved in making it), but from what I've seen it's harmless.

I'm glad you're sorted! I'll go ahead and close this, then.
