### ISSUE TITLE
Let's Encrypt on different ports 

### ISSUE THREAD

**Issue by primetoxinz** [nextcloud/nextcloud-snap#353]
In my attempts to setup Let's Encrypt on my Nextcloud Box I have discovered that my ISP blocks port 80 inbound, so I cannot setup SSL has it is. Is it possible to change the ports to something other than 80 for this purpose? If so what configs would I change?

**Comment by kyrofa** [comment]
You mean they block port 80 inbound? i.e. you can't host anything on port 80? What about 443?

**Comment by primetoxinz** [comment]
Ah yes, confused my directions, I meant inbound. 443 isn't listed as blocked by the ISP but no services can see the port as open.

**Comment by kyrofa** [comment]
@primetoxinz I'm sorry to say that you're simply out of luck right now: Let's Encrypt [doesn't support anything other than port 80 for webroot, which we're using](https://certbot.eff.org/faq/#can-i-issue-a-certificate-if-my-webserver-doesn-t-listen-on-port-80):

> ### Can I issue a certificate if my webserver doesn't listen on port 80?
> 
> Yes, using the TLS-SNI-01 challenge. At the moment, Certbot only implements this challenge for Apache. If you’re using the webroot mode, your webserver must listen on port 80.

**Comment by kyrofa** [comment]
Note that you can still use self-signed or custom certificates, though.

**Comment by primetoxinz** [comment]
Ok, well how would I change the listening port for the webserver so that I can use it outside of my lan? not certain where the config is.

**Comment by kyrofa** [comment]
@primetoxinz that functionality was literally just released, you'll need to either wait for the snap to be automatically updated, or run `sudo snap refresh` manually if you want it sooner. Then, refer to the [README](https://github.com/nextcloud/nextcloud-snap#httphttps-port-configuration) for details on how to change ports.

**Comment by primetoxinz** [comment]
This worked, thank you for the help :)
