### ISSUE TITLE
 Preview Generator nextcloud box

### ISSUE THREAD

**Issue by coderInCape** [nextcloud/nextcloud-snap#355]
Hiya,
I’m trying to configure Preview Generator in my nextcloud box
I enabled the app from nextcloud app store

Went to ssh to execute the following command

    sudo -u www-data php /snap/nextcloud/current/htdocs/occ preview:generate-all

and the message I get is

    sudo: php: command not found

which is weird. Isn’t it supposed to be installed already?

One more question. it’s been recommended to use the “screen” command to run the Preview Generation process in the background while in ssh. though the “screen” command cannot be found in snap. I will have to apt-get it. Is it fine to do so in nextcloud box [which is essentially an ubuntu snappy core]?

**Comment by kyrofa** [comment]
Yeah it's installed, but it's not available to the rest of the system like that. To run `occ` in the snap, you run it like this

    $ sudo nextcloud.occ preview:generate-all

No users or paths to worry about.

> One more question. it’s been recommended to use the “screen” command to run the Preview Generation process in the background while in ssh. though the “screen” command cannot be found in snap. I will have to apt-get it. Is it fine to do so in nextcloud box [which is essentially an ubuntu snappy core]?

I'm afraid you can't `apt-get` anything on Ubuntu Core: it's snaps-only.

**Comment by coderInCape** [comment]
Thank you @kyrofa 
The "nextcloud.occ" totally replaced the php and occ locations in the command... nice 
and it's alright. I can live without "screen" command. I can wait for "preview:generate-all" to do its job 

Thank you
