### ISSUE TITLE
Port configuration fails on arch linux

### ISSUE THREAD

**Issue by a-m-s** [nextcloud/nextcloud-snap#366]
I installed snap 11.0.5snap1, and followed the "set" instruction, but the open port has not changed. The configure hook appears to run "successfully". The "snap get" command returns the value I set. I tried disable and enable, but still no joy.

Nextcloud is running just fine, albeit on port 80.

I happen to be running snap on Arch, if that makes a difference.

**Comment by kyrofa** [comment]
I've investigated this. First of all, this is not particularly helpful:

```
$ snap version
snap    unknown
snapd   unknown
series  16
arch    unknown
kernel  4.13.4-1-ARCH
```

Worth logging a bug, I think. However, I was able to determine that it's earlier than v2.27, where support was added for running `snapctl` outside of hooks, with this:

```
$ snap run --shell nextcloud.enable-https
snapctl get ports
error: error running snapctl: cannot get without a context
```

That's the issue, then: Apache can't actually obtain the port you set via `snapctl`, so it continues to use the default: 80. Arch needs an updated snapd.

**Comment by kyrofa** [comment]
Yep, [v2.26.1](https://www.archlinux.org/packages/community/x86_64/snapd/).

**Comment by a-m-s** [comment]
Hum, Arch snapd package was last updated Sept 12th, but has had an out-of-date flag since July. The maintainer is also listed as "Orphan". Not ideal.

Thanks for investigating this.

**Comment by kyrofa** [comment]
I was told snapd has been updated in arch. Is this issue now fixed?

**Comment by a-m-s** [comment]
It does appear to have a new maintainer and recent updates:

```
$ snap --version           
snap    2.31.1-1
snapd   2.31.1-1
series  16
arch    
kernel  4.15.3-2-ARCH
```

I've tested the "set" command, and port assignment seems to be working properly.
