### ISSUE TITLE
Are snaps production ready?

### ISSUE THREAD

**Issue by sempervictus** [nextcloud/nextcloud-snap#367]
So given the v12 issues and repeated breakage of snapd images, I'm starting to wonder if the packaging and execution mechanism is ready for prime time. Is this effort an official next cloud packaging and execution approach, or a spare time project? I'm not dockers biggest fan, but they seem to be much more up to date and much less broken on that end. Is that the officially supported container path, or are both approaches first order members of the ecosystem? If docker is the way, is there a migration procedure documented between the two?

**Comment by kyrofa** [comment]
I suppose it depends on your usage. I personally use it in production, so I'd say yes.

That said:

1. The v12 issues are due to breakage in Nextcloud itself, not the snap.
2. What is this "repeated breakage of snapd images" of which you speak?

**Comment by SkyWheel** [comment]
@sempervictus , I'm using snaps for production and home purposes. And if home using is OK, I don't have control on snap updates, so, I believe snaps are not production-ready. But it is just my opinion.
Migrating to docker or standalone server of my production installation is in my plans. At the same time I am pretty happy with home installation.
So, I'm very interested in a way of migration from snap to standalone server/docker (and back) as well.

**Comment by sempervictus** [comment]
+1 to a migration/export function. I imagine you can federate, but a direct CLI tool would be grand.

**Comment by kyrofa** [comment]
This is not really an issue, so closing.
