### ISSUE TITLE
Apache Virtualhost file

### ISSUE THREAD

**Issue by BrechtLapage** [nextcloud/nextcloud-snap#368]
My admin panel of Nextcloud shows this:
> The "Strict-Transport-Security" HTTP header is not configured to at last "15552000" seconds. For enhanced security we recommend enabling HSTS as described in our security tips.

I want to enable HTTP Strict Transport Security, but I'm having trouble finding the apache virtual host file, I don't think it's there actually.

Thanks in advance for the help!

**Comment by kyrofa** [comment]
Hey @BrechtLapage, thanks for logging the issue! HSTS is automatically enabled, but only if it _should_ be enabled. There are two situations when this is the case:

1. You used `nextcloud.enable-https lets-encrypt`
2. You used `nextcloud.enable-https custom -s`

In all other situations (self-signed certs, or custom certs where you did not request that it be enabled), HSTS is (and should be) disabled. May I ask how you enabled HTTPS?

**Comment by BrechtLapage** [comment]
Hey,
I'm using a self-signed certificate and mistakenly thought I could enable HSTS.

Thanks for your reply!

**Comment by kyrofa** [comment]
Yeah you'll run into problems trying to enable HSTS with self-signed. For example, Firefox will no longer allow you to add exceptions for it, etc. They aren't compatible.

**Comment by BlueNinja0** [comment]
I have this same problem.

I installed Nextcloud via snap on a clean Ubuntu and enabled HTTPS with self-signed certificate through the command:
`nextcloud.enable-https self-signed`

And now I get I have this message on the Admin settings:

> The "Strict-Transport-Security" HTTP header is not configured to at least "15552000" seconds. For enhanced security we recommend enabling HSTS as described in our security tips.

**Comment by BlueNinja0** [comment]
Shouldn't HSTS be disabled when using the `nextcloud.enable-https self-signed` command then?

**Comment by kyrofa** [comment]
[It is](https://github.com/nextcloud/nextcloud-snap/blob/master/src/apache/conf/ssl.conf#L164), hence the warning :stuck_out_tongue: . Nextcloud doesn't like it, nothing we can do about that.

**Comment by BlueNinja0** [comment]
I understand now! Thanks! :)
