### ISSUE TITLE
Enabling emoticon support

### ISSUE THREAD

**Issue by stevenandree** [nextcloud/nextcloud-snap#369]

**Comment by stevenandree** [comment]
Hi, having a constant error in enabling sms sync off and to the server. I have done some digging and it appears to be linked to enabling utf8mb4 support. I was going to have a dig and see if I could edit the myself conf, but I wasn't sure where to find it in the snap.

Issue was originally opened https://github.com/nerzhul/ownCloud-SMS-App/issues/135

**Comment by stevenandree** [comment]
Sorry edit mysql conf

**Comment by stevenandree** [comment]
Link to Nextcloud implementation instructions were here https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html
I'm happy to test on my set up, was just hoping to get some feedback from someone on where the configuration file was in the snap

**Comment by kyrofa** [comment]
Hey @stevenandree, thanks for logging an issue! Quick guide for you (note that this is, of course, experimental, until it's been stabilized in Nextcloud):

First, change database character set and collation:

```
$ sudo nextcloud.mysql-client
mysql> ALTER DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```

Then set `mysql.utf8mb4` to true in Nextcloud:

```
$ sudo nextcloud.occ config:system:set mysql.utf8mb4 --type boolean --value="true"
```

And finally apply the new settings to existing tables with:

```
$ sudo nextcloud.occ maintenance:repair
```

**Comment by stevenandree** [comment]
Thanks @kyrofa works a treat and no issues! Have been using the snap for a long time now and that has been my only issue to sync up with all the extra apps on my phone! Thanks for your work!

**Comment by kyrofa** [comment]
Thanks for letting me know, @stevenandree! I appreciate your using it :smile: . Please let me know if you have any other issues.
