### ISSUE TITLE
phpredis isn't found

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#370]
**This only applies to new and daily builds (not stable ones)**.

Once the admin account is created, Nextcloud fails to find Redis. This is due to the version check-- for some reason, phpredis changed the tag so that the version was `develop`, and Nextcloud compared that to its minimum supported version of 2.2.5 and found it lacking.

**Comment by SkyWheel** [comment]
@kyrofa , I have the same nasty issue.
Because of the issue Web page shows 503 error...
Only reverting to the working Nextcloud-snap from 14/10/2017 helps to resolve the issue.
Looking forward to move to stable version 12...

**Comment by SkyWheel** [comment]
@kyrofa , btw when to expect the 12/edge snap with the fix? Thanks.

**Comment by kyrofa** [comment]
@SkyWheel it'll be updated tomorrow automatically with the fix.

**Comment by SkyWheel** [comment]
@kyrofa , that's good news! Thanks!
