### ISSUE TITLE
Download file as *.zip never be downloaded completely.

### ISSUE THREAD

**Issue by karpaz** [nextcloud/nextcloud-snap#382]
Hello
I have problem, when i click to download from website i tried it locally download, and from external domain, both doesn’t work etc. 150 photography (330Mb) that convert it to *zip file, i click on save file, but the file never save complete, i download only (etc150Mb). Never download full file, where can be the problem ?
```

Iam using Nextcloud snappy ubuntu (nextcloudBOX)
Version: 11.0.5 STABLE
HW: Raspberry pi 3 type B
```

VIDEO: https://youtu.be/NKS7X7SzsuI

**Comment by kyrofa** [comment]
Hey there @karpaz, thanks for logging an issue!

I'm not sure how Nextcloud builds the .zip, but I suspect it's in RAM, and you're running out of it. To make sure this is the case, can you make it happen again and then capture the state of the logs? This script will do it:

https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts

**Comment by karpaz** [comment]
Em, sorry Iam newbie in making posts, and maybe i don't understand your script. Iam also newbie in linux 😀 
```
Screenshots after tried to download file in *zip
```
PIC1 [https://imgur.com/a/nmXW8](url)
PIC2 [https://imgur.com/a/9lZP7](url)

**Comment by kyrofa** [comment]
Hmm, yeah sounds like you're starving MySQL out. Just to sanity check: can you download a zip of a smaller directory?

**Comment by karpaz** [comment]
Yea, 20Mb zip is downloaded sucefully. Any fix for that problem, or have this issue every NextcloudBOX ? 😞

**Comment by kyrofa** [comment]
Yeah, not a lot we can do for such RAM-constrained devices, I'm afraid :( .

**Comment by kyrofa** [comment]
Do you have shell access to the box? You could try creating a swapfile.

**Comment by karpaz** [comment]
Yea, i have SSH to the box, but i don't know hot to make swapfile and absolutely don't know how to do it in snap

**Comment by kyrofa** [comment]
Sorry for the tremendously late reply. Here's a [guide for how to enable a swapfile](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04). I'm going to go ahead and close this issue as I believe the question was answered. Feel free to continue discussion here.
