### ISSUE TITLE
Symlink to access data on disk

### ISSUE THREAD

**Issue by dekkerj1** [nextcloud/nextcloud-snap#387]
Hi,
I've installed Nextcloud  11.0.5snap2 on Mint 18.2. Removable media is enabled.
My question: Is it possible to access data with Nextcloud on a different place at the hard disk (in my case /data/owncloud/data on sda5) by using a symlink? I've tried several options, without success.
1. First I tried without a symlink and modified the config.php
* modified config.php
// ...
'datadirectory' => '/data/owncloud/data',
// .
But with no success. chown -R root:root . didn’t help.
Error in the browser: “Data directory (/data/owncloud/data) is not valid, verify .ocdata is in the root. (dutch message translated)
2.Then I tried to achieve this by putting back
// ...
'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',
// .
to the original setting and by making the following symlink:
ln -s /data/owncloud/data/jaap/files /var/snap/nextcloud/common/nextcloud/data. No success. 
chown -R root:root . didn’t help.

3. Then I followed #150:
modified config.php
// ...
'datadirectory' => '/media/nextcloud',
// .
sudo mv /var/snap/nextcloud/common/nextcloud/data /media/nextcloud
ln -s /data/owncloud/data/jaap/files /media/nextcloud/jaap/files/ocdocs
No errors, but I didn’t see the folder ocdocs in the Nextcloud browserinterface.
I tried with sudo  /snap/bin/nextcloud.occ files:scan –all No errors, but also no folders ocdocs after this.

Maybe I’m trying to do something that’s not possible at all.
Thanks in advance for your help.

**Comment by kyrofa** [comment]
No, the confinement follows symlinks. You can, however, bind-mount.

**Comment by dekkerj1** [comment]
Thanks for your suggestion. Bind-mount works. Following the above example:
mount --bind /data/owncloud/data/jaap/files  /var/snap/nextcloud/common/nextcloud/data/jaap/files
and in /var/snap/nextcloud/current/nextcloud/config/config.php: 
'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',

The symlink however did not work. Maybe because the confinement  doesn't  follow synlinks between different partitions? (/data/owncloud/data/jaap/files is on /dev/sda6 and /var/snap/nexctloud on /dev/sda5)

**Comment by kyrofa** [comment]
Close, but not quite. The `removable-media` plug being connected grants access to /media/*, and that's it. AppArmor is smart enough to know that a symlink you place in /media/foo pointing to /data means it's trying to access /data, not /media/foo. However, actually mounting something there is perfectly fine.
