### ISSUE TITLE
Use cron rather than Ajax cron

### ISSUE THREAD

**Issue by thomascobb** [nextcloud/nextcloud-snap#39]
I'm new to nextcloud, but my understanding is that if you're not going to visit the webpage regularly then you should use cron or web cron rather than Ajax cron. I am mainly planning on using the desktop client for sync so I think this applies to me? I had a look at how you've done the renew certificates, and I think a similar approach running cron.php with 15 minute sleeps might be a good idea? Do you think this would work? I could try to do this and make a pull request if that's helpful.

**Comment by kyrofa** [comment]
You're absolutely right. I've actually tried to do this already, but it seems impossible to do before a user is created. This should be exposed by Nextcloud in its autoconfig, but that doesn't seem to be supported. Likewise occ doesn't have it unless a user is created. This needs some upstream work.

**Comment by oparoz** [comment]
Well, the cron could be set up, along with another one which calls the required occ command to make the change and then removed the line from crontab, no?

**Comment by kyrofa** [comment]
Not really... it's more like cron lite. We wouldn't be able to disable the service like that.

**Comment by thomascobb** [comment]
What about an enable-cron script that ran the right occ command then kicked off a service that ran cron.php every 15mins? Or just expose cron.php and include some instructions on how to add it to the system cron so it runs as the right user?

**Comment by kyrofa** [comment]
Hmm. There's no downside to running cron.php periodically even if the event loop is set to Ajax, right? Which means we could run that service and just tell people to switch from Ajax to cron in the admin interface. Not ideal, but a good part toward hopefully bring able to set via autoconfig in the future. And no SSH required.

**Comment by thomascobb** [comment]
Sounds like a plan, should I have a go at it? It might be a couple of weeks til I get round to it, but it would be interesting to find out how to make a snap...

**Comment by kyrofa** [comment]
> Sounds like a plan, should I have a go at it?

Sure, take a crack at it! Please let me know if you don't think you'll be able to, though, and I can do it.

**Comment by thinking-aloud** [comment]
Meanwhile, how can I setup a cron manually inside the nextcloud snap package?

**Comment by thomascobb** [comment]
Ok, I made some changes to the help text on the enable-https script just to check that I had a working system. I've submitted it as a pull request in case it's useful. I'll try the cron change next...

**Comment by thomascobb** [comment]
I've had a go at this in #42

**Comment by thinking-aloud** [comment]
@thomascobb thx, sounds good. I will wait till that got merged into the release and NC 10 is in snap. After that I might replace my beloved ownCloud with it. Until then, I think its more pain than gain, considering that NC does not differ too much from OC jet.

**Comment by kyrofa** [comment]
FYI, it seems this will never be supported by `autoconfig.php` or anything else: https://github.com/nextcloud/server/issues/3732
