### ISSUE TITLE
"Non UTF-8 charset for MySQL/MariaDB database detected!"

### ISSUE THREAD

**Issue by WereCatf** [nextcloud/nextcloud-snap#393]
Apparently, while I was sleeping, the Snap-version of Nextcloud that I am using got updated to v12.0.4 and I got greeted with the message in the title. The link to learning how to convert the database to utf-8 isn't exactly helpful, I have no idea how to apply that to the Nextcloud-database. Why didn't the upgrader convert such things automatically, and is this a big issue? How to actually convert the database?

**Comment by kyrofa** [comment]
You're the first to report this. Did you by any chance enable [4-byte support](https://docs.nextcloud.com/server/12/admin_manual/configuration_database/mysql_4byte_support.html) in your database?

**Comment by WereCatf** [comment]
I installed the Snap-package, it's the Snap-package that sets up the database. I haven't touched anything, so everything is how the package set it up.

**Comment by kyrofa** [comment]
How odd. Which version were you on before the update occurred?

**Comment by WereCatf** [comment]
I don't remember. v11something, whatever was the latest previous one. Snap-packages are updated automatically, so I have had no reason to pay much attention to the version-number.

**Comment by kyrofa** [comment]
Not sure what the deal is, but my research leads me to believe this should fix it:

```
$ sudo nextcloud.mysql-client
mysql> ALTER DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```

Then set `mysql.utf8mb4` to true in Nextcloud:

```
$ sudo nextcloud.occ config:system:set mysql.utf8mb4 --type boolean --value="true"
```

And finally apply the new settings to existing tables with:

```
$ sudo nextcloud.occ maintenance:repair
```

**Comment by WereCatf** [comment]
@kyrofa Those instructions apparently converted only some of the database. The RSS-reader app called "News" that I use still complains about the non-UTF8-thing.

**Comment by kyrofa** [comment]
Yeah, sounds like News does some sort of auto-detection that we're failing here ([relevant bug](https://github.com/nextcloud/news/issues/176#issuecomment-306210977)). I'm not sure there's much we can do, here.

**Comment by kyrofa** [comment]
Note that if you require this app to work you can revert back to v11 and stay on the 11/stable channel:

    $ sudo snap revert nextcloud # Gets you back to v11
    $ sudo snap refresh nextcloud --channel=11/stable # Keeps you on v11

**Comment by WereCatf** [comment]
Well, I'll have to think about what to do next, then. That said, should I leave this issue open or close this? I mean, I feel like Nextcloud Snap-package should automatically fix the non-UTF8-error or at least the error-message should point to proper instructions for people to fix it themselves, instead of just leaving it like it is now.

**Comment by kyrofa** [comment]
From that issue I linked, that error seems to come from News, not Nextcloud, and certainly not the snap.

**Comment by WereCatf** [comment]
No, you're misunderstanding. The issue originally appeared everywhere, now it only appears in the News-app. The instructions you posted earlier fixed the errors elsewhere. I am *NOT* talking about the News-app right now, I am talking about the whole shebang.

**Comment by kyrofa** [comment]
Right, but I _am_ talking about the News app. The string "Non UTF" isn't in the upstream Nextcloud codebase at all. It's in the News app, which apparently requires UTF-8 support now:

    https://github.com/nextcloud/news/blob/0fa82e88d7150f2160bd8a0c08c8869f80f6d82d/templates/part.content.warnings.php#L29

**Comment by kyrofa** [comment]
It's pretty easy to revert back to v11 if you need to. Note that this will throw away any database modifications made during your stay in v12 (calendar entries you added since the upgrade, etc), but the raw data will not be touched (pictures, etc.)

    $ sudo snap revert nextcloud
    nextcloud reverted to 11.0.5snap2

Then refresh to the `11/stable` channel to make sure you don't get v12 updates:

    $ sudo snap refresh nextcloud --channel=11/stable
    nextcloud (11/stable) 11.0.5snap2 from 'nextcloud' refreshed
    $ snap info nextcloud
    <snip>
    tracking:                   11/stable
    <snip>

**Comment by pachulo** [comment]
Hey @WereCatf ! I just wanted to comment that I was seeing the same error message, but after using the instructions @kyrofa mentioned in https://github.com/nextcloud/nextcloud-snap/issues/393#issuecomment-351279079 and restarting my server, I'm not seeing it anymore in the News app.

**Comment by WereCatf** [comment]
@pachulo Yeah, I got it fixed, too. I just didn't comment here anymore, because this issue is already closed.
