### ISSUE TITLE
12.0.4 loading assets over http instead of https

### ISSUE THREAD

**Issue by gmask** [nextcloud/nextcloud-snap#395]
Some assets (logo image, for example) are being loaded over http instead of https, even though the domain is forced to https via Apache2 proxy. This was a non-issue in the prior version and only appeared upon update to 12.0.4 (snap version).

**Comment by kyrofa** [comment]
Very interesting! I'm not seeing this issue on the main login page. Where are you seeing it?

**Comment by gmask** [comment]
After logging into the web app: at first the images were simply not loading, but that's because I had HTTPS Everywhere addon enabled. Login page seems to work fine.

![SSL warning image](https://i.imgur.com/Wmbagjf.jpg)
![Devtools image](https://i.imgur.com/bafZnbY.jpg)

**Comment by kyrofa** [comment]
I have HTTPS Everywhere as well, and all my assets are loading over HTTPS. Here's my CSS of the same thing:

```
#header .logo-icon {
    display: inline-block;
    background-image: url('https://my-domain.com/core/img/logo.svg?v=0');
    background-repeat: no-repeat;
    background-position: center center;
    background-size: contain;
    width: 62px;
    height: 34px;
}
```

I have no clue what's happening there. How did you enable HTTPS?

**Comment by gmask** [comment]
Only by the apache's proxy via a rewrite rule: I couldn't find any settings in the Nextcloud admin panel to enforce https. Is there one?

**Comment by kyrofa** [comment]
Ah, so you have the snap behind a proxy with HTTPS enabled as opposed to enabling HTTPS in the snap itself? I haven't tried that.

**Comment by kyrofa** [comment]
You might try using `'overwriteprotocol' => 'https'` in your config.

**Comment by gmask** [comment]
@kyrofa That fixed it, thanks! I wonder why it isn't just loading over the same protocol being used to access the instance?

**Comment by kyrofa** [comment]
Ah very good! I'm not sure, something must have changed in upstream Nextcloud, but it sounds like that overwrite flag is all one needs. I'll remember that. Feel free to log a bug against upstream Nextcloud if you think something should change there, but I'll go ahead and close this here. Feel free to continue discussions, though :) .
