### ISSUE TITLE
Cannot access to my NC server neither locally

### ISSUE THREAD

**Issue by mauricioduarte01** [nextcloud/nextcloud-snap#408]
Hello,
I just wanted to report that everything was working good here for me using my snaps NC server in my Raspbi Pi3 with duckdns. But when I tried to enter to upload some files a few minutes ago I was unable to connect to it anymore. Even direct using my local IP address without dns.. 
I dont know what I have to do to debug this issue. 

I tried to connect from my desktop, laptop, macbookpro, NC Appimage.. no luck. I can connect to my Pi3 using samba, ssh without any issues. 

Thank you and sorry for the lack of information. 

snap list
Name       Version      Rev   Developer  Notes
core       16-2.29.4.2  3606  canonical  core
nextcloud  12.0.4snap1  4378  nextcloud  devmode

UPDATE: I dont know how this happened but for some reason I entered my router to check the forwared ports, and the port 80 and 443 were configured to another ip address different than I used with my NC device. I really dont understand how something like that could happen after almost 3 months of using NC without any issues. Anyways, I just changed the IP's and now everything is working well again. Thank you and sorry for opening this issue ticket.

**Comment by kyrofa** [comment]
Make sure you set your Nextcloud box to have a static IP address from your router, otherwise upon reboot it may not get the same address.

Thanks for updating the issue, I'll go ahead and close it now.
