### ISSUE TITLE
Maintenance mode has no effect

### ISSUE THREAD

**Issue by MrksKwsnck** [nextcloud/nextcloud-snap#409]
For doing some administrative tasks I want to put my Nextcloud instance into maintenance mode. My Nextcloud is a Nextcloud Box running Ubuntu Core on a Raspberry Pi 3 with the Nextcloud snap.

```
$ uname -a
Linux nextcloudbox 4.4.0-1030-raspi2 #37-Ubuntu SMP Thu Oct 20 15:06:25 UTC 2016 armv7l armv7l armv7l GNU/Linux

$ snap list
Name           Version       Rev   Developer  Notes
core           16-2.30       3750  canonical  core
nextcloud      12.0.4snap1   4378  nextcloud  -
pi2-kernel     4.4.0-1030-3  22    canonical  kernel
snapweb        0.26-10       305   canonical  -
wdl-nextcloud  16.04-0.5-6   9     canonical  gadget
```

Unfortunately, the maintenance mode turned on seems to not have any effect on my *Nextcloud Box*. Still I can log into my Nexcloud via web browser. All apps are active and also my desktop syncing client is syncing farther.

---

For turning the maintenance mode on/off I am using the commandline.

```
$ sudo nextcloud.occ maintenance:mode --on
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Maintenance mode enabled
```

The current state of the maintenance mode I can also confirm.

```
$ sudo nextcloud.occ maintenance:mode
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Nextcloud is in maintenance mode - no app have been loaded

Maintenance mode is currently enabled
```

Also the `config.php` file was edited properly.

```php
<?php
$CONFIG = array (
  ...
  'maintenance' => true,
  ...
);
```

But, what appears strange to me: After a reboot of the system the maintenance mode was turned off automatically, even inside the `config.php` file was reedited back to `'maintenance' => false`. So, am I missing something?

**Comment by kyrofa** [comment]
You're not missing anything, I'm afraid this is a [known bug](https://github.com/nextcloud/nextcloud-snap/issues/202). It falls into the code path where the snap thinks it just tried to upgrade but failed, and is trying again. It needs to be smarter about it.

**Comment by MrksKwsnck** [comment]
Ah, snap :-(

Anyway thanks for cross referencing the issues.
