### ISSUE TITLE
backup all

### ISSUE THREAD

**Issue by zuosc** [nextcloud/nextcloud-snap#413]
now,I have two VPS.

one of them is installed nextcloud-snap , but this VPS I dot not want  use it，because I have a better one.

so,What should I do to  back up all my data to another？

Can you help me?

**Comment by kyrofa** [comment]
I don't quite understand. Are you saying you want to migrate from one Nextcloud snap instance to another Nextcloud snap instance on another server? Or from a snap to a from-source installation? Or the other way around?

**Comment by zuosc** [comment]
@kyrofa   emmmm. sorry,  my English is poor...

I mean  another server。

**Comment by kyrofa** [comment]
Okay, so you have two servers. Do they both have the snap? Or are you wanting to migrate from the snap to a from-source installation? Or are you wanting to migrated from-source to the snap?

**Comment by shaokuuipo** [comment]
@zuosc 
说中文啊，你是想迁移数据到另外一台全新的服务器，还是要合并两台服务器的数据？

**Comment by zuosc** [comment]
@shaokuuipo   迁移数据到另外一台全新的服务器

**Comment by kyrofa** [comment]
@zuosc I think what you're saying is that you want to migrate from the snap on an old server to another server. Do you also have the snap installed on the new server?

**Comment by shaokuuipo** [comment]
@zuosc nextcloud.mysqldump命令导出导入数据库，然后把数据文件夹/var/snap/nextcloud/common/nextcloud/data全部内容拷贝过去。

**Comment by zuosc** [comment]
@kyrofa   😂not yet. both servers are Ubuntu 16.04, so the  new server can be very easy to install  the snap。


@shaokuuipo   好的，我晚上下班之后尝试一下。非常感谢！

**Comment by kyrofa** [comment]
Okay, indeed, migrating between snaps shouldn't be too hard (and an export/import script is something we've been wanting to do for a while). Is your data contained in the default location, or did you connect, say, the `external-media` plug and put it on another disk/partition?

**Comment by kyrofa** [comment]
(note that you may not need to dump the database as @zuosc says, you might be able to just get away with tarring up `/var/snap/nextcloud/current/`, which contains the database.)

**Comment by 19wolf** [comment]
To make sure I'm clear on this: If I want to migrate or store a backup of nextcloud, all I need to do is copy /var/snap/nextcloud/current/ to another location, and then it can be copied back in place on a fresh installation? So example code:

```
$snap stop nextcloud
$rsync -a /var/snap/nextcloud/current/ ~/backup/nextcloud
$snap delete nextcloud
$snap install nextcloud
$snap stop nextcloud
$rsync -a ~/backup/nextcloud/ /var/snap/nextcloud/current
$snap start nextcloud
```
...and everything should work?

**Comment by kyrofa** [comment]
Eh, not quite. Try this (remember the trailing slashes are important for rsync):

`$ sudo snap install nextcloud`

Visit it, create your admin user, upload a few files. Install the calendar app, schedule some events. Now stop the snap:

`$ sudo snap disable nextcloud`

This actually removes the `current` symlink so we'll need to use the revision instead, but that's okay. Now make a backup of the raw data (this is the default place for it, but you can also put it on e.g. removable media):

`$ sudo rsync -ah /var/snap/nextcloud/common/ ~/backup/nextcloud_data`

Now grab the database and all the configuration:

`$ sudo rsync -ah /var/snap/nextcloud/4371/ ~/backup/nextcloud_config`

Now remove the snap:

`$ sudo snap remove nextcloud`

Install it again:

`$ sudo snap install nextcloud`

Disable it:

`$ sudo snap disable nextcloud`

Copy data back:

`$ sudo rsync -ah ~/backup/nextcloud_data/ /var/snap/nextcloud/common/`

Copy config back:

`$ sudo rsync -ah ~/backup/nextcloud_config/ /var/snap/nextcloud/4371/`

Enable nextcloud:

`$ sudo snap enable nextcloud`

You should now be able to visit it again, login using your old login, see the files you uploaded, and see the calendar entries you made. i.e. you should be back to exactly where you were.

CAVEATS: This assumes you're not moving across architectures, and is only recommended if you're migrating to and from the same snap revision.

**Comment by 19wolf** [comment]
Followed your instructions, 502 Bad Gateway error

**Comment by Seferi** [comment]
Would this kind of backup/restore work between snap and docker nextcloud container ?

**Comment by kyrofa** [comment]
> Edit: needed sudo snap set nextcloud ports.http=81 since I was running on 81 instead of 80

Ooo, configuration, didn't even think about that! Good catch.

**Comment by kyrofa** [comment]
> Would this kind of backup/restore work between snap and docker nextcloud container ?

I'm afraid not. The Docker container is organized completely differently. You an still use the relatively typical "export database, import database, copy raw data over, copy Nextcloud config over" flow though.

**Comment by 19wolf** [comment]
> > Edit: needed sudo snap set nextcloud ports.http=81 since I was running on 81 instead of 80
>
> Ooo, configuration, didn't even think about that! Good catch.

I didn't think it would matter since the config file said port 81, but I guess snaps need to be told explicitly that kind of thing. Also same with connecting external media

**Comment by chrauscher** [comment]
This may be a good start: https://gist.github.com/kapcom01/ad2c279750830038e8fa3c39ddf2ef5b

**Comment by Seferi** [comment]
@kyrofa Hi mate, I'm trying to migrate this way between nextcloudbox and intel Nuc. I'm getting a permission error. Any ideas?

 rsync -ah user@192.168.158.42:/var/snap/nextcloud/common/ ~/Documents/nextcloud-apps
user@192.168.158.42's password: 
rsync: opendir "/var/snap/nextcloud/common/nextcloud" failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1655) [generator=3.1.1]

**Comment by kyrofa** [comment]
Hey there @Seferi. Those files are owned by root, but you're SSHing in as a user, it seems. I suggest simply tarring it up or something, and making the resulting tar accessible to the user, pulling it over, and extracting it.

**Comment by kyrofa** [comment]
Please see #688 for a better way to export/import backups of the snap.
