### ISSUE TITLE
Background image change

### ISSUE THREAD

**Issue by corwin78** [nextcloud/nextcloud-snap#414]
Hello guys, such silly issue - I can't change background picture for the login screen. Other theming options are working fine. After uploading new background picture, I can see that it is located in theming folder on the server, but logins screen picture remains default. Interesting is, that in the mobile app for Android I can see new picture used for menu background.

So, this is really low priority, but would be nice have it solved ;-)

**Comment by kyrofa** [comment]
This is a dupe of #394. I'm afraid it's a regression from v11 to v12 that we need to investigate. More details on that issue (I'll close this one).
