### ISSUE TITLE
trusted_domains not working

### ISSUE THREAD

**Issue by noobpurple** [nextcloud/nextcloud-snap#415]
Currently trying to configure nextcloud on a Digital Ocean droplet running Ubuntu 16.04. I can access the website from the domain that points to the server, but it says that the domain isn't listed in trusted_domains. On my end, SSH'd into the server, running `nextcloud.occ config:system:get trusted_domains` shows the domain listed, and it's the same domain that it's telling me to add to the list.

**Comment by kyrofa** [comment]
How did you add the trusted domain in the first place? Any chance the ports have changed? Do you have something proxying to the snap?

**Comment by noobpurple** [comment]
I used `nextcloud.occ config:system:set trusted_domains` to set it. Turns out I had to restart Nextcloud to get the changes to take effect. The documentation on DigitalOcean was missing that last bit. Managed to figure out the problem the other night, but I forgot to comment back and close the issue.

**Comment by kyrofa** [comment]
Oh very good! Thank you for updating the issue :) .
