### ISSUE TITLE
Let's Encrypt and reverse proxy

### ISSUE THREAD

**Issue by 19wolf** [nextcloud/nextcloud-snap#422]
I'm not sure this is so much an issue so much as more of a question (maybe it could be added to the documentation), but I'm running the nextcloud/12 snap on one machine, and an nginx reverse proxy on a different machine. It all worked well, I pointed cloud.domain.name to the machine with the snap on port 80 and it works fine, and now I'm trying enable let's encrypt, but I'm not sure what I need to do in my reverse proxy to make it work. It seems to work until I connect to the server and I have an invalid certificate.

**Comment by 19wolf** [comment]
Also, I can't connect to the web interface because 192.168.26.54 is not a trusted domain (which is the IP the server is running on)

**Comment by kyrofa** [comment]
You're visiting the domain, but Nextcloud is only seeing the IP? Make sure your proxy is passing that info along.

> It seems to work until I connect to the server and I have an invalid certificate.

How are you running `nextcloud.enable-https`? What reason does the browser give regarding its invalidity?

**Comment by 19wolf** [comment]
On Ubuntu 16.04 host:
```
$ sudo nextcloud.enable-https lets-encrypt
In order for Let's Encrypt to verify that you actually own the
domain(s) for which you're requesting a certificate, there are a
number of requirements of which you need to be aware:

1. In order to register with the Let's Encrypt ACME server, you must
   agree to the currently-in-effect Subscriber Agreement located
   here:

       https://letsencrypt.org/repository/

   By continuing to use this tool you agree to these terms. Please
   cancel now if otherwise.

2. You must have the domain name(s) for which you want certificates
   pointing at the external IP address of this machine.

3. Both ports 80 and 443 on the external IP address of this machine
   must point to this machine (e.g. port forwarding might need to be
   setup on your router).

Have you met these requirements? (y/n) y
Please enter an email address (for urgent notices or key recovery): ~~~~~
Please enter your domain name(s) (space-separated): cloud.domain.name
Attempting to obtain certificates... done
Restarting apache... done
```

On the nextcloud app on Mac:
```
Cannot connect securely to cloud.domain.name:
The host name did not match any of the valid hosts for this certificate
with Certificate cloud.domain.name
Organization: <not specified>
Unit: <not specified>
Country: <not specified>
Fingerprint (MD5): fc:86:04:20:74:5c:f4:0f:52:77:31:a3:62:61:30:7b
Fingerprint (SHA1): fa:61:93:6b:a3:2d:4f:20:1a:34:ab:21:2b:42:6e:ed:cf:e3:eb:6a

Effective Date: Mon Jan 22 14:32:18 2018 GMT
Expiration Date: Sun Apr 22 14:32:18 2018 GMT
Issuer: Let's Encrypt Authority X3
Organization: Let's Encrypt
Unit: 
Country: US
```

On cloud.domain.name:
https://www.dropbox.com/s/3paoszrq6gai9f0/Screenshot%202018-01-22%2010.35.58.png?dl=0
https://www.dropbox.com/s/sgrxqphwzvye33f/Screenshot%202018-01-22%2010.36.36.png?dl=0


Nginx Proxy:
```
server {
	listen 80;
        server_name cloud.domain.name;
	client_max_body_size 0;
        location / {
            proxy_pass       http://192.168.26.54:81;
	    proxy_set_header host $host;
        }
	listen 443 ssl;

	ssl_certificate /url.crt;
	ssl_certificate_key /url.key;
 }
```

**Comment by kyrofa** [comment]
Ah, looks like nginx has its own cert. Any chance that's the cert your client is seeing?

**Comment by 19wolf** [comment]
Nginx shouldn't have it's own cert, I never set one up. I was just copying from [this reddit post](https://www.reddit.com/r/NextCloud/comments/7n3gup/nextcloud_with_nginx/)

**Comment by olastor** [comment]
@19wolf This the basic config I currently use with a similar setup:
```
server {
  listen 80;
  listen [::]:80;

  server_name domain.tld www.domain.tld;

  # Enforce HTTPS
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name domain.tld www.domain.tld;

  ssl_certificate /etc/letsencrypt/live/domain.tld/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/domain.tld/privkey.pem;

  # Turn on OCSP stapling as recommended at
  # https://community.letsencrypt.org/t/integration-guide/13123
  # requires nginx version >= 1.3.7
  ssl_stapling on;
  ssl_stapling_verify on;

  # Uncomment this line only after testing in browsers,
  # as it commits you to continuing to serve your site over HTTPS
  # in future (see https://serverfault.com/a/784940)
  # add_header Strict-Transport-Security "max-age=31536000";

  # access_log /var/log/nginx/sub.log combined;

  # see http://tom.busby.ninja/letsecnrypt-nginx-reverse-proxy-no-downtime/
  # When using letsencrypt you would use the .well-known directory for verifying that you're
  # the owner of the domain (when getting a new certificate with a command like 
  #   certbot certonly --webroot -w /var/www/ssl-proof/domain.tld/ -d domain.tld
  # ).
  location /.well-known {
    root /var/www/ssl-proof/domain.tld/;
  }

  # set max upload size
  client_max_body_size 512M;
  fastcgi_buffers 64 4K;

  location / {
    # reverse proxy to nextcloud
    proxy_pass           http://localhost:98;
  }
}
```

**Comment by kyrofa** [comment]
Yeah I'm afraid I'm pretty unfamiliar with nginx and its proxying abilities. Once we get this hammered down it'd be nifty to write a quick tutorial on the wiki or something. @olastor any chance you could help with that?

**Comment by olastor** [comment]
@kyrofa Sure, but I'm not very experienced with nginx, as well. But I did the basic setup with nginx reverse proxy and let's encrypt, so I maybe could help with that (most commands are still in my bash history...).

**Comment by 19wolf** [comment]
I updated my nginx config to the same as @olastor has (updated for my domain etc) and had it working, but then I realized I never enabled https on the snap, so I ran `sudo nextcloud.enable-https lets-encrypt` and generated a new(?) cert and put the new(?) cert in place on the proxy server.

However, now, when I go to `cloud.domain.name`, I get redirected to `192.168.1.2`. Any idea what could be happening?

**Comment by olastor** [comment]
@19wolf If the machine running nextcloud is not exposed to the internet, it's not necessary to enable https for the nextcloud instance. In this case only the webserver needs to be configured for ssl and using http for local redirect is fine. Have you changed the `proxy_pass` url in the nginx config to `https` and changed the port to your https port of nextcoud after you ran the `nextcloud.enable-https lets-encrypt` command?

**Comment by mickaelicoptere** [comment]
I face the same problem...
I have nextcloud running on a vm at home which is connected to my vpn running on my vps and use my vpn as a gateway.
My domain name send to my vps who redirects to my nextcloud vm in the vpn's subnet.
Everything was  working fine with http but now i face exactly the same problem as @19wolf.

I generated the lets encrypt cert and private key and found it in `/var/snap/nextcloud/current/certs`.
How can i set up my nginx configuration on my vps to https the whole thing to my nextcloud ?

**Comment by 19wolf** [comment]
I've been rate-limited by letsencrypt, and I'm an idiot and didn't back up my certs... I guess I have to wait a week(?) to be un-rate-limited.

**Comment by 19wolf** [comment]
Update: 
I tried with a certificate generated on my proxy server, then again using @mickaelicoptere's config/method
It's not working. If I try to go to http://cloud.domain.name I get redirected to https://cloud.domain.name and browsers "can't establish a secure connection"

**Comment by mickaelicoptere** [comment]
@19wolf you should generate the certificates on your nextcloud server, not on the proxy server

**Comment by 19wolf** [comment]
I did that, using your method exactly as you wrote it

**Comment by kyrofa** [comment]
I did a little research today and wrote [this wiki page](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy) if anyone finds it helpful. Depending on how you have nginx setup, using the stream block can pass through SSL to the snap allowing it to continue managing certs.
