### ISSUE TITLE
"Request entity too large" for any file over 1MB

### ISSUE THREAD

**Issue by 19wolf** [nextcloud/nextcloud-snap#424]
I've found several articles on this dealing with this, but those answers don't seem to be applicable to the snap, or at least I can't figure out how to change the relevant settings in within the snap.

**Comment by kyrofa** [comment]
Can I see the output of `snap list`, and `snap version`, please?

**Comment by 19wolf** [comment]
```
# snap list; snap version
Name       Version      Rev   Developer  Notes
core       16-2.30      3748  canonical  core
lxd        2.21         5447  canonical  -
nextcloud  12.0.4snap1  4371  nextcloud  -
snap    2.30
snapd   2.30
series  16
ubuntu  16.04
kernel  4.15.0-041500rc7-generic

```

**Comment by kyrofa** [comment]
The snap is setup to handle large files. Any chance you have a proxy in front of it?

**Comment by 19wolf** [comment]
I do

```
server {
        listen 80;
        server_name cloud.domain.name;
       client_max_body_size 1000M; #same thing with or without this line
        location / {
            proxy_pass       http://192.168.1.2:81;
            proxy_set_header host $host;
        }
 }
```

**Comment by Nutomic** [comment]
@19wolf Is that nginx? Works fine for me if I put the `client_max_body_size` inside the `http` block inside nginx.conf.

**Comment by kyrofa** [comment]
Yeah this is due to your proxy, not the snap. Try @Nutomic's suggestion. I'll close the issue as I don't believe it's snap-related, but feel free to continue discussion here.
