### ISSUE TITLE
Help text for enable-https could be clearer

### ISSUE THREAD

**Issue by thomascobb** [nextcloud/nextcloud-snap#43]
I missed the fact that you could run this script without arguments to get a Let's Encrypt certificate. I will submit a PR that tries to improve this...

**Comment by MariusBluem** [comment]
PR merged. Closing. THX! 😉

**Comment by kyrofa** [comment]
This bug is not fixed until the fix has been merged into master-- it has not (need to test and merge the other PR before making the next release). I suggest we leave the bug open until the users see the bug has been fixed. I've made a fix-committed tag to track such a status.

**Comment by kyrofa** [comment]
Note that the issue will be closed automatically due to the commit messages requested in the contribution guide.
