### ISSUE TITLE
Ubuntu 16.04 TLS / Nextcloud Interface not reachable after fail2ban de-installation

### ISSUE THREAD

**Issue by kolmberger** [nextcloud/nextcloud-snap#434]
Hi guys,
I am completely new to Ubuntu and Nextcloud and hope you can help me troubleshoot my problem.
I have had a working installation on my own PC running with DynDns, Nextcloud snap, letsencrypt and ssmtp. Finally, I wanted to install fail2ban. After fiddling around with it, it kinda worked, but not as expected according to the configuration. I decided to remove fail2ban again.

After a a reboot of the server, the Nextcloud interface was not reachable anymore. Though, DynDns is up and running, I cannot even access over my internal networks IP address.
I tried a couple of things with the snap commands, but nothing worked.

Thanks a lot for your instructions on how best to provide you with information so that you can help me on.

**Comment by kolmberger** [comment]
I wanted to add, that this happened twice. After the first occurance, I have just re-installed my system. Now I have exact same behaviour after the second fail2ban installation/de-installation. It seems to be reproducable.

**Comment by kolmberger** [comment]
Could my issue be similar to https://github.com/nextcloud/nextcloud-snap/issues/425?

**Comment by kyrofa** [comment]
Can I please see the output of `sudo netstat -tulpn` ?

**Comment by kolmberger** [comment]
Of course :) 

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:4022            0.0.0.0:*               LISTEN      1039/sshd
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      1471/perl
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1228/apache2
tcp6       0      0 :::4022                 :::*                    LISTEN      1039/sshd
udp        0      0 0.0.0.0:10000           0.0.0.0:*                           1471/perl
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1327/mdns-publisher
udp6       0      0 :::5353                 :::*                                1327/mdns-publisher

**Comment by kyrofa** [comment]
It looks like Apache is listening on port 80. What do you see if you visit port 80 of the server in a browser?

**Comment by kolmberger** [comment]
http://<serverip>:80 brings up the "Apache2 Ubuntu Default Page".

**Comment by kyrofa** [comment]
That means you must have Apache2 installed, which is claiming port 80 (the snap also wants port 80). Either remove the Apache package, or request the snap to change ports.

**Comment by kolmberger** [comment]
I have no idea, why Apache is installed at all. In Ubuntu server setup, I haven't installed it.
Could it have come with another package?

**Comment by kyrofa** [comment]
What does `apt-cache rdepends --installed apache2` say?

**Comment by kolmberger** [comment]
Sorry, I was just executing `apt-get remove apache2*`
Now `apt-cache rdepends --installed apache2` gives:
apache2
Reverse Depends:
Calling http://serverip:80 now brings up Nexcloud interface, redirected to https://
And it says in Chrome "this website is not safe"

**Comment by kolmberger** [comment]
Calling my DNS-URL brings up the expected Nextcloud Interface with login. According to Chrome, the website is safe :)

**Comment by kyrofa** [comment]
Ah, that's okay! So things seem to be working, now?

**Comment by kolmberger** [comment]
as far as I can tell from my beginners' knowledge, yes!
Thank you so much, Kyle. 👍

**Comment by kyrofa** [comment]
My pleasure! I'll go ahead and close this, then, but feel free to reopen (or log another issue) if necessary :smiley: .
