### ISSUE TITLE
Apache2 Ubuntu default page after Ubuntu updates and rebo

### ISSUE THREAD

**Issue by wecreatedigital** [nextcloud/nextcloud-snap#438]
Hi there,

We've had NextCloud for approximately two weeks and over the weekend I updated Ubuntu and rebooted the server. Unfortunately, I see the default Ubuntu splash page when I go to the approved domain. I've been trying to figure out what happened but it is very unclear.

Is there a way to reinstall NextCloud snap without loosing the data? Or can I configure Apache2 again?

Would be grateful for any insight!

Thanks

Dean

**Comment by kyrofa** [comment]
That sounds like you have Apache installed from the archives, and on reboot it claimed port 80 before the snap could. You'll need to either remove Apache, or [change the ports](https://github.com/nextcloud/nextcloud-snap#httphttps-port-configuration) on which Nextcloud listens.

**Comment by wecreatedigital** [comment]
Thanks @kyrofa - I've disabled Apache and a reboot fixed the problem. Many thanks for your help.

**Comment by supra89t** [comment]
Hello, I had an issue today with my Nextcloud snap. It just stopped working and the android app would show no connection and I was not able to access it via the web. I got home and even on the local network it was down. I rebooted the server and still nothing. Refreshed the services manually and still nothing. I thought that perhaps I messed something up while trying to install plex media server snap so I reformatted the server with a clean install Ubuntu server 18.04. 

I installed nextcloud with the sudo snap install nextcloud command and when I try to connect to it on the local network to set it up again I'm only seeing the default apache page. I never installed it and its not on my server. 

Please help.

**Comment by kyrofa** [comment]
There _is_ no default apache page in the snap, which means you also have Apache installed on the system alongside the snap, which won't work (at least, not without changing ports).

**Comment by supra89t** [comment]
I do not have it installed, but now all of a sudden its working fine... perhaps there was a delay for apache to setup?
