### ISSUE TITLE
PHP and Nginx

### ISSUE THREAD

**Issue by patricktokeeffe** [nextcloud/nextcloud-snap#444]
I've installed the Nextcloud Snap on Ubuntu 16.04 (thanks for making it so easy!) but my server hosts other experiments and I'm getting stuck connecting Nginx to php. 

I added the relevant parts from the [admin docs example](https://docs.nextcloud.com/server/12/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-nginx) to my nginx config and received 502 Gateway Error messages when accessing `/nextcloud`. Since there was no `/var/run/php5-fpm.sock` and nothing listening locally:
```
patrick@server:~$ nc -zv 127.0.0.1 9000                                                                                                                     
nc: connect to 127.0.0.1 port 9000 (tcp) failed: Connection refused
```
..I looked for way to connect to the Snap's php instance, and then finally just installed `php-fpm` (v7.0) alongside nginx. Now I receive the cryptically short error message "`File not found.`" when accessing the `/nextcloud` subdirectory. 

Am I missing something easy?

**Comment by kyrofa** [comment]
I'm afraid the snap isn't made to work this way. PHP listens on a unix socket that is by design only accessible to the snap. NGINX isn't really the best reverse proxy, but please see [this wiki page](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy) for some hints about how to do this.

**Comment by patricktokeeffe** [comment]
Thanks @kyrofa, I didn't really think that would work but I was getting desperate. Starting with the stripped down nginx config from the wiki page instead of the admin docs, I've created a working setup. (Trailing. Slashes. 😐)

**Comment by patricktokeeffe** [comment]
Yes of course. I don't see edit available so here's a new section:

-----

## NGINX subfolder

If you already have a working SSL-encrypted Nginx server, it's possible to proxy the Nextcloud Snap in a subdirectory (e.g. `https://your.tld/nextcloud`). 

First, the Snap must be configured to use alternate ports. It's also a good idea (though not reqd) for the Snap to only listen on `localhost`:
```
$ sudo snap set nextcloud ports.http=81 ports.https=444
$ sudo snap set nextcloud listen=127.0.0.1
```

Next, the Nextcloud config needs to reflect the proxying situation:
```
$ sudo nano /var/snap/nextcloud/current/nextcloud/config/config.php 
```
* set `overwrite.cli.url` to the complete public path: e.g. `https://your.tld/nextcloud`
* set `overwritewebroot` to the relative public path: e.g. `/nextcloud`
* set `overwriteprotocol` to `https` (because Nginx will serve over https)
* *(other proxy-related settings exist in this file, but they were not required for correct operation by this author; ymmv)*

Finally, add the following to your target Nginx `server { ... }` declaration:

> Testing indicated a trailing slash must be present (e.g. `location ^~ /nextcloud/`) for successful proxying. It's apparently not important for the `.well-known` definitions though. 

```
        location = /.well-known/carddav {
                return 301 $scheme://$host/nextcloud/remote.php/dav;
        }
        location = /.well-known/caldav {
                return 301 $scheme://$host/nextcloud/remote.php/dav;
        }
        location /.well-known/acme-challenge { }

        location ^~ /nextcloud/ {
                proxy_pass http://localhost:81;
                proxy_pass_header Server;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                rewrite ^/nextcloud/(.*)$ /$1 break;
        }
```
