### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by newmediologo** [nextcloud/nextcloud-snap#446]
HI.. In the Events Log I found tons of Warning like that:
"Warning | core | Trusted domain error. "71.6.202.204" tried to access using "2.xxx.xxx.xx" as host."

There's something to do to limit these attempts..?

Thanks

**Comment by kyrofa** [comment]
Are they all from the same IP?

Note that I wouldn't concern yourself too much over this, there are countless bots scanning the internet all the time; seeing that warning doesn't mean anyone is trying to hack you (or even log in), they're just taking a peek at what on that port.

**Comment by newmediologo** [comment]
Hi kyrofa, they comes from several IPs, there are also some warnings of failed login as:

Warning | core | Login failed: 'anonymous' (Remote IP: '192.168.1.254')

Username and Password meets security requirements

**Comment by kyrofa** [comment]
First of all, I highly recommend enabling two-factor authentication, it should help you rest a bit easier. Beyond that, it might be worth checking out the [bruteforce protection](https://apps.nextcloud.com/apps/bruteforcesettings) app to rate-limit these types of accesses.

**Comment by kyrofa** [comment]
I think this question has been answered, so I'll go ahead and close. Feel free to continue discussions here though.
