### ISSUE TITLE
HAProxy and HTTP -> HTTPS

### ISSUE THREAD

**Issue by Nichlas** [nextcloud/nextcloud-snap#447]
I have enabled HAProxy in front of Nextcloud SNAP as described in [this repository](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy). Including changing Nextcloud ports to 81 and 444.

Now the issue is, that when i access `cloud.example.com` it forwards to `https://cloud.example.com:444/`

This works because i haven't set up any firewall on my test server, but in production this will not work.

Also, setting up Let's Encrypt certificate fails because of the port.

**Comment by r4co0n** [comment]
I just checked the wiki entry you linked to, and what you describe is the expected outcome following this tutorial. It's not what anyone would want, I suppose, but:
1. Nextcloud http listens on 81, redirecting traffic to Nextcloud https
2. Nextcloud https listens on 444
3. HAProxy http request on port 80 redirects to 444, that's the https port configured for Nextcloud, it doesn't know about your proxy.

I have never worked with HAProxy, but setup proxies using Apache2 and nginx, but I think you should drop the nextcloud-http backend and instead configure forwarding to https within HAProxy as discussed here: https://stackoverflow.com/questions/13227544/haproxy-redirecting-http-to-https-ssl

Let the proxy deal with the forwarding, this means less complexity in your proxy setup (only one way from your proxy to your backend) and less load on your Nextcloud.

This should probably be updated in the documentation. I think reporting back with what worked for you will be appreciated.

**Comment by kyrofa** [comment]
> I think you should drop the nextcloud-http backend and instead configure forwarding to https within HAProxy as discussed here: https://stackoverflow.com/questions/13227544/haproxy-redirecting-http-to-https-ssl

Agreed, the snap's redirect behind the proxy isn't what you want here, I copied in the config I use for lxd containers without thinking that through all the way. Try using HAProxy to do it and see if that changes things.

**Comment by Nichlas** [comment]
This solves the problem of connecting as a user, but it creates a problem for running `nextcloud.enable-https lets-encrypt` 

It looks like Let's Encrypt expect to connect to the non-SSL site for the acme-challenge, and now that I've redirected all traffic to SSL (which currently runs with a self-signed cert) it results in a timeout.

Of course, a workaround on my test server is disable to temporarily haproxy and allow Nextcloud to respond to port 80, but I'd rather not do this on my production box.

I wonder if there is some setting in Nextcloud that would allow me to trick it into believing that it's actually responding to port 80 and 443 even if it really isn't.

**Comment by r4co0n** [comment]
You could make HAProxy only forward requests for `/.well-known/acme-challenge` to Nextcloud HTTP on port 81 and still handle HTTP->HTTPS redirection in HAProxy. Look at the snap's Apache config here: https://github.com/nextcloud/nextcloud-snap/blob/master/src/apache/conf/httpd.conf#L140

The part about Let's Encrypt is what you need to forward to make the ACME challenge work as expected.

**Comment by Nichlas** [comment]
I'm sorry that I have wasted your time.

It seems that the problem is not related to HAproxy, but instead the apache configuration in the snap. In the apache log i found this line:
`[Tue Feb 13 14:41:22.224406 2018] [authz_core:error] [pid 6492:tid 140533880059648] [client 95.154.54.91:23236] AH01630: client denied by server configuration: /var/snap/nextcloud/5132/certs/certbot/.well-known/acme-challenge`
So it seems the certbot is not being denied by HAProxy, but instead by the snap itself.

**Comment by Seferi** [comment]
Hi, I followed the tutorial with Haproxy and enabled the https, everything worked fine. But when i go to the address without  writing https in the beginningcloud.example.com it redirects to https://cloud.example.com:444/ which doesn't work... I have to write https://cloud.example.com in order to reach the site.. Is there any way to fix this ?

**Comment by r4co0n** [comment]
@Seferi, it seems you have HAProxy configured to redirect to port 444, this isn't in use anywhere here. Please post your HAProxy-config if you still have problems, I have successfully implemented redirects using HAProxy now.

I am closing this as the original issue is solved.

**Comment by Seferi** [comment]
@r4co0n Hi mate, still having the same problem. Here is the haproxy.cfg:

global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # Default ciphers to use on SSL-enabled listening sockets.
        # For more information, see ciphers(1SSL). This list is from:
        #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!$
        ssl-default-bind-options no-sslv3

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

backend nextcloud-http
        mode http
        balance roundrobin
        option forwardfor
        option httpchk HEAD / HTTP/1.1\r\nHost:localhost
        server nextcloud 127.0.0.1:81 check

backend nextcloud-http
        mode http
        balance roundrobin
        option forwardfor
        option httpchk HEAD / HTTP/1.1\r\nHost:localhost
        server nextcloud 127.0.0.1:81 check

backend nextcloud-https
        mode tcp
        balance roundrobin
        option forwardfor
        option httpchk HEAD / HTTP/1.1\r\nHost:localhost
        option ssl-hello-chk
        server nextcloud 127.0.0.1:444 check


frontend http
        bind *:80
        mode http

        acl host_nextcloud hdr(host) -i site.demo.com
        use_backend nextcloud-http if host_nextcloud

frontend https
        bind *:443
        mode tcp

        tcp-request inspect-delay 5s
        tcp-request content accept if { req_ssl_hello_type 1 }

        acl host_nextcloud req_ssl_sni -i site.demo.com
        use_backend nextcloud-https if host_nextcloud

**Comment by Seferi** [comment]
@r4co0n Any ideas what might be causing it?

**Comment by skjaeve** [comment]
I have the same issue, using HAproxy 1.7. The reverse proxy listens on mydomain.example.com on ports 80 and 443, Nextcloud snap is on ports 8080 and 8443. If I allow HTTP requests through the proxy, attempts to go to `http://mydomain.example.com:80` are rerouted by Nextcloud-snap to `https://mydomain.example.com:8443`, which of course doesn't work.

For logging in regularly in the web interface I can work around this by adding a HTTP->HTTPS redirect in HAproxy, but for some reason this doesn't work for the .well-known/caldav urls. Nextcloud redirects HTTPS urls: `https://mydomain.example.com/.well-known/caldav`  to `https://mydomain.example.com:8443/.well-known/caldav`.
