### ISSUE TITLE
Plex + Nextcloud, searching for the right permissions

### ISSUE THREAD

**Issue by Seferi** [nextcloud/nextcloud-snap#451]
Hi, i installed plex alongside nextcloud snap and trying to add nextcloud data directory as a source for plex but plex can't read the directory. These are what i tried so far:
- sudo usermod -aG www-data plex
- sudo chmod -R 775 /home/user/nextcloud/data/user/files
- sudo chmod -R 775 /home/user/nextcloud/data

I'll be greatful if you have any suggestions.
Thanks.

**Comment by Seferi** [comment]
sudo chmod -R 775 /home/user/nextcloud/data/

actually works but snap resets the permissions after every reboot...

**Comment by ch1x0r** [comment]
I'm trying this myself atm. Thanks for the heads up...
sudo usermod -aG www-data pi
sudo systemctl restart plexmediaserver.service
chmod -R 775 /var/www/nextcloud/data/pi/files

**Comment by Seferi** [comment]
I use to have the same setup on nextcloudbox and had the same problem.. ended up installing plex docker image as root, everything worked but probably not secure at all..

**Comment by ch1x0r** [comment]
I am using it on Pi3 with no issues. I rebooted several times. No snap...though. On raspbian base.
![2018-02-19-123959_1824x984_scrot](https://user-images.githubusercontent.com/4945600/36394939-bf283476-1573-11e8-88c5-c2a650bda200.png)
![2018-02-19-124100_1824x984_scrot](https://user-images.githubusercontent.com/4945600/36394940-c0b76b5e-1573-11e8-83fb-75eba09800a3.png)

**Comment by ch1x0r** [comment]
Not using Snap these days, so I guess I will leave this group. Farewell!!! :D

**Comment by Ark74** [comment]
Wouldn't it be better to have an external location/drive to set there files so plex can encode whatever it needs and make modifications that could break NC?
