### ISSUE TITLE
Can't stat() local storage directory

### ISSUE THREAD

**Issue by mo-seph** [nextcloud/nextcloud-snap#452]
I've just installed nextcloud on Ubuntu 16_04, using snap. If I try to add a local directory as an external storage, I get
`stat(): stat failed for /data/test/ at /snap/nextcloud/5119/htdocs/lib/private/Files/Storage/Local.php#140`

This happens both with version 12 and 13.

I'm working with a test directory that is readable and writable by everyone:
`>ls -lad /data/test`
`drwxrwxrwx 2 www-data 4096 Feb 17 13:50 /data/test`

I've tried several other directories, including ones on the same filesystem as the snap, in case this makes a difference.

External Storage setup is as follows:
![image](https://user-images.githubusercontent.com/509387/36351926-a0bba732-14a8-11e8-98ed-5b839b45f6cf.png)

DB info is:
```
>sudo nextcloud.occ files_external:list
+----------+-------------+---------+---------------------+-------------------------+---------+------------------+-------------------+
| Mount ID | Mount Point | Storage | Authentication Type | Configuration           | Options | Applicable Users | Applicable Groups |
+----------+-------------+---------+---------------------+-------------------------+---------+------------------+-------------------+
| 5        | /test       | Local   | None                | datadir: "\/data\/test" |         | All              |                   |
+----------+-------------+---------+---------------------+-------------------------+---------+------------------+-------------------+
```

**Comment by Seferi** [comment]
It seems a bit like the problem I had. Don't know if it will help but here is what i did:
- connect the removable-media plug with : sudo snap connect nextcloud:removable-media
- bind mounted the /data/test to /media/nextcloud : sudo mount -o bind /data/test /media/nextcloud  -
- added it to fstab so it stays after reboots:  /data/test    /media/nextcloud/    none    bind 
- afterwards added the /media/nextcloud as external storage in nextcloud web interface.

**Comment by mo-seph** [comment]
Thanks @Seferi, that works.

**Comment by Seferi** [comment]
Glad I could help!

**Comment by kyrofa** [comment]
Thanks @Seferi, you're on top of things!

**Comment by mo-seph** [comment]
Could I suggest that a message that "Only directories in /media can be mounted as external storage" would save future users a lot of time? The restriction is not immediately clear, and it's a slightly strange workaround for a fairly reasonable use case.

**Comment by Crypt0Graf** [comment]
The solution with removable-media is very easy and works excellent. However, this makes it possible to mount all removable media / all mounts from within Nextcloud as root, which is something I didn't like. However, this is how I did it in the end:
1. I've created a mountpoint in the directory of my user (please replace myUsername with your username)
`sudo mkdir /var/snap/nextcloud/common/nextcloud/data/myUsername/files/Data`
2. Then I've bound the directory I wanted to the mountpoint (to make this permanent, please note what [Seferi wrote about fstab](https://github.com/nextcloud/nextcloud-snap/issues/452#issuecomment-366519374))
`sudo mount -B /what/i/want/in/my/Nextcloud /var/snap/nextcloud/common/nextcloud/data/myUsername/files/Data`
3. As the folder didn't showed up in the Nextcloud interface (it wasn't listed in the database index yet), I had to create a folder in Nextcloud with the name of my mountpoint, `Data`, and Nextcloud found the mounted folder.
4. Worksforme.

**Comment by JakobPP** [comment]
Sorry to bring up this old thread.

I am just wondering, is this error and workaround only related to removable-media (as in an external USB drive or what ever)? Or does it apply so S3 storage as well? I am getting this error once in a while, and my data is on S3 storage connected via external storage.

**Comment by Crypt0Graf** [comment]
> I am just wondering, is this error and workaround only related to removable-media (as in an external USB drive or what ever)? Or does it apply so S3 storage as well? I am getting this error once in a while, and my data is on S3 storage connected via external storage.


I seriously have no Idea about how S3 storage can be integrated into a Nextcloud snap, sorry. This workaround was for removable media as well as partitions outside the partition where the snap is installed on. And, in my case, this isn't something that occurs more than one time. If it works, it just works.

**Comment by JakobPP** [comment]
> > I am just wondering, is this error and workaround only related to removable-media (as in an external USB drive or what ever)? Or does it apply so S3 storage as well? I am getting this error once in a while, and my data is on S3 storage connected via external storage.
> 
> I seriously have no Idea about how S3 storage can be integrated into a Nextcloud snap, sorry. This workaround was for removable media as well as partitions outside the partition where the snap is installed on. And, in my case, this isn't something that occurs more than one time. If it works, it just works.

The external storage app supports S3. I should hope that it is in fact supported, why wouldnt it?

**Comment by Crypt0Graf** [comment]
> The external storage app supports S3. I should hope that it is in fact supported, why wouldnt it?
Sorry, I've just tried to state that I'm not familiar with S3 and do not know how it works. Therefore, I don't have any idea whether this workaround works for S3 or not.

**Comment by stanislavgeorgiev** [comment]
> It seems a bit like the problem I had. Don't know if it will help but here is what i did:
> 
> * connected the removable-media plug with : sudo snap connect nextcloud:removable-media
> * bind mounted the /data/test to /media/nextcloud : sudo mount -o bind /data/test /media/nextcloud  -
> * added it to fstab so it stays after reboots:  /data/test    /media/nextcloud/    none    bind
> * afterwards added the /media/nextcloud as external storage in nextcloud web interface.

Thanks @Seferi , your instructions helped me to finally get my external hdd working properly! I didn't need to do step 1 though since the Pi is already connecting with the external hdd automatically.
