### ISSUE TITLE
Prevent snap resetting permissions for data folder after reboot

### ISSUE THREAD

**Issue by Seferi** [nextcloud/nextcloud-snap#454]
Hi, I installed plex with nextcloud and set the data directory permissions with sudo chmod -R 775 /home/user/nextcloud/data/ so plex could read the directory but after every reboot nextcloud resets the permissions for the directory. Is there a way to prevent that?

**Comment by kyrofa** [comment]
Hey @Seferi sorry for the slow responses recently-- just had a baby!

Remind me-- you have this dir bind-mounted into /media/ somewhere, right?

**Comment by Seferi** [comment]
@kyrofa  No worries mate. Yes, in /etc/fstab          /home/user/nextcloud /media/nextcloud     none     bind 

I just realized not just with every reboot but like all the time resets after some time..

**Comment by kyrofa** [comment]
My third boy!

Okay, that permissions thing sounds a little odd. Let me investigate once I'm at my computer.

**Comment by oparoz** [comment]
> My third boy!

Wow, congrats :)

**Comment by ch1x0r** [comment]
> My third boy!
Congrats!

**Comment by Seferi** [comment]
> My third boy!
Congrats mate! And thanks for looking in to it. It's a pretty frustrating problem.. Couldn't find a way around it..

**Comment by Seferi** [comment]
I tried using symlink instead of bind mount : sudo ln -s /home/user/nextcloud     /media
but when I visited nextcloud web, I got this: Your data directory is readable by other users
Please change the permissions to 0770 so that the directory cannot be listed by other users.

Did you have time to investigate @kyrofa ?

**Comment by kyrofa** [comment]
Yeah, pretty sure it's [this bad boy](https://github.com/nextcloud/server/blob/master/lib/private/legacy/util.php#L1006). Not sure there's anything we can do about this in the snap if it's upstream Nextcloud behavior :cry: .

**Comment by Seferi** [comment]
@kyrofa Thanks for looking into it mate. I stupidly did chown -R www-data:plex /home/user/data
and now I'm getting :
Your data directory is invalid
Ensure there is a file called ".ocdata" in the root of the data directory.

Cannot create "data" directory
This can usually be fixed by giving the webserver write access to the root directory. See https://docs.nextcloud.com/server/12/go.php?to=admin-dir_permissions

Anyway I could recover from this?

**Comment by Seferi** [comment]
When I do: sudo nextcloud.occ I get this if it helps: 
Your data directory is not writable
Permissions can usually be fixed by giving the webserver write access to the
root directory. See https://docs.nextcloud.com/server/12/go.php?to=admin-dir
permissions.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /snap/nextcloud/5132/htdocs
lib/private/Console/Application.php:145
Stack trace:
#0 /snap/nextcloud/5132/htdocs/console.php(99): OC\Console\Application->load
ommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Co
ponent\Console\Output\ConsoleOutput))
#1 /snap/nextcloud/5132/htdocs/occ(11): require_once('/snap/nextcloud...')
#2 {main}user@NUC:~$

I already tried sudo chown -R www-data:www-data /home/user/nextcloud/data

**Comment by kyrofa** [comment]
Hey @Seferi, note that the web server in the snap runs as root, not www-data (confined root though, don't worry). Try that instead.

**Comment by Seferi** [comment]
Hey mate, Thanks! so root:root or www-data:root?

**Comment by kyrofa** [comment]
Nice! Plex must be www-data, then?

**Comment by Seferi** [comment]
Well I added plex to www-data group with sudo usermod -aG www-data plex long ago but it didn't work.. Very strange..

**Comment by kyrofa** [comment]
Well, by default the snap uses root:root so without changing that, adding Plex to www-data didn't do anything. Changing permissions like you did would work, but only by making your data world-readable. This is a much better solution.

**Comment by kyrofa** [comment]
Sounds like this solution is working, so I'll go ahead and close this. Please reopen if necessary.

**Comment by Seferi** [comment]
Just for the sake of understanding what happened.. All I did was changing the ownership to plex with sudo chown -R www-data:plex /home/user/nextcloud/data and then back to root with  sudo chown -R root:www-data /home/user/nextcloud/data      How come plex can still read the directory? root owns it now, everything is back to before..

**Comment by kyrofa** [comment]
Well, you said you added Plex to the www-data group, right? If you have 750 permissions with root:www-data, you're allowing the owner (root) to do anything, allowing the group (www-data) to read and execute, and disallowing anyone else from doing anything.
