### ISSUE TITLE
"Internal Server Error" after installing Collabora Online and trying to edit an *.odt file

### ISSUE THREAD

**Issue by halb9** [nextcloud/nextcloud-snap#455]
Hi there, 

I was playing around with the snap package and the Collabora Online App does seem to have some hickups. 

Here is what I did. 

1. Set up fresh Ubuntu 16.04.3 LTS Server
2. Server is available via a public domain and IP address behind a firewall (ICMP, 80 & 443 open)
3. Installed nextcloud snap package via 'sudo snap install nextcloud'
4. Set up my admin account. nothing more. 
5. Set up Let's Encrypt Certificate via 'sudo nextcloud.enable-https lets-encrypt' (worked great btw!)
6. Refreshed browser. It redirects now to https, yay! ;)
7. Installed the Collabora Online App via AppStore. 
8. Create a new *.odt File 
![nc-helloworld](https://user-images.githubusercontent.com/18451020/36393120-20f31d10-15a6-11e8-92e3-a5083a166260.png)

9. Click on HelloWorld.odt. Nextcloud shows "Internal Server Error" dialog. 
![nc-internal-server-error](https://user-images.githubusercontent.com/18451020/36393180-723993f2-15a6-11e8-8374-742bd198ecc2.png)

A quick search throws up #354 where the solution was to remove some of the apps. But since Collabora is the only App I ever installed I guess this is somehow different. 

Furthermore the dialog says that more details can be found in the server log. But I'm not confident where to find the correct log files. I'll post them otherwise. 

//edit: Here is a log from /var/snap/nextcloud/common/nextcloud/data/nextcloud.log 
Maybe it helps.

`{"reqId":"v0NH3jdpUYvhvunbvE1d","level":3,"time":"2018-02-19T20:51:25+00:00","remoteAddr":"00.00.000.000","user":"abcdef","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/index?fileId=156&requesttoken=PU0M6HPdOhLGKbh6gZpqDmDr9t5pSZYwH%2FPjSuYryXE%3D%3ARDhJiwSHS1z%2BYc0b6tU%2BNwm%2FvYcvHadkMMu1Ao8S%2BRU%3D","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\RequestException\",\"Message\":\"cURL error 3: <url> malformed\",\"Code\":0,\"Trace\":\"#0 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(103): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\RingException))\\n#1 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(*** sensitive parameters replaced ***)\\n#3 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(138): GuzzleHttp\\\\Client->get('\\\/hosting\\\/discov...', Array)\\n#9 \\\/var\\\/snap\\\/nextcloud\\\/5132\\\/nextcloud\\\/extra-apps\\\/richdocuments\\\/lib\\\/WOPI\\\/DiscoveryManager.php(84): OC\\\\Http\\\\Client\\\\Client->get('\\\/hosting\\\/discov...')\\n#10 \\\/var\\\/snap\\\/nextcloud\\\/5132\\\/nextcloud\\\/extra-apps\\\/richdocuments\\\/lib\\\/WOPI\\\/Parser.php(41): OCA\\\\Richdocuments\\\\WOPI\\\\DiscoveryManager->get()\\n#11 \\\/var\\\/snap\\\/nextcloud\\\/5132\\\/nextcloud\\\/extra-apps\\\/richdocuments\\\/lib\\\/TokenManager.php(122): OCA\\\\Richdocuments\\\\WOPI\\\\Parser->getUrlSrc('application\\\/vnd...')\\n#12 \\\/var\\\/snap\\\/nextcloud\\\/5132\\\/nextcloud\\\/extra-apps\\\/richdocuments\\\/lib\\\/Controller\\\/DocumentController.php(168): OCA\\\\Richdocuments\\\\TokenManager->getToken(*** sensitive parameters replaced ***)\\n#13 [internal function]: OCA\\\\Richdocuments\\\\Controller\\\\DocumentController->index('156')\\n#14 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#15 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'index')\\n#16 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'index')\\n#17 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Richdocumen...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#20 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/richdocum...')\\n#21 \\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/index.php(48): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/snap\\\/nextcloud\\\/5132\\\/htdocs\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":51}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/64.0.3282.140 Chrome\/64.0.3282.140 Safari\/537.36","version":"12.0.5.3"}`

**Comment by igelkotten** [comment]
--This has nothing to do with the snap.
Collabora works by sending it on to a Collabora host api thingy =P I am not even sure if that is free.

So you either set that up as it should be setup or you remove Collabora.

**Comment by halb9** [comment]
Thanks igelkotten. I didn't know that before and thus assumed simply installing it through the app store would be enough. But as I did some more research (thank you for the hints) it turned there is indeed a bit more to be done ^^ (e.g. https://nextcloud.com/collaboraonline/)
I'll have to look a bit deeper into it at some point. 

Nevertheless I think "offering" the app when there is basically no functionality behind it is kinda weird from a UX point of view. 

// I close this issue as I see it resolved.

**Comment by PattMayne** [comment]
I'm on WebFaction which doesn't allow Docker because of a linux-kernal conflict. I'd like to see the resolution to this, too!

**Comment by rusmircrnica** [comment]
Same problem here... Is there any solution for this? I've spent weeks on this, and the issue is still present...

**Comment by PattMayne** [comment]
I gave up completely. I've been looking for a self-hosted alternative to Google Docs, but it's just WAY too much work to install and maintain these beasts. This stuff is meant for big software teams, rather than Some Dude (me) who wants his own online office suite.

I'm just continuing to use Google Docs for now.
