### ISSUE TITLE
Tests with rake fail because of missing dependency xvfb

### ISSUE THREAD

**Issue by r4co0n** [nextcloud/nextcloud-snap#460]
When trying to run the tests this snap provides via the mechanism described in the README under [Hacking][1], i found that I need to install another dependency, `xvfb`(Virtual Framebuffer 'fake' X server) via apt before being able to run `rake test`.

This is on Ubuntu 16.04 .

To mitigate, run
```
sudo apt install xvfb
```
before running the tests.

Without the dependency, the following happens:

```
$ rake test
/usr/bin/ruby2.3 -I/var/lib/gems/2.3.0/gems/rspec-support-3.6.0/lib:/var/lib/gems/2.3.0/gems/rspec-core-3.6.0/lib /var/lib/gems/2.3.0/gems/rspec-core-3.6.0/exe/rspec spec/change_php_memory_limit_spec.rb spec/change_port_spec.rb spec/enable_https_spec.rb spec/login_spec.rb --format documentation

An error occurred in a `before(:suite)` hook.
Failure/Error: RSpec.configuration.headless = Headless.new

Headless::Exception:
  Xvfb not found on your system
# /var/lib/gems/2.3.0/gems/headless-2.3.1/lib/headless/cli_util.rb:9:in `ensure_application_exists!'
# /var/lib/gems/2.3.0/gems/headless-2.3.1/lib/headless.rb:78:in `initialize'
# ./spec/spec_helper.rb:137:in `new'
# ./spec/spec_helper.rb:137:in `block (2 levels) in <top (required)>'

An error occurred in an `after(:suite)` hook.
Failure/Error: RSpec.configuration.headless.destroy

NoMethodError:
  undefined method `destroy' for nil:NilClass
# ./spec/spec_helper.rb:142:in `block (2 levels) in <top (required)>'

Finished in 0.01426 seconds (files took 0.31509 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

/usr/bin/ruby2.3 -I/var/lib/gems/2.3.0/gems/rspec-support-3.6.0/lib:/var/lib/gems/2.3.0/gems/rspec-core-3.6.0/lib /var/lib/gems/2.3.0/gems/rspec-core-3.6.0/exe/rspec spec/change_php_memory_limit_spec.rb spec/change_port_spec.rb spec/enable_https_spec.rb spec/login_spec.rb --format documentation failed
```

[1]: https://github.com/nextcloud/nextcloud-snap/blob/master/README.md#hacking

**Comment by kyrofa** [comment]
It's been a while since I played with this, but if I remember correctly this is only required on a distribution that doesn't already have X running (e.g. Ubuntu Server). In fact, according to memory if you install it on Ubuntu Desktop the tests start exploding. That's why we [definitely install it in CI](https://github.com/nextcloud/nextcloud-snap/blob/master/.circleci/runtests.sh#L4), but didn't recommend it in the hacking section.

You mention you're on Ubuntu, but are we talking Desktop or Server?

**Comment by r4co0n** [comment]
Hi, it's a vagrant box, bare ubuntu/xenial64 with snapcraft installed (for building some modifications locally), then followed the guide. So yeah, I don't have X running. Maybe it should be noted separately à la: "If you are running this on a headless system and don't have an X Server configured, you need to additionally install xvfb."

**Comment by kyrofa** [comment]
Okay good deal. I'll comment on the PR to that effect.
