### ISSUE TITLE
Optimise PHP config for the hardware it runs on

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#47]
PHP shouldn't be configured the same way if it runs on a Pi2 or some powerful amd64 server.

**Comment by oparoz** [comment]
Ok, so looking at how to do this, we need to provide a read-only file where we search and replace values for key variables and offer a read-write config to be able to overwrite any variable which creates problems.

I think exporting variables would just create more work to create an importer instead of just including changes as is in the PHP file.

**Comment by kyrofa** [comment]
This should have been closed by 7d994c95.
