### ISSUE TITLE
Update Nextcloud to v11.0.7

### ISSUE THREAD

**Issue by pachulo** [nextcloud/nextcloud-snap#470]
I don't really know if there are many users with nextcloud v11, but as it still supported I think that we should update it. Or maybe wait to the release of 11.0.8:
https://github.com/nextcloud/server/milestone/35

**Comment by kyrofa** [comment]
Agreed, we should update it.

**Comment by QuaySo** [comment]
Now 13.0.2 is out, Nextcloud annouces that 11 is no longer maintained.
See this blog item: https://nextcloud.com/blog/nextcloud-13.0.2-and-12.0.7-available-collabora-online-3.2-is-out/

**Comment by kyrofa** [comment]
11.0.8 has been released to 11/stable. We're done supporting it now as well.
