### ISSUE TITLE
Let's Encrypt using with port 4443

### ISSUE THREAD

**Issue by paschalis-ch** [nextcloud/nextcloud-snap#475]
Hello

Is it possible to use let's Encrypt with another port as 443? I have two nextcloud servers in use and I want to connect with 443 and 4443 from the internet without a proxy server.

Thank you

**Comment by r4co0n** [comment]
Unfortunately, you will need your snap to listen on HTTP/80 to let certbot aquire a LetsEncrypt certificate. Then, it does not matter which port you run HTTPS on, you can just change the https port of the nextcloud snap via `snap set`. I would advise you to setup a web proxy, but if you want to avoid that at all costs, you could configure certbot yourself on the host, disable it for the snaps and use the `enable-https custom` command after moving the generated certificate to a location readable by the respective snap.

**Comment by r4co0n** [comment]
Closing this as it seems answered, albeit not resolved.

Please note that questions like this will probably get a faster answer and a bigger audience at [https://help.nextcloud.com/](https://help.nextcloud.com/).
