### ISSUE TITLE
Issues with Nextcloud Snap behind Nginx proxy & subdir

### ISSUE THREAD

**Issue by JohnDorien1** [nextcloud/nextcloud-snap#483]
I want to have the running nginx to server the Nextcloud snap in a subfolder domain.tld/cloud

So far I can get the index to load, but all further requests of Nextcloud are directd to domain.tld instead of domain.tld/cloud/*

I've tried lots of different nginx configs after googling hours so far, but it seems there needs to be any changes being done in the NC snap so it is requesting its files from the subdir /cloud ?

Please help where and what I have to chage here, can't find anything in the docs helping with the snap config in this regards.

Thanks in advance

**Comment by JohnDorien1** [comment]
Found it by accident: In the config php within the snap nextcloud folders add the line "overwritewebroot"  => "/chat", and it will work.

**Comment by hardfire** [comment]
@JohnDorien1 could you share the nginx config you used for this?
