### ISSUE TITLE
How-to upgrade from 12 stable to 13 stable?

### ISSUE THREAD

**Issue by dutchievj** [nextcloud/nextcloud-snap#490]
I have been using 12 stable now for a couple of weeks and would like to upgrade to 13 stable without losing my data.

How does one do that with snap? :)

**Comment by auberginepop** [comment]
13 stable has not been released yet #442 
You can test the release candidate by running
`sudo snap install nextcloud --channel=13/candidate`

**Comment by JamesBream** [comment]
@auberginepop Does doing a refresh preserve data? i.e. going from 13/candidate to 13/stable once it's released?

**Comment by kyrofa** [comment]
@JamesBream yes, it does. As a result, however, you cannot refresh from e.g. 13 to 12, so keep that in mind.

**Comment by kyrofa** [comment]
v13 is now in stable, so consider running `sudo snap refresh --stable nextcloud`.
