### ISSUE TITLE
How do I install Nextcloud with a datadir in /data

### ISSUE THREAD

**Issue by adam-szabo** [nextcloud/nextcloud-snap#498]
I am trying to set up Nextcloud snap on an Azure VM running Ubuntu 16.04. I have a 4TB VHD as sdc1 mounted under `/data`.

I tried creating a symlink from `/var/snap/nextcloud/common/nextcloud/data` to `\data\nextcloud\data`, didn't work. Tried all combinations of permissions, owners, etc.

What am I missing?

**Comment by erwinchan** [comment]
hi @adam-szabo have you try to update datadirectory in config.php?

**Comment by kyrofa** [comment]
The snap is confined, and by default can't access any part of your disk except its own area. You can [allow it access to /media/](https://github.com/nextcloud/nextcloud-snap#removable-media), but that's still not `/data`. The only way to do that is to bind-mount e.g. `/data/nextcloud/data` to `/media/nextcloud/data`

**Comment by adam-szabo** [comment]
Thanks @kyrofa, I will give it a try. What owner and permissions should I set for the `/media/nextcloud/data` folder to work?

**Comment by kyrofa** [comment]
Try root:root, 750.

**Comment by kyrofa** [comment]
(you can switch the group around, as long as the files are root-owned).

**Comment by adam-szabo** [comment]
Still doesn't work. I did the following:

1. Mount `/dev/sdc1` to `/media/datadisk` (root:root 755)
2. `sudo snap install nextcloud`
3. `sudo snap connect nextcloud:removable-media`
4. Connect to nextcloud URL, enter admin user/pass, click finish install
5. After the configuration finished, `sudo service snap.nextcloud.apache stop`
6. Create `/media/datadisk/nextcloud` folder (root:root 750)
7. Move `/var/snap/nextcloud/common/nextcloud/data` to `/media/datadisk/nextcloud`
8. Set datadir to `/media/datadisk/nextcloud/data` in `/var/snap/nextcloud/current/nextcloud/config/config.php`
9. `sudo service snap.nextcloud.apache start`
10. `Your data directory is invalid` `Ensure there is a file called ".ocdata" in the root of the data directory.` :-(

Does it have to be bind-mount, does snap have a problem accessing normally mounted filesystems?

**Comment by kyrofa** [comment]
> Does it have to be bind-mount, does snap have a problem accessing normally mounted filesystems?

No, normal mounts are perfectly fine! How did you move your data over? If you're still in a situation where you can start from scratch, try this:

1. Mount HD into `/media/datadisk`
2. `sudo snap install nextcloud`
3. `sudo snap connect nextcloud:removable-media`
4. Edit `/var/snap/nextcloud/current/nextcloud/config/autoconfig.php` (note that it will take a few seconds for this file to be available, it's generated on first install). Change the `datadirectory` to `/media/datadisk/nextcloud/data` (note that this path must already exist and have proper permissions)
5. Visit Nextcloud in the browser and create admin user
6. Nextcloud should be using your external disk

Note that (5) MUST come after (4). Since the config file is PHP, it's only evaluated once you visit it, so if you visit Nextcloud before (4) and then create an admin user, the `datadirectory` will hold its original, un-edited value.

**Comment by adam-szabo** [comment]
Thanks, I started from scratch. `/var/snap/nextcloud/current/nextcloud/config/autoconfig.php` doesn't contain any `datadirectory` though. It has an array called `$AUTOCONFIG`, should I add new key called `datadirectory` to that array?

**Comment by adam-szabo** [comment]
Didn't work unfortunately. I followed your advice step by step, but it looks like the `directory` parameter got disregarded and it still put set `'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',` in `config.php`.

**Comment by kyrofa** [comment]
Ah, sorry, I was operating from memory. So by default `autoconfig.php` looks like this:

```
<?php

$snap_name = getenv('SNAP_NAME');

$data_path = '/var/snap/'.$snap_name.'/current';

$database_password = trim(file_get_contents($data_path . '/mysql/nextcloud_password'));

$AUTOCONFIG = array(
'directory' => getenv('NEXTCLOUD_DATA_DIR'),

'dbtype' => 'mysql',

'dbhost' => 'localhost:'.getenv('MYSQL_SOCKET'),

'dbname' => 'nextcloud',

'dbuser' => 'nextcloud',

'dbpass' => $database_password,
);
```

You need to update it to look like:

```
<?php

$snap_name = getenv('SNAP_NAME');

$data_path = '/var/snap/'.$snap_name.'/current';

$database_password = trim(file_get_contents($data_path . '/mysql/nextcloud_password'));

$AUTOCONFIG = array(
'directory' => '/media/datadisk/nextcloud/data',

'dbtype' => 'mysql',

'dbhost' => 'localhost:'.getenv('MYSQL_SOCKET'),

'dbname' => 'nextcloud',

'dbuser' => 'nextcloud',

'dbpass' => $database_password,
);
```

Then and ONLY then should you visit Nextcloud in your browser and create a user, or you'll see behavior like what you just described.

**Comment by adam-szabo** [comment]
Found the issue! I made a mistake at the last step, instead of replacing the value of `'directory'`, I've added another element to the end of the array, so it was disregarded.
Re-did it again according to your steps and it works. Thank you very much for your help, much appreciated. 👍

**Comment by kyrofa** [comment]
Excellent, I wondered it that was it! :100:
