### ISSUE TITLE
Nextcloud-snap gives error on raspberry pi 3

### ISSUE THREAD

**Issue by qazip** [nextcloud/nextcloud-snap#499]
Hey,

I am trying to install nextcloud-snap on a raspberry pi 3 running ubuntu-mate (the arm version) and I'm getting the following error:

error: cannot perform the following tasks:

` - Run configure hook of "nextcloud" snap if present (run hook "configure": cannot apply seccomp profile: Invalid argument)`

How can I fix this?

**Comment by kyrofa** [comment]
I'm afraid Ubuntu MATE on the rpi doesn't use the Ubuntu kernel, which is required for snaps to work. I have it on good authority, however, that this will change come 18.04. I recommend Ubuntu Core for the rpi if you want to run snaps.

**Comment by MasterGroosha** [comment]
@kyrofa Which kernel (minimum version) is required for Nextcloud? I'm running Ubuntu 16.04 on my ODroid-C1 with 3.10 kernel and I'm having the same error as topic starter.

**Comment by kyrofa** [comment]
@MasterGroosha it's not version so much as enabled features. You need a pretty new apparmor and seccomp filters enabled to run snaps, among other things.
