### ISSUE TITLE
Split Web stack configs in two to make it possible for users to customise them

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#50]
It's very important for developers to be able to turn on debug flags in the Snap to be able to see what is going on, but users may also want to change the configuration we've shipped as the default.

I propose to use the following convention:

* `platform.conf` will contain all the changes we make based on the detected hardware
*  `custom.conf` will contain settings users may want to configure depending on their use cases

`platform.conf` will sit on the read-only partition and `custom.conf` will be used to override the default settings.

## TODO

- [ ] Apache https://github.com/nextcloud/nextcloud-snap/issues/70
- [ ] PHP
- [ ] MySQL

**Comment by kyrofa** [comment]
I suggest you leave the platform-specific configs in the read-only snap (e.g. configured via environment variables or something similar), or you'll run into conflict issues.

**Comment by oparoz** [comment]
We will run into conflict issues as well for the custom config, no?

**Comment by oparoz** [comment]
Ah yes, using overrides.  It works for Apache and MySQL, but I'm not sure it does for PHP-FPM. We'll have to test.
