### ISSUE TITLE
Updating SSL certificates

### ISSUE THREAD

**Issue by wouterverduin** [nextcloud/nextcloud-snap#500]
Hello alll!

I have Nextcloud snap 12.0.5 running and got some good certificate for my domain. Unfortantly it expired and i tried to regain a new certificate. The problem is: i get a timeout at the fetching stage.

I reopend port 80 on my router because maybe it needed it but without succes. Anyone else running into this issue or know what i am doing wrong?

All other settings are unchanged.

**Comment by kyrofa** [comment]
To clarify, are you trying to get Let's Encrypt certificates via `nextcloud.enable-https lets-encrypt`? Can you show me what happens when you do this?

**Comment by wouterverduin** [comment]
sudo nextcloud.enable-https lets-encrypt.

Got part of the problem solved though, thanks for the help!

Root of the problem: Nextcloud needs port 80 open for retrieval of the certificate altough it functions well with just 443 open. 

After temporarily opening both the retrievel was done easily.

Only thing left: It still says the certificate isnt trusted when i browse to my nextcloud.. Does it take some time to update things?

**Comment by kyrofa** [comment]
Indeed, it needs port 80.

However, once Apache restarts the new cert should be picked up. You're sure you're visiting it using a domain name you used on the cert?

**Comment by wouterverduin** [comment]
Yeah i did, it worked when i removed all cookies, got it fixed, thanks mate!

**Comment by kyrofa** [comment]
Excellent, thanks for getting back to me. I'll go ahead and close this, then.
