### ISSUE TITLE
Enabling FTP support

### ISSUE THREAD

**Issue by benjamingwynn** [nextcloud/nextcloud-snap#503]
Hi,

I can't figure out how to enable external storage for FTP servers. I tried following the instructions [here](https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage/ftp.html), but I can't find php.ini.

Thanks.

**Comment by vorell** [comment]
Is there some compatibility issue like with SMB support which prevents FTP support from being integrated into the snap? I would think it should be as simple as loading an additional PHP extension.

**Comment by pachulo** [comment]
@benjamingwynn the file is in `/writable/system-data/snap/nextcloud/current/config/php/php.ini` but I think that the underlyng problem is that when compiling PHP for the snap we are not using the `--enable-ftp` config-flag:
- https://github.com/nextcloud/nextcloud-snap/blob/master/snap/snapcraft.yaml#L163 
- https://secure.php.net/manual/en/ftp.installation.php

What do you think about this @kyrofa ?

**Comment by pachulo** [comment]
By the way, even without the config-flag `--enable-ftp` for PHP the SFTP option is available in the external storage app...have you tried it @benjamingwynn ?

**Comment by kyrofa** [comment]
@pachulo does your comment imply that the PR is unnecessary? Or is that only for SFTP?

**Comment by pachulo** [comment]
No, it means that **SFTP** is available with the current configuration, but for **FTP** to be available we need my PR.
And also that I have not tried to add a SFTP server, only a FTP one.

**Comment by kyrofa** [comment]
Alright, thank you. @benjamingwynn can you verify that #628 fixes your problem by testing the `beta/pr-628` channel, please?

    $ sudo snap install nextcloud --channel=beta/pr-628

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=beta/pr-628

Once you're done testing, switch back to the channel you were on (e.g. `stable`) with:

    $ sudo snap refresh nextcloud --stable

**Comment by benjamingwynn** [comment]
I'm afraid I can't. I had to move away from Nextcloud for the project I was working on. I can close this issue as it's no longer relevant for me, or leave it open for further discussion.
