### ISSUE TITLE
Where are the config files?

### ISSUE THREAD

**Issue by Benjarobbi** [nextcloud/nextcloud-snap#504]
Hi there, can't find the config files in the given path: 
`/var/snap/nextcloud/current/nextcloud/config/config.php`.
It doesn't exists on my system.
I'm trying to move my nextcloud directory to another place but it isn't working without editing the config. Where can I find it or how to do it?
The documentation: `https://github.com/nextcloud/nextcloud-snap/blob/master/README.md` is also referring to this place. Sadly I can't find a way how to do it.

**Comment by Benjarobbi** [comment]
Nevermind. Seems like it came in a new install.

**Comment by Krutonium** [comment]
I'm having the same issue actually, and it's been around for a while - I can't find config.php
