### ISSUE TITLE
how can use occ

### ISSUE THREAD

**Issue by johnpoint** [nextcloud/nextcloud-snap#505]
i want to update my file list by php occ files:scan，but i can't

**Comment by stmaro** [comment]
im new to this but had to do same exact thing... after uploading the files to database location I than ran below and it worked like a charm:

`sudo nextcloud.occ files:scan --all`

**Comment by johnpoint** [comment]
wow，it run ，thx

**Comment by BR0KK** [comment]
So where is OCC located then .... i want to ad a script that scans my external shares only every hour. That script needs the path to occ ( apparently its not th default path....)

**Comment by kyrofa** [comment]
You can tell with `which nextcloud.occ`, but you'll find it in `/snap/bin/`.

**Comment by phuongdzu** [comment]
> sudo nextcloud.occ files:scan --all

Hi,
Exception during scan: "files/346bb0c4ebad1fe695b4cb75032e253e"("ftp::admin_ftp@94.130.220.234//::scanner::") is locked,
How to fix?
Thanks
