### ISSUE TITLE
adding website to apache web-root, with read-only snap directories.

### ISSUE THREAD

**Issue by jwstolk** [nextcloud/nextcloud-snap#506]
I was one of the early nextcloud users and my old install ended up as a mix of version 9 and 10. It works fine but is hard to migrate to a new server.
I'm new to snap and trying to use it for nextcloud on a new webserver.

The nextcloud-snap documentation states that it comes with it's own web server and I need to remove any existing web servers. I'd like to uninstall apache and use nginx instead but I can't a good way to uninstall the included apache and can't find how to configure nextcloud-snap to use nginx instead.

For now keeping apache, I found a web-root in /snap/nextcloud/current/htdocs/ but I can't put my website here since these directories are not writable. (I'd like to use grav for my website)
For things like extra apps there are writable directories in /var/snap/, but 

I'd like to use the letsencrypt certificate from my old server and copied over /etc/letsencrypt, but I suspect that won't be used by the snap package.

In my old installation I made quite a few changes to nextcloud php files, which seems problematic when using snap.

In general, is it better to use the non-snap-nextcloud install if I would like to make these or similar changes to the default configuration, or should this be possible with nextcloud-snap?

**Comment by kyrofa** [comment]
Hey there @jwstolk. Indeed, the snap is a nice and easy way to run standard Nextcloud, but it's not very flexible if you need to customize stuff. Snaps are by definition read-only, so you can't just switch out apache for nginx, nor can you change any of Nextcloud's php files. You can always proxy from nginx to the apache embedded in the snap, but given your other desires as well you may be better off setting this stuff up on your own.

**Comment by jwstolk** [comment]
Thank you for the quick response, that clears things up a lot.
I will re-install without snap and work form there.
