### ISSUE TITLE
ISP Blocking port 80/443 - How to go about putting Nextcloud behind proxy?

### ISSUE THREAD

**Issue by fredrikburmester** [nextcloud/nextcloud-snap#509]
Hi all! 

My ISP seems to be blocking ports 80/443 since I cannot reach my Nextcloud server through those ports, but I am able to when changing the ports to 880/8443. How do I go about setting up HTTPS on my server with letsencrypt? (or some other relatively simple solution). 

Any advice is appreciated!
Thank you!

**Comment by kyrofa** [comment]
I'm afraid Let's Encrypt requires ports 80 and/or 443 as far as I'm aware. You'll be stuck obtaining certificates from elsewhere, or using self-signed ones: `sudo nextcloud.enable-https self-signed`.

**Comment by fredrikburmester** [comment]
Are you sure? According to this [https://github.com/nextcloud/nextcloud-snap] it should work with a proxy.
