### ISSUE TITLE
Tighten default SSL config

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#51]
## Tighten default config

There isn't much to do here, because we need to keep backward compatibility with TLS1.0. It's bad, but we can't do anything about it until the OSX client is updated.

### Changes

* Remove DES3
* 384bits curve only
* Use 2048 bits DH parameters

```
SSLCipherSuite ECDHE+AESGCM:DHE+AESGCM:ECDHE+AES256:DHE+AES256:ECDHE+AES128:DHE+AES:RSA+AESGCM:RSA+AES:!aNULL:!3DES:!MD5:!DSS;
SSLOpenSSLConfCmd DHParameters "${SNAP}/conf/dhparams.2048.pem
```

**Comment by kyrofa** [comment]
Where does the `dhparams.2048.pem` file come from?

Also, I'd rather avoid preload in HSTS, HSTS is trouble enough for home devices, preloading could cause permanent issues.

**Comment by kyrofa** [comment]
Note also that nothing is setting `SSLProxyEngine on`, the extra config items are probably unnecessary.

**Comment by oparoz** [comment]
OK about HSTS.

The DH parameters are generated by us and shipped in the Snap. They can be public. More information here: https://security.stackexchange.com/questions/94390/whats-the-purpose-of-dh-parameters

**Comment by oparoz** [comment]
PR is at https://github.com/nextcloud/nextcloud-snap/pull/63

Improves SSLLabs rating from [100%, 95%, 90%, 90] to [100%, 100%, 100%, 90%] which is the best we can do without removing support for AES128.

**Comment by oparoz** [comment]
Also, I'll let users enable OCSP stapling by themselves if they want to have that feature.

**Comment by oparoz** [comment]
Updated the OP with the proposed changes. There is going to be two configs, a default, unsafe one which supports TLS 1.0 and a safer one which is commented and that users can tweak to meet their requirements.

**Comment by kyrofa** [comment]
I'll go ahead and close this for now.
