### ISSUE TITLE
Can we get an update of this snap?

### ISSUE THREAD

**Issue by Cole128** [nextcloud/nextcloud-snap#516]
This snap uses nextcloud 12, but the whole point of snaps is they have updated software. Can we get an update to nextcloud 13?

**Comment by kyrofa** [comment]
We're working on it, there are bugs in v13 that haven't been solved, yet. More info [in the pull request](https://github.com/nextcloud/nextcloud-snap/pull/442).

**Comment by kyrofa** [comment]
You can update regardless by running `sudo snap refresh nextcloud --channel=13/candidate` if you like.

**Comment by kyrofa** [comment]
Also, to be clear: the point of the snap is not so much to always be up to date, but to be _automatically_ up to date. We focus on the fact that it's automatic: if something is broken, we don't push it out to everyone. v13 is currently broken. This snap will be as up to date as we can make it without (as much as possible) breaking people or providing a bad experience.
