### ISSUE TITLE
Unable to connect to nextcloud

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#517]
I'm suddenly unable to connect to my nextcloud installed a week ago on a Ubuntu server via snap.

Everything was operating successfully locally as well as via a tor hidden service. Then suddenly, I have been unable to connect remotely and now locally as well. Status indicates the Apache server is running, Nextcloud is enabled.

The remote attempts to connect time out with ERR_CONNECTION_TIMED_OUT.

During earlier tests I had been running Nextcloud via port 8888 on http only and that was working successfully via localhost, via 192.168.3:8888 and remotely via a xyz.onion address. I switched the php.config to port 80, 443 and everything came to a screeching halt. I'm alarmed my ability to connect via localhost as well as 192.168.1.3 NAT address has suddenly stopped as well as any remote connections. 

The ping back from the domain I've chosen to use indicates the non-VPN IPv4 address telling me the DNS servers are working correctly but the server is not responding and the ping's time out without receiving anything back.

I normally run a full time VPN on the server however my temporary tests with the VPN tun0 disabled didn't resolve the inability to connect. I've run out of ideas to test and try here. I'd be interested in reviewing the Iprules, Iptable commands anyone has that is port forwarding incoming, outgoing to, from a VPN via tun0 as I suspect that is the problem here.

**Comment by kyrofa** [comment]
Well, why don't we start by eliminating the snap as the issue. Please paste in the output of [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts) (there might be domains in the certificate refresher, filter them out if you like).

**Comment by ASmith-** [comment]
$ ./nextcloud-debugging.sh
<details>
  <summary>Apache</summary>
  <p>

### Status
```
● snap.nextcloud.apache.service - Service for snap application nextcloud.apache
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.apache.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 14:58:05 PDT; 10min ago
 Main PID: 16916 (run-httpd)
   CGroup: /system.slice/snap.nextcloud.apache.service
           ├─16916 /bin/sh /snap/nextcloud/5627/bin/run-httpd -k start -DFORE...
           ├─17338 /bin/sh /snap/nextcloud/5627/bin/httpd-wrapper -k start -D...
           ├─17360 httpd -d /snap/nextcloud/5627 -k start -DFOREGROUND
           ├─17361 httpd -d /snap/nextcloud/5627 -k start -DFOREGROUND
           ├─17362 httpd -d /snap/nextcloud/5627 -k start -DFOREGROUND
           └─17363 httpd -d /snap/nextcloud/5627 -k start -DFOREGROUND

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
### Journal
```
-- No entries --
```
  </p>
</details>

<details>
  <summary>PHP</summary>
  <p>

### Status
```
● snap.nextcloud.php-fpm.service - Service for snap application nextcloud.php-fpm
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.php-fpm.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 14:58:05 PDT; 10min ago
 Main PID: 16913 (start-php-fpm)
   CGroup: /system.slice/snap.nextcloud.php-fpm.service
           ├─16913 /bin/sh /snap/nextcloud/5627/bin/start-php-fpm
           └─17237 php-fpm: master process (/snap/nextcloud/5627/config/php/p...

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
### Journal
```
-- No entries --
```
  </p>
</details>

<details>
  <summary>MySQL</summary>
  <p>

### Status
```
● snap.nextcloud.mysql.service - Service for snap application nextcloud.mysql
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.mysql.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 14:58:05 PDT; 10min ago
 Main PID: 16904 (start_mysql)
   CGroup: /system.slice/snap.nextcloud.mysql.service
           ├─16904 /bin/sh /snap/nextcloud/5627/bin/start_mysql
           ├─17031 /bin/sh /snap/nextcloud/5627/bin/mysqld_safe --datadir=/va...
           ├─17197 /snap/nextcloud/5627/bin/mysqld --basedir=/snap/nextcloud/...
           └─20119 sleep 1

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
### Journal
```
-- No entries --
```
  </p>
</details>

<details>
  <summary>Redis</summary>
  <p>

### Status
```
● snap.nextcloud.redis-server.service - Service for snap application nextcloud.redis-server
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.redis-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 14:58:05 PDT; 10min ago
 Main PID: 16915 (start-redis-ser)
   CGroup: /system.slice/snap.nextcloud.redis-server.service
           ├─16915 /bin/sh /snap/nextcloud/5627/bin/start-redis-server
           └─16983 redis-server 127.0.0.1:0

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
### Journal
```
-- No entries --
```
  </p>
</details>

<details>
  <summary>mDNS Publisher</summary>
  <p>

### Status
```
● snap.nextcloud.mdns-publisher.service - Service for snap application nextcloud.mdns-publisher
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.mdns-publisher.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 14:58:05 PDT; 10min ago
 Main PID: 16893 (delay-on-failur)
   CGroup: /system.slice/snap.nextcloud.mdns-publisher.service
           ├─16893 /bin/sh /snap/nextcloud/5627/bin/delay-on-failure mdns-pub...
           └─16914 mdns-publisher nextcloud

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
### Journal
```
-- No entries --
```
  </p>
</details>

<details>
  <summary>Certificate Renewer</summary>
  <p>

### Status
```
● snap.nextcloud.renew-certs.service - Service for snap application nextcloud.renew-certs
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.renew-certs.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 14:58:05 PDT; 10min ago
 Main PID: 16925 (renew-certs)
   CGroup: /system.slice/snap.nextcloud.renew-certs.service
           ├─16925 /bin/sh /snap/nextcloud/5627/bin/renew-certs
           └─17268 sleep 1d

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
### Journal
```
-- No entries --
```
  </p>
</details>

<details>
  <summary>Nextcloud Cron</summary>
  <p>

### Status
```
● snap.nextcloud.nextcloud-cron.service - Service for snap application nextcloud.nextcloud-cron
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.nextcloud-cron.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 14:58:05 PDT; 10min ago
 Main PID: 16905 (nextcloud-cron)
   CGroup: /system.slice/snap.nextcloud.nextcloud-cron.service
           ├─16905 /bin/sh /snap/nextcloud/5627/bin/nextcloud-cron
           └─17015 sleep 15m

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
### Journal
```
-- No entries --
```
  </p>
</details>

**Comment by kyrofa** [comment]
Oh darn, can you please run `sudo snap disable nextcloud && sudo snap enable nextcloud` and then run the script again?

**Comment by ASmith-** [comment]
$ ./nextcloud-debugging.sh
<details>
  <summary>Apache</summary>
  <p>

### Status
```
● snap.nextcloud.apache.service - Service for snap application nextcloud.apache
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.apache.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 15:32:16 PDT; 43s ago
 Main PID: 26228 (run-httpd)
   CGroup: /system.slice/snap.nextcloud.apache.service
           ├─26228 /bin/sh /snap/nextcloud/5627/bin/run-httpd -k start -DFORE...
           ├─26728 /bin/sh /snap/nextcloud/5627/bin/httpd-wrapper -k start -D...
           ├─26750 httpd -d /snap/nextcloud/5627 -k start -DFOREGROUND
           ├─26751 httpd -d /snap/nextcloud/5627 -k start -DFOREGROUND
           ├─26752 httpd -d /snap/nextcloud/5627 -k start -DFOREGROUND
           └─26753 httpd -d /snap/nextcloud/5627 -k start -DFOREGROUND

Apr 18 15:32:18 server nextcloud.apache[26228]: Waiting for PHP... done
Apr 18 15:32:18 server nextcloud.apache[26228]: System config value redis =>...k
Apr 18 15:32:18 server nextcloud.apache[26228]: System config value redis =>...0
Apr 18 15:32:19 server nextcloud.apache[26228]: System config value memcache...s
Apr 18 15:32:19 server nextcloud.apache[26228]: System config value memcache...s
Apr 18 15:32:19 server nextcloud.apache[26228]: Making sure nextcloud is ful....
Apr 18 15:32:19 server nextcloud.apache[26228]: Nextcloud is already latest ...n
Apr 18 15:32:19 server nextcloud.apache[26228]: All set! Running httpd...
Apr 18 15:32:19 server nextcloud.apache[26228]: No certificates are active: ...y
Apr 18 15:32:19 server nextcloud.apache[26228]: AH00558: httpd: Could not re...e
Hint: Some lines were ellipsized, use -l to show in full.
```
### Journal
```
-- Logs begin at Wed 2018-04-18 15:28:33 PDT, end at Wed 2018-04-18 15:32:59 PDT. --
Apr 18 15:31:32 server systemd[1]: Stopping Service for snap application nextcloud.apache...
Apr 18 15:31:32 server nextcloud.apache[25586]: Making sure nextcloud is setup...
Apr 18 15:32:02 server systemd[1]: snap.nextcloud.apache.service: Stopping timed out. Terminating.
Apr 18 15:32:02 server nextcloud.apache[25586]: Waiting for PHP...
Apr 18 15:32:02 server systemd[1]: Stopped Service for snap application nextcloud.apache.
Apr 18 15:32:02 server systemd[1]: snap.nextcloud.apache.service: Unit entered failed state.
Apr 18 15:32:02 server systemd[1]: snap.nextcloud.apache.service: Failed with result 'timeout'.
Apr 18 15:32:16 server systemd[1]: Started Service for snap application nextcloud.apache.
Apr 18 15:32:16 server nextcloud.apache[26228]: Making sure nextcloud is setup...
Apr 18 15:32:18 server nextcloud.apache[26228]: Waiting for PHP... done
Apr 18 15:32:18 server nextcloud.apache[26228]: System config value redis => host set to string /tmp/sockets/redis.sock
Apr 18 15:32:18 server nextcloud.apache[26228]: System config value redis => port set to integer 0
Apr 18 15:32:19 server nextcloud.apache[26228]: System config value memcache.locking set to string \OC\Memcache\Redis
Apr 18 15:32:19 server nextcloud.apache[26228]: System config value memcache.local set to string \OC\Memcache\Redis
Apr 18 15:32:19 server nextcloud.apache[26228]: Making sure nextcloud is fully upgraded...
Apr 18 15:32:19 server nextcloud.apache[26228]: Nextcloud is already latest version
Apr 18 15:32:19 server nextcloud.apache[26228]: All set! Running httpd...
Apr 18 15:32:19 server nextcloud.apache[26228]: No certificates are active: using HTTP only
Apr 18 15:32:19 server nextcloud.apache[26228]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
```
  </p>
</details>

<details>
  <summary>PHP</summary>
  <p>

### Status
```
● snap.nextcloud.php-fpm.service - Service for snap application nextcloud.php-fpm
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.php-fpm.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 15:32:16 PDT; 43s ago
 Main PID: 26218 (start-php-fpm)
   CGroup: /system.slice/snap.nextcloud.php-fpm.service
           ├─26218 /bin/sh /snap/nextcloud/5627/bin/start-php-fpm
           └─26631 php-fpm: master process (/snap/nextcloud/5627/config/php/p...

Apr 18 15:32:16 server systemd[1]: Started Service for snap application nex...m.
Apr 18 15:32:17 server nextcloud.php-fpm[26218]: Waiting for MySQL... done
Apr 18 15:32:17 server nextcloud.php-fpm[26218]: Obtaining nextcloud mysql c...e
Hint: Some lines were ellipsized, use -l to show in full.
```
### Journal
```
-- Logs begin at Wed 2018-04-18 15:28:33 PDT, end at Wed 2018-04-18 15:32:59 PDT. --
Apr 18 15:31:29 server systemd[1]: Stopping Service for snap application nextcloud.php-fpm...
Apr 18 15:31:29 server systemd[1]: Stopped Service for snap application nextcloud.php-fpm.
Apr 18 15:32:16 server systemd[1]: Started Service for snap application nextcloud.php-fpm.
Apr 18 15:32:17 server nextcloud.php-fpm[26218]: Waiting for MySQL... done
Apr 18 15:32:17 server nextcloud.php-fpm[26218]: Obtaining nextcloud mysql credentials... done
```
  </p>
</details>

<details>
  <summary>MySQL</summary>
  <p>

### Status
```
● snap.nextcloud.mysql.service - Service for snap application nextcloud.mysql
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.mysql.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 15:32:16 PDT; 43s ago
 Main PID: 26245 (start_mysql)
   CGroup: /system.slice/snap.nextcloud.mysql.service
           ├─26245 /bin/sh /snap/nextcloud/5627/bin/start_mysql
           ├─26356 /bin/sh /snap/nextcloud/5627/bin/mysqld_safe --datadir=/va...
           ├─26588 /snap/nextcloud/5627/bin/mysqld --basedir=/snap/nextcloud/...
           └─27002 sleep 1

Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.297472Z 0...)
Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.297535Z 0...)
Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.297655Z 0....
Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.298919Z 0....
Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.300543Z 0...g
Apr 18 15:32:16 server nextcloud.mysql[26245]: Starting MySQL
Apr 18 15:32:17 server nextcloud.mysql[26245]: . *
Apr 18 15:32:17 server nextcloud.mysql[26245]: Checking/upgrading mysql tabl....
Apr 18 15:32:17 server nextcloud.mysql[26245]: Checking if update is needed.
Apr 18 15:32:17 server nextcloud.mysql[26245]: This installation of MySQL is...e
Hint: Some lines were ellipsized, use -l to show in full.
```
### Journal
```
-- Logs begin at Wed 2018-04-18 15:28:33 PDT, end at Wed 2018-04-18 15:32:59 PDT. --
Apr 18 15:31:29 server systemd[1]: Stopping Service for snap application nextcloud.mysql...
Apr 18 15:31:29 server nextcloud.mysql[25535]: Shutting down MySQL
Apr 18 15:31:31 server nextcloud.mysql[25535]: .. *
Apr 18 15:31:31 server systemd[1]: Stopped Service for snap application nextcloud.mysql.
Apr 18 15:32:16 server systemd[1]: Started Service for snap application nextcloud.mysql.
Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.297472Z 0 [Warning] Changed limits: max_open_files: 1024 (requested 5000)
Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.297535Z 0 [Warning] Changed limits: table_open_cache: 431 (requested 2000)
Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.297655Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.298919Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
Apr 18 15:32:16 server nextcloud.mysql[26245]: 2018-04-18T22:32:16.300543Z 0 [ERROR] Aborting
Apr 18 15:32:16 server nextcloud.mysql[26245]: Starting MySQL
Apr 18 15:32:17 server nextcloud.mysql[26245]: . *
Apr 18 15:32:17 server nextcloud.mysql[26245]: Checking/upgrading mysql tables if necessary...
Apr 18 15:32:17 server nextcloud.mysql[26245]: Checking if update is needed.
Apr 18 15:32:17 server nextcloud.mysql[26245]: This installation of MySQL is already upgraded to 5.7.18, use --force if you still need to run mysql_upgrade
```
  </p>
</details>

<details>
  <summary>Redis</summary>
  <p>

### Status
```
● snap.nextcloud.redis-server.service - Service for snap application nextcloud.redis-server
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.redis-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 15:32:16 PDT; 43s ago
 Main PID: 26251 (start-redis-ser)
   CGroup: /system.slice/snap.nextcloud.redis-server.service
           ├─26251 /bin/sh /snap/nextcloud/5627/bin/start-redis-server
           └─26333 redis-server 127.0.0.1:0

Apr 18 15:32:16 server systemd[1]: Started Service for snap application nex...r.
Hint: Some lines were ellipsized, use -l to show in full.
```
### Journal
```
-- Logs begin at Wed 2018-04-18 15:28:33 PDT, end at Wed 2018-04-18 15:32:59 PDT. --
Apr 18 15:32:02 server systemd[1]: Stopping Service for snap application nextcloud.redis-server...
Apr 18 15:32:02 server systemd[1]: Stopped Service for snap application nextcloud.redis-server.
Apr 18 15:32:16 server systemd[1]: Started Service for snap application nextcloud.redis-server.
```
  </p>
</details>

<details>
  <summary>mDNS Publisher</summary>
  <p>

### Status
```
● snap.nextcloud.mdns-publisher.service - Service for snap application nextcloud.mdns-publisher
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.mdns-publisher.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 15:32:16 PDT; 43s ago
 Main PID: 26259 (delay-on-failur)
   CGroup: /system.slice/snap.nextcloud.mdns-publisher.service
           ├─26259 /bin/sh /snap/nextcloud/5627/bin/delay-on-failure mdns-pub...
           └─26303 mdns-publisher nextcloud

Apr 18 15:32:16 server systemd[1]: Started Service for snap application nex...r.
Apr 18 15:32:16 server nextcloud.mdns-publisher[26259]: 2018/04/18 15:32:16 F...
Apr 18 15:32:16 server nextcloud.mdns-publisher[26259]: 2018/04/18 15:32:16 P...
Hint: Some lines were ellipsized, use -l to show in full.
```
### Journal
```
-- Logs begin at Wed 2018-04-18 15:28:33 PDT, end at Wed 2018-04-18 15:32:59 PDT. --
Apr 18 15:32:02 server systemd[1]: Stopping Service for snap application nextcloud.mdns-publisher...
Apr 18 15:32:02 server systemd[1]: Stopped Service for snap application nextcloud.mdns-publisher.
Apr 18 15:32:16 server systemd[1]: Started Service for snap application nextcloud.mdns-publisher.
Apr 18 15:32:16 server nextcloud.mdns-publisher[26259]: 2018/04/18 15:32:16 Failed to listen [ff02::fb]:5353: listen udp6 [::]:5353->ff02::fb: setsockopt: no such device
Apr 18 15:32:16 server nextcloud.mdns-publisher[26259]: 2018/04/18 15:32:16 Publishing server.local -> [192.168.1.3] with 60-second TTL
```
  </p>
</details>

<details>
  <summary>Certificate Renewer</summary>
  <p>

### Status
```
● snap.nextcloud.renew-certs.service - Service for snap application nextcloud.renew-certs
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.renew-certs.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 15:32:16 PDT; 43s ago
 Main PID: 26257 (renew-certs)
   CGroup: /system.slice/snap.nextcloud.renew-certs.service
           ├─26257 /bin/sh /snap/nextcloud/5627/bin/renew-certs
           └─26623 sleep 1d

Apr 18 15:32:16 server systemd[1]: Started Service for snap application nex...s.
Apr 18 15:32:17 server nextcloud.renew-certs[26257]: Saving debug log to /var...
Apr 18 15:32:17 server nextcloud.renew-certs[26257]: No renewals were attempted.
Apr 18 15:32:17 server nextcloud.renew-certs[26257]: No hooks were run.
Hint: Some lines were ellipsized, use -l to show in full.
```
### Journal
```
-- Logs begin at Wed 2018-04-18 15:28:33 PDT, end at Wed 2018-04-18 15:32:59 PDT. --
Apr 18 15:31:31 server systemd[1]: Stopping Service for snap application nextcloud.renew-certs...
Apr 18 15:31:31 server systemd[1]: Stopped Service for snap application nextcloud.renew-certs.
Apr 18 15:32:16 server systemd[1]: Started Service for snap application nextcloud.renew-certs.
Apr 18 15:32:17 server nextcloud.renew-certs[26257]: Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Apr 18 15:32:17 server nextcloud.renew-certs[26257]: No renewals were attempted.
Apr 18 15:32:17 server nextcloud.renew-certs[26257]: No hooks were run.
```
  </p>
</details>

<details>
  <summary>Nextcloud Cron</summary>
  <p>

### Status
```
● snap.nextcloud.nextcloud-cron.service - Service for snap application nextcloud.nextcloud-cron
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.nextcloud-cron.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-18 15:32:16 PDT; 43s ago
 Main PID: 26223 (nextcloud-cron)
   CGroup: /system.slice/snap.nextcloud.nextcloud-cron.service
           ├─26223 /bin/sh /snap/nextcloud/5627/bin/nextcloud-cron
           └─26372 sleep 15m

Apr 18 15:32:16 server systemd[1]: Started Service for snap application nex...n.
Apr 18 15:32:16 server nextcloud.nextcloud-cron[26223]: Waiting for Nextcloud...
Hint: Some lines were ellipsized, use -l to show in full.
```
### Journal
```
-- Logs begin at Wed 2018-04-18 15:28:33 PDT, end at Wed 2018-04-18 15:32:59 PDT. --
Apr 18 15:31:31 server systemd[1]: Stopping Service for snap application nextcloud.nextcloud-cron...
Apr 18 15:31:31 server systemd[1]: Stopped Service for snap application nextcloud.nextcloud-cron.
Apr 18 15:32:16 server systemd[1]: Started Service for snap application nextcloud.nextcloud-cron.
Apr 18 15:32:16 server nextcloud.nextcloud-cron[26223]: Waiting for Nextcloud config dir... done
```
  </p>
</details>

**Comment by kyrofa** [comment]
Okay, that all looks good. Can I see the output of `sudo netstat -tulpn`, please?

**Comment by ASmith-** [comment]
I'm switching over to snap Nextcloud using http port 8080 to see if that makes any difference. I'll need to redirect the domain to 8080, the onion hidden service is already set to 8080. Here is the present output from that netstat command.

$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      1640/smbd       
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      26750/httpd     
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1696/dnsmasq    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      4310/cupsd      
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      16008/master    
tcp        0      0 0.0.0.0:8090            0.0.0.0:*               LISTEN      15483/python3.5 
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      9254/tor        
tcp        0      0 127.0.0.1:25243         0.0.0.0:*               LISTEN      3591/qbittorrent
tcp        0      0 127.0.0.1:9052          0.0.0.0:*               LISTEN      16208/tor       
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      1640/smbd       
tcp        0      0 127.0.0.1:9054          0.0.0.0:*               LISTEN      9347/tor        
tcp        0      0 127.0.0.1:31742         0.0.0.0:*               LISTEN      2748/ruby       
tcp        0      0 127.0.0.1:31743         0.0.0.0:*               LISTEN      2748/ruby       
tcp        0      0 127.0.0.1:31749         0.0.0.0:*               LISTEN      31539/openvpn   
tcp6       0      0 :::139                  :::*                    LISTEN      1640/smbd       
tcp6       0      0 ::1:631                 :::*                    LISTEN      4310/cupsd      
tcp6       0      0 127.0.0.1:13080         :::*                    LISTEN      11488/retroshare_0.
tcp6       0      0 ::1:25                  :::*                    LISTEN      16008/master    
tcp6       0      0 :::445                  :::*                    LISTEN      1640/smbd       
tcp6       0      0 :::52000                :::*                    LISTEN      11812/retroshare_0.
udp        0      0 0.0.0.0:52000           0.0.0.0:*                           11812/retroshare_0.
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           26303/mdns-publishe
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           23921/download_inst
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           23921/download_inst
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1058/avahi-daemon: 
udp        0      0 0.0.0.0:40125           0.0.0.0:*                           31539/openvpn   
udp        0      0 127.0.0.1:25243         0.0.0.0:*                           3591/qbittorrent
udp        0      0 0.0.0.0:42762           0.0.0.0:*                           1058/avahi-daemon: 
udp        0      0 0.0.0.0:44702           0.0.0.0:*                           11488/retroshare_0.
udp        0      0 0.0.0.0:13080           0.0.0.0:*                           11488/retroshare_0.
udp        0      0 0.0.0.0:47926           0.0.0.0:*                           1696/dnsmasq    
udp        0      0 127.0.1.1:53            0.0.0.0:*                           1696/dnsmasq    
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1686/dhclient   
udp        0      0 10.79.10.6:123          0.0.0.0:*                           1548/ntpd       
udp        0      0 192.168.1.3:123         0.0.0.0:*                           1548/ntpd       
udp        0      0 127.0.0.1:123           0.0.0.0:*                           1548/ntpd       
udp        0      0 0.0.0.0:123             0.0.0.0:*                           1548/ntpd       
udp        0      0 192.168.1.255:137       0.0.0.0:*                           1600/nmbd       
udp        0      0 192.168.1.3:137         0.0.0.0:*                           1600/nmbd       
udp        0      0 0.0.0.0:137             0.0.0.0:*                           1600/nmbd       
udp        0      0 192.168.1.255:138       0.0.0.0:*                           1600/nmbd       
udp        0      0 192.168.1.3:138         0.0.0.0:*                           1600/nmbd       
udp        0      0 0.0.0.0:138             0.0.0.0:*                           1600/nmbd       
udp        0      0 0.0.0.0:631             0.0.0.0:*                           4311/cups-browsed
udp        0      0 0.0.0.0:33531           0.0.0.0:*                           11812/retroshare_0.
udp6       0      0 :::5353                 :::*                                1058/avahi-daemon: 
udp6       0      0 :::54515                :::*                                1058/avahi-daemon: 
udp6       0      0 :::123                  :::*                                1548/ntpd

**Comment by ASmith-** [comment]
I really don't want to uninstall snap nextcloud and reinstall snap nextcloud unless that is the last possible solution and choice that I have here which would leave me with additional work in restoring users and linking up the external storage etc. etc.

**Comment by kyrofa** [comment]
No, no need to reinstall, let's figure out what's happening here. Can you explain your setup a little more? Did you use 'snap set' to change the snap's port to 8080, then? Do you have HTTPS enabled? Can you verify that curl works over localhost?

**Comment by ASmith-** [comment]
Oh, I think there's a very real possibility of desperately attempting to repair 'whatever happened here' and spending days on that failed exercise then ending with a uninstall and follow that with a install of the snap nextcloud here.

$ sudo snap set nextcloud ports.http=8080

php.config modifications
  'trusted_domains' => 
  array (
    1 => 'xyz.me',
    2 => 'xyz.onion',
    3 => 'localhost',
    4 => '192.168.1.3',
  ),
  'overwrite.cli.url' => 'http://127.0.0.1:8080',
  'overwritehost' => 'xyz.me:8080',

I had https disabled when everything was 'working' locally and remotely with xyz.onion, localhost, localhost:8080, 127.0.0.1:8080 and 192.168.1.3:8080.
Then adding a clearnet IPv4 domain xyz.me I enabled https and switched over the ports to http 80, https 443. And its been entirely downhill from there. Now nothing connects at all, not even locally. I now have https disabled and trying everything possible to restore nextcloud server functionality that I can.

$ curl localhost
curl: (7) Failed to connect to localhost port 80: Connection refused
$ sudo curl localhost
curl: (7) Failed to connect to localhost port 80: Connection refused

$ ping site.xyz.me  URL Redirect to Port 8080 at the domain provider.
hangs

$ping xyz.me  SRV Record set to Port 8080 both tcp and udp protocols.
hangs

**Comment by ASmith-** [comment]
Here are the iptables I have added but remain unclear about the POSTROUTING iptables command.

$ sudo iptables -A INPUT -p tcp -m multiport --dport 80,443 -s 192.168.2.0/24 -m state --state NEW,ESTABLISHED -j ACCEPT

$ sudo iptables -A OUTPUT -p tcp -m multiport --sport 80,443 -d 192.168.2.0/24 -m state --state ESTABLISHED -j ACCEPT

$ sudo iptables -t nat -A PREROUTING -i eth0 -p tcp -m multiport --dport 80,443 -j DNAT --to-destination 192.168.2.1

POSTROUTING iptable rule?

**Comment by ASmith-** [comment]
Hi kyrofa,
I'm getting a curl response now and its giving me a 500 Internal Server Error. Do you or anyone else here have any suggestions and solutions?

$ curl -v domain.mine
* Rebuilt URL to: domain.mine/
*   Trying xx.xx.1xx.6...
* Connected to domain.mine (xx.xx.1xx.6) port 80 (#0)
> GET / HTTP/1.1
> Host: domain.mine
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Date: Sat, 21 Apr 2018 21:25:09 GMT
< Server: Apache/2.4.28 (Unix)
< X-Powered-By: PHP/7.1.15
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Length: 0
< Connection: close
< Content-Type: text/html; charset=UTF-8
< 
* Closing connection 0

**Comment by kyrofa** [comment]
In the same directory as the Apache log, there's a PHP log. There's also a Nextcloud log in the data directory. See anything interesting there?

**Comment by ASmith-** [comment]
I didn't see anything that would help me in the log kyrofa, I'll remove and install snap nextcloud again and then work on returning the website nearly to the point where I had been previously. Thanks for your advise and help.
