### ISSUE TITLE
[bug or memory issue?] '... took too long to respond.' - After moving and deleting large files 

### ISSUE THREAD

**Issue by fredrikburmester** [nextcloud/nextcloud-snap#518]
After removing and moving large files I couldn't reach my server anymore. The error message in the browser was '... took too long to respond.' The error message in the server was:

`Out of memory: Kill process 7170 (php-fpm) score 374 or sacrifice child`

Then it killed the above process but the server never recovered.
How can I avoid this is the future? Is it really my server running out of memory or is this a bug? 

Thanks!

**Comment by kyrofa** [comment]
Sounds like you're running out of RAM. What kind of machine is this? Did you check the state of the memory when this was happening?

**Comment by fredrikburmester** [comment]
No, unfortunately not. I'm running on Ubuntu Server on a VM. Admittedly there's not a lot of RAM dedicated to that machine, but how much would the server need to move and delete some files? It seems a bit excessive to crash because of that, no?

**Comment by r4co0n** [comment]
@fredrikburmester, this is what linux does when it runs out of RAM - This can't be fixed here. But you can use a swap partition/file to increase your available memory.
It seems you have no swap or the swap is too small, which is something you would have chosen to do, by using a specialised distro or intentionally configuring your system this way. Additionally, you can monitor your server and try to recover from failures like this one by restarting the service. I have swap configured and written a simple health-check script that would have restarted the nextcloud snap if it remained unresponsive for too long.

**Comment by kyrofa** [comment]
@r4co0n is spot on. The entire Nextcloud system is pretty memory hungry, I'm afraid.

**Comment by r4co0n** [comment]
@kyrofa: Would a script checking the health of the server be a worthwhile addition to this snap? I reckon checking if `/`returns status 2xx (after redirection) would already catch a lot of problems. The script would restart php-fpm if it receives another status or the request times out after 30 seconds.

As a side note, I have no trouble running this snap with 1GB of RAM (+swap) and a single vCPU. I only have around ~420MB RAM in used state right now and the system has no other services configured.

**Comment by fredrikburmester** [comment]
@r4co0n Yeah sorry, did the asking before the googleing. What health-check script are you using and how would I go about setting that up?

**Comment by fredrikburmester** [comment]
@r4co0n I checked and I do indeed have a swap file. I'm not sure how it is configured or how the system is using it right now. But it is the same size as my RAM, i.e. 1GB.
