### ISSUE TITLE
[BUG] php.config Trusted Domains does not accept the v3 new tor .onion addresses

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#520]
The Snap installed Nextcloud php.config Trusted Domains does not accept the v3 new tor .onion addresses

The onion router is switching over to a new v3 tor .onion address and soon all hidden tor webservers will have updated to use the new more secure v3 tor .onion urls.

My initial tests with a Snap installed Nextcloud install indicated the variable length provided for the 'Trusted Domains' does not take into account the new length of the .onion v3 addresses. It acts like its ignoring them entirely. What is likely happening is the variable for the added trusted domain is exceeding the maximum length for that variable the developers have coded and its ignoring it.

Tor v3 Example
bhsxqbnxqu2zfedlbehijbkbfp2337rtokusaqyrecvmy4zenst2ykid.onion

That is now 63 characters long including the .onion domain.

Please update the Trusted Domains variable size to allow the new v3 tor .onion addresses asap.

Meanwhile Snap Nextcloud installers that chose to operate via a tor routed domain must use the now old v2 .onion addressing which is 23 characters long including the .onion domain.

Tor v2 Example
bxip2zrhw3owqa5x.onion

**Comment by kyrofa** [comment]
I'm afraid we're bound by what upstream Nextcloud does here. Please log this bug [upstream](https://github.com/nextcloud/server).
