### ISSUE TITLE
Let's Encrypt installation gives a lot of errors

### ISSUE THREAD

**Issue by michelvandun** [nextcloud/nextcloud-snap#521]
I've tried to install let's encrypt on a NextCloud box. I did use the following command : sudo nextcloud.enable-https lets-encrypt.
I do use 

core       16-2.32.5    4489  stable    canonical  core
nextcloud  12.0.5snap2  5633  stable/…  nextcloud  -
snapweb    0.26-11      323   beta      canonical  -

I did give the e-mail, I did give in the domain, and then..

Please enter an email address (for urgent notices or key recovery): blabla.bla
Please enter your domain name(s) (space-separated): sub.domain.com
Attempting to obtain certificates... done
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
Restarting apache... ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
done

and It does not work.

**Comment by kyrofa** [comment]
Those errors are warnings, not actually errors. Also, they have nothing to do with the snap, something is weird with the Box image. Regardless, they should be harmless: do you see other errors further on in the log?

**Comment by michelvandun** [comment]
Can you tell me where this log is placed on the box?

**Comment by michelvandun** [comment]
the journalctl -xe command give me:
 Apr 24 19:19:21 ubuntu-standard nextcloud.mysql[1364]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be prel.

further no issue in this log file

**Comment by kyrofa** [comment]
Maybe I should have started with this: what makes you say "it does not work"?

**Comment by michelvandun** [comment]
I started firefox and give the https://domain name in. It says your connection in not secure. So I presume it does not work

**Comment by kyrofa** [comment]
Firefox should tell you WHY it's insecure. Any chance you're visiting it with a domain that you DIDN'T use when getting the cert? Perhaps with (or without) a www?

**Comment by michelvandun** [comment]
It is a subdomain, is that a problem?
Further does firefox give me that the website: the website does not supply  ownership information and verified by : not specified. 
Connection not encrypted. De site does not support encryption for the page you are viewing.

**Comment by kyrofa** [comment]
> It is a subdomain, is that a problem?

Yes, unless it's a wildcard cert, certs only cover the domains you requested them to cover. Sounds like things are working fine here, just make sure you generate the cert for the domain(s) you're actually using.

**Comment by michelvandun** [comment]
Ok, thank for the effort. I try again, let see what happens.

**Comment by kyrofa** [comment]
Feel free to continue the discussion here if you still run into issues.
