### ISSUE TITLE
ERR_CONNECTION_REFUSED On 2 fresh installations on 2 different networks

### ISSUE THREAD

**Issue by ishmumx** [nextcloud/nextcloud-snap#524]
I installed nextcloud via snap on Ubuntu 16 and 17 machiens on two different networks:

> sudo snap install nextcloud

After installation, I end up with ERR_CONNECTION_REFUSED at the nextcloud IP no matter if I reboot, disable ufw or whatever I try to do.  

Any help would be appreciated

**Comment by neo-de** [comment]
Did you perform the initial setup on localhost or via cli?
