### ISSUE TITLE
Shared Music Folder with Friends Group is not reporting any scanned music files by users in that group

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#525]
Shared Music Folder with Friends Group is not reporting any scanned music files by users in that group

I added a Music Folder using the external file storage app and added that folder to the Friends group in the external storage application addon, the icon is Green the folder is shared with the Friends group and users in the Friends group can see the Music folder and open it up to individual music files.

The Issue is
Users in the Friends group attempting to use the Audio Player or Music application tool are being told there are zero (0) music files resulting from the audio, music player's scans. I have consequently added a Friends and Visitors group folder (1 each) with a smaller sampling of music files (these are royalty-free music files) which both the audio and music player addon's do properly scan but not the external drives music files.

I later as mentioned above, I enabled the Group Folder application and have placed a small sampling of music files into a Group Folder shared with Friends until I can sort out the above issue. 

I have issued the following .occ command in an attempt to solve this still existing issue
$ sudo nextcloud.occ files:scan -all -vvv

The terminal output shows each user whose permissions include the Friends group files which were recently included, however the issue remains. The Audio Player and Music addon's are not scanning the external drive Music folders.

Thanks for your help on this issue.

**Comment by ASmith-** [comment]
No help on this, closed.

**Comment by kyrofa** [comment]
@ASmith- this repository is mostly for support of the snap specifically, if you're experiencing general Nextcloud issues or have questions that don't relate specifically to the snap, you'll probably have more luck hopping in #nextcloud on IRC, or logging an issue on the [Nextcloud server itself](https://github.com/nextcloud/server).
