### ISSUE TITLE
Fix apparmor policy for MySQL

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#53]
syslog is getting spammed like crazy by MySQL and all those writes have a negative effect on performance.
Maybe it's a problem with the image itself... but it would be good to get rid of the problem one way or another.

```
Sep 24 12:35:30 ubuntu-standard kernel: [35131.515928] audit: type=1400 audit(1474720530785:35364): apparmor="DENIED" operation="open" profile="snap.nextcloud.mysql" name="/etc/ld.so.preload" pid=7741 comm="sleep" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by oparoz** [comment]
Reported the problem upstream https://bugs.launchpad.net/snappy/+bug/1627813

**Comment by oparoz** [comment]
It has gotten worse... Anything built on Launchpad will just refuse to start

```
Sep 30 14:56:07 ubuntu-standard kernel: [408245.611447] audit: type=1400 audit(1475247367.477:404739): apparmor="DENIED" operation="open" profile="/usr/lib/snapd/snap-confine" name="/etc/ld.so.preload" pid=15806 comm="ubuntu-core-lau" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 30 14:56:07 ubuntu-standard kernel: [408245.633836] audit: type=1400 audit(1475247367.497:404740): apparmor="DENIED" operation="open" profile="snap.nextcloud.apache" name="/etc/ld.so.preload" pid=15806 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

```

**Comment by oparoz** [comment]
Upstream bug report:
https://bugs.launchpad.net/snappy/+bug/1627813

**Comment by Guillaume99** [comment]
I also got

> Dec  8 03:39:28 localhost kernel: [   58.048091] audit: type=1400 audit(1481168368.384:50): apparmor="DENIED" operation="exec" profile="snap.nextcloud.mysql" name="/bin/run-parts" pid=1613 comm="mysql.server" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Dec  8 03:39:28 localhost kernel: [   58.600164] audit: type=1400 audit(1481168368.936:51): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=1741 comm="ps" requested_mask="trace" denied_mask="trace" peer="unconfined"
Dec  8 03:39:28 localhost kernel: [   58.600409] audit: type=1400 audit(1481168368.936:52): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=1741 comm="ps" requested_mask="trace" denied_mask="trace" peer="unconfined"
Dec  8 03:39:28 localhost kernel: [   58.600532] audit: type=1400 audit(1481168368.936:53): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=1741 comm="ps" requested_mask="trace" denied_mask="trace" peer="unconfined"

**Comment by kyrofa** [comment]
Upstream bug is fixed.
