### ISSUE TITLE
How can I internally upload a folder filled with files and/possibly including sub-folders with files?

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#532]
How can I internally upload a folder filled with files and/possibly including sub-folders with files?

I have terabytes of files and many folders I need to place on my Nextcloud, what is the most used and expedited method commonly used to accomplish this task?

I thought I briefly saw a 'drag and drop' query inside the snap installed Nextcloud for my Music folder which might suggest there is an ability to upload entire folders and folders with sub-folders containing files.

Currently the simple 'upload a file' only uploads individual files, not folders nor sub-folders even if control-a selects all the files in a directory to upload.

**Comment by kyrofa** [comment]
Yeah the drag/drop doesn't work for entire directory trees. I recommend using the [clients](https://nextcloud.com/install/#install-clients) for that.

**Comment by kyrofa** [comment]
You can also put them on in the data directory outside of nextcloud (e.g. by mounting the HD directly, or using rsync) and run `nextcloud.occ files:scan` after the transfer has completed to get Nextcloud to find them.

**Comment by ASmith-** [comment]
Please do everyone a favor when they come asking about that fundamental feature on a application that should have that feature for peers starting with version 1.0. The ability to Upload entire Folders filled with files and sub-folders is found in Flowupload application. I knew one existed, I remembered I saw that feature while looking around and for something else. It took me 3 days to locate it because it seems no one whatsoever knew that feature even existed nor which Nextcloud application addon contained it.

**Comment by auberginepop** [comment]
Probably worth noting that the app description includes, "Early alpha state, not approved for security."
[https://github.com/e-alfred/flowupload](url)

**Comment by kyrofa** [comment]
Indeed, I was unaware of this application as well.
