### ISSUE TITLE
Ship updated OpenSSL 1.1

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#54]
I couldn't find a package for version 1.1, but perhaps we could compile it ourselves?
One big advantage is to be able to use Chacha20 for mobile.

**Comment by bithex** [comment]
Recommend updaging openssl soon as the current stable version (12.0.4snap1) comes out bad with security/vulnerability scanners, with critical issues reported for support of OpenSSL 1.0.2g.
The server header reads "Apache/2.4.28 (Unix) OpenSSL/1.0.2g"

**Comment by kyrofa** [comment]
That's because security scanners often look at only the version, and not the patches applied. Don't worry, these are false positives. See #286 for more details.
