### ISSUE TITLE
How to manually install an app?

### ISSUE THREAD

**Issue by stone212** [nextcloud/nextcloud-snap#555]
I am new to snaps but it looks like the filesystem is not writeable.  So how do I install an app manually?

**Comment by stone212** [comment]
I do not think that it was caused by adding an app this way but I did add an app this way and also my "Admin" menu item is missing.  I have removed the app but "Admin" is still missing.

**Comment by stone212** [comment]
@kyrofa Yes this worked.  I re-enabled the app and it works fine.  I can add this to the wiki but which wiki and do I have access to it?

**Comment by kyrofa** [comment]
[This one](https://github.com/nextcloud/nextcloud-snap/wiki). Do you have the ability to edit it?

**Comment by stone212** [comment]
I do not see where I can edit it so I think that means the option is not available to me currently.  No pencil icon, no word "Edit" on the page.

I am happy to add this but since your suggestion was correct without modification and since giving me access to the wiki might take as long as adding the entry yourself I would not feel you are being rude if you decide to just add this entry.
