### ISSUE TITLE
Google Drive external drive no longer available after update to 13.0.2

### ISSUE THREAD

**Issue by rdao** [nextcloud/nextcloud-snap#565]
Hi!

After last nights snap update to v13.0.2 my external storage on Google Drive is no longer available

The external storage pages says: 'Unknown: googledrive'. For adding new external storage only the following options are available: Amazon S3, Nextcloud, Openstack Object Storage, SFTP, WebDAV.

What can I do to fix this?

Kind regards,
Roland

**Comment by pachulo** [comment]
It seems that Google Driver and Dropbox were moved to external applications: 

- https://docs.nextcloud.com/server/13/admin_manual/configuration_files/external_storage_configuration_gui.html#available-storage-backends
- https://github.com/owncloud/files_external_gdrive

Could it be that now you need to install them?

**Comment by rdao** [comment]
Apparently so, but still in (early?) development and to me it is unclear how to install it.

**Comment by SkyWheel** [comment]
Can Google drive and Dropbox WebDAV? If yes, connect them in this way

**Comment by rdao** [comment]
Google Drive doesn't have WebDAV. I don't know for (or use) Dropbox.

**Comment by pachulo** [comment]
To install an application manually you should follow the steps explained in https://github.com/nextcloud/nextcloud-snap/issues/555#issuecomment-387420025

**Comment by rdao** [comment]
I cloned the 'files_external_gdrive' into the 'extra-apps' folder. The app shows up in the Apps menu, but the 'Enable' buttun is greyed out. A restart of Nextcloud did not help.

**Comment by kyrofa** [comment]
When you can't enable an app, Nextcloud typically says why. Do you see any explanation around the grayed-out button?

**Comment by rdao** [comment]
Nope. Below screenshot is from the 'Disabled apps' menu. 'Direct menu' also has its button greyed out without explanation.
![image](https://user-images.githubusercontent.com/39113823/39908688-844b6696-54ef-11e8-98a1-58f3e82ac897.png)

**Comment by PnjDbq** [comment]
Was interested in trying this myself, so gave it a go.  Saw the discussion about how apparently this app is not supported in v13 and where to get the beta: 
https://help.nextcloud.com/t/nextcloud-13-and-google-drive/27052

Note:  The above thread references a different app than pachulo linked to.

Downloaded and unzipped to `/var/snap/nextcloud/current/nextcloud/extra-apps/` without any issue.  I also noticed that the app is up to v0.2.2 and your screenshot is at v0.1, but that's not really the issue.

When trying to enable via web interface I did get the error message:

> Error:  this app cannot be enabled because it makes the server unstable

![capture](https://user-images.githubusercontent.com/37458932/40093147-70be9810-5886-11e8-86ef-6d2f7e3370db.PNG)

Also saw two PHP errors in the log:

`require_once(/var/snap/nextcloud/6916/nextcloud/extra-apps/files_external_gdrive/vendor/autoload.php): failed to open stream: No such file or directory at /var/snap/nextcloud/6916/nextcloud/extra-apps/files_external_gdrive/appinfo/app.php#22`


`require_once(): Failed opening required '/var/snap/nextcloud/6916/nextcloud/extra-apps/files_external_gdrive/vendor/autoload.php' (include_path='/snap/nextcloud/6916/htdocs/3rdparty/pear/console_getopt:/snap/nextcloud/6916/htdocs/3rdparty/pear/pear_exception:/snap/nextcloud/6916/htdocs/3rdparty/pear/pear-core-minimal/src:/snap/nextcloud/6916/htdocs/3rdparty/pear/archive_tar:/snap/nextcloud/current/htdocs/apps:/var/snap/nextcloud/current/nextcloud/extra-apps') at /var/snap/nextcloud/6916/nextcloud/extra-apps/files_external_gdrive/appinfo/app.php#22]`


This looks like a known issue: https://github.com/NastuzziSamy/files_external_gdrive/issues/1

**Comment by pachulo** [comment]
This issue is not specific to the nextcloud-snap, should we close it @kyrofa ?

Thanks for the info @PnjDbq !

**Comment by kyrofa** [comment]
Yeah, good idea @pachulo.
