### ISSUE TITLE
"Admin" Menu Item Missing 

### ISSUE THREAD

**Issue by stone212** [nextcloud/nextcloud-snap#567]
This is a duplicate of https://github.com/nextcloud/nextcloud-snap/issues/564 which was closed but should not have been.

During the 12 hours when the snap was upgrading from 12 to 13, I did nothing else.  Then the "Admin" menu was gone.  It is still gone.

What is the URL of the Admin page?  Maybe I can find it manually?

**Comment by pachulo** [comment]
The URL is: http://your-domain.com/index.php/settings/admin

**Comment by stone212** [comment]
@pachulo That URL works.  So I have a workaround until the Issue is solved.  Thank you.

**Comment by stone212** [comment]
Yes it is.  I did not try "Settings" because I was already trained by v.12 to only expect personal settings there.  This answers the Issue.  Thank you.
