### ISSUE TITLE
v13 "Help" shows v12 Docs

### ISSUE THREAD

**Issue by stone212** [nextcloud/nextcloud-snap#568]
The snap upgraded but when I go to "Help" the docs are still the v12 docs.

**Comment by pachulo** [comment]
In my server I'm seeing the documentation for v13: http://x.x.x.x/index.php/settings/help

**Comment by kyrofa** [comment]
Mine is also v13. Are you sure you're not using the `12` track?

**Comment by stone212** [comment]
@kyrofa It looks like v.13 based on: "installed:      13.0.2snap1"

@pachulo Here is the output you asked for:

`root@files:~# snap --version 
snap    2.32.6
snapd   2.32.6
series  16
ubuntu  16.04
kernel  4.4.0-121-generic`

`root@files:~# snap info nextcloud
name:      nextcloud
summary:   Nextcloud Server - A safe home for all your data
publisher: nextcloud
contact:   https://github.com/nextcloud/nextcloud-snap
license:   unknown
description: |
  Access, share and protect your files, calendars, contacts, communication and
  more at home and in your enterprise.
commands:
  - nextcloud.disable-https
  - nextcloud.enable-https
  - nextcloud.manual-install
  - nextcloud.mysql-client
  - nextcloud.mysqldump
  - nextcloud.occ
services:
  nextcloud.apache:         simple, enabled, active
  nextcloud.mdns-publisher: simple, enabled, active
  nextcloud.mysql:          simple, enabled, active
  nextcloud.nextcloud-cron: simple, enabled, active
  nextcloud.php-fpm:        simple, enabled, active
  nextcloud.redis-server:   simple, enabled, active
  nextcloud.renew-certs:    simple, enabled, active
snap-id:   njObIbGQEaVx1H4nyWxchk1i8opy4h54
tracking:  stable
refreshed: 2018-05-08T20:49:52+02:00
installed:      13.0.2snap1       (6916) 205MB -
channels:                                
  stable:       13.0.2snap1       (6916) 205MB -
  candidate:    ↑                              
  beta:         13.0.2snap1       (6932) 205MB -
  edge:         master-2018-05-10 (6992) 203MB -
  11/stable:    11.0.8snap1       (6942) 202MB -
  11/candidate: ↑                              
  11/beta:      ↑                              
  11/edge:      ↑                              
  12/stable:    12.0.7snap1       (6949) 205MB -
  12/candidate: ↑                              
  12/beta:      ↑                              
  12/edge:      12-2018-05-10     (6979) 205MB -
  13/stable:    13.0.2snap1       (6916) 205MB -
  13/candidate: ↑                              
  13/beta:      ↑                              
  13/edge:      13-2018-05-10     (6980) 205MB -
`

**Comment by kyrofa** [comment]
Can I please see the output of `sudo nextcloud.occ config:list system`?

**Comment by stone212** [comment]
@kyrofa Here it is:


> root@files:~# nextcloud.occ config:list system
> {
>     "system": {
>         "apps_paths": [
>             {
>                 "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
>                 "url": "\/apps",
>                 "writable": false
>             },
>             {
>                 "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
>                 "url": "\/extra-apps",
>                 "writable": true
>             }
>         ],
>         "supportedDatabases": [
>             "mysql"
>         ],
>         "memcache.locking": "\\OC\\Memcache\\Redis",
>         "memcache.local": "\\OC\\Memcache\\Redis",
>         "redis": {
>             "host": "***REMOVED SENSITIVE VALUE***",
>             "port": 0
>         },
>         "instanceid": "***REMOVED SENSITIVE VALUE***",
>         "passwordsalt": "***REMOVED SENSITIVE VALUE***",
>         "secret": "***REMOVED SENSITIVE VALUE***",
>         "trusted_domains": [
>             "files.mysite.com",
>             "nextcloud.mysite.com"
>         ],
>         "datadirectory": "***REMOVED SENSITIVE VALUE***",
>         "overwrite.cli.url": "https:\/\/files.mysite.com",
>         "dbtype": "mysql",
>         "version": "13.0.2.1",
>         "dbname": "***REMOVED SENSITIVE VALUE***",
>         "dbhost": "***REMOVED SENSITIVE VALUE***",
>         "dbport": "",
>         "dbtableprefix": "oc_",
>         "mysql.utf8mb4": true,
>         "dbuser": "***REMOVED SENSITIVE VALUE***",
>         "dbpassword": "***REMOVED SENSITIVE VALUE***",
>         "installed": true,
>         "maintenance": false,
>         "mail_from_address": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtpmode": "smtp",
>         "mail_smtpauthtype": "LOGIN",
>         "mail_domain": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtpport": "587",
>         "mail_smtpsecure": "tls",
>         "mail_smtpauth": 1,
>         "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
>         "loglevel": 2
>     }
> }

**Comment by pachulo** [comment]
Are you still seeing the old documentation with the latest version (13.0.4) @stone212 ?

**Comment by stone212** [comment]
@pachulo I see a help page for v13 but I don't think I'm using 13.0.4.  But I want to track stable again.  Can you tell me how?  Here is my output:

```
snap-id:      njObIbGQEaVx1H4nyWxchk1i8opy4h54
tracking:     beta/pr-573
refresh-date: 14 days ago, at 20:52 CEST
channels:                                      
  stable:       13.0.4snap1       (7658) 206MB -
  candidate:    13.0.4snap1       (7658) 206MB -
  beta:         13.0.4snap1       (7654) 206MB -

```
