### ISSUE TITLE
Folders disappeared

### ISSUE THREAD

**Issue by newmediologo** [nextcloud/nextcloud-snap#572]
Hi.. Hi've remove the SD Card from the Raspy to make an image backup, when I've reboot the system I've forgot to mount the the external drive in /media/sda1 where is the data dir.. Open Nextcloud web interface and clicking on the folders they disappeared one by one.. The Folders and all the data are always in place checked by terminal.. How i can do to restore the folders in Nextcloud.. Thanks

**Comment by newmediologo** [comment]
@kyrofa the rescan command does not work the output is:

nextcloud.occ: command not found

**Comment by kyrofa** [comment]
Huh. And you're running the snap? What OS? Can I see the output of `snap version`, please?

**Comment by newmediologo** [comment]
snap    2.32.6
snapd   2.32.6
series  16
ubuntu  16.04
kernel  4.4.0-1009-raspi2

**Comment by kyrofa** [comment]
Alright, try `sudo /snap/bin/nextcloud.occ files:scan --all`

**Comment by newmediologo** [comment]
Now the scan works and all is in the right place.. May be I need to setup automount for the drive.. Thank You Very much @kyrofa

**Comment by kyrofa** [comment]
No problem! I'll go ahead and close this, then :) .
