### ISSUE TITLE
Unable to connect with Nextcloud while snap installed Rocketchat concurrently runs on www port 8080

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#574]
Unable to connect with Nextcloud while the snap installed Rocketchat-server concurrently runs on a www port 8080, the rocketchat-server is set internally for port 3000. The domain.name port 8080 proxys to rocketchat-server's internal port 3000.

Both snap installed packages (nextcloud, rocketchat) operate fine individually and while the other is not concurrently running each correctly connects to their individual domain.names on the www.

However, If I run the snap installed rocketchat-server set for www port 8080, my snap installed nextcloud running on the same system refuses to connect and serve up its content.

I had hoped to avoid that by running the rocketchat-server on a non-conflicting port. My nextcloud is using the regular 80/443 port setup and both Nextcloud and Rocketchat-server have passed the let's encrypt checks and have received their individual ssl certificates on their individual domain.names.

Any useful thoughts or helpful command suggestions I can carry out to tweak the nextcloud and/or rocketchat-server to cooperate with a concurrently running snap installed Nextcloud running on the same system?

**Comment by r4co0n** [comment]
Did you check if the output of `netstat -tulpn` shows something listening on port 80 or 443 when only rocketchat is running? If you are unsure how to interpret what this gives you, you can post the output here.
