### ISSUE TITLE
Nextcloud is not installed - only a limited number of commands are available

### ISSUE THREAD

**Issue by KyleTryon** [nextcloud/nextcloud-snap#584]
`Nextcloud is not installed - only a limited number of commands are available`

I am following the tutorial below but it isn't very relevant.
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-16-04

Error:
`Nextcloud is not installed - only a limited number of commands are available`

Steps to reproduce:

1.  `sudo snap install nextcloud` successful install
2. `sudo nextcloud.manual-install sammy password` This fails

**Comment by NikosEfthias** [comment]
same issue

**Comment by kyrofa** [comment]
That's not an error, it's a warning from `occ`, which is expected. Are you sure that it fails? Can I please see the entire output?

**Comment by afterconnery** [comment]
I am also getting this issue. Below is my output

sean@embyserver ~> sudo snap install nextcloud
nextcloud 13.0.2snap1 from 'nextcloud' installed
sean@embyserver ~> sudo nextcloud.manual-install sammy mypassword
Nextcloud is not installed - only a limited number of commands are available

**Comment by afterconnery** [comment]
well after a system reboot it worked and I have other issues to figure out, but this one cleared up :)

**Comment by pachulo** [comment]
Did it work for you @KyleTryon @NikosEfthias ?

**Comment by kyrofa** [comment]
This is not an issue. It's a warning from `occ`. The command eventually completes. I'll close this now, let me know if an actual failure occurs.

**Comment by NikosEfthias** [comment]
restart didnt fix my issue and i get following error
<img width="542" alt="pasted_image_6_17_18__2_30_am" src="https://user-images.githubusercontent.com/9097437/41502914-7073b462-71d6-11e8-8b71-a670b470d5e9.png">

**Comment by NikosEfthias** [comment]
and i always get this domain i snot trusted error and im unable to add it to the trusted domains

**Comment by NikosEfthias** [comment]
@kyrofa i dont know how the other people uses this snap but for me whatever i do this doesnt work.
I restarted the machine and everything but i cannot even start nextcloud it always give me untrusted domain error and i cannot find the config file anywhere and also commands give the error i posted above

**Comment by r4co0n** [comment]
Try `snap run nextcloud.manual-install ***** ********` as root or append `sudo `.

**Comment by treedbox** [comment]
@KyleTryon you need access your IP or domain and proceed with the installation,
then you can use nextcloud commands like: `nextcloud.occ`

**Comment by JeffRockatansky** [comment]
@treedbox 
> you need access your IP or domain and proceed with the installation

* What do you mean? An SSH?
* What should I do if I'm getting this message from a localhost on a machine that I'm using to host Nextcloud?

**Comment by dhowe** [comment]
Same issue here

**Comment by rkhyd** [comment]
> Try `snap run nextcloud.manual-install ***** ********`. Run this as root or append `sudo `.

this worked for me as i installed using snap. Thank you.

**Comment by neonota** [comment]
I'm also having the same issue ..

Nextcloud is not installed - only a limited number of commands are available


  There are no commands defined in the "config:system" namespac
  e. 

Though it worked on my other server
