### ISSUE TITLE
Chrome ERR_SSL_PROTOCOL_ERROR after SSL migration

### ISSUE THREAD

**Issue by luky92** [nextcloud/nextcloud-snap#587]
After enabling https i get the error above in chrome when trying to access the installation

**Comment by r4co0n** [comment]
Nobody will be able to help you with this unless they first run into the same issue.

Which steps did you take to enable https? Where there any errors/warnings while you did that?

Is https working now, and only Chrome can't connect? Did you check with another browser? Did you check with another machine (and Chrome)?

**Comment by luky92** [comment]
I forwarded ports to the machine that has nextcloud installation on it and then run sudo nextcloud.enable-https lets-encrypt on it and it runs without erorrs. I used to use it without SSL thats why i wrote about migration. I tested it on other browsers it just ends up with connection error

**Comment by r4co0n** [comment]
You should check in the snap's apache log if you can find an indication why this is happening. Using a search engine on `ERR_SSL_PROCOTOL_ERROR` turns up lots of client-side solutions. Alternatively, if Chrome throws up the same error on another machine, I would take a closer look on the server-side.

It could be as simple as your antivirus software messing with the TLS handshake.

**Comment by luky92** [comment]
`[Sun Jun 03 13:51:42.099588 2018] [ssl:warn] [pid 17203:tid 140587260159872] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Jun 03 13:51:42.104615 2018] [ssl:warn] [pid 17203:tid 140587260159872] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 03 13:51:42.105211 2018] [mpm_event:notice] [pid 17203:tid 140587260159872] AH00489: Apache/2.4.33 (Unix) OpenSSL/1.0.2g configured -- resuming normal operations
[Sun Jun 03 13:51:42.105232 2018] [core:notice] [pid 17203:tid 140587260159872] AH00094: Command line: 'httpd -d /snap/nextcloud/6916 -D EnableHTTPS -D EnableHSTS -D FOREGROUND'
[Sun Jun 03 13:51:42.105982 2018] [unixd:alert] [pid 17204:tid 140587260159872] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Sun Jun 03 13:51:42.106068 2018] [unixd:alert] [pid 17205:tid 140587260159872] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Sun Jun 03 13:51:42.106340 2018] [unixd:alert] [pid 17206:tid 140587260159872] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive`


here is the apache log it seems that servername variable is not set is there any way I could modify the config?

**Comment by luky92** [comment]
Turns out it was a misconfiguration on my part ( I redirected port 443 to 80 instead of 443)
