### ISSUE TITLE
Could not find a required package in 'build-packages': libpng12-dev

### ISSUE THREAD

**Issue by robotichead** [nextcloud/nextcloud-snap#591]
Hello,

Please note I am new, and mostly in the experimental stage of snaps. I am both asking for help and trying to fix a potential issue. Any help or tips are appreciated.

### Prerequisites
Ubuntu 18.04
Snap

### Method

1. Open terminal
2. Navigate to the snaps folder of your choosing, for this example it is ~/snap
3. Get nextcloud-snap using "git clone https://github.com/nextcloud/nextcloud-snap"
4. cd ./nextcloud-snap
5. Run command "snapcraft"

### Expected Results

Snap to be built

### Actual Results
The following output from terminal

-- TERMINAL OUTPUT --
cd ./snap/nextcloud-snap/
~/snap/nextcloud-snap$ snapcraft
Loaded local plugin for apache
Loaded local plugin for php
Loaded local plugin for redis
Could not find a required package in 'build-packages': libpng12-dev
-- END TERMINAL OUTPUT --

Please note, I tried installing libpng12-dev as stated https://www.linuxuprising.com/2018/05/fix-libpng12-0-missing-in-ubuntu-1804.html

In the file ./snap/snapcraft.yaml I have made the following changes

line 191: libpng-16-16
line 195: libpng-dev

However this change might not work for Ubuntu Core, or any earlier versions of Ubuntu (like 16.04). Is there an option-build-packages where we can place these?

**Comment by pachulo** [comment]
If your running Ubuntu 18.04 I would say that your best option is to compile the snap with:

`snapcraft cleanbuild`

Because right now this snap is meant to be build in an Ubuntu 16.04 environment.
Anyway, you will find more help in the snapcraft forums: https://forum.snapcraft.io/

**Comment by kyrofa** [comment]
Indeed, the snap is meant to be built on 16.04.
