### ISSUE TITLE
imagemagick not installed? (favicon)

### ISSUE THREAD

**Issue by lug-gh** [nextcloud/nextcloud-snap#592]
Hi, I'm running nextcloud snap 13.0.2 stable snap, and saw that i cant have the favicon auto-generated, because imagemagick is not installed (or enabled?)
Is there a way to fix that in snap?

errorfrom the theming plugin: Install the Imagemagick PHP extension with support for SVG images to automatically generate favicons based on the uploaded logo and color.

**Comment by r4co0n** [comment]
Not having imagemagick can also result in image previews not being generated as discussed [here](https://github.com/nextcloud/server/issues/9794). I also think this should be included.

**Comment by PnjDbq** [comment]
Would also appreciate imagemagick to enable the Raw Preview app (.NEF, .CR2, .DNG, .TIFF).
https://github.com/cowai/CameraRawPreviews

**Comment by pachulo** [comment]
hey @lug-gh I'm testing this here: https://github.com/nextcloud/nextcloud-snap/pull/629 and I'm trying to change the theme, but nextcloud does not seems to generate the favicon; I'm not seeing any error either. If you want to try you can download a compiled version of that PR here: https://code.launchpad.net/~pachulo/+snap/nextcloud-imagemagick

@PnjDbq I also tried with that app, but it seems that it also needs to have perl installed: https://github.com/cowai/camerarawpreviews/issues/20#issuecomment-407160167 which i think that the snap has not.

**Comment by kyrofa** [comment]
After much discussion and considering, it has been decided that ImageMagick is just too risky to include for everyone at this time. If there comes a time where we can make it opt-in, we'll do that.

**Comment by PnjDbq** [comment]
Just to jump in, the theming app in NC14 allows you to upload your own header logo & favicon versus NC13 where ImageMagick had to generate the icon.

So in this use case, i'm now able to set the Favicon (and other items) without ImageMagick.

As a follow-up to Camera RAW Previews, the app is generating previews for .NEF files.  I guess the snap has access to the GD graphics library.  GD is slow, and ImageMagick is supposed to be faster.  But the app works (for me) without the risks of ImageMagick.

**Comment by pachulo** [comment]
Thanks for the info @PnjDbq !
By the way, should we close this @kyrofa ?

**Comment by kyrofa** [comment]
Yes, I think so.
