### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#6]
Upon visiting the admin page after initial install, it recommends the set-up of HTTPS.

**Comment by teslasmoustache** [comment]
I'm not sure if this is related, but I'm trying to use Let's Encrypt with the snap. Have you had any success with this? If so, how did you do it?

**Comment by kyrofa** [comment]
Indeed it is related. The snap needs a little more development before HTTPS is supported, but the plan is to build in Let's Encrypt.

**Comment by at-2500** [comment]
Have you thought about just using caddy? It will automatically do Lets encrypt for you, and with a caddyfile in /var/snap/nextcloud/current/, It will be trivial to switch from localhost:80 for people who like proxying to 0.0.0.0:443/80 for all other people...

**Comment by kyrofa** [comment]
> Have you thought about just using caddy?

I'm afraid I have no experience with Caddy, which means I have no confidence that I'll be able to configure it in a secure manner. I might be willing to experiment with such things for myself, but probably not for all the users of the snap.

**Comment by bonsje** [comment]
I think SSL is a must for using this snap for internet oriented purpose.
Lets Encrypt is also a good option, but i can image to integrate this the correct way takes some time. 

Looking forward to using this snap, when SSL is possible =).

**Comment by kyrofa** [comment]
@bonsje I just about have an initial version. Would you be willing to try a beta before it's actually released? I'll make a comment here once I have it, so anyone can try it and give me some feedback.

**Comment by kyrofa** [comment]
Alright, I've got a beta for HTTPS. I've only built it for amd64, so if you have that, install it with:

```bash
$ sudo snap install nextcloud --beta`
```

The first thing you'll notice is that it's HTTPS **only**. HTTP redirects to HTTPS. Upon first install, a self-signed certificate is generated, so you'll get a warning about that when you visit it. This may be enough for many users-- add an exception and away you go (I've actually been running this way for years).

But if you have a domain name pointing to the external address of the machine running the snap as well as ports 80 and 443 open on it (e.g. you may have to setup port forwarding if you're behind NAT), you can get a Let's Encrypt certificate by running the following command:

```bash
$ sudo /snap/bin/nextcloud.setup-https
```

This command is interactive; it'll ask you a few questions. Once you answer them, assuming you have the domain name and port forwarding setup correctly, Nextcloud should suddenly be running using the new certificates, and obtain an A rating on [SSLLabs](https://www.ssllabs.com/ssltest/).

I'm still working on things, but this should give you an idea of how the next version of the snap will work. Please let me know what you think!

**Comment by bonsje** [comment]
@kyrofa Sorry for my late response, 
I will test this snap on my amd64 test machine =). 

The let encrypt option seems a good SSL choice :) 
I will let you know if i bump in some issues. 

Thanks for developing the snap!

**Comment by kyrofa** [comment]
Thanks @bonsje! Please let me know either way-- if it seems to work well or not :smile: .

A 4096-bit cert and HSTS gets the snap an A+ on ssllabs; I'm uploading that rev to beta right now.

**Comment by kyrofa** [comment]
@jospoortvliet and @oparoz, would appreciate your input here when you're able.

**Comment by oparoz** [comment]
Will try to launch it on DigitalOcean

**Comment by oparoz** [comment]
OK, so HTTPS redirection seems to work. I can see the registration page and get warned about using the wrong cert.

When creating a cert, I get this:
>2016-08-17 14:49:46,148:WARNING:certbot.client:Non-standard path(s), might not work with crontab installed by your operating system package manager

Does that mean that auto-renewals won't work?
Also, how does the user set the maximum validity of the cert and when to renew? No questions were asked in that regard.

> Your account credentials have been saved in your Certbot configuration directory at  /var/snap/nextcloud/21/certs/certbot/config. You should make a
   secure backup of this folder now

I'm guessing we don't care because we can generate a new one if we lose the config?

Apart from that, it all worked. I was able to connect from the Internet using SSL. :+1:

**Comment by kyrofa** [comment]
> Does that mean that auto-renewals won't work?

No, it's a warning from certbot that I'm saving the configs in a location other than default, but there's a renew-certs service running that will take care of renewal for you that uses the same location. You can safely ignore that warning; unfortunately I can't stop it from being displayed.

> Also, how does the user set the maximum validity of the cert and when to renew? No questions were asked in that regard.

Let's Encrypt certs are always valid for 90 days, there is no way to change that.  The `renew-certs` service will renew it for you when it needs to be renewed, though, so it shouldn't be a concern.

> I'm guessing we don't care because we can generate a new one if we lose the config?

Indeed. Again, a message from certbot. You know what... I'll go ahead and mask out certbot's stdout and stderr and only display them if it exits non-zero so people aren't confused.

**Comment by oparoz** [comment]
>Let's Encrypt certs are always valid for 90 days, there is no way to change that. The renew-certs service will renew it for you when it needs to be renewed, though, so it shouldn't be a concern.

Yes, but the default should be to renew 60 days before the deadline.

From LE:
 "The Technical Advisory Board, chose a 90-day certificate lifetime to start with, with an expectation that people will want to auto-renew at the 60-day mark. “.

I guess we don't need to make it user-configurable, but let's just make sure we follow that recommendation?

> I'll go ahead and mask out certbot's stdout and stderr and only display them if it exits non-zero so people aren't confused.

Good idea. The script works. No need to confuse users about error messages.

There was one more when Apache was restarted though, but it's unrelated. Something about the Servername. Not sure if we can hide this as it may hide more serious issues reported that way.

**Comment by kyrofa** [comment]
> Yes, but the default should be to renew 60 days before the deadline.

The renewal is attempted once a day, and any certificate that has less than 30 days of validity remaining will be renewed, so that guideline is met.

> There was one more when Apache was restarted though, but it's unrelated. Something about the Servername. Not sure if we can hide this as it may hide more serious issues reported that way.

I suspect I can do the same thing there. Let me investigate.

**Comment by oparoz** [comment]
>The renewal is attempted once a day, and any certificate that has less than 30 days of validity remaining will be renewed, so that guideline is met.

Nice :)

**Comment by kyrofa** [comment]
Hmm. I didn't realize that Firefox won't let you add an exception for self-signed certificates if HSTS is enabled (like it is in the latest beta). That's really dumb.

I'm still waffling on the out-of-the-box experience. I can conditionally disable HSTS if it's self-signed, but the initial experience is still not a good one (e.g. an immediate "WARNING! THIS IS SELF SIGNED! RUN FOR YOUR LIFE!"). Perhaps the initial experience should be HTTP, with the `setup-https` script enabling HTTPS, with the option to utilize self-signed certs or Let's Encrypt. But then I'm worried that a great many users would be perfectly happy with the initial experience, and never setup HTTPS because they don't know any better.

Thoughts?

**Comment by jospoortvliet** [comment]
so Nextcloud gives you a warning on the admin page about SSL not being enabled. I think the key here is to make it as easy as possible to actually enable a proper SSL... I can at least create a nice how-to on nextcloud.com ... but easier than that is better.

**Comment by LukasReschke** [comment]
> Hmm. I didn't realize that Firefox won't let you add an exception for self-signed certificates if HSTS is enabled (like it is in the latest beta). That's really dumb.

That's actually the expected behaviour of user agents and as specified in the HSTS specs :-)

**Comment by oparoz** [comment]
Currently, a user who doesn't know how to connect to his PiCloud using FTP or SSH will probably not know how to connect it to the Internet, so I don't think it would be too much of an issue to offer both HTTP and HTTPS on the device while beginners wait for a solution which make it a no-brainer for anybody to connect to the Internet.

**Comment by kyrofa** [comment]
>> Hmm. I didn't realize that Firefox won't let you add an exception for self-signed certificates if HSTS is enabled (like it is in the latest beta). That's really dumb.

> That's actually the expected behaviour of user agents and as specified in the HSTS specs :-)

Doesn't make it less dumb ;) . Anyway, I disabled HSTS for the self-signed certs.

**Comment by kyrofa** [comment]
I also proposed #23 if we want to move our conversation there and see changes.

**Comment by kyrofa** [comment]
> Indeed. Again, a message from certbot. You know what... I'll go ahead and mask out certbot's stdout and stderr and only display them if it exits non-zero so people aren't confused.

@oparoz I've done this in the latest beta. For apache as well.
