### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by unik-web** [nextcloud/nextcloud-snap#602]
Hello,

I get this error on chrome NET::ERR_CERT_COMMON_NAME_INVALID and when i **disable SSL** then it works fine.  Can somebody tell me why my ssl no working and how to fix my issue.

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

Nextcloud version 13.0.2

**Comment by unik-web** [comment]
Hello,
I found the issue on my firewall. I forgot to open port https, so now it works fine. Thanks for your help.

**Comment by r4co0n** [comment]
Then probably another webserver answered the HTTPS request, leading to the scenario I described. Glad you got it working, I'm closing this now.
