### ISSUE TITLE
 sudo nextcloud.enable-https lets-encrypt fails

### ISSUE THREAD

**Issue by andreaswarnaar** [nextcloud/nextcloud-snap#605]
Hi,

Im setting up a nexcloud snap but i cannot generate a letsencrypt certificate. 
Attempting to obtain certificates... error running certbot:

An unexpected error occurred:
IOError: [Errno 13] Permission denied: '/etc/letsencrypt/cli.ini'
Please see the logfile '/tmp/tmpkjdNfx' for more details.

Any advice how to fix this?

Andreas

**Comment by kyrofa** [comment]
Yeah, dupe of #569, workaround over there. You can refresh to beta if you want the pre-release fix.

**Comment by andreaswarnaar** [comment]
Thx!
