### ISSUE TITLE
LetsEncrypt not renewing

### ISSUE THREAD

**Issue by stmaro** [nextcloud/nextcloud-snap#609]
Im currently running the latest snap (Nextcloud 13.02) on Ubuntu 16.0.4.

I received an email today saying my LetsEncrypt certificate will expire in 2 weeks. However when I run `sudo journalctl -u snap.nextcloud.renew-certs.service` the output says cert not due for renewal. I also ran `systemctl status snap.nextcloud.renew-certs.service` and the service is "active (running)".

How can I read the certificate and see the details of expiry? I tried `certbot certificates` but it said Certbot command is not found.

NOTE... I checked other threads regarding similar issue but they do not appear to be the same. My issue is NOT due to a change in domain (not that I recall), and "/etc/letsencrypt/cli.ini" does NOT exist.

**Comment by kyrofa** [comment]
Go straight to the source: visit Nextcloud in your browser and look at the cert. When does it say it'll expire?

**Comment by stmaro** [comment]
oh duh.... ok it says it expires September 5th. So I assume the email from LetsEncrypt is an error or an old certificate. thanks for the help!

**Comment by r4co0n** [comment]
This seems to be resolved, I'm closing it.
