### ISSUE TITLE
Nextcloud-snap v13.0.2.1 which folders and files do I need to backup for full recovery?

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#615]
After rebooting my snap installed nextcloud, the application is now refusing to connect. Checking my Nextcloud notes I found that instead of 1 four-digit named folder containing the config.php file, there were now three 4-digit folders each containing various updated config.php files in them.

/var/snap/nextcloud/ there now are folders 5627, 6708, 6916. Previously of these only 5627 existed of the 4-digit foldernames each containing all of the subfolders found in the original 5627 folder.

The highest 4-digit folder 6916 config.php contains the most recent version release update and data path. Copying this newest config.php file over to the other two config.php folders (5627, 6708) however did not restore my connectivity. The application is up and running, I cannot connect to it locally nor remotely. The browser is stating 'refusing to connect'. 

With the new Ubuntu/Mint LTS coming later this month and early next month, I'll need to learn and apply a backup of my pre-existing snap installed nextcloud and fully restore it after formating my server's SSD housing the older Linux LTS software. This is however slightly earlier than I had anticipated but worthwhile learning and applying now.

What snap installed nextcloud folders and files do I need to backup to reinstall this snap nextcloud application and fully restore it?

**Comment by pachulo** [comment]
The folders with digits contain the different installed revisions of the snap.

Anyway, this is a recurring question, please see the discussion of relevant issues in issue #489.
It can be done, but the current approach requires some manual work.

**Comment by stone212** [comment]
@pachulo Issue #489 does not answer Asmith's question.  Why is it so difficult to provide a single list?  I am not trying to sound petulant.  I really want to know why answering this question is so challenging.

**Comment by kyrofa** [comment]
Please see #688 for an automated way to do this. It also hopefully answers the question of what needs to be backed up.
