### ISSUE TITLE
SSL Encryption Settings

### ISSUE THREAD

**Issue by ilfrigorifero** [nextcloud/nextcloud-snap#616]
Hi there,

I've like to disable TLS 1.0 and only use TLS 1.1 and TLS 1.2.
All i could find was a Wiki entry from 2017 saying I should edit /var/snap/nextcloud/current/apache/config/ but that folder and its content seem to have vanished since the Wiki entry was last edited.

What can I do to edit these settings?

**Comment by r4co0n** [comment]
Unfortunately, it's not as easy as that, as the content of the snap itself is immutable.

I think this issue is a feature request, and an easy one at that, and will tag it accordingly. If you disagree, just let us know.

**Comment by ilfrigorifero** [comment]
Sounds good, thank you!
I'm new to snaps, so you know best anyways!

Simon Hollenbach <notifications@github.com> schrieb am Mo., 18. Juni 2018,
18:21:

**Comment by pachulo** [comment]
This is becoming a trend: https://blog.sucuri.net/2018/06/sucuri-enhances-security-by-disabling-tls-version-1-0-and-1-1.html

**Comment by kyrofa** [comment]
Indeed, I want to try just disabling these and seeing what ssllabs says about it.

**Comment by ASmith-** [comment]
Many folks are using only the PFS cipher suites exclusively on their web server settings. Those contain the strongest ciphers and form TLS v1.2 and soon TLS v1.3. Nearly all web browsers now can work just fine with TLS v1.2 PFS cipher suites and you are using the strongest connective end to end encryption possible using openssl libraries. My suggestion to kick upstream is gut everything but PFS (Perfect Forward Secrecy) ciphers as those are the strongest available and publicly supported.

Perfect Forward Secrecy is obtained by using Ephemeral Diffie-Helman keys (DHE or EDH). So to get the cipher suits in that list that support PFS you could do:

$ openssl ciphers -v aECDSA:aECDH:kEDH:kRSA | grep DHE

This will include ciphers based on ECDHE (Elliptic Curve) as well as DHE (RSA). An advantage of ECDHE is that it is a lot faster than DHE. However in the list generated by that command there are still quite a few weak ciphers that use weak or no crypto: DES, RC4, SSLv3, NULL.

All of those happened to have SSLv3 in common, so by excluding SSLv3 you get a list of 12 solid ciphers:

$ openssl ciphers -v aECDSA:aECDH:kEDH:kRSA | grep DHE | grep -v SSLv3

ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH Au=ECDSA Enc=AESGCM(256) Mac=AEAD
ECDHE-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH Au=ECDSA Enc=AES(256) Mac=SHA384
ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH Au=ECDSA Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES128-SHA256 TLSv1.2 Kx=ECDH Au=ECDSA Enc=AES(128) Mac=SHA256
DHE-DSS-AES256-GCM-SHA384 TLSv1.2 Kx=DH Au=DSS Enc=AESGCM(256) Mac=AEAD
DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH Au=RSA Enc=AESGCM(256) Mac=AEAD
DHE-RSA-AES256-SHA256 TLSv1.2 Kx=DH Au=RSA Enc=AES(256) Mac=SHA256
DHE-DSS-AES256-SHA256 TLSv1.2 Kx=DH Au=DSS Enc=AES(256) Mac=SHA256
DHE-DSS-AES128-GCM-SHA256 TLSv1.2 Kx=DH Au=DSS Enc=AESGCM(128) Mac=AEAD
DHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH Au=RSA Enc=AESGCM(128) Mac=AEAD
DHE-RSA-AES128-SHA256 TLSv1.2 Kx=DH Au=RSA Enc=AES(128) Mac=SHA256
DHE-DSS-AES128-SHA256 TLSv1.2 Kx=DH Au=DSS Enc=AES(128) Mac=SHA256

**Comment by Airtdschahn** [comment]
Hallo everyone,

could we disable TLSv1.1 and v1.0 and all CBC-ciphers in the next stable release (it‘s a great image, but this is for me the most annoying point, that I have to break the update mechanism of snap and edit the ssl.conf for every stable release manuelly).

**Comment by kyrofa** [comment]
Please take a look at #941.

**Comment by Airtdschahn** [comment]
Hello everyone,

I refreshed my snap install on my test installation with pr-941 (--channel=beta/pr-941)
![SSL Labs](https://user-images.githubusercontent.com/48522025/54870891-cb2dc980-4dac-11e9-853a-2c9df69b2042.png)
and tested it with win7 (Build 7601 with SP1)
![Windows 7](https://user-images.githubusercontent.com/48522025/54870900-e6003e00-4dac-11e9-9266-7f77e2b4f6e3.png)
and ie11 (11.0.9600), 
![Internet Explorer 11](https://user-images.githubusercontent.com/48522025/54870905-f1ec0000-4dac-11e9-8093-df853f82ddf0.png)
and everything works great (Connection: TLS 1.2, AES with 256 bit encryption (High); DH with 4096 bit exchange),
![Nextcloud 15](https://user-images.githubusercontent.com/48522025/54870917-05976680-4dad-11e9-9e97-27eb1dabce79.png)
I am repeating myself again and again, but you all (especially kyrofa) do great work with this snap!

**Comment by kyrofa** [comment]
Thank you for taking that for a spin, @Airtdschahn! I was relying completely on simulators, very happy to see it working on the real deal.
