### ISSUE TITLE
Wiki add for enabling ssh/https and getting cert 

### ISSUE THREAD

**Issue by joltdude** [nextcloud/nextcloud-snap#62]
Addition to wiki.. Might want to suggest folks change the shell password from the default of ubuntu in the process of enabling https in the steps for enabling https and letsencrypt if they haven't already.. Its obvious for some folks but remember this is a setup process.

**Comment by oparoz** [comment]
Agreed.

https://github.com/nextcloud/nextcloud-snap/wiki/Connecting-the-Nextcloud-Box-to-the-Internet
