### ISSUE TITLE
No simple install example for: nc-snap + nginx with ssl managed by certbot + mydomain.com/nextcloud/

### ISSUE THREAD

**Issue by oz10h** [nextcloud/nextcloud-snap#622]
Here is the fix for a suffix or path based url for reverse proxy of nextcloud.
The nginx portion is at the bottom.
(I assume you are already using certbot AKA letsencrypt to secure your connections)
Replace --channel=13/stable with the channel of your choice.
Replace mypassword  with your password of choice.
Replace mydomain.com with your domain.

````bash
#!/bin/bash
snap remove nextcloud
snap install nextcloud --channel=13/stable
snap set nextcloud ports.http=81 ports.https=444
nextcloud.manual-install admin "mypassword"
nextcloud.occ config:system:set overwritehost --value="mydomain.com"
nextcloud.occ config:system:set overwriteprotocol --value="https"
nextcloud.occ config:system:set overwritewebroot --value="/nextcloud"
nextcloud.occ config:system:set overwrite.cli.url --value="https://mydomain.com/nextcloud"
nextcloud.occ config:system:set htaccess.RewriteBase --value="/nextcloud"
nextcloud.occ config:system:set trusted_domains 2 --value="mydomain.com"
 


      location /nextcloud/ {
            proxy_pass http://localhost:81/;
        }

**Comment by unicorn667** [comment]
Have somebody tried?

**Comment by oz10h** [comment]
Yes I tried many times trying to customize my installation. This method worked.

**Comment by joelpurra** [comment]
Works for me! Thanks @oz10h =)

**Comment by kyrofa** [comment]
Thanks @oz10h, I'll go ahead and close this since it's not actually an issue, but the wiki is open for editing if you'd like to add it!

**Comment by oz10h** [comment]
I know this is a dead thread but I wanted to make sure everyone gets the changes I have made to my setup. Having a similar problem [here](https://github.com/owncloud/core/issues/21760#issuecomment-363494988) 
I realize that it's a quicker fix if it's done this way.

**Comment by DAMONSTA360** [comment]
Dead thread I see. Just hoping to clarify regarding ncsnap+nginx.

I'd like to run ncsnap with nginx vs apache.
As I am not familiar with reverse proxy-ing, my question is can I use Nginx with NC Snap without using a reverse proxy?

Or is that not a thing?

**Comment by oz10h** [comment]
That's a thing I believe but it would all be dependent on how you assign your ports. You would have port issues if you tried to run nginx on standard ports... that's all

**Comment by oz10h** [comment]
I guess it depends upon how you plan on using Nginx and NC. From what I read it's recommended to use some kind of reverse proxy for internet facing anyways for scalability, security, customization, downtime and more. You could use Apache too if you're more comfortable.

If you're not comfortable with reverse proxies I can walk you through the process. Just let me know where you're having trouble. I have been up and down this road before.
I like reverse proxies, they get the job done.

**Comment by virgilchiou** [comment]
Thank you for your contribution!
According to your solution, mydomain.com/nextcloud **(no "/" in the end)** cannot visit nextcloud.
Is there possible to use mydomain.com/nextcloud instead of mydomain.com/nextcloud/ to visit nextcloud, namely, without the last "/"?
