### ISSUE TITLE
Previewgenerator on specific directories? 

### ISSUE THREAD

**Issue by fredrikburmester** [nextcloud/nextcloud-snap#624]
Hi, I'm trying to run previewgenerator [https://apps.nextcloud.com/apps/previewgenerator] on a single directory. Does anyone know how I can do this? 

Currently, previewgenerator is scanning all libraries, and I assume, creates previews for all images. 
Also, what size previews are being created and what format?

Thanks!

**Comment by PnjDbq** [comment]
It does not appear to be an option.  However, there's an open PR, so perhaps soon?

See https://github.com/rullzer/previewgenerator/pull/119

**Comment by pachulo** [comment]
I would say that this is not an issue specific to the nextcloud-snap, but from the application previewgenerator. May I close this?

**Comment by kyrofa** [comment]
Agreed.
