### ISSUE TITLE
Reduce apparmor-spam?

### ISSUE THREAD

**Issue by WereCatf** [nextcloud/nextcloud-snap#630]
My log-files are getting spammed with `audit: type=1400 audit(1531032491.884:163): apparmor="DENIED" operation="file_mmap" profile="snap.nextcloud.nextcloud-cron" name="/" pid=5227 comm="php" requested_mask="w" denied_mask="w" fsuid=0 ouid=0`

Is there anything that could be done to reduce this?

**Comment by WereCatf** [comment]
Adding "deny / w," (without the quotes) into /var/lib/snapd/apparmor/profiles/snap.nextcloud.nextcloud-cron seems to have fixed the spam. I'm just mentioning this here in any case anyone else is bothered by the same issue.

**Comment by hwiorn** [comment]
I have same problem.

```
... 
[1830913.447425] audit: type=1400 audit(1557855298.996:6237): apparmor="DENIED" operation="file_mmap" profile="snap.nextcloud.nextcloud-cron" name="/" pid=18465 comm="php" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
[1831516.354614] audit: type=1400 audit(1557855901.878:6238): apparmor="DENIED" operation="file_mmap" profile="snap.nextcloud.occ" name="/" pid=20800 comm="php" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
...
```
Add `deny / w,` to
 -  /var/lib/snapd/apparmor/profiles/snap.nextcloud.nextcloud-cron 
 - /var/lib/snapd/apparmor/profiles/snap.nextcloud.occ

Then, Execute below command to apply the apparmor.
```
sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.nextcloud.{nextcloud-cron,occ}
```

**Comment by kaangoksal** [comment]
Why does this happen?

**Comment by arnonuem** [comment]
> I have same problem.
> 
> ```
> ... 
> [1830913.447425] audit: type=1400 audit(1557855298.996:6237): apparmor="DENIED" operation="file_mmap" profile="snap.nextcloud.nextcloud-cron" name="/" pid=18465 comm="php" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
> [1831516.354614] audit: type=1400 audit(1557855901.878:6238): apparmor="DENIED" operation="file_mmap" profile="snap.nextcloud.occ" name="/" pid=20800 comm="php" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
> ...
> ```
> 
> Add `deny / w,` to
> 
> * /var/lib/snapd/apparmor/profiles/snap.nextcloud.nextcloud-cron
> * /var/lib/snapd/apparmor/profiles/snap.nextcloud.occ
> 
> Then, Execute below command to apply the apparmor.
> 
> ```
> sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.nextcloud.{nextcloud-cron,occ}
> ```

i added this command somewhere in the middle of the files so i had to append a `,` at the end.
