### ISSUE TITLE
nextcloud-snap offers the AV-Scan addon to its users but needs clamscan added to the snap sandbox

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#637]
The AV-Scan addon searches outside of its snap sandbox to /usr/bin/clamscan for the needed antivirus executable. On my Linux Bionic amd64 system, its located there and functions alone fine. It does not however even appear as found by the nextcloud-snap AV-Scan addon resulting in this logged error
RuntimeException: The antivirus executable could not be found at /usr/bin/clamscan

I've reported this in the NC-antivirus issues https://github.com/nextcloud/files_antivirus/issues/85
They rightly sent me back to nextcloud-snap as the snap enclosure is the issue causing this.

Solutions?
Suggestions?

**Comment by r4co0n** [comment]
Please see my comments on your previous issue about this in #583. I'm closing this as well as it is out of scope.
