### ISSUE TITLE
Snap Inside LXD - database restore backup permission denied

### ISSUE THREAD

**Issue by rudiservo** [nextcloud/nextcloud-snap#641]
Snap is install inside a LXD container, it works on the host server or stand alone machine but not inside LXD for some reason.

> snap run nextcloud.mysql-client nextcloud < backup_nextcloud.sql 
> mysql: Error reading file 'UNOPENED' (Errcode: 13 - Permission denied)

**Comment by rudiservo** [comment]
I found out that it's a problem with lxc itself with some kind of permission issue with using '<'.
Altough it works fine with pipe '|' it might not be a solution for a huge database.

**Comment by kyrofa** [comment]
Sounds like this doesn't involve the snap, so I'm going to go ahead and close it. Feel free to continue discussion here.
