### ISSUE TITLE
Your storage is full cannot upload nor synch any more files Warning

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#648]
**Your storage is full cannot upload nor synch any more files Warning**

Both external HD's being used for snap-nextcloud data and external files indicate 2+ TB of free space available. My Administrative account is set for 'Unlimited'. I reset 'Unlimited to 5 TB' which turned the rather ominous looking red stripe under my quota use to a blue line however the warning still pops up when uploading files, 'Your storage is full, cannot upload nor synch any more files'.

The files are uploading just fine and the hard drives have Terabytes of free space. Unlimited should be unlimited within the ability to store the files on the free space available. This is a bug, looks and acts like a bug. The temporary work around thus far has been to forget 'Unlimited' and use other... 5 TB but this bug should be patched.

Linux Ubuntu 18.04 / Mint 19 Tara LTS amd64 Nextcloud newest stable snap release v13.x

**Comment by kyrofa** [comment]
> I reset 'Unlimited to 5 TB' which turned the rather ominous looking red stripe under my quota use to a blue line however the warning still pops up when uploading files, 'Your storage is full, cannot upload nor synch any more files'.

This makes it sound like switching Unlimited to 5TB didn't change anything, it still says the storage is full, but then you say:

> The temporary work around thus far has been to forget 'Unlimited' and use other... 5 TB but this bug should be patched.

Which makes it sound like it DOES change something. Which is it?

**Comment by ASmith-** [comment]
Hi Kyrofa, sorry I must have been sleep typing, the corrected entry would be "My Administrative account had been set for 'Unlimited'. I began receiving the warning, 'Your storage is full, cannot upload nor synch any more files'. 

I reset 'Unlimited to 5 TB' which turned the rather ominous looking red stripe under my quota use to a blue line and the warning no longer pops up when uploading files.

The files are uploading just fine and the hard drives have several Terabytes of free space. Unlimited should be unlimited within the ability to store the files with the free space available. This is a bug, looks and acts like a bug. The temporary work around thus far has been to forget 'Unlimited' and use other... 5 TB but this bug should be patched."
