### ISSUE TITLE
Gracefully restart Apache server daily

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#65]
We need to gracefully restart Apache daily if we want to deliver Perfect Forward Secrecy without any performance impact.

This may require making modifications to the Apache daemon app to support a graceful restart.

Background information:
- https://media.blackhat.com/us-13/US-13-Daigniere-TLS-Secrets-Slides.pdf
- https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/

**Comment by kyrofa** [comment]
This is news to me. What's the reasoning behind this?

**Comment by oparoz** [comment]
I don't have the link to the study handy, but it was discovered that without a restart or turning the feature off, forward secrecy was compromised and it has since been a recommendation in the Apache docs.
https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslsessiontickets

**Comment by oparoz** [comment]
Also, my current recommendation to users is to disable SSLSessionTickets, but it has a performance impact, so I think it wold be great if we could restart the server instead.

**Comment by oparoz** [comment]
https://media.blackhat.com/us-13/US-13-Daigniere-TLS-Secrets-Slides.pdf

Hmmm... According to Mozilla, restarting a recent Apache doesn't work :cry: 

https://wiki.mozilla.org/Security/Server_Side_TLS#TLS_tickets_.28RFC_5077.29

**Comment by kyrofa** [comment]
I'm going to close this since there seems to be little proof that this actually is a thing. If more data comes to light, please re-open.
