### ISSUE TITLE
Add access to /media

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#66]
`/media` is a zone which is accessible by all snaps supporting the `removable-media` interface. We should add it to this Snap.
## Benefits
- Creates a permanent storage location. Currently, when adding other Nextcloud snaps, they're all empty
- Provides an area which will survive a snap removal, whether by accident or because it has become unrecoverable
- Allows Nextcloud to have access to data of other snaps
- Gives access to mounted storage
- Makes it possible to create backups
- Gives access to USB sticks?

**Comment by kyrofa** [comment]
You state benefits, but you don't state why these benefits are actually benefits :stuck_out_tongue: .

> Creates a permanent storage location. Currently, when adding other Nextcloud snaps, they're all empty

Why is that a bad thing?

> Provides an area which will survive a snap removal, whether by accident or because it has become unrecoverable

I kind of like that the data is owned by the snap-- remove it and you're done. Purposefully leaving things lying around is not quite as slick.

> Allows Nextcloud to have access to data of other snaps

Why do we want this?

**Comment by oparoz** [comment]
>> Creates a permanent storage location. Currently, when adding other Nextcloud snaps, they're all empty

> Why is that a bad thing?

It's not necessarily a bad thing, but when testing various snaps with different features, developers have to recreate the content in every snap they load. When this is enabled, developers will be able to add various folders to their Snaps for quick testing.

>> Provides an area which will survive a snap removal, whether by accident or because it has become unrecoverable

> I kind of like that the data is owned by the snap-- remove it and you're done. Purposefully leaving things lying around is not quite as slick.

I find it scary :). Anything happens to the Snap and the data is gone. If you type the wrong command like `snap remove` it's gone if I'm not mistaken.
In the end it's just another option for those who want a safe location for some of their data per example.

>> Allows Nextcloud to have access to data of other snaps

> Why do we want this?

Because other snaps can provide access to more files which would not otherwise be directly accessible from Nextcloud.

I've also just added these 3 reasons:
* Gives access to mounted network storage
* Makes it possible to create backups
* Gives access to USB sticks?

**Comment by kyrofa** [comment]
>>> Provides an area which will survive a snap removal, whether by accident or because it has become unrecoverable

>> I kind of like that the data is owned by the snap-- remove it and you're done. Purposefully leaving things lying around is not quite as slick.

> I find it scary :). Anything happens to the Snap and the data is gone. If you type the wrong command like snap remove it's gone if I'm not mistaken.

What about a wrong command like `rm -rf` :wink: ? But fair enough.

> I've also just added these 3 reasons:
> 
> - Gives access to mounted network storage
> - Makes it possible to create backups
> - Gives access to USB sticks?

Okay, those reasons make more sense to me.

**Comment by oparoz** [comment]
> What about a wrong command like rm -rf :wink: ? But fair enough.

True, the data on `/media` wouldn't be protected as well as when it's stored inside the Snap, but I think that offering that option wouldn't hurt :)
