### ISSUE TITLE
Error Updating to NC 13.05 from 13.04 via Browser

### ISSUE THREAD

**Issue by edrohler** [nextcloud/nextcloud-snap#660]
I tried to log in to my nextcloud install via the web browser and received the update notification, backed up my config and clicked the update button and received the below error. 

Checking for update of app "workflowengine" in appstore
Checked for update of app "workflowengine" in appstore
Starting code integrity check
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_appconfig` SET `configvalue` = ? WHERE (`appid` = ?) AND (`configkey` = ?) AND (`configvalue` <> ?)' with params ["[]", "core", "oc.integritycheck.checker", "[]"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Honestly, I have been getting similar errors in my logs and have been receiving numerous errors in my DavDroid app on Android. 

I am running the snap in a nextcloud box, with Raspberry Pi 3 and am running off of a SD Card with the 1TB drive as the data drive.

**Comment by edrohler** [comment]
Well, I reverted the snap back using `snap revert nextcloud` which at least gives me access to my files using Nautilus and the Android app but the web front-end renders poorly because I receive 500 errors all over the place. I guess I am going to have to reinstall it another day.

**Comment by kyrofa** [comment]
Dang, it sounds like you're running out of RAM when running database updates :( .

**Comment by edrohler** [comment]
I definitely will give that a shot.

**Comment by edrohler** [comment]
Hey @kyrofa thank you for the help. I did add the swap file and I think I will keep it since I only have a gig of ram. After I did the revert all I needed to do was execute ```nextcloud.occ maintenance:repair``` and this refreshed the web cache. Although, now when I run ```nextcloud.occ upgrade``` it doesn't recognize the release. Anyway, thanks again and I think this issue can be resolved.

**Comment by kyrofa** [comment]
@edrohler of course, I've had to do the same when I was using an rpi. Let's try to make sure you're as up-to-date as can be, though, before considering this resolved. Can I see the output of `snap info nextcloud`, please?

**Comment by edrohler** [comment]
Absolutely and thank you.

```
name:      nextcloud
summary:   Nextcloud Server - A safe home for all your data
publisher: nextcloud
contact:   https://github.com/nextcloud/nextcloud-snap
license:   unknown
description: |
  Access, share and protect your files, calendars, contacts, communication
  and more at home and in your enterprise.
commands:
  - nextcloud.disable-https
  - nextcloud.enable-https
  - nextcloud.manual-install
  - nextcloud.mysql-client
  - nextcloud.mysqldump
  - nextcloud.occ
services:
  nextcloud.apache:         simple, enabled, active
  nextcloud.mdns-publisher: simple, enabled, active
  nextcloud.mysql:          simple, enabled, active
  nextcloud.nextcloud-cron: simple, enabled, active
  nextcloud.php-fpm:        simple, enabled, active
  nextcloud.redis-server:   simple, enabled, active
  nextcloud.renew-certs:    simple, enabled, active
snap-id:      njObIbGQEaVx1H4nyWxchk1i8opy4h54
tracking:     stable
refresh-date: 2 days ago, at 02:14 UTC
channels:                                      
  stable:       13.0.5snap1       (8269) 197MB -
  candidate:    ↑                              
  beta:         ↑                              
  edge:         master-2018-08-03 (8334) 202MB -
  11/stable:    11.0.8snap1       (6962) 193MB -
  11/candidate: ↑                              
  11/beta:      ↑                              
  11/edge:      ↑                              
  12/stable:    12.0.10snap1      (8248) 196MB -
  12/candidate: ↑                              
  12/beta:      ↑                              
  12/edge:      12-2018-08-03     (8332) 197MB -
  13/stable:    13.0.5snap1       (8269) 197MB -
  13/candidate: ↑                              
  13/beta:      ↑                              
  13/edge:      13-2018-08-03     (8333) 197MB -
  14/stable:    –                              
  14/candidate: –                              
  14/beta:      14.0.0beta2snap1  (8329) 202MB -
  14/edge:      ↑                              
installed:      13.0.4snap1       (7659) 197MB -
```

**Comment by edrohler** [comment]
@kyrofa any word on upgrading?

**Comment by kyrofa** [comment]
Sorry for the delay @edrohler. Can I also see the output of `snap list nextcloud --all` as well as the output of `ls /snap/nextcloud`, please?

**Comment by edrohler** [comment]
No problem. Here you go:

```
~$ snap list nextcloud
Name       Version      Rev   Tracking  Publisher  Notes
nextcloud  13.0.4snap1  7659  stable    nextcloud  -
```

```
~$ ls /snap/nextcloud/
7659  8269  current
```

**Comment by kyrofa** [comment]
Ah, very good. Try this, then. First, remove the new version, since the data might be garbled. **Take careful note of the `--revision` parameter**: `sudo snap remove nextcloud --revision=8269`. Then simply try the upgrade again: `sudo snap refresh nextcloud`.

**Comment by edrohler** [comment]
Awesome, @kyrofa! Thank you for your help. I really appreciate it.

**Comment by kyrofa** [comment]
@edrohler did that end up working, then?

**Comment by edrohler** [comment]
@kyrofa apologies for the delay. It sure did work. Thank you for your help. I really appreciate it. Pretty new to Ubuntu Core and was unsure how to manage snaps. Thanks again!

**Comment by kyrofa** [comment]
Very good! My pleasure. I'll go ahead and close this out, then.
