### ISSUE TITLE
non-default apps marked "to be updated" after restoration

### ISSUE THREAD

**Issue by Refhi** [nextcloud/nextcloud-snap#661]
After a restoration [following this](https://docs.nextcloud.com/server/13/admin_manual/maintenance/restore.html)
Apps that I installed on the previous install where marked "This app has an update available." + didn't work.

They mostly worked fine after finding and clicking _all_ the "Update to x.x.x" button (exept TOTP and mail which needed more work) 

I hoped to use nextcloud.occ app:xxxx to ease the process, but couldn't find a way to activate everything at once. Worked around with :
`sudo nextcloud.occ app:install appname && sudo nextcloud.occ app:enable appname`

**Comment by kyrofa** [comment]
@Refhi what version were you restoring?

**Comment by Refhi** [comment]
Deepest apologies, I forgot the basics : 
- Nextcloud 13.0.5
- nextcloud 13.0.5snap1


>  sudo snap version
> - snap 2.34.2+18.04
> - snapd   2.34.2+18.04
> - series  16
> - ubuntu  18.04 kernel  4.15.0-29-generic

**Comment by Refhi** [comment]
forgot to restore the config directory...
