### ISSUE TITLE
Cannot change data directory

### ISSUE THREAD

**Issue by fpernice518** [nextcloud/nextcloud-snap#664]
I followed [this guide to the T](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition), in order to change my data drive from my small SSD to my 4TB NAS drive. But when visiting the login page (after changing the settings), I'm instead greeted by the following.

![image](https://user-images.githubusercontent.com/30581999/43625926-8ec221b8-96bd-11e8-90b3-24def55cadf2.png)

**Comment by kyrofa** [comment]
@fpernice518 the snap is confined to only be able to write in specific areas. `/data` is not one of those areas. Take a careful look at the first sentence of that guide:

> The partition you want to use must be mounted somewhere in `/media/`. This is the only location the snap can access under confinement with the `removable-media` plug.

**Comment by fpernice518** [comment]
Update. I got it I believe, but I needed to do a few extra steps.

`cd /media/data`
`sudo touch .ocdata`
`sudo chmod 0770 .ocdata`
sudo chmod 0770 /media/data`

**Comment by 447937** [comment]
Same issue here. Steps taken: 
1. sudo snap install nextcloud
2. sudo snap connect nextcloud:removable-media
3. modified *'directory' => '/media/storage/data'* in /var/snap/nextcloud/current/nextcloud/config/autoconfig.php
4. Attempt to create admin account -> failed

**Installed version of snap:** 13.0.5snap1  (Rev: 8267, Tracking: stable)
OS: Ubuntu 18.04 (minimal installation)

I've also tried to take steps listed in previous post, but without success.

**Comment by kyrofa** [comment]
> Attempt to create admin account -> failed

Can you define "failed" ?

**Comment by 447937** [comment]
Same result as @fpernice518 shown in first post. Would be nice if this got fixed or guidelines updated. For now I have workaround - I've installed nextcloud in --devmode and connected to removable-media. Now it works, but this (--devmode) means that I won't get automatic snap updates (if I understand it correctly).

**Comment by kyrofa** [comment]
@447937 which one, the "failed to create" error or the ".ocdata" error?

**Comment by 447937** [comment]
Failed to create.

**Comment by 447937** [comment]
Yes, I'm absolutely sure about directory in `/media/`.

This is relevant line from my `/etc/fstab`:
`UUID=769b7fe2-2159-4777-543d-5b976843e61f        /media/storage ext4    errors=remount-ro 0     1`

Well, I have no idea either, thats why I'm asking. :)
