### ISSUE TITLE
Unclear description from the Ubuntu Software Center

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/nextcloud-snap#67]
Hi,
I found the snap in the Ubuntu Software application, however it doesn't make it clear what exactly is installed; a server? a client? It only has a very generic description.

My initial thought was that it would be the nextcloud client, which is also most logical from a desktop user perspective, until I glanced over the size of the package.

![screenshot from 2016-09-30 21-03-25](https://cloud.githubusercontent.com/assets/9272078/19003640/131490a4-8752-11e6-80f0-2d811abcf244.png)

**Comment by kyrofa** [comment]
@armaccloud thanks for the bug report! Looks like the software center is missing the summary, so I'm passing the buck to the software center, with LP: [#1629456](https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1629456).
