### ISSUE TITLE
Tomboy server app not working due to missing oauth package in PHP

### ISSUE THREAD

**Issue by ruedigerkupper** [nextcloud/nextcloud-snap#670]
I'm trying to activate this app: https://apps.nextcloud.com/apps/grauphel.
It fails due to missing oauth support in PHP (http://pecl.php.net/package/oauth).
How can I add php-oauth to my nextcloud snap?

**Comment by pachulo** [comment]
You would need to modify the snapcraft to include the module and then compile the snap. More info here: https://github.com/nextcloud/nextcloud-snap/wiki/Building-your-first-Nextcloud-snap

**Comment by kyrofa** [comment]
We tend to only add libraries necessary to enable core apps. Enabling every app in the world simply doesn't scale, I'm sorry. If you need this library you can either build your own snap that includes it, or install Nextcloud in another way.
