### ISSUE TITLE
Using Nextcloud from a sub-directory...

### ISSUE THREAD

**Issue by dorearendil** [nextcloud/nextcloud-snap#671]
Hi everyone,
Sorry but I can't find much documentation on this issue... And I'm new to snaps!

I installed Nextcloud on my Ubuntu 16.04/Apache server through snap, using this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-16-04
To my surprise, the install process didn't ask into what directory I would like to install NC. But I thought maybe I could specify that later.

Anyway - as a result, NC now launches immediately when I open my website's homepage.
I would like it to only function from a specific sub-directory of my root folder.
Is there an easy & painless way to make this happen?

I tried modifying (perhaps I created? can't remember) a NC config file /etc/apache2/sites-available/nextcloud.conf, as explained here:
https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#apache-configuration-label
- replacing the directory variables with my own filepath. But to no avail.

So what should I do? Is it better for me to uninstall NC, then reinstall it? If so, is there a way to specify during snap install what directory I want to run NC from?

Thanks in advance.

**Comment by kyrofa** [comment]
I'm afraid this isn't really supported unless you want to setup a proxy.

**Comment by dorearendil** [comment]
I see. Thanks for your reply.
Could you please advise on the best way to uninstall NC from my server, then?
I found uninstall instructions elsewhere, but I suppose the procedure must be slightly different when the install happened through snap?

**Comment by kyrofa** [comment]
Indeed, super simple: `sudo snap remove nextcloud`.
