### ISSUE TITLE
Nextcloud 13.05 on Ubuntu 18?

### ISSUE THREAD

**Issue by QuaySo** [nextcloud/nextcloud-snap#673]
According to the [readme](https://github.com/nextcloud/nextcloud-snap#how-to-install) the Nextcloud Snap is designed to work on Ubuntu 16 series. Will it also work on Ubuntu 18? With the point release on 18 available, it might be nice to upgrade.

**Comment by kyrofa** [comment]
The README isn't phrased quite right. Indeed, this snap is built against series 16, but that doesn't actually have any relevance regarding where it will run. It will run on Fedora, it will run on Arch, it will run on Ubuntu 14.04, 16.04, 18.04, etc. It's a snap, if it doesn't run where snaps are supported, there's a problem!

To clearly answer your question: I develop the snap on 18.04 and test it there all the time. You can safely upgrade.
