### ISSUE TITLE
Alternative to stream behind a reverse proxy with nginx

### ISSUE THREAD

**Issue by tbille** [nextcloud/nextcloud-snap#679]
I am trying to run nextcloud snap with other services on my server.

The snap is behind a reverse nginx. So I followed this [documentation](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy). But it seems that this [part](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy#nginx) is not working if I have other services running on port 443.

Is there another way of running it without passing via the stream directive on nginx?

**Comment by kyrofa** [comment]
Quoting that wiki:

> NGINX is a little more difficult to setup as it wants badly to terminate SSL connections for you. If that works for you, great-- have the proxy machine handle the SSL stuff, and just leave the snap with HTTPS disabled. There are all sorts of docs out there for that, so I won't document it here.
>
> However, if you want the snap to continue managing Let's Encrypt certificates for you, that won't work. There is a way to get NGINX to pass along SSL-encrypted traffic without touching it, but it sort of breaks anything else you have on SSL.

I'm afraid the only way is to let nginx terminate SSL for you, which means managing the certs on your own instead of letting the snap do it.

**Comment by tbille** [comment]
Ok, I was curious if maybe some solutions had been found :smile: 
I'll manage them by myself.

Thanks

**Comment by kyrofa** [comment]
@tbille I can't claim to be an nginx pro, but that's the only way I've found. If you find something else, please do share!

**Comment by giocomai** [comment]
@tbille , could you please share your nginx config? The option to have the certificate taken care of out of the snap, and have a "regular" reverse proxy with nginx seems a reasonable one, but it is not discussed in the Wiki. Of course one can look at other sources, but having a nginx config file tested and working specifically with NextCloud snap would make things easier. Thanks!

**Comment by tbille** [comment]
@giocomai I am working on it for now, once I have something clean I will publish it in this issue to improve the wiki :smile:
