### ISSUE TITLE
lets encrypt not working

### ISSUE THREAD

**Issue by xxdxhxx** [nextcloud/nextcloud-snap#680]
Hello, 
Trying to enable https and keep failing.  Pretty new to snaps, but I think this is permissions related.
If I try to browse to the lets-encrypt response url I get:

> Forbidden
>You don't have permission to access /.well-known/acme-challenge/4fKlx0_zI1-iEYuiMC8TLhchCq0BEBnvRbjftfOev2s on this server.

Not sure where I go to check permissions.  Any help would be great.  I have been looking for the solution to avoid bothering you all with what is probably a trivial problem to fix, but I am not making much progress.  Perhaps I should do a manual install and avoid the snap?

oh, here  is the error from cli:

> Waiting for verification...
Cleaning up challenges
Failed authorization procedure. cabocloud.cabovillas.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://cabocloud.cabovillas.com/.well-known/acme-challenge/U00LIXVObGk7fjVxfoIqMtzG3H6lyWvKafV2afexW_4: "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http", cabocloud.caboserver.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://cabocloud.caboserver.com/.well-known/acme-challenge/4fKlx0_zI1-iEYuiMC8TLhchCq0BEBnvRbjftfOev2s: "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http"

I hope someone can give me a fix.  Thanks for the awesome software.

**Comment by kyrofa** [comment]
@xxdxhxx that domain name gives me a 403 no matter what path I try to use. It also doesn't look like an Apache error, which makes me think you have the snap behind some sort of proxy. Is that true?

**Comment by xxdxhxx** [comment]
No, just firewall.  Opened and forward of port 80 and 443, but no proxy.

**Comment by kyrofa** [comment]
@xxdxhxx this is what it would look like if you were hitting the snap:

![screenshot from 2018-08-21 14-29-52](https://user-images.githubusercontent.com/946674/44430200-cff87980-a54e-11e8-96b4-b1b0476770aa.png)

However, this is what yours looks like:

![screenshot from 2018-08-21 14-30-08](https://user-images.githubusercontent.com/946674/44430212-d5ee5a80-a54e-11e8-92bf-3d4c79b425a9.png)

**Comment by xxdxhxx** [comment]
yeah, that was a firewall issue.  I have fixed but now get that same forbidden error.  You can try now and see what I mean.

**Comment by xxdxhxx** [comment]
or try cabocloud.caboserver.com instead.  Both go to the same snap

**Comment by kyrofa** [comment]
http://cabocloud.caboserver.com/sdfglkjh gives me the same styled error page as before (and it's a 403, not a 404).

**Comment by xxdxhxx** [comment]
I had to make some dns changes so you can access, should be available soon.  My guess is that same problem that happened to you also happened to certbot.  Thanks for your quick response.  I had been testing internally and assumed my firewall config was correct...
I will make sure it is all public accessible and test before I waste your time further.

**Comment by kyrofa** [comment]
Yeah I suspect you may be right. Let's leave this open for now, give it 24 hours or so, if you're still having problems come back :) .

**Comment by xxdxhxx** [comment]
Update: Got it working.  Was networking/firewall issue on my end.  After I fixed that it worked like a charm.

Thanks again!!!

**Comment by kyrofa** [comment]
Excellent, thanks for getting back to us!
