### ISSUE TITLE
Change which port LetsEncrypt Uses

### ISSUE THREAD

**Issue by jasondefuria** [nextcloud/nextcloud-snap#689]
Hi there,

I am blocked on port 80. I setup a rule for my other devices to use port 8082, and I am able to use LetsEncrypt on them to get certificates. Is there a way to change the LetsEncrypt in snap to use that port?

Maybe there is a way to manually install the certificate, if a port change is not supported?
Thanks!

**Comment by kyrofa** [comment]
I'm afraid not, Let's Encrypt only supports port 80 at this time. You'll need to either use self-signed certificates, or use another manner to obtain certificates.
