### ISSUE TITLE
how-to-install-and-configure-nextcloud-on-ubuntu-18-04

### ISSUE THREAD

**Issue by generic-user** [nextcloud/nextcloud-snap#692]
Hi, I installed nextcloud using this tutorial in a digital ocean droplet on 18.04 Ubuntu. Using the SNAP package.
[how-to-install-and-configure-nextcloud-on-ubuntu-18-04](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-18-04)

Everything seems to be working fine, except for the "app-store" page.
It is not available in the admin settings.

Anyone any thoughts?

This is my config.php `/var/snap/nextcloud/current/nextcloud/config/config.php`

```php
<?php
$CONFIG = array (
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/snap/nextcloud/current/htdocs/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/snap/nextcloud/current/nextcloud/extra-apps',
      'url' => '/extra-apps',
      'writable' => true,
    ),
  ),
  'supportedDatabases' =>
  array (
    0 => 'mysql',
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/tmp/sockets/redis.sock',
    'port' => 0,
  ),
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'xxx.xxx.xx.xxx',
  ),
  'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '13.0.5.2',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:/tmp/sockets/mysql.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'instanceid' => 'xxx',
  'appstoreenabled' => true,

);
```

**Comment by kyrofa** [comment]
Huh. Maybe I'm being a bit dense, but... app store? Do you mean you don't see the "Apps" link like I do?
![screenshot from 2018-08-27 12-49-38](https://user-images.githubusercontent.com/946674/44682244-bbf1c380-a9f7-11e8-98a5-1f904aebcd1f.png)

**Comment by generic-user** [comment]
Ok, I need to go to bed, just spent 4 hours debugging because I was looking in the wrong place ...

Thanks a million! 

Just feel free to ignore me ...

![capture](https://user-images.githubusercontent.com/1516035/44682689-5a0b7b00-aa44-11e8-8107-6c22a375a446.JPG)

**Comment by kyrofa** [comment]
Oh thank goodness, I was SO confused :grinning: ! No worries, questions always welcome around here.
