### ISSUE TITLE
command not found: nextcloud.enable-https self-signed

### ISSUE THREAD

**Issue by KuenzelIT** [nextcloud/nextcloud-snap#694]
Hi,

after installing the snap on a fresh Debian 9 server, I geht the following 
```sudo: nextcloud.enable-https: command not found```

As I found in another issue, the absolute path works:
`sudo /snap/bin/nextcloud.enable-https self-signed`

Do you have any idea what's causing this issue?

Thanks!

**Comment by kyrofa** [comment]
Did you just recently install snapd? It may carry environment modifications along with it to put `/snap/bin` on the PATH, but you may need to logout/login to get it.
