### ISSUE TITLE
Add PostgeSQL driver support to nextcloud snap for access an existing PostgreSQL server

### ISSUE THREAD

**Issue by steffen201706** [nextcloud/nextcloud-snap#700]
Hi,

when i try to connect a snapped nextcloud to an existing postresql server, i see the following error: no database driver installed.

How can i add the pgsql driver with nextcloud snap?

best regards Steffen

**Comment by kyrofa** [comment]
Sorry @steffen201706, this isn't supported. The snap uses a bundled mysql.

**Comment by the-moog** [comment]
I'm migrating an existing NC server (using PGSQL) to a new server.  Does this mean that it's impossible to use the SNAP on the new server?

**Comment by kyrofa** [comment]
Technically no, but you'll need to make sure your database export is in a format that mysql can import.
