### ISSUE TITLE
Update nextcloud-snap

### ISSUE THREAD

**Issue by michau992** [nextcloud/nextcloud-snap#701]
Hi i check in https://scan.nextcloud.com my server has been: A. Last week i have : A+

Reason: NOT on latest patch level

Its possible a update from ssh?
sudo snap refresh nextcloud?

My version: Nextcloud 13.0.5.2

**Comment by kyrofa** [comment]
Because 13.0.6 was just released, you'll get it soon :) .

**Comment by michau992** [comment]
Thanks kyrofa.  How look like update process for me normally user :) ?

**Comment by kyrofa** [comment]
Snaps update automatically, so you'll really just wake up one morning and you'll be on 13.0.6.
