### ISSUE TITLE
Security & setup warnings after upgrading to 14/beta

### ISSUE THREAD

**Issue by Mczty** [nextcloud/nextcloud-snap#707]
Hello, I just upgraded nextcloud to 14/beta using `sudo snap refresh nextcloud --channel=14/beta` and i have com a crossed some warnings.

1, their is some missing stuff in the db. I fixed it using `sudo nextcloud.occ db:add-missing-indices`
2, `Use of the the built in php mailer is no longer supported. Please update your email server settings ` I don't have a php mailer set up in the first place so i can't really address that.
3, The "Referrer-Policy" HTTP header is not set to "no-referrer", "no-referrer-when-downgrade", "strict-origin" or "strict-origin-when-cross-origin". This can leak referer information. I can't find the apache2 config so i can't add the config options.

**Comment by Mczty** [comment]
i fixed Number 2 by messing around with the mail settings so the server can update my email method.

**Comment by kyrofa** [comment]
Thanks for this @Mczty, I'll look into it.

**Comment by Mczty** [comment]
i did a fresh install on 14/beta and only the http header and the mail security warning, the sql db security didn't appear. I have fixed the mail security warning by messing with the options so it will update. But i still can't find a way to fix the http header warning. I am using Ubuntu 18.4LTS. and this is a screenshot to the security warning. https://korzq.might-be-super.fun/da41dd.png

**Comment by kyrofa** [comment]
Note that the email warning is an upstream [bug](https://github.com/nextcloud/server/issues/11107).

**Comment by Mczty** [comment]
everything is fixed in 14/candidate.
Picture: https://korzq.might-be-super.fun/42cea0.png
Closing issue
