### ISSUE TITLE
LetsEncrypt DNS Challange

### ISSUE THREAD

**Issue by Stealthbird97** [nextcloud/nextcloud-snap#720]
Am I missing something or is there no way to use LetsEncrypt with a DNS Challenge for Cloudflare or other API's. 
This functionality is particularly useful for those who do not use port 80 or 443, and especially those who are not able to use it.

**Comment by kyrofa** [comment]
Not automatically, anyway. We may get there at some point, but the built-in commands uses a variant of the webroot plugin, which [only supports http-01](https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins). You can of course do this on your own and install them into the snap using `nextcloud.enable-https custom`, though.

**Comment by Stealthbird97** [comment]
Thanks
