### ISSUE TITLE
Filesize Limit - Nextcloud Sync Client

### ISSUE THREAD

**Issue by Hofer-Julian** [nextcloud/nextcloud-snap#721]
Hello!
I just freshly installed the Nextcloud Snap on a Odroid HC2 and it seems like the Nextcloud Client refuses to upload files bigger than 2GB.

The error is "Internal Server Error( Error while copying to target location (copied bytes 2147483647, expected filesize: -1))"

I also changed the data directory to an external drive.

Can anybody help me to find out where's the problem?  🙏

**Comment by ethanfann** [comment]
I would check which file system the external drive is formatted as. It sounds like it might be FAT16 which has a max file size of 2GB.

**Comment by thraemos** [comment]
Thank you!
Unfortunately, that's not the problem.
The drive is formatted with ext4 and I can upload files bigger than 2GB per webDAV.

**Comment by thraemos** [comment]
Also: download of files per syncclient which are bigger than 2 GB works.

**Comment by hwiorn** [comment]
@Hofer-Julian Please check to see if #791 has resolved this issue.

**Comment by Hofer-Julian** [comment]
Thank you for your link. Unfortunately I've already reinstalled nextcloud without the snap because of this issue.

**Comment by hwiorn** [comment]
I had a "500 Internal server error" problem if file size larger than 2GB on Odroid-XU4. Since the nextcloud desktop client uses webdav, you will also experience the same problem with webdav clients.

Odroid-HC2 is based on Odroid-XU4, arch is same armv7l. Therefore, there will be the same problem. https://archlinuxarm.org/platforms/armv7/samsung/odroid-hc2

**Comment by Hofer-Julian** [comment]
What do I have to do, to check if https://github.com/nextcloud/nextcloud-snap/issues/721?_pjax=%23js-repo-pjax-container#issuecomment-440502757 resolved my issue?

**Comment by Hofer-Julian** [comment]
Thanks, I will buy a second microSD card and then I will test it!

**Comment by Hofer-Julian** [comment]
It worked!

**Comment by Hofer-Julian** [comment]
Fixed by #862
