### ISSUE TITLE
Ubuntu 16.04 to 18.04: php connection

### ISSUE THREAD

**Issue by kwd42** [nextcloud/nextcloud-snap#722]
I'll apologize upfront for not keeping better records and for my not so careful update path.

I installed nextcloud snap about 2 months ago. Everything working fine. Then a little less than a month ago I performed a dist-upgrade of Ubuntu taking it from 16.04 to 18.04. Nextcloud stopped working. Scanning the logs and help forums leads me to believe I ended up with some kind of PHP version mismatch.

From apache/logs/php_errors.log
```
[16-Sep-2018 03:08:53 UTC] PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /snap/nextcloud/8267/htdocs/lib/private/DB/Connection.php:64
Stack trace:
#0 /snap/nextcloud/8267/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /snap/nextcloud/8267/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /snap/nextcloud/8267/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /snap/nextcloud/8267/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /snap/nextcloud/8267/htdocs/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /snap/nextcloud/8267/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__con in /snap/nextcloud/8267/htdocs/lib/private/DB/Connection.php on line 64
```

However, nextcloud.mysqldump did work, so I have opted to do a backup/reinstall/restore. 

The initial re-install did not allow me to make use of nextcloud.mysql-client or nextcloud.manual-install (connection errors). However switching to channel=beta resolved that issue and I was able to restore from my backup and the new nextcloud install seems to be happy again.

**Comment by kyrofa** [comment]
That looks like the database wasn't running (or was otherwise unavailable) for some reason. Without more logs I'm afraid it's impossible to know why.
