### ISSUE TITLE
Dead link in README leading on 404

### ISSUE THREAD

**Issue by adriens** [nextcloud/nextcloud-snap#730]
![2018-09-24 16_22_39-](https://user-images.githubusercontent.com/5235127/45938495-38d38580-c016-11e8-9a58-e3ebe77fd84d.png)

![2018-09-24 16_21_36-404 - page not found _ developer](https://user-images.githubusercontent.com/5235127/45938500-46890b00-c016-11e8-884c-15a32bf5df03.png)

**Comment by kyrofa** [comment]
That doesn't look like the README, it's the wiki, which is editable by everyone. Please feel free to update the link if you know where it should go.
