### ISSUE TITLE
How to migrate from nextcloud snap to lemp manual setup.

### ISSUE THREAD

**Issue by engyishere** [nextcloud/nextcloud-snap#735]
I need to migrate my nextcloud 13.0.6 setup from snap package to LEMP setup but i am having problems migrating it. please suggest way to do it.

Thanks

**Comment by stone212** [comment]
@engyishere I asked the same question and @kyrofa suggested this:

> https://github.com/nextcloud/nextcloud-snap/issues/788

It's not an answer but it is a start.

**Comment by stone212** [comment]
@engyishere I just finished a migration.  I like the snap but I needed something different. My PR is here: https://github.com/nextcloud/nextcloud-snap/pull/804
