### ISSUE TITLE
Deprecate non-forward-secrecy ciphers

### ISSUE THREAD

**Issue by bn4t** [nextcloud/nextcloud-snap#737]
I think it would be a good idea to no longer support non-forward-secrecy ciphers out of several reasons.

1. No forward secrecy (obvious)
2. Even IE on vista supports ephemeral keys (According to this list https://github.com/client9/sslassert/wiki/IE-Supported-Cipher-Suites)

By no longer supporting non-forward-secrecy ciphers we can increase security and still maintain compatibility to IE.

What are your thoughts on this? @kyrofa @pachulo @r4co0n

**Comment by pachulo** [comment]
I think it would be a good move @bn4t !
I think @kyrofa wanted to check everything related to ciphers and TLS configuration to update all of it at once, but I don't remember exactly...

**Comment by pachulo** [comment]
This is a nice resource: https://mozilla.github.io/server-side-tls/ssl-config-generator/
It shows which client will be supported each server configuration.

**Comment by kyrofa** [comment]
Please take a look at #941.
