### ISSUE TITLE
Store artifacts for PRs in CircleCI

### ISSUE THREAD

**Issue by bn4t** [nextcloud/nextcloud-snap#740]
I think it would be helpful to store the `.snap` build artifacts for PRs, so people can easily download and test them without having to build the snap on their own.

I'm not sure if there is a storage limit in CircleCI (They didn't write anything about that in [their documentation](https://circleci.com/docs/2.0/artifacts/)).

What do you think about this, @kyrofa (or anyone else)?

**Comment by bn4t** [comment]
Relevant PR if this becomes a thing: #742

**Comment by kyrofa** [comment]
We use [github snap builder](https://github.com/kyrofa/github-snap-builder) for this, now.
