### ISSUE TITLE
Internal server error after moving Nextcloud snap data directory

### ISSUE THREAD

**Issue by saadtech1** [nextcloud/nextcloud-snap#741]
![internal issue](https://user-images.githubusercontent.com/43807026/46399280-55ec1080-c708-11e8-9744-281176d29579.PNG)

I get this error after moving Nextcloud snap data directory to the second partition any solution?
Reference:
 https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition

**Comment by kyrofa** [comment]
Is your second partition accessible under confinement? Basically, did you connect the `removable-media` plug and is your partition mounted into /media somewhere? Otherwise, the snap simply can't access it.

**Comment by drjameskay** [comment]
Same problem here. I followed the same procedure.

**Comment by Chrozayis** [comment]
I have posted a related issue under this thread [Issue#797](https://github.com/nextcloud/nextcloud-snap/issues/767)

**Comment by ugurozturk** [comment]
Same

**Comment by kyrofa** [comment]
`/data1/nextcloud/data` isn't accessible under confinement. You need to use somewhere in `/media/` or `/mnt/` and make sure the `removable-media` plug is connected. I'm going to close this, if you have a new issue that is not resolved by following the above advice, please log it as such.
