### ISSUE TITLE
How to use newer openssl in nextcloud snap?  (NESSUS failure)

### ISSUE THREAD

**Issue by namronb** [nextcloud/nextcloud-snap#743]
I'm running Ubuntu 18.10 beta and installed the nextcloud snap (13.0.6snap1).  It's working great; thank you!  The only issue I have is that my workplace's NESSUS scanner registers a high vulnerability because of the openssl version (1.0.2g) in the snap:

```
user@host:~$ /snap/nextcloud/8971/usr/bin/openssl version
OpenSSL 1.0.2g  1 Mar 2016 (Library: OpenSSL 1.0.2n  7 Dec 2017)
```

I apologize for the naive question, but my machine will be blocked without resolving this.  I did read #286.  Am I to understand that this really is 1.0.2n but is reporting 1.0.2g.  Have I made some other silly mistake?

Thanks!

**Comment by kyrofa** [comment]
> Am I to understand that this really is 1.0.2n but is reporting 1.0.2g.

Note quite: new features aren't backported, just security fixes. But yes, that nessus failure isn't fully informed: if openssl is coming from a supported Ubuntu distro (which it is in this case), CVEs are fixed ASAP, even if the version doesn't change.
