### ISSUE TITLE
Mail with STARTTLS 1.2 only is Not Working

### ISSUE THREAD

**Issue by alexwijoyo** [nextcloud/nextcloud-snap#754]
Hi,
My mail server only support STARTTLS 1.2 so nextcloud-snap cannot send email anymore.
The issues and solution described below:
[Nextcloud issue 7421](https://github.com/nextcloud/server/issues/7421)
[Nextcloud issue 11408](https://github.com/nextcloud/server/issues/11408)
The quick fix is patching the file below:
`/snap/nextcloud/current/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php`
to support TLS 1.2
Since the StreamBuffer.php file is read only on nextcloud-snap, how can I patch this file?
Thanks.

**Comment by kyrofa** [comment]
Snaps are by definition read-only. I suggest proposing pull requests to fix this issue upstream, and as soon as it's contained in a release you'll get it in the snap.
