### ISSUE TITLE
Update base to core18

### ISSUE THREAD

**Issue by pachulo** [nextcloud/nextcloud-snap#755]
First, the reasons that come to my mind to make this upgrade:

- Get a newer version of GCC and "better" compiled binaries.
- Get OpenSSL 1.1.x and then access to configure and use TLS 1.3 and more performant crypto for HTTPS, like `TLS13-CHACHA20-POLY1305-SHA256` (https://www.openssl.org/blog/blog/2018/02/08/tlsv1.3/)
- Get a newer version of the library Nghttp2 (once we use it for HTTP2).

I did a quick test to see what would it take to update the nextcloud snap to use `core18` as its `base`, and it was almost too easy https://github.com/nextcloud/nextcloud-snap/compare/develop...pachulo:test-base18 : I only had to change the name of two packages!

I even tested the compiled snap:

- https://code.launchpad.net/~pachulo/+snap/pachulo-nextcloud-snap-core18

In my computer (new install) and in my rbpi3 instance (updating my installation) and everything went smooth, including the download of the core18 snap in my rbpi.

Nextcloud seems to work fine as far as I can tell. What do you think @kyrofa ?
Besides that, is `core18` stable enough?

**Comment by kyrofa** [comment]
I don't feel too strongly about this given that core/core16 is still supported, but you've pointed out some decent upsides to moving to core18. I'd like to wait for two things:

- core18 is not yet officially stable, but it should be soon
- The build infrastructure (snapcraft, build.snapcraft.io, and launchpad itself) haven't all landed proper core18 support

Once those pieces are in place, I think it'll be just fine to upgrade.

**Comment by pachulo** [comment]
What it's the status of core18 @kyrofa ?

**Comment by CmdrMichael** [comment]
> I don't feel too strongly about this given that core/core16 is still supported, but you've pointed out some decent upsides to moving to core18. I'd like to wait for two things:
> 
> * core18 is not yet officially stable, but it should be soon
> * The build infrastructure (snapcraft, build.snapcraft.io, and launchpad itself) haven't all landed proper core18 support
> 
> Once those pieces are in place, I think it'll be just fine to upgrade.

I think the pieces are now in place. The reason in the first post should be sufficient to plan a migration vom core16 to core18.

**Comment by kyrofa** [comment]
> I think the pieces are now in place.

Indeed they are.

> The reason in the first post should be sufficient to plan a migration vom core16 to core18.

Our security is excellent and core16 is still supported. In my mind, the potential issues (i.e. who knows what could happen) associated with upgrading outweigh the benefits of doing the upgrade. Until core18 offers something we really need, this will be difficult to justify.

**Comment by kyrofa** [comment]
This is still something I check on periodically. I still read concerning things, for example:

https://forum.snapcraft.io/t/need-both-core-and-core18-base-snaps-possible-to-rationalize/15382

At this point we may end up just waiting until core is no longer supported.

**Comment by pachulo** [comment]
I'm looking a this right now, because I would like to experiment with setting up TLS 1.3 for the snap...can we do anything else than waiting for April next year when core passes away @kyrofa ?

**Comment by kyrofa** [comment]
I think there are only two options when it comes to TLS 1.3:

1. Wait until we move to core18
2. Build our own openssl

The latter concerns me because if we use the from from the base snap we get security updates without having to do anything, but if we build our own we'll need to handle that ourselves.

**Comment by pachulo** [comment]
To me, the most sensible option is 1; I think that, right now, TLS 1.3 is not such a critical feature to have if it means going through option 2 path.
