### ISSUE TITLE
Is nextcloud.enable-https a snap specific command?

### ISSUE THREAD

**Issue by jcklpe** [nextcloud/nextcloud-snap#756]
I have installed NextCloud on my parent's desktop to turn it into a cloud server for them. I did this a couple of months ago when I was visiting. I was only able to get it working over http on a local network. I am back, and I'm trying to sort out their router and ISP issues so that they can access it through https through the internet and a custom domain. 

I'm starting by switching it over to https and installing let's encrypt certificates. Since installing there stuff I have learned a little bit more about how to use letsencrypt but I'm still pretty new to the process. 

I found a tutorial that said to use the command "nextcloud.enable-https". [[link here]](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-18-04) I get a response from the terminal saying that the command does not exist. I search for it online and find [[this part of the snap wiki]](https://github.com/nextcloud/nextcloud-snap/wiki/Enabling-HTTPS-(SSL,-TLS))

So I'm wondering is enable-https a snap install only command? What would be the equivalent for a normal server installation?

I'm running NextCloud 14.03 on an Ubuntu 18.04 installation.

**Comment by pachulo** [comment]
Yes it is, and no, there is not an equivalent for “normal” installations, at least that I know of.

**Comment by kyrofa** [comment]
I'm afraid so, yes. You'll need to install and use Let's Encrypt on your own if you're not using the snap.

**Comment by jcklpe** [comment]
thanks guy! I managed to get ssl etc working. I just had to run a command to open the firewall for port 80 and 443.
