### ISSUE TITLE
WebDAV 0 byte issue

### ISSUE THREAD

**Issue by AndreasSchantl** [nextcloud/nextcloud-snap#759]
I have got a problem with WebDAV as it is using PHP-FPM/FASTCGI wihich  results in files being uploaded with 0 bytes. I am using Mountainduck as my client and they made me aware of the problem being Nextcloud and not Mountainduck.

See here: https://trac.cyberduck.io/wiki/help/en/howto/mount/issues/fastcgi

Is there a way I can change the configuration myself without building a new snap package?

**Comment by kyrofa** [comment]
Yeah, this is #365, and it sucks, I'm sorry. We were using mod_php back in the day but it just doesn't offer any control over performance. If you require this functionality you'll need to either build your own snap or install Nextcloud from scratch. This is an issue Apache really needs to fix.
