### ISSUE TITLE
Allow nextcloud snap access to /home directory

### ISSUE THREAD

**Issue by HiDef888** [nextcloud/nextcloud-snap#761]
I tried to enable my nextcloud access to my home directory via
sudo snap connect nextcloud:home
error: snap "nextcloud" has no plug named "home"

It obviously failed, but I think it may be a good idea to allow users to mount their home filesystem with nextcloud because many people work from their home directories Documents,Pictures,Downloads,etc)
[https://docs.snapcraft.io/the-home-interface/7838](url)

Snapcraft allows interfacing with /home/$user and it seems that would be ideal in a cloud solution.  I am currently forced to use my network mounts in /media via "removable-media" instead of mounting my drives to Documents and Pictures in my home directory where they would normally reside and applications typically default to save.

What do you guys think?

**Comment by kyrofa** [comment]
This is the server we're talking about in this repo, not the client. The server creates a copy of all the data and holds it in a single location, which in pretty much every case I can think of wouldn't be the home directory, but some system-wide directory. Which means using the home plug would give it far more access than it needs or should have.

**Comment by HiDef888** [comment]
Sorry for confusion, in fact I am now a little bit confused!  I thought of the 'client' as the web interface and my iphone app.  The reason I assumed it belonged in this repo is because the readme on here talks about  sudo snap connect nextcloud:removable-media to allow you to mount external media.

Basically I setup network shares and then load them into nextcloud /media/Documents (for example) and that way I can read any work I've done while on the road on my phone.  I used the external storage app on the web interface to add this local network share (it's on a NAS mounted at boot by fstab).  More ideally, I would mount it to /home/$user/Documents in fstab because say I wanted to use OpenOffice to type a word doc and if I am on the road I can pull it up on my iphone in nextcloud and go over it.

As it stands, you can't really access your data in your home folder because nextcloud doesn't allow it (you can't mount it successfully in web client).  Now it may make copies of those directories to some snap location if you wish but like my Pictures, for example, I have 30-60gigs of data!  I'd rather just have nextcloud have access to that network share and serve it to me on request.

Is there somewhere else I should request this feature?  Or is the server snap actually the right place to request the :home plugin?  If nothing else it would seem not terribly insecure to make the home plug available in the snap but disabled by default then users could enable at their own risk.  Then you could mount home directories in the external storage app in the NC client.  This would unmarry us from the /media only mount point.

I hope that makes some sense!  Or that I'm not asking in the wrong repo!

**Comment by qwertyuser1983** [comment]
Rather than home, 

We should be able to chose any folder we wish for data, especially when multiple server instance, like in my case, Nextcloud + Ampache, share a very same folder. 

My old dirty way is to actually provide read only access to var/snap/nextcloud/.../[mediadata], which is very inconvenient

**Comment by kyrofa** [comment]
Sadly snap confinement isn't quite as flexible as we would sometimes like. Some day I imagine it will be possible to explicitly allow access to any given folder, but today is not that day.

**Comment by cldtech** [comment]
I need external storage that is neither /media nor /mnt. In fact why can't we choose any folder? Or at least follow symlinks? There must be something new new by now..

**Comment by kyrofa** [comment]
We Nextcloud snap maintainers aren't involved in such decisions. If you want to start a discussion about it, consider creating a new topic on the [snapcraft forums](https://forum.snapcraft.io/).
