### ISSUE TITLE
How can I add a file to Nextcloud from the server?

### ISSUE THREAD

**Issue by NightMachinary** [nextcloud/nextcloud-snap#773]
I like to use Nextcloud to keep a folder synced between my server and my iPad. How do I go about it?

**Comment by kyrofa** [comment]
You'll get better answers to such questions in the [Nextcloud forum](https://help.nextcloud.com/), but it sounds like you're looking for the [iOS mobile app](https://itunes.apple.com/us/app/nextcloud/id1125420102?mt=8)?

**Comment by NightMachinary** [comment]
No, I want to add files to the Nextcloud drive of a user (the admin,
actually) from bash running on the server. Something like
`nextcloud.addFile <username> <source-file> <destination-on-user-drive>`. I
think the way to do this changes when I have installed Nextcloud via snaps,
so I asked about it here.

**Comment by kyrofa** [comment]
Well, how would you do it without snaps? The way I've done this in the past is to move files into the `files` directory of the user's slice of the datadir,  make sure permissions were the same, and then run `occ files:scan --all`. In the snap it's the same, and the command is `nextcloud.occ files:scan --all`. Unless you've put the data elsewhere, the data is in `/var/snap/nextcloud/common/nextcloud/data/`.

**Comment by NightMachinary** [comment]
Thanks🌸🌸
