### ISSUE TITLE
Support for TLS-ALPN-01 with Let's Encrypt

### ISSUE THREAD

**Issue by fpernice518** [nextcloud/nextcloud-snap#789]
I posted a question on the Let's Encrypt page to see if there's any solutions for those of us with ISPs who block port 80. It apparently now supports TLS-ALPN-01. Any plans to implement this in the future?

https://community.letsencrypt.org/t/whats-the-status-on-tls-sni-01-challenge/77702/2

**Comment by kyrofa** [comment]
Thanks for the heads up! However, it sounds like the tech stack at large isn't quite ready for this change yet:

https://community.letsencrypt.org/t/so-how-are-we-bringing-tls-alpn-to-the-masses/63824/21

I'll continue investigating. Meanwhile, is DNS verification an option for you?

**Comment by fpernice518** [comment]
It might be, not sure. How do I do it? I'd like to use Let's Encrypt or other free certificate provider and I really don't want to deal with self-signed certs anymore. Thanks

**Comment by thermionic** [comment]
There is a DNS-01 with acme.sh https://github.com/Neilpang/acme.sh

**Comment by kyrofa** [comment]
Darn, it looks like it would essentially be impossible to support automatic renewals for all DNS providers (given that they don't all have an API and the ones that do differ from each other, of course). @fpernice518 I think the best way to get you off self-signed certs would be to disable SSL in the snap and handle SSL in e.g. haproxy instead, with certbot installed on your own. Then you can use the DNS plugins as necessary.

**Comment by thermionic** [comment]
@kyrofa although most implemntations I have seen using acme.sh are DNS-01, it also supports HTTP-01 for those that are unable to use DNS-01. Also acme.sh is considerably smaller than certbot and does not have the same extensive dependancies. Granted configuration of acme.sh is a little more complex with the different options required by each DNS provider plugin...

**Comment by kyrofa** [comment]
@thermionic acme.sh looks nice, agreed. But I see no real benefit to offset the work of moving away from certbot. Not to mention I would be pretty surprised if acme.sh could seamlessly transition in and continue updating certs obtained by certbot without manual interaction.

**Comment by fpernice518** [comment]
> Darn, it looks like it would essentially be impossible to support automatic renewals for all DNS providers (given that they don't all have an API and the ones that do differ from each other, of course). @fpernice518 I think the best way to get you off self-signed certs would be to disable SSL in the snap and handle SSL in e.g. haproxy instead, with certbot installed on your own. Then you can use the DNS plugins as necessary.

So this?
https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy

**Comment by kyrofa** [comment]
That entry lists ways to continue letting the snap manage your certs while using a proxy, which isn't quite what you want. I suggest handling the certs on the proxy end (e.g. haproxy or nginx) and then proxying to the snap without HTTPS setup in the snap at all. That way you can use one of the DNS plugins in certbot, or indeed just use acme.sh if you find that easier.

**Comment by thermionic** [comment]
@kyrofathere are seperately downloadable plugins for 12 DNS providers with certbot, acme.sh has support for over 50 built in.

I don't follow the requirement to update existing certificates, this is letsencrypt, deployed in a snap format, simply issue a new cert using acme.sh...

**Comment by kyrofa** [comment]
> I don't follow the requirement to update existing certificates

**Comment by kyrofa** [comment]
> I don't follow the requirement to update existing certificates [...].

Today, a certificate is obtained with certbot in the snap (a manual action), which is thereafter automatically renewed by the snap. If we switch to acme.sh, can we continue to automatically renew the certs already in place?

**Comment by thermionic** [comment]
If ywe just take a step back for a moment.

To issue a certiificate with certbot using HTTP-01, two pieces of information are required

1. The hostname(s) for the certificate
2. The -webroot path (not required is using the Apache plugin)

Other information such as an email address can be provided, but only those two pieces of information that are required

As a letsencrypt certificate only has a lifetime of 90 days, certbot has the capability to "renew" a certificate. The reason I put renew in quotes, is that although it is used as the standard term, in fact, just like a passport, a new certificate is issued, the certificate has the same hostname, but it will have a new serial number and new valid to and from dates.

Taken from the certbot user guide "--force-renewal tells Certbot to request a new certificate" 

Therefore as the nextcloud snap has the hostname (and the path to teh root of the webserver is also known), all of the information required to use acme.sh (or any other letsencrypt client) is already there, and a new certificate can be issued using the new client.

**Comment by kyrofa** [comment]
To bring this conversation to a close, I see no real benefit to switching to acme.sh, but we can keep it in mind if certbot breaks on us. There is, I'm afraid, no real solution to this issue right now.

**Comment by enoch85** [comment]
*following*

**Comment by enoch85** [comment]
@kyrofa If you find any solution, please let me know as well. 

Thanks!
