### ISSUE TITLE
Large file support in 32bit

### ISSUE THREAD

**Issue by hwiorn** [nextcloud/nextcloud-snap#792]
_Since I made the PR #791 wrong, I created this issue first through the contribution guide and then created the PR #793 again._

nextcloud-snap will cause a "fopen: Value too large for defined data type" error when reading a file larger than 2G on 32-bit. This problem occurs not only on the web, but also on the webdav client (e.g. desktop client, mobile webdav client).

If this error occurs, the WebDAV client will see the message "500 Internal Server Error".

This error is because PHP does not natively support the large file support (LFS) option, which allows to process files larger than 2G in 32-bit(e.g. raspberry-pi, odroid-xu4, x86). So, i added LFS option to snapcraft.yml(PR #793).

```
CFLAGS=-D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64
```

See the link below for PHP LFS options.

- http://php.net/manual/en/intro.filesystem.php

I confirmed it's worked using the armhf snap below with the Odroid-XU4 (armv7l).

- armhf snap: https://launchpad.net/~hwiorn/+snap/nextcloud-for-32bit/+build/381922/+files/nextcloud_13.0.7snap1_armhf.snap
- arm64 snap: https://launchpad.net/~hwiorn/+snap/nextcloud-for-32bit/+build/381921/+files/nextcloud_13.0.7snap1_arm64.snap
- i386 snap: https://launchpad.net/~hwiorn/+snap/nextcloud-for-32bit/+build/381923/+files/nextcloud_13.0.7snap1_i386.snap
- amd64 snap: https://launchpad.net/~hwiorn/+snap/nextcloud-for-32bit/+build/381914/+files/nextcloud_13.0.7snap1_amd64.snap

This option appears to have no effect on 64-bit. However, testing will be necessary. It might be better to be able to dynamically configure snapcraft so that the following command will only activate the options in 32-bit(Actually i don't know snapcraft syntax well).

```
CFLAGS=$(getconf LFS_CFLAGS)
```

When building armhf, I did not add LFS CFLAGS to Apache and MySQL because there is already the LFS option in the Apache and MySQL-Server build logs.

- armhf: https://launchpadlibrarian.net/398090788/buildlog_snap_ubuntu_xenial_armhf_nextcloud-for-32bit_BUILDING.txt.gz
- amd64: https://launchpad.net/~hwiorn/+snap/nextcloud-for-32bit/+build/381914/+files/buildlog_snap_ubuntu_xenial_amd64_nextcloud-for-32bit_BUILDING.txt.gz

_Note that the nextcloud/docker armhf version also has the same problem ("fopen: Value too large for defined data type") because it uses the default PHP  without LFS provided by the docker hub._

**Comment by delfer** [comment]
Fixed by docker-library/php#901
Tested in Docker image `nextcloud:17-apache` (`nextcloud@sha256:58836d449406b396c1c119c2661577fd7d8284ff41a7d181a0e2be232d2757fc`, `2019-10-24T05:04:49.946856094Z`)
