### ISSUE TITLE
[Wiki] snap1 vs snap2

### ISSUE THREAD

**Issue by lindhe** [nextcloud/nextcloud-snap#798]
Would be nice to know the difference between the tags `snap1` and `snap2` in this repo. But I cannot find any info on it in the Wiki.

(sorry if I missed it, but I searched for it and couldn't find it)

**Comment by pachulo** [comment]
I think this is just a convention: if the nextcloud version is not updated, but something else is, then a `snapX` version is tagged and released.

**Comment by lindhe** [comment]
Oh, I see. Like configuration, packaging etc. That's nice. I'm adding it here: https://github.com/nextcloud/nextcloud-snap/wiki/Contributing

**Comment by kyrofa** [comment]
Yeah exactly. We want a version number that communicates what version of Nextcloud is being used, but the snap contains much more than just Nextcloud, so we need a way to communicate changes beyond just Nextcloud. For example, if you compare the [changelog entry for 13.0.7snap1](https://github.com/nextcloud/nextcloud-snap/blob/master/CHANGELOG#L7) to [the changelog entry for 13.0.7snap2](https://github.com/nextcloud/nextcloud-snap/blob/master/CHANGELOG#L1) you'll see that Nextcloud was updated to 13.0.7 in snap1, but stuff _other_ than Nextcloud changed in snap2 (certbot was the big one, a security update).
