### ISSUE TITLE
Update phpredis to 3.16

### ISSUE THREAD

**Issue by pachulo** [nextcloud/nextcloud-snap#802]
Maybe we should update phpredis to 3.1.6 as per:
https://github.com/phpredis/phpredis/blob/develop/package.xml#L283

Or even maybe 4.2.0 if it doesn't break anything:
https://github.com/phpredis/phpredis/blob/develop/package.xml#L256

**Comment by r4co0n** [comment]
@pachulo: I assume there is no breakage that you are aware of? Have you already tried building the snap againt `phpredis 4.2.0`? This seems a worthwhile task that could also qualify for `good first issue`.

**Comment by JamesBream** [comment]
The docs for NC15 suggest using "Redis PHP module 3.1.x or later" and given that PHP Redis 4.0 came out near enough a year ago, I'd imagine that'd be enough time for issues to be spotted if there were any. 

I can only find the one relevant thread to suggest that the 4.0 version works (https://help.nextcloud.com/t/is-redis-php-driver-4-0-0-supported/30000), but given the above feel like it's worth us giving the 4.2 version a try. I don't think NC's use case for Redis is particularly complex so it should be easy enough to see whether file locking is working.

**Comment by pachulo** [comment]
No I haven't, I'm quite busy right now, but will try to test it this weekend.
