### ISSUE TITLE
Federation: Can't add trusted nextcloud server if SSL Cert is self-signed.

### ISSUE THREAD

**Issue by fishscene** [nextcloud/nextcloud-snap#81]
Federation: Can't add trusted nextcloud server if SSL Cert is self-signed.

I was attempting to run a test to link 2 snap installations of NextCloud with federation, but the following error was generated:
cURL error 60: SSL certificate problem: self signed certificate

Self-signed certs aren't a problem. Maybe a warning perhaps, but not a problem. Why would a server admin need to rely on outside parties to verify an internal server is what it says it is?

It would seem to me that an override option should be available, preferably with the cert displayed for manual verification. After all, I trust my servers. :)

Nextcloud Snap 9.x on Ubuntu 16.04.

**Comment by kyrofa** [comment]
> Self-signed certs aren't a problem. Maybe a warning perhaps, but not a problem. Why would a server admin need to rely on outside parties to verify an internal server is what it says it is?

> It would seem to me that an override option should be available, preferably with the cert displayed for manual verification. After all, I trust my servers. :)

I agree with you, but unfortunately this isn't something that we can control from within the snap-- it's an upstream Nextcloud problem. Please log an issue against the Nextcloud server!

**Comment by fishscene** [comment]
Posted in: https://github.com/nextcloud/server/issues/1413
