### ISSUE TITLE
Is it possible to use FFmpeg to generate thumbnails for MP4 files with NC Snap

### ISSUE THREAD

**Issue by AaronADev** [nextcloud/nextcloud-snap#813]
Hello all - 

I have been trying to get thumbnails generated for MP4 files for some time now with no success. Is there a different procedure to follow other than the one detailed in [NextCloud 14 Admin Docs](https://docs.nextcloud.com/server/14/admin_manual/)?

I haven't been able to figure out how to change the path for the preview generation to access the ffmpeg binary in the snap.

Is there anyone that could offer some advice on how to achieve this? I was able to configure the non-snap server I test on with MP4 thumbnail generation but no yet with the snap.

I am using the 14/candidate channel. 

Any guidance or advice is greatly appreciated. This would be great to have working.

**Comment by pachulo** [comment]
As far as I know the snap does no include ffmpeg, so it won't be able to access it even when installed in the system.
I also think that it won't get included in the snap, as it wasn't imagemagick: https://github.com/nextcloud/nextcloud-snap/issues/592#issuecomment-423813065

**Comment by AaronADev** [comment]
@pachulo Thanks for your feedback. I appreciate it.

**Comment by nickcmaynard** [comment]
> As far as I know the snap does no include FFmpeg, so it won't be able to access it even when installed in the system.
> I also think that it won't get included in the snap, as it wasn't imagemagick: [#592 (comment)](https://github.com/nextcloud/nextcloud-snap/issues/592#issuecomment-423813065)

I'm sorry - I'm not sure I understand.  How does the decision regarding imagemagick affect ffmpeg?

**Comment by ngvoicu** [comment]
I would like ffmpeg included in the snap also. Please
