### ISSUE TITLE
14.0.4snap1-rc1 tagging files error

### ISSUE THREAD

**Issue by tscsmith** [nextcloud/nextcloud-snap#817]
Can't set Tags to any files or folders. Tags function does not work anymore.
I tried several browsers to check if it is a browser presentation error, but that's not the case.
I think its related to a steylecheet error or something is not linked correctly in 14.0.4snap1-rc1

![tag error](https://user-images.githubusercontent.com/46021479/50279347-b5290980-0449-11e9-92d6-e66643078267.PNG)

**Comment by lug-gh** [comment]
Can confirm, this happened in my installation too. (This may not be a snap issue, as this also happens in manually installed 14.0.4) https://github.com/nextcloud/server/issues/12707
seems to be fixed in v15

**Comment by pachulo** [comment]
This does not seem to be a snap only issue then. Closing.
