### ISSUE TITLE
Snap install: Failed to mount Mount unit for core

### ISSUE THREAD

**Issue by tseegers** [nextcloud/nextcloud-snap#818]
Hi guys, i am having troubles with the snap installation and unfortunalty the error message is not very helpful :( i have looked other syslog and other classic logs but i got the same error message (below) everywhere. Does someone know how can i get more info to troubleshoot the installation ?

Here are some info about my dedicated server:
root@ns531084:/# cat /etc/debian_version
9.6

root@ns531084:/# uname -a
Linux ns531084 4.9.144-xxxx-std-ipv6-64 #494761 SMP Mon Dec 10 14:02:48 UTC 2018 x86_64 GNU/Linux

root@ns531084:/# df -h
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
udev               3,9G       0  3,9G   0% /dev
tmpfs              788M     26M  762M   4% /run
/dev/sda2           20G    1,6G   17G   9% /
tmpfs              3,9G    8,0K  3,9G   1% /dev/shm
tmpfs              5,0M       0  5,0M   0% /run/lock
tmpfs              3,9G       0  3,9G   0% /sys/fs/cgroup
/dev/sda1          487M     30M  429M   7% /boot
/dev/sda3          1,8T    3,1G  1,7T   1% /home

root@ns531084:/# free -h
              total        used        free      shared  buff/cache   available
Mem:      7,7G        848M        2,4G         25M        4,5G        6,5G
Swap:      510M          0B        510M

root@ns531084:/# snap install nextcloud
error: cannot perform the following tasks:
- Mount snap "core" (6130) ([start snap-core-6130.mount] failed with exit status 1: Job for snap-core-6130.mount failed.
See "systemctl status snap-core-6130.mount" and "journalctl -xe" for details.
)
root@ns531084:/# journalctl -xe
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- L'unité (unit) snapd.socket a terminé son démarrage, avec le résultat done.
déc. 21 18:19:08 ns531084 systemd[1]: snapd.refresh.timer: Adding 2h 34min 28.724446s random time.
déc. 21 18:19:08 ns531084 systemd[1]: Reloading.
déc. 21 18:19:08 ns531084 systemd[1]: apt-daily-upgrade.timer: Adding 19min 40.446456s random time.
déc. 21 18:19:08 ns531084 systemd[1]: apt-daily.timer: Adding 9h 20min 31.437200s random time.
déc. 21 18:19:08 ns531084 systemd[1]: Reloading.
déc. 21 18:19:08 ns531084 systemd[1]: apt-daily-upgrade.timer: Adding 58min 55.159954s random time.
déc. 21 18:19:08 ns531084 systemd[1]: apt-daily.timer: Adding 10h 9min 35.477288s random time.
déc. 21 18:19:08 ns531084 systemd[1]: Started Snappy daemon.
-- Subject: L'unité (unit) snapd.service a terminé son démarrage
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- L'unité (unit) snapd.service a terminé son démarrage, avec le résultat done.
déc. 21 18:19:08 ns531084 /usr/lib/snapd/snapd[13465]: daemon.go:250: DEBUG: init done in 413.609µs
déc. 21 18:19:08 ns531084 /usr/lib/snapd/snapd[13465]: daemon.go:251: started snapd/2.21-2+b1 (series 16; classic; devmode) debian/9 (amd64).
déc. 21 18:19:08 ns531084 snapd[13465]: 2018/12/21 18:19:08.986388 daemon.go:251: started snapd/2.21-2+b1 (series 16; classic; devmode) debian/9 (amd64).
déc. 21 18:19:08 ns531084 systemd[1]: Reloading.
déc. 21 18:19:09 ns531084 systemd[1]: apt-daily-upgrade.timer: Adding 28min 24.348427s random time.
déc. 21 18:19:09 ns531084 systemd[1]: apt-daily.timer: Adding 5h 21min 6.195156s random time.
déc. 21 18:19:09 ns531084 systemd[1]: Starting Auto import assertions from block devices...
-- Subject: L'unité (unit) snapd.autoimport.service a commencé à démarrer
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- L'unité (unit) snapd.autoimport.service a commencé à démarrer.
déc. 21 18:19:09 ns531084 snap[13490]: auto-import is disabled on classic
déc. 21 18:19:09 ns531084 systemd[1]: Started Auto import assertions from block devices.
-- Subject: L'unité (unit) snapd.autoimport.service a terminé son démarrage
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- L'unité (unit) snapd.autoimport.service a terminé son démarrage, avec le résultat done.
déc. 21 18:19:17 ns531084 /usr/lib/snapd/snapd[13465]: api.go:879: Installing snap "nextcloud" revision unset
déc. 21 18:19:17 ns531084 snapd[13465]: 2018/12/21 18:19:17.512618 api.go:879: Installing snap "nextcloud" revision unset
déc. 21 18:19:18 ns531084 /usr/lib/snapd/snapd[13465]: taskrunner.go:353: DEBUG: Running task 81 on Do: Download snap "core" (6130) from channel "stable"
déc. 21 18:19:18 ns531084 /usr/lib/snapd/snapd[13465]: daemon.go:176: DEBUG: uid=0;@ POST /v2/snaps/nextcloud 970.225588ms 202
déc. 21 18:19:27 ns531084 /usr/lib/snapd/snapd[13465]: taskrunner.go:353: DEBUG: Running task 82 on Do: Fetch and check assertions for snap "core" (6130)
déc. 21 18:19:28 ns531084 /usr/lib/snapd/snapd[13465]: taskrunner.go:353: DEBUG: Running task 83 on Do: Mount snap "core" (6130)
déc. 21 18:19:29 ns531084 systemd[1]: Reloading.
déc. 21 18:19:29 ns531084 systemd[1]: apt-daily-upgrade.timer: Adding 28min 9.777463s random time.
déc. 21 18:19:29 ns531084 systemd[1]: apt-daily.timer: Adding 9h 24min 30.722197s random time.
déc. 21 18:19:29 ns531084 systemd[1]: Mounting Mount unit for core...
-- Subject: L'unité (unit) snap-core-6130.mount a commencé à démarrer
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- L'unité (unit) snap-core-6130.mount a commencé à démarrer.
déc. 21 18:19:29 ns531084 systemd[1]: snap-core-6130.mount: Mount process exited, code=exited status=32
déc. 21 18:19:29 ns531084 systemd[1]: Failed to mount Mount unit for core.
-- Subject: L'unité (unit) snap-core-6130.mount a échoué
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- L'unité (unit) snap-core-6130.mount a échoué, avec le résultat failed.
déc. 21 18:19:29 ns531084 systemd[1]: snap-core-6130.mount: Unit entered failed state.
déc. 21 18:19:29 ns531084 /usr/lib/snapd/snapd[13465]: task.go:303: DEBUG: 2018-12-21T18:19:29Z ERROR [start snap-core-6130.mount] failed with exit status 1: Job for snap-core-6130.mount failed.
                                                        See "systemctl status snap-core-6130.mount" and "journalctl -xe" for details.
déc. 21 18:19:29 ns531084 /usr/lib/snapd/snapd[13465]: taskrunner.go:353: DEBUG: Running task 81 on Undo: Download snap "core" (6130) from channel "stable"

root@ns531084:/# systemctl status snap-core-6130.mount
● snap-core-6130.mount - Mount unit for core
   Loaded: loaded (/etc/systemd/system/snap-core-6130.mount; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-12-21 18:19:29 UTC; 1min 2s ago
    Where: /snap/core/6130
     What: /var/lib/snapd/snaps/core_6130.snap
  Process: 13580 ExecMount=/bin/mount /var/lib/snapd/snaps/core_6130.snap /snap/core/6130 -t squashfs (code=exited, status=32)

déc. 21 18:19:29 ns531084 systemd[1]: Mounting Mount unit for core...
déc. 21 18:19:29 ns531084 systemd[1]: snap-core-6130.mount: Mount process exited, code=exited status=32
déc. 21 18:19:29 ns531084 systemd[1]: Failed to mount Mount unit for core.
déc. 21 18:19:29 ns531084 systemd[1]: snap-core-6130.mount: Unit entered failed state.

**Comment by kyrofa** [comment]
What is the environment in which you have the snap installed? It looks to me like your kernel doesn't support squashfs, which is a requirement for snaps.

**Comment by tseegers** [comment]
Hello, thank you for your answer, I think you are probably right, my cloud provider (kimsufi) probably has customized the kernel too much. I am going to see if I can reinstall a proper OS.
Nice job by the way, I already use this snap on other servers without any problems, keep it going !

**Comment by souha00001** [comment]
i cannot start snapd

**Comment by gradvis** [comment]
In my case clear snapd cache (/var/lib/snapd/cache) resolve issue
