### ISSUE TITLE
External User Support 0.4 does not work in Snap image for Nextcloud 15.0.0 (max version is 14)

### ISSUE THREAD

**Issue by gabrielmongefranco** [nextcloud/nextcloud-snap#820]
Affected apps

Tell us which app(s) you are talking about
External User Support (user_external)
Steps to reproduce

  

1. Install NextCloud 15 via Snappy image on Debian 9
2. Create admin account.
3. Login as admin.
4. Go to Settings -> Apps -> Disabled Apps
5. Click Enable on External User Support

Expected behaviour

Tell us what should happen
Application should be successfully enabled.
Actual behaviour

Tell us what happens instead
Application is not enabled, and instead this error message is shown:

> This app cannot be installed because the following dependencies are not fulfilled:
> Server version 14 or lower is required.
>

**Comment by gabrielmongefranco** [comment]
Moved issue from: https://github.com/nextcloud/apps/issues/73
This seems like a better place for it.

**Comment by kyrofa** [comment]
Well, if the app doesn't support v15 there's not a lot we can do in the snap to fix this.

**Comment by gabrielmongefranco** [comment]
> Well, if the app doesn't support v15 there's not a lot we can do in the snap to fix this.

No, that's not what I said. I said the error message is that that the App compiled with Snap doesn't support version 15 of Nextcloud. The App does in fact support version 15. It was updated a day or two after you compiled the rc1 Snap.

See the file history for the user_external App here:

https://github.com/nextcloud/apps/commit/0a33a1ea349ee902738959ef6f8b167f0c345289

**Comment by kyrofa** [comment]
Download the v15 tarball and you'll see for yourself. Specifically, download [this](https://download.nextcloud.com/server/releases/nextcloud-15.0.0.tar.bz2), unpack it, and take a look at `apps/user_external/appinfo/info.xml`, and you'll see that version doesn't support v15. I expect 15.0.1 will include the update.
