### ISSUE TITLE
External User Support App in v15 snap is the wrong version

### ISSUE THREAD

**Issue by gabrielmongefranco** [nextcloud/nextcloud-snap#821]
> Well, if the app doesn't support v15 there's not a lot we can do in the snap to fix this.

_Originally posted by @kyrofa in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ1MDIxMDcwMw==/timeline/issue_comment#issuecomment-450210703_

No, that's not what I said. I said the error message is that the App compiled with Snap doesn't support version 15 of Nextcloud. The App does in fact support version 15. It was updated a day or two after you compiled the v15 rc1 Snap.

See the file history for the user_external App here:

https://github.com/nextcloud/apps/commit/0a33a1ea349ee902738959ef6f8b167f0c345289?diff=unified

It clearly shows that it was updated to support version 15.

I believe what needs to happen is that the Snap needs to be compiled with the latest version of the App.

**Comment by kyrofa** [comment]
Please don't log new issues, we can reopen old ones if they're still deemed relevant, and until we have determined so we can continue having a discussion on the other bug.
