### ISSUE TITLE
Unexpected behaviour when --value= ommitted from nextcloud.occ

### ISSUE THREAD

**Issue by Chrozayis** [nextcloud/nextcloud-snap#823]
**Actual Behaviour**
Running
`sudo nextcloud.occ config:system:set datadirectory /media/nextcloud/data`
 results in a success message that looks off
`System config value datadirectory => /media/nextcloud/data set to empty string`

Looking at config.php I see that it has overwritten the string value with an array containing an empty string at index /media/nextcloud/data

(For anybody coming here trying to fix their issue, the correct command is
`sudo nextcloud.occ config:system:set datadirectory --value=/media/nextcloud/data`)

**Expected behaviour:**
Under no circumstances should nextcloud.occ corrupt the settings file and display a success message.

A warning that --value= has been ommitted or for nextcloud.occ and/or nextcloud.occ making an intelligent assumption about what the user is trying to do would also be greatly appreciated.

**Comment by kyrofa** [comment]
`nextcloud.occ` is just a [passthrough to upstream Nextcloud's occ](https://github.com/nextcloud/nextcloud-snap/blob/master/src/nextcloud/bin/occ#L21). I suggest you log the bug in [upstream Nextcloud](https://github.com/nextcloud/server/).
