### ISSUE TITLE
How to apply SSL using lets-encrypt while not using default ports 80/443

### ISSUE THREAD

**Issue by Daniel-Jomaa** [nextcloud/nextcloud-snap#832]
I am running an apache 2.4 server on ubuntu 18.04 that serves a website on ports 80/443.I used lets-encrypt to give an SSL cert for the website which is functioning normally.

Since i am serving a website on 80/443 I set nextcloud to 8000 (http) and 8443(https), which can be accessed using http://example.com:8000 however https://example.com:8443 does not work. 

I tried using `sudo nextcloud.enable-https lets-encrypt` and go the following error message: 
```
Attempting to obtain certificates... error running certbot:

Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Plugins selected: Authenticator nextcloud:webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for www.compiledna.com
Using the webroot path /var/snap/nextcloud/current/certs/certbot for all domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. www.compiledna.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.compiledna.com/.well-known/acme-challenge/nnJiOl97GFBr1FhKqCQ775k71b2AYC8XQ4yUN6G2ny8: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was"
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.compiledna.com
   Type:   unauthorized
   Detail: Invalid response from
   http://www.compiledna.com/.well-known/acme-challenge/nnJiOl97GFBr1FhKqCQ775k71b2AYC8XQ4yUN6G2ny8:
   "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2
   Final//EN\">
<title>404 Not Found</title>
<h1>Not
   Found</h1>
<p>The requested URL was"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```
I suspect it is because i am not using 80/443 as in the requirements it states that: 

```
3. Both ports 80 and 443 on the external IP address of this machine
   must point to this machine (e.g. port forwarding might need to be
   setup on your router).
```
Is there a way to enable SSL on nextcloud while deploying it on ports other than 80/443

**Comment by ykgmfq** [comment]
You should use your Apache to [reverse proxy](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy) your port 8000, ideally with a subdomain at cloud.example.com. That way there is no need for either the snap https port or the snap letsencrypt.

**Comment by kyrofa** [comment]
I'm afraid Let's Encrypt doesn't support non-standard ports, there's no way to do this without a proxy.
