### ISSUE TITLE
Custom apache config

### ISSUE THREAD

**Issue by markusschweitzer** [nextcloud/nextcloud-snap#834]
Hi,

is there any way to add lines to the apache config? e.g a custom.conf
I cant find anything like this in /var/snap/nextcloud/current/apache/
The files under /snap are ofc readonly.

Any way to add things to the config?

Best regards

**Comment by kyrofa** [comment]
I'm afraid not, no. The fact that Apache is even used should be transparent to you. What functionality are you missing?

**Comment by r4co0n** [comment]
I am feeling free to close this issue, as @markusschweitzer pointed out, a reverse proxy web server in front of the NextCloud snap is the way to go if you want to serve snap-external content on the same domain.
