### ISSUE TITLE
Complete reset

### ISSUE THREAD

**Issue by jdgallag84** [nextcloud/nextcloud-snap#841]
I believe I have screwed up a setting on my nextcloud server snap install.  I cannot edit encrypted files, or they are deleted from the server.  I would just like to completely uninstall the snap with all configuration, wipe out app settings (including encryption), remove users, etc.  And then reinstall as though it's the first time being installed.

Is there a means to do this with the snap?

Sincerely,
Jonathan

**Comment by kyrofa** [comment]
You can simply uninstall the snap, is that what you're looking for?
