### ISSUE TITLE
error: cannot refresh "nextcloud": cannot refresh snap-declaration for "core"

### ISSUE THREAD

**Issue by iegtcamnp** [nextcloud/nextcloud-snap#851]
I am running  a Nextcloud Box w/ a Raspberry Pi3. Attempted to update nextcloud via `sudo snap refresh nextcloud --channel=stable` and received the following error 

> error: cannot refresh "nextcloud": cannot refresh snap-declaration for "core": Get
       https://api.snapcraft.io/api/v1/snaps/assertions/snap-declaration/16/99T7MUlRhtI3U0QFgl5mXXESAiSwt776?max-format=2:
       net/http: request canceled while waiting for connection (Client.Timeout exceeded while
       awaiting headers)

I couldn't find any helpful solutions to this problem so I'm trying my luck here. 
Things I've already tried
- `sudo snap refresh ubuntu-core`

> error: cannot refresh "ubuntu-core": cannot refresh snap-declaration for "snapweb": Get
       https://api.snapcraft.io/api/v1/snaps/assertions/snap-declaration/16/cr5pkasGhR7N3M8wKfP9DJqGxbBGeET2?max-format=2:
       net/http: request canceled while waiting for connection (Client.Timeout exceeded while
       awaiting headers)

- `sudo snap refresh`

>  error: cannot refresh: cannot refresh snap-declaration for "wdl-nextcloud": Get
       https://api.snapcraft.io/api/v1/snaps/assertions/snap-declaration/16/hUQXrvsg286Yh4m1GQ6ODW9WKIOcsHyH?max-format=2:
       net/http: request canceled while waiting for connection (Client.Timeout exceeded while
       awaiting headers)

Here is some relevant info on the setup.

Name | Version | Rev | Tracking | Publisher | Notes
------|---------|-----|----------|----------|--------
core | 16-2.35.5 | 5744 | stable | canonical | core
nextcloud |13.0.5snap1 | 8269| stable | nextcloud | -
pi2-kernel |4.4.0-1092.100 | 56 | stable | canonical | kernel
snapweb | 0.26-11 | 323 | stable | canonical | -
wdl-nextcloud | 16.04-0.5-6 | 9 | stable | canonical | gadget

**Comment by pachulo** [comment]
It looks like your box cannot access the snap store. Besides that, the revisions/versions of your installed snaps are quite old; here are mine:
```
Name          Version               Rev    Tracking  Publisher   Notes
core          16-2.36.3             6132   stable    canonical✓  core
nextcloud     14.0.5snap2           10800  stable    nextcloud✓  -
pi2-kernel    4.4.0-1102.110        81     stable    canonical✓  kernel
pi3           16.04-0.6             27     stable    canonical✓  gadget
```
So maybe your problem has been there for a while.

**Comment by iegtcamnp** [comment]
I tried ` sudo systemctl restart snapd.service` as suggested in some forums but I'm still unable to connect to the store. Is there any other approach to solving this issue?

**Comment by kyrofa** [comment]
@iegtcamnp you should head over to https://forum.snapcraft.io/ and ask, no idea what's happening here.

**Comment by kyrofa** [comment]
I'm going to close this since it doesn't involve an issue in the snap, but feel free to continue discussions.
