### ISSUE TITLE
Unable to Load Image After Download

### ISSUE THREAD

**Issue by iegtcamnp** [nextcloud/nextcloud-snap#858]
I have a Nextcloud Box setup running 13.0.5snap1. Due to an issue #851 I am unable to update my snaps. The encryption module is off. Preview-generator app is installed and running `sudo nextcloud.occ preview:pre-generate`

I downloaded all of my photos ( .JPG files) to have a backup and am getting the following error when trying to open the images: Could not load image "IMG_0041.JPG". Error interpreting JPEG image file (Not a JPEG file: starts with 0x48 0x42). The output of `file IMG_0041.JPG ` was IMG_0041.JPG: data. I don't know why this is happening.

The weird thing is that I am able to see the preview of the image, and I can browse/see all of the images prior to downloading them. So I am hopeful that all is not lost. Please help, I am in desperate need of securing/recovering my photos.

**Comment by kyrofa** [comment]
Hmm, was the encryption module ever on? I'm afraid to say that being able to see thumbnails (which could have been generated months ago) is not indicative of anything other than being able to access thumbnails. This sounds like corrupted data. Did you have any sort of hardware failure?

**Comment by iegtcamnp** [comment]
Yes the encryption module was on at one point, but I needed to turn it off in order to run the Preview Generator app.

**Comment by kyrofa** [comment]
Then I would say that your files are all still encrypted, but disabling the encryption app means you removed the fact that Nextcloud knows they're encrypted, so it just handed you a blob of encrypted data.

**Comment by kyrofa** [comment]
Anyway, I'm going to close this since it doesn't involve the snap, but feel free to continue discussions here.

**Comment by iegtcamnp** [comment]
According to the known issues listed on [https://github.com/rullzer/previewgenerator](url) the app does not work with encryption enabled. So I disabled the app thinking it would decrypt the files. 

Is there a way to decrypt the files on the snap?

**Comment by kyrofa** [comment]
The snap works the same way as everything else in this regard. That's a question for the encryption app people :) .

**Comment by kyrofa** [comment]
I assume when you enabled encryption you saw this warning (taken from [here](https://docs.nextcloud.com/server/13/admin_manual/configuration_files/encryption_configuration.html)):

![screenshot from 2019-01-19 14-13-03](https://user-images.githubusercontent.com/946674/51426498-6a3f1500-1bf4-11e9-9a69-adcc66634684.png)

**Comment by the-sane** [comment]
@iegtcamnp I know this is a very old issue, but a new set of tools for helping deal with all of Nextcloud's encryption bugs has just been created:
https://github.com/syseleven/nextcloud-tools/

It has tools for manually decrypting files and repairing corrupted signatures in the database.
