### ISSUE TITLE
nextcloud.nextcloud-fixer

### ISSUE THREAD

**Issue by FloMiau** [nextcloud/nextcloud-snap#859]
Hey there,

a few days ago my monitoring warned me that a snap service is not running. I'm checking for all Nextcloud Snaps:

```
Info:    CRITICAL - service nextcloud.nextcloud-fixer is not active
Service                    Startup  Current
nextcloud.apache           enabled  active
nextcloud.mdns-publisher   enabled  active
nextcloud.mysql            enabled  active
nextcloud.nextcloud-cron   enabled  active
nextcloud.nextcloud-fixer  enabled  inactive
nextcloud.php-fpm          enabled  active
nextcloud.redis-server     enabled  active
nextcloud.renew-certs      enabled  active
```
The service nextcloud.nextcloud-fixer wasn't there before.
So my question is: what does the nextcloud-fixer do and why is it inactive?

Thank you.

**Comment by kyrofa** [comment]
Heh, what does it do? [Save you pain and annoyance](https://github.com/nextcloud/nextcloud-snap/blob/master/src/nextcloud/bin/nextcloud-fixer#L10) (it was added as part of the upgrade to v14). Once it's done doing that, it exits successfully. That's not really a problem, why does your monitoring system think it is?

**Comment by FloMiau** [comment]
Oh thanks.

It's because I defined inactive as bad.

Is there a way define a "oneshot" service like in systemd?

**Comment by FloMiau** [comment]
I'm using the command ```snap services nextcloud```. 
This command gives me only service name, startup and current like seen above. I don't know any other easy way to check that.

I've looked it up, there is a oneshot way for the daemon. May be it will fix this for me. https://docs.snapcraft.io/snapcraft-app-and-service-metadata/8335

May be can you check that please? 
Can you change the line in https://github.com/nextcloud/nextcloud-snap/blob/master/snap/snapcraft.yaml#L99 ?

**Comment by kyrofa** [comment]
No, that will result in the same output. I suggest using `systemctl`, e.g.:

```
$ systemctl status snap.nextcloud.nextcloud-fixer.service 
● snap.nextcloud.nextcloud-fixer.service - Service for snap application nextcloud.nextcloud-fixer
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.nextcloud-fixer.service; enabled; vendor preset:
   Active: inactive (dead) since Sat 2019-01-12 15:37:01 PST; 6 days ago
 Main PID: 29396 (code=exited, status=0/SUCCESS)

Jan 12 15:36:49 nextcloud systemd[1]: Started Service for snap application nextcloud.nextcloud-fixer.
Jan 12 15:37:00 nextcloud nextcloud.nextcloud-fixer[29396]: Waiting for Apache... done
Jan 12 15:37:01 nextcloud nextcloud.nextcloud-fixer[29396]: Check indices of the share table.
Jan 12 15:37:01 nextcloud nextcloud.nextcloud-fixer[29396]: Done.
```

Take note of the `(code=exited, status=0/SUCCESS)` bit.

**Comment by FloMiau** [comment]
Yeah but inactive (dead) is also defined as critical.

Is there a good tutorial to set up your own snap dev environment for nextcloud?
