### ISSUE TITLE
nc 15 build 15.0.2 deleted files not working properly

### ISSUE THREAD

**Issue by tscsmith** [nextcloud/nextcloud-snap#861]
If I delete files they are deleted right after I hit the delete button. They don't show up in delted files anymore. But if I delte a folder with files in there, they show up in deleted files. They are restoreable too so theres no problem with deleting folders with files inside. 
But if I delete single files there just gone, they dosen't show up in files_trashbin directy on server too. The folder is empty too, so I can except a gui error in browser.

Anyone outside that can reproduce this issue.

**Comment by lug-gh** [comment]
I think this is because end-to-end encryption 👎

**Comment by tscsmith** [comment]
Update

After a long painful investigation of this weird issue I found by myself the cause of this problem.

If you have the End to end encryption app installed and running (Configured in an account) all other users on this server are suffering this deleted files immediately issue. The weird thing is that deleting folders with files inside is functioning like intended. They are not deleted immediately and you can recover them. Only deleting files are deleted immediately nad you can't recover them.

So the work round is to disable end to end encryption app and everything is running like a charm again. 

I hope that somebody can take a look at it and confirm this issue. 

And lug-gh I never tell you the solution again before I throw my 50 cents in. 😁😂

**Comment by kyrofa** [comment]
@tscsmith thank you the bug and the analysis, but there's nothing in the snap we can do to fix this. Can you please log an issue in [upstream Nextcloud](https://github.com/nextcloud/server)?
