### ISSUE TITLE
import data: cannot open database.sql: Permission denied

### ISSUE THREAD

**Issue by chidalgom1503** [nextcloud/nextcloud-snap#868]
Hi guys.

There was a unknow issue uploading files from the desktop app wich ended in internal server error (non specified). After this I made a bkup using the CLI utilities to export database, config and apps folders and so far is ok, but when I try to import back to the new nextcloud installation it always says: 

Importing database...
/snap/nextcloud/11130/bin/import-data: 61: /snap/nextcloud/11130/bin/import-data: cannot open /media/NEXTCLOUD-BKUP/20190129-210250/database.sql: Permission denied
Unable to import database...

trying giving full permissions to this bkup folder and subfolders (tested with root and www-data ownerships) and I runing as root user always, but cant go further. 

Please heeelp!!! :C

whats the problem??? wich permission/owner must set in the folders and files to make this possible???

**Comment by kyrofa** [comment]
Given that the backup is in `/media`, did you connect the `removable-media` plug?

**Comment by chidalgom1503** [comment]
It work!!! but still get the:

**Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.  More details can be found in the server log.**

this is very frustrating!!!... How can a figure out this kind of error??? everything was fine till upload some files :C

**Comment by kyrofa** [comment]
Hmm, interesting. Let's take a look at a few things. First of all, let's see Apache's error log:

    $ sudo cat /var/snap/nextcloud/current/apache/logs/error_log

Then, please also paste the output of [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts).

**Comment by chidalgom1503** [comment]
thank for your help **kyrofa**, but it seems the config.php file was wrong, still don't know which part, but I could make it work by importing only the apps and database using CLI... and the config.php file was edited manually later to set the external datadirectory only (located inside of /media folder).

Now is working fine with all the important data for us (tags, users, folders, permissions, etc).

cheers!

**Comment by kyrofa** [comment]
Ah, well, glad you sorted it out! I'll go ahead and close this, then.
