### ISSUE TITLE
Broken link on wiki page?

### ISSUE THREAD

**Issue by simonthelwall** [nextcloud/nextcloud-snap#87]
Hi, I spotted what I think is a broken link on the wiki page. The link https://github.com/nextcloud/nextcloud-snap/wiki/First-usage-of-the-Box
from https://github.com/nextcloud/nextcloud-snap/wiki simply returns the user to the same page.

**Comment by oparoz** [comment]
Thanks it's now fixed! The page had been renamed and can be found here:
https://github.com/nextcloud/nextcloud-snap/wiki/Getting-started
