### ISSUE TITLE
Not enabling recovey key

### ISSUE THREAD

**Issue by SkyWheel** [nextcloud/nextcloud-snap#873]
Hi,
I'm using Latest stable snap that is 14.06 for now. I'm trying to enable encryption recovery key under default encryption module. I enter the key, press "Enable recovery key", the status "Saving" appears next to "enable recovery key" and... nothing happens. Nothing at all.
![image](https://user-images.githubusercontent.com/10903432/52111830-eb68c400-2658-11e9-9bf9-4eb57edd4d91.png)

**Comment by SkyWheel** [comment]
Ouch.... I think I've found the root of the issue. From the documentation:
```
encryption:enable-master-key
Enable the master key. Only available for fresh installations with no existing encrypted data! There is also no way to disable it again.
```
Is there any workaround on how to enable this recovery key?

**Comment by kyrofa** [comment]
Hey @SkyWheel, I'm afraid this is a question for the [upstream Nextcloud](https://github.com/nextcloud/server) folks, we don't really deal with the encryption app here.
