### ISSUE TITLE
Anyone able to use the new Social Plugin on the newest Nextcloud-Snap?

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#874]
Has anyone tried installing and using the new Nextcloud Social Plugin on the newest Nextcloud-Snap?
https://github.com/nextcloud/social

**Comment by kyrofa** [comment]
Looks like it requires v15. I'm able to install and mess around with it, although its icon seems to be missing for me. Does it not work for you?

**Comment by kyrofa** [comment]
No, it doesn't even show up in the store for v14, you need to install v15 to get it. Hang tight though, I suspect #872 (v15) will be merged in the next day or so.

**Comment by ASmith-** [comment]
Outstanding, thanks for your efforts and consideration kyrofa.

**Comment by kyrofa** [comment]
Alright, refresh and give it a try :) .

**Comment by Geforce8472** [comment]
Hi, I'm trying to use the nextcloud snap package with the new social app but there seems to be a problem with the federation.

I believe this is related to the following issues:
https://github.com/nextcloud/social/issues/376
https://github.com/nextcloud/social/issues/268

The fixes seem to involve editing the webserver config which I can't do with the snap package.

Is anyone else having this problem?
