### ISSUE TITLE
[15.0.2] Missing imagick after update

### ISSUE THREAD

**Issue by edrohler** [nextcloud/nextcloud-snap#882]
I noticed the snap updated to 15.0.2 which is cool. However, I am missing the imagick dependency. I am happy to install it or submit a pull request for the updated snap. Is this a known issue? 

![image](https://user-images.githubusercontent.com/2218823/52248671-8530ab00-28bd-11e9-9cb9-cd141caa8c5d.png)
`snap info nextcloud` output

```shell
name:      nextcloud
summary:   Nextcloud Server - A safe home for all your data
publisher: Nextcloud✓
contact:   https://github.com/nextcloud/nextcloud-snap
license:   unset
description: |
  Where are your photos and documents? With Nextcloud you pick a server of your choice, at home, in
  a data center or at a provider. And that is where your files will be. Nextcloud runs on that
  server, protecting your data and giving you access from your desktop or mobile devices. Through
  Nextcloud you also access, sync and share your existing data on that FTP drive at school, a
  Dropbox or a NAS you have at home.
commands:
  - nextcloud.disable-https
  - nextcloud.enable-https
  - nextcloud.export
  - nextcloud.import
  - nextcloud.manual-install
  - nextcloud.mysql-client
  - nextcloud.mysqldump
  - nextcloud.occ
services:
  nextcloud.apache:          simple, enabled, active
  nextcloud.mdns-publisher:  simple, enabled, active
  nextcloud.mysql:           simple, enabled, active
  nextcloud.nextcloud-cron:  simple, enabled, active
  nextcloud.nextcloud-fixer: simple, enabled, inactive
  nextcloud.php-fpm:         simple, enabled, active
  nextcloud.redis-server:    simple, enabled, active
  nextcloud.renew-certs:     simple, enabled, active
snap-id:      njObIbGQEaVx1H4nyWxchk1i8opy4h54
tracking:     stable
refresh-date: 2 days ago, at 02:24 UTC
channels:
  stable:       15.0.2snap2       2019-02-03 (11341) 177MB -
  candidate:    ↑
  beta:         ↑
  edge:         master-2019-02-03 2019-02-03 (11359) 188MB -
  15/stable:    15.0.2snap2       2019-02-03 (11341) 177MB -
  15/candidate: ↑
  15/beta:      ↑
  15/edge:      15-2019-02-02     2019-02-02 (11332) 187MB -
  14/stable:    14.0.6snap1       2019-01-26 (11140) 175MB -
  14/candidate: ↑
  14/beta:      ↑
  14/edge:      14-2019-02-02     2019-02-02 (11334) 185MB -
  13/stable:    13.0.10snap1      2019-01-19 (10862) 170MB -
  13/candidate: ↑
  13/beta:      ↑
  13/edge:      13-2019-02-02     2019-02-02 (11327) 180MB -
  12/stable:    12.0.13snap1      2019-01-07 (10633) 197MB -
  12/candidate: ↑
  12/beta:      ↑
  12/edge:      ↑
  11/stable:    11.0.8snap1       2018-05-10  (6962) 193MB -
  11/candidate: ↑
  11/beta:      ↑
  11/edge:      ↑
installed:      15.0.2snap2                  (11341) 177MB -
```

**Comment by kyrofa** [comment]
Yes, it has always been this way, but Nextcloud v15 decided to start warning about it (https://github.com/nextcloud/server/issues/13099). We do not ship such an insecure piece of software in the snap (imagick has a dreadful security history). The warning will go away if you disable the theming app. If you need the theming app, then you don't get automatically-generated favicons. I think that's the only feature imagick gives you (but I could be wrong-- I have it disabled).

**Comment by edrohler** [comment]
Cool. I will just disable it. Thanks @kyrofa

**Comment by kyrofa** [comment]
My pleasure :) .

**Comment by Scadro** [comment]
I installed snap Nextcloud Hub 3 (25.0.6) yesterday.
And have tried to disable theming app, as mentioned above.
But I get the message: 'theming can't be disabled' (see also https://github.com/nextcloud/server/issues/34338)
So how to get rid of the 'missing imagick' warning now?

**Comment by kyrofa** [comment]
Oh that's annoying. I guess it's impossible to get rid of the warning, now!

**Comment by aronkvh** [comment]
This is a minor issue with theming, but a pretty big issue if you use [Memories](https://github.com/pulsejet/memories), because several features depend on this (like viewing HEIC images)

**Comment by Pilzinsel64** [comment]
Not sure how exactly it works, but you might try this one:
https://github.com/h2non/imaginary
See here for the implementing or with Infos: https://github.com/nextcloud/server/pull/24166

**Comment by szaimen** [comment]
Hi, I would rather recommend the following documentation:
https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html?highlight=imaginar#previews
