### ISSUE TITLE
Uploading files with same filename in different folders

### ISSUE THREAD

**Issue by Jojesp** [nextcloud/nextcloud-snap#885]
I have the same problem as described here:
https://github.com/nextcloud/server/issues/10527

When I upload files with the same filename but in different folders it asks me if I want to overwrite. Any way I can solve this?

**Comment by Jojesp** [comment]
Sorry, left out useful details. I run 15.0.2 latest stable snap on ubuntu 18.

**Comment by kyrofa** [comment]
I'm sorry @Jojesp, looks like an upstream Nextcloud bug. Focus your efforts over there, and if it's fixed in Nextcloud the snap will get the fix.
