### ISSUE TITLE
Lets-Encrypt Certificate Renewal Fails due to Redirect

### ISSUE THREAD

**Issue by mhspradlin** [nextcloud/nextcloud-snap#896]
Hello,

I'm on the stable channel and my version is 15.0.2snap2. I've configured HTTP to run on port 10080 and HTTPS to run on port 10443 using `sudo snap set nextcloud ...`. I have port forwarding set up and have no problems accessing nextcloud. Initial certificate setup via lets-encrypt succeeds but certificate renewal via lets-encrypt is failing for me with the following message:

```text
Invalid port in redirect target. Only ports 80 and 443 are supported, not 10443
```

After running `nextcloud.disable-https` then running `nextcloud.enable-https` I can get a new certificate. I verified using `curl` that requests over HTTP are redirected to a URL with the 10443 port appended. I think the issue is caused because the [RewriteRule to redirect HTTP traffic to HTTPS is defined](https://github.com/nextcloud/nextcloud-snap/blob/master/src/apache/conf/ssl.conf#L81) appends the [same port it's listening on for HTTPS](https://github.com/nextcloud/nextcloud-snap/blob/master/src/apache/conf/ssl.conf#L10) to the URL. As far as I can tell there's no way to change or omit the port in the RewriteRule without also changing the listening port for HTTPS. When HTTPS is disabled this rewrite rule is not in place, which would explain why disabling and then re-enabling HTTPS is successful.

Would it make sense to disable the RewriteRule for the `.well-known/acme-challenge` path? If not, could the redirect URL be changed to use the value for `overwritehost` or have its own override value?

**Comment by kyrofa** [comment]
Yeah that seems problematic. Add the fact that Let's Encrypt only works with HTTP nowdays anyway, and I agree that it seems to make sense to exclude that path from the redirect.

**Comment by mhspradlin** [comment]
Oops, put this on the PR instead of here:

> Created a PR that I think prevents the Let's Encrypt challenge requests from getting redirected, but I wasn't able to test it. Let me know if I should change the format of the PR or if the change should be altered.
