### ISSUE TITLE
What exactly does cron.php and how to edit it to rescan files automatically?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-snap#904]
Good evening,
I have setup snappy nextcloud and enabled the external storage app to acces all my files stored on one Windows-SMB-Share.
How can I setup a cronjob for rescanning all files or is it enabled by default?

**Comment by kyrofa** [comment]
I'm not sure if the default cron.php does this, but you can always write a cron job that runs `nextcloud.occ files:scan --all`.

**Comment by szaimen** [comment]
Thank you for your answer! 
Do you might have a link with instructions on how to do that in snappy nextcloud? 
That would be awesome!

**Comment by kyrofa** [comment]
The Nextcloud snap isn't going to help you with this, I'm afraid-- at least not today. If you're on classic Ubuntu I suggest doing this in the host's root's cron. For example, if you wanted to scan daily, use:

    @daily /snap/bin/nextcloud.occ files:scan --all

Or are you using Ubuntu Core?

**Comment by szaimen** [comment]
No, I am running Debian Linux. 
I managed to edit the _/etc/crontab_ file. 
So I think that will work.

**Comment by kyrofa** [comment]
Excellent.

**Comment by szaimen** [comment]
Thank you for your help!
