### ISSUE TITLE
 There are no commands defined in the "preview" namespace.

### ISSUE THREAD

**Issue by SpacePotatoBear** [nextcloud/nextcloud-snap#905]
Tried running ```sudo nextcloud.occ preview:generate-all``` but got this error message instead.

"There are no commands defined in the "preview" namespace."

**Comment by kyrofa** [comment]
That's because you need to install the [preview generator app](https://apps.nextcloud.com/apps/previewgenerator).

**Comment by daschmidt1994** [comment]
Same probleme here:
NCP in Docker with ncp version 1.29.8 

In Application.php line 598:
                                                                    
  [Symfony\Component\Console\Exception\NamespaceNotFoundException]  
  There are no commands defined in the "preview" namespace.         
                                                                    

Exception trace:
  at /data/nextcloud/3rdparty/symfony/console/Application.php:598
 Symfony\Component\Console\Application->findNamespace() at /data/nextcloud/3rdparty/symfony/console/Application.php:651
 Symfony\Component\Console\Application->find() at /data/nextcloud/3rdparty/symfony/console/Application.php:236
 Symfony\Component\Console\Application->doRun() at /data/nextcloud/3rdparty/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /data/nextcloud/lib/private/Console/Application.php:215
 OC\Console\Application->run() at /data/nextcloud/console.php:100
 require_once() at /data/nextcloud/occ:11
