### ISSUE TITLE
Setup S3 as Primary Storage

### ISSUE THREAD

**Issue by mccarthyryanc** [nextcloud/nextcloud-snap#921]
Really like the snap install, but I'm having trouble configuring objectstore, specifically S3. I tried modifying the nextcloud configs under `$SNAP_DATA` but from the [docs](https://docs.nextcloud.com/server/15/admin_manual/configuration_files/primary_storage.html) it sounds like this needs to be done before the install. Is this possible when installing via snap? Or are there instructions on how to set this up after the install?

**Comment by kyrofa** [comment]
Reading those same docs, it sounds like you can do this after install, but all the files you had in the data directory before the switch will become inaccessible. What happens if you add this to the config after install?

**Comment by mccarthyryanc** [comment]
@kyrofa I tried again and got it working! I had to try a few times, but here is correct order of operations:
1. snap install
2. Edit config `/var/snap/nextcloud/current/nextcloud/config/config.php` with S3 info:
```php
'objectstore' => array(
        'class' => '\\OC\\Files\\ObjectStore\\S3',
        'arguments' => array(
                'bucket' => 'bucketname',
                'autocreate' => true,
                'key'    => 'key',
                'secret' => 'secret',
                'use_ssl' => true,
                'region' => 'region',
        ),
),
```
3. login via web as admin

After that I see could objects getting written to S3 as I added users and files.

**Comment by joshhopkins** [comment]
@mccarthyryanc did you find this is still working for you without any issues? I'm getting some odd errors https://github.com/nextcloud/nextcloud-snap/issues/1770

**Comment by mccarthyryanc** [comment]
@joshhopkins I actually migrated my nextcloud instance off AWS, so I'm not sure if this workaround is still applicable.

**Comment by joshhopkins** [comment]
Thanks @mccarthyryanc, still using nextcloud-snap + objectstore? I've been using Digital Ocean Spaces (S3 spec).
