### ISSUE TITLE
Question about updating

### ISSUE THREAD

**Issue by Chippel** [nextcloud/nextcloud-snap#926]
So I've installed Nextcloud via Snap. It was super easy and smooth as I'm not familar with programming. Because of that I'd like to know what I have to do in order to update. I mean security updates and such. Do I have to do anything or will Nextcloud updated automatically?

**Comment by kyrofa** [comment]
All you need to do is leave it connected to the internet. The snap will update automatically. Security updates of the web server, PHP, and even Nextcloud updates will all happen automatically.

**Comment by Chippel** [comment]
Wow that sounds really nice and intuitive. What about backups?

**Comment by kyrofa** [comment]
Every time the snap updates it creates a snapshot of the config and the database, which gives you the ability to rollback if an update somehow goes awry. Three copies of this data will be kept by default, the current one and two previous. Notably, this does NOT include your raw data. No one can afford to have three copies of that sitting around, it can be far too large (mine is several TBs). We definitely recommend regular backups if you can afford to store them somewhere, or at least use RAID. The snap supports exporting and importing backups, see `nextcloud.import -h` and `nextcloud.export -h` for more details.

**Comment by kyrofa** [comment]
I'll go ahead and close since I think the question was answered, but feel free to continue conversation here.
