### ISSUE TITLE
Changed data directory breaks nextcloud.export

### ISSUE THREAD

**Issue by davidmichaelhuber** [nextcloud/nextcloud-snap#929]
Hi there!

I successfully installed nextcloud via the snap and now want to export database, config and data. When I use the ```nextcloud.export``` CLI utility I get the following error. I am pretty sure this is caused because I changed the data directory to use a partition on an external hard drive. In order to achieve that I followed the steps described [here](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition#if-you-just-installed-the-snap-and-havent-created-an-admin-user-yet). It looks like the ```nextcloud.export``` CLI utility uses the default path for nextcloud data that I changed manually in the ```config.php```.

Is there any way I can make the export work for my setup or do I have to backup manually?

```
WARNING: This functionality is still experimental and under
development, use at your own risk. Note that the CLI interface is
unstable, so beware if using from within scripts.

Enabling maintenance mode... done
Exporting apps...
              0 100%    0.00kB/s    0:00:00 (xfr#0, to-chk=0/1)
Exporting database...
Exporting config...
Exporting data...
rsync: change_dir "/var/snap/nextcloud/common/nextcloud/data" failed: No such file or directory (2)
              0 100%    0.00kB/s    0:00:00 (xfr#0, to-chk=0/0)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
Unable to export data
Disabling maintenance mode... done
```

**Comment by kyrofa** [comment]
Just run the export without trying to export the data (see `nextcloud.export -h` for more info), and backup the data yourself. I'm not sure there's a particularly reasonable way the snap can deal with this. If it automatically discovered that you moved the data, what should an import do? Put it back in the same place? That's what the config says, but it may not be accessible under the new snap's confinement, etc. If you just use the export/import tool to handle everything except the raw data, it's pretty easy to do that on your own.

**Comment by Micromegass** [comment]
Is there no better way of doing this? Splitting up the backup in a part that nextcloud/snap does and in a data part seems not a good solution. Is there no way of telling snap/nextcloud to change the backup path (or the export/import path for that matter)....

**Comment by Vsevolod-1C** [comment]
Good evening!

Found solution:
"Nextcloud" settings do not change
We mount the external device in / mnt ***
in place of the 'datadirectory' and /vsr/snap/****/backup directories, create a simlink to the directories of the external device
month - normal flight :)
Linux experience - "regular user" :)
Is this approach likely to cause problems?

sorry for my English
