### ISSUE TITLE
Documentation: How to find out UID and GID used by Nexcloud snap?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-snap#930]
For mounting a SMB-Share I need to know the UID and GID of my nextcloud snap installation. How can I find out?

I am using the command:
_//lindner-cloud/Lindner-Cloud /media/samba cifs vers=3.0,username=arg,password=secret,iocharset=utf8,uid=1000,gid=1000,file_mode=0777,dir_mode=0777 0 0_
to mount a windows SMB-Share over /etc/fstab. 

My linux account with uid=1000 and gid=1000 can delete files mounted on /media/samba. 
The nextcloud snap strangely cannot, even thoug it can acces the files. (I enabled removable media support). 
Also gid=0 and gid=65534 don't work.

My hope is to change uid and gid to the ID's used by my nextcloud snap installation so that the installation is also able to delete files on that SMB-Share.

**Comment by skewty** [comment]
I took a look at the files created by my server and they are currently all owned by root.
Perhaps a config option to use and set a different user:group (if one doesn't already exist).

A `nextcloud` group would be nice.  Then you could just add your user to the group.

I am faced with the same issues.  I use an Ubuntu workstation to access the server using sftp:// through nautilus and run into all sorts of permissions issues all the time.  I don't want to enable root access via ssh.

**Comment by kyrofa** [comment]
> Perhaps a config option to use and set a different user:group (if one doesn't already exist).

I'm afraid this isn't possible in snaps today. Services always run as (confined) root. So to answer the issue: user and group will be root.

>  I use an Ubuntu workstation to access the server using sftp:// through nautilus and run into all sorts of permissions issues all the time.

You should mount it via davs, or just use Ubuntu's gnome shell integration for it, and you won't have those issues.

I'm going to close this issue as I believe the question has been answered, but feel free to continue discussion here.
