### ISSUE TITLE
solve mysql warning 

### ISSUE THREAD

**Issue by nirajvara** [nextcloud/nextcloud-snap#936]
Hi 

I have the latest nextcloud snap version is  15.0.5snap1 and ubuntu 18.04 server in syslog I have found some warnings and I want to clear these warnings, Please guide for the same.

[Warning] Changed limits: max_open_files: 1024 (requested 5000)
 [Warning] Changed limits: table_open_cache: 431 (requested 2000)
 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).

**Comment by kyrofa** [comment]
These warnings are expected, don't worry about them.
