### ISSUE TITLE
Cannot update ssl

### ISSUE THREAD

**Issue by sparkerb** [nextcloud/nextcloud-snap#938]
Hello

I am trying to renew my cert and am getting the following error:
I RUN 
sudo nextcloud.enable-https lets-encrypt

Attempting to obtain certificates... error running certbot:

Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Plugins selected: Authenticator nextcloud:webroot, Installer None
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for MYDOMAIN

Using the webroot path /var/snap/nextcloud/current/certs/certbot for all domains.
 (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://MYDOMAIN/.well-known/acme-challenge/26R9-VOyo8XwDxHocg0OYKdUVSdPqnHy39eiZu6IUOc

 "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML
   2.0//EN\">
<html><head>
<title>400 Bad
   Request</title>
</head><body>
<h1>Bad Request</h1"

when i curl -X GET -I http://MYDOMAIN
is shows that it redirects to https

Any ideas?

**Comment by kyrofa** [comment]
Is it possible that your IP address changed and your domain name is no longer pointing at your Nextcloud install?

**Comment by sparkerb** [comment]
Hi. Nothing has changed the ip is the same.



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by sparkerb** [comment]
Its pointing to a dedicated ip address and is currently working.



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by sparkerb** [comment]
Any ideas? I trying to renew to avoid downtime.

**Comment by kyrofa** [comment]
Any chance you have a proxy or some other server in front of Nextcloud?

**Comment by mkrueger2002** [comment]
Had the same problem yesterday. My nextcloud instance worked fine for about a year, but yesterday I had the same error in renewing LetsEncrypt-certificates. I turned off the https-only-function, then I was able to renew the certificate, afterwards I turned on https-only. 
Silly workaround, but my server is online again ...
Maybe it works for you, too !

**Comment by sparkerb** [comment]
Actually makes sense as letsencrypt requires both port 80 and 443 to work



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by sparkerb** [comment]
Hi, just getting round to sorting this. How did you turn off https-only-function?. I am using haproxy. i've tried bypassing and sending traffic direct. still no joy.

**Comment by mkrueger2002** [comment]
I'm using nextcloud-pi on a raspberry. There is a function in the menue to activate/deactivate https-only. I don't exactly know how it works, I think there is a script behind. Try to find out when I'm back at home !

**Comment by mkrueger2002** [comment]
Hi, sparkerb,
on the nextcloud-pi there is a configuration script in /usr/local/bin/ncp/CONFIG/nc-httpsonly.sh
This is called via ncp-config. I attach a text file with the script in it -- it just configures apache. Don't know how this affects Lets encrypt ...
[httpsonly-skript.txt](https://github.com/nextcloud/nextcloud-snap/files/3035230/httpsonly-skript.txt)

**Comment by sparkerb** [comment]
Hi , thanks for that but I'm using snap and next cloud . I think the issue is the redirect to https. Does anyone one know how I can get around it?

**Comment by sparkerb** [comment]
my cert has just run out!!!!!!!!!!!!!!!!

**Comment by sparkerb** [comment]
> Any chance you have a proxy or some other server in front of Nextcloud?

Yes i have haproxy but have tried bypassing it and get the same error

**Comment by sparkerb** [comment]
snap!

**Comment by kyrofa** [comment]
> I think the issue is the redirect to https.

What makes you say that? When HTTPS is enabled HTTP is typically redirected to HTTPS, this isn't a problem for renewing a cert. Have you tried simply running `sudo nextcloud.enable-https lets-encrypt` again? Does the same thing happen?

**Comment by kyrofa** [comment]
By the way, what version of the snap are you using (`snap list nextcloud`)?

**Comment by sparkerb** [comment]
hi, Yes it does. I think the issue might be the .well-known folder might be missing. i get the following log..(http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from

**Comment by sparkerb** [comment]
where should the /.well-known/acme-challenge/ folder be located within snap?

**Comment by sparkerb** [comment]
Name       Version      Rev   Tracking  Publisher   Notes
nextcloud  13.0.6snap1  8971  stable    nextcloud✓  devmode

**Comment by kyrofa** [comment]
Oh wow, that's ancient actually. Can you run `snap info nextcloud`, please?

**Comment by sparkerb** [comment]
ame:      nextcloud
summary:   Nextcloud Server - A safe home for all your data
publisher: Nextcloud✓
contact:   https://github.com/nextcloud/nextcloud-snap
license:   unset
description: |
  Access, share and protect your files, calendars, contacts, communication and more at home and in
  your enterprise.
commands:
  - nextcloud.disable-https
  - nextcloud.enable-https
  - nextcloud.manual-install
  - nextcloud.mysql-client
  - nextcloud.mysqldump
  - nextcloud.occ
services:
  nextcloud.apache:         simple, enabled, active
  nextcloud.mdns-publisher: simple, enabled, active
  nextcloud.mysql:          simple, enabled, active
  nextcloud.nextcloud-cron: simple, enabled, active
  nextcloud.php-fpm:        simple, enabled, active
  nextcloud.redis-server:   simple, enabled, active
  nextcloud.renew-certs:    simple, enabled, active
snap-id:      njObIbGQEaVx1H4nyWxchk1i8opy4h54
tracking:     stable
refresh-date: 2018-10-04
channels:
  stable:       15.0.5snap2               2019-03-24 (12387) 205MB -
  candidate:    15.0.5snap2               2019-03-24 (12387) 205MB -
  beta:         15.0.5snap2               2019-03-24 (12386) 205MB -
  edge:         master-2019-04-02         2019-04-02 (12572) 210MB -
  15/stable:    15.0.5snap2               2019-03-24 (12387) 205MB -
  15/candidate: ↑                                                  
  15/beta:      ↑                                                  
  15/edge:      15-2019-03-31             2019-03-31 (12543) 204MB -
  14/stable:    14.0.7snap1               2019-02-22 (11748) 194MB -
  14/candidate: ↑                                                  
  14/beta:      14.0.7snap1+git4.c4636f0  2019-03-16 (12202) 202MB -
  14/edge:      14-2019-03-31             2019-03-31 (12532) 203MB -
  13/stable:    13.0.11snap1              2019-02-22 (11752) 188MB -
  13/candidate: ↑                                                  
  13/beta:      13.0.11snap1+git4.92e1309 2019-03-16 (12199) 193MB -
  13/edge:      13-2019-03-31             2019-03-31 (12533) 194MB -
  12/stable:    12.0.13snap1              2019-01-07 (10632) 206MB -
  12/candidate: ↑                                                  
  12/beta:      ↑                                                  
  12/edge:      ↑                                                  
  11/stable:    11.0.8snap1               2018-05-10  (6942) 202MB -
  11/candidate: ↑                                                  
  11/beta:      ↑                                                  
  11/edge:      ↑                                                  
installed:      13.0.6snap1                           (8971) 206MB devmode

**Comment by kyrofa** [comment]
You're tracking stable, but are significantly out of date. Something is wrong. Can I see `snap changes`, please?

**Comment by sparkerb** [comment]
hi, snap changes didn't work

**Comment by sparkerb** [comment]
sorry it said no changes found

**Comment by sparkerb** [comment]
in-fact it said error no changes found

**Comment by kyrofa** [comment]
Huh. Okay, try this:

```
$ sudo snap refresh nextcloud --channel=13
```

**Comment by sparkerb** [comment]
cool, its doing something..brb

**Comment by sparkerb** [comment]
done. nextcloud (13/stable) 13.0.11snap1 from Nextcloud✓ refreshed

**Comment by kyrofa** [comment]
What the heck. It should be doing this all automatically. Okay, let's continue getting you more up-to-date. Have you verified that you can log into it, update looks okay?

**Comment by kyrofa** [comment]
Can I also see the output of `snap version`, please?

**Comment by sparkerb** [comment]
1 min . i can't from the the host name as the cert has run out

**Comment by kyrofa** [comment]
You should be able to tell your browser to ignore that temporarily, no?

**Comment by sparkerb** [comment]
not these days!  i can get the trust this domain up internally via the internal IP address. clicked trust, then the page timed out. This site can’t be reached x.x.x.x took too long to respond

**Comment by sparkerb** [comment]
reboot?

**Comment by sparkerb** [comment]
its rebooting

**Comment by sparkerb** [comment]
still no joy

**Comment by sparkerb** [comment]
should i disable https ?

**Comment by kyrofa** [comment]
You can, at least temporarily, but your browser will still be unhappy given HSTS. You might need to use a private browsing mode to get around that. Just verify that things look healthy and then we can upgrade you to v14, then v15, then try Let's Encrypt again.

**Comment by kyrofa** [comment]
(I'd still like to see the output from `snap version`, when possible)

**Comment by sparkerb** [comment]
ok its up .

**Comment by sparkerb** [comment]
snap    2.38
snapd   2.38
series  16
ubuntu  18.04
kernel  4.15.0-46-generic

**Comment by kyrofa** [comment]
Real quick: you're not using a brand store, are you? You just `snap install`ed nextcloud on a server?

Let's continue getting you up to date by upgrading to v14:

```
$ sudo snap refresh nextcloud --channel=14
```

After that completes, visit it, make sure everything looks sane. Once you're happy with it, move to v15, which is the current stable:

```
$ sudo snap refresh --stable nextcloud
```

Again, make sure that all looks sane. You should be on 15.0.5snap2 at that point. Assuming everything goes well, try enabling HTTPS again:

```
$ sudo nextcloud.enable-https lets-encrypt
```

**Comment by sparkerb** [comment]
yes

**Comment by sparkerb** [comment]
currently i cannot log in . i get the page up , put my details in and the page just sits there! doesn't even send the request

**Comment by sparkerb** [comment]
the backdrop on the login page is back to default. but cannot log in on http:

**Comment by sparkerb** [comment]
I've kicked off the sudo snap refresh nextcloud --channel=14

**Comment by sparkerb** [comment]
getting an error message on the login page. Internal Server error

**Comment by sparkerb** [comment]
hi, hope yo can still help. 
getting the following systemctl status nextcloud.service
● nextcloud.service
   Loaded: loaded (/etc/init.d/nextcloud; generated)
   Active: failed (Result: exit-code) since Wed 2019-04-03 16:49:56 UTC; 33s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5867 ExecStart=/etc/init.d/nextcloud start (code=exited, status=203/EXEC)

**Comment by kyrofa** [comment]
Alright, please paste in the output from [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts).
