### ISSUE TITLE
Upgrade MySQL to 5.7.15

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#94]
For this snap, it requires a change to the custom branch being used.

**Comment by kyrofa** [comment]
Again, why? As you noticed, this takes some work to do. Are there new features we need? Vulnerabilities that have been fixed?

**Comment by oparoz** [comment]
The long list of bugs fixed is enough for me, but it's your choice. We don't have a team who can backport fixes to a fixed version like it usually happens on some distros, especially LTS and it's impossible to know if it works without trying. So since I compile everything from source, I stage and test, but you may have a different approach.

Regarding the update process, isn't a rebase sufficient? I had a look and it looks like not much is happening in this file, in this branch.

**Comment by pachulo** [comment]
Hi! I think that we should really have an updated version of mysql as:
* The current one is from more than a year ago (2016-02-05).
* All the security patches that could potentially affect it: http://changelogs.ubuntu.com/changelogs/pool/main/m/mysql-5.7/mysql-5.7_5.7.18-0ubuntu0.16.04.1/changelog

**Comment by pachulo** [comment]
I guess that you already know about this, but anyway:

- http://elopio.net/blog/call-for-testing-mysql/
- https://github.com/mysql/mysql-snap

**Comment by kyrofa** [comment]
Yeah, the nextcloud snap existed long before the MySQL snap, and they have the advantage of getting the process control interface automatically connected, so they don't need the patch we need. However, the work to migrate databases is non-trivial.

**Comment by pachulo** [comment]
Just for the sake of trying I patched the latest version of mysql-server (5.7.18) with @kyrofa modifications in here:
* https://github.com/pachulo/mysql-server/tree/feature/support_no_setpriority

And tried to compile this version of the snap with success:
* https://github.com/pachulo/nextcloud-snap/tree/update-mysql-5.7.18

Made a fresh install, and it seems that the application works OK.

Do you have any tests in mind that I should try with the updated version to see if everything is in it's place?

**Comment by pachulo** [comment]
@kyrofa any news on this?

**Comment by kyrofa** [comment]
@pachulo I'm very sorry, I missed your update! Thanks for taking it for a test run, we should go ahead and do this. I'm spinning up test builds now.
