### ISSUE TITLE
External storage （Local） will not refresh

### ISSUE THREAD

**Issue by wallfacertony** [nextcloud/nextcloud-snap#945]
Hi,I was set up an aria2 on my server.
The files has download to ~/data successful.
I want to use them in nextcloud,so I use External storage support.
And I add ~/data to nextcloud as local.
This operation has succeed
However,I can't find my files in nestcloud.
Is that because ""smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login" is not possible."?

**Comment by johanneskoester** [comment]
I have the same problem. External storage is there, it contains files, but they are not shown in nextcloud. In my case, the folder is bind-mounted.

**Comment by wathashi** [comment]
I have the same problem. but 
I can't find help anywhere =/

**Comment by kyrofa** [comment]
Make sure your files are places somewhere the snap can access them. ~/data isn't accessible under confinement. If you connect the `removable-media` interface you can use anywhere in `/media/` or `/mnt/`, but that's it.

**Comment by wathashi** [comment]
I'm using an internal disk and mounted it on /mnt/storage.
it appears on nexcloud, but I can't record anything on it

**Comment by kyrofa** [comment]
Check the permissions, root should be able to write to it (e.g. try `sudo chmod -R root:root `/mnt/storage`)

**Comment by wathashi** [comment]
thank you very much for your help, I gave permission and now I can use it normally.

I just have a question, can you tell me where I determine how much each user will use the external storage?

**Comment by kyrofa** [comment]
I'm afraid I don't know, I'm sorry-- that's a question for someone more familiar with the external storage app. I suggest [asking over here](https://help.nextcloud.com/). I think this question has been answered, so I'm going to go ahead and close, but feel free to continue discussion here.
