### ISSUE TITLE
sudo nextcloud.enable-https self-signed triggers SSL_ERROR_RX_RECORD_TOO_LONG in Firefox

### ISSUE THREAD

**Issue by dougabugg** [nextcloud/nextcloud-snap#946]
I followed the instructions in the [wiki](https://github.com/nextcloud/nextcloud-snap/wiki/Enabling-HTTPS-(SSL,-TLS)) and called `sudo nextcloud.enable-https self-signed`, apache restarted and then I got an SSL_ERROR_RX_RECORD_TOO_LONG in Firefox whenever I visit my nextcloud server address. The wiki doesn't provide any other info on this error or how to go about fixing it.

**Comment by kyrofa** [comment]
Try clearing your cache, and refresh with Ctrl + Shift + R. What version of Firefox are you using? Are you using a proxy?

**Comment by dougabugg** [comment]
I cleared Firefox's cache. I'm getting SSL errors in Firefox (66.0.1), Chrome (73.0.3683.86), and Firefox on Android (65.0.1). My current setup is as a VirtualBox machine running on a Windows 10 desktop. The Vbox machine is running Ubuntu Server 18.04.2, and I checked the nextcloud option when installing.

**Comment by dougabugg** [comment]
There was an issue with Ports and NAT mappings. I was mistakenly connecting to a port of an HTTP server, but using HTTPS to connect by mistake, which caused the error I was seeing. After fixing that, everything worked as expected.

**Comment by kyrofa** [comment]
That sounds about right, thanks @dougabugg.
