### ISSUE TITLE
Upgrade Redis to 3.2.6

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud-snap#95]

**Comment by kyrofa** [comment]
Why? New features we need? Security vulnerabilities that have been fixed? We have absolute control over our dependencies, but that doesn't mean we need to chase them constantly unless there's a reason.

**Comment by oparoz** [comment]
There is a big security problem, but we're not affected since it requires attacking the configuration. Same answer as with MySQL. I want the bug fixes. It's not a major version change.
