### ISSUE TITLE
increasing PHP ram?

### ISSUE THREAD

**Issue by stone212** [nextcloud/nextcloud-snap#959]
I see this warning:

```
There are some warnings regarding your setup.

    The PHP memory limit is below the recommended value of 512MB.
```

What is the correct way to manage this setting for the snap?

**Comment by pachulo** [comment]
It's in the README: https://github.com/nextcloud/nextcloud-snap#php-memory-limit-configuration
Should be enough with:
`$ sudo snap set nextcloud php.memory-limit=512M`
