### ISSUE TITLE
nextcloud.occ not found

### ISSUE THREAD

**Issue by ikmaak** [nextcloud/nextcloud-snap#96]
In the page
https://github.com/nextcloud/nextcloud-snap/wiki/Connecting-the-Nextcloud-Box-to-the-Internet

there is a command

sudo nextcloud.occ config:system:set trusted_domains 2 --value=your.domain

if you try it, the error is: "sudo: nextcloud.occ: command not found"

if i try to find the file, i can see it as the "ubuntu" user, but am not allowed to use it due to permissions.

I have no idea how to find that file, as the image has no tools included

**Comment by kyrofa** [comment]
Make sure your `sudo` package is completely up-to-date. This was fixed relatively recently by adding /snap/bin to its safe path.

A quick workaround is to use the complete path instead: `sudo /snap/bin/nextcloud.occ`.

**Comment by ikmaak** [comment]
I did apt upgrade (am i supposed to do that with a snap?), it did include a sudo update, and slightly changed the error:

**execv** failed: No such file or directory

for both the normal as the /snap/bin/ variant.

**Comment by oparoz** [comment]
ikmaak, are you using a Nextcloud Box? If not did you just update to 16.10. There have already been reports that snaps are broken on 16.10.

**Comment by ikmaak** [comment]
this is on a box

**Comment by ikmaak** [comment]
after the update nextcloud web server is not reachable anymore

**Comment by oparoz** [comment]
Could you run this and paste what you get? 

`$ dpkg -l | grep snap`

The image has had an issue for the past weeks which had prevented the installation and update of snaps. They would all crash.
But that has now been fixed, so I need to make sure you got the latest packages.

**Comment by oparoz** [comment]
This is what it looks like here:

```
ii  snap-confine                     1.0.43-0ubuntu1~16.04.1                  armhf        Support executable to apply confinement for snappy apps
ii  snapd                            2.15.2ubuntu1                            armhf        Tool to interact with Ubuntu Core Snappy.
ii  ubuntu-core-launcher             1.0.43-0ubuntu1~16.04.1                  armhf        Launcher for ubuntu-core (snappy) apps
```

**Comment by ikmaak** [comment]
ii  snap-confine                 1.0.43-0ubuntu1~16.04.1                  armhf 
ii  snapd                            2.15.2ubuntu1                                   armhf
ii  ubuntu-core-launcher    1.0.43-0ubuntu1~16.04.1                  armhf  

i just updated all the snaps as well, core went from rev 120 to 424

**Comment by ikmaak** [comment]
ok, it seems that upgrading the core snap did it, the local ip does work again, and on the cli i got:

The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
System config value trusted_domains => 2 set to string mydomain.com

**Comment by oparoz** [comment]
Ah, I'm glad. The last step is indeed to update ubuntu-core, but it's not possible on some networks and some people are stuck with half-working solutions.

You can ignore the information message given, you Nextcloud config has been updated.

**Comment by kyrofa** [comment]
@ikmaak good call on updating the snaps as well (note that they would have eventually updated on their own). Sorry for the difficulties!

**Comment by ikmaak** [comment]
the box is still not reachable under the external domain name, i can still only connect to it via local ip, or ping the external domain.

**Comment by kyrofa** [comment]
Are you sure you have any necessary port forwarding correctly setup?

**Comment by ikmaak** [comment]
all my other port forwarding works well.

**Comment by oparoz** [comment]
@ikmaak - May I suggest you install another snap and see if it's reachable using your domain? That way we would be sure it's an issue with Nextcloud itself.

**Comment by kyrofa** [comment]
If the domain name isn't reaching the device, it must be a problem either with the domain name not pointing to your router (note that it can take a while for DNS changes to propagate), or the router not forwarding the right ports to the right device. I'm afraid that snap can't help with either of these problems.

**Comment by ikmaak** [comment]
I think i would need to setup letsencrypt, i only forwarded 443, but as long as letsencrypt does not work, that is a problem. for getting letsencrypt working i seem to need forwarded port 80 too.

**Comment by kyrofa** [comment]
Yes indeed-- if the snap isn't setup for HTTPS it's only listening on port 80. Note that you should always forward port 80 as well, and the snap will redirect it to 443 if HTTPS is enabled. It makes for the best user experience, otherwise people visiting `yourdomain.com` (which is by definition http) will get a "no such site" type error.

**Comment by ikmaak** [comment]
i did, now i can reach the site over port 80, now the letsencrypt setup works, but i would still not like to use 80 for the box, there's other things on there normally. is that even possible?

**Comment by oparoz** [comment]
@kyrofa Yes, but I think there is another problem. To be able to generate the cert, Let's Encrypt needs tp ping the server and at that stage, it's only available on port 80.

**Comment by oparoz** [comment]
@ikmaak - You should be able to disable port 80 now and your Box should be reachable using HTTPS

**Comment by ikmaak** [comment]
i am not getting redirected automatically to https?

**Comment by kyrofa** [comment]
@oparoz not sure what problem you're referring to. That's how it works.

@ikmaak indeed, you can disable port 80 if you want, but like I said, the user experience won't be perfect. Your users will have to make sure they type `https://` in front of the domain. If you  can live with that, go for it!

**Comment by oparoz** [comment]
>@oparoz not sure what problem you're referring to. That's how it works.

The problem is that port 80 is not open in the firewall and thus the Box is not reachable from the Internet for validation.

**Comment by ikmaak** [comment]
but now i have done the initial install, will it be able to renew over 443 alone?

**Comment by ikmaak** [comment]
if it does, that has to be changed in the wiki, otherwise only the update instructions need to be added.

**Comment by oparoz** [comment]
Wiki has been updated

**Comment by ikmaak** [comment]
could you also (temporarily) add the update info too?

could there also be a clarification about port 80 after initial certbot run? i know at least two users who will run into this in the coming days.

**Comment by ikmaak** [comment]
also, the snapstore is only locally reachable on 4200 or you need to add that port forwarding to the router too, which i think is not advisable.

**Comment by kyrofa** [comment]
> also, the snapstore is only locally reachable on 4200 or you need to add that port forwarding to the router too, which i think is not advisable.

Yeah, don't do that-- it's not authenticated (it should be eventually). Anyone would be able to install snaps on your box :stuck_out_tongue: .

**Comment by ikmaak** [comment]
i meant that that is the logical route to go if you read:

https://github.com/nextcloud/nextcloud-snap/wiki/How-to-manage-your-snaps

This doesn't work if you've enabled SSL for your Nextcloud. If you did follow the instructions below
Connect to the store at http:<your box's IP or hostname>:4200
Note: That's the URL you access the box with and port 4200

**Comment by oparoz** [comment]
>could you also (temporarily) add the update info too?

It's on the front page of the wiki and on the forums

> could there also be a clarification about port 80 after initial certbot run? i

You can just leave it as it is. Once the next snap version is pushed, It won't create any issue since users are redirected

> there is also a recommended "spreed-webrtc" that seems to be unavailable, with a "spreedme" mentioned on your twitter but that is not yet available?

Unfortunately, at the moment, you need to create your own snap to be able to use spreed.ME

>also, the snapstore is only locally reachable on 4200 after https is installed, or you need to add that port forwarding to the router too, which i think is not advisable.

Correct, you need to wait for this PR to be merged:
https://github.com/nextcloud/nextcloud-snap/pull/83

**Comment by ikmaak** [comment]
> You can just leave it as it is. Once the next snap version is pushed, It won't create any issue since users are redirected

Does this mean that i can stop the port 80 forward to the box (i use the port 80 for public info), or that i should wait till the next snap is pushed?

> Unfortunately, at the moment, you need to create your own snap to be able to use spreed.ME
Every user needs to to that? Is there info for that? Latest news from spreed is from nov 2015. IS it maintained?

> Correct, you need to wait for this PR to be merged
How is the release schedule for that? Is this something that is weekly, monthly? snaps (if this is related) are still unclear to me.

**Comment by oparoz** [comment]
>Does this mean that i can stop the port 80 forward to the box (i use the port 80 for public info), or that i should wait till the next snap is pushed?

Actually, if I'm not mistaken you shouldn't be affected. I had the problem with self-signed certificates. @kyrofa will confirm, but as he's mentioned, keeping port 80 open is better if you intend on having a few users on the box as some will forget to type the s in https.

>Every user needs to to that? Is there info for that? Latest news from spreed is from nov 2015. IS it maintained?

Yes, but the problem is not with the snap. The spreed.ME snap works fine and will be updated. But you need a different Nextcloud Snap if you want to use that feature.
There may be another option, but it requires installing a 3rd snap and I don't know how stable it is and if it will be maintained.

>How is the release schedule for that? Is this something that is weekly, monthly? snaps (if this is related) are still unclear to me.

I'd say it's best effort, but some features have an ETA, per example when we need to release a new OS image. @kyrofa can provide more details.
