### ISSUE TITLE
Login via Windows App end in login-loop

### ISSUE THREAD

**Issue by Blackraz0r** [nextcloud/nextcloud-snap#960]
Hello,

i have a Apache reverse proxy (cert via apache certbot from letsencrypt) and behind is a ubuntu-vm with nextcloud snap.

when i try to login via the windows app i enter my credentials and click "grant access"
it asks to login again. loops infinite.

i've read that one have to add the folowing line to 

/snap/nextcloud/current/htdocs/config/config.php

```
'overwrite.cli.url' => 'https://subdomain.domain.tld',
'overwriteprotocol' => 'https',
'overwritehost' => 'subdomain.domain.tld',
'trusted_proxies' => array('ip.of.reverse.proxy'),

```

when i try to save, nano tells me that the filesystem is non-writable.

so i cant get my login to work.

any suggestions how to solve it ?

**Comment by kyrofa** [comment]
The writable config is in `/var/snap/nextcloud/current/nextcloud/config/config.php`.

**Comment by Blackraz0r** [comment]
this file is empty. 
Should i copy the contents of the non-writable in there and etit it then?

**Comment by kyrofa** [comment]
It should most certainly _not_ be empty. Have you created an admin account, etc.? Or did you just now install it?

**Comment by Blackraz0r** [comment]
got dammit.

well of course you're right.

had a typo. what esle...

oh and finaly i could fix that login issue.

missing part in the config was:

```
'overwriteprotocol' => 'https',
'trusted_proxies' => array('ip.of.reverse.proxy'),

```

**Comment by kyrofa** [comment]
Ah wonderful, thanks for confirming. I'll go ahead and close this, then, but feel free to continue discussion here.
