### ISSUE TITLE
Typo `everythin` in Wiki page

### ISSUE THREAD

**Issue by zhang-ray** [nextcloud/nextcloud-snap#963]
`Import everythin` should be `Import everything` in [this page](https://github.com/nextcloud/nextcloud-snap/wiki/How-to-backup-your-instance)

**Comment by strugee** [comment]
@zhang-ray I would encourage you to go in and [edit the page](https://github.com/nextcloud/nextcloud-snap/wiki/How-to-backup-your-instance/_edit) yourself!

**Comment by kyrofa** [comment]
Fixed, thank you!

**Comment by zhang-ray** [comment]
> 
> 
> @zhang-ray I would encourage you to go in and [edit the page](https://github.com/nextcloud/nextcloud-snap/wiki/How-to-backup-your-instance/_edit) yourself!

Thank you for your information 🙂  I don't know that link last time 😔

**Comment by strugee** [comment]
There's an edit button on each wiki page :-)
