### ISSUE TITLE
[Bug] nextcloud.export - empty database dump file when using SQLite

### ISSUE THREAD

**Issue by itadakimas** [nextcloud/nextcloud-snap#966]
Hi,

I've noticed that the generated database.sql file is empty after doing a full export. I don't remember selecting SQLite during install, so maybe other people (will) have the same issue.

Regards.

**Comment by kyrofa** [comment]
That's not an sqlite database, but a database dump from `mysqldump`. Is it consistently empty for you? Do you see any errors when running the backup?

**Comment by itadakimas** [comment]
Hi @kyrofa,

Yes, it is consistently empty (no database, tables, nor values). Is SQLite database export not supported yet ?

**Comment by kyrofa** [comment]
Wait, I'm confused-- did you update the config to specifically use an sqlite database?

**Comment by itadakimas** [comment]
I don't remember doing anything specific about that. However, it seems that SQLite in the default database, according to the documentation : https://docs.nextcloud.com/server/16/admin_manual/installation/installation_wizard.html#database-choice.

**Comment by kyrofa** [comment]
In the snap, it's mysql. Can you paste in the output of `sudo nextcloud.occ config:list`, please?

**Comment by itadakimas** [comment]
I've already reinstalled nextcloud without using the snap package. Therefore I can't get the output you need, sorry.

I'll try to reproduce the issue next time. In the meantime time, I'm closing this issue.

Cheers!
