### ISSUE TITLE
Enable editing of permissable mimetypes in some place writable by the hosting user.

### ISSUE THREAD

**Issue by goiken** [nextcloud/nextcloud-snap#969]
I’d like to get the [ownpad](https://github.com/otetard/ownpad)-plugin to run in my nc-snap. As per  [their documentation](https://github.com/otetard/ownpad#mimetype-detection), after installation one is supposed to declare these mimetypes to nextcloud:
```
"pad": ["application/x-ownpad"],
"calc": ["application/x-ownpad"],
```
This is recommended to be done by placing a modified copy of `/snap/nextcloud/current/htdocs/resources/config/mimetypemapping.json` into `/snap/nextcloud/current/htdocs/config`. It seems to me that within the snap setup those two folders are mounted in read only file-systems which don’t allow the user to do that.

I see how disallowing the permitted mimetypes to be tampered with has security implications, but here it seems necessary to allow it, or to find some solution that does.

**Comment by kyrofa** [comment]
You did indeed find the read-only config, but that's only used to seed the real-deal config, which is located in `/var/snap/nextcloud/current/nextcloud/config/config.php`. Try placing the json file in that directory and see what happens. I'm not sure how ownpad finds it, but it may need to support the `$NEXTCLOUD_CONFIG_DIR` environment variable like Nextcloud does.

**Comment by goiken** [comment]
Right that just worked ;-). Thx.

**Comment by kyrofa** [comment]
Ah, excellent!
