### ISSUE TITLE
Update nextcloud to v16

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/nextcloud-snap#972]

**Comment by kyrofa** [comment]
We haven't updated yet since core apps don't yet support v16. We're holding out for that. If you want to upgrade ahead of when we believe it's ready for everyone, use the `16/candidate` channel:

    $ sudo snap refresh nextcloud --channel=16/candidate

**Comment by Flobin** [comment]
Just out of curiosity (and sorry if this is not the proper place to ask): which core apps are not supported in v16?

And thank you for all your hard work, @kyrofa!

**Comment by robwent** [comment]
I'm curious about this too since the latest post about the new text app :)

**Comment by kyrofa** [comment]
End-to-end encryption, specifically: https://github.com/nextcloud/end_to_end_encryption/issues/108#issuecomment-506493816

**Comment by robwent** [comment]
Is that specifically the app 'Default encryption module'?
When I was looking for the text app that was one of the 3 that are disabled on my install.
So I should be good to go?

**Comment by kyrofa** [comment]
> So I should be good to go?

I offer no promises in a non-stable channel, but if it's working for you, go for it!

**Comment by robwent** [comment]
I'm just trying to understand if I have end-to-end encryption enabled as I see no app with that name.
If it's the default encryption module then when I check the details it says it can't be installed as I don't have server-side encryption enabled (It's off).
If that's the case, can I update without the issue you linked to?

**Comment by the-sane** [comment]
@robwent I believe it's specifically the [end-to-end encryption app](https://apps.nextcloud.com/apps/end_to_end_encryption), which is not installed by default.  The app's page lists it as an alpha and it is listed as "in testing phase" on the nextcloud website [here](https://nextcloud.com/endtoend/).

**Comment by robwent** [comment]
@the-sane thanks.
I'm going for it...

**Comment by kyrofa** [comment]
@robwent if you run into issues you're a simple `sudo snap revert nextcloud` away from safety!

**Comment by robwent** [comment]
Well, that was easy :)

    Version Cloud 16.0.1

Weirdly, the text folder in /extra-apps/ seemed to get deleted after the refresh but others I had previously installed are still there like notes and unsplash.
I now see a download and install button when I look in the apps area though and it installed without any issue.

Created a new text file in a folder and get the new editor.

Happy days.

Thank you @kyrofa @the-sane

**Comment by kyrofa** [comment]
Very good, @robwent. Keep an eye on when v16 is released to stable so you can refresh back (otherwise you won't get v17 when it comes out): `sudo snap refresh --stable nextcloud`

**Comment by robwent** [comment]
Noted, thanks @kyrofa

**Comment by kyrofa** [comment]
16.0.2 is out now, testing over at #1002.

**Comment by kyrofa** [comment]
Agh, 16.0.2 is broken for [other reasons](https://github.com/nextcloud/server/issues/16238).

**Comment by robwent** [comment]
I wasn't sure how to help with this?
I tried a stable refresh and went back to 15, so went to 16 again and all was fine.

I'm currently running 16.0.2 release candidate.

**Comment by kyrofa** [comment]
@robwent instructions are contained [here](https://github.com/nextcloud/nextcloud-snap/pull/1002#issuecomment-508595171), but no need to test it further at this point, there's no way we'll ship something that broken.

**Comment by kyrofa** [comment]
Even in 16.0.3, the calendar app is disabled upon upgrade. Still working on this. [This comment](https://github.com/nextcloud/nextcloud-snap/issues/972#issuecomment-495356382) still applies though, i.e. if you want to upgrade ahead of when we believe v16 is ready for everyone, use the `16/candidate` channel:

    $ sudo snap refresh nextcloud --channel=16/candidate

**Comment by kyrofa** [comment]
Just so folks know, we're no longer considering end to end encryption in our tests.

**Comment by Flobin** [comment]
>Just so folks know, we're no longer considering end to end encryption in our tests.

Any particular reason why? Just curious.

**Comment by kyrofa** [comment]
> Any particular reason why? Just curious.

Because [they've made it pretty clear](https://github.com/nextcloud/end_to_end_encryption/issues/108#issuecomment-514293627) that it's too early-stage to be considered an important feature, regardless of how much it was hyped.

**Comment by kyrofa** [comment]
Update: just waiting on this PR to land (and be released): https://github.com/nextcloud/server/pull/16753 . No other known blocking issues at this time.

**Comment by Flaburgan** [comment]
I see the PR you were talking about has been merged and you did the bump to 16.0.4, is there anything else missing to push that as the new stable? I'm eagerly waiting for it as the email app is deeply broken on 15.x and they said they [will not update it](https://apps.nextcloud.com/apps/mail) on that version.

**Comment by robwent** [comment]
Just to note. I just tried going back to the stable version and get an error message when I try to access the site:

`Downgrading is not supported and is likely to cause unpredictable issues (from 16.0.4.1 to 15.0.11.1) `

**Comment by kyrofa** [comment]
Indeed, upstream Nextcloud doesn't support downgrading. You can't refresh down major versions, you can only revert (thus picking up the database as it was in the old version).

**Comment by robwent** [comment]
> @robwent if you run into issues you're a simple `sudo snap revert nextcloud` away from safety!

I feel I was missold lol.

All good now anyway, I assume when the 16 snap is available I will still be able to move to the latest stable?

**Comment by kyrofa** [comment]
@robwent sorry, let me clarify. There are two operations to consider in this scenario: a refresh, and revert. I said you were a simple _revert_ away, and you _refreshed_, which is not the same.

Snaps (this is universal, not just to the Nextcloud snap) have unique revisions in the store. Let's say you're currently on revision X. When you refresh (update), you fetch the most recent revision (let's call it Y) and the following happens:

1. The data for X is copied and put into place for Y. This includes the database, SSL certs, pretty much everything except Nextcloud's raw data (it's too large to copy, thus it's stored elsewhere).
2. Y is mounted into place and given access to its data, which is really a copy of X's data, and its services are fired up. Importantly, X's data is still there, just not being used (snap data is held for three revisions).

Let's say X was v15, and Y was v16. When its services were fired up, it noticed that it needed to upgrade, so it did, running database migrations and whatnot, thus making the database not backward compatible with v15.

Now if you run `snap refresh nextcloud --channel=one-with-v15-in-it`, let's call it revision Z, snapd will go through this same process, making a copy of revision Y's data for revision Z and firing Z up. Well, Z knows it's v15 and has no idea what to do with your database, thus the error you saw.

What I said to do is run some rendition of `snap revert`, which would have moved you from revision Y _back to revision X_. This means you stop using revision Y's data and pick up revision X's data where you left off. That means you lose any data in Y's database (contacts added, apps enabled, etc.). Typically that's most useful if you upgraded to v16, immediately realized that it was broken, and ran `snap revert`. You've now been running v16 for quite a while, I suspect the data loss that comes with a revert would upset you at this point. You can still do it if `snap list nextcloud --all` still shows a v15 snap there by running `sudo snap revert nextcloud --revision=<the 15 one>`, but again, you'll lose any database modifications that you made while using v16.

**Comment by robwent** [comment]
Thanks for the excellent explanation!

I did actually try revert originally and that's what gave me the error message. Probably a good thing though as going back to the snapshot of the install 2 months ago might have been worse.
I'm guessing that going to the beta made whatever changes were needed to the database that I was getting prompted to do when trying to log in.

**Comment by kyrofa** [comment]
Alright, glad that resolved things.

> I assume when the 16 snap is available I will still be able to move to the latest stable?

Indeed, when this issue is closed and `snap info nextcloud` shows v16 in the stable channel, run `sudo snap refresh --stable nextcloud`. You'll upgrade to the stable release, and also start tracking the `stable` channel. Note that you will also be able to use `16/stable` if you prefer not to upgrade to v17 when it comes out.

**Comment by kyrofa** [comment]
Thanks to everyone who participated in the discussion, helped getting this done, and was generally very patient with the slow progress here. I know I for one remember the issue number by heart now :wink: . I'm pleased to say that 16.0.5snap1 is now in the stable channel and it rolling out to everyone.

**Comment by kyrofa** [comment]
By the way, if you've been hanging on `16/candidate`, you have two options:

1. Refresh to `16/stable`. Use this channel if you want to get all the v16 updates, but _not_ automatically update to v17. I hope you've seen how seriously we take breakage and trust that an automatic update to v17 will probably not break you, but this is a perfectly valid option if you want major version updates to be under your control.
2. Refresh to `stable`. Use this channel if you want to stay on the latest stable (stable in the snap sense, not in the Nextcloud sense, obviously) release. This will update you to v17 when it comes around.

The command to do that is:

    $ sudo snap refresh nextcloud --channel=<channel>

**Comment by Flaburgan** [comment]
Thank you for your work here. Upgraded to the 16 version was smooth, and I now have access to Mail v17 instead of 11! Thank you very much.

**Comment by robwent** [comment]
I did a `sudo snap refresh --stable nextcloud` and everything seems fine.

Thanks for all the info about how this works!
