### ISSUE TITLE
problem renewing lets-encrypt  

### ISSUE THREAD

**Issue by TinoS1964** [nextcloud/nextcloud-snap#979]
Ubuntu 18.04 LTS nexctcloud-snap 15.0.7

I'm rather a noob on linux

Like many others I also have a problem renewing the let's encrypt certificate.
Ip adres has not changed since the beginning.
ports 80 and 443 are not blocked by firewall
certifcates where working perfectly for about 4 months
this week they became invalid.

tried :

sudo nextcloud.disable-https
sudo rm -rf /var/snap/nextcloud/current/certs
sudo nextcloud.enable-https lets-encrypt

but nothing works.

_Failed authorization procedure. yourdomain.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://yourdomain.com/.well-known/acme-challenge/UpvZFrFXAINuo0Zf9cp52dbRTbyKPhG1EOXf9HzKOAA: Timeout during connect (likely firewall problem)
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: yourdomain.com
   Type:   connection
   Detail: Fetching
   http://yourdomain.com/.well-known/acme-challenge/UpvZFrFXAINuo0Zf9cp52dbRTbyKPhG1EOXf9HzKOAA:
   Timeout during connect (likely firewall problem)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided._

for the time being I now entered : 
sudo nextcloud.enable-https self signed

So now at least I can log in to the system, but I must have the let's encrypt certificate back.
Can anyone help me with this?

**Comment by kyrofa** [comment]
Do you have a reverse proxy in front of the snap?

**Comment by TinoS1964** [comment]
No I don't think so.
I have a router with mulpiple IP on WAN and a DMZ setting pointing the right public IP to my nextcloud server.

**Comment by TinoS1964** [comment]
Oh my GOD, stupid me !!
I put a translation in my DMZ settings translating port 80 into 1 on The LAN side 👎 

Thanks kyrofa , You put me on the right path 💯

**Comment by kyrofa** [comment]
Well, let's take a look at some logs. Please paste in the output from [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts).

I'm afraid if Let's Encrypt can't reach your server, the problem is very likely outside the snap, and there's not much we can do.

**Comment by TinoS1964** [comment]
I'll close this issue, have a nice day.

**Comment by kyrofa** [comment]
Ah! Very good, thank you for updating :) .
