### ISSUE TITLE
Ubuntu 19.04 Client not loading on startup

### ISSUE THREAD

**Issue by hjbleier** [nextcloud/nextcloud-snap#980]
Clean install of Ubuntu 19.04 Desktop
under the general settings tab, Launch on System Startup is checked.
but nextcloud client doesn't load and I got to launch it manually.
I installed it from the snap

**Comment by sizeur** [comment]
What is the output of the following command ?
# systemctl list-units |grep nextcloud

**Comment by hjbleier** [comment]
![Screenshot from 2019-05-02 08-54-30](https://user-images.githubusercontent.com/32180458/57088834-f5ca4680-6cb7-11e9-932c-877d6bc73547.png)

**Comment by kyrofa** [comment]
@hjbleier I'm sorry, this repo is for the _server_ snap, not the client. I'm not really sure the client snap is maintained these days, they completely switched repos.

**Comment by hjbleier** [comment]
I am sorry for the confusion I didn't know that this was for the server snap only.

my apologies
