### ISSUE TITLE
Nextcloud can't access /tmp/

### ISSUE THREAD

**Issue by tseegers** [nextcloud/nextcloud-snap#981]
Hi there,

I cannot access to my web interface anymore (i got a white page instead) and the all the logs related to nextcloud are showing an access problem with the folder /tmp/:

For example apache:

root@ns531084:/home/thomas# systemctl status snap.nextcloud.apache.service
● snap.nextcloud.apache.service - Service for snap application nextcloud.apache
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.apache.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-02 13:33:12 CEST; 13min ago
  Process: 20249 ExecStop=/usr/bin/snap run --command=stop nextcloud.apache (code=exited, status=0/SUCCESS)
 Main PID: 20307 (run-httpd)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/snap.nextcloud.apache.service
           ├─20307 /bin/sh /snap/nextcloud/10314/bin/run-httpd -k start -DFOREGROUND
           ├─20328 /bin/sh /snap/nextcloud/10314/bin/setup_nextcloud
           └─23612 sleep 1

mai 02 13:33:12 ns531084 nextcloud.apache[20307]: chmod: cannot access '/tmp/pids': No such file or directory
mai 02 13:33:12 ns531084 nextcloud.apache[20307]: chmod: cannot access '/tmp/sockets': No such file or directory
mai 02 13:33:12 ns531084 nextcloud.apache[20307]: mkdir: cannot create directory '/tmp/pids': No such file or directory
mai 02 13:33:12 ns531084 nextcloud.apache[20307]: mkdir: cannot create directory '/tmp/sockets': No such file or directory

But i got the same error message for mysql:
mai 02 13:03:05 ns531084 nextcloud.mysql[12197]: touch: cannot touch '/tmp/locks/mysql-setup': No such file or directory
mai 02 13:03:05 ns531084 nextcloud.mysql[12197]: mkdir: cannot create directory '/tmp/pids': No such file or directory

And even using the occ command line return me a problem with /tmp/ :(
root@ns531084:/home/thomas# /snap/bin/nextcloud.occ --help
mkdir: cannot create directory '/tmp/pids': No such file or directory
mkdir: cannot create directory '/tmp/sockets': No such file or directory
chmod: cannot access '/tmp/pids': No such file or directory
chmod: cannot access '/tmp/sockets': No such file or directory
mkdir: cannot create directory '/tmp/pids': No such file or directory

The rights set on /tmp are as followed:
root@ns531084:/home/thomas# ls -lah /
[...]
drwxrwxrwt  67 root root 4,0K mai    2 14:00 tmp
[...]

And in my /tmp/ i don't have anything special:
root@ns531084:/home/thomas# ls -lah /tmp/
total 77M
drwxrwxrwt 67 root     root     4,0K mai    2 14:02 .
drwxr-xr-x 22 root     root     4,0K févr. 21 14:11 ..
-rw-r--r--  1 root     root     1,5K mai    2 14:02 cpu_stats
drwxr-xr-x  2 root     root     4,0K févr.  7 16:17 DEBIAN
[...]
-rwxrwxrwx  1 www-data www-data    0 janv.  2 13:05 .p
drwxr-xr-x  3 plex     plex     4,0K mai    1 20:46 pms-422740c7-2b5d-4fc2-b3d1-ff29b110f9fa

Other tools such as plex are installed on the server and seems to work fine, only nextcloud is affected :(

I have tried to restart the snap but it didn't help (root@ns531084:/# snap restart nextcloud). Of course creating the file manually in /tmp/ doesn't help. I suspect an important file would have been deleted  from /tmp/ but i don't know what.
My umask is set as 0022
root@ns531084:/# umask
0022

**Comment by tseegers** [comment]
I succeed to solve the problem, a restart of the next cloud snap was not enough, if some one as the same the same problem proceed like this:

snap stop nextcloud
systemctl stop snapd.service
systemctl start snapd.service
snap start nextcloud

Still i have no idea where the problem came from 😕

**Comment by ash-ishh** [comment]
In my case nextcloud and snapd restart did not solve the issue but system reboot did
It repopulated the deleted tmp files which were mounted inside nextcloud snap installation

If someone is looking for the files which were mounted in /tmp of nextcloud snap in version 19.0.0.12 to try remapping without reboot then you can create

```
/tmp
# ls -lah | grep snap
drwx------  3 root     root     4.0K snap.nextcloud

/tmp/snap.nextcloud
# ls -lah
drwxrwxrwt  5 root root 4.0K tmp

/tmp/snap.nextcloud/tmp
# ls -lah
drwxr-x--- 2 root root 4.0K locks
drwxr-x--- 2 root root 4.0K pids
drwxr-x--- 2 root root 4.0K sockets
```

\# snap run --shell nextcloud.occ
```
# cd /tmp
# ls -lah
drwxr-x---  2 root root 4.0K locks
drwxr-x---  2 root root 4.0K pids
drwxr-x---  2 root root 4.0K sockets

```

**Comment by ash-ishh** [comment]
I had to reboot the server.

I listed the three missing files `locks` `pids` and `socket` with their location and permission in case someone wants to recreate them for trying to resolve the issue just by restarting the service instead of whole system reboot.

I did not try it at that time since I did not know the exact location of missing files, that is why I am not sure if it will work or not.

If in your case system reboot is a concern you can give file recreation and restarting the service a shot, otherwise system reboot can be the last resort which might solve the issue.

**Comment by ash-ishh** [comment]
* Just a minor corrections all three are directories.

**Comment by ash-ishh** [comment]
Just a minor correction, all three are directories not files.

**Comment by iulianraduat** [comment]
In my case, the location of `tmp` folder for `nextcloud` was `/tmp/snap-private-tmp/snap.nextcloud/tmp/`.
