### ISSUE TITLE
https connection dropped when using letsencrypt

### ISSUE THREAD

**Issue by hurelhuyag** [nextcloud/nextcloud-snap#993]
I have installed nextcloud snap package on ubuntu 18.04. looks working fine over http. But I need https. And I executed `nextcloud.enable-https letsencrypt`. Now connection keeps failing.

how to reproduce:
1. install minimal ubuntu 18.04 
2. $ apt install snapd fuse 
3. $ snap install nextcloud
4. $ nextcloud.manual-install user password
5. $ nextcloud.enable-https letsencrypt
6. use nextcloud over https. after few refresh can't connect to nextcloud

**Comment by kyrofa** [comment]
Can you please paste in the output from [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)?

**Comment by hurelhuyag** [comment]
I reinstalled and configured using web interface and configured smtp email sender. No it is working fine.

**Comment by luixxiul** [comment]
Closing as the issue is not experienced already.
