### ISSUE TITLE
Why not use Apache, PHP and MySQL already in place?

### ISSUE THREAD

**Issue by jfha73** [nextcloud/nextcloud-snap#994]
Hey guys,

I just installed NextCloud using snap to a test server and noticed that it has its own Apache, PHP, MySQL and others, why not use the already in place Apache, PHP, MySQL, etc?

After I saw that, I think I will go with the zip file from the website and use the already in place Apache 2.4, PHP 7.2, MySQL 5.7, etc. as I don't want to break the website in the production server that's already using Apache 2.4, PHP 7.2, MySQL.

Just a suggestion, I don't know how snap works, but if you can add those packages as requirements and have snap install them if they are not installed, instead of put its own in place, it would be much better.

Thanks,

**Comment by kyrofa** [comment]
Thanks for the recommendation, @jfha73! However, if you already have all those pieces in place, you really have no need for the snap. It's intended to be a standalone appliance that takes care of itself (including anything it requires, updating automatically, etc.). In your situation, that's indeed not what you want. It is, however, perfect for folks who don't have the knowledge, desire, or requirement to already have all those pieces in place.
