### ISSUE TITLE
Ubuntu Core 18 (release only snap) root permissions?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/nextcloud-snap#996]
Ubuntu has released the ubuntu core 18 version for iot and pc devices.

this version is characterized by the fact of using only the snap packages, there is no apt environment.

I ask you experts how you can manually edit the nextcloud config.php file in an ubuntu snap environment.

is there any text editor snap that you can use to have root privileges and to access 

`/var/snap/nextcloud/current/nextcloud/config/config.php`

there is no traditional nano command I repeat. only snap. ubuntu core is like that.

does anyone have any ideas?

**Comment by kyrofa** [comment]
Try `vi`.

**Comment by tigernero79** [comment]
ok thanks, too bad there is not a text editor snap package that allows to have root privileges to be able to modify config.php file.  for I had tried but too old and I have to understand how to use it.  development environment you mentioned concerned Ubuntu core 16. for Ubuntu core 18 does not work well.  I can edit with nextcloud.occ.  would need a nice Wiki containing all the commands to use.  terminal text help does not explain well.

**Comment by kyrofa** [comment]
The snap developers didn't create `occ`, that's an upstream Nextcloud tool. Documentation is [here](https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html).
